### ISSUE TITLE
Monument historique sans ref:mhs ou invalide

### ISSUE THREAD

**Issue by lenny31** [osm-fr/osmose-backend#100]
error "Monument historique sans ref:mhs ou invalide"
http://osmose.openstreetmap.fr/fr/map/#zoom=17&lat=43.3984882&lon=-0.9392721&item=7080&level=3

**ref:mhs is present**  -> ref:mhs = IA64000741

**and ref:mhs is valid** http://www.culture.gouv.fr/public/mistral/mersri_fr?ACTION=CHERCHER&FIELD_1=REF&VALUE_1=IA64000741

**Comment by frodrigo** [comment]
It's an IA an "inscrit", but we have only the list on PA "classé"
Maybe you look at or anywhere to get the IA list https://www.data.gouv.fr/fr/search/?q=
Nevertheless we can update PA list of Osmose.

**Comment by frodrigo** [comment]
In fact we can fix the merge analyser
* `heritage=2` is for PA
* `heritage=3` is for IA

**Comment by lenny31** [comment]
désolé, mais j'ai du mal à m'exprimer en anglais, je continue donc en 
français

J'avais mis "heritage=2" car dans la fiche du monument
http://www.culture.gouv.fr/public/mistral/mersri_fr?ACTION=CHERCHER&FIELD_1=REF&VALUE_1=IA64000741

il est écrit "protection MH 1912/07/08 : _classé MH_"
J'ai pensé qu'il était classé

et comme dans le wiki, il est écrit "généralement /PA/  ..."

en cherchant dans le lien que vous m'avais donné plus bas, j'ai trouvé 
une nouvelle page pour la même église avec la référence PA00084526

et la j'ai vu qu'à "IA..." il y avait une ligne "© Inventaire général"
alors qu'à "PA..."                                            © 
Monuments historiques, 1992

C'est bien une erreur de saisie de ma part, je corrige osm en mettant la 
bonne référence
---
Je suis allé voir des monuments avec "heritage=3"
http://www.culture.gouv.fr/public/mistral/mersri_fr?ACTION=CHERCHER&FIELD_1=REF&VALUE_1= 
PA00094630
J'ai trouvé sur la fiche "© Monuments historiques, 1992"
Il devrait donc être "heritage=2" ?

cordialement
lenny

**Comment by frodrigo** [comment]
> Il devrait donc être "heritage=2" ?
Je ne suis plus sûr, j'avais d'ailleurs supprimé mes commentaires.

**Comment by lenny31** [comment]
Je ne comprends pas très bien à quoi se rapporte ton commentaire ?

C'est sûrement de ma faute car j'ai fait précédemment référence à deux objets : 
1- celui qui a fait l'objet de mon signalement à tord : http://www.openstreetmap.org/way/297558139
pour lequel j'expliquais mon erreur (il existe dans Mérimée avec deux références IA et PA), j'ai modifié OSM avec "ref:MHS=PA..." - Osmose ne le détecte plus.

2- Pour bien vérifier que j'avais compris, je posais la question sur un monument qui a "heritage=3" http://www.openstreetmap.org/way/166106355 et vu la fiche Mérimée, je demandais s'il ne devrait pas passer en "heritage=2"
