### ISSUE TITLE
False positives for maxspeed on suspicious object (waterways) item=9001 class=9001002 

### ISSUE THREAD

**Issue by AdVerburg** [osm-fr/osmose-backend#1000]
According to https://wiki.openstreetmap.org/wiki/Key:maxspeed?uselang=en maxspeed=* on a waterway is a valid tag.
However with waterway=**fairway** these are marked as "maxspeed on suspicious object"  see: http://osmose.openstreetmap.fr/en/map/#username=AdVerburg&zoom=10&lat=52.0039&lon=4.801&item=9001&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/error/1a223e5b-3eee-dc5c-28ee-8dc4bd37162c

item | 9001
-- | --
class | 9001002

It is from JOSM validator.

https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
issue #1000 fixed :)

https://josm.openstreetmap.de/changeset/17175

**Comment by AdVerburg** [comment]
Alas, just noticed a bunch of "suspicious tag combination" on fresh (yesterday) added fairways. See:  http://osmose.openstreetmap.fr/en/map/#username=AdVerburg&zoom=16&lat=52.3606&lon=4.96961&item=9001&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
Please wait, the fix is still only on JOSM code side, not yet imported on Osmose, and then need deployment on server, then data refresh.
