### ISSUE TITLE
International routes : Default and local language name not the same

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-backend#1001]
I've noticed that international routes, like line buses, are marked with many errors "Default and local language name not the same"

For example the Bus route (From Paris to Madrid) https://www.openstreetmap.org/relation/10983560, goes through France an Spain all they way.

It's "name" and "name:fr" have the same value
name | Flixbus N1793: Paris, Bercy Seine => Madrid, gare routière sud
-- | --
name:fr |Flixbus N1793: Paris, Bercy Seine => Madrid, gare routière sud

But all these errors came up:

- http://osmose.openstreetmap.fr/en/error/e14dbf67-80cd-5cf8-f594-db43a6e14a1d
- http://osmose.openstreetmap.fr/en/error/96a8ae69-30fb-3bbc-280c-24c2c2a45a11
- http://osmose.openstreetmap.fr/en/error/980114f1-ee38-4893-2f21-45f1e8f1722d
- http://osmose.openstreetmap.fr/en/error/734d5ee9-638f-399b-276f-fc304db3ca90
- http://osmose.openstreetmap.fr/en/error/a25e6046-e23d-6732-61f2-4b358259b3c7

Which language is good for the validator? how can we manage a route goes by multiple countries?

**Comment by frodrigo** [comment]
Duplicate #353
