### ISSUE TITLE
name proposed is badly written

### ISSUE THREAD

**Issue by lenny31** [osm-fr/osmose-backend#1002]
- "arrêt TransGironde mis à jour - arrêt TransGironde de BORDEAUX - Av. d'Eysines"
- item 8042 
- class number node/2735054116
- http://osmose.openstreetmap.fr/fr/error/8cb98b8b-f8c9-c30a-a491-fbe0dd72fbfd

Propose "name = **Avenued'Eysines**" which is an anomaly in relation to the existing "name = **Avenue d'Eysines**"

**Comment by frodrigo** [comment]
It is the data from the external open data set. Just mark it as false positive.

**Comment by lenny31** [comment]
May be I make a mistake, but when I open the stops.txt in the gtfs https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-gir-nva-m/
I do not found Avenued'Eysines

**Comment by frodrigo** [comment]
The current data source is https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-de-transport-cg-33-transgironde/ from 2018.

**Comment by lenny31** [comment]
Ok, in your data source link I download the zip "Horaires théoriques Transgironde - lignes régulières (copie GTFS)" : https://static.data.gouv.fr/resources/horaires-theoriques-du-reseau-de-transport-cg-33-transgironde/20180423-150005/download_CD33_GTFS_lignes_reg.zip and I do not found "Avenued'Eysines" but "Av. d'Eysines" as written in the osmose tittle

**Comment by frodrigo** [comment]
Good point. Found a missing space in the small transcript included in this analyser.
