### ISSUE TITLE
False positive : Unmatched voltage of line on substation

### ISSUE THREAD

**Issue by flacombe** [osm-fr/osmose-backend#1006]
Dear maintainers,

There are some false positives regarding the powerline analysis 7040 class 7
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_powerline.py#L361
http://osmose.openstreetmap.fr/fr/error/c34e23c4-e553-f1d0-6b7a-9a0eff3cdcc6

Osmose thinks the northern extremity of this power line https://www.openstreetmap.org/way/139834745 isn't consistent with the voltage of a power substation crossed by the line
https://www.openstreetmap.org/way/105783300

Given problem of this analysis is it doesn't consider if line stops in the substation or not.
A possible solution is to look for untagged nodes connecting lines to substation's bays. They accurately mean that the voltage of the line should be found in the substation description.
Example : https://www.openstreetmap.org/node/1356819097

Looking for power lines extremities won't bring expected results : it doesn't mean the power line is connected to anything in the substation. Lines can only stop there with dead end.

Furthermore, following continuous discussions regarding voltages and ;-values prevention, I use to tag now substations with highest voltage only. Practices may differ in different areas.
Then I think the analysis should only check if the substation's voltage where the lines are connected in is >= to the line voltage only.

This is not urgent to fix, this issue is written to keep a record about such flase positive.

All the best

**Comment by frodrigo** [comment]
The current check is https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_powerline.py#L300

Check for substations within 30m of the end of the line. Was made on an epoch were power was done with less description. But I think there is still low details mapped grid over the world. This check the "connection" of the line with the substation, not other part of the network.

Your case may be unfrequented, maybe just mark it as false positive?

**Comment by flacombe** [comment]
Thank your @frodrigo 

The situation is Eguzon is valid regarding the 30m distance
![image](https://user-images.githubusercontent.com/5690599/96383643-fd71f980-1190-11eb-8ee9-49c1c59dab21.png)

A quick fix would be removing the 30m tolerance and look for line ends in the substation polygon, strictly.

Qualifying line ends with connection to any line=bay + power=line would be useful as well.

**Comment by frodrigo** [comment]
Removing the buffer look reasonbale.
http://osmose.openstreetmap.fr/en/errors/?item=7040&class=7

But, first can you have a look at Ireland, since there is lot more issue in this country than others.

**Comment by flacombe** [comment]
1154 Ireland's errors sounds to be related to such situations
https://www.openstreetmap.org/way/622146538

lines coming with voltage=low but substation only have voltage=38000
voltage:primary and voltage:secondary won't apply there and should be restricted power=transformer or transformer=* objects.

voltage=38000 isn't wrong on this substation as it seems to be the highest voltage.
That's why check should consider line_voltage <= substation_highest_voltage

**Comment by deuzeffe** [comment]
@frodrigo vu que @jocelynj a poussé tes modifs en prod., je peux passer les signalements à faux-positif (c'est moi qui ai alerté @flacombe) et le ticket peut être fermé ?

**Comment by frodrigo** [comment]
No. This one was made after the last deployment.

**Comment by frodrigo** [comment]
My bad, was deployed yesterday.

Now only 3 000 issues in place of 14 000.

@deuzeffe what kind of false positive do you still have?

**Comment by deuzeffe** [comment]
@frodrigo plus aucun faux-positif depuis le déploiement du correctif ;)

**Comment by flacombe** [comment]
That's really good in France, thank you !
