### ISSUE TITLE
Associated street check should also look for 'place' or 'locality'

### ISSUE THREAD

**Issue by habi** [osm-fr/osmose-backend#1007]
In Switzerland we have quite a bunch of adresses mapped which don't have an associated street.

[The check here](https://github.com/osm-fr/osmose-backend/blob/2122e7776aa73d879ba9534d108aaf8328c29d34/analysers/analyser_osmosis_relation_associatedStreet.py#L648) complains about that.
[Here's an example](http://osmose.openstreetmap.fr/en/map/#zoom=16&lat=46.62177&lon=7.37978&item=2060&level=2&tags=&fixable=) of a small region where Osmose complains *a lot* :smiley: 

It would be great if the check could also account for `place=locality` or `place=village` in the vicinity.

I have *no* idea how to implement it, but would try to start with a PR if someone is willing to to do some hand-holding...

**Comment by frodrigo** [comment]
But `addr:street` is for a street, use `addr:locality` in place.

**Comment by habi** [comment]
> But `addr:street` is for a street, use `addr:locality` in place.

I wasn't aware of that, thanks for pointing that out.

But that means changing the tags in literally thousands of POIs and building adresses all around (the remote areas of) Switzerland, which is something I'm going to refrain from.

**Comment by frodrigo** [comment]
My bad, is not addr:locality but addr:place.

**Comment by habi** [comment]
This error popped up again today, on a different POI: http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=47.514267&lon=7.779886&item=2060&level=2&tags=&fixable=

The thing is that in Switzerland, there's no way to know if `addr:street` or `addr:place` is correct.
In this case the POI gives 'Egghof' as address on its website: https://egghof-kunz.ch/kontakt.htm

Could the check be tweaked that it also looks for the `place` nearby?

**Comment by Marc-marc-marc** [comment]
> The thing is that in Switzerland, there's no way to know if `addr:street` or `addr:place` is correct.

"real live" doesn't have the info, but osm have it  like in other country : 
if it's the name of a ihghway=*, then it's a addr:street
if it's the name of a place=*, then it's a addr:place
maybe the analyse could be improved to add a fix addr_street -> addr:place if a place if found nearby with the same name

**Comment by habi** [comment]
> maybe the analyse could be improved to add a fix addr_street -> addr:place if a place if found nearby with the same name

Thanks for describing exactly what I had in mind but was not able to figure out in words :)
