### ISSUE TITLE
highway=livingstreet and maxspeed>20km/h

### ISSUE THREAD

**Issue by WeftWiki** [osm-fr/osmose-backend#1008]
The living_street [tag page](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street#National_specialities) on the wiki lists the maxspeed limit known worldwild. 
No maxspeed limit above 20km/h is known.
Osmose could detect inconsistency such as highway=livingstreet and maxspeed=50 (ex : [688984614](https://www.openstreetmap.org/way/688984614))

**Comment by frodrigo** [comment]
@Klumbumbus interested to have this rule in JOSM ?

**Comment by Klumbumbus** [comment]
Added to JOSM in https://josm.openstreetmap.de/changeset/17247

**Comment by frodrigo** [comment]
Thank you

**Comment by Klumbumbus** [comment]
Little adjustment in https://josm.openstreetmap.de/changeset/17253
