### ISSUE TITLE
Small highway group apart from the main network or with insufficient access upstream

### ISSUE THREAD

**Issue by craigallan** [osm-fr/osmose-backend#1010]
Hello Reader,
This issue is about a principle, a decision about in setting the tags.  For reference, here is one tag:

32740
-- | --
item | 1210
class | 4
lat lon | 0.6107877 21.2297913
 fr | Petit ensemble de voiries séparées du réseau principal ou avec des accès insuffisants

Problem 1: The analyser is tagging roads that *DO* connect to the main road hierarchy, but do not do so fast enough to keep the analyser happy. The area shown in the link below is a network of small tracks in dense jungle, but I can manually trace all the roads through the network to the nearest higher grade road.  Your system can also do that trace, and probably it does succeed, but at some point it gets bored and just flags everything after its boredom cut-off point as being an ERROR.   False positive. Please do not apply European standards to the Democratic Republic of the Congo. 

Please see here:  https://osmose.openstreetmap.fr/en/map/#item=1210&zoom=12&lat=0.5288&lon=21.3248&level=1&tags=&fixable

===================

Problem 2: The analyser is tagging small clusters of roads that serve river bank communities as a local transport group. This is quite correct as the roads *DO NOT* have sufficient access upstream. They DO NOT connect at all to a main road hierarchy.  The communities are served by the RIVER as their major transport route. There is no way to reach these communities by a road route.  But, it is a false positive. The river-bank roads are not an ERROR.   In a way, they are like an island in an ocean.  A ocean of trees. You don't trigger connection errors on small islands, but in this area you flag hundreds of false positives.    Please do not apply European standards to the Democratic Republic of the Congo.  

Please see here:  https://osmose.openstreetmap.fr/en/map/#item=1210&zoom=14&lat=-0.62497&lon=17.78866&level=1&tags=&fixable=

best wishes
Craig Allan

**Comment by frodrigo** [comment]
Problem 1

Look at this. It is really not connected.

Problem 2

For network from sea or river add pier for example.

All of this are considered as seed for the network: https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_floating_islands.py#L37-L46
