### ISSUE TITLE
false positive on mapillary image detector - cycle infrastructure is tagged already

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1011]
http://osmose.openstreetmap.fr/pl/error/90514ca3-8c94-2d44-ba19-d4ce5392b0a5

OSM way with `cycleway:left=opposite_lane` and `oneway:bicycle=no` https://www.openstreetmap.org/way/25367091
![screen](https://user-images.githubusercontent.com/899988/97068659-e33d7e80-15c9-11eb-8f73-152ce558a04d.png)

**Comment by frodrigo** [comment]
Suggest missing tags https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json#L1876

**Comment by matkoniecz** [comment]
Does ` "highway": null,` mean "any value of highway"?

**Comment by frodrigo** [comment]
> Does ` "highway": null,` mean "any value of highway"?

Yes

**Comment by matkoniecz** [comment]
I would add values `opposite`, `opposite_lane` in keys `cycleway`, `cycleway:left` and `cycleway:right`. Adding such values in `cycleway:both` seems not needed.

Also, `lane` in `cycleway`, `cycleway:left`, `cycleway:right` and `cycleway:both`.


I would recommend this as the image processing is quite poor and catches also cycleway signs denoting lanes (and white text on blue shops signs and logos of motorway payment scheme in Poland - but that is harder to avoid false positives in such cases :) )

**Comment by Famlam** [comment]
Ehm, may I vote against this?

Lane is significantly different from tracks, to my knowledge not signposted normally. The sign pictured seems to be a clear false positive detection of Mapillary.

(Also, cycleway:left/right=opposite_* has no meaning)

**Comment by Famlam** [comment]
It might be more convenient to teach Mapillary about those False Positives. Did something similar for NL a while ago.

**Comment by frodrigo** [comment]
I prefer avoiding false positives by making more matching than necessary. It also should be tolerant to alternative and old mapping rules (like cycleway:left/right=opposite_*).

**Comment by Famlam** [comment]
Perhaps it's possible to exclude a.o. The Netherlands from these oneway exceptions then? Almost all our residential roads have oneway-exclusions, and since these connect to the roads with tracks...

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=8470
Update in progress

**Comment by masterofnoroad** [comment]
Including highway=* + bicycle=designated results in not showing erroneus tagging: highway=footway + bicycle=designated (this combination is not treated as cycleway in most routing engines

**Comment by frodrigo** [comment]
@masterofnoroad bad tag combination should be deal in other analyser, like this one
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Bicycle.validator.mapcss
Please, open new issues for that.

**Comment by matkoniecz** [comment]
Note https://josm.openstreetmap.de/ticket/17901 https://josm.openstreetmap.de/ticket/9250 and related issues and commits.

JOSM started to complain about `highway=footway + bicycle=designated` (after my request), in the end it was reverted as it was considered as a valid tagging.
