### ISSUE TITLE
fuel station integration

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1017]
Reported by Bernard59118

I have updated many stations but I'm wasting time integrating already integrated stations.

- 1 - the tag "ref:FR:fuel prices" has changed, probably due to a change of manager, same sign, be careful, there can be a change of sign; but the station exists with the tag "ref:FR:fuel prices".

- 2 - it happens that some closed stations remain in the file of "https://www.prix-carburants.gouv.fr/" but without the tag "fuel".

- 3 - it would be interesting to have on the Osmose tab all the information present on the ".gouv".
    - Non-integrated gas station 
AUTOROUTE A6, Saint-Albain , on Osmose
    - ALCANE GESTION | Shell
Autoroute a6
71260 Saint-Albain , on ""https://www.prix-carburants.gouv.fr/"" "".

**Comment by frodrigo** [comment]
@PanierAvide the ref was not initially integrated, but you do it. Do you still thing the ref is enough stable?

Stations with no more fuel can be filtered.

Report all fields maybe a lot, but we can add more.

**Comment by PanierAvide** [comment]
I'm not sure to understand why it may not be stable enough. This ID is stable in a way that if a station is at the same place, managed by same company, its ID will stay identical. Looks fairly stable to me.

**Comment by Bernard59118** [comment]
Il y a un turnover important dans la gestion des stations-service, notamment chez carrefour. La station reste mais le gérant change. D'où un changement de référence. L'affichage des informations sur osmose, présentent sur le site prix carburants. Gouv faciliterai l'intégration..

**Comment by frodrigo** [comment]
@Bernard59118 pour rajouter des champs c'est facile, peux tu donner ceux que tu aimerais  voir en plus ? Depuis le fichier de @PanierAvide ou d'autres depuis les données d'origine ? 
https://files.pavie.info/depot/remote/carburants_gouv.geojson

**Comment by Bernard59118** [comment]
dans le fichier joint, je n'y vois pas les informations présentes sur le site 
https://www.prix-carburants.gouv.fr/recherche/ 
à savoir
CARRREFOUR MARKET | Carrefour Market .................................absent (intéressant pour vérification changement enseigne ou de gérant)
Creis er prat    ............................. présent OK
56240 PLOUAY...............................présent OK

**Comment by frodrigo** [comment]
L'enseigne n'est pas disponible dans les données OpenData.
