### ISSUE TITLE
Tag on train stop and relation route=train

### ISSUE THREAD

**Issue by Percherie** [osm-fr/osmose-backend#1018]
Hello,

I am currently updating the train lines around Narbonne and I have been confronted with the management of the two public transport models PTv1 (old model) and PTv2

Strictly applying the JOSM "Relation Checker" validation if a node having the "stop" role in a road=train relation having "public_transport:version=1", this node must have the tag railway=station (seen on the 2012 archives of the wiki where a station must be placed in each direction)

This is very disturbing with the PTv2 model where only one station has to be placed (next to the stops) and the stop has to have railway=stop.

Is it possible to add an Osmosis control to pass stops to the PTv2 model when all relationships are equally so?

Detail of the condition for switching stops to the PTv2 model:

    Node search with tag railway=station
    Checks if in a relation road=train + ( public_transport:version=1 OR public_transport:version!=* )
    If in no relationship in PTv1
    Replacement by railway=stop

Detail of the condition for backwards compatibility to the PTv1 model;

    Search relation road=train + ( public_transport:version=1 OR public_transport:version!=* )
    Node search with tag railway=stop
    Replacement by railway=station
    Add info (to explain the process) note=stop is in PTv1 relation for use railway=station, please update all relation route=* to PTv2

**Comment by frodrigo** [comment]
cc @nlehuby

**Comment by nlehuby** [comment]
I think there is a confusion here because `railway=station` and `railway=stop` does not represent the same objects: 
`railway=station` represents the station whereas `railway=stop` are the points where the trains stop in the station. So we shouldn't switch the `railway` tag  from `station` to `stop` 
See : 
- https://wiki.openstreetmap.org/wiki/Railway_stations
- https://wiki.openstreetmap.org/wiki/Tag:railway%3Dstop

**Comment by Percherie** [comment]
I am aware of this and what I wrote earlier is a deduction of errors reported by the JOSM validator.
I assume that a validator used by so many contributors contains very few errors on old tags.

If a relationship is in PTv1 format, the tag railway=stop is refused and only railway=station is accepted.
Not having understood why I consulted the old version of the page railway=station when PTv1 was very often used: https://wiki.openstreetmap.org/w/index.php?title=Tag:railway%3Dstation&oldid=820397

Currently on the railway=station page, only the PTv2 model is discussed, otherwise I would have refrained from searching in the archives.

Make a test with JOSM by creating (without sending it) a relation in PTv1 format with a stop having railway=stop.

Translated with www.DeepL.com/Translator (free version)

**Comment by nlehuby** [comment]
> the tag railway=stop is refused and only railway=station is accepted.

It is not about the tags, it is about the objects with the tags. 

In my understanding, making the conversion from `public_transport:version = 1` to `public_transport:version = 2` is not about changing the tag on the objects that already are in the relation, but changing the objects in the relation : removing the `railway=station` object and putting instead the `railway=stop` node

With that in mind, I don't think Osmose should suggest any switching of tags

**Comment by Percherie** [comment]
Okay, I'm starting to understand. Probably the PTv1 relationships did not strictly follow the model. It misled me

From your feedback I assume that in PTv1 only the station next to the tracks must be present and not the nodes used in PTv2 which represent the location of the train stop.

Is this correct? In this case I will take the necessary steps to correct what I have tagged incorrectly

**Comment by Percherie** [comment]
Depending on the answer I have an additional question

**Comment by frodrigo** [comment]
I close it, but you can still talk here.

**Comment by nlehuby** [comment]
> From your feedback I assume that in PTv1 only the station next to the tracks must be present and not the nodes used in PTv2 which represent the location of the train stop.
> Is this correct?

Yes, I think so. But I also think that we had a PTv2 because PTv1 was not clear and formalized enough so I'm not surprised if you can find stations in some PTv1 train route relations and/or stop in others...
