### ISSUE TITLE
Missing road

### ISSUE THREAD

**Issue by operon** [osm-fr/osmose-backend#102]
For the France, is exist 7170 test, use INSEE.
You can use BAN and BANO File for test :
If numberhouse exist then road exist (100m) else osmose issue.

This test can use for world if open file numberhouse exist

**Comment by frodrigo** [comment]
A test like this one was already made and removed cause of too much computation time.
The main difference with 7170 is the usage of a grid and not a distance. Maybe done using a grid in local projection and check for buildings or addresses vs highway. But this is interesting where data are imported or addresess open data set is available.
