### ISSUE TITLE
amenity=shelter highway=bus_stop should not trigger " Conflict between tags: amenity, highway"

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1020]
I see no reason to trigger validator warning here. There is even `shelter_type=public_transport`.

(yes, I prefer `shelter=yes` tagging but I would not describe this variant as bad enough to trigger QA complaint marked as important)

item: 4030
class: 900

http://osmose.openstreetmap.fr/en/error/94227934-1392-b7fb-caaa-a2d7af9a3fbf

http://osmose.openstreetmap.fr/en/map/?#zoom=16&lat=54.40435&lon=16.37372&item=xxxx&level=1&tags=&fixable=

http://overpass-turbo.eu/s/ZCQ

**Comment by frodrigo** [comment]
cc @nlehuby

**Comment by nlehuby** [comment]
I would also prefer `shelter=yes` but I agree : this kind of mapping should not trigger an error.
