### ISSUE TITLE
Complaints about a 'disc_golf' course

### ISSUE THREAD

**Issue by habi** [osm-fr/osmose-backend#1026]
A while ago I added a [disc_golf](https://wiki.openstreetmap.org/wiki/Disc_golf) course to OSM: https://www.openstreetmap.org/relation/10224469
OSMOse complains that single holes are `Untagged named object`s: https://github.com/osm-fr/osmose-backend/blob/f9086b23e4e3c6f21ea30354c782d8a3e50d0a81/plugins/TagFix_MultipleTag.py#L64

I *think* that I need to add a `sport=disc_golf` tag to the course or holes to stop OSMOse from complaining, or could I update the `TagFix_MultipleTag.py` somehow to help with this 'complaint'?

**Comment by frodrigo** [comment]
It expects one of the main tags
https://github.com/osm-fr/osmose-backend/blob/f9086b23e4e3c6f21ea30354c782d8a3e50d0a81/plugins/TagFix_MultipleTag.py#L31

**Comment by habi** [comment]
> It expects one of the main tags

So, adding `sport=disc_golf` to the 'holes' is the correct way of fixing this issue?

**Comment by frodrigo** [comment]
Yes on `disc_golf=hole` objects.
