### ISSUE TITLE
8300: Adding traffic_sign as Key

### ISSUE THREAD

**Issue by britiger** [osm-fr/osmose-backend#1028]
The tags for correction should also contain the Key `traffic_sign=*`. While using JOSM for fixing missing `maxspeed` the validator detect the missing tag `traffic_sign=maxspeed` this should be added to the suggestion of correction.

**Comment by frodrigo** [comment]
Please can you give more detail, example and/or a link.

**Comment by britiger** [comment]
Example:
http://osmose.openstreetmap.fr/de/error/7f37bb9e-0d93-18f2-7c8a-edc22c459267

Here was detected a traffic sign with maxspeed=60 within mapillary.
The suggested tags for a new node are:
```
mapillary=agTz5dDgh0YW52VRsUthpQ
maxspeed=60
source=Mapillary Traffic Signs
survey:date=2019-07-24
```
after adding these tags to a node there are no primary tag. You only have maxspeed as information but no kind of "object". The node should be also tagged with `traffic_sign=maxspeed` to identify the node as a traffic sign. maxspeed is also possible on an enforcement with `highway=speed_camera` for nodes.

If you fix an 8300 error with maxspeed in JOSM you get a warning "suspicious tag combination"
This should be this line: https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss#L416

In my opinion the warning in JOSM is correct.

**Comment by frodrigo** [comment]
It is not indented to be used in this way.

The node created by josm-fix must by deleted, it is only useful to help locate the issue. Then you must copy the tags on ways.
