### ISSUE TITLE
3240 route access mismatch

### ISSUE THREAD

**Issue by DinoM65** [osm-fr/osmose-backend#1031]
Hi, i report these errors related to an inaccessible hiking route.
In the mountains, for safety reasons, the routes (path, [via ferrata](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dvia_ferrata) or track) can be closed by the CAI or public authorities; consequently, by mapping, on the highway (path, track, via ferrata)  set "access=no" and the relative "route=hiking" "state=closed" (see [CAI Percorsi escursionistici](https://wiki.openstreetmap.org/wiki/CAI#Percorsi_escursionistici). These two conditions ("access=no" and "state=closed") should prevent GPS navigators from selecting dangerous and therefore closed tracks, paths or via ferratas as a route. The check performed by osmose seems to ignore the state=closed value placed in the route=hiking. The following table is a list of errors that do not take into account the two conditions, used on the highway and on the route. Thanks for your attention.
source | l | item | cl | E | pos | elems | subtitle 
-- | -- | -- | -- | -- | -- | -- | -- 
30395 | 2 | 3240 route access mismatch | 3 | E | 13.28 42.83 | w 125911217 r 10764791 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.28 42.83 | w 125911217 r 10764791 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.27 42.96 | w 127503748 r 10799738 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.26 42.96 | w 127503755 r 10799727 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.26 42.96 | w 127503761 r 10799727 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.26 42.96 | w 127503765 r 10799727 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.26 42.96 | w 127503785 r 10799727 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.27 42.96 | w 127503787 r 10799738 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.28 42.82 | w 170590858 r 10764791 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.22 42.99 | w 171931912 r 11162024 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.20 42.98 | w 264202970 r 11162024 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.23 42.99 | w 264203273 r 11162024 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.29 42.85 | w 372645010 r 10764791 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.27 42.96 | w 597465019 r 10799738 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.27 42.96 | w 597465024 r 10799727 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.28 42.96 | w 597465036 r 10799738 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.21 42.99 | w 597886366 r 11162024 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.21 42.99 | w 597886371 r 11162024 | Way access mismatch relation route=hiking
30395 | 2 | 3240 route access mismatch | 3 | E | 13.29 42.85 | w 605009814 r 10764791 | Way access mismatch relation route=hiking

**Comment by frodrigo** [comment]
Right `state=closed` is not supported. There is documentation on the wiki about this?

**Comment by frodrigo** [comment]
The right alternative to `state` look like to be one of the lifecycle prefixes
https://wiki.openstreetmap.org/wiki/Category:Key_descriptions_for_group_%22Lifecycle%22

**Comment by frodrigo** [comment]
Please, reopen if required.

**Comment by bikepiper** [comment]
Hi!
osmose reports issues 3249, i.e. "Way access mismatch relation route=bicycle", for relations that indeed contain ways not usable for bicycles, but these routes are also tagged with `state=abandoned`.
See, e.g., [route 2110268](https://www.openstreetmap.org/relation/2110268), containing [way 185034230](https://www.openstreetmap.org/way/185034230).

As 'abandoned' is a valid lifecycle prefix (similar to 'disused' which was proposed elsewhere but describing a feature that is currently falling into decay), I thought that this case should not trigger an osmose issue.

**Comment by frodrigo** [comment]
I does not see `state=abandoned` as a documented tag in the wiki.

We also have a similar issue in #2093
