### ISSUE TITLE
Sinkholes

### ISSUE THREAD

**Issue by hungerburg** [osm-fr/osmose-backend#1032]
A waterway that ends in a natural=sinkhole will be reported as unconnected. This is not an error though. Please adjust test to account for sinkholes.

**Comment by frodrigo** [comment]
Do you have link? I see various think on OSM data.

**Comment by hungerburg** [comment]
Hello frodrigo, the tag page is https://wiki.openstreetmap.org/wiki/Tag:natural%3Dsinkhole - it is an approved feature. The picture there looks quite appropriate.

PS: I'd say, a stream must not end at a riverbed, that should be an error.

**Comment by hungerburg** [comment]
Hmm, another likely false positive, https://www.openstreetmap.org/way/781735237 ends in a lake, which, in this case, is another kind of sinkhole ;)

**Comment by frodrigo** [comment]
I mean a link of OSM data with waterway and sinkhole.

**Comment by hungerburg** [comment]
Here we go https://www.openstreetmap.org/way/119196391 - One might say, the water just peters out in the scree, there is not much of a hole in the ground, actually, if you look closely at the aerial, where the stream ends, there is a nice waterfall, seasonally at least, but there never is a stream below

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_waterway.py#L121
