### ISSUE TITLE
Maxspeed and source:maxspeed - new values for Brussels, Belgium

### ISSUE THREAD

**Issue by bxl-forever** [osm-fr/osmose-backend#1037]
This is about class 303241: Discordant maxspeed and source:maxspeed or maxspeed:type

Effective Jan. 1, 2021, there will be new maxspeed default values in the Brussels Region (Belgium).  We have already started to update source:maxspeed at some places where the speed limit was unchanged.

Please add the following lines in https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Maxspeed.py
       'be-bru:rural': ['70'],
       'be-bru:urban': ['30'],

This is also mentioned in the wiki: https://wiki.openstreetmap.org/wiki/Key:source:maxspeed#Belgium

**Comment by frodrigo** [comment]
It is a copy from OSRM, then report here too https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L269

**Comment by bxl-forever** [comment]
OK, done.  https://github.com/Project-OSRM/osrm-backend/pull/5903
