### ISSUE TITLE
Lone highway or barrier node

### ISSUE THREAD

**Issue by lenny31** [osm-fr/osmose-backend#104]
when the node is tagged highway=traffic_signals (250601669, 244117656, 1351121823) =give_way (3262986364) =crossing (2635647672, 4060132716, 3861072862, 3964641468, 2635647672, 2635647674) if this node is part of a highway and of a landuse=residential amenity=parking (2640796333) or a leisure=park (293385253) or amenity=townhall (3576569993)

Bonjour, je reçois ce signalement alors le nœud n'est pas isolé, il appartient bien à une voie, mais en même temps à un landuse, amenity ou leisure (j'ai indiqué ci-dessus des id de nodes
cordialement
lenny

**Comment by frodrigo** [comment]
done
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=7090&class=3&country=france*
