### ISSUE TITLE
item #1210, entrance=garage is not possible

### ISSUE THREAD

**Issue by bmallet** [osm-fr/osmose-backend#1041]
Une erreur "Route à sens unique inaccessible ou parking manquant ou entrée de parking manquante" est levée sur https://www.openstreetmap.org/way/871128606 alors que le node d'origine (https://www.openstreetmap.org/node/8114561127) est entrance=garage, valeur documentée (https://wiki.openstreetmap.org/wiki/Key:entrance).
Est-il possible d'ajouter cette possibilité dans l'analyse ? Merci.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_deadend.py#L162
