### ISSUE TITLE
Too many golf cartpaths disconnected

### ISSUE THREAD

**Issue by lectrician1** [osm-fr/osmose-backend#1043]
`error#1210` come up for disconnected golf cart ways with that usually are disconnected by-design. 

As a result, Osmose creates a large number of issues per golf course.
![image](https://user-images.githubusercontent.com/22477298/101269770-d5862780-3737-11eb-889f-3b3fc4573461.png)

Maybe ways with tags:
`golf = cartpath`
`golf_cart = designated`
and/or
`highway = service`
can be excluded?

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=41.729917&lon=-88.191073&item=xxxx&level=1%2C2%2C3&tags=&fixable=

**Comment by tguen** [comment]
This issue has returned, please reopen.

https://osmose.openstreetmap.fr/en/map/#zoom=12&lat=45.5063&lon=-122.7235&item=1210

**Comment by frodrigo** [comment]
Fixed, update in progress.
