### ISSUE TITLE
False positive: The route of this road is discontinuous. 

### ISSUE THREAD

**Issue by Percherie** [osm-fr/osmose-backend#1045]
Hello,

The road relations go back up as discontinuous whereas all the elements seem to be present and correct.

Is it a false positive that can be ignored or an error in the analysis?

Error : http://osmose.openstreetmap.fr/fr/error/f777c72f-2b20-1ae1-b480-fcd87912a544
Relation : https://www.openstreetmap.org/relation/5559077

**Comment by frodrigo** [comment]
You can mark it as false positive. I think it is linked to the fact that the route rentre into the Nord Département.

**Comment by Percherie** [comment]
No problem

There are several other relationships that go back to the same error.
Do I mark them to check if it is a mistake in the design of the relationships?
In the south of France the relations are however correctly analyzed.
No big deal, just in case it hides a larger problem.

**Comment by frodrigo** [comment]
No, mark as false positives.
