### ISSUE TITLE
false positive for parking:lane:both=no?

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#1049]
According to the analyser, 

parking:lane:both | no
-- | --

is not a valid value. In the [wiki](https://wiki.openstreetmap.org/wiki/Key:parking:lane#Parking_spaces), it seems to be a valid value.

Example: http://osmose.openstreetmap.fr/fr/error/de5a8910-b98c-5b2a-ee56-f2202dcaadf6

key | value
-- | --
source | 407718
item | 3161
class | 31615

Maybe I'm misunderstanding something and the error text wording should be updated.

**Comment by matkoniecz** [comment]
@frodrigo It can be marked with ready label

**Comment by frodrigo** [comment]
Deployed, Update in progress.
