### ISSUE TITLE
Item 1210 class 4 : lots of false positives "Small highway group apart from the main network or with insufficient access upstream"

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#1053]
Hello,

Today, some french areas are suddenly invaded by lots of "Small highway group apart from the main network or with insufficient access upstream" issue.

For example, there is 51035 (!!) reported defects in Tarn http://osmose.openstreetmap.fr/fr/errors/?country=france_midi_pyrenees_tarn&item=1210&level=1 
vs only 92 in Isère http://osmose.openstreetmap.fr/fr/errors/?country=france_rhone_alpes_isere&item=1210&level=1

Cheers
~~
laurent

**Comment by frodrigo** [comment]
There is probably a more general issue.
http://munin.openstreetmap.fr/osm28.openstreetmap.fr/osm153.openstreetmap.fr/index.html
cc @jocelynj

**Comment by frodrigo** [comment]
A buggy deploy was done yesterday. We have now millions of issues of unconnected highway.
http://osmose.openstreetmap.fr/en/issues/matrix?item=1210
Probably linked to this commit d079b397899013b2141ec9cd7c1d68b7b4b75c6b

**Comment by frodrigo** [comment]
I disabled the display of this item for now.

**Comment by frodrigo** [comment]
I write the fix 13928aad6726066d681af739897105dff0589ad4

**Comment by laurentriffard** [comment]
Ok Frédéric,
Thank you for this _quick_ fix.
~~
Laurent

**Comment by frodrigo** [comment]
The fix is now deployed. The cleaning of false issue will be one or two days. Then we will renable the item.

**Comment by frodrigo** [comment]
Reneabled item.
