### ISSUE TITLE
Add an exception for ref:temples.ru and ref:sobory.ru

### ISSUE THREAD

**Issue by fizmat** [osm-fr/osmose-backend#1055]
item: 3050
class: 30501

One example:
https://osmose.openstreetmap.fr/en/error/4b398997-62e9-7423-69cc-89988c16ce81

RU wiki encourages tagging Orthodox churches with ref:temples.ru and ref:sobory.ru: 
https://wiki.openstreetmap.org/wiki/RU:Tag:amenity%3Dplace_of_worship

3700 and 800 are tagged already:

- https://taginfo.openstreetmap.org/keys/?key=ref%3Atemples.ru

- https://taginfo.openstreetmap.org/keys/?key=ref%3Asobory.ru

Is having a period in the key suffix harmful, or is this check more of a screening tool for possible typos? If the latter, please add an exception for these two keys.

Somebody proposed adding an exception allowing periods in any key suffix for ref: but maybe that would be too broad.

**Comment by frodrigo** [comment]
The key does not match the rule https://wiki.openstreetmap.org/wiki/Any_tags_you_like#Syntactic_conventions_for_new_tags
I just change this check to produce issue of level 3 in place for `.`. https://github.com/osm-fr/osmose-backend/commit/5a0bf922483f6b1a58e05192b21bcdd38d4f5cd9#diff-0a1ad46db9213fa883348285f66202006559f3e73d66f8f1ed6e79351b5f1608

There are already many github issues to ask to add keys to the white list. Sorry to be rude, but we cant just add a key to the white list because it raise an issue.

Duplicate #948

**Comment by fizmat** [comment]
You're right, it breaks the rule. But I did not invent this key.

I would have proposed to rename the key before touching the checker, but:

- using a domain name for a ref makes sense. Maybe you're right, and the initiative should be directed to the rule on the wiki first.
- show me one bulk-rename initiative that worked! Everything is legacy on top of legacy, and the OSM community seems to prefer it this way, not my place to tell them how to tag =/

Thank you.

**Comment by frodrigo** [comment]
> show me one bulk-rename initiative that worked! Everything is legacy on top of legacy, and the OSM community seems to prefer it this way, not my place to tell them how to tag =/

https://github.com/osm-fr/osmose-backend/issues/277
https://github.com/osm-fr/osmose-backend/issues/129

And I know for others not on the issues.

**Comment by matkoniecz** [comment]
> using a domain name for a ref makes sense

It also seems this way to me, you can try starting discussion on tagging mailing list and change recommended rules for tag names

> show me one bulk-rename initiative that worked! 

It is relatively easy to get permission for edit limited to a single country (see https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account ), much easier than a worldwide one
