### ISSUE TITLE
Switch from travis.org to github Actions

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1056]
Travis.org is closing at the end of the year 2020. We need to replace it.

**Comment by jocelynj** [comment]
Looking at https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing, it seems that we will still be allowed to use Travis, with 1000 minutes at start, and which can be increased by sending a request.

Is Github Actions strictly similar to Travis?
