### ISSUE TITLE
landuse=commercial and amenity is often a valid combination, for example with amenity=boat_storage

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1059]
https://osmose.openstreetmap.fr/en/map/#item=4030&zoom=17&lat=51.076816&lon=0.384178&level=1&tags=&fixable=
https://www.openstreetmap.org/way/370680096
https://osmose.openstreetmap.fr/en/error/68266df9-dc19-f86f-1938-5912a703fdf3

source | 14449
-- | --
item | 4030
class | 900
lat lon | 51.0768195 0.3841728

**Comment by matkoniecz** [comment]
I guess that it should be made similarly to https://github.com/frodrigo/osmose-backend/commit/42a7af2a7014eec573e9051dbdf8b6599dbb1598

Thanks for quick review, now I know that it is useful to make a PR

**Comment by frodrigo** [comment]
Yes
