### ISSUE TITLE
How can I run tests?

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1064]
https://github.com/osm-fr/osmose-backend/blob/master/CONTRIBUTING.md is not mentioning this

https://github.com/osm-fr/osmose-backend/blob/master/docker/README.md#develop-on-osmose-with-docker is not mentioning this

https://github.com/osm-fr/osmose-backend/blob/master/.travis.yml#L53 has some hints - I guess that I should run https://github.com/osm-fr/osmose-backend/blob/master/.travis.yml#L27 to setup testing environment, right?

**Comment by frodrigo** [comment]
You are right, It should be added to the doc. Details in contributing, and recall in Docker README.

It all can by done with `./tools/pytest.sh` or unitary with `pytest foobar.py`. The CI also run the test.
