### ISSUE TITLE
Unmapped traffic light

### ISSUE THREAD

**Issue by willisturm** [osm-fr/osmose-backend#1065]
Hi,
there are no traffic signals. These are a crossings with flashing lights (flashing_lights=always). In Austria there are many of such pedestrian crossings. ( Sorry about my bad english.)

http://osmose.openstreetmap.fr/de/error/df84b170-74d2-28a8-35f2-7e3a0564b4e0
http://osmose.openstreetmap.fr/de/error/43170e79-2dcc-a319-cd71-e67dd391ebc2

Thank you an Merry Christmas
Willi

**Comment by frodrigo** [comment]
Also match highway=crossing  + flashing_lights=* in
https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-street-objects.mapping.json#L63-L98

**Comment by soulei-seg** [comment]
Hi,
I'm focusing on this issue and tried the following change (locally) on the file /merge_data/mapillary-street-objects.mapping.json :
![2021-01-15_17-28](https://user-images.githubusercontent.com/31833254/104752557-1cb00100-5757-11eb-85c1-45199a81ec3f.png).

**Comment by frodrigo** [comment]
No, we need a full new block, propably
```diff
+      {
+        "highway": "crossing",
+        "flashing_lights": None
+      },
```

**Comment by Famlam** [comment]
@frodrigo shouldn't it be without quotes around None (or null)?

**Comment by frodrigo** [comment]
@Famlam you are right.
@soulei-seg please, can you make an other PR to fix this?

**Comment by soulei-seg** [comment]
Yes, sorry for the mistake.
Indeed it has to be **null** without any quote.
Making another PR soon.

**Comment by frodrigo** [comment]
Deployed
