### ISSUE TITLE
[Name_Multiple] Not only streets are affected

### ISSUE THREAD

**Issue by fossdd** [osm-fr/osmose-backend#1067]
I would prefere in the "multiple names in one tag"-Issue Description, that not only streetnames are affected.

`name=*`-Tags are not only for streets.

Source:

https://github.com/osm-fr/osmose-backend/blob/a39903b976ac0aba8f8f4967a8ca6b6a271e8b2e/plugins/Name_Multiple.py#L35-L46

**Comment by frodrigo** [comment]
You are right, the check is not specific for the street names.

**Comment by matkoniecz** [comment]
@frodrigo I can be marked with "ready" label

**Comment by fossdd** [comment]
Thanks, great!
