### ISSUE TITLE
IGN OD: Église simultanées

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osmose-backend#1069]
Salut,

320 ligne 94
Concernant les églises simultanées, j'ai découvert ca personnellement (je ne connaissais pas du tout) en cartographiant les églises en Alsace.
https://fr.wikipedia.org/wiki/%C3%89glise_simultan%C3%A9e

Du coup, comme il y a avait aucun tag, j'ai mis
amenity=place_of_worship
religion=chistian
denomination=simultaneous

J'en ai 24 en base d'après taginfo. Faut voir combien l'IGN en a elle.
Après concrètement, il s'agit surtout d'un usage historique et de disposition architectural. Si une église ne propose plus qu'un seul culte, faut-il la tagguer en simultanée. La question reste entière.

**Comment by frodrigo** [comment]
```
42 Eglise simultanée
```
Il n'y en a que 42, je ne l'ai pas traité.

Tu peux commenter directement le code ou ici https://github.com/osm-fr/osmose-backend/pull/1050

**Comment by gendy54** [comment]
Si y en a que 42 ca correspond peu ou prou à ce qu'il y a sur WP, donc effectivement, on laisse tomber.
