### ISSUE TITLE
TagRemove_Incompatibles whitelist ['wood', 'leisure', 'playground'

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1071]
Report from @ecd1eb5
https://github.com/osm-fr/osmose-backend/commit/ecd1eb5a3b903559b9d3f2c3e415a791cda9fa3d#commitcomment-45491851

Please also whitelist ['wood', 'leisure', 'playground'] under "natural" - we call this here a "Waldspielplatz", i.e. playground in the woods - this renders much better in mapnik when combined, c.f https://www.openstreetmap.org/relation/6873478 for a real world use
PS: perhaps also landuse/forest//leisure/playground too?

**Comment by hungerburg** [comment]
Thank you frodrigo
