### ISSUE TITLE
Misleading RTE "power tower" on underground cable terminations

### ISSUE THREAD

**Issue by cquest** [osm-fr/osmose-backend#1078]
http://osmose.openstreetmap.fr/fr/error/e17686df-e393-83b2-0b1f-392f49b5510b

RTE data says these is a power tower there, but all power line are underground.

It may be there as a termination to the power cable.

To filter them maybe use `hauteur_pylone != '0' AND numero_pylone > '9'` (alpha is used in termination names)

**Comment by frodrigo** [comment]
Add select "number" on `numero_pylone`:
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_power_tower_FR.py#L43

**Comment by flacombe** [comment]
I second proposal to check on power support's height.

It could be even more accurate by intersecting them with underground cables (because 0m power towers at the end of overhead power lines should be properly added). Grande-Motte's one shouldn't bother osmose because it is at the end of an undergrorund cable

**Comment by frodrigo** [comment]
Update in progress
http://osmose.openstreetmap.fr/fr/issues/open?item=8290&class=1
http://osmose.openstreetmap.fr/fr/issues/graph.png?item=8290&class=1&start_date=2021-6

**Comment by flacombe** [comment]
Sounds really nice thank you.

Why a node like https://www.openstreetmap.org/node/1079477373 isn't proposed to be completed with operator=RTE, height=xx from opendata ?
I didn't remember if it has ever existed like this or not. If not I could complete analyser later.

**Comment by frodrigo** [comment]
No. Update is not enable. It requires a ref.

**Comment by flacombe** [comment]
As conflation is used to determine if a tower exists at a similar place than opendata, isn't this possible to do the same for update?
For RTE case, two distinct towers should be at a significant distance

**Comment by frodrigo** [comment]
It is always done using ref in the conflation framework. It would may be done without, by changing the code.
Not sure about the assert "significant distance", like close to power station.

**Comment by flacombe** [comment]
Ok, that requires a bit more work

"significant distance" is understood here >> than the conflation distance

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/issues/graph.png?item=8290&class=1&start_date=2021-6
Half of the missing poles are now gone. It is the expected behaviours?

**Comment by flacombe** [comment]
I guess yes.
Occurrences I visited were accurate or false positive due to errors on RTE side.
It's good news :)
