### ISSUE TITLE
Allow building:part to have a name

### ISSUE THREAD

**Issue by hungerburg** [osm-fr/osmose-backend#1079]
https://www.openstreetmap.org/way/884904024 is the "Turm" of the first "Hochhaus" in this town. I guess that should appear more often in data, that parts of buildings have their own names? Tagging looks complete to me and perfectly valid.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/error/3d92c5c3-bfd8-fa65-e552-17b07c135ebb

Yes `building:part` should be added here https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag.py#L31

**Comment by frodrigo** [comment]
Deployed
