### ISSUE TITLE
New analysis : detect ways with high node density

### ISSUE THREAD

**Issue by GeorgeKaplan** [osm-fr/osmose-backend#108]
Some ways (often imported ones) are over-described and are made of too many nodes. We can simplify them with JOSM to avoid wasting resources.

This new analysis would detect ways that have, on average, more than N nodes per meter.
I think we can start with a limit of 2 nodes per meter.

**Comment by didier2020** [comment]
or compare the number of node of the geometry and the ST_SimplifyPreserveTopology of the geometry

**Comment by frodrigo** [comment]
Do you have exemple where the quantity of nodes is a problem ?

**Comment by didier2020** [comment]
exemple :
http://www.openstreetmap.org/way/282784499
http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=43.29655&lon=6.46971&layer=Mapnik&item=xxxx&level=1%2C2%2C3&tags=&fixable=

**Comment by GeorgeKaplan** [comment]
frodrigo, this is often seen on polygons with curves, imported from french cadastre.

**Comment by operon** [comment]
Exist for road imported from GPX file
I have not example

**Comment by frodrigo** [comment]
I know, but the point is : why should we report this as a problem ?

**Comment by GeorgeKaplan** [comment]
For the same reason Osmose already reports split buildings, duplicated nodes or duplicated ways : this is unnecessary data, which wastes disk space, bandwidth and CPU cycles.

**Comment by frodrigo** [comment]
> split buildings, duplicated nodes or duplicated ways : this is unnecessary data, which wastes disk space, bandwidth and CPU cycles.
There are mapping issues, but not just about unnecessary data.

**Comment by didier2020** [comment]
item=7011&class=1 do the job  when there is no specific tag.
The number of nodes is not quality for geom :
![capture-3](https://cloud.githubusercontent.com/assets/5434425/14759716/4f64d9f0-092c-11e6-834a-25144e2ef0df.png)
