### ISSUE TITLE
multipolygon relation is not detected for post_office

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osmose-backend#1080]
Hello and bonne année !

Multipolygon seem to be not detected for the post offices (item 8020)
ex : 
http://osmose.openstreetmap.fr/fr/map/?#zoom=13&lat=46.9983&lon=-2.2203&item=8020&level=1%2C2%2C3&tags=&fixable=

In this exemple the post office Noirmoutier-en-lille (ref 16079A) is said missing, but it exists in the relation https://www.openstreetmap.org/relation/8303626

thanks.

**Comment by frodrigo** [comment]
You are right
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_poste_FR.py#L53

Edge case, just mark it as false positive.

**Comment by zorglubu** [comment]
d'ac !
