### ISSUE TITLE
XXXX without name

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#1081]
key | value
-- | --
source | 407663
item | 9001
class | 9001001

http://osmose.openstreetmap.fr/en/error/e2f07ffb-ebf7-3c96-ac00-cecb8b6f32bd

Some places have no name. In that case 

noname | yes
-- | --

states it, so no error should be raised in this case.

**Comment by frodrigo** [comment]
Rule from JOSM Validator
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss

cc @Klumbumbus

**Comment by Bibi56** [comment]
Thanks @frodrigo (next step in advance: thanks in advance @klumbumbus, let me now if I should create a ticket on JOSM).

**Comment by Klumbumbus** [comment]
Fixed in https://josm.openstreetmap.de/changeset/17441

**Comment by frodrigo** [comment]
Will in osmose on next validator update.
