### ISSUE TITLE
millesime is hardcoded

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#1082]
Please display the exact date of data.

https://github.com/osm-fr/osmose-backend/blob/456980c79b80cfce67cb51176882f61fd1438ca9/analysers/analyser_merge_shop_FR.py#L59

**Comment by frodrigo** [comment]
Require to fetch the last date from OpenData portail API.

**Comment by gileri** [comment]
Would the `millesime` be simply the current date or should it be retrieved from the data when possible ?

I ask before I was thinking about implementing it before seeing the `big` tag on this issue :smile:

**Comment by frodrigo** [comment]
The goal is to subclass the Source to use OpenData portal API. 80% Of existing analyzers use data.gouv.fr or an OpenDataSoft portal (v1 / v2).

First step can be to only fetch the last millesime of the resource, independently of the version of the data in cache.

As 80% os this analyzers can be supported, the Source of these analyzers must be edited.

**Comment by gileri** [comment]
Thank you for those details !

I'll have a look, I'll report back if it's more than I can chew.

**Comment by frodrigo** [comment]
Ask if you need help or have question.

Note: the PR will me merged soon 
https://github.com/osm-fr/osmose-backend/pull/1075

**Comment by frodrigo** [comment]
The big PR on merge is now merged.

**Comment by frodrigo** [comment]
Deployed, So far, so good.

**Comment by frodrigo** [comment]
All passed.Thank you for all the time you give to this.

**Comment by gileri** [comment]
> All passed.Thank you for all the time you give to this.

And to you for the help and reviews ! Happy to contribute.
