### ISSUE TITLE
substation currently wrongly classified in the category of roads

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1086]
https://osmose.openstreetmap.fr/fr/errors/?item=7170&class=94
substation currently wrongly classified in the category of roads

**Comment by frodrigo** [comment]
@jocelynj need more sources for @cquest

**Comment by Marc-marc-marc** [comment]
ping @cquest @jocelynj

**Comment by jocelynj** [comment]
Actuellement, sur le country=france, on a ça:
```
  id   | country |      analyser       
-------+---------+---------------------
  3206 | france  | communes_manquantes
 14708 | france  | opendata_xref
```
Je peux rajouter d'autres sources: quels noms vous voulez ?

**Comment by cquest** [comment]
J'ai corrigé le XML qui avait un tag=highway (maintenant tag=power) pour les 2 analyses qui concernent les données sur le réseau électrique.

opendata_xref me va bien, mais si vous pensez qu'il faut organiser ça autrement, pourquoi pas.
Vous connaissez mieux le front que moi !

**Comment by frodrigo** [comment]
It rather the item than the source. 7170 is "routes".
You can push under other item using the same analyser/source.
- "(TEST) poste de transformation HT/BT à intégrer" should be under item http://osmose.openstreetmap.fr/fr/errors/?item=8281

**Comment by alkino** [comment]
Hey du coup ça en est où ?
On a moyen d'accéder au fichier d'analyses ?

**Comment by Marc-marc-marc** [comment]
est-ce que le fix est aussi trivial que https://github.com/Marc-marc-marc/osmose-scripts/commit/8c450cb9283bff680fece52298a7fda62897ff8b ?

**Comment by cquest** [comment]
Pas aussi trivial que ça, car il faut un token/pass pour envoyer au front le résultat de l'analyse et il est lié au numéro de celle-ci si j'ai bien compris.

Quel est le problème en fait ?

Les analyses sous 7170 sont des croisements multiples avec des données opendata qui peuvent être de natures différentes : routes, réseaux électriques, cours d'eau, etc... d'où son nom "opendata_xref".

**La description de l'analyse en "route" vient du front, pas de ce que mes scripts envoient. Je ne peux pas la changer.**

L'erreur sur le tag a été corrigée il y a un mois, on peut bien sélectionner les résultats par thème, il me semble que c'est donc juste un problème de nom donné par le front à ce groupe d'analyses.

Comme indiqué le 3 mars, si vous pensez qu'une autre organisation avec différents numéros d'analyse est souhaitable, ça ne me pose aucun problème. Envoyer vers l'item 8281 est possible, mais il me semble qu'il faut un autre token/pass pour les transferts, non ?

Je veux bien un item "bac à sable" pour y mettre les tests, à moins qu'il y ait toujours un front de test dispo.

**Comment by alkino** [comment]
Et sinon y'aurait pas moyen de mettre ces backends dans osmose-backend ?

Autre point : 
```<tag action=\"create\" k=\"voltage\" v=\"20000\" />```
Dans l'autre backend le voltage est `20000;400`, lequel est le plus juste ?

**Comment by Marc-marc-marc** [comment]
> Quel est le problème en fait ?

quand on choisit l'[item 7170 route](https://osmose.openstreetmap.fr/fr/errors/?item=7170) dans le menu de gauche du front, on est noyé avec plein de non-route (des postes électriques, des cours d'eau, ...).

pour le mot de passe, fred disait que le front acceptait plusieurs items dans un envoi, je n'ai pas testé.

**Comment by frodrigo** [comment]
# 7170 OK

class | label | #
-- | -- | --
1 | route potentiellement manquante à proximité (BD Topo IGN) | 119379
30 | name=* ou route potentiellement manquante à proximité | 99393
3 | ref=* manquant ou tracé décalé de la route comparé à la BDTopo IGN | 28281
33 | route manquante à proximité ? | 13871
32 | name=* à ajouter sur highway ? | 6994
20 | lanes=* manquant sur route à plus de 2 voies (BD Topo) | 6911
31 | name=* à modifier sur highway ? | 3799
2 | ref=* ou route potentiellement manquante à proximité | 0
13 | voirie cadastre sans route à 20 m | 0
10 | route potentiellement manquante à proximité | 0
99 | (TEST) name=* ou route potentiellement manquante à proximité | 927
96 | (TEST) tracé décalé de la route | 126
97 | (TEST) lanes=* manquant sur route à plus de 2 voies | 71

# Pas OK

Envoyer tous les tests vers un item caché (non déclaré) par example 7171.

Autre possibilité pour les rendre visible. Utiliser d'autres items. Les items sont thématiques.

* Trouver un item convenable ou en créer un :

class | label | #
-- | -- | --
50 | bâtiments non importés sur la commune | 0

* 8510

class | label | #
-- | -- | --
98 | (TEST) cours d'eau potentiellement manquant à proximité | 467911

* 8280 ou 8281

class | label | #
-- | -- | --
94 | (TEST) poste de transformation HT/BT à intégrer | 63366
95 | (TEST) ligne électrique HT (power=line) manquante à proximité | 567

**Comment by cquest** [comment]
Ok, compris, je redirige vers les items de mon choix et sans lien avec le nom/pass de l'analyse...

Donc :
- 94 > 8281
- 95 > 8280
- 98 > 8510

Et pour les tests, je squatte 7171

La 94 a déjà disparu de 7170, ce qui était l'issue de départ.
