### ISSUE TITLE
IGN : Cemetery not integrated : item=8480 class=8

### ISSUE THREAD

**Issue by lenny31** [osm-fr/osmose-backend#1087]
When the cemetery is described in osm with a multi-polygon relation, osmose declares it absent.

https://www.openstreetmap.org/relation/7494469

http://osmose.openstreetmap.fr/fr/error/8a5faae9-f106-5dab-5878-68cc6edce20a

http://osmose.openstreetmap.fr/fr/map/#item=8xxx&useDevItem=all&zoom=17&lat=43.589056&lon=1.38536&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
Fixed, but update in progress.

**Comment by frodrigo** [comment]
Multi-polygon relation are ignored. Just mark as false positives.
