### ISSUE TITLE
Address of place:plot areas

### ISSUE THREAD

**Issue by vnmabus** [osm-fr/osmose-backend#1088]
I have been mapping areas in Spain with the label place:plot. In these places, the addresses are assigned to plots and not buildings (so all buildings in the same plot share the same address, and plots with no buildings also have an address). However, Osmose complains about mixing `place` and `addr` labels. Could it be possible to accept this particular combination of labels for `place:plot` areas?

**Comment by frodrigo** [comment]
Do you have a link to osmose or the item/class ids?

**Comment by vnmabus** [comment]
This is the area in question that I am mapping, although I do not think it is the only place where the addresses are assigned to plots:

http://osmose.openstreetmap.fr/es/map/#zoom=17&lat=40.76644&lon=-3.781615&item=xxxx&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
This rule come from the JOSM validator.

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
Fixed in https://josm.openstreetmap.de/changeset/17448

**Comment by frodrigo** [comment]
Thank you.
Will be fixed in Osmose on next Validator update.
