### ISSUE TITLE
parking:lane:<value>=separate is not recognized

### ISSUE THREAD

**Issue by nyqvist** [osm-fr/osmose-backend#1089]
According to the osm wiki - `parking:lane:<side>=separate` is used on a highway to indicate that the parking information is mapped separately (see https://wiki.openstreetmap.org/wiki/Tag:parking%3Dstreet_side). This is not recognized by Osmose.

Item: 3161
Class: 31615
Message: Bad parking:lane:[side] value

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Parking_Lane.py

**Comment by frodrigo** [comment]
Deployed
