### ISSUE TITLE
amenity=driving_school + landuse=commercial is fine

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1095]
https://www.openstreetmap.org/way/484294071

`Conflict between tags: amenity, landuse`

http://osmose.openstreetmap.fr/en/error/67b2ff34-2352-839f-4070-99f575f87eca

**Comment by frodrigo** [comment]
Do you think we can add more "wilcard" here, rather than one by one ? https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Incompatibles.py#L89-L97

**Comment by matkoniecz** [comment]
I see two solutions: 

(1) skip all `landuse=commercial` `amenity=*` matches
(2) add one by one yet another `amenity=something`

both are fine to me - second is extremely annoying but will catch actual mismatches. What you prefer? Do you see a better solution?

**Comment by frodrigo** [comment]
I think we must act more globally. I even ask mys self if this analyser should be disabled.
I prefer miss issues, rather than raise too many false positives.

**Comment by matkoniecz** [comment]
During reporting that I also found some valid reports (`natural=tree_row` `highway=residential` on one way, friend thanks to this learned that `leisure=track` is not for motor sport).

But it is doomed to produce endless stream of false positives - that is why I focused on this one, as I can handle both real errors and make PRs for false positives.

And I would say that Osmose is not suffering from reporting not enough issues, so killing this report completely for high false positive ratio may make sense. Some clear mistakes are already reported by JOSM rules.

**Comment by matkoniecz** [comment]
You mentioned that you consider completely removing this rule - what is the verdict on this? I would gladly make PR with further exceptions, but if it would be removed in entirety then it would be pointless to spend time on tweaking this.

**Comment by frodrigo** [comment]
Ok. Let keep it and add more rules.

**Comment by frodrigo** [comment]
Deployed, Update in progress.
