### ISSUE TITLE
highway=footway/path + railway=disused/abandoned should not trigger level 1 tag conflict

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1096]
```
highway = footway
railway = disused 
```

https://www.openstreetmap.org/way/403703724
http://osmose.openstreetmap.fr/en/error/4c8809b4-d812-a211-d299-1e92a3b27dd4

**Comment by frodrigo** [comment]
Please add it https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Incompatibles.py#L35

**Comment by frodrigo** [comment]
Deployed, Update in progress.
