### ISSUE TITLE
Analysis Build error

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-backend#1097]
Hello

From the http://osmose.openstreetmap.fr/en/control/update_matrix I see several regions are reporting error since 8 days ago (and counting :smile:).

For example this build : https://buildbot.osmose.openstreetmap.fr/#/builders/471/builds/140
show errors. making the analysis fail.

No problem for me to gather the file:
`curl -sI  download.openstreetmap.fr/extracts/europe/spain/comunidad_de_madrid-latest.osm.pbf  | grep -i Content-Length  
Content-Length: 61702017
`
Could you please fix this?
Thanks

**Comment by frodrigo** [comment]
@jocelynj @Marc-marc-marc An issue the ipv6 tunnel ?

**Comment by frodrigo** [comment]
To be checked if the tunnel is not pointing the old download.osm.fr

**Comment by Marc-marc-marc** [comment]
aquilenet ihivane1 hivane2 are ipv6-only vm and use a tunnel for download.openstreetmap.fr
tunnel is going to osm26
the tunnel endpoint doesn't respond

**Comment by jocelynj** [comment]
I don't think it is an issue with download vs old download, as it was removed several months ago, and the tunnel is using the whole name.
Looking at osm26, I see that we have tunnels running, but not for download.openstreetmap.fr, not sure why. I've launched 
`/root/osmfr/6tunnel-cron.sh`, which has started this tunnel.

**Comment by jocelynj** [comment]
By the way, I don't think we need a tunnel for download.openstreetmap.fr anymore, as it is accessible though ipv6: the tunnel was only necessary for the java library behind osmosis.

**Comment by jocelynj** [comment]
It is now fixed, thanks for having reported the issue: https://buildbot.osmose.openstreetmap.fr/#/workers/5
