### ISSUE TITLE
tag `waterway=rapids` is deprecated : this is wrong

### ISSUE THREAD

**Issue by fx99-D** [osm-fr/osmose-backend#1098]
This 

415872 | 2 | 4010             disused | 40102 | E | -76.33 46.58 | n          460231997                    (j) | The tag `waterway=rapids` is deprecated in favour of [Whitewater sports](https://wiki.openstreetmap.org/wiki/Whitewater_sports)

should not be an issue. 

According to wiki  `waterway=rapids`  is not depreciated! 
https://wiki.openstreetmap.org/wiki/Tag:waterway%3Drapids 

Besides thsi formal fact, rapids exist without any relation to whitewater_sports

**Comment by frodrigo** [comment]
This check use https://wiki.openstreetmap.org/wiki/Deprecated_features

And `waterway=rapids` if deprecated since 2010-05-10.

**Comment by fx99-D** [comment]
That is correct, but used more and more: https://taghistory.raifer.tech/#***/waterway/rapids
Also see: https://wiki.openstreetmap.org/wiki/Talk:Deprecated_features#I_suggest_remove_the_following_from_the_list

**Comment by matthewdarwin** [comment]
FWIW, waterway=rapids is used a lot in Canada.  I ignore osmose warning for this issue.
