### ISSUE TITLE
Lots of false positives in merge

### ISSUE THREAD

**Issue by masterofnoroad** [osm-fr/osmose-backend#1100]
Something must changed because lots of new places appeared, but the infrastructure IS mapped, so it shouldn't show:

http://osmose.openstreetmap.fr/en/map/?#zoom=18&lat=53.583184&lon=15.303692&item=8470&level=1%2C2%2C3&tags=&fixable=

http://osmose.openstreetmap.fr/en/map/?#zoom=18&lat=53.034016&lon=15.297936&item=8470&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
Yes, there is something wrong
http://osmose.openstreetmap.fr/en/errors/graph.png?source=34000&item=8470&class=130

**Comment by masterofnoroad** [comment]
I checked randomly, and it appears that the tag combination is not taken into account:

highway=path
bicycle=designated
foot=designated

...but it was before, so what changed?

**Comment by frodrigo** [comment]
Look like a more general issue,. Not linked to the country or the item.
Other items are impacted from the same date
http://osmose.openstreetmap.fr/en/errors/graph.png?item=8010&class=1
Probably linked to this big PR #1075

**Comment by frodrigo** [comment]
Back to normal

**Comment by masterofnoroad** [comment]
sorry, but not much changed in Poland, numbers didnt drop and lots of false positives showing up:

http://osmose.openstreetmap.fr/en/map/?#zoom=16&lat=53.24405&lon=16.37664&item=8470&level=1%2C2%2C3&tags=&fixable=

http://osmose.openstreetmap.fr/en/errors/graph.png?country=poland_zachodniopomorskie&item=8470&level=1%2C2%2C3

**Comment by frodrigo** [comment]
The update take a while, now it is ok.

**Comment by masterofnoroad** [comment]
took longer than i though. sorry, still learning :-) thanks!
