### ISSUE TITLE
highways not connected or false positive?

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#1102]
http://osmose.openstreetmap.fr/fr/error/67ace068-d812-17f9-5d2f-384fe483be3a

says that a way in https://www.openstreetmap.org/node/3247483795#map=19/47.86435/-3.44237 is not connected.

But two roads are connected,  both as:

highway | secondary
-- | --

Is it a bug or should I simply mark it as false positive?

**Comment by frodrigo** [comment]
False positive. Due to admin limit. issues are computed by départment in France.
