### ISSUE TITLE
Power minor_distribution substation not integrated not looking at power pole, item=8280, class=11

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osm-fr/osmose-backend#1105]
This analysis reports missing power transformer. 
But it reports missing items where there is already a transformer in OSM on top of a power=pole + transformer=distribution.

Suggestion: look at existing power substation by using the tag "transformer=distribution" + ( "substation=minor_distribution"or "power=pole")

Example: http://osmose.openstreetmap.fr/fr/error/92031ad3-84e5-f78f-562c-abef093b8062

**Comment by frodrigo** [comment]
Duplicate #1100
Fixed yesterday, update in progress.
