### ISSUE TITLE
Warning for valid opening_hours format

### ISSUE THREAD

**Issue by double-a** [osm-fr/osmose-backend#1106]
Warning for wrong value for
  opening_hours = Mo-Sa 14:00-19:00; PH,Su,SH 10:00-19:00

I can't see the issue and https://openingh.openstreetmap.de/evaluation_tool/ evaluates ok.

See http://osmose.openstreetmap.fr/de/error/f8757b7d-cee4-e10e-d81c-28106dca9b9b
Objekt #3250, Priority low,  points to  TagFix_Opening_Hours.py#L39

**Comment by frodrigo** [comment]
cc @dfaure

**Comment by dfaure** [comment]
The evaluation_tool includes a lot of tolerance compared to the spec, https://wiki.openstreetmap.org/wiki/Key:opening_hours.
The spec says     `dates: monthly | weekly | daily | variably | holidays`
So where monthly includes weekdays which includes "Su", while holidays has "PH" and "SH". So technically, mixing Su with PH,SH is incorrect. However, it so happens that we implemented the same tolerance in KOpeningHours in the last few days, so simply using a more recent KOpeningHours will fix this.

**Comment by frodrigo** [comment]
Deployed
http://osmose.openstreetmap.fr/en/errors/?item=3250
