### ISSUE TITLE
`building:part` is not treated as a top-level tag

### ISSUE THREAD

**Issue by jdhoek** [osm-fr/osmose-backend#1109]
I'm seeing **Untagged named object** (item 2110) being flagged for ways tagged with `name` and `building:part`.

This doesn't seem right. `building:part` looks like a top-level tag, and building parts being named is not uncommon (e.g., a wing of a hospital).

**Comment by frodrigo** [comment]
Duplicate #1079

**Comment by frodrigo** [comment]
Deployed
