### ISSUE TITLE
power pole with transformer

### ISSUE THREAD

**Issue by jzvc** [osm-fr/osmose-backend#111]
Osmose report this as unfinished power line.

power=pole
transformer=distribution

**Comment by pyrog** [comment]
Same issue with `transformer=minor_distribution`. See [error/23612004381](http://osmose.openstreetmap.fr/fr/error/23612004381).

**Comment by frodrigo** [comment]
Ok, added.

**Comment by pyrog** [comment]
Thank you 😀
