### ISSUE TITLE
Missing way on level crossing

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1113]
item | 7090
class | 1

But there is the ways

http://osmose.openstreetmap.fr/en/error/dc034255-7210-1bd0-6a25-bc64c39ec10c

**Comment by gileri** [comment]
Here is a still active [error](http://osmose.openstreetmap.fr/fr/issue/abaa5263-08e7-b80a-63b9-a9bd4b1b27e5).

**Comment by bxl-forever** [comment]
I am experiencing the same issue: in the last days or weeks, dozens of code 7090 warnings have popped up about alleged missing ways.

An example here: https://www.openstreetmap.org/node/4360348846
This is a level crossing and the node properly belongs to both a road (highway=tertiary) and a railway (railway=tram).

There are 2,265 level_crossing and 2,193 crossing nodes on the Brussels tram network, and they didn’t raise warnings until now.
Seems to come from analyser_osmosis_highway_features.py.

**Comment by frodrigo** [comment]
Yes,. Something strange in the stats
http://osmose.openstreetmap.fr/en/issues/graph.png?country=belgium_%2a&item=7090

**Comment by deuzeffe** [comment]
Same for me, eg https://www.openstreetmap.org/node/3571800493 reported as Missing way on level crossing (I'm mapping in France).

**Comment by Famlam** [comment]
Looks fixed in NL now

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/issues/1301#issuecomment-1006732229
