### ISSUE TITLE
"The URL does not have a valid scheme" complaint is not useful 

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1115]
Osmose complains about `website=www.maliprzyjaciele.pl` and demand http(s) prefix. It is displayed as "normal" priority error. Why?

 If anyone would care about this transformation and wanted to apply it, then it is easy to automate it like with https bot ( https://wiki.openstreetmap.org/wiki/Automated_Edits/b-jazz-bot ). Asking humans to do it manually is massive waste of time, there is no shortage of issues where fixes are actually useful and require human attention. 

And that assumes that such change improves it even a bit. I propose to completely remove this complaint or at least reduce its importance. In general, I feel tags such as `website=www.openstreetmap.org` or `website=astralcodexten.substack.com` should be considered as perfectly fine and should not raise any kind of complaints.

http://osmose.openstreetmap.fr/en/error/c06c52f4-4fca-9e27-286c-99841f20886d is example of specific case where it happens

**Comment by matkoniecz** [comment]
I propose to reduce its importance to lowest possible or - even better - completely remove it.

**Comment by frodrigo** [comment]
cc @fgouget

**Comment by fgouget** [comment]
The OpenStreetMap wiki says:
> Include the scheme (http or https) explicitly. https://www.openstreetmap.org/, not www.openstreetmap.org/

I consider this to be sufficient to justify an Osmose check. I don't care about the priority however so if someone thinks some other priority is more appropriate feel free to change it.

Also feel free to do a mass edit using the "Https all the Things"  script, getting approval through the  proper channels first of course. Given that quite a few links are actually garbage I suspect this check will still flag issues after.

**Comment by matkoniecz** [comment]
I started "consider website=www.openstreetmap.org to be OK" on tagging mailing list with a goal of removing this part.

**Comment by matkoniecz** [comment]
> Also feel free to do a mass edit using the "Https all the Things" script, getting approval through the proper channels first of course. 

I am not planning to do this, as I see no value at all in such changes. So if someone is interested in going for it - feel free!

**Comment by fgouget** [comment]
For reference, the discussion on the tagging mailing list:
https://lists.openstreetmap.org/pipermail/tagging/2021-January/058994.html

**Comment by frodrigo** [comment]
Moved to level 3
