### ISSUE TITLE
"Fence with material tag, better use fence_type tag" complaint is not that useful

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1116]
I am unsure why `material=steel` is problematic and some `fence_type` value should be used instead.

But it definitely is not "high" level of importance, it is not even lower.

Note: if `fence_type` is at all important/useful/used then let me know - and I would gladly implement StreetComplete quest for it. But right now this tag seems to have basically no importance and way of recording this seems even more pointless.

So I propose to remove this complaint or at least downgrade it to low importance.

**Comment by maro-21** [comment]
Duplicate of #803
