### ISSUE TITLE
Hiking route passing over pedestrian multipolygon

### ISSUE THREAD

**Issue by janj-su** [osm-fr/osmose-backend#112]
The relation [4673896](http://www.openstreetmap.org/relation/4673896) (route=hiking) is tagged on way [332683611](http://www.openstreetmap.org/way/332683611) which is untagged but also a member of [3862769](http://www.openstreetmap.org/relation/3862769) which is of type highway=pedestrian. OSMOSE indicates that there is a tag missing but as far as I can see all parts are correctly tagged and it would seem that OSMOSE can't see the pedestrian polygon.

http://osmose.openstreetmap.fr/en/error/6692997612

More examples are available a bit to the north-vest
http://osmose.openstreetmap.fr/en/error/6692998742
http://osmose.openstreetmap.fr/en/error/6692994174

**Comment by frodrigo** [comment]
Yes, you right, there is something wrong.
Btw, I see you linked to issues, but you have already close them.

**Comment by janj-su** [comment]
No I did not. :-( But they surely are gone.

You can find the first error from my [blame page](http://osmose.openstreetmap.fr/en/byuser/?username=bagis#). :-)

**Comment by frodrigo** [comment]
http://wiki.openstreetmap.org/wiki/Relation:route
On members: role (blank)/route "The ways making up the route."
So blank is a valid value in this case.

**Comment by frodrigo** [comment]
Please reopen if required.
