### ISSUE TITLE
Add detection of oneways

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1123]
Mapillary contains about 200000 cases of the "oneway, no entry from this side" (`regulatory--no-entry--g1`) sign in NL, of which a large amount is already mapped.
Unlike the arrow-like oneway signs, like [this one](https://traffic-icons.mapillary.com/signs/regulatory--one-way-right--g1.svg) (which contain huge amounts of false positives) the ['no entry from this side' sign](https://traffic-icons.mapillary.com/signs/regulatory--no-entry--g1.svg) is quite well detected. 

Hence I would propose to add the following rule:
```
  {
    "item": 8300,
    "class": XXXXXXXXXXXX,
    "level": 3,
    "otype": [
      "ways"
    ],
    "conflation": 200,
    "title": "one-directional roads",
    "object": [
      "regulatory--no-entry--g1"
    ],
    "select_tags": [
      {
        "highway": null,
        "oneway": null
      },
      {
        "highway": null,
        "oneway:motor_vehicle": null
      },
      {
        "highway": null,
        "oneway:vehicle": null
      },
      {
        "highway": null,
        "oneway:motorcar": null
      },
      {
        "highway": null,
        "oneway:hgv": null
      },
      {
        "highway": null,
        "oneway:bus": null
      },
      {
        "highway": null,
        "oneway:foot": null
      },
      {
        "highway": null,
        "oneway:psv": null
      },
      {
        "highway": null,
        "oneway:bicycle": null
      },
      {
        "highway": null,
        "oneway:moped": null
      },
      {
        "highway": null,
        "vehicle:backward": null
      },
      {
        "highway": null,
        "motor_vehicle:backward": null
      },
      {
        "highway": null,
        "hgv:backward": null
      },
      {
        "highway": null,
        "hazmat:backward": null
      },
      {
        "highway": null,
        "bicycle:backward": null
      },
      {
        "highway": null,
        "access:backward": null
      }
    ],
    "generate_tags": {
      "oneway": "yes"
    }
  },
```

I don't know how well oneway ways are mapped in the remaining part of the world, so in case it is causing excessive messages, perhaps the following should be added - similar to the stop sign detection in Canada:
```
    "only_for": [
      "NL"
    ],
```

**Justification of the tags I picked (with XXXXX = a vehicle type) :**
- I've added all tag combinations that I could find in taginfo _worldwide_ with more than 100 hits, searching for `oneway:*=yes` or `:backwards=no`. (mofa excluded: that's typically together with bicycle or moped tags)
- Since `oneway=no/0` and `oneway:XXXXX=no/0` wouldn't cause false positives I made the oneway key checks check for any value (so there is no need to check for all of `yes, alternating, 1, -1, reversible`)
- As `XXXXX:backward = no` and `XXXXX:backward = destination` both exist, but `XXXXX:backward = yes` is rare to exist without anything suggesting a oneway in another direction, I chose to count every tag with `XXXXX:backward` as a likely oneway
- As `XXXXX:forward = no`  is more rare and is often combined with `XXXXX:backward` I chose to ignore these

**Comment by frodrigo** [comment]
Ok, please make a pull request with that, including the only_for NL.
Once you will evaluated the result of it for NL we will show for world wide or not.

**Comment by Famlam** [comment]
Thanks!

**Comment by frodrigo** [comment]
Deployed, update in progress.
http://osmose.openstreetmap.fr/en/errors/?country=netherlands*&item=8300&class=53

**Comment by Famlam** [comment]
I've checked all 109 detections in NL. These were the false positives/negatives:
- 1 was a Mapillary detection error (not a oneway sign)
- 1 is disputable with the current tagging ( [way](https://www.openstreetmap.org/way/7035307); [error](http://osmose.openstreetmap.fr/nl/error/b6b6dfa7-e4e9-0c09-d825-fb0ac9653d1a) ): `opening_hours` instead of `oneway:conditional` and missing bicycle exceptions.
- 1 is disputable how it should be tagged (no access + oneway sign; [error](http://osmose.openstreetmap.fr/nl/error/6eb99b45-b313-1da9-b6fd-e1a11db32705) )
- 1 was a sign announcing a oneway starting in 300m
- 2 involved [waterways that have oneway restrictions](https://wiki.openstreetmap.org/wiki/Key:oneway#On_waterways) (although both weren't tagged as such yet), which weren't detected yet ([error](http://osmose.openstreetmap.fr/en/error/a61ce93c-4264-25e9-3f8f-7cc0576ee71e)). 

Also I removed the suggested fix to add `oneway=yes` as it often requires `oneway:*` tags (too).
https://github.com/osm-fr/osmose-backend/pull/1154

All other 103 cases seemed to be valid missing oneway tagging. (Some of which on service roads, so not always as important, but that also applies to i.e. speed limits). So I'm very content with the results. 

Would you like me to enable it globally?

**Comment by frodrigo** [comment]
Ok for enable it globally. Add it to the PR.

**Comment by Famlam** [comment]
Added and marked the PR as ready! Thanks!

**Comment by frodrigo** [comment]
Globaly deployed
http://osmose.openstreetmap.fr/en/errors/?item=8300&class=53
