### ISSUE TITLE
Untagged area object for area:highway

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1127]
https://www.openstreetmap.org/way/476632984 has some problems (area:highway without `highway=*` line inside, unneded `area=yes`), but "Untagged area object" is not one of them

https://osmose.openstreetmap.fr/en/error/562cfa6f-15e5-d624-7a94-374715a4b348

**Comment by matkoniecz** [comment]
https://github.com/osm-fr/osmose-backend/pull/1016/files seems to be usable as base for PR

**Comment by matkoniecz** [comment]
>  @frodrigo frodrigo reopened this 2 minutes ago 

Do you prefer skipping "fixes #CODE" in PRs?

**Comment by frodrigo** [comment]
Only the fix/fixes part. It auto-closes the issue. But I prefer mark as ready and only close when deployed and result verified.

**Comment by frodrigo** [comment]
Deployed, Update in progress.
