### ISSUE TITLE
Untagged named object for cemetery=sector

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1128]
https://www.openstreetmap.org/way/191474963 probably should be ref=A, not name=A but is not untagged

https://wiki.openstreetmap.org/wiki/Tag:cemetery%3Dsector

https://osmose.openstreetmap.fr/en/error/3acbe9c0-e5fb-ecb2-baa0-ebb4c9eadbee

**Comment by matkoniecz** [comment]
https://github.com/osm-fr/osmose-backend/pull/1016/files seems to be usable as base for PR

**Comment by matkoniecz** [comment]
found in latest: 

https://github.com/osm-fr/osmose-backend/blob/912b5438a01f6426ac21386f7106f52f010d4909/plugins/TagFix_MultipleTag.py#L31

Though I am unsure what `ford` is doing in the list of main tags...

**Comment by frodrigo** [comment]
Yes, make a new PR.

**Comment by Famlam** [comment]
(For ford, see #992 )

**Comment by frodrigo** [comment]
Deployed, Update in progress.
