### ISSUE TITLE
Tag "addr:street" not matching a street name around error unclearly displayed in listings

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1129]
https://osmose.openstreetmap.fr/en/byuser/Mateusz%20Konieczny?level=2 and search for "Orle Gniazdo"

![screen15](https://user-images.githubusercontent.com/899988/106023395-0c891180-60c7-11eb-9d2a-dda86d79fb61.png)

it is display of https://osmose.openstreetmap.fr/en/error/f6b19ab2-5edb-3429-467c-cd5387f8dccc

In overview listing it is completely unclear what is reported, unlike with other errors

**Comment by frodrigo** [comment]
Please suggest some improvement for the text part here:
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_associatedStreet.py#L657

**Comment by frodrigo** [comment]
Update in progress.
