### ISSUE TITLE
Double listing of Andhra Pradesh

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#113]
Andhra Pradesh is listed two times in osmose_config.py with differing projection settings. Looks suspicious. Please confirm this is a bug or close this issue if it is correct.

```
india_state("andhra_pradesh", 2022095, proj=32644)
india_state("andhra_pradesh", 2022095, proj=32645)
```

**Comment by jocelynj** [comment]
Thanks, I will soon fix this.
