### ISSUE TITLE
linter explodes on "analyser_merge_wikipedia_FR.py:23: error: No parent module"

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1138]
`analysers/disabled/analyser_merge_wikipedia_FR.py:23: error: No parent module -- cannot perform relative import` crash one of checks

#1137 attempted to fix it and failed

**Comment by frodrigo** [comment]
See pr #1137

**Comment by stephankn** [comment]
#1137 fixed it. mypy needs python modules correctly set up to be able to ignore files. `__init__.py` within the disabled folder fixes this. mypy now runs and finds further issues.

**Comment by frodrigo** [comment]
Thank all.
