### ISSUE TITLE
Maybe mention extra packages needed for Ubuntu 20.04?

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1141]
https://github.com/osm-fr/osmose-backend/blob/master/INSTALL.md#install on  Ubuntu 20.04 required also

`sudo apt-get install ninja-build libarchive-dev extra-cmake-modules flex bison` for PyKOpeningHours dependency that needed to be compiled. Is it worth mentioning?

Without that `pip install -r requirements.txt` was not completing successfully.

**Comment by frodrigo** [comment]
Yes new packages are required since we add PyKOpeningHours.
But I do not maintain INSTALL.md any more. Primary target is Docker.
cc @jocelynj

**Comment by matkoniecz** [comment]
Would you accept PR adding this packages to listing?

**Comment by frodrigo** [comment]
Yes please.

**Comment by jocelynj** [comment]
I don't have ninja-build on my script for updating backends. Only these ones from https://github.com/osm-fr/ansible-scripts/blob/master/roles/osmose-backend/tasks/main.yml#L80:
```
    - cmake
    - extra-cmake-modules
    - qtbase5-dev
    - flex
    - bison
    - libarchive-dev
 ```

**Comment by matkoniecz** [comment]
Without `ninja-build` PyKOpeningHours was refusing to compile, but later I added more packages. Maybe one of later ones would be able to replace it?

**Comment by jocelynj** [comment]
`ninja-build` is in fact installed by `cmake`, as it is a dependency.
