### ISSUE TITLE
Split reports titled "Inconsistent tagging of {{1.key}}" to allow display of less confusing names

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1144]
Currently some issues are displayed with `{{1.key}}` shown to normal users, what is confusing to them.

It would be nice to change that, so that for example "Unexpected proposed tag" is shown instead that would be more clear.

It seems to me that it would require splitting existing single report into multiple.

From https://discord.com/channels/413070382636072960/763192797775265864/804515317534687262 where I convinced someone to try Osmose

![screen22](https://user-images.githubusercontent.com/899988/106242718-66ddbb80-6208-11eb-92b9-fbe20b9c8fc9.png)
![screen23](https://user-images.githubusercontent.com/899988/106242939-c8058f00-6208-11eb-90e8-ac33359798ec.png)

I understand technical reasons for that, but it was also confusing to me when I tried using Osmose in Vespucci, and making things legible to the point of disabling it in this editor.

**Comment by frodrigo** [comment]
Please, can you give item/class id to help point on source code for this or it is a general issue ?
If on Osmose side, can be done. If on JOSM, need to have a talk with them.

**Comment by matkoniecz** [comment]
I have not found this specific one, but similar ones are from JOSM.

**Comment by frodrigo** [comment]
See here how to improve: https://github.com/osm-fr/osmose-backend/blob/master/doc/2-PluginMapCSS.md#message

**Comment by matkoniecz** [comment]
So https://github.com/osm-fr/osmose-backend/blob/1eca30496e752f9bb7e839a818d4a05575376a90/plugins/Construction2.validator.mapcss should be modified  by adding https://github.com/osm-fr/osmose-backend/blob/master/doc/2-PluginMapCSS.md#groups

**Comment by frodrigo** [comment]
Yes
