### ISSUE TITLE
analyser_merge_pitch_FR data source no longer available

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1146]
The CSV used in `analysers/analyser_merge_pitch_FR.py` is no longer available, the analyser currently run using the cached resource.

The data is now a zipped xlsx. Format not supported by Osmose.

There is now 3 files in place of one.

**Comment by frodrigo** [comment]
Original data
[Uploading 20180110_RES_FichesEquipements.zip…]()

**Comment by frodrigo** [comment]
https://www.data.gouv.fr/fr/datasets/recensement-des-equipements-sportifs-espaces-et-sites-de-pratiques/#discussion-60148062b55b544a3b677648

Data may be back in CSV.

cc @gileri

**Comment by gileri** [comment]
I don't see it yet.

But I subscribed to the data source to see whether they'll use CSV when updating the resources.

**Comment by gileri** [comment]
Thank you, @frodrigo !
