### ISSUE TITLE
area=no is fine on closed way of barrier=hedge

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1147]
http://osmose.openstreetmap.fr/en/error/81648adb-8f83-0b5a-1ced-8b3690e29685 

Such closed way may represent either area or way.

Being specific here is fine

**Comment by frodrigo** [comment]
From JSOM validator
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/deprecated.mapcss
cc @Klumbumbus

**Comment by Klumbumbus** [comment]
The linked error thas nothing to do with hedges.

**Comment by matkoniecz** [comment]
@Klumbumbus Sorry! It should be http://osmose.openstreetmap.fr/en/error/55ee369d-200d-d9e5-4e81-09d59954d3d8

**Comment by frodrigo** [comment]
So. Not linked to JOSM validator.

**Comment by frodrigo** [comment]
This plugin ask to remove useless `area=no` tag.
It is an early plugin in Osmose-QA, we does not more add rule of this kind any more.

**Comment by frodrigo** [comment]
Change nothing. It is not worng.
