### ISSUE TITLE
Analysis Build error Max retries exceeded with url

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-backend#1148]
Hello, 
As I can see in the [last updates matrix](http://osmose.openstreetmap.fr/en/control/update_matrix) there are a buch of builds failing since several days.

Build in error : https://buildbot.osmose.openstreetmap.fr/#/builders/471/builds/158

Maybe the error is related with this worker `aquilenet`

Could you please fix this?
Thanks

**Comment by frodrigo** [comment]
There is an was issue on OSM-FR internal network with ipv6. But it should fixed now.
@jocelynj , @Marc-marc-marc do you have update on this?

**Comment by frodrigo** [comment]
https://github.com/osm-fr/infrastructure/issues/262

**Comment by jocelynj** [comment]
We had a bridge ipv6->ipv4 on backend aquilenet, needed by osmosis update, and this bridge failed because of the ipv6 issue we had a few days ago.

I've disabled this bridge: now, aquilenet will directly access download.openstreetmap.fr through ipv6 address.

**Comment by jocelynj** [comment]
I was able to manually launch osmose on backend aquilenet for spain_comunidad_de_madrid, but got several retries to update the local pbf file with diffs from download.openstreetmap.fr. It looks like we have connection issues between aquilenet and the download server.

**Comment by jocelynj** [comment]
I've proposed a change on pyosmium to be more robust on connection issues: https://github.com/osmcode/pyosmium/pull/163

This change is already applied on aquilenet backend, and we should be able to check if it resolves the issue

**Comment by frodrigo** [comment]
Thank all. We are back on track.
