### ISSUE TITLE
problem with lanes counting

### ISSUE THREAD

**Issue by it4workflow** [osm-fr/osmose-backend#115]
> Falsche lanes Verwendung 
(turn:lanes:forward=2) != (lanes:forward=1)
way 368396836 rawedit josm edit 
highway = tertiary 
lanes = 3 
lanes:backward = 1 
maxspeed = 50 
ref = K 526 
turn:lanes:forward = left|right 
Problem gemeldet am: 2016-06-17

Why does osmose assume lanes:forward=1 in this case? 
lanes=3 - lanes:backward=1 should be lanes:forward=2 ;)

in the meanwhile i've replaced lanes:backward=1 into lanes:forward=2 cause turn:lanes also tagged as forward.

**Comment by jocelynj** [comment]
Osmose assumes lanes:forward = 1 as it is the default number of lanes for tertiary.

It could have deduced that lanes:forward is equal to 2 by doing lanes - lanes:backward, but I think it complexifies the logic a bit. Shouldn't both lanes:forward and lanes:backward be specified ?

**Comment by mueschel** [comment]
My idea about parsing lanes tags is: 
1) If lanes is given, but nothing else - split in half for each direction on oneway=no
2) If 2 out of lanes, lanes:forward, lanes:backward are given, calculate the missing one
3) lanes:both_ways (e.g. center turn lanes) must be specified if present (and mapped).

**But** I think it is wrong to assume that the number of turn:lanes should be equal to lanes: 
lanes=* specifies only full-width lanes for cars but does not count for smaller lanes like bike lanes. There was even some discussion whether short turn lanes should be counted or not. All the *:lanes tags on the other hand take every lane into account, no matter how wide or what they are used for.
Possible checks include whether all *:lanes are the same lane count and whether *:lanes has at least as many entries as there are lanes=*.

**Comment by it4workflow** [comment]
> Shouldn't both lanes:forward and lanes:backward be specified ?

I think, this leads into an open end discussion about should, could, have to :/

**Comment by kdano** [comment]
this recent commit caused false errors with lanes:both_ways:

> Conflict between lanes number
> on two way, (lanes=1) != (lanes:both_ways=1 * 2) 

Why does it count a lane for both ways as two lanes?

**Comment by frodrigo** [comment]
humm, you are right, I misunderstood the both_ways suffix when I rewrite the checks.
