### ISSUE TITLE
"Probably only for bottles, not any type of glass" listed in online only mode

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1150]
It does not qualify for edits without survey (and in areas where it qualifies it should be fixed by mass replace in JOSM or other bot edit)

http://osmose.openstreetmap.fr/en/error/18b6ca6a-4cca-c783-5dbf-f7f48879462d

**Comment by frodrigo** [comment]
Until now I see no area where exists a mix of `recycling:glass_bottles=yes` and `recycling:glass=yes`.
If in your area it is `recycling:glass=yes` we can disable this check.

**Comment by matkoniecz** [comment]
Well, for areas where `recycling:glass=yes` can be assumed without survey one may just run mass replace - doing it manually is rather waste of time (hm, maybe I should do it in Poland).

PS: if you plan do this, see https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct

**Comment by frodrigo** [comment]
I do not plan any automated edtis.
