### ISSUE TITLE
Unfinished power minor line - mention location:transition=yes

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1153]
https://wiki.openstreetmap.org/wiki/Tag:location:transition%3Dyes

Current description:

> Unfinished power minor line

> The line ends in a vacuum, and should be connected to another line or a transformer (power=transformer) or a generator (power=generator).

http://osmose.openstreetmap.fr/pl/error/21ad4b69-67bd-86ac-97fa-d6804b5698dd

source | 8467
-- | --
item | 7040
class | 6

**Comment by frodrigo** [comment]
Please, make a PR for this one.

**Comment by matkoniecz** [comment]
Yep, I will make it. I just created issue as I am talking right now with another mapper and helping him with Osmose.
