### ISSUE TITLE
Reimport JOSM rules

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1155]
"Combined foot- and cycleway without segregated." was reduced to stop pointless spam such as http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.0598&lon=19.93511&item=xxxx&level=1%2C2%2C3&tags=&fixable=&issue_uuid=fe5323a2-4c59-5bcc-a40c-4554c04f383d http://osmose.openstreetmap.fr/en/error/fe5323a2-4c59-5bcc-a40c-4554c04f383d

It would be nice to have this fix also in Osmose.

https://josm.openstreetmap.de/ticket/20318

https://josm.openstreetmap.de/changeset/17457/josm appears to have not appeared in latest Osmose update.

**Comment by matkoniecz** [comment]
Or maybe Osmose pulls from  josm-tested (version 17428 right now)?

**Comment by frodrigo** [comment]
Update done.
