### ISSUE TITLE
Detect dead wikipedia/wikidata links

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1157]
`wikipedia` and `wikidata` targets are sometimes deleted and sometimes never existed.

See for example https://www.openstreetmap.org/way/654731887 that links nonexisting https://en.wikipedia.org/wiki/en:Tanaklak%20Island%20(Alaska) ( not reported by Osmose http://osmose.openstreetmap.fr/en/map/#zoom=14&lat=51.95727&lon=-176.10612&item=xxxx&level=1%2C2%2C3&tags=&fixable= )

This is not something rare or unusual (though outright deleted wikidata entries are quite rare).

See for example Arizona: https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/Arizona,%20USA.html

I am not sure how it should be implemented. My method of calling Wikimedia API for every single link would not scale well (or maybe running some worker slowly going through all links and rechecking existing reports is acceptable?) and dealing with importing and upgrading Wikipedia and Wikidata dumps would be obnoxious.

**Comment by matkoniecz** [comment]
> If you want it. Do it.

Is there an existing validator that crawls external dataset and that I can use as an inspiration?

**Comment by frodrigo** [comment]
External validator content can be pushed to the fronted directly.
An XML file must be uploaded.
https://wiki.openstreetmap.org/wiki/Osmose#Issues_file_format

**Comment by turbotimon** [comment]
Note that it exists for `Wikidata` (currently around 1,626 issues): https://osmose.openstreetmap.fr/en/issues/open?item=3031&source=&class=2&username=&bbox=

**Comment by frodrigo** [comment]
> Note that it exists for `Wikidata` (currently around 1,626 issues): https://osmose.openstreetmap.fr/en/issues/open?item=3031&source=&class=2&username=&bbox=

Yes. Thank.
