### ISSUE TITLE
please improve the wiki documentation

### ISSUE THREAD

**Issue by it4workflow** [osm-fr/osmose-backend#116]
Could you please improve the wiki documentation in matters of ...
... some more detailled descriptions of errors
... the background or rather your intentions of errors
... some how-to-repair examples of erros

e.g. there's a discussion in the German OSM forum why [this](http://osmose.openstreetmap.fr/de/map/#zoom=17&lat=53.0468075&lon=8.9726116&item=7090&level=2) is an error.

I think for clarity reasons you also could point out your classifications (grade 1 to 3) into ...
... what is an error
... what could be an error
... what is a nive to have fixing

Also i think a improvement of your wiki documentation can help OSM and OSMOSE beginners to get better. Now beginners see a lot of errors, want to fix them and don't know how, especially if they are the "last" user of an object with a long history.

**Comment by frodrigo** [comment]
You are right the wiki is poor, but it is a wiki, everybody can enhance it ;-)

> what could be an error

There is no such issues reported by Osmose

Issues reported because they broke a rule, not because they could eventually broke one.

**Comment by it4workflow** [comment]
> Need fix

is an error? ;)

> You are right the wiki is poor, but it is a wiki, everybody can enhance it ;-)

But how can we improve it, when we don't know which rule is broken? Have a look to the error mentioned above: we've discussed it, but nobody can definitely say, what's the broken rule...

**Comment by frodrigo** [comment]
> But how can we enhance it, when we don't know which rule is broken? Have a look to the error mentioned above: we've discussed it, but nobody can definitely say, what's the broken rule...

Maybe it's an error on the check. It's this check:
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_feature_on_way.py#L47

**Comment by EwenH** [comment]
hi, sorry to jump in however  a little more detail on these two issues would be useful.

**- Access -**  	
**Including car, horse, moped, hazmat and so on, unless explicitly excluded**
http://osmose.openstreetmap.fr/map/#zoom=17&lat=-23.5108144&lon=113.8137174&item=3220&level=2
http://osmose.openstreetmap.fr/map/#zoom=17&lat=-34.4428784&lon=140.9642570&item=3220&level=2

** Relation **
** Restriction relation, wrong number of members ** 
http://osmose.openstreetmap.fr/map/#zoom=17&lat=-23.5295521&lon=148.1623790&item=3180&level=2
http://osmose.openstreetmap.fr/map/#zoom=17&lat=-23.5468481&lon=148.1610129&item=3180&level=2
-

**Comment by frodrigo** [comment]
I updated the wiki pages with the new missing issues from Osmose.
Then, I added some detail as @EwenH requested.
