### ISSUE TITLE
Way node tagged like way in node aeroway=parking_position	

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-backend#1161]
Hello,

Issues are being detected in nodes tagged with  `aeroway=parking_position`

According to the wiki, nodes are allowed to be tagged like this. https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dparking_position

Issue detected:
http://osmose.openstreetmap.fr/en/error/3f89d075-ad26-5e32-e536-bf976421601a

Could you fix this rule-check to avoid issues in this kind of nodes?

Thanks

**Comment by frodrigo** [comment]
The issue is not about the tag in the node, but also on the way.
https://www.openstreetmap.org/way/556730213
https://www.openstreetmap.org/node/5370126426
