### ISSUE TITLE
"Call" from OGC Service of a SDI  regional plateform ?

### ISSUE THREAD

**Issue by jerbou** [osm-fr/osmose-backend#1166]
We have callback from our CKAN ressource not found.

```
CKAN_CURRENT_URL | '/dataset/59d07ea2-ca9a-444a-b977-0e32b280af1c/resource/ddfa8db8-0cf5-4e72-9504-072c96b2c328/service_proxy?SERVICE%3DWFS%26VERSION%3D2.0.0%26REQUEST%3DGetFeature%26TYPENAME%3Dpei71_acbdd5c%26OUTPUTFORMAT%3Dgeojson%26CRSNAME%3DEPSG%3A4326'

HTTP_USER_AGENT | 'python-requests - https://osmose.openstreetmap.fr/'
```

We made contact with the producer of the data, we made corrections, and we want to discuss / exchange with the people from Osmose who made the call. The URI and the url from the dataset :
https://trouver.ternum-bfc.fr/dataset/points-deau-incendie-repertories-en-saone-et-loire
the ressource has changed, and we want to stop the raise of the error, and the people "behind" Osmose user have to change / correct the OGC call (the "win" a correct ressource, and we "win" to stop a error message.

Best Regards.
IDéO BFC team

**Comment by frodrigo** [comment]
Thank you for reporting the issue, we will fix the call to this dataset.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_hydrants_FR.py#L102

**Comment by jerbou** [comment]
Thanks for this so quickly replie ! :1st_place_medal: 

For info, we havec others hydrants from others SDIS 21 (Cote d'or) , SDIS 39 (Jura) and SDIS 90, but this are not all ckeck with the AFIGEO schema. (modele minimale in french).
We work with them to this "standarisation".

Maybe we can tell them, that OSM community needs the datas ?

**Can i close this particular issue ?**

**Comment by frodrigo** [comment]
cc @flacombe

Please, keep this open until deployed and fixed.

**Comment by frodrigo** [comment]
cc @wetneb

**Comment by frodrigo** [comment]
URL updated and deployed.
