### ISSUE TITLE
Enhance 3130 (Plugin TagFix_Brand.py) : suggest the brand:wikidata tag when only the brand tag is on the node

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osmose-backend#1169]
I'll use https://www.openstreetmap.org/node/6974650360 as example
This node represents a Promovacances travel_agency in Lyon.

Current tags in osm:
```
brand = Promovacances
name = Promovacances
shop = travel_agency
```

Promovacances is part of the name-suggestion-index : promovacances-9ff76a with 
```
    {
      "displayName": "Promovacances",
      "id": "promovacances-9ff76a",
      "locationSet": {"include": ["fr"]},
      "tags": {
        "brand": "Promovacances",
        "brand:wikidata": "Q3407444",
        "brand:wikipedia": "fr:Promovacances",
        "name": "Promovacances",
        "shop": "travel_agency"
      }
    }
```

Code of the plugin : https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Brand.py

### Current behavior

The plugin doesn't suggest adding brand:wikidata=Q3407444 because it only selects nodes where the tag "brand" is absent

### Suggested behavior

I suggest to select nodes where the tag "brand" is absent or the tag "brand:wikidata" is absent

I actually see two options:
1 select nodes where the tag "brand" is absent or the tag "brand:wikidata" is absent:
- Pros: less nodes to be processed
- Cons : won't suggest brand:wikipedia or additional secondary tags (clothes= , shoes=, ...)

2 select nodes with tag name and with tag amenity or shop without checking for brand or brand:wikidata

**I can work on the change myself then submit a pull request but would like your feedback before I spend time on it**

**Comment by frodrigo** [comment]
We should not override the existing brand. Maybe look for `brand:wikidata` from `brand`.
Can also look how NSI is used elsewhere.

> I can work on the change myself then submit a pull request but would like your feedback before I spend time on it

Please do.

**Comment by nuxper** [comment]
From what I understand of the code, the plugin only suggests adding tags, never override.

OK I'll work on this.

**Comment by frodrigo** [comment]
cc @nlehuby @Marc-marc-marc

**Comment by nlehuby** [comment]
Yes, that would be a good addition :+1: 
Your first option is my preference to limit false positives.

**Comment by frodrigo** [comment]
It is deployed, but your changes lower the number of raised issues by 100 000.
http://osmose.openstreetmap.fr/en/errors/?item=3130
http://osmose.openstreetmap.fr/en/errors/graph.png?item=3130&start_date=2020-02

**Comment by nuxper** [comment]
Great news, thanks.

I don't see the decrease on the graph for the moment : 
![image](https://user-images.githubusercontent.com/7891262/107990698-46b64680-6fd5-11eb-88d8-d0141d9897ad.png)

Is there a refresh issue ?

**Comment by frodrigo** [comment]
> Is there a refresh issue ?

Will refresh this night.

But I was expect a raise of issues, not a lower number, was not?

**Comment by nuxper** [comment]
Yeah I was expecting the figure to increase.
I've added a verification that the tags_to_add is not empty.
Is there a way to know which ones disappeared ?

**Comment by frodrigo** [comment]
> Is there a way to know which ones disappeared ?

No

**Comment by frodrigo** [comment]
Maby be retry in local and look at results.

**Comment by nuxper** [comment]
Good Idea, I'll check

**Comment by nuxper** [comment]
The figures actually seem in the increase

![Screenshot from 2021-02-16 23-33-09](https://user-images.githubusercontent.com/7891262/108130128-69b52900-70af-11eb-8716-b058b32a353e.png)

I think we are good

**Comment by frodrigo** [comment]
Ok, look good. Thank you.
