### ISSUE TITLE
remove naptan option for "missing object kind"

### ISSUE THREAD

**Issue by boothym** [osm-fr/osmose-backend#117]
In the UK there have been imports of bus stops from the naptan database (public transport) in various regions. For those which have not been verified on the ground and had highway=bus_stop added to the node, Osmose shows these in "missing object kind". As seen in the image, in parts of Scotland near me there are so many unverified naptan nodes that it makes it almost impossible to find other types of nodes with a missing object type.
![untitled-1](https://cloud.githubusercontent.com/assets/16965772/16300132/31a6f030-3936-11e6-9862-7c9d940c8d41.jpg)

Could you please add an option to hide these errors when viewing the map in the UK? Or create a new error type for UK mappers? Thanks

**Comment by frodrigo** [comment]
You can uncheck the item on the left panel.

**Comment by frodrigo** [comment]
I move away Naptan import from "Missing object kind". Add a new check similar to "seamark:fixme" item.
Wait few days for result on the slippy map.

**Comment by frodrigo** [comment]
Ok. It's done.
http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=52.570302&lon=1.66635&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=2110%2C4060%2C8010&level=1%2C2%2C3&tags=&fixable=

**Comment by boothym** [comment]
Thanks! :)
