### ISSUE TITLE
Add bicyle parking merge for Bordeaux Metropole

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1170]
Remove for Bordeaux city, need to be replace with data from Bordeaux Metropole
https://opendata.bordeaux-metropole.fr/explore/dataset/st_arceau_p/information/

**Comment by gileri** [comment]
I can do it if you're not already on it

**Comment by frodrigo** [comment]
> I can do it if you're not already on it

Not on it.

**Comment by frodrigo** [comment]
Deployed
http://osmose.openstreetmap.fr/fr/errors/?item=8150&class=50
