### ISSUE TITLE
All ways on island marked as unconnected.

### ISSUE THREAD

**Issue by double-a** [osm-fr/osmose-backend#1172]
There are multiple small islands on which it seems that all ways are marked as not connected. 
E.g. http://osmose.openstreetmap.fr/de/map/#item=1210&zoom=11&lat=-8.0236&lon=157.1862&level=1&tags=&fixable=
But you will find others around Micronesia, Vanatu or Solomon Islands.
Specific example:
http://osmose.openstreetmap.fr/de/error/3d69e668-ecdd-c25b-5f13-bdba305fe7ae
Item 1210, class 4

No ferry lines exist, thus no connection to other road network parts are available.

**Comment by frodrigo** [comment]
The doc must be improved add the objects making network as connected.
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_floating_islands.py#L37-L46
