### ISSUE TITLE
Add integration of operator:wikidata from name-suggestion-index

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osmose-backend#1174]
name-suggestion-index added a list of operators and the corresponding operator:wikidata
This will be integrated in future version of id but the list already exists.

I suggest to add the detection of operator matching an entry in name-suggestion-index

FOREACH node
   IF node has the "operator" tag but no "operator:wikidata" tag 
        IF "operator" is in name-suggestion-index
            suggest adding the operator:wikidata from name-suggestion-index
      
I can work on this but would like your feedback first:
* Do you agree with the idea ?
* Should I create a new plugin or complete the TagFix_Brand.py or create a TagFix_Operator.py ?
* If I should create a new plugin, what item class id should I use ?

**Comment by frodrigo** [comment]
I am ok with it.
I see no need to create a new plugin. Just a new class in it under the same item.

cc @nlehuby

**Comment by nuxper** [comment]
ok for me
so item 3130 class 31302 ? I'm not completely clear on the item / class / subclass notions ;)
do I need to register the class to the frontend somehow ?

**Comment by frodrigo** [comment]
Yes this class is free 
http://osmose.openstreetmap.fr/en/errors/?item=3130&class=31302

FYI https://github.com/osm-fr/osmose-backend/blob/master/doc/0-Index.md#concepts-of-osmose-qa-issue

**Comment by frodrigo** [comment]
It is the goal to have all this tags? That a lot!

![imagen](https://user-images.githubusercontent.com/1785486/108760093-80df9500-754d-11eb-87f1-9b1671790c1d.png)

**Comment by nuxper** [comment]
Yes I'm a bit hesitant on the subject too.
I see the same problem with post_boxes.
The problem is more with the name-suggestion-index than the plugin I believe. I think atms and post_boxes shouldn't include that many tags.
My point of view: the information is actually accurate. Those tag values are correct and legitimate. But does the community want to have all those tags on all the atms and post_boxes ? not sure.
I'll open an issue on the name-suggestion-index on the matter to discuss and link it here. Worst case I could limit the plugin to only add operator:wikidata but I think it would be fixing the problem in the wrong place.

**Comment by frodrigo** [comment]
I got this stange suggestion

http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=44.81259&lon=-0.590057&item=xxxx&level=1%2C2%2C3&tags=&fixable=josm&issue_uuid=c70da878-6848-8afe-ed37-099cebead1b7

```diff
Operator can be completed with operator:wikidata
node 609072408 josm iD edit

+ brand = AutoCool

amenity = car_sharing
capacity = 2
name = Talence Forum
operator = AutoCool
```

**Comment by nuxper** [comment]
that should be fixed by the latest fix on name-suggestion-index. 
The script in nsi used to systematically add a brand tag in the operator entries ( see comments on https://github.com/osmlab/name-suggestion-index/issues/4925 )
I think it needs to be deployed.

**Comment by frodrigo** [comment]
The code pass no more the test
https://github.com/osm-fr/osmose-backend/runs/1993890050?check_suite_focus=true

**Comment by nuxper** [comment]
Thanks, I'll work on this.
I believe the error comes from a slight change in nsi.json format, not really related to this ticket. But whatever the reason, I'm on it.
