### ISSUE TITLE
Warning on roundabout traffic direction wrong on US Virgin islands

### ISSUE THREAD

**Issue by double-a** [osm-fr/osmose-backend#1175]
Erroneous warning of wrong direction of roundabout.
Left-hand traffic can be seen on the highways around and roundabout is going clockwise, thus it seems that the country-wide traffic direction is incorrect.

In contrast to US the traffic is left handed on US Virgin islands, e.g. Puerto Rico or Saint Croix 
See https://en.wikipedia.org/wiki/United_States_Virgin_Islands

Item 1050, Class 1
Example on Puerto Rico
http://osmose.openstreetmap.fr/de/error/41d6f8d9-7b31-ad00-b2a8-ff8da759a047
Example of Saint Croix
http://osmose.openstreetmap.fr/de/error/ee0fa452-c4df-eab9-380d-8b6cbac7dfb5

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_roundabout_reverse.py#L62

**Comment by frodrigo** [comment]
Only US Virgin Islands have to be switched, that your point, doesn't?

**Comment by frodrigo** [comment]
Deployed, but not working.

**Comment by frodrigo** [comment]
One left. But wrong direction detection.
http://osmose.openstreetmap.fr/en/errors/?country=usa_virgin_islands&item=1050

**Comment by frodrigo** [comment]
Configuration if OK and well deployed on the server
https://github.com/frodrigo/osmose-backend/blob/master/osmose_config.py#L1171

**Comment by frodrigo** [comment]
My bad. I was sure it was deployed before, but I was wrong.
Now it is OK. And new real positive issues are found.
