### ISSUE TITLE
Probable erroneous sig :: A way connects directly to the street classification much smaller. [...]

### ISSUE THREAD

**Issue by JacLavi** [osm-fr/osmose-backend#1176]
Osmose spits an error :  A way connects directly to the street classification much smaller. motorway_link, primary_link, trunk_link, secondary, secondary_link

When : one go from « highway=motorway_link » to « highway=service »

See : http://osmose.openstreetmap.fr/fr/error/b167e086-89fe-d3a4-0cda-12d7e6b3651e

**Comment by Marc-marc-marc** [comment]
imho the whole parking should be a highway=service, including the small one connected to the highway=motorway
_link is for highway=* between 2 transit highway... but the parking isn't a part of "transit" highway

**Comment by frodrigo** [comment]
> imho the whole parking should be a highway=service, including the small one connected to the highway=motorway
> _link is for highway=* between 2 transit highway... but the parking isn't a part of "transit" highway

Wiki tell to use `_link` in this case: https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservices
