### ISSUE TITLE
Exclude power=minor_line from unfinished line test?

### ISSUE THREAD

**Issue by CloCkWeRX** [osm-fr/osmose-backend#118]
Unlike major power lines, minor lines can terminate on a power pole (connected to houses afterwards). OSMose treats those as errors and gets a high false positive rate.

**Comment by boothym** [comment]
According to the wiki, you can add pole=transition to the end of a power line. http://wiki.openstreetmap.org/wiki/Tag:power=pole

But yes I agree that it would be nice to separate the unfinished power line check into major/minor lines.

**Comment by frodrigo** [comment]
Major power line
http://osmose.openstreetmap.fr/fr/errors/?item=7040&class=2

Minor power line
http://osmose.openstreetmap.fr/fr/errors/?item=7040&class=6

**Comment by EwenH** [comment]
Thank you - that makes a lot of sense and allows the main power lines to be rectified.
