### ISSUE TITLE
Change osmose suggestion for type:FR:FINESS = 223

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osmose-backend#1180]
@vinber 
The wiki describes the tagging of the PMI's
https://wiki.openstreetmap.org/wiki/FR:Comment_cartographier_un_(sant%C3%A9)#PMI

It should be
     amenity=social_facility
    social_facility=ambulatory_care
    social_facility:for=child
and not healthcare=yes

Thanks.

**Comment by vinber** [comment]
ah, ok je n'avais pas fait le lien avec @zorglubu :)
pour rappel c'est ici que cela se passe : https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json

**Comment by zorglubu** [comment]
c'est le même sur mastodon ;-)

**Comment by vinber** [comment]
> c'est le même sur mastodon ;-)

oui j'arrive à faire ce lien :D

j'ai fait une proposition mais ce que je ne sais pas c'est pourquoi cela propose healthcare=yes je n'arrive pas trouver où cela se passe (mais j'imagine, espère que cela ne le propose que si il n'y a pas de choses plus précises) à voir

**Comment by zorglubu** [comment]
Il faudrait faire à l'identique pour type=230

**Comment by zorglubu** [comment]
J'ai l'impression que c'est ça, les types 223 et 230 n'étant précisés nulle part, ça doit leur mettre le truc santé par défaut "healthcare=yes". Dans le fichier json, je ne comprends pas comment sont gérés les catégories et classes, et comment on décide d'en créer une nouvelle ? Bon, on verra le résultat de ta proposition.

**Comment by vinber** [comment]
> Il faudrait faire à l'identique pour type=230

si c'est à l'identique, on doit alors pouvoir l'ajouter directement, je regarde.

**Comment by vinber** [comment]
> Dans le fichier json, je ne comprends pas comment sont gérés les catégories et classes, et comment on décide d'en créer une nouvelle ? Bon, on verra le résultat de ta proposition.

les catégories dans le fichier correspondent au ref finess

les classes c'est plus obscurs, c'est le regroupement de diverses sources pour le front je crois et ça c'est @frodrigo qui gère :+1:

**Comment by frodrigo** [comment]
RTFM https://github.com/osm-fr/osmose-backend/blob/master/doc/0-Index.md#classes-of-issues

**Comment by vinber** [comment]
même en RTFM je ne suis toujours pas sur de comprendre :D

**Comment by zorglubu** [comment]
Comme tu as fait le commit, on peut tester demain ? Ou il faut attendre plus pour la mise à jour des données ?

**Comment by frodrigo** [comment]
First I will test the PR, then merge it if valid.
Later we will deploy the commit, and the days after you will have the result.

**Comment by vinber** [comment]
Concerning class, could i find list of all classes ?

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=3270&useDevItem=all
the cl column

**Comment by vinber** [comment]
thanks but it's only for one item.
Could we have all classes, not class for one item ?

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=xxxx&useDevItem=all&country=france%2a
