### ISSUE TITLE
Generalize fix:* tags in analysers

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-backend#1182]
I see that in http://osmose.openstreetmap.fr/api/0.3/tags we have available three `fix:*` tags : chair, imagery, survey. To make issues more easily reusable by third party tooling, would it make sense to :
- Introduce a `fix:picture` tag for issues that can be fixed with street-level pictures ?
- Generalize the presence of these tags in all analysers to have a precise idea for every analyser on how it can be fixed ?
- Document these tags so they can be used by developers working on analysers more easily ?
- (on frontend side) Display all these fix tags values in UI ?

I would like to spend some time on this task if there isn't any particular problem with it, and if you don't see any technical issue that would require major architecture change.

**Comment by frodrigo** [comment]
* `fix:picture` does not have almost the same meaning as `fix:survey`?
* Generalize the presence of these tags. -> I agree, but lot of works.
* Display all these fix tags values in UI: already show

Yes, you can work on this. About the frontend UI, note, switching in progress to Vue js.

cc @Marc-marc-marc

**Comment by PanierAvide** [comment]
Maybe it's a bit arbitrary, but I think it might make sense to distinguish picture/survey, examples :
- Street numbers on houses : they are rarely correctly visible from street pictures, needs survey
- Fire hydrants : can be seen correctly on street pictures and by survey
- Destination signs on motorways : quite dangerous or difficult to survey without pictures

By reading that all tags are already shown, I just realized that the "Avec correction" select field isn't about `fix:*` tags, but issues list of fixes... So UI already handles this, it's just not really clear.

**Comment by frodrigo** [comment]
Deployed
