### ISSUE TITLE
type:FR:FINESS=6111 (healthcare=laboratory) match a amenity=social_center

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1187]
http://osmose.openstreetmap.fr/fr/error/85343524-b247-aebc-4d4f-d1d383668bbd
item | 8341
class | 73
https://www.openstreetmap.org/way/39232008 main tag building+amenity=social_facility

if I understand correctly

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_healthcare_FR_finess.py#L88
is a dynamic match (not any static osm tag for the match, but several according opendata datas)

https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json#L92  and L103 mean that the match is with healthcare=laboratory
but as this tag is not on the osm object, I'm wrong somewhere :)

**Comment by frodrigo** [comment]
class 70 already in use for laboratory, the new PMI should be class 140.
https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json#L314

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=8340&class=140

**Comment by frodrigo** [comment]
Deployed. Not working.

**Comment by frodrigo** [comment]
Ok, on 141
http://osmose.openstreetmap.fr/en/errors/?item=8340&class=141
