### ISSUE TITLE
LaPoste : add brand:wikipedia together with brand

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1189]
during creation/modificationof a amenity=post_office, add brand:wikipedia together with brand
it avoid have the suggestion after the next run, via nsi

**Comment by frodrigo** [comment]
Only `brand:wikipedia`?

NSI suggest to add:
```diff
+brand:wikidata = Q373724
+brand:wikipedia = fr:La Poste (entreprise française)
+operator:wikidata = Q373724
+operator:wikipedia = fr:La Poste (entreprise française) 
```

**Comment by UKChris-osm** [comment]
Just an FYI, the NSI has removed the "_brand_" from post office, but retained "_operator_" where operator and brand are the same.

+operator:wikidata = Q373724
+operator:wikipedia = fr:La Poste (entreprise française)

**Comment by Marc-marc-marc** [comment]
duplicating human readable values (:wikipedia) by machine readable values (:wikidata) is imho non-consensual, so I still code it but I don't want to activate this kind of controversial stuff by default while adding the non-controversial part anyway (adding :wikipedia)

**Comment by frodrigo** [comment]
Close because out Osmose scope.
Talk about this issue on NSI.
