### ISSUE TITLE
tourism=attraction doesn't require attraction=*

### ISSUE THREAD

**Issue by superrache** [osm-fr/osmose-backend#1192]
According to that OSM wiki: https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dattraction
attraction key is not required for a tourism=attraction feature.
In the theme park Legoland : http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=55.735267&lon=9.12782
we get attribute lack with only tourisme=attraction and name=*

**Comment by frodrigo** [comment]
It for marker like this one?
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=55.735387&lon=9.128321&item=xxxx&level=1%2C2%2C3&tags=&fixable=&issue_uuid=2cd4af16-c6de-0a4c-d2b6-8ef67a1edfb2

name = Miniland
tourism = attraction 

It come from JOSM validator
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss#L367

cc @Klumbumbus

**Comment by matkoniecz** [comment]
>  attraction key is not required for a tourism=attraction feature.

It is true, but 

> name = Miniland
> tourism = attraction

without any other tags is not a sufficient tagging. It just specified that it is a tourism attraction without specifying what it is.

**Comment by Klumbumbus** [comment]
JOSM only warns if the object has only tourism=attraction or only tourism=attraction + name=*. This is fine as in these cases the object lacks the information what it actually is. This is written also in the wiki.  _"In such cases it is always possible to improve tagging by adding more specific tags describing object itself._ "

**Comment by Klumbumbus** [comment]
This issue can be closed imho.

**Comment by frodrigo** [comment]
@Klumbumbus Thank
