### ISSUE TITLE
Untimely returns of ref:FR:Tisséo

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osmose-backend#1196]
Hello,
Je trouve plein de faux positifs dans les alentours de Toulouse avec les numéros de référence des arrêts de bus gérés par l'opérateur Tisséo.
Voir par exemple les points verts ici https://osmose.openstreetmap.fr/en/map/#zoom=15&lat=43.59479&lon=1.34303&item=xxxx&level=1&tags=&fixable=&issue_uuid=b1f7d246-b95d-af59-3f81-6793ef995c35

On est pourtant sur un tag bien valide cf. https://wiki.openstreetmap.org/wiki/Toulouse/Transports_en_commun#R.C3.A9seau_Tiss.C3.A9o

Est-ce un oubli ou bien une erreur ?

**Comment by frodrigo** [comment]
It is not false positive, `é` in the key tag are not in convention.

> The key of tag contains characters not recommended. The key is composed of alphanumeric characters: 0-9, a-z (preferably lower case), separator '_' or ':'. See [Any_tags_you_like#Syntactic_conventions_for_new_tags](https://wiki.openstreetmap.org/wiki/Any_tags_you_like#Syntactic_conventions_for_new_tags).

**Comment by frodrigo** [comment]
Fill be fixed in the data.

**Comment by overflorian** [comment]
That's fixed cf. https://wiki.openstreetmap.org/wiki/Mechanical_Edits/overflorian-mass-edits/ref:FR:Tiss%C3%A9o
