### ISSUE TITLE
Incorrect "typo in tag, tracks -> traces" for railways

### ISSUE THREAD

**Issue by Yogurt4** [osm-fr/osmose-backend#1199]
Source 6414, item 3150, class 1
[link](https://osmose.openstreetmap.fr/en/errors/?country=hungary&item=3150&level=1)

The [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:railway#Tracks) says it's a valid, moreover, useful tag for railways.
I guess the checker should ignore railways.

(It's a useful warning for highways though.)

**Comment by frodrigo** [comment]
It is an automatic statistical based suggestion. tracks -> traces must be black listed.
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_tag_typo.py#L51

**Comment by frodrigo** [comment]
But `traces` is undocumented tag only present in Hungary.

https://taginfo.openstreetmap.org/keys/traces#map

**Comment by Yogurt4** [comment]
Please don't mix the two.

I know of the tracks/paths with the indeed undocumented `traces` tags. Historically, these are to mark how many GPS tracks/traces were recorded to draw them. So far they were pardoned by the Hungarian community. (Nevertheless, they are correctly spot by Osmose.)

The issue is about `railway`s, and in the opposite direction (e.g., `tracks` being correct).

**Comment by frodrigo** [comment]
Yes. I understand your point. But what annoys me it as add a rule based on undocumented and local tag.
No plan to remove these `traces` tags ?

**Comment by Yogurt4** [comment]
Nonono. You don't need to add anything based on a local tag. Just please accept the valid, global and documented `railway` + `tracks`.

Regarding `traces`, I'm a strong supporter for "kill'em'all". Unfortunately, there is a guy who objects deleting anything. There is another who thinks `traces` is useful until we resurvey them with an RTK receiver (and can give them a proper `accuracy` tag). There was a proposal to convert trace count to virtual accuracy (like `traces=1` -> `accuracy=30`) but rejected.

**Comment by frodrigo** [comment]
Ok. I white list `track`, but not `traces`.
