### ISSUE TITLE
Mapillary traffic sign country-based interpretation?

### ISSUE THREAD

**Issue by mcvarer** [osm-fr/osmose-backend#1200]
https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json

Awesome repository, 

what do the **g1-g2-g3-g4** tags in the traffic signs in this JSON file mean?
**also** how did you extract the 
#### not_for 
and 
#### only_for 
information.

**Comment by frodrigo** [comment]
The code of traffic signs are from https://www.mapillary.com/developer/api-documentation/#traffic-signs

`only_for` and `not_for` use the country codes or prefixes from the configuration: 
https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L647
