### ISSUE TITLE
Invalid character warning for Serbian-Latin

### ISSUE THREAD

**Issue by Yogurt4** [osm-fr/osmose-backend#1201]
Source 6391, Item 5070 (Invalid character), Class 50701 (Some value chars does not match the language charset)
https://osmose.openstreetmap.fr/en/errors/?country=hungary&item=5070&level=1,2,3#

The [Serbian language](https://en.wikipedia.org/wiki/Serbian_language#Writing_system) uses two alphabets: Cyrillic and Latin. They both are in use. There is no different ISO-639 language code for the two however.
Osmose rejects texts in the Latin, like "name:sr"="Ambasada Republike Srbije".

**Comment by frodrigo** [comment]
The configuration for `sr`
https://github.com/osm-fr/osmose-backend/blob/master/modules/languages.py#L89-L90
```
  'sr': ['Cyrillic'],
  'sr-Latn': [u'[A-Za-zČĆĐŠŽčćđšž]'],
```

**Comment by Yogurt4** [comment]
With respect to the fact that >50% of the current names are in Latin, should mappers use "name:sr-Latn" for all these objects?

I think these two lines should be merged into
```
  'sr': ['Cyrillic', [u'[A-Za-zČĆĐŠŽčćđšž]']],
 
```instead.

**Comment by frodrigo** [comment]
Not sure about that. Do you have link with the local community to ask?

**Comment by Yogurt4** [comment]
Well, the rule of the Serbian community **within** Serbia is to use name:sr for the Cyrillic text solely and they're quite conservative about it. Therefore, within Serbia, they use the name:sr-Latn tag extensively even though it's only in a proposal stage.
They even require Cyrillic transliteration of Latin texts, and they use the default "name" tag for the Cyrillic version even if the actual place/board has the name in Latin.

So I guess I will adapt their way and replace name:sr instances to name:sr-Latn ones.

They have a [forum on the Serbian language](http://forum.openstreetmap.org/viewforum.php?id=62) and a http://lists.openstreetmap.org/listinfo/talk-rs.
Their Telegram group is @osm_sr.
