### ISSUE TITLE
Please add "checkpoint" as an object

### ISSUE THREAD

**Issue by Yogurt4** [osm-fr/osmose-backend#1203]
Source 6391, Item 2110 (missing object kind), Class 21101 (Untagged named object)
https://osmose.openstreetmap.fr/en/errors/?source=6391&item=2110&class=21101#

Osmose gives this error for [checkpoints](https://www.openstreetmap.org/node/6814306461), for example.
According to the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:checkpoint), it's a valid object kind and they do not require additional main tags, like `tourism` or `amenity`.

There are also renderers using this key, like [turistautak.hu](http://turistautak.hu).

**Comment by frodrigo** [comment]
To de added here
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag.py#L31
