### ISSUE TITLE
Osmose raises an error when tag housenumber is used in the member of an associatedstreet relation but also member of another relation

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osmose-backend#1205]
Item 2060 class 1
http://osmose.openstreetmap.fr/fr/error/4e1daae5-8324-8ef2-b0e3-f34278110a79

osmose reports an issue for a housenumber node member of:
* associatedstreet relation
* provides_feature relation

2060 reports that addr:housenumber or addr:housename without addr:street, addr:district, addr:neighbourhood, addr:quarter, addr:suburb, addr:place or addr:hamlet must be in a associatedStreet relation. It shouldn't report this issue as the node is member of an associatedStreet relation.

I believe I found the problem in the code. I'll submit a PR

**Comment by frodrigo** [comment]
To be tested. but probably something like this
```sql
WHERE
     (relation_members.member_id IS NULL OR relations.id IS NOT NULL) AND
     ...
```
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_associatedStreet.py#L80

**Comment by nuxper** [comment]
Hi @frodrigo ,

Thanks for your feedback.

I checked your suggestion but do not reach the expected result. Can I ask your help ?:

### Taking a step back and focusing on nodes only first:

If I understand correctly, sql01 should return the nodes which seem to be address nodes (with a addr:housenumber or addr:housename tag)

The intention is also to get the information
- whether or note the addr:street (or similar) exists
- whether the node is a member of an associatedStreet (or similar) relation

In order to do that, sql01 would left outer join the table of (nodes with a addr:housenumber) to the table of (members of an associated street relation)

### my understanding...
...is that members of an associated street relation should be an inner join:

```
relation_members
INNER JOIN relations ON
	relation_members.relation_id = relations.id AND
	relations.tags?'type' AND
	relations.tags->'type' IN ('associatedStreet', 'street')
```
	
I tested this solution which was in the PR and as far as I could tell, the fix worked as intended. I checked the differences (before->after fix) at least in Lyon.

### If I try to use a LEFT JOIN...
... between relation_members and relations then restrict it in the where clause, 

```
WHERE
     (relation_members.member_id IS NULL OR relations.id IS NOT NULL) 
```
     
then the nodes that have a addr:housenumber tag, are NOT in an associatedstreet but ARE in another type of relation are no longer in the result (example : 6440629970)

### Can you help please ? ;) :
Have I understood your suggestion correctly ?
Can you please give me a hint why you don't think the PR is the right thing to do ?


### Alternative
I also tried a different wording which returns the same records if you think it's better:

```
WITH members_of_street AS (
	SELECT
		relation_members.member_id AS m_id,
		relations.id AS r_id,
		relation_members.member_role AS member_role,
		relations.tags->'name' AS r_name
	FROM
        relation_members
        JOIN relations ON
            relation_members.relation_id = relations.id AND
            relations.tags?'type' AND
            relations.tags->'type' IN ('associatedStreet', 'street')
	WHERE
		relation_members.member_type = 'N'
)
SELECT
    'N'::CHAR(1) AS type,
    nodes.id,
    ST_Transform(geom,4326) AS geom_proj,
    members_of_street.r_id AS rid,
    members_of_street.member_role AS role,
    nodes.tags?'addr:flats' AS flats,
    coalesce(nodes.tags->'addr:housenumber', nodes.tags->'addr:housename') AS number,
    nodes.tags->'addr:door' AS door,
    nodes.tags->'addr:unit' AS unit,
    members_of_street.r_name AS r_name,
    nodes.tags->'addr:street' AS addr_street,
    coalesce(nodes.tags->'addr:street', nodes.tags->'addr:district', nodes.tags->'addr:neighbourhood', nodes.tags->'addr:quarter', nodes.tags->'addr:suburb', nodes.tags->'addr:place', nodes.tags->'addr:hamlet') AS name
FROM
    nodes
    LEFT JOIN members_of_street ON nodes.id = members_of_street.m_id
WHERE
    nodes.tags != ''::hstore AND
    nodes.tags ?| ARRAY ['addr:housenumber', 'addr:housename'];
```

**Comment by frodrigo** [comment]
Update in progress
http://osmose.openstreetmap.fr/fr/error/4e1daae5-8324-8ef2-b0e3-f34278110a79
http://osmose.openstreetmap.fr/en/issues/open?item=xxxx&source=411754&useDevItem=all&class=1
