### ISSUE TITLE
Create separate, high severity error for unconnected rivers

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1207]
Background: I am trying to use OSM river data and wanted to start from fixing some obvious data issues.

Sadly, "Unconnected waterway or wrong way flow" has mix of reports for all waterway types and fixing thousands of errors just to fix one serious data quality issue affecting my current project is not feasible.

Also, stream issues often require resurvey and are not fixable from aerial images alone.

So I think that separate issue for river issues only would be useful. 

"Unconnected major waterway or wrong way flow" ?
 
http://osmose.openstreetmap.fr/en/map/#zoom=13&lat=50.9137&lon=10.1728&item=1220&level=1%2C2%2C3&tags=&fixable=&issue_uuid=2d5a56a2-97a1-a16a-b996-44bfe4e2bd2f

**Comment by frodrigo** [comment]
Can be spited into two class with different levels
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_waterway.py#L154

**Comment by matkoniecz** [comment]
>  good first issue

Maybe, but it is not exactly trivial to fix. I will look again into it later.

**Comment by frodrigo** [comment]
Could be done with a switch https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_building_overlaps.py#L194

**Comment by frodrigo** [comment]
I implemented it. But most of remain issues are like `ул. "3-та", ул. "2-ра"`. I think it it not ok and should raise issue?

**Comment by frodrigo** [comment]
Split river/strem done
http://osmose.openstreetmap.fr/en/errors/?item=1220&class=2,3
