### ISSUE TITLE
Detect natural=water water=river without river

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1209]
`waterway=riverbank` without river are detected, but there is ongoing attempt to retag all of them to `natural=water water=river `

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_waterway.py#L147

**Comment by frodrigo** [comment]
Yes, both or new schema will be used.

**Comment by frodrigo** [comment]
Done. But number of issue failing. Not the expected result.

http://osmose.openstreetmap.fr/en/issues/open?item=1220&class=1
http://osmose.openstreetmap.fr/en/issues/graph.png?item=1220&class=1&start_date=2021

**Comment by frodrigo** [comment]
False alert. It Is OK.
