### ISSUE TITLE
Add an analyser for Nantes data on recycling containers

### ISSUE THREAD

**Issue by tomao44** [osm-fr/osmose-backend#121]
There is a wiki page for [glass recycling containers in Nantes](http://wiki.openstreetmap.org/wiki/Nantes/Projets/Recyclage#Conteneurs_.C3.A0_verre).
I saw that an analyser exist for Bordeaux : [analyser_merge_recycling_FR_cub.py](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_recycling_FR_cub.py)
So I try to do the same for Nantes : [analyser_merge_recycling_fr_nm_glass-py](https://gist.github.com/tomao44/a69c47a4139616a26a44fdcd415c6660#file-analyser_merge_recycling_fr_nm_glass-py)

How could I test this ?

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=8120,8121,8122

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=8120,8121,8122&source=25874
Results are available on frontend
