### ISSUE TITLE
item 2090 duplicate identical fix

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1213]
item 2090
class  1

show twice : 
fix_index | 0
type id | N 308001706
create | crossing traffic_signals | crossing | traffic_signals |  
crossing | traffic_signals |  
modify |  
delete |  

https://osmose.openstreetmap.fr/fr/error/54387666-9a10-62df-68da-9baa1623dc55

**Comment by frodrigo** [comment]
Fix #0 change one object, while fix #1 two.
