### ISSUE TITLE
check phone number format

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osmose-backend#1217]
I'd like to suggest a new plugin to check the validity and format of phone numbers.
I'm happy to write the code. I just want to check that it doesn't already exist and the filter makes sense.

My analysis for the moment:
* The wiki suggest to use an international format ( https://wiki.openstreetmap.org/wiki/Key:phone ) however the format depends on the convention of local communities. For the moment, I suggest to start just with France
* I made a random sampling on Lyon, Paris, Bordeaux, Angers, Decazeville:
  - 25 have format +33 X XX XX XX XX
  - 2 have format +33 XXXXXXXXX
  - 7 without spaces +33XXXXXXXXX
  - 4 are short numbers only available locally (e.g.  3631 for La Poste)
=> the standard seems to be accepted in France to use an international format when possible
* I tried an imperfect overpass query: https://overpass-turbo.eu/s/14WP based on regexp but my intention is to use libphonenumber
* My intention is to be able to suggest the correct phone number when possible using libphonenumber (local -> international format)

2 questions if you think it's alright for me to make an attempt:
* which item number and class number should I use ?
* how can i restrict it to France for the moment ?

**Comment by frodrigo** [comment]
There is already an advanced phone number validator.
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Phone.py

**Comment by nuxper** [comment]
how on earth haven't I seen it ???
Thanks ;)
