### ISSUE TITLE
False positive for "Object tagged twice as way and relation"

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1220]
https://osmose.openstreetmap.fr/en/error/f48e5330-cb8f-20a1-83d6-00d8684dcbce

https://www.openstreetmap.org/relation/12410466  `leisure=track` multipolygon

https://www.openstreetmap.org/relation/12410465 inside that there is multipolygon representing grass

https://www.openstreetmap.org/way/835495846 - separate `leisure=track` and inner of grass multipolygon

This two tracks are separate, tagging is valid.

**Comment by frodrigo** [comment]
It is a know issue. Just mark it as false positive.

**Comment by matkoniecz** [comment]
Sorry for an insufficient research then.

**Comment by VladimirMorozov** [comment]
Does "known issue" mean that it is technically impossible to fix it? I've found multiple instances of this issue, but I don't understand why are they closed. The message is confusing and doesn't help.

**Comment by frodrigo** [comment]
Yes the problem with this false positives is known and there are few of this. So no fix is planned. Maybe is doable, but the work of doing this and the over computation required maybe not worth the cost.
