### ISSUE TITLE
Report highway=residential without any nearby buildings

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1221]
For example see https://www.openstreetmap.org/way/881911882#map=17/27.21891/86.79112

http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=27.218151&lon=86.790865&item=xxxx&level=1%2C2%2C3&tags=&fixable=

It was proposed by someone in Nepal who mentioned that it would be very useful for cleanup of mass scale HOT edits and reveal either unmapped buildings or misused `highway=residential`

**Comment by frodrigo** [comment]
But what is the issue with that?

**Comment by matkoniecz** [comment]
It indicates either missing data or wrong `highway` value.
