### ISSUE TITLE
Report buildings without any nearby highway=* at all

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1222]
It would be useful to report `buildings` without any nearby `highway=`, as it would reveal places where such things need to be mapped.

See for example http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=27.230639&lon=86.801015&item=xxxx&level=1%2C2%2C3&tags=&fixable= http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=27.224386&lon=86.767605&item=xxxx&level=1%2C2%2C3&tags=&fixable= http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=26.965998&lon=87.585867&item=xxxx&level=1%2C2%2C3&tags=&fixable= http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=26.93834&lon=87.618901&item=xxxx&level=1%2C2%2C3&tags=&fixable= http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=26.897181&lon=87.662347&item=xxxx&level=1%2C2%2C3&tags=&fixable=

buildings with `ruins=yes`, `abandoned=yes` etc probably should be skipped

triggered by https://www.facebook.com/groups/osmnepal/permalink/4004338302944931/ where such tool was requested (in Nepal it would be especially useful to cleanup HOT mapping after 2015 eathquake)

**Comment by frodrigo** [comment]
It is not done, because it is a too expensive computation.

**Comment by matkoniecz** [comment]
So I guess that if someone needs such reports it should be done via own processing + Maproulette? (or own private server)

**Comment by frodrigo** [comment]
Yes, there is similar implementation on France area, but it is done by an external analyser and push to Osmose.

http://osmose.openstreetmap.fr/en/issues/open?item=7170
