### ISSUE TITLE
Case of wrong wikidata id suggested

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osmose-backend#1225]
It's about 13561 - 3130 «This name is very common, is this store part of the brand network?»

There was a bank with
name=Caixabank
brand=La Caixa

The suggestion was Q4163407 (Fundación "la Caixa") instead of Q847225 (Caixabank), Q4163407 is too general.

Is this the right place to report issues with this dataset?

**Comment by Identitaet** [comment]
Okay so this actually a weird case since it seems that this data is actually correct in the NSI already
and looking at the history it seems to be the case for a longer time

**Comment by frodrigo** [comment]
There is a cache of 30 days on Osmose side.
