### ISSUE TITLE
item 8xxx is empty

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osmose-backend#1228]
Hello,

For the last few days the item http://osmose.openstreetmap.fr/fr/errors/?item=8020 has been empty.
Could you check what is happening ? Thanks.

**Comment by frodrigo** [comment]
We have an issue with most of the open data merge since yesterday.

**Comment by frodrigo** [comment]
Caused by #1230
Repopulating in progress.

**Comment by zorglubu** [comment]
Merci  ;-)
