### ISSUE TITLE
Many names from the BD TOPO IGN are dropped

### ISSUE THREAD

**Issue by archie83** [osm-fr/osmose-backend#1229]
In the BD TOPO, the files "statut_du _toponyme" can have these values:
- Validé
- Collecté
- Régional
- Historique
- Autre

But In these three analysers of osmose-backend:
- analyser_merge_cemetery_FR.py
- analyser_merge_man_made_FR.py
- analyser_merge_poi_FR.py,

only the names that have the status "Validé" are proposed for merging.

I checked the stats:

The file cimetiere.gpkg contains:
- 290 names with status "Validé"
- 1270 names with status "Collecté" 
--> 81% of the names are dropped.

The file construction_ponctuelle.gpkg contains:
- 5772 names with status "Validé"
- 1566 names with status "Collecté"
--> 21% of the names are dropped.

The file zone_d_activite_ou_d_interet.gpkg contains:
- 65835 names with status "Validé"
- 272216 names with status "Collecté"
--> 81% of the names are dropped.

**Globally, 79% of the names are dropped.**

Since every item will be checked by a contributor, I think osmose should propose all the names for merging.

**Comment by frodrigo** [comment]
The name is not proposed as new tag, but still show to the contributor

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_cemetery_FR.py#L53
