### ISSUE TITLE
Construction: Distinguish between meaning of check_date and opening_date

### ISSUE THREAD

**Issue by mikini** [osm-fr/osmose-backend#123]
An object tagged as under construction, having no opening_date and a check_date which is exceeded will be flagged by Osmose. This is contrary to my expectation as check_date doesn't say anything about expected construction end but only establishes the date when the state was last confirmed (http://wiki.openstreetmap.org/wiki/Key:check_date).

I experienced this (thanks to @elgaard for [bringing attention to it](https://lists.openstreetmap.org/pipermail/talk-dk/2016-July/004655.html)) on V2 of this building under construction; http://www.openstreetmap.org/way/374778346/history. It got this error id; http://osmose.openstreetmap.fr/en/error/7323389683 (I messed around in the UI and got it deleted from the db unfortunately, I'm not very experienced with Osmose).

I can confirm this in the code at https://github.com/osm-fr/osmose-backend/blob/master/plugins/Construction.py#L35 where opening_date and check_date are handled as if they are identical. In this specific situation where no construction end/opening date is known, the flagging ought to be subject to the 2 year timeout also used when no end date is tagged, but calculated from the check_date not the last edit timestamp.

BTW: it's a separate issue, but It doesn't look like the search for construction tags would detect the [Lifecycle prefix](http://wiki.openstreetmap.org/wiki/Lifecycle_prefix) I tagged in addition to construction=yes (construction:man_made=water_works) (or maybe I'm not fluent enough in Python to see it?)

**Comment by frodrigo** [comment]
Just remove `check_date` as object timestamp change when `check_date` is set.
