### ISSUE TITLE
False positive "The track of this route contains gaps"

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1231]
Item: 1260
Class: 1

Example: http://osmose.openstreetmap.fr/nl/error/d6cde8a3-79b7-a700-ce1e-7a4f2040b79e

This railway route (and a few others) is reported to contain gaps, whereas it seems like a continuous route to me.
(From: [analyser_osmosis_relation_public_transport.py](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_public_transport.py))

**Comment by Yogurt4** [comment]
Are there proper "railway" tags all along on all the ways? I've seen a similar issue where one piece was tagged as "construction" (incorrectly, as this was temporary).

**Comment by Famlam** [comment]
It appears to me that every way contains either railway=rail or railway=platform (the latter with role=platform).
Some nodes have a 'role' as stop position without railway=stop, but this doesn't cause this warning at other trajectories either.

**Comment by frodrigo** [comment]
The osmose issue no more exists.

Please reopen if there is still an issue.

**Comment by Famlam** [comment]
The issue is back again, perhaps this issue can be re-opened?

http://osmose.openstreetmap.fr/nl/issue/c1151416-a3db-3c29-dcd5-f5d0849bae83
http://osmose.openstreetmap.fr/nl/issue/d694c0a5-75f8-a3f7-b4d5-8892c6d02d04
http://osmose.openstreetmap.fr/nl/issue/d50f8e9c-6043-f4bf-654a-3493e135d179

Two train lines and one bus line for which I cannot find a gap in the track

**Comment by Famlam** [comment]
@frodrigo  (not sure if you see closed issues without @-mention)
