### ISSUE TITLE
building shape

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1234]
Suggested fix must not raise issue from SQL query

#885

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_building_shapes.py#L40

**Comment by habi** [comment]
Since this is tagged as 'good first issue' I'm happy to try to tackle this :)

I have *no* experience with SQL queries, is it as simple as expanding the query in the above linked line 40 by 'ger' and/or 'hut'?

**Comment by frodrigo** [comment]
Yes, not not only for building but also man_made.
