### ISSUE TITLE
False positive: "Object must be close to coast or water" pier (or quay) far from water 

### ISSUE THREAD

**Issue by AdVerburg** [osm-fr/osmose-backend#1237]
Many piers (man-made=pier) are marked See: [Example map](http://osmose.openstreetmap.fr/en/map/#country=france_haute_normandie_seine_maritime&zoom=11&lat=49.5984&lon=0.6172&item=1221&level=1%2C2%2C3&tags=&fixable=)  while those piers are pretty well (partly) in water, or inside landuse=basin.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_water.py#L145

Distance is set to 30m, maybe too short.

**Comment by frodrigo** [comment]
Distance set to 50m.
