### ISSUE TITLE
False positive: "Similar names"

### ISSUE THREAD

**Issue by Dimitar5555** [osm-fr/osmose-backend#1240]
In Bulgaria we have quite a lot of streets which don't have actual names but instead have numbers. For example "ул. 1-ва" (First street), "ул. 2-ра" (Second street) etc. Osmose detects streets that are named like this and start with "ул." as similar names although they aren't. 
This is the check that is returning these results: https://osmose.openstreetmap.fr/en/errors/?source=29816&item=5080&class=1#

**Comment by frodrigo** [comment]
Need to write one rule like this
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_name_close.py#L29-L30

Are you able to write it ? or give sufficient info to do it ?

**Comment by Dimitar5555** [comment]
This regex expression should be able to catch all.

**Comment by Dimitar5555** [comment]
Is anything wrong with my expression or you expected something else?
Just letting you know of the common syntax in case the expression is wrong: usually but not always the name starts with either "ул." or "улица". Then there could be a space but some people don't add it. After that there is the street number, dash and two letters in Cyrrilic. I've made the letters part oversimplified because there would be too many possible cases. The numbers usually reach the thousands.
There could be any amount of numbers before these numbers. The letters in the end correspond to the respective numbers and the amount of digits before these digits doesn't change the ending.

```
1-ва
2-ра
3-та
(same up to 6)
7-ма
8-ма
9-та
10-та
20-та
30-та
100-тна
```

**Comment by frodrigo** [comment]
Sorry, not checked yet. Missing free time to do it.

**Comment by frodrigo** [comment]
I implemented it. But most of remain issues are like `ул. "3-та", ул. "2-ра"`. I think it it not ok and should raise issue?

**Comment by Dimitar5555** [comment]
According to [WikiProject Bulgaria](https://wiki.openstreetmap.org/wiki/Bg:WikiProject_Bulgaria#.D0.98.D0.BC.D0.B5.D0.BD.D0.B0_.D0.BD.D0.B0_.D1.83.D0.BB.D0.B8.D1.86.D0.B8_.D0.B8_.D0.B1.D1.83.D0.BB.D0.B5.D0.B2.D0.B0.D1.80.D0.B4.D0.B8) street names should not include "ул." in their name neither they should have quotes but there is no "Improper format of the street name" or similar error in Osmose as far as I know.

**Comment by frodrigo** [comment]
![imagen](https://user-images.githubusercontent.com/1785486/121817327-07e18600-cc81-11eb-8e1e-4bbc7947eed6.png)

Deployed and look good.
