### ISSUE TITLE
supervised vs crossing:supervision

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osmose-backend#1241]
Item : 9015 
class : 9015029 
link to sample error : https://osmose.openstreetmap.fr/en/error/088af7ab-9414-1f1a-83cd-01373bb2caed

This analyser reports an error on a node because the key-value "supervised"="no" is used and suggests "crossing:supervision"="no" instead (node https://www.openstreetmap.org/node/2571357555 )

From what I could see:
- the wiki page for supervised exists but I couldn't find a documentation for crossing:supervision : https://wiki.openstreetmap.org/wiki/Key:supervised
- taginfo reports **8 396** use of crossing:supervision in the world ( https://taginfo.openstreetmap.org/keys/crossing%3Asupervision#overview ) versus **232 842** for "supervised" ( https://taginfo.openstreetmap.org/keys/supervised )

I'm not sure whether I should report this here or find the openrailwaymap repository.

**Comment by frodrigo** [comment]
Yes, this rule come from the JOSM openrailwaymap validator. Please contact the project to fix it.
If you no able to do so and still think it as a bad check. We can disable it in Osmose anyway.

https://josm.openstreetmap.de/wiki/Rules

**Comment by nuxper** [comment]
Ok thanks. I'll contact the project and link to this issue

**Comment by frodrigo** [comment]
Issue reported, close here.

**Comment by Famlam** [comment]
The fix is live :)
https://osmose.openstreetmap.fr/nl/issues/graph.png?item=9015&start_date=2022
