### ISSUE TITLE
Unconnected Highway Question

### ISSUE THREAD

**Issue by hungerburg** [osm-fr/osmose-backend#1243]
Hello Frodrigo,

this is not to dispute the positive, although I had no problem mapping that*), but from reading the analyzer source, I do not see, why a track produces the message, while I am pretty certain, that a path wont.

https://osmose.openstreetmap.fr/en/error/edfd24a7-e37f-0a5a-d7b1-3d52518fead2

Peter

(* Lately on a hike i spotted recent activity there, an orchard got planted near the start. The track itself is old, serviced some huts below in the 30ies. I made the track start in the meadow, because it is not used much, so that traffic leaves no traces between its start and the ending of the (connected) other track higher up the meadow and trail_visibility=none seemed silly to me. Again, not to dispute the positive, I live fine with dozens of unmapped fords (over imaginary streams :)

**Comment by frodrigo** [comment]
As you can access from the meadow without defined track, just mark it as false positive.

The analyser check the data of `highways` from https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Osmosis.py#L35, including `track`.

**Comment by hungerburg** [comment]
Thank You for the explanation!
