### ISSUE TITLE
False positives at 9002/9002014 (questionable key (ending with a number))

### ISSUE THREAD

**Issue by ZEE6de** [osm-fr/osmose-backend#1245]
In the United States, since the TIGER imports, there are hundreds of thousands of roads that use tags like "name_1" or "tiger:name_base_1" or "tiger:name_direction_prefix_1" or "tiger:name_type_1". These are all marked as possible errors, which is of course a false positive. [Example](https://osmose.openstreetmap.fr/de/error/056bc24b-f23f-f544-c7d9-7750e2a58b0e): [Most of the highlighted things are false positives.](https://osmose.openstreetmap.fr/de/map/#zoom=13&lat=39.0676&lon=-94.5384&item=9002&level=1%2C2%2C3&tags=&fixable=) Could you add a whitelist there, so that the mentioned tags are not detected as "probable" false?

**Comment by frodrigo** [comment]
This rule come JOMS Validator
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/deprecated.mapcss

cc @Klumbumbus

**Comment by matkoniecz** [comment]
`name_1` key is actually a mistake which should be fixed.

**Comment by Klumbumbus** [comment]
It is the intention of the rule to warn about keys like name_1, shop_1 or highway_1. The rules does't warn about the mention keys starting with "tiger". I would keep the rule as is.
