### ISSUE TITLE
Gas Stations Operator Problem in South Tyrol

### ISSUE THREAD

**Issue by MinerMax555** [osm-fr/osmose-backend#1247]
Greetings,

I'm a mapper from the bilingual province of South Tyrol (Alto Adige) from Northern Italy. I noticed that there are quite some wrong markers in my province where Osmose wants to update the operator of a gas station, for example this one:

osmose.openstreetmap.fr/en/error/6e7c424a-2872-42a5-a6fb-f11cc75dbd97

I noticed that the input dataset correctly contains both the German and Italian Operator name and uses ' % ' to differentiate between them.

Could this be converted to ' - ', the way we split our bilingual names here? The marker should not show up as an issue when the operator already matches, or when it's flipped (`German Operator - Italian Operator` instead of `Italian Operator - German Operator`)

**Comment by frodrigo** [comment]
cc @fansanelli

**Comment by fansanelli** [comment]
Hello @frodrigo and @MinerMax555 ,

I'll check this and come back to you with a patch in the next few days

Cheers
Francesco

**Comment by frodrigo** [comment]
Deployed

**Comment by frodrigo** [comment]
Please, could you check it is ok, now ?
