### ISSUE TITLE
Waterway connecting to lake

### ISSUE THREAD

**Issue by boothym** [osm-fr/osmose-backend#125]
When a river/stream connects to a lake (or other body of water), Osmose gives an "Unconnected waterway or wrong way flow" error. But the waterway is connected and is flowing in the correct direction!

Example: this stream connects to a lake http://www.openstreetmap.org/way/11652109#map=16/56.1095/-3.1838 which then flows out to the south.

Suppose I could mark them as false positives but would be easier if Osmose would stop flagging connections to lakes as errors.

**Comment by frodrigo** [comment]
From http://wiki.openstreetmap.org/wiki/Tag:waterway%3Driver
> Use waterway=river for the linear flow larger natural waterways, in flow direction. Note that the linear ways should form a complete routable description of the watercourse.

You to connect inbound and outbound stream.

**Comment by jocelynj** [comment]
@boothym do you agree with the proposed modification on OSM ?

Adding a waterway in the middle of the lake has the advantage of making easier to know what is the global direction of the waterflow of lake.

**Comment by frodrigo** [comment]
And make the water network continuous, it's like waterway and riverbank.

**Comment by frodrigo** [comment]
Please reopen if you still think there is a problem.

**Comment by platlas** [comment]
What to do if there is not outbound stream?
