### ISSUE TITLE
detect (ARABIC DAMMA, 0x064f) as invalid character in "alt_name" key

### ISSUE THREAD

**Issue by hubaishan** [osm-fr/osmose-backend#1256]
in 5070 invalid character
osmose detected "ُ" (ARABIC DAMMA, 0x064f) as invalid character in alt_name key while it a valid Arabic diacritic mark .
https://osmose.openstreetmap.fr/en/map/#item=5070&zoom=17&lat=30.556565&lon=41.146459&level=2&issue_uuid=a626bfdd-ae08-87c3-a8a7-7ee72cc29206

**Comment by frodrigo** [comment]
Is not only a script setting, but also by language (/country).
The rules are here https://github.com/osm-fr/osmose-backend/blob/master/modules/languages.py

Since I am not able to read Arabic, what change is required in this file?

**Comment by hubaishan** [comment]
Here is PR https://github.com/osm-fr/osmose-backend/pull/1259
