### ISSUE TITLE
Conditional lanes incorrectly identified as a lane count mismatch

### ISSUE THREAD

**Issue by BalooUriza** [osm-fr/osmose-backend#1258]
Highway_Lanes.py incorrectly assumes bicycle lanes are always narrow, a bad assumption, and should instead check for lane width if validation needs to be performed on lane size.  Please validate for lane access instead, same as any other conditional lane.

**Comment by frodrigo** [comment]
Please can point tags on wiki or on OSM data.

**Comment by BalooUriza** [comment]
https://wiki.openstreetmap.org/wiki/Key:access#Lane_dependent_restrictions

**Comment by BalooUriza** [comment]
https://www.openstreetmap.org/way/742059176

**Comment by frodrigo** [comment]
Issue no more here.
Please, comment and reopen if there is still something to do.
