### ISSUE TITLE
"REF/UAI missing" is unadapted for strcutures whichare not school

### ISSUE THREAD

**Issue by fk13** [osm-fr/osmose-backend#126]
In France, the tag amenity=kindergarten refers to places where young children spend some time before getting to school. The same tag refers to school when associated with the tag kindergarten:FR=maternelle.
Osmose should give the warning 7070 "   School without ref:UAI or invalid" only when the tag  kindergarten:FR=maternelle is not present, because UAI ref doesn't exist in this case.

**Comment by frodrigo** [comment]
- [ ] Split away kindergarten from school and build a new analyser
