### ISSUE TITLE
network added on stops by STAR analyser and removed by JOSM QA

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#1268]
On analysers/analyser_merge_public_transport_FR_star.py, network is added on bus stops.
But another analyser asks to but it only on relations.

key | value
-- | --
source | 407661
item | 8042
class | 84

Incompatible with:

key | value
-- | --
source | 407718
item | 9014
class | 9014007

[Example of network addition proposal](http://osmose.openstreetmap.fr/en/issue/ec8e77ee-1784-a7a1-cb17-9debca20b920)

[Example of network addition proposal](http://osmose.openstreetmap.fr/en/issue/adec5c1f-2f84-67b7-cb81-f4b67e6978ee)))

One, I guess STAR analyser should be updated.

**Comment by lenny31** [comment]
I have the same problem with transgironde analyser
analyser_merge_public_transport_FR_transgironde.py

http://osmose.openstreetmap.fr/fr/issue/947a719d-c5ba-c060-0b66-79937a260b83
source | 406748 / item | 8042 / class | 44 / lat lon | 44.6239451&nbsp;-1.2471931
Corrections : create | network=TransGironde

http://osmose.openstreetmap.fr/fr/issue/830a319d-1f4f-e980-83e4-260604b76f12
source | 406678 / item | 9014 / class | 9014007 / lat lon | 44.6938619&nbsp;-1.2356346
Corrections : delete | network
