### ISSUE TITLE
help with item 7160

### ISSUE THREAD

**Issue by fk13** [osm-fr/osmose-backend#127]
I have several 7160 issues ("admin_level 8 without addr:postcode")which I don't understand, as all of them are tagued with addr:postcode. what is wrong ?
example : [http://osmose.openstreetmap.fr/fr/error/7715335766]
on the whole  world, there are more than 35000 issues : is the analysis method still accurate? ([http://osmose.openstreetmap.fr/fr/errors/?item=7160&class=2])

**Comment by frodrigo** [comment]
Yes, there is something broken:
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=7160&class=2

It's a France only analyser.

**Comment by frodrigo** [comment]
Problably related to this commit https://github.com/osm-fr/osmose-backend/commit/e1d246c5d9e3771c83f3bc35b686eaa8ce16e654
