### ISSUE TITLE
Improve roundabout check rule

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osm-fr/osmose-backend#1271]
Osmose gives missing roundabout, after comparison with TMC data (https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_tmc_point_FR.py#L35).
But if there is a point "highway"="mini_roundabout", the error is also given.

Improvement: osmose shall also detect mini roundabout and don't indicate for missing roundabout around.

**Comment by frodrigo** [comment]
TMC are supposed to be on major road. And so not having mini roundabout.
Just mark it as false positive.
No interesting to implement it for few case.
