### ISSUE TITLE
Possible problem with unconnected way check.

### ISSUE THREAD

**Issue by FrakGart** [osm-fr/osmose-backend#128]
This error:

http://osmose.openstreetmap.fr/en/error/7733570355

refers to this way:

http://www.openstreetmap.org/way/151219842

which is connected to other highway=primary ways at both ends, so I can't figure what is supposed to be the problem.

**Comment by frodrigo** [comment]
Since you mark the issue as resolved or false positive I can't examine it.
You can un-false-positife the issue from this list:
http://osmose.openstreetmap.fr/en/errors/false-positive?country=australia*
Or if you just mark it as resolved, it will reappear by itself.
I'm not sure about which kind of Osmose-QA issues you encountred.

**Comment by FrakGart** [comment]
I marked it as resolved:

http://osmose.openstreetmap.fr/en/errors/done?country=australia_australian_capital_territory&item=1210

So I guess it will reappear.

**Comment by FrakGart** [comment]
The error hasn't come back. I'll close this and reopen if I ever find one again.

**Comment by FrakGart** [comment]
Ok, the errors came back:

http://osmose.openstreetmap.fr/en/error/7871381944
http://osmose.openstreetmap.fr/en/error/7871381943

which are linked by this bridge:

http://www.openstreetmap.org/way/184987524

**Comment by frodrigo** [comment]
@jocelynj the bridge is missing into the australian_capital_territory extract. Maybe it is corrupted.

**Comment by FrakGart** [comment]
Would a corrupted extract explain why this error keeps getting reported:

http://osmose.openstreetmap.fr/en/error/7974216557

despite the relation having been deleted a month ago:

http://www.openstreetmap.org/relation/5659470 ?

**Comment by jocelynj** [comment]
I can find this relation in the extract, which is quite strange. I'm checking why the diffs didn't pick this removal.

**Comment by frodrigo** [comment]
Reopen if problem persist.

**Comment by FrakGart** [comment]
I'm not sure if this is the same problem so apologies in advance.

There are a number of waterway errors being reported:

http://osmose.openstreetmap.fr/en/error/9494358825
http://osmose.openstreetmap.fr/en/error/9494356888
http://osmose.openstreetmap.fr/en/error/9494357299

but these are for ways that were deleted 4 months ago.

If I check in  http://download.openstreetmap.fr/extracts/oceania/australia/new_south_wales.osm.pbf

the ways are still there.

Should this be reported somewhere else?

**Comment by frodrigo** [comment]
You are in the rigth place. @jocelynj generate this files.
