### ISSUE TITLE
904: false positive "Giratoire n°5"

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-backend#1286]
[Example of false positive item](https://osmose.openstreetmap.fr/fr/map/#zoom=16&lat=45.05487&lon=5.0757&item=1010%2C1040%2C1050%2C1060%2C1070%2C1080%2C1090%2C1100%2C1110%2C1120%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1260%2C1270%2C1280%2C1290%2C2010%2C2020%2C2030%2C2080%2C2090%2C2100%2C2110%2C2120%2C2130%2C2140%2C2150%2C2160%2C3xxx%2C4xxx%2C5xxx%2C6xxx%2C7xxx%2C8010%2C8011%2C8012%2C8020%2C8021%2C8022%2C8025%2C8026%2C8030%2C8031%2C8032%2C8040%2C8041%2C8042%2C8050%2C8051%2C8060%2C8070%2C8080%2C8090%2C8091%2C8100%2C8101%2C8110%2C8120%2C8121%2C8122%2C8130%2C8131%2C8132%2C8140%2C8150%2C8160%2C8161%2C8162%2C8170%2C8180%2C8182%2C8190%2C8191%2C8192%2C8200%2C8201%2C8202%2C8210%2C8211%2C8212%2C8221%2C8230%2C8240%2C8250%2C8260%2C8270%2C8281%2C8282%2C8290%2C8300%2C8310%2C8320%2C8330%2C8331%2C8340%2C8341%2C8350%2C8351%2C8360%2C8370%2C8380%2C8381%2C8382%2C8390%2C8391%2C8392%2C8400%2C8401%2C8410%2C8411%2C8412%2C8420%2C8430%2C8431%2C8450%2C8460%2C8470%2C8480%2C8490%2C8500%2C8510%2C8520%2C9xxx&level=1%2C2%2C3&issue_uuid=e5dc8d9f-9405-08e9-1498-5f18364b1536)

Near my home, some roundabouts have not a real name but number instead (eg. Giratoire n°1 up to n°7) but Osmose thinks it should be a `ref=*` instead. I don't know how the analysis could be fixed, but it would be nice to accept that :).

![image](https://user-images.githubusercontent.com/1451988/123547240-49cdfa00-d760-11eb-9cbb-40e7e9b59827.png)

**Comment by frodrigo** [comment]
But it look to me like a ref.

**Comment by bagage** [comment]
Well I don't know it looks strange to me to use a ref for it, like `name=Giratoire n°7 ref=7`? I'm not very much familiar with `ref` so if anyone has a thought about what would be the proper mapping here...
