### ISSUE TITLE
32501: wrong fix proposed (removes "off" part)

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-backend#1288]
[Example](https://osmose.openstreetmap.fr/fr/map/#zoom=15&lat=45.04488&lon=5.06104&item=1010%2C1040%2C1050%2C1060%2C1070%2C1080%2C1090%2C1100%2C1110%2C1120%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1260%2C1270%2C1280%2C1290%2C2010%2C2020%2C2030%2C2080%2C2090%2C2100%2C2110%2C2120%2C2130%2C2140%2C2150%2C2160%2C3xxx%2C4020%2C4030%2C4040%2C4060%2C4061%2C4070%2C4080%2C4090%2C4100%2C4110%2C4130%2C5xxx%2C6xxx%2C7010%2C7011%2C7012%2C7020%2C7040%2C7050%2C7051%2C7070%2C7080%2C7090%2C7100%2C7110%2C7120%2C7130%2C7150%2C7160%2C7170%2C7220%2C7240%2C7250%2C8010%2C8011%2C8012%2C8020%2C8021%2C8022%2C8025%2C8026%2C8030%2C8031%2C8032%2C8040%2C8041%2C8042%2C8050%2C8051%2C8060%2C8070%2C8080%2C8090%2C8091%2C8100%2C8101%2C8110%2C8120%2C8121%2C8122%2C8130%2C8131%2C8132%2C8140%2C8150%2C8160%2C8161%2C8162%2C8170%2C8180%2C8182%2C8190%2C8191%2C8192%2C8200%2C8201%2C8202%2C8210%2C8211%2C8212%2C8221%2C8230%2C8240%2C8250%2C8260%2C8270%2C8281%2C8282%2C8290%2C8300%2C8310%2C8320%2C8330%2C8331%2C8340%2C8341%2C8350%2C8351%2C8360%2C8370%2C8380%2C8381%2C8382%2C8390%2C8391%2C8392%2C8400%2C8401%2C8410%2C8411%2C8412%2C8420%2C8430%2C8431%2C8450%2C8460%2C8470%2C8480%2C8490%2C8500%2C8510%2C8520%2C9000%2C9001%2C9002%2C9003%2C9004%2C9005%2C9006%2C9007%2C9009%2C9010%2C9011%2C9015%2C9016%2C9017%2C9018%2C9019%2C9100&level=1%2C2%2C3&fixable=online&issue_uuid=440a85d2-ca14-c906-e3c9-28c4417e53b8)

Osmose suggests to replace:

```diff
- opening_hours = Mo off, Tu-Th 09:00-18:00; Fr 09:00-19:00; Sa 08:00-18:00; Su off 
+ opening_hours = Mo    , Tu-Th 09:00-18:00; Fr 09:00-19:00; Sa 08:00-18:00; Su off 
```

But this is invalid (eg they have not the same meaning) if I compare [current](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo%20off,%20Tu-Th%2009:00-18:00;%20Fr%2009:00-19:00;%20Sa%2008:00-18:00;%20Su%20off) and [proposed](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo,%20Tu-Th%2009:00-18:00;%20Fr%2009:00-19:00;%20Sa%2008:00-18:00;%20Su%20off) versions.

**Comment by frodrigo** [comment]
cc @dfaure

**Comment by dfaure-kdab** [comment]
That looks wrong indeed, but I don't understand: I can't reproduce this locally in the docker setup from osmose-backend git master...

* I apply http://www.davidfaure.fr/2021/add_test.diff
```cd docker
docker-compose -f docker-compose.yml -f docker-compose-dev.yml build
docker-compose -f docker-compose.yml -f docker-compose-dev.yml run backend bash
```
then `pytest -k Opening` says
`1 passed`

Any idea why this works differently from the real site?

**Comment by frodrigo** [comment]
@jocelynj are we using the last version ?

**Comment by jocelynj** [comment]
Backends are currently on version 0176240a4ce437a0fb5fbf512b259781e190f5b5. Should I update?

**Comment by frodrigo** [comment]
Maybe because it is already up to date ?

**Comment by dfaure-kdab** [comment]
Yep this hasn't changed in a long time. Could you maybe try the unittest addition on the server?

**Comment by jocelynj** [comment]
I've applied your test patch osm211, and launched the test, and it is failing:
```
>       assert not a.node(None, {'opening_hours': 'Mo off, Tu-Th 09:00-18:00; Fr 09:00-19:00; Sa 08:00-18:00; Su off'})
E       AssertionError: assert not {'class': 32501, 'fix': {'opening_hours': 'Mo,Tu-Th 09:00-18:00; Fr 09:00-19:00; Sa 08:00-18:00; Su off'}, 'subclass': 0}
E        +  where {'class': 32501, 'fix': {'opening_hours': 'Mo,Tu-Th 09:00-18:00; Fr 09:00-19:00; Sa 08:00-18:00; Su off'}, 'subclass': 0} = <bound method TagFix_Opening_Hours.node of <plugins.TagFix_Opening_Hours.TagFix_Opening_Hours object at 0x7f54441ae048>>(None, {'opening_hours': 'Mo off, Tu-Th 09:00-18:00; Fr 09:00-19:00; Sa 08:00-18:00; Su off'})
E        +    where <bound method TagFix_Opening_Hours.node of <plugins.TagFix_Opening_Hours.TagFix_Opening_Hours object at 0x7f54441ae048>> = <plugins.TagFix_Opening_Hours.TagFix_Opening_Hours object at 0x7f54441ae048>.node
```

Could you add a test on a Pull-Request, so that we can also check Github CI result?

**Comment by dfaure** [comment]
Thanks for the test. Very interesting. Pull request done in https://github.com/osm-fr/osmose-backend/pull/1307

**Comment by jocelynj** [comment]
The test is now working on osm212, where I did the following:
```
pip3 uninstall PyKOpeningHours
pip3 install -r requirements.txt
pytest -k Opening
```
It looks like it didn't update the version last time.

**Comment by jocelynj** [comment]
I've launched the same commands on all backends handled by OSM-Fr.

Can you check if it fixes the original issue?

**Comment by dfaure-kdab** [comment]
The "Example" link in the bug report points to a JSON error now, I guess because the error on that node no longer exists.
In other words, I think the original issue is fixed, yes.

**Comment by jocelynj** [comment]
Thanks for the confirmation.
