### ISSUE TITLE
Tag Fix Bad Key: railway:memor2+

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#129]
`railway:memor2+=yes` should be accepted as a valid tag. Memor2+ is the railway protection system that's being used in Luxembourg.

**Comment by jocelynj** [comment]
Do you remember the item of the incorrect error ?  Is it 3050 ?

**Comment by jocelynj** [comment]
There is a list of available railways:* keys on (railway wiki page)[http://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging]. It specifies memor2+ and tbl1+

**Comment by grischard** [comment]
3050 indeed, e.g. http://osmose.openstreetmap.fr/en/api/0.2/error/7791910614

**Comment by grischard** [comment]
Thank you!
