### ISSUE TITLE
Flat roofs with roof:height=*

### ISSUE THREAD

**Issue by 501Ghost** [osm-fr/osmose-backend#1292]
I found that nearly 7,000 objects in the DB are tagged with both roof:height=* and roof:shape=flat. This has already caused https://demo.f4map.com/ to crash when looking at the city of New York. Could this combination of tags be flagged as an error?

Edit based on feedback elsewhere: The height of a roof relative to the walls of a building is more like a vertical offset than a true height. Unless we're mapping the thickness of the roof, which I assume is included in the height=* tag and the height of building levels, the true height of a supposedly flat surface (roof:shape=flat) should be assumed to be zero.

**Comment by Famlam** [comment]
This check is added to JOSM, I guess it'd be enough to update the JOSM mapcss rules?
https://josm.openstreetmap.de/ticket/21068

**Comment by 501Ghost** [comment]
I suppose so, yes.

**Comment by frodrigo** [comment]
Yes, ok.
