### ISSUE TITLE
`man_made=piste:halfpipe` is criticized as error even though it's mentioned on the OSM Wiki.

### ISSUE THREAD

**Issue by habi** [osm-fr/osmose-backend#1293]
I've been on a small ski-piste tagging spree (I know, it summer, but nonetheless).
I've tagged a half-pipe with `man_made=piste:halfpipe`, as suggested by the [OSM Wiki here](https://wiki.openstreetmap.org/wiki/Key:piste:type#See_also).

Osmose complained about this tag and linked me to https://github.com/osm-fr/osmose-backend/blob/da3d341478cef978cb8a6c5961050aa76df389d5/plugins/TagFix_BadValue.py#L40 where the error springs up.

The 'details' from Osmose are [here](http://osmose.openstreetmap.fr/en/issue/5be06a40-6074-2dc3-995c-f6686994ca07), the way in question is [here](https://www.openstreetmap.org/way/961560443).

Am I missing some additional  `piste`-tags on the half-pipe?

**Comment by frodrigo** [comment]
Should be added in the exception list here https://github.com/osm-fr/osmose-backend/blob/da3d341478cef978cb8a6c5961050aa76df389d5/plugins/TagFix_BadValue.py#L84

**Comment by habi** [comment]
I tried to add this to a PR, let me know if this needs something more!
