### ISSUE TITLE
item 4030 class 900 Conflict between tags: amenity, landuse - Single school on one site

### ISSUE THREAD

**Issue by imagoiq** [osm-fr/osmose-backend#1295]
Hi,

According to the wiki, to map a [single school on one site](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dschool#Single_school_on_one_site), you should map the entire area with amenity=school and optionally landuse=education. In Osmose, using both is reported as an error. Osmose also has a trap (I'm not familiar with the trap system): "Sometimes the object needs both tags.". But in the end, I'm not confident that the targeted object needs both.

Here is for example an object in this situation: https://osmose.openstreetmap.fr/en/issue/280dce44-432f-5681-e4c2-646c9b056434

**Comment by frodrigo** [comment]
Should be added here https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Incompatibles.py#L45
