### ISSUE TITLE
Conflict between tags: amenity, highway (amenity=weighbridge on highway objects seems okay)

### ISSUE THREAD

**Issue by sun-geo** [osm-fr/osmose-backend#1298]
It seems it's okay to use an `amenity=weighbridge` direct on the same `highway=*` osm way object.

Error/warning message: *"Tag conflict: Conflict between tags: amenity, highway"*

Item: 4030
Class: 900

Permalink to the Osmose map:
https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=48.762766&lon=2.472218&item=4030&level=1%2C2%2C3
https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=48.762766&lon=2.472202&item=4030&level=1%2C2%2C3&issue_uuid=92608708-1836-bc55-9f10-de3ff202640e

Example-osm-objcect:
https://www.openstreetmap.org/way/794167130

Wiki `amenity=weighbridge`: 
https://wiki.openstreetmap.org/wiki/Tag:amenity=weighbridge

Here are the cases where these combination (`amenity=weighbridge` & `highway=*` ) is currently used:
[Overpass-turbo query](https://overpass-turbo.eu/s/19mZ)
[Sophox query](https://sophox.org/#%23defaultView%3AMap%0ASELECT%20%2a%20WHERE%20%7B%0A%20%20%3FosmId%20osmm%3Atype%20%22w%22%20%3B%0A%20%20%20%20%20%20%20%20%20osmt%3Aamenity%20%22weighbridge%22%20%3B%0A%20%20%20%20%20%20%20%20%20osmt%3Ahighway%20%3Fkey%20%3B%0A%20%20%20%20%20%20%20%20%20osmm%3Aloc%20%3Floc%20.%0A%7D)

Thanks in advance for proceeding

**Comment by frodrigo** [comment]
Should be added here https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Incompatibles.py#L43

**Comment by sun-geo** [comment]
Thank you
