### ISSUE TITLE
The reason for error 5030 two names being reported

### ISSUE THREAD

**Issue by sarxos** [osm-fr/osmose-backend#1299]
Hello there :)

I have a question first. What is the reason for banning `/` character from being used in the `name=*` tag? I haven't found this explained on https://wiki.openstreetmap.org. Can someone clarify this to me, please?

The reason why I'm asking is because `5030 two names` error is reported for every bus stop in Bydgoszcz city of Poland. For example [errors](https://osmose.openstreetmap.fr/en/byuser/sarxos?username=sarxos&item=5030) were reported for few changesets I did in the past:

![image](https://user-images.githubusercontent.com/472658/125478270-dbb11274-dff9-4246-aa2f-9295f7da4c4b.png)

But those are valid official names. See [here](http://www.zdmikp.bydgoszcz.pl/pl/transport/rozklad-jazdy/2014-07-02-12-57-42). There a tons of bus stops with the same naming convention, e.g. "Akademicka / Romanowskiej", etc.

From the error message in here https://osmose.openstreetmap.fr/en/issue/d9470852-73c6-72c4-807d-93b3586c139c I can see that there are some mentions about streets having two names when `name:left=*` and `name:right=*` must be used accordingly. I suppose this may be the reason for the error. Are we forced to mark all of these errors as false positives or can this be somehow automated?

**Comment by sarxos** [comment]
For example, could we check in the code if way is `highway=platform` and treat it as valid in such a case?

**Comment by frodrigo** [comment]
Was mainly made for street names. It may not be adapted to other kind of objects.

-> reduce this rule scope to highway and maybe be other objects.

**Comment by frodrigo** [comment]
It seams to me there is not so much report.
https://osmose.openstreetmap.fr/en/issues/open?country=poland%2a&item=5030&class=705

Do you think most of them are false positives ?

Option are:
- allow `\` in the country
- apply rule only on `highway` in the country

https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_Multiple.py#L56-L58
