### ISSUE TITLE
File name conflicts

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#130]
Users of case-insensitive file systems (Mac OS X) cannot contribute to osmose-backend, because some files have the same names in a different case.

Checking out osmose-backend produces:

```
git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   plugins/TagFix_MultipleTag_FR.py
        modified:   tests/results/sax.test.FR.xml

no changes added to commit (use "git add" and/or "git commit -a")
```

because `tests/results/sax.test.FR.xml` conflicts with `sax.test.fr.xml` and `plugins/TagFix_MultipleTag_FR.py` with `plugins/TagFix_MultipleTag_fr.py`.

The difference between 'fr' and 'FR' isn't explained on the wiki. If it were, it would be difficult to search for. And if if were easy to find, it would still be confusing.

If this is to distinguish between plugins that only run in France and plugins that run in francophone countries, `only_for = ["France"]` or `only_for = ["french"]` would be clearer.

**Comment by jocelynj** [comment]
That's right, it is not very nice for case-insensitive file systems... And we are using fr/FR quite often, for example in plugins/ directory.

The idea here is that fr is ISO 639-1 code for french language, and FR is ISO 3166 code for country France.

**Comment by grischard** [comment]
The current system really makes confusion easy - I got the two mixed up while typing this message.

I would like to replace FR with lang-fr, and ES with lang-es.

@frodrigo and I chatted about this briefly at SOTM, but I wanted to mention it here and see if there are objections or better ideas before I work on it.

**Comment by frodrigo** [comment]
I prefer if we keep the uppercase for readability.

**Comment by grischard** [comment]
Ah, I mean replace fr with lang-fr. See, I get the two mixed up!

FR can stay FR, or even become country-FR.

**Comment by frodrigo** [comment]
ho ok, so let's go.

**Comment by jocelynj** [comment]
@grischard If I understand correctly, you plan to rename the file specific for a language from fr/es to lang-fr/lang-es ?  If it is so, I'm perfectly fine with this.

**Comment by grischard** [comment]
Wow! Thank you!!
