### ISSUE TITLE
False positives for named telecom centers

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#1300]
https://osmose.openstreetmap.fr/fr/issue/71965ef0-a138-5cce-9021-1de1003ccfe8

Tag|Value
-- | --
source | 407663
item | 2110
class | 21101

https://www.openstreetmap.org/node/7902526435 is tagged according to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:telecom%3Ddata_center)

Tag|Value
-- | -- 
**name** | Data Center Bluecom 
operator | Bluecom |  
**telecom** | **data_center**

But Osmose suggests it would be an unfeatured object. It is not.

**Comment by frodrigo** [comment]
OK. `telecom` is new main tag.
Should be added to this list https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag.py#L31

**Comment by SK53** [comment]
Somewhat unfortunate that this tag uses EN-US not EN-GB as should be the case with tags, but it far outweighs the alternative.

**Comment by Bibi56** [comment]
@flacombe, what about to make a proposal according to @SK53 wishes? It makes sense. Even if mechanical edits...
@frodrigo thanks.

**Comment by SK53** [comment]
@Bibi56 See discussion between @flacombe & russss on the wiki page: https://wiki.openstreetmap.org/wiki/Talk:Tag:telecom%3Ddata_center

**Comment by Bibi56** [comment]
@SK53 you'll see my answer there: half OK only.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/issues/open?item=2110&class=21101
