### ISSUE TITLE
Worldwide church names are reported as having a 'descriptive' name and 'unnecessary'

### ISSUE THREAD

**Issue by sekerob** [osm-fr/osmose-backend#1303]
Please follow the discussion on OSM Help describing the problem. Tests were made to include the London Westminster Cathedral. All are being flagged with the same tagging problem.
[
Link: [https://help.openstreetmap.org/questions/81001/church-name-suddenly-reported-as-unnecessary](url)

**Comment by frodrigo** [comment]
This rule come from JOSM Validator MapCSS
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/unnecessary.mapcss

cc @Klumbumbus

Not sure why it is triggered by the rule.

But I am agree with it. The "Westminster Cathedral" name is something like "Metropolitan Cathedral of the Precious Blood of Our Lord Jesus Christ".
https://en.wikipedia.org/wiki/Westminster_Cathedral

**Comment by Klumbumbus** [comment]
There is probably something wrong on the osmose side. Within JOSM there is no warning about descriptive name for https://www.openstreetmap.org/way/10810446 (Westminster Cathedral)

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/issue/e3c4f6f9-f944-5886-9ddf-882e2cf6c9b5
http://osmose.openstreetmap.fr/en/issues/open?item=9010&class=9010003

Yes there is something wrong
http://osmose.openstreetmap.fr/en/issues/graph.png?item=9010&class=9010003&start_date=2021

**Comment by frodrigo** [comment]
```
amenity=place_of_worship
name=Westminster Cathedral
```

These tags match this rule due to bad scoped OR in the last condition on generated python code.

```css
*[name][name=~/^(?i)(chapel|chapelle|kapelle)$/][tag("building")=="chapel"||tag("amenity")=="place_of_worship"]
```

**Comment by sekerob** [comment]
Chapeau for dogging the issue, the quick diagnostics and fixing. Is there an ETA as to when this is going to translate into the few hundred thousand 'unnecessary' warning pins disappearing ;?

**Comment by frodrigo** [comment]
Will be progressively updated in the next 24h.
