### ISSUE TITLE
wrong interpretation in class 9010001

### ISSUE THREAD

**Issue by Klumbumbus** [osm-fr/osmose-backend#1304]
all details see https://josm.openstreetmap.de/ticket/21149

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/issue/f7b50ad2-69fd-69c9-a91c-df137f0ff980

|k|v
-- | --
area | yes
barrier | fence
leisure | dog_park
opening_hours | Mo-Su 00:00-24:00; 09:00-17:00; PH closed
wheelchair | no


unnecessary tag
highway={{2.value}} is unnecessary for area
