### ISSUE TITLE
Check for typographical mistakes

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#131]
Typographical mistakes like:

"Barrage d' Esch" -> no space after the apostrophe
"1ier", "2ème" "XXieme" -> "1er", "2e", "XXe"

**Comment by jocelynj** [comment]
Your first idea is a good one. There is already plugins/Name_Spaces.py that checks successive spaces and initial/final spaces. It could easily be extended to space after apostrophe.

The second idea is good too, and is similar to code in plugins/Name_Dictionary_fr.py#64. It proposes to correct 4ieme / 4eme / 4éme, to 4ième / 4ème / 4ème.

**Comment by frodrigo** [comment]
In english '' ' (apostrophe space) is not a fault, and maybe in other languages.

**Comment by grischard** [comment]
You're right, English would have the possessive after s, and colloquial English would have, for example "His 'n' Hers". Dutch would have "'s-Hertogenbosch". Even French has Grand' Rue.

Overpass finds 23918 elements in total worldwide for “name~/' /”

This quite obviously needs re-thinking on my part! What do you think of `/(^| )[LlDd]' /` in French-speaking countries?

**Comment by frodrigo** [comment]
I do it for French. But you can suggest rules for other language too.
