### ISSUE TITLE
sidewalk=both && sidewalk:both=<value>

### ISSUE THREAD

**Issue by tordans** [osm-fr/osmose-backend#1311]
OSM has two ways to tag things that are on both sides of a road.

For example:
`sidewalk=both` vs `sidewalk:both=yes`

But this could also be `sidewalk:both=<some_other_value>`.

I wonder if a validation would be feasible that checks for those conflicting double taggings.

Example: ATM, we have a few of those issues at https://overpass-turbo.eu/s/1a34 for example (which we will fix manually soon).

This validation could also be viewed as more general (not just sidewalks) since there are a few tags that suffer from the fact sometimes `:both` is added, sometimes its implicit.

**Comment by frodrigo** [comment]
@Klumbumbus interested in this for JOSM rules?

**Comment by Famlam** [comment]
Turns out I already implemented this in 2022 in a generic way without knowing about this issue :)
https://osmose.openstreetmap.fr/en/issues/open?item=3360

I made a small PR to catch another case, see #2311, but that's a few dozen of cases worldwide.
