### ISSUE TITLE
check barrier=cycle_barrier on highway=tertiary ( possibly other highway keys as well )

### ISSUE THREAD

**Issue by serpico** [osm-fr/osmose-backend#1312]
While browsing I discovered I mistakenly placed a  `barrier=cycle_barrier` on a `highway=tertiary` rather than on the adjacent `highway=footway`, making almost any kind of routing impossible on this road's section.

source : https://www.openstreetmap.org/changeset/109298055

**Comment by Famlam** [comment]
A check was added to JOSM recently, so synchronising the mapcss rules should fix this too:
https://josm.openstreetmap.de/ticket/20742

**Comment by frodrigo** [comment]
> A check was added to JOSM recently, so synchronising the mapcss rules should fix this too: https://josm.openstreetmap.de/ticket/20742

Osmose does not support this kind of mapcss rules (because of multi objet). Mapcss have to be improved (hard) or this rule can be donne directly with sql.

**Comment by frodrigo** [comment]
Fixed on JOSM
