### ISSUE TITLE
Changes in French RTE substations dataset

### ISSUE THREAD

**Issue by flacombe** [osm-fr/osmose-backend#1313]
A slight change has been made in French RTE substation dataset.
In first version, only substation were there but since a few weeks, a function column has been added and distinguish with branch points (`POINT DE PIQUAGE`).

Branch points are towers connecting a branch line to a main line (Y connection).
Osmose currently encourage users to create a substation node beside the actual power tower but it shouldn't.
Example: https://www.openstreetmap.org/node/8910300561

Instead, it should recommend to complete a probably existing power tower with `ref:FR:RTE` reference of the branch point in the dataset (column `Code poste`).
Branch points are always power towers.

I'll try to propose a change in analyzer to fix substations merger and a new one for branch points shortly.

**Comment by frodrigo** [comment]
power_substation or power_substation_minor ? The filed is still available ? I do not see it.

cc @flacombe

**Comment by flacombe** [comment]
Didn't know why I didn't mention the relevant file when writing this ticket. It's in Postes file :
https://opendata.reseaux-energies.fr/explore/dataset/postes-electriques-rte/table

It is for power_substsation analyzer.
In addition to `ref:FR:RTE` tag, it should also propose to add `line_management=branch` which literally means `POINT DE PIQUAGE`.
It is valid for `power=tower`, `power=pole` or `power=insulator`.
Example : https://www.openstreetmap.org/node/1773389169
