### ISSUE TITLE
natural=water water=river without river false positive

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1314]
https://osmose.openstreetmap.fr/en/map/#item=1220&zoom=18&lat=48.701488&lon=2.49499&level=1%2C2%2C3&issue_uuid=3afd66b4-aef8-9518-0f5b-674879215d5d
https://www.openstreetmap.org/way/257426249#map=19/48.70179/2.49491
https://www.openstreetmap.org/way/30429271#map=19/48.70146/2.49455

from https://github.com/osm-fr/osmose-backend/issues/1209#issuecomment-900324861

https://osmose.openstreetmap.fr/en/issue/3afd66b4-aef8-9518-0f5b-674879215d5d
https://osmose.openstreetmap.fr/en/issue/20b61847-98cc-cb71-cdcb-587346f6a08e
https://osmose.openstreetmap.fr/en/issue/6730e53f-bba3-1270-dc06-067a928f83ed
https://osmose.openstreetmap.fr/en/issue/46e0be27-19d6-6179-f06b-670fdf29fcaa

**Comment by frodrigo** [comment]
Issue linked to diff mode.
Will be fixed on next deploy.
