### ISSUE TITLE
Update_Matrix seems not updated correctly

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-backend#1317]
Hello,

In the http://osmose.openstreetmap.fr/en/control/update_matrix we can see lot of orange values, and also missed cells.

Starting in the colum "guinea" no values unless the first few columns.

Is the matrix correctly updated?

**Comment by frodrigo** [comment]
Yes, the matrix look "good".
Counties with all < 1 is not show because of performance issue of the page.

You can see details of build here
https://buildbot.osmose.openstreetmap.fr
