### ISSUE TITLE
Flag numerical names on houses

### ISSUE THREAD

**Issue by arrival-spring** [osm-fr/osmose-backend#1319]
Houses with purely numerical names are normally errors, they should be tagged as `addr:housenumber`

Approximate overpass turbo wizard queries for the selection of elements:

Either
`name~"[0-9]+"` and (`building=house` or `building=detached` etc.

Or
`name~"[0-9]+"` and `building=*` and !(`building=garage` or `shop=*` or `amenity=*` etc.

This could be extended to look for houses with name, which should be `addr:housename`

**Comment by frodrigo** [comment]
cc @Klumbumbus interested to take this into JOSM validator ?
