### ISSUE TITLE
Check for missing crossing=*

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#132]
`highway=crossing` or `highway=traffic_signals` should include `crossing=*`. It would be nice if osmose could check for it.

**Comment by jocelynj** [comment]
For `highway=crossing`, it is true that we could suggest:
  - `crossing=uncontrolled`
  - `crossing=island`

For `highway=traffic_signals`, won't we have a lot of false-positive, where `crossing=no` should be automatically picked ?

**Comment by frodrigo** [comment]
Nice features is not a job for Osmose in many case. Osmose if for bad features ;-).

Adding the `crossing` tag can be achieved with other tools, like MapContrib with some theme like this one https://www.mapcontrib.xyz/t/bd6134-Passages_pietons#
