### ISSUE TITLE
Issue detection not updated

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-backend#1320]
Hello,

This isue was detected on  2021-08-24 :
https://osmose.openstreetmap.fr/en/issue/bef3d886-8edc-72e6-5517-e4d91f8e0937
saying in the "Elements" section the tag surface = asphalt is on the node.

But the node was fixed on 2021-08-20 (4 days days before) to remove that tag.
https://www.openstreetmap.org/node/5397028034#map=19/40.41866/-3.67076
as result there is no tag in the node.

Is the issue having the latest data?
Could you fix this?

Thanks

**Comment by frodrigo** [comment]
Osmose is up to date
https://osmose.openstreetmap.fr/en/issues/open?item=xxxx&source=14005

Issue look similar to #1301.

**Comment by frodrigo** [comment]
No more valid data to look into.

Probably linted to https://github.com/osm-fr/osmose-backend/issues/1301#issuecomment-1001766824
