### ISSUE TITLE
Wrong tag suggested

### ISSUE THREAD

**Issue by Mannivu** [osm-fr/osmose-backend#1326]
Osmose stated that in some ways I've recently edited I've used the wrong tag `disabled=yes` and suggests to use `disable=yes` (see for example [this issue](https://osmose.openstreetmap.fr/it/issue/a35f9d37-4f4a-0793-3469-224e92c88f21)). However according to taginfo `disabled` is used [~8500 times](https://taginfo.openstreetmap.org/keys/disabled), while `disable` is used [~250 times](https://taginfo.openstreetmap.org/keys/disable).

**Comment by frodrigo** [comment]
It use statistics on tags of the area (country or subdivision).
It means there is lots of wrongs tags in this area.

item=3150

**Comment by Mannivu** [comment]
I'm not sure about this, to be honest. The issue I've linked before is (was?) near Comacchio, but according to [this overpass query](https://overpass-turbo.eu/s/1aWP) there's no `disable` tag near Comacchio.

**Comment by frodrigo** [comment]
> I'm not sure about this, to be honest. The issue I've linked before is (was?) near Comacchio, but according to [this overpass query](https://overpass-turbo.eu/s/1aWP) there's no `disable` tag near Comacch

**Comment by Famlam** [comment]
This issue is solved via #1616

**Comment by Mannivu** [comment]
Thank you!
