### ISSUE TITLE
Spuriousness "Missing way on level crossing" warnings

### ISSUE THREAD

**Issue by danfos** [osm-fr/osmose-backend#1327]
I see quite some "Missing way on level crossing" warnings but I do not see what is wrong, the node is on a crossing between a way marked as highway=* and railway=*

For examples and further details see:

- http://osmose.openstreetmap.fr/en/issue/25908c1e-a1a5-d9c1-abf4-c4334dc4dcf7
- http://osmose.openstreetmap.fr/en/issue/cd2e6c91-f2b3-b7f8-7cea-5d4652b88acf

Or use http://osmose.openstreetmap.fr/en/map/#item=7090&zoom=7&lat=51.113&lon=4.883&level=2&tags=&fixable= to find more examples.

I had a look at https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_features.py but it is not clear to me where things go wrong.

Does this have anything to do with #1216?

**Comment by Bibi56** [comment]
[Here](http://osmose.openstreetmap.fr/en/map/#zoom=16&lat=48.38714&lon=-4.46174&level=2&tags=&fixable=&issue_uuid=e241345b-b66e-b783-67f4-cf227b4edcdb&item=xxxx) I was about to add a ticket for railway=disused but the issue seem to be more generic.

**Comment by marsip** [comment]
Thanks for your answers. I will mark these as false positives in OSMOSE.

**Comment by smootheFiets** [comment]
Those false positives crop up in the Netherlands, too.  I came across this example:
https://osmose.openstreetmap.fr/en/issue/e7c28be0-063f-c3dc-ae73-ce9fc495f420

I gather from the error message that it finds the corresponding highway=unclasified OK, but it doesn't appear to find the railway https://www.openstreetmap.org/way/396695648 (although the offending node is part of it)

I hope this helps debugging.

**Comment by frodrigo** [comment]
Fixed, update in progress
http://osmose.openstreetmap.fr/en/issues/open?item=7090&class=1
http://osmose.openstreetmap.fr/en/issues/graph.png?item=7090&class=1&start_date=2021

**Comment by danfos** [comment]
Thanks for the fix, the spurious warnings are gone and the number of remaining warnings is back on the normal level.

![Screenshot_20220101_115705](https://user-images.githubusercontent.com/8472097/147849084-7e6b79d9-dac1-4e81-a84f-4e8f3bce54f0.png)

Checked the remaining warnings in my area and see they are "real" problems
