### ISSUE TITLE
Waterway meeting "natural=coastline" is no longer considered connected stream

### ISSUE THREAD

**Issue by Pikse** [osm-fr/osmose-backend#1331]
Report is for item 1220, class 3.

For example:
http://osmose.openstreetmap.fr/en/issue/bae7f39a-f9a8-3169-d07a-e542bf1a02cc
(way 775707008 [waterway=stream] meeting coastline)

http://osmose.openstreetmap.fr/en/issue/2f655860-d292-25d2-2ce5-5de15b071b21
(way 112697405 [waterway=river] meeting coastline)

This surfaced around the time when the number of issues on the following graph jumped from about 10 to about 80.
http://osmose.openstreetmap.fr/en/issues/graph.png?item=1220&class=3&country=estonia

**Comment by frodrigo** [comment]
Found issue on diff mode. Wait for update on #1348
