### ISSUE TITLE
Tags/keys shouldn't be translated

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1333]
I noticed in some cases tags themselves are translated, i.e. in Dutch:
_"Possible missing traffic_signals:direction tag or crossing on traffic signals"_
Became:
_"Mogelijk ontbreekt traffic_signals:richting tag of kriusing op verkeerslichten"_
(i.e. `traffic_signals:direction` & `crossing` were translated, but shouldn't as they're tag names)

Hence I was thinking: maybe it's an idea to convert all these from (using this example)
```python3
title = T_('Possible missing traffic_signals:direction tag or crossing on traffic signals')
```
To for instance:
```python3
title = T_('Possible missing `traffic_signals:direction` tag or `crossing` on traffic signals')
or
title = T_('Possible missing {0} tag or {1} on traffic signals', 'traffic_signals:direction', 'crossing')
or
title = T_('Possible missing `{0}` tag or `{1}` on traffic signals', 'traffic_signals:direction', 'crossing')
```

Obviously a lot of work and I hope this wouldn't erase good translations?

**Comment by frodrigo** [comment]
Yes, the good practice for now is using backquote. As it may be rendered as markdown.

**Comment by Famlam** [comment]
Would you say it's best to update all the strings now, or only when they're modified in a PR that modifies the code? Or only the ones that are currently incorrectly translated in a language?
(Updating the strings would also cause a lot of the translations to get lost I think)

**Comment by frodrigo** [comment]
You could may a mass update PR. If you want.

If it impacts too much strings, we can try to update these with a script.

**Comment by jocelynj** [comment]
To keep current translations that are on transifex, the script should also update the strings in po/*.po files, so that they can be directly uploaded to transifex.
