### ISSUE TITLE
OpenData: update charging_station

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#1334]
Some charging_station got a new ref:EU:EVSE.
The analyser doesn't see the existing station and propose to create a new one. Is the conflation criterion too strict?

https://osmose.openstreetmap.fr/fr/issue/55a164cb-113f-53cf-624a-de7eb554e5b0

The issue seems to be common in France:

https://osmose.openstreetmap.fr/fr/issues/open?item=xxxx&source=417085

 titre | nombre
 -- | --
 Station de recharge | **5782**
 Station de recharge, intégration possible | 610
 Station de recharge mise à jour | **299**

**Comment by frodrigo** [comment]
Conflation is done using ref :
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_charging_station_FR.py#L62

If ref change it see it as a new station.
