### ISSUE TITLE
False positives for validator 'The name tag contains two names' in Denmark

### ISSUE THREAD

**Issue by Zero3** [osm-fr/osmose-backend#1335]
The validator 'The name tag contains two names' creates false positives in Denmark because many buildings contains a name with the '/' character. This is because the name of a public company is commonly/legally suffixed with "A/S" in Denmark, which causes this validator to create false positives.

Example: https://osmose.openstreetmap.fr/en/issue/fbf4cd2b-0a19-44cf-e09b-35a4ebad9c9d

**Comment by frodrigo** [comment]
Exception can be added here
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_Multiple.py

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/en/issues/open?item=5030&class=705&country=denmark

**Comment by frodrigo** [comment]
Fixed.
