### ISSUE TITLE
Line breaks in tag values

### ISSUE THREAD

**Issue by Zero3** [osm-fr/osmose-backend#1336]
Osmose does not seem to like line breaks in tag values. Is this a false positive, or are newlines really discouraged/not allowed?

Example: https://osmose.openstreetmap.fr/en/issue/65e7bfb7-cd53-864c-51af-e3c6650d7450

**Comment by frodrigo** [comment]
It is the list of non printable char
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_Script.py#L66

Not sure about this.

**Comment by jocelynj** [comment]
I don't think tools correctly support line-breaks in tag values, and I would recommend to not use them.

In this specific case, why is there a link-break on the description?

**Comment by Zero3** [comment]
I see. I do not know why the OSM editor is using line breaks, but presumably it is for formatting reasons. I will write him and ask if he can explain why.
