### ISSUE TITLE
False positive: Unconnected stream or wrong way flow

### ISSUE THREAD

**Issue by marsip** [osm-fr/osmose-backend#1337]
I often get errors "Unconnected stream or wrong way flow", but there are no errors.
Often the stream is connected to bridge.
Examples:
https://www.openstreetmap.org/way/988087717
https://www.openstreetmap.org/way/667908587

I also get errors when the steam is connected to a lakes on a lake node.

**Comment by frodrigo** [comment]
Waterway should be connected, event in lake.
You must continue the water stream into the lake (when make sens).
As the lake are more a riverbank than a wayter ways.
