### ISSUE TITLE
Wrong Pit not integrated

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#1339]
There is an existing "cave" at 12 m tagged as `natural=cave_entrance`(node [5969194084](https://www.openstreetmap.org/node/5969194084))

<img width="33%" alt="Capture d’écran 2021-10-02 à 09 20 31" src="https://user-images.githubusercontent.com/2158081/135707521-a4511230-370a-418e-b21a-c6b3f05e0c63.png">

- item=[8530](http://osmose.openstreetmap.fr/fr/issues/open?item=8530)
- class=[190](http://osmose.openstreetmap.fr/fr/issues/open?item=8530&class=190)
- http://osmose.openstreetmap.fr/fr/issue/8d3ff708-9213-a3cf-38d8-5d99b6838909
- [Osmose map](http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=45.733939&lon=6.62431&item=8530&class=190&level=1%2C2%2C3&tags=&fixable=
)

**Comment by frodrigo** [comment]
`natural = sinkhole` and `natural=cave_entrance` are not the same think.

What is your issue about ?

**Comment by pyrog** [comment]
No.

Cave entrance is for an horizontal cave (grotte in french)
Sinkhole, pit is for a vertical entrance

So in this case, Osmose should detect the node and warn about the type

**Comment by archie83** [comment]
When Osmose suggests to add a new object, it is the user responsibility to check if the same object already exists in OSM with wrong tags and, then, to fix the tags instead of adding the new object.

**Comment by frodrigo** [comment]
Agree with @archie83
