### ISSUE TITLE
Mismatched power substation and line voltage

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#134]
Power substations should have the same voltage as the lines nearby.

Osmose should check if for substations that have a power line 30 meters from them, but don't have the corresponding voltage tag.

**Comment by frodrigo** [comment]
Are you asking for validating the presence of the voltage tag (not an issue), or the values (an issues) ?

**Comment by grischard** [comment]
I'm asking to detect mismatching voltage values

**Comment by frodrigo** [comment]
I have some result.

But https://www.openstreetmap.org/way/100500802 https://www.openstreetmap.org/way/367164978 is an issue ?

**Comment by fanfouer** [comment]
Hi all

As Frederic mentioned, his results are indeed a mismatch and the substation should have voltage=400000;225000;63000;20000

BUT

As often in industrial facilities there are auxiliary power supplies with different voltages, to feed command and control systems. It's possible to see them in OSM : https://www.openstreetmap.org/node/2387971998
voltage:tertiary key is for auxiliary power systems and the substation where this particular transformer is in isn't serving 20000 volt at all on the power grid.
Tagging isn't so precise that way and it would be hard to be 100 percent right in mismatch checking.

**Comment by frodrigo** [comment]
Results:
http://osmose.openstreetmap.fr/fr/errors/?item=7040&class=7
