### ISSUE TITLE
post_office=post_partner (eg) : wrong proposal fix 

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#1342]
Hello,

post_office:type= is deprecated and it's issued by osmose -> ok.

After tag correction (post_office=post_partner or post_annex), osmose proposes to fix it with post_office:type=post_partner (or post_annex) :/

(eg https://osmose.openstreetmap.fr/fr/issue/27a388e3-39fc-d98b-14f7-e5cfb9a99db7)

Any fix for this wrong fix? ^^

**Comment by frodrigo** [comment]
@deuzeffe is it now ok for you ?

**Comment by deuzeffe** [comment]
@frodrigo yep.
