### ISSUE TITLE
Osmose reportedly complains about valid opening hours, has no support for extended_hour syntax

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1344]
According to my understanding `opening_hours=Mo 20:00-26:00` is valid, according to recent mailing list thread Osmose complains about it

See

https://lists.openstreetmap.org/pipermail/tagging/2021-October/thread.html#62618 https://lists.openstreetmap.org/pipermail/tagging/2021-October/062618.html

https://wiki.openstreetmap.org/wiki/Key:opening_hours#Closing_after_midnight (I just created it!)

https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#extended_hour and specification in general

**Comment by frodrigo** [comment]
Maybe @dfaure can answer this
