### ISSUE TITLE
Osmose reports several false positives for Philippine waterways not connected to coastline

### ISSUE THREAD

**Issue by JAT86** [osm-fr/osmose-backend#1348]
Related to  #1331 , Osmose reports false positives of waterways not connected to coastline (Item `1220 - waterway`). This is especially evident in the Philippines where both rivers and streams (`waterway=river` and `waterway=stream`) which are actually connected to multipolygon/relation island coastlines (`natural=coastline`) are reported as not connected to the coastline:

- [Issues link](https://osmose.openstreetmap.fr/en/issues/open?country=philippines&item=1220&level=1,2,3&source=&class=&tags=waterway&username=&bbox=)
- [Map link](https://osmose.openstreetmap.fr/en/map/#source=3168&item=1220&class=&zoom=8&lat=16.359&lon=120.91&level=1%2C2%2C3)

Kindly check and fix.

**Comment by frodrigo** [comment]
Found issue on diff mode. Wait for update.

**Comment by frodrigo** [comment]
Not sure about the fix
Update in progress
http://osmose.openstreetmap.fr/en/issues/open?item=1220&class=2,3

**Comment by frodrigo** [comment]
Fixed, update in progress.
