### ISSUE TITLE
improve duplicated ways in analyser_osmosis_duplicated_geotag.py

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#135]
add tags to detect duplicated ways in select array
'historic','man_made','power'
and clause where 
...
( b1.lsttag->'historic' = b2.lsttag->'historic' ) or
( b1.lsttag->'man_made' = b2.lsttag->'man_made' ) or
( b1.lsttag->'power' = b2.lsttag->'power' ) or
...

**Comment by frodrigo** [comment]
man_made and power are already set.
Really useful to do it for `historic` tag ?

**Comment by didier2020** [comment]
psql -d osmose_frontend -c "select count(*) from marker_elem where tags?'historic'"
=> 392 ...
