### ISSUE TITLE
analyser_merge_shop_FR.py improvements ?

### ISSUE THREAD

**Issue by Shallowmallow** [osm-fr/osmose-backend#1351]
Hello it seems to to add shops that don't exist anymore. For example this shop

https://www.societe.com/societe/autochrono-66-537519829.html

It seems to be a strange case , it's still in the SIRENE but has been radiated i( has been cloturé pour insuffisance d'actifs)

Maybe the could script could be improved ?

I don't know but maybe it could check it has some justificatifs here https://annuaire-entreprises.data.gouv.fr/justificatif/537519829

or it has an RCS  https://entreprise.data.gouv.fr/api/rncs/v1/fiches_identite/537519829/pdf

**Comment by frodrigo** [comment]
Is the radiated information present in the SIRENE / geoSIRENE data file ?
