### ISSUE TITLE
BD Topo mountain

### ISSUE THREAD

**Issue by Hades1503** [osm-fr/osmose-backend#1354]
The names of the mountains are mixed with the summits and peaks, it creates errors 

Separate the mountains from the peaks paragraph and propose a "natural=ridge" line to add the name of the mountain

**Comment by archie83** [comment]
Sometimes the name of the summit is the same as the name of the mountain, that is why I had included the mountains.

You propose to use "natural=ridge". But mountains are not ridges. Moreover, the BD TOPO also contains ridges, although their integration is not enabled in Osmose at this time.
I have looked at the best tags to define a mountain, and I have found:
```
   place=region
   region:type=mountain_area
```
but it is not widely used.

I think the best option should be simply to remove the integration of the mountains. What do you think?

**Comment by Hades1503** [comment]
it would be a shame to disable the name of the mountains. 

Ok with your proposal 

Creating a paragraph in the code especially for the mountain would be better.

Why aren't the ridges activated? 

There are a lot of natural elements disabled in the code, why?

**Comment by archie83** [comment]
> it would be a shame to disable the name of the mountains.
> Ok with your proposal

I think this should be discussed. I'll open a topic on the French forum.

> Why aren't the ridges activated?
> There are a lot of natural elements disabled in the code, why?

I think it is because it would take too much time on the Osmose server. See the discussion on [https://github.com/osm-fr/osmose-backend/pull/1233](https://github.com/osm-fr/osmose-backend/pull/1233)

@frodrigo : Now that the analyser merge_natural_FR is running, could you check how much time it takes, and if you could allow to add a few more items for the integration?

**Comment by archie83** [comment]
@frodrigo: please keep "Sommet", remove only "Montagne"

**Comment by frodrigo** [comment]
Osmose should avoid suggest possible false possitive. So better not considering "Sommet".

**Comment by archie83** [comment]
I don't agree, not at all. "Sommet" and "Pic" must be tagged as "natural=peak'. The only difference is that a peak is more acute than a summit.

Look at the description on the BD TOPO:

Nature = « Pic »
Définition : Sommet pointu d’une montagne.
Regroupement : Aiguille | Pic | Piton

Nature = « Sommet »
Définition : Point haut du relief non caractérisé par un profil abrupt (voir aussi Nature="Pic".)
Regroupement : Colline | Mamelon | Mont | Sommet | Inselberg

**Comment by archie83** [comment]
I have opened a [discussion](https://forum.openstreetmap.fr/t/taguer-les-montagnes/7394) on the French forum.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/commit/ad325cc5e25f58b6aed6e890489730a68584760b

**Comment by archie83** [comment]
> Osmose should avoid suggest possible false possitive. So better not considering "Sommet".

I never found a false positive related to the "Sommets".

**Comment by frodrigo** [comment]
Ok, let `nature=Sommet` be back.

**Comment by archie83** [comment]
Thank you
