### ISSUE TITLE
mhs:inscription_date: please check date format

### ISSUE THREAD

**Issue by treinen** [osm-fr/osmose-backend#136]
Hello,

osmose doesn't seem to check the format of the date in the field mhs:inscription_date,
for instance here:

http://www.openstreetmap.org/way/200452259

at least this one, and other ones in the format YYYY/MM/DD, are not listed under 3090-date

**Comment by frodrigo** [comment]
Yes, It does not. And I don't think it will.

**Comment by treinen** [comment]
Why? I thought all dates should be ISO 8601, according to

http://wiki.openstreetmap.org/wiki/Editing_Standards_and_Conventions#Date_and_time

**Comment by frodrigo** [comment]
> Why?
Cause it's too much complicated to do this, IMHO.

Feel free to study the code, and make a pull request yourself if you want.
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_heritage_FR_merimee.py

**Comment by frodrigo** [comment]
Hint : https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge.py#L876

**Comment by jocelynj** [comment]
@treinen: can you check which item the error you have seen has ?  Your fix on #138 would fix this issue only if error is on item 3090. If error is on item 8011 or 8012, then it is file  analyser_merge_heritage_FR_merimee.py or Analyser_Merge.py that should be fixed.

**Comment by frodrigo** [comment]
@jocelynj for 801x it's in #137

**Comment by treinen** [comment]
when there is something like "mhs:inscription_date=2010/12/31" then osmose *should* raise a 3090,
but currently it doesn't 

In order to fix #137 we need that the date is in standard format,so that we can extract the year from the date. So, in some sense this is a prerequisite for fixing #137.
