### ISSUE TITLE
False positive on "Small highway group apart from the main network or with insufficient access upstream"

### ISSUE THREAD

**Issue by atorger** [osm-fr/osmose-backend#1361]
Here:
http://osmose.openstreetmap.fr/en/map/#zoom=13&lat=65.68153&lon=17.6387

and nearby there are a number of "Small highway group apart from the main network or with insufficient access upstream" which just don't go away and I don't see there is any issue, the roads are connected to a parent and the parent is connected to a parent and so on until it reaches the backbone road network. I suspect that the problem is that the rural road network around here is so sparse that even though that it is fully connected upstream those connections are so far away that maybe the analyzer doesn't see them?

**Comment by frodrigo** [comment]
I do not see witch one exactly.
But it may have issue with the check close to borders. Check is done by area.
If it is ok, just mark as false positive.

**Comment by atorger** [comment]
All of them around the area linked above are false positives, it's about 21 of them. But all are also relatively close to the county  border (Norrbottens län / Västerbottens län), so maybe that is the reason?

I still think it's strange though as even if we cut and separate all roads at the border all those false positives have connections into the backbone road network within the own county.

**Comment by frodrigo** [comment]
You are right. The local "main" road is not on the issues. This is strange.
Keep this issue open.

**Comment by rivermont** [comment]
Likely the same issue [here](https://osmose.openstreetmap.fr/en/map/#item=1210&zoom=10&lat=13.579&lon=36.3736), on the Sudan--Ethiopia border.

**Comment by frodrigo** [comment]
The original issue is gone.

> Likely the same issue here, on the Sudan--Ethiopia border.
> Another example on the India--Bangladeh border.
> Possibly also the same issue here, on the border of a US county.

All of this are legitimate due how it works. You have to cross the border to connect to main road.

I flag this issue with the "Issue detection not updated" project. As I suspect it is part of a more general issue with update.
