### ISSUE TITLE
"not in route_master relation" with public_transport:version=1

### ISSUE THREAD

**Issue by ivanbranco** [osm-fr/osmose-backend#1363]
item | 1260
class | 4
Detail: http://osmose.openstreetmap.fr/it/issue/8f8eed06-4998-4b55-b6b9-90f22a970a1b

I think "Public transport relation route not in route_master relation" should not be flagged to routes having the tag public_transport:version=1. But only to routes without public_transport:version tag or with public_transport:version=2.

The [Wiki](https://wiki.openstreetmap.org/wiki/Tag:route%3Dbus) for bus routes says:

> There are subtle differences between two convention of mapping bus route:
> In PTv2, use one relation for each direction, so you generally need 2 relations for a bus line. Don't forget to add these relations to a route_master relation.
> In the traditional PTv1, each direction can be mapped using 2 separate relations (sharing the same ref=* value); or alternatively, using a single relation.

route_master=* was introduced with [PTv2](https://wiki.openstreetmap.org/wiki/Public_transport#Route_Master_relations), PTv1 doesn't need it.

**Comment by frodrigo** [comment]
@nlehuby what do you think of this ?

**Comment by nlehuby** [comment]
Agreed, it seems legit to exclude from this analysis the relations with an explicit `public_transport:version = 1` tag

**Comment by deuzeffe** [comment]
Maybe @frodrigo  should create another flag for route_masters that are still in PTv1 and need to be fixed?
(or this exists yet?)

**Comment by ivanbranco** [comment]
@deuzeffe my two cents: honestly this flag would just obstruct the Osmose list of many users that will not ever update the route bus from PTv1 to PTv2. Let's say I changed a node of a random way near London, I would get TON of flags for every bus route passing by. Is super annoying and distracts me to focus on mistakes I could fix. Also I bet most people would flag it as "false positive" just to clean up their list.

But as I said is just a personal opinion.

**Comment by deuzeffe** [comment]
@ivanbranco I understand your confusion. Also, when I update the transport networks, osmose brings up many reports, which would allow me to correct, if I have the capacity. 
It seems to me that osmose is among other things a QA tool and it would be a pity if this type of report became invisible for all contributors.
Perhaps simply unchecking the class(es) of reports you don't want to see anymore would be a solution for you?
(translated with DeepL)

Translated with www.DeepL.com/Translator (free version)

**Comment by frodrigo** [comment]
chiave | valore
-- | --
source | 24162
item | 1260
class | 4
lat lon | 45.2694418 11.1019778

**Comment by frodrigo** [comment]
Fixed. Remove 10% of this kind of issues !
https://osmose.openstreetmap.fr/en/issues/open?item=1260&class=4
