### ISSUE TITLE
opening_hours: suggest multiple values

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-backend#1364]
opening_hours editing has gotten to new impressive level, and with that, there is additional ambiguity with suggested corrections.
Would it be possible to update Osmose interface so it would allow showing multiple suggestions.  For example:

Mo-Fr 09:00-20:00; 09:00-17:00; Su 09:00-12:00
could be suggested as:
Mo-Fr 09:00-20:00,09:00-17:00; Su 09:00-12:00
Mo-Fr 09:00-20:00, Sa 09:00-17:00; Su 09:00-12:00

**Comment by frodrigo** [comment]
@dfaure What do you think of this ?

**Comment by dfaure-kdab** [comment]
This requires artificial intelligence of some sort :-)

More seriously, this doesn't really seem possible to me, in the end a human has to think about what another human might have meant, this is why this fixing isn't automated.

**Comment by frodrigo** [comment]
@dfaure-kdab thank.
