### ISSUE TITLE
mhs_inscription_date: compare year only

### ISSUE THREAD

**Issue by treinen** [osm-fr/osmose-backend#137]
Hi,

when mhs:inscription_date is filled in with day and month, osmose proposes a fix which consists in replacing the value by the year only. osmose should extract the year from the existing date, before
comparing. For instance here :

http://osmose.openstreetmap.fr/en/error/7850477883

**Comment by frodrigo** [comment]
Duplicate #136

**Comment by frodrigo** [comment]
Yes, It does not. And I don't think it will.

Cause it's too much complicated to do this, IMHO.

Feel free to study the code, and make a pull request yourself if you want.
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_heritage_FR_merimee.py

Hint : https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge.py#L876

**Comment by frodrigo** [comment]
#140 has a better solution to this problem.
