### ISSUE TITLE
"The duration is invalid (try a number of minutes)" being applied incorrectly

### ISSUE THREAD

**Issue by osm-spiregrain** [osm-fr/osmose-backend#1372]
I've got a few items showing in Osmose with the error "The duration is invalid (try a number of minutes)" - r3657604 , r310588, r3659059, & r3658190.     Item "9014 public transport", class 9014022.

- http://osmose.openstreetmap.fr/en/issue/a63a7e73-378a-b6a4-0cff-45f1ff2de59e
- http://osmose.openstreetmap.fr/en/issue/f013d4ca-0070-0bdb-ab99-d6f26d963ad0
- http://osmose.openstreetmap.fr/en/issue/008b7297-8cc0-7e6e-eda4-0cb384c7f56c
- http://osmose.openstreetmap.fr/en/issue/93387426-35b6-47ef-abc9-dc385d7381e4

In each case, the duration tag is correctly in HH:MM format.   Correct according to:

- https://wiki.openstreetmap.org/wiki/Public_transport  and
- https://wiki.openstreetmap.org/wiki/Key:duration

We learn that bus journeys on the Isle of Wight take 55minutes, max.    

But I think osmose is over-reporting the issue.  Please advise.

**Comment by frodrigo** [comment]
cc @nlehuby

**Comment by osm-spiregrain** [comment]
Having tracked down the source code, it could be that the validator is expecting "00:55", but seeing "0:55".  Perhaps it is valid after all.

**Comment by nlehuby** [comment]
I guess this is the rule: https://github.com/Jungle-Bus/transport_mapcss/blob/master/transport.validator.mapcss#L329

it seems already ok for HH:MM format
