### ISSUE TITLE
Search for former (now-redundant) temporary road closures

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1373]
In The Netherlands, there is a slight tendency to map temporary road closures too using conditional restrictions, i.e. [`access:conditional=no @ (2021 Jun 18-2021 Sept 15)`](https://www.openstreetmap.org/way/6932270/history). However, this eventually leads to many unneeded conditional restrictions, like the way I used as an example.
Hence I would propose adding a (very simplified) way of checking for "aged" conditional restrictions, using approximately the following flow diagram:

1. (Skip the test on non-ways and ways without `highway` key)
2. Get all tags with `*:conditional` on the highways. If none, exit.
3. For every of these tags, get the value; split it by `;`. Let's call the fragments **"A"** here. Note to self: not if `;` in brackets, e.g. `no @ (2021; 2025)`
4. For all fragments in **"A"**, get the part after the `@`. Let's call it **"B"** here. (Note to self: check if `@` exists)
5. For every **"B"**, search for the *last* occurrence of 4 consecutive numbers (a year or the end of a year range). Let's call the result **C** here.
6. If **"C"** is found, check if **"C"** < current year. If so, raise a warning

It's simplified to years-only as the conditional syntax is too complicated to check for week ranges / month ranges etc. as well.

Please let me know if you think this test is (or isn't) a good addition; if fine, I'll try to program it in the Christmas-New Year break

**Comment by frodrigo** [comment]
Yes, its is interesting.
Check anyway if there is not an existing lib able to parse it.

**Comment by Famlam** [comment]
> Yes, its is interesting.

Great! I'll do it next week :)

> Check anyway if there is not an existing lib able to parse it.

Unfortunately I couldn't find a standalone library yet; those that exist are highly experimental and non-python. I could theoretically parse it partially manually and then feed it into the opening_hours parser, however that'd require much more manual pre-parsing than the above approach (as it'd fail with i.e. `no @ (2019-2021 AND weight > 30)`). Hence I believe manual parsing is currently the safest way

**Comment by frodrigo** [comment]
cc @dfaure in case you are interested in a new challenge with https://wiki.openstreetmap.org/wiki/Conditional_restrictions ;-)

**Comment by Famlam** [comment]
I just spotted `interval:conditional = 10 @ (Mo-Su 06:00-07:59, 23:00-24:30); 3 @ (Mo-Fr 08:00-08:59); 5 @ (Mo-Su 11:00-17:59);` [(link)](https://osmose.openstreetmap.fr/nl/issue/053ebe4f-c1f0-fe08-ded9-d32f1e60034b) 
It results in the error `Missing condition or parentheses in "interval:conditional"`

Do you believe this is clear enough, or should I special-case tags ending with a `;`?
(Or probably this should be a generic rule in TagFix_MultipleValue.py as I don't think there's any tag allowed to (start or) end with a `;`, right?)

**Comment by frodrigo** [comment]
> Do you believe this is clear enough, or should I special-case tags ending with a ;? Edit, warning has been slightly rephrased

Obliviously, the message does not match the issue. But if it is very unfrequent I think you can keep it as is, unless it is easy to fix it.

**Comment by Famlam** [comment]
Odd, somehow the expired items of 2021 don't always show up yet. For example, Netherlands_Utrecht (source=5042), results updated 2 hours ago, should contain the way I used in my initial post.
https://osmose.openstreetmap.fr/nl/issues/open?source=5042&class=33503&useDevItem=all&username=&bbox=

Does the server evaluate init() long before the actual run, perhaps?

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/nl/issues/open?source=5042&item=3350&class=33503&useDevItem=all

May should contain the item to use the class.

**Comment by Famlam** [comment]
https://osmose.openstreetmap.fr/nl/issues/open?source=3064&class=33503&useDevItem=all&username=&bbox=
That is unlikely be the issue, because this link (other country, no item in the link) does show entries, while the link of Utrecht you mention shows also nothing.
Maybe the plugin was initialized & scheduled in 2021 already, let's see in about 2 days

**Comment by Famlam** [comment]
But another day ahead, also i.e.
https://osmose.openstreetmap.fr/nl/issues/open?source=4682&item=3350&class=33503&useDevItem=all
still doesn't list i.e. 
https://www.openstreetmap.org/way/626899709
https://www.openstreetmap.org/way/723133840
🤔

**Comment by Famlam** [comment]
So it seems that [the 2021 items](https://osmose.openstreetmap.fr/nl/issues/graph.png?source=&class=33503&useDevItem=all&username=&bbox=&item=3350&limit=5000) are indeed coming up, just two days "late". (Practically all new entries in class 33503 between yesterday evening and now are expired "2021"-issues). So I guess `init()` was just called in 2021 (server time) and it took some time until it was actually ran or so.


In 33501 (invalid conditionals) I didn't find new false positives; only some rare cases where the error message isn't too well describing the issue (one that was like `*:conditional=(xxx@yyy)` for example, and the rules terminating with a `;` described above). Those are relatively rare, and the rules are truly invalid, so I can live with that.

In 33502 (recommendation for parentheses) I didn't find false positives, so I'm happy with it. However, if you believe the number of errors ([currently 9392](https://osmose.openstreetmap.fr/nl/issues/open?source=&class=33502&useDevItem=all&username=&bbox=&item=3350&limit=1)) is too big, I can make it slightly more tolerant (for example by allowing also "simple" ranges like `no @ Jan-Mar` and/or `no @ 06:00-09:00`)

In 33503 (expired conditionals) I did find a few very rare false positives: 2x a rule that had the condition `engine=ice AND det<2011` (no clue what that means), and 30x a conditional rule that ends with a [year >= 2100](https://www.openstreetmap.org/way/161671315) (while the regex searches for `20xx`). The first 2 I've simply marked as false positives; the 30 others I'm fine with ignoring (as I'm pretty confident that no official legislation has traffic restrictions until a fixed date in the year 21xx), but I could also just as well fix them if you wish.


**Conclusion**: personally I'd say it's ready to be deployed to the world, would you agree? (And if so, do I need to do something on the frontend?) Or would you prefer me to make any kind of adjustment(s)?

**Comment by frodrigo** [comment]
OK, lets enable it.

**Comment by Famlam** [comment]
Great! :)

![image](https://user-images.githubusercontent.com/1315520/147982041-e54fdbf6-eb94-4dbc-b475-57142c66c904.png)
May I perhaps recommend to name the item (in the menu left on the map view) "Conditional restriction" instead, (similar to item 3250 being called "opening hours" rather than "invalid opening hours")? Only class 33503 handles expired items, the other two classes deal with broken tags and less-optimal tags respectively.

**Comment by frodrigo** [comment]
right, done.
