### ISSUE TITLE
Data source IdFM RELEX not more available

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1377]
The analyser `analyser_merge_public_transport_FR_stif` is no more working because the data source is no more available at
https://data.iledefrance-mobilites.fr/explore/dataset/referentiel-arret-tc-idf/information/?sort=fichier

@nlehuby there is a replacement data source or we need to remove it ?

**Comment by nlehuby** [comment]
This dataset has the same scope: https://data.iledefrance-mobilites.fr/explore/dataset/arrets/information/

**Comment by frodrigo** [comment]
Les arrêts avec geoloc sont ici https://data.iledefrance-mobilites.fr/explore/dataset/referentiel-arret-tc-idf

**Comment by frodrigo** [comment]
I re-enable bust stops. We will disable it again if it still makes issues.

**Comment by frodrigo** [comment]
Update in progress
https://osmose.openstreetmap.fr/en/issues/open?source=408822&item=xxxx

**Comment by frodrigo** [comment]
We have the result. But it come with lots of issues:
- stop type not reported in the issue
- `ref:FR:STIF` ends with `.0`
- `ref:FR:STIF` should be used ? conflation should be done on ``ref:FR:STIF` ?

https://osmose.openstreetmap.fr/en/issues/open?source=408822&item=xxxx
https://osmose.openstreetmap.fr/en/issues/open?source=408823&item=xxxx
https://osmose.openstreetmap.fr/en/issues/open?source=408824&item=xxxx
https://osmose.openstreetmap.fr/en/issues/open?source=425086&item=xxxx

@nlehuby please, can you review the results and have your feedback.

**Comment by nlehuby** [comment]
I'm mostly a bus lover, I never dig out the data to know if the `ref:FR:STIF` of the tram stop should be on the railway=tram_stop, the platforms, the stop_positions, both or none: we really need some doc about this ref  :see_no_evil:
Here is the good place: https://wiki.openstreetmap.org/wiki/France/Transports_en_%C3%8Ele-de-France#R.C3.A9f.C3.A9rences_Open_Data For now, it's only talking about the bus stops and it may be outdated. 

What would be useful, for each stop type:
- what kind of object do we have in IDFM data: is it a station ? is it a platform (quay) ? do we have both ?
- what object in OSM (public_transport=station and/or platform and/or stop_position and/or something else) ? can one IDFM object mach several OSM object ? can one OSM object match several IDFM object ?

**Comment by nlehuby** [comment]
@frodrigo j'ai analysé les données et les résultats et effectivement il y a pas mal de problèmes.

Globalement, les objets matchent tous des `public_transport=platform` (donc des arrêts de bus et des quais) donc

* pour le bus, ça devrait être ok (après correction du `.0` et des autres remarques)
* pour le tram, on devrait matcher sur railway=platform (plutôt que railway=tram_stop), avec le wording "Quai de tram" plutôt que "Arrêt de tram"
* pour le métro, on devrait matcher également sur railway=platform (au lieu de railway=station), avec le wording "Quai de métro" plutôt que "Station de métro". 
* pour le train, c'est plus compliqué :
   * on a également des quais : donc on voudrait matcher aussi sur railway=platform (au lieu de railway=station), avec le wording "Quai de RER ou Transilien" au lieu de "Station ferrée / Val"
   * mais on a aussi un objet supplémentaire pour chaque gare et je ne sais pas trop ce que c'est. Ils sont facilement identifiables sur les gares SNCF car le nom est différent (par exemple "Maurecourt" pour les quais et "Gare de Maurecourt" pour l'objet bonus). Je ne vois pas trop comment le filtrer, il n'a pas d'attributs qui permettrait de l'ignorer dans le traitement.
    * Donc deux options : ne rien faire de spécial mais on aura plusieurs centaines de faux positifs ou bien ne pas afficher du tout les trains


remarques complémentaires:
* Il manque pas mal de quais dans OSM sur le métro (pas facile à mapper, en souterrain et indoor) donc c'est tentant de matcher sur railway=station. Mais de mon point de vue, ça ne marche pas car on a plusieurs objets dans les référentiels IDFM (un par quai et non un par station)
* j'ai regardé dans le GTFS (qui utilise ces mêmes identifiants pour fabriquer le `stop_id`) mais ça ne règle pas le problème du train (les quais ne sont pas présents, il y a à la place encore un autre objet avec un autre id) tout en complexifiant le filtrage par mode transport
* il y a un peu plus d'info dans le fichier des arrêts au format Netex sur les quais des trains (on a notamment le numéro du quai ou de la voie) mais toujours l'objet bonus (et surtout beaucoup plus de boulot pour extraire les quelques infos qui nous intéressent)

**Comment by nlehuby** [comment]
@frodrigo can we deactivate it while we are working on it ?
Some mappers are already using these results, adding random ref (ex https://www.openstreetmap.org/node/5888412454) or on wrong objects (ex https://www.openstreetmap.org/changeset/118325846 on 28 items !)

**Comment by frodrigo** [comment]
Disabled. Can be shown with `useDevItem=all`.

**Comment by frodrigo** [comment]
Due to many issues the data is still not up to date

https://osmose.openstreetmap.fr/en/issues/open?source=408822&item=xxxx&useDevItem=all
https://osmose.openstreetmap.fr/en/issues/open?source=408823&item=xxxx&useDevItem=all
https://osmose.openstreetmap.fr/en/issues/open?source=408824&item=xxxx&useDevItem=all
https://osmose.openstreetmap.fr/en/issues/open?source=425086&item=xxxx&useDevItem=all

**Comment by frodrigo** [comment]
Data look updated. But something wrong. Look like not using the new code, or data not update but only the update the date.
