### ISSUE TITLE
Conditional restrictions: style recommendations

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1380]
There are three style recommendations in the wiki for conditional restrictions for which we could hypothetically warn:

1. Warn about missing space around `@` (suggested by @jocelynj in #1376 in the review comments). I personally don't mind too much about the space being present and fear that the number of markers would overwhelm more important edits, while bots can fix this and it's unlikely that people will make mistakes due to the absence of spaces.

2. Warn about `and` instead of `AND`? Initially implemented in #1376, the first results showed too many "bad" conditionals like `opening_hours:conditional = 24/7 @ ('camper and fisherman')` where this would be confusing. (It's meant as a comment & it's an invalid condition: one cannot be a camper and a fisherman simultaneously, unless you throw your rod out of the camper window, probably an "or"-like statement is meant, which (in dummy tags) would be `24/7 @ camper; 24/7 @ fishing` ). Making it `AND` would make no sense. For now, the error was disabled in [this commit](https://github.com/osm-fr/osmose-backend/pull/1378/commits/1676e79bc71aef78e3bb8797691c3884723e24fc). These were the results after roughly 3/4th of the world was checked:

> - 2x: `opening_hours:conditional = 24/7 @ ('camper and fisherman')` **(invalid warning)**
> - 2x: `restriction:conditional = no_left_turn @ bus and trucks` **(invalid warning)**
> - 2x: `access:conditional = yes @ MAY 1st - OCT 31 and 06:00 - 22:00` (inefficient, but maybe valid?)
> - 1x: `restriction:conditional = no_left_turn @ truck and bus` **(invalid warning)**
> - 1x: `hgv:conditional = no@(22:00-07:00 and maxweight>=1.5)` (valid warning, although probably `weight` is meant)
> - 1x: `hgv:conditional = no @ (19:00-07:00 and weight>7.5)` (valid warning)
> - 1x: `charge:conditional = $4.50 @ (axle >= 6); $4.00 @ (axle = 5); $3.50 @ (axle = 4); $3.00 @ (axle = 3); $2.50 @ (axle = 2 and wheel >= 6)` (valid warning)
> - 1x: `charge:conditional = $13.50 @ (axles >= 6); $12.00 @ (axles = 5); $10.50 @ (axles = 4); $9.00 @ (axles = 3); $7.50 @ (axles = 2 and wheels >= 6); $4.50 @ (axles = 2 and trailer); $3.00 @ (axles = 2 and wheels = 4)` (valid warning)
> - 1x: `restriction:conditional = no_left_turn @ (06:00-17:00) @ trucks and contractors` **(invalid warning)**
> - 1x: `maxweight:conditional = no @ delivery AND agricultural And bus And tourist_bus` **(invalid warning)**
> - 1x: `toll:motor_vehicle:conditional = yes @ (emissions<euro_4 and weight>3.5)` (valid warning)
> - 1x: `charge:motor_vehicle:conditional = £200 per day @ (emissions<euro_4 and weight>3.5)` (valid warning)
> - 1x: `fee:conditional = no @ (Sep 27, "International Tourism Day Sundays in the period between 1 November and 31 March"); no @ (age < 18)` **(invalid warning)**

Hence I'm not in favor of re-adding this rule

3. Warn about missing parentheses (when the lack of them is not clearly wrong)? If so, I can think of four ways to do so:
**Option 1**: at the `;` where the 2nd conditional starts (i.e. the semicolon in `a@b;c@d`), check if the previous condition (`b`) had parentheses and if not, recommend parentheses (regardless of the condition itself, so also if it's a simple one like `wet`)
**Option 2**: check if there's a `;` somewhere in the entire tag, if so, recommend parentheses around all conditions if missing (regardless of the position of the `;` and regardless of the condition being simple or not)
**Option 3**: Check if the condition of the conditional contains any other characters than alphanumerical (a-z,A-Z,0-9), if so, recommend parentheses if missing
**Option 4**: a combination of 1 and 3
For simplicity, I like option 2, but they're all possible. In #1382 I went for option 3.
I think this is the most important warning of the three, as I've seen errors that were made because of the lack of braces, that couldn't easily be spotted without way more complicated interpretation of the tag, i.e.: `no @ Fr 16:00-24:00; Sa,Su 00:00-24:00; yes @ wet` is currently interpret as `no @ Fr 16:00-24:00` + `Sa,Su 00:00-24:00; yes @ wet` and considered valid (as we do not check that `Sa,Su 00:00-24:00; yes` is invalid for i.e. `access:conditional`. Warning about missing parentheses might trigger people to cause that the `)` should be after the `Sa,Su 00:00-24:00` part of the rule)

**Comment by Famlam** [comment]
Implemented the third one in #1382
@frodrigo what's your opinion on the first item: spaces around `@`? I'm not in favor, @jocelynj is, so you're the decisive vote (unless someone else steps in ;) ). If two say "please do", I'll program it: it's very easy: `if not " @ " in tag_value: [newline] err.append(...)`, so it's mostly about the added value of those warnings.

**Comment by jocelynj** [comment]
Just to be clear: I'm not sure if the right way is to:
  - force spaces in the tag value
  - or improve analyser to also check cases where there are no spaces

Do you know what current tools using these tags expect?

**Comment by Famlam** [comment]
> or improve analyser to also check cases where there are no spaces

Ah, in that case, the analyser does check those already ;). `no@wet` and `no @ wet` are both identically analysed (I just strip the spaces, literally). I was in the impression that you just wanted the analyser to add an additional warning.


> Do you know what current tools using these tags expect?

Quickly checked two:
- [OsmAnd](https://github.com/osmandapp/OsmAnd/blob/0f1734271756bf7578f0f9ece63b752be8496064/OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapRouteReaderAdapter.java#L241) first splits by `);` and then simply looks for the `@` and splits the value there, trimming spaces of the fragment. Also, it does require parentheses if there's multiple rules (`a@b;c@d` it can't parse, `a@(b);c@d` it can)
- [GraphHopper](https://github.com/graphhopper/graphhopper/blob/0522c495ccad5f22fe19c6e858a40a7bd6f74eae/core/src/main/java/com/graphhopper/reader/osm/conditional/ConditionalParser.java#L117) does not support combined conditions, but for a single conditional (`a@b`) it just splits by `@` and trims spaces and parentheses

**Comment by jocelynj** [comment]
Thanks for the answer - I thought that the plugin was working only if there was spaces :) 

So, I'm no longer interested in an additional check for spaces, especially as tools don't need spaces. Sorry for the misunderstanding!

**Comment by Famlam** [comment]
Thanks! Then I guess the parentheses check is the only relevant one, hence I've marked it "no longer a draft".
Feel free to reject it if you don't think it's needed though!

**Comment by Famlam** [comment]
@frodrigo @jocelynj Happy new year :)

(I've found no false positives with this addition and it'll become live when #1373 becomes publicly available, so I'm closing this issue)

**Comment by frodrigo** [comment]
> Seems as if these rules are requiring parentheses in cases in which they are not needed (leading for example to this complaint https://github.com/MarcusWolschon/osmeditor4android/issues/1999). As characters are really a scarce resource for these tags they should IMHO not be wasted on formatting that doesn't actually do anything.

Fixed by https://github.com/osm-fr/osmose-backend/pull/1832
