### ISSUE TITLE
building relation without building tag

### ISSUE THREAD

**Issue by ivanbranco** [osm-fr/osmose-backend#1381]
item | 9007
class | 9007001
Detail: http://osmose.openstreetmap.fr/it/issue/dece295b-a51c-a96f-5e14-7c106151544b

Uhm, not sure about this one. The Wiki page for [type=building](https://wiki.openstreetmap.org/wiki/Relation:building) doesn't mention that you have to put the building=* tag in the relation itself. Instead it says "This outline must be tagged with building=* ", in which the outline is the building added as a member and mapped as an enclosed way. I suspect this Osmose flag is dated back to the now deprecated [IndoorOSM schema](https://wiki.openstreetmap.org/wiki/Proposed_features/IndoorOSM), in which the building=* tag (and all other building descriptive tags) was put on the relation itself: "A building is represented as a relation within our model".

Maybe someone can double-check?

**Comment by ivanbranco** [comment]
something I thought about now, if someone else confirms this, the flag could be changed to check the opposite, such as "building relation with building tag", so we can fix relations using the old deprecated schema

**Comment by frodrigo** [comment]
It comes from this JOSM MapCSS rule
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/relation.mapcss#L12

It expects a `building` tag.

**Comment by osm-spiregrain** [comment]
I spent some time this week responding to this error by added building=* to relations.   Osmose responded by flagging all these relations with "Object tagged twice as way and relation" the next day.   (I think because, as you suggest, the relations follow the convention that the building=* tag goes on the member with role "outline"; and adding to the relation doubles-up).

**Comment by ivanbranco** [comment]
Yes, because this way a building is represented both as way and relation, this seems to go against the "One feature, one OSM element" principle

**Comment by osm-spiregrain** [comment]
Agreed.  And I think that means that this "building relation without building tag" rule can be removed.

**Comment by osm-spiregrain** [comment]
Looks like this is an error in JOSM that is on the way to being resolved-

- https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/relation.mapcss#L70  (see row 70)
- https://josm.openstreetmap.de/ticket/21738

Will this be reflected in Osmose automatically?

**Comment by frodrigo** [comment]
It requires a manual update.

**Comment by frodrigo** [comment]
Mapcss updated.
