### ISSUE TITLE
leisure=golf_course and sport=golf (analyser_merge_pitch_FR.py)

### ISSUE THREAD

**Issue by Olyon** [osm-fr/osmose-backend#139]
Sur le wiki il est dit que leisure=golf_course implique sport=golf ( http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course ).
Donc ça serait plus juste et donc donnerait moins de faux positifs dans osmose si dans pitch_FR.mapping.csv on enlevait sport=golf lorsqu'il est avec leisure=golf_course.

**Comment by frodrigo** [comment]
What wrong with sport=golf on leisure=golf_course ?

Whitch false positive do you talk about ?

**Comment by Olyon** [comment]
exemple: http://osmose.openstreetmap.fr/fr/map/#source=5833&item=8170&class=61&zoom=16&lat=45.92&lon=4.71552&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT
un golf est proposé à l'integration au milieu d'un golf déjà present dans osm. Le problème c'est que les tags du golf dèja present sont juste leisure=golf_course et name=... et il n'y a pas sport=golf donc pour osmose ce n'est pas un golf.
Pourtant, d'après le wiki, pour un golf le tag leisure=golf_course suffit, sport=golf est inutile.
Pour régler le problème il me semble qu'il suffit de supprimer sport=golf lorsqu'il est avec leisure=golf_course dans le fichier pitch_FR.mapping.csv.
