### ISSUE TITLE
(New) route relations reported as not in route_master relation (while they are)

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1390]
I updated the bus routes in my region, which means I added a few new bus `route` relations as well, but for some reason Osmose doesn't recognize these bus routes being in a `route_master` relation? Oddly enough, this works fine with all existing relations, it only fails when new route relations are added...
(And the route_master always either existed already or was added simultaneously with the bus line)

http://osmose.openstreetmap.fr/en/issue/075759dc-1630-2387-6a63-f2cdcd9e54ef
http://osmose.openstreetmap.fr/en/issue/f3b8db16-157c-394f-e3b5-32cc2e95d7c9
http://osmose.openstreetmap.fr/en/issue/b891e8b4-09df-9436-673c-4cec932a50ab
http://osmose.openstreetmap.fr/en/issue/9a60a7ab-ac12-b73e-ca51-6fd487506fcf
http://osmose.openstreetmap.fr/en/issue/735ed3d4-df80-0535-a114-c7e955920c7b
http://osmose.openstreetmap.fr/en/issue/f3b8db16-157c-394f-e3b5-32cc2e95d7c9

item 1260
class 4
`Public transport relation route not in route_master relation` from here: https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_public_transport.py#L219

**Comment by frodrigo** [comment]
If you are sure about the data. We have to check the relation is in the extract by extraction of a bbox or a object id.
http://download.openstreetmap.fr/extracts/europe/netherlands/

**Comment by Famlam** [comment]
Thanks Frodrigo! I checked the result using
`osmconvert64-0.8.8p.exe gelderland.osm.pbf --drop-nodes --drop-ways --out-osm > gelderland.osm`
and then loading the result in JOSM.

It seems that indeed i.e. `relation 13674358` and `relation 13674359` (the bus routes) *are* present, but `relation 5667107` their (route_master) is missing. Same for the relation of bus line 11 of Arnhem.

This is what you see when you open the created gelderland.osm file in JOSM and open the relation that contains all bus route_master relations of the Nijmegen-Arnhem area: clearly the two new ones aren't included.
![image](https://user-images.githubusercontent.com/1315520/149810208-dd7e142a-2fa8-43f3-80f7-e6dac56e6670.png)

Any clue where to report this, assuming it's not osmose who generates those files? (Note: my French is limited to je ne parle pas français ;) )

**Comment by frodrigo** [comment]
cc @jocelynj issues of extract on relation of relations.

**Comment by Famlam** [comment]
Maybe similar as it's also related to updating the extract (or the lack thereof): 
http://osmose.openstreetmap.fr/nl/issue/e600f9bc-6470-3912-0f47-6c5d12fa4822
This way has been deleted for almost 3 weeks, yet still exists in yesterdays extract: https://www.openstreetmap.org/way/924453130

`osmconvert64-0.8.8p.exe gelderland.osm.pbf -b=5.7,51.7,5.9,52 --drop-nodes --drop-relations --drop-author --out-osm > gelderland.osm` on yesterday's pbf file still gives:
```
	<way id="924453130" version="1">
		<nd ref="3546490037"/>
		<nd ref="44086402"/>
		<tag k="fixme" v="Wandelroute op straat, hoe loopt deze echt?"/>
		<tag k="highway" v="footway"/>
	</way>
```

If unrelated, I'll create a new issue for this

**Comment by Famlam** [comment]
All of the above issues have now resolved itself, with the exception of http://osmose.openstreetmap.fr/en/issue/9a60a7ab-ac12-b73e-ca51-6fd487506fcf which became a different issue. (So apparently the hash isn't unique 🤔 ). Anyway, this issue is resolved :)
