### ISSUE TITLE
"Default and local language name not the same" on Saami-language names in northern Finland

### ISSUE THREAD

**Issue by CRCulver** [osm-fr/osmose-backend#1391]
In the Lapland region of Finland, name= tags of ways are generally in the Saami language (a regionally official language), not Finnish. Consequently, the name= tag will differ from the name:fi tag. Osmose is incorrectly marking these ways with a "Default and local language name not the same" error.

An example is [this way](https://osmose.openstreetmap.fr/map/#&item=5060&zoom=17&lat=69.3975539&lon=25.8548617&level=1&tags=&fixable=&issue_uuid=9e1c2fbc-2511-113b-207f-7bd7dc031c05) that has the following tags:

```
name = Norggageaidnu
name:fi = Norjantie
name:se = Norggageaidnu
```

Osmose should treat this region of Finland differently from other regions of the country.

**Comment by frodrigo** [comment]
Please can you review the language configuration of the country.
The configuration not the default language(s) for the area.

https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L713-L733

**Comment by CRCulver** [comment]
Yes, so I think this line:

```
fi_part('lapland', 2541341, 'FI-10', language="fi")
```

Should actually be something like this:

```
fi_part('lapland', 2541341, 'FI-10', language=["fi", "se"])
```

by analogy with Finland’s other bilingual regions.
