### ISSUE TITLE
False positive for direction tag on stop or give way

### ISSUE THREAD

**Issue by davidpnewton** [osm-fr/osmose-backend#1392]
There is a false positive for missing direction tag on a stop or a give way.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_traffic_signals.py#L180

When direction is equal to a numerical value (compass bearing) the system incorrectly reports that direction is missing as a tag.

http://osmose.openstreetmap.fr/en/issue/faa6882b-0c54-b38c-9f41-5b9a30968d75

http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=52.266474&lon=-1.530249&item=1010%2C1040%2C1050%2C1060%2C1070%2C1080%2C1090%2C1100%2C1110%2C1120%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1260%2C1270%2C1280%2C1290%2C2xxx%2C5xxx%2C6xxx%2C7xxx%2C8xxx%2C9001&level=1%2C2%2C3

**Comment by AndrewKvalheim** [comment]
Is this the same issue as #602?

**Comment by frodrigo** [comment]
`highway=give_way` is for the stop location. While `direction=75` is for road sign. Use `direction=forward|backward` in this case.


> Is this the same issue as #602?

Yes I think it is the same.

**Comment by davidpnewton** [comment]
So then please tell me which way of which the node is part the "forward" or "backward" applies to? I am quite aware that in reality for node 1297495951 using "forward" or "backward" would apply to way 54571966. That's because I am human. How is a machine to tell that this is the case and that it doesn't apply to way 121989523?

Answer me that one properly and your closing of this issue is legitimate. Since you actually can't answer me that one properly, as no such proper answer exists, your rejection of the issue and closure of it is illegitimate.

The tagging applied is generic forward and backward. It has no namespace to denote that it applies to the highway tagging on the node. Were such a namespace applied to the tagging then you would have a point. It isn't and therefore you are simply wrong.

Fix the issue. Stop the system falsely reporting problems where none actually exist. Either alter the system to report that no namespace is applied to the forward and backward tags so that things can be fixed in that manner or stop the false positive.

**Comment by frodrigo** [comment]
So, please. Can you explain what is wrong and how to fix it.
Please add link to the wiki.

**Comment by AndrewKvalheim** [comment]
> So then please tell me which way of which the node is part the "forward" or "backward" applies to? I am quite aware that in reality for node 1297495951 using "forward" or "backward" would apply to way 54571966. That's because I am human. How is a machine to tell that this is the case and that it doesn't apply to way 121989523?

Node [1297495951](https://www.openstreetmap.org/node/1297495951) is on only one `highway=*` (way [54571966](https://www.openstreetmap.org/way/54571966)) so it must apply to that. It’s also on an `area:highway=*` (relation [1673026](https://www.openstreetmap.org/relation/1673026)) but those are [non-routable](https://wiki.openstreetmap.org/wiki/Key:area:highway).

**Comment by davidpnewton** [comment]
> Either alter the system to report that no namespace is applied to the forward and backward tags so that things can be fixed in that manner or stop the false positive.

Either alter the system to report that no namespace is applied to the forward and backward tags so that things can be fixed in that manner or stop the false positive.

**Comment by davidpnewton** [comment]
> So, please. Can you explain what is wrong and how to fix it. Please add link to the wiki.

Either alter the system to report that no namespace is applied to the forward and backward tags so that things can be fixed in that manner or stop the false positive.

I have already told you how to fix it with the information above. Decide which solution you want to apply and apply it. Either report that generic "forward" or "backward" tags need an extra namespace adding to them or stop ignoring the presence of the direction tag with degree values.

**Comment by AndrewKvalheim** [comment]
What namespace are you referring to? Or are you proposing one? The [wiki](https://wiki.openstreetmap.org/wiki/Talk:Tag:highway%3Dstop) might be a better place to have that discussion.

**Comment by davidpnewton** [comment]
> > So then please tell me which way of which the node is part the "forward" or "backward" applies to? I am quite aware that in reality for node 1297495951 using "forward" or "backward" would apply to way 54571966. That's because I am human. How is a machine to tell that this is the case and that it doesn't apply to way 121989523?
> 
> Node [1297495951](https://www.openstreetmap.org/node/1297495951) is on only one `highway=*` (way [54571966](https://www.openstreetmap.org/way/54571966)) so it must apply to that. It’s also on an `area:highway=*` (relation [1673026](https://www.openstreetmap.org/relation/1673026)) but those are [non-routable](https://wiki.openstreetmap.org/wiki/Key:area:highway).

Why "must it apply to that"? There are two ways which intersect at that node. Just because only one of those ways is "routable" does NOT mean that the generic backward and forward tags "must" apply to that way and that way only. Now I know which way it should apply to, but I only know that because of context and I get the context because I am human.

For a further example consider node 8321868641. Consider its tagging VERY carefully and then think about how that applies to this situation for highway=give_way. It is tagged with traffic_sign=GB:616 and traffic_sign:2=GB:613. It is also tagged traffic_sign:direction=backward and traffic_sign:2:direction=forward. So why do you think I didn't merely tag it direction=forward or direction=backward when creating it? Why would doing that have been utterly useless?

It would have been completely useless because it would have been AMBIGUOUS. Which of the two traffic signs at that point is being referred to by "direction=forward" or "direction=backward"? Now I know that the no entry sign applies backwards along the way and I know that the no left turn sign applies forwards along the way. How do I know that? Context gained by being human.

So why am I objecting to plain direction=forward or direction=backward tagging in the instance of the node I originally cited? It is AMBIGUOUS. Tagging with the facing of the give way line in degrees is unambiguous. There is no possibility of confusion about which direction is being referred to and yet it is flagged as wrong tagging. If there is only one way that the node is part of then that's fine. One way has only one direction. There is no ambiguity. Any situation where the node is part of more than one way means ambiguity is present.

Don't just assume that the situation will always be as in this case with one way ruled routable and one ruled not routable. That is an incomplete solution to the problem. Allowing direction=360 or direction=245 or direction=75 or any other such tagging with direction expressed in degrees as correct for situations where a node is part of two or more ways removes any possibility of ambiguity for what direction is being referred to.

As I said above either remove stop reporting false positives for the direction tag being missing when direction is defined in terms of degrees or shift the reporting of an error over to indicating that ambiguity about which way, or indeed which tag on the node is being referred must be removed by using an appropriate namespace. Highway:direction=forward and Highway:direction=backward for example. That's a less optimal solution and I would much prefer that the simpler solution of stopping reporting false positives of missing direction tags for direction=75 et al.

**Comment by AndrewKvalheim** [comment]
It sounds like you’re proposing an improvement to what’s currently documented on the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway=stop#How_to_map).

**Comment by frodrigo** [comment]
Osmose implements checks based on the wiki. It is not a place to such discussion. Go the forum, mailing list (taging eg) to make such discussion.
