### ISSUE TITLE
False positive: Invalid street level postcode ___ ____ for country code IE

### ISSUE THREAD

**Issue by VictorIE-OSM** [osm-fr/osmose-backend#1397]
This https://osmose.openstreetmap.fr/en/byuser/VictorIE?username=VictorIE&item=3190 is a list of post codes (Eircodes https://www.eircode.ie/ - it is building specific) in Ireland that Osmose is reporting as problematic. Having inspected a sample of them, they appear to be OK. Is there more information available on this issue? A long time ago there had been an issue with Eircodes not being recognised because the Eircode formatting scheme was incorrectly inputted on Wikipedia, i.e. which characters could be numbers or letters.

**Comment by frodrigo** [comment]
Yes; It uses wikipedia data. Osmose have a cache of 30 days.

But the value look complex `[D6W/ANN] [A/N][A/N][A/N][A/N] (Single exception where its D6W ????)`. Maybe is not valid or not parsed correctly.

https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Postcode.py#L30

**Comment by frodrigo** [comment]
There is an issue. As the code does not achieve to parse the street format, it falls back to area format.

**Comment by frodrigo** [comment]
It is now fixed.
