### ISSUE TITLE
The tag `name=*` contains multiple names, separated by a semicolon, a "/" or a "\" reported for "Kurdwanów P+R"

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1407]
https://osmose.openstreetmap.fr/en/issue/38e58213-532c-76be-f2a3-918fc68bc90c

https://www.openstreetmap.org/way/536372054

item | 5030
-- | --
class | 705

1) there is neither ; nor \ nor / in the name
2) this is a valid name
3) https://en.wikipedia.org/wiki/Park_and_ride "Park and ride is abbreviated as "P+R" on road signs"

**Comment by matkoniecz** [comment]
1) if + is also causing names to be listed mention it in the error message
2) if + is also causing names to be listed - please exclude "P+R" or at least report that wit lower severity ([my level1 errors](https://osmose.openstreetmap.fr/en/byuser/Mateusz%20Konieczny?level=1) are filled with false positives and pointless reports - that is in my opinion the largest problem with Osmose)

**Comment by frodrigo** [comment]
Done.
