### ISSUE TITLE
/meta/countries API URL not found

### ISSUE THREAD

**Issue by harry-wood** [osm-fr/osmose-backend#1408]
On the [wiki here](https://wiki.openstreetmap.org/wiki/Osmose#One_frontend_and_multiple_backends) it gives this URL: 
http://osmose.openstreetmap.fr/api/0.2/meta/countries which supposedly lists the different osmose backends that are available. 

That is currently responding with `Not found: '/meta/countries'` 404 response.

**Comment by frodrigo** [comment]
API 0.2 is now deprecated. Use the 0.3 : http://osmose.openstreetmap.fr/api/0.3/countries

**Comment by frodrigo** [comment]
> What should this say? : "Full list of end-points available at http://osmose.openstreetmap.fr/en/404. "

Yes I know, there is a migration in progress (since one year ago....) and this is currently not working.
