### ISSUE TITLE
Suggestions to change at identical street names?

### ISSUE THREAD

**Issue by Art-Penteur** [osm-fr/osmose-backend#141]
J'ai ajouté un commentaire sur l'issue #122 ,  mais ça ne la re-ouvre pas, alors j'en ouvre une nouvelle : Osmose suggère des modifications qui me semblent être l'identité : Par exemple "Rue de Gap" en "Rue de Gap"
![erreur_osmose_incomprehensible_20160918](https://cloud.githubusercontent.com/assets/7870824/18613769/7112d38a-7d81-11e6-97db-1185f4954685.png)

**Comment by Art-Penteur** [comment]
Le permalink : 
http://osmose.openstreetmap.fr/fr/map/#zoom=17&lat=43.626228&lon=1.4661&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=7170&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
@cquest 
Il n'y a bien aucune différence entre avant et après.
