### ISSUE TITLE
Possible false positive on all-way stop

### ISSUE THREAD

**Issue by AndrewKvalheim** [osm-fr/osmose-backend#1410]
Osmose is suggesting that this [all-way stop](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstop#All-way_stop) needs a direction:

> <img alt="screenshot" src="https://user-images.githubusercontent.com/1844746/155612374-d9fba64d-85cf-41b4-b8bb-b635e5f5055e.png" width="355" />

- Issue: [41abde35-8a60-56cf-a2a7-82433241f729](https://osmose.openstreetmap.fr/en/issue/41abde35-8a60-56cf-a2a7-82433241f729) “Possible missing direction tag on stop or a give way”
- Node: [53109764](https://www.openstreetmap.org/node/53109764) `highway=stop` + `stop=all`

I expected that being located on a four-way intersection would be sufficient to not need a direction tag, and that `stop=all` would reaffirm this in case of ambiguity.

**Comment by frodrigo** [comment]
There is an implementation for this case. But it may be buggy.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_traffic_signals.py#L152

**Comment by frodrigo** [comment]
I do net reproduce the issue in local. Maybe linked to the diff incremental mode.

**Comment by frodrigo** [comment]
Fixed. Removed diff support.
