### ISSUE TITLE
diameter sign in a description is not OK?

### ISSUE THREAD

**Issue by jajajaneeneenee** [osm-fr/osmose-backend#1414]
I have a question: why should a diameter sign (⌀ = unicode DIAMETER SIGN, 0x2300) in a description text be replaced by "a letter from the appropriate alphabet"? – Script = [Name_Script.py#L54](https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_Script.py#L54)

It is a correct symbol in a description, e.g. "⌀ 1 m" – should it really be replaced by e.g. "Ø" (unicode 00D8, LATIN CAPITAL LETTER O WITH STROKE) – which is often used as a replacement for the correct symbol – but the correct symbol should also be allowed, shouldn't it?

Perhaps this also concerns other symbols ...

**Comment by frodrigo** [comment]
Yes, it is generic rule it match all http://unicode.org/cldr/utility/list-unicodeset.jsp?a=[:General_Category=Other_Symbol:]

But in your case "⌀" is the right symbol, while "Ø" is a letter.

Just mark it as false positive.
