### ISSUE TITLE
Conflicting tags for sides of the way

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1417]
I believe that item 3360, implemented in #1405 and #1411, is ready to be released to the general public without useDevItem flag.

It warns against cases where `tag` conflicts with `tag:both`, `tag:left` or `tag:right`, or if `tag:both` conflicts with `tag:left` and `tag:right`

*Potential false positives that I neglected at this moment*
- It may be that in the future a check needs to be added to allow cases like `key=a;b` + `key:left=a` + `key:right=b`, but this is undocumented behaviour, so unless someone reports this as being the desired way of tagging, I would leave it as it is.
- The same for 10 ways worldwide where there's something like `*_name:left=X` + `*_name:right=Y` + `*_name=X / Y` (with `*`=`alt`/`short`/`old`/...). Can be fixed if desired by making line 61 `if (tag[0:5] == "name:" or "_name:" in tag) and tt in ttd:`, but I guess it's not worth it.

**Comment by frodrigo** [comment]
I enabled the new item. Thank.

**Comment by Famlam** [comment]
Thank you!
