### ISSUE TITLE
Analysis is red

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-backend#1421]
Hello,
The summary page shows analysis in red
http://osmose.openstreetmap.fr/en/control/update_summary

Also:
http://buildbot.osmose.openstreetmap.fr/ is down

Regards

**Comment by frodrigo** [comment]
Yes, we are aware of this.
There a global network issue on osm-fr.

https://github.com/osm-fr/infrastructure/issues/357#issuecomment-1068295075
https://github.com/osm-fr/infrastructure/issues/358
https://github.com/osm-fr/infrastructure/issues/359
And many other non listed on github.

**Comment by frodrigo** [comment]
Network issue solved. Update in progress.
