### ISSUE TITLE
3130 brand in name-rule adjustment

### ISSUE THREAD

**Issue by michael-reuter** [osm-fr/osmose-backend#1430]
Hello,

I noticed that locations marked with not:brand:wikidata still show up on this check. That tag is suggested in ID editor to stop recommendations for businesses with similar names that are not part of the same brand. Is it possible to add that tag as a condition and exclude locations with the tag from the results?

item # 3130
class # 31301

link: https://www.openstreetmap.org/node/4852400457 (reported as false positive)

**Comment by Famlam** [comment]
The fix is live :)
