### ISSUE TITLE
Fails to update to last kopeninghours version

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1434]
Update to last version of kopeninghours is not possible du to compilation issue.

It fails on Debian 10 and Debian 11.3 (last) used in docker.

We cannot deploy the last version of Osmose code due to this issue.

I look at the cmake log on configure stage. But not be able to understand witch check was failing.

See [CMakeOutput.log](https://github.com/osm-fr/osmose-backend/files/8467422/CMakeOutput.log)

Can be reproduced with Docker an probably on any Debian.

@dfaure @Famlam @jocelynj need help on this.

**Comment by frodrigo** [comment]
With @jocelynj we have done review of last changes and update is not required, does it ?

We still have to figure why test is not passing on test setup before deploying.

Nevertheless, it changes nothing about the impossibility to compile the last version.

**Comment by jocelynj** [comment]
My understanding is that the new tag of kopeninghours is adding a new include for CMake: [ECMDeprecationSettings](https://api.kde.org/ecm/module/ECMDeprecationSettings.html#ecmdeprecationsettings), which is not available on Debian Stable, because it has an older version of extra-cmake-modules
```
  CMake Error at CMakeLists.txt:21 (include):
    include could not find requested file:

      ECMDeprecationSettings
```

This was added by this commit: https://invent.kde.org/libraries/kopeninghours/-/commit/12a40d79481b853adc7e48743266a259c1ad3c9b.

**Comment by Famlam** [comment]
> @dfaure @Famlam @jocelynj need help on this.

> With @jocelynj we have done review of last changes and update is not required, does it ?

I would agree that for now, the old version of kOpeningHours is good enough until this is fixed. Don't know how to help with a fix on the kOpeningHours side though

**Comment by dfaure-kdab** [comment]
I just pushed https://invent.kde.org/libraries/kopeninghours/commit/11cfd7b1712e71061cf3226e94223e65aa4d6e36, can you check if this fixes the issue for you? Thanks.

**Comment by frodrigo** [comment]
> I just pushed https://invent.kde.org/libraries/kopeninghours/commit/11cfd7b1712e71061cf3226e94223e65aa4d6e36, can you check if this fixes the issue for you? Thanks.

Thank you. It works for me.

**Comment by Famlam** [comment]
It was updated today, so I guess this issue can close?
