### ISSUE TITLE
Add support for maxheight non-numerical values

### ISSUE THREAD

**Issue by carlosarc87** [osm-fr/osmose-backend#1437]
Non-numerical values for maxheight should be supported. See https://wiki.openstreetmap.org/wiki/Key:maxheight#Non-numerical_values

**Item**: 9006
**Class**: 9006026
**Error subtitle**: unusual value of maxheight: meters is default; only positive values; point is decimal separator; if units, put space then unit
**Error example**: http://osmose.openstreetmap.fr/es/issue/dda3807b-ec35-53f1-e45c-1fe0aaed1e9c

Regards

**Comment by frodrigo** [comment]
This check come from JOSM Validator

Please report this to JOSM.

https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/numeric.mapcss

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/numeric.mapcss#L275
_none_, _default_ and _below_default_ are allowed as non-numerical values in the validator.
The other ones in the wiki _no_indications_, _no_sign_ and _unsigned_ have extremely low usage numbers and lack a proper definition.

**Comment by frodrigo** [comment]
> https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/numeric.mapcss#L277 _none_, _default_ and _below_default_ are allowed as non-numerical values in the validator. The other ones in the wiki _no_indications_, _no_sign_ and _unsigned_ have extremely low usage numbers and lack a proper definition.

Ok, thank you.

**Comment by carlosarc87** [comment]
I have reported this to JOSM https://josm.openstreetmap.de/ticket/22025#ticket
I do not think that those values with low usage should be avoided, they are useful.
