### ISSUE TITLE
False positive: Almost junction on connected way/node

### ISSUE THREAD

**Issue by Helium314** [osm-fr/osmose-backend#1439]
https://osmose.openstreetmap.fr/en/issue/0e751dbe-2f95-6ff7-e6da-b2b18880063d is an "Almost junction" between [W 803435089](https://www.openstreetmap.org/way/803435089) and [N 2195816129](https://www.openstreetmap.org/node/2195816129).
However, it can easily be seen that the node is already part of the way, so I see no possibility of joining them even more (as "join or use noexit tag" is suggested).

Generally it seems there are issues with not detected connections, see also nearby https://osmose.openstreetmap.fr/en/issue/c668ce6d-7487-49b7-a256-b6f1f2f89628 and https://osmose.openstreetmap.fr/en/issue/99d7e53f-8aed-b8e4-3d59-cd800fb589a6

**Comment by frodrigo** [comment]
It more look like a bug in the analyser or a data corruption on analyser server side.
