### ISSUE TITLE
Item 3030 class 1398494170 (règle “ks_vr”): how to fix?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#1443]
(tag=question ^^)

This alert : https://osmose.openstreetmap.fr/fr/issue/5a177e91-2b89-3cea-3f41-ab953d77ea1f

refers to https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagWatchFrViPofm.py#L68

then to https://wiki.openstreetmap.org/wiki/User:FrViPofm/TagwatchCleaner

I don't understand if it must be fixed (and how) or not.

NB : it's the name of a bus stop...

Thx for your help.

**Comment by frodrigo** [comment]
"Notre-Dame" should take a "-" according to toponymic rules when refer to religious.
As the bus stop refer to the place name, referring itself to religious name, it should take "-".
But the bus stop it self may not follow this French toponymic rules.
But as we write on OSM unabbreviated name (eg if the bus stop name was "St-Jean"), I personally think in OSM we must add the "-".

**Comment by deuzeffe** [comment]
Oh yes, of course! Thanks for the tip. I try to respect the French toponomic rules even for bus stops. And sometimes I forget...
