### ISSUE TITLE
Add incorrect key "toilet"

### ISSUE THREAD

**Issue by danieldegroot2** [osm-fr/osmose-backend#1447]
_May require feedback_

Found on wiki page for [`amenity=toilets`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Toilets_within_places)
> Please do not use toilet=yes (singular).

Taginfo: [`toilet`](https://taginfo.openstreetmap.org/keys/toilet#overview)

**Comment by Famlam** [comment]
Isn't this better for i.e. the mapcss rules of JOSM (which are imported to Osmose as well)

**Comment by danieldegroot2** [comment]
If so, just fyi, I've never worked with JOSM's tracker and I think it'd be better left to someone else to post it there in that case.

**Comment by Famlam** [comment]
Filed here: https://josm.openstreetmap.de/ticket/22335

**Comment by Klumbumbus** [comment]
Done in JOSM in https://josm.openstreetmap.de/changeset/18545/josm

**Comment by Famlam** [comment]
Thank you! Very fast :)

**Comment by Famlam** [comment]
I think this has been deployed, right? @frodrigo

**Comment by frodrigo** [comment]
Yes.
