### ISSUE TITLE
Unfinished power line when lines are merging or separating?

### ISSUE THREAD

**Issue by juhanjuku** [osm-fr/osmose-backend#145]
Why there is messages about "Unfinished power line" when two lines are merging on tower and continuing together from there? Or when lines are separating?
Example: [url](http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=-21.783114&lon=-48.26265&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFTFT&item=xxxx&level=1%2C2%2C3&tags=&fixable=&bbox=-50.4343056678772%2C-21.215320285005113%2C-50.42581915855407%2C-21.211369556117056)

**Comment by WK-GiHu** [comment]
Hi,
if I understand aright, the query (analyser_osmosis_powerline.py) does not considered 'merged nodes' .
The result of the query holds all 'ending lines', also if those will ended on 'merged node'.
Therefore i assume, most or even all will be 'False Positives'.

BTW: The line 171525032 needs a ending power=tower and probably location:transition' = 'yes'.

**Comment by jocelynj** [comment]
Yes, I'm not really sure how this query handle nodes that are on multiple power line, and I agree that it shouldn't detect the reported case as an error.

**Comment by WK-GiHu** [comment]
Is there a way to suspend the 'analyzer' # 7040 class 2 and class 6 until corrected? 
Furthermore, each # 7040 class 2 and class 6 should to be removed from the 'error' Database. 

Which leads me to the question: 
Is there a recommended course of actions if 'False positive' got recognized?
