### ISSUE TITLE
Allow "bis" and "ter" in Switzerland housenumber checker

### ISSUE THREAD

**Issue by imagoiq** [osm-fr/osmose-backend#1455]
Hi,

I notice that the [regex ](https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Housenumber.py#L54-L57) used to valid housenumber in Switzerland doesn't allow the suffix "bis" and "ter" (used in the French part the same way as in France).

I've reported the issue in https://github.com/ltog/osmi-addresses/issues/93 as it's the source of the regex.

Example of an issue in Osmose: https://osmose.openstreetmap.fr/en/issue/01d225f2-91ec-4cde-5529-04ccfeb9b077

**Comment by frodrigo** [comment]
Seems reasonable.

https://osmose.openstreetmap.fr/en/issues/open?item=2060&class=10&country=swit%2a
