### ISSUE TITLE
Individual items of playground=* and area=

### ISSUE THREAD

**Issue by imagoiq** [osm-fr/osmose-backend#1457]
Hi,

I've notice that individual installations inside a playground are flagged as `Untagged area object` when they are tagged with area=yes.

Here is a good example: https://osmose.openstreetmap.fr/en/issue/e48ceb6f-f1eb-7410-1311-f84189b202ca

If you look at the imagery, you can see that the installations inside this particular playground have for each one a different surface (not tagged as I'm not exactly sure what it is from imagery). 

According to the wiki, almost all kind of installations may be tagged as an area, it appears as well that there is no main tag: https://wiki.openstreetmap.org/wiki/Key:playground

I'm not entirely sure of my analysis, can you confirm that it is correct? (I can make a pull request afterwards). Perhaps, the area around the playground is not included within the installations?

**Comment by frodrigo** [comment]
One of this tags is expected inthe check
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Area.py#L30
As `playground` is not ok alone.

**Comment by imagoiq** [comment]
From what we can read on the wiki, it seems ok.

This is what I understand from the wiki:
![Artboard-1](https://user-images.githubusercontent.com/12294151/169859264-ead869f2-1e6f-4c5a-b354-8f8673ef5d2a.jpg)

On the left side of [https://wiki.openstreetmap.org/wiki/Key:playground](https://wiki.openstreetmap.org/wiki/Key:playground), it's clearly saying: "[use] [leisure](https://wiki.openstreetmap.org/wiki/Key:leisure)=[playground](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dplayground) for the area around the devices".

In ID, it has a mixed interpretation:

![Screenshot 2022-05-23 at 17-52-34 OpenStreetMap](https://user-images.githubusercontent.com/12294151/169859938-2347dd60-443e-48da-8325-9eaf60cee455.jpg)

You can add a "seesaw" has a single point, and it only adds the key `playground=seesaw`. But it doesn't allow you to add it with an area, as opposed to the wiki:

![Screenshot 2022-05-23 at 17-52-25 OpenStreetMap](https://user-images.githubusercontent.com/12294151/169859925-8c7a49e6-bd57-472e-8f53-983e8634d9cd.jpg)

![image](https://user-images.githubusercontent.com/12294151/169860253-69648b8f-822a-43da-ac77-74b8bf4dbdaf.png)

So, I'm a bit lost.

**Comment by Famlam** [comment]
I would agree with imagoiq that it seems to be correct to tag these items without another main key (and hence made PR #1464 to fix it)

**Comment by frodrigo** [comment]
Yes, I am agree too.
Merged. But not deployed, yet.
