### ISSUE TITLE
Motorway refs in Belgium

### ISSUE THREAD

**Issue by bibi6** [osm-fr/osmose-backend#146]
Hello, Bonjour,

Belgian highways are now signalled by Osmose as they are missing a ref. But they usually use the European number as the usual ref, and convented to tag the way as explained here:
http://wiki.openstreetmap.org/wiki/WikiProject_Belgium/Conventions/Highways#European_E-numbers
As such, Osmose should check nat_ref too.

**Comment by WK-GiHu** [comment]
Hi,
I understand your problem, but it can not check without error number. 
Please click the 'E' in the Marker message box and send this link.

**Comment by bibi6** [comment]
This, for instance:
http://osmose.openstreetmap.fr/fr/error/8256629075

Actually, all (or nearly all) motorways are pinned by lots of markers of this kind in Osmose!

**Comment by WK-GiHu** [comment]
The displayed problem concerns with the relation route=road A16. 
It has nothing to do with ref=*. 
Same problem as 'Issue' # 122 and probably 'false positives'. 
Read Issue # 122 to get more info.

You can wait [@cquest](https://github.com/cquest)  jump in or
open an issue at 'https://github.com/cquest/osmose-scripts'. 
Involve yourself on osm-fr/osmosis_backend Issue # 122.

Recommendation for Issue title: 
Marker.item # 7170 on almost all Belgian motorways.

**Comment by jocelynj** [comment]
Is this error still present ?
If it is still present, can you provide a permalink to the map ?

**Comment by bibi6** [comment]
It is.

Here is a permalink:
http://osmose.openstreetmap.fr/fr/map/?#zoom=10&lat=50.6207&lon=3.414&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=7170&level=1%2C2%2C3&tags=&fixable=

I also noted a shift between the map and where Osmose expects the roads, in the Charleroi region - see http://osmose.openstreetmap.fr/fr/map/?#zoom=12&lat=50.447&lon=4.465&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=7170&level=1%2C2%2C3&tags=&fixable= (but I think this is another issue).

**Comment by frodrigo** [comment]
It is absolutly not linked to Belgium, it's a French specific analysis that exceed widely to border countries:
http://osmose.openstreetmap.fr/fr/map/?#zoom=7&lat=49.827&lon=5.48&overlays=FFFFFFFFFFFFFFFFFFFTF&item=7170&level=1%2C2%2C3

@cquest: please, can you clip the result of your analyse to France only.

**Comment by bibi6** [comment]
Well, I have to say that, except for the two points I mentioned, plus the point that the analyzer sometimes proposes a ref like Dxxx instead of Nxxx, it works pretty well in Belgium. So I'd suggest either make the clip, or adapt it a bit for Belgian ways ;) 

However, I don't know about what should be done for other neighbouring countries.

**Comment by cquest** [comment]
The problem does not lies in the analysis code itself, but on the reference data we're using.
The dataset is coming from IGN (France) and may not be up to date outside of France.
I have no way to sort the bad data from the good one...
Do you prefer to have some false positive or no analysis at all outside of France ?

**Comment by bibi6** [comment]
The problem is not about how up-tp-date the data is (it looks like it is okay), but about the way it is analyzed in Belgium... as said, the analyzer should check about a "nat_ref" tag, which contains the national reference.

If you can do that, then (as far as I'm concerned) you can let the analyzer do its job in Belgium.

**Comment by frodrigo** [comment]
The fix is in place ? 

http://osmose.openstreetmap.fr/fr/errors/?source=14708&item=7170&class=2
http://osmose.openstreetmap.fr/fr/errors/graph.png?source=14708&item=7170&class=2
http://osmose.openstreetmap.fr/fr/map/#source=14708&item=7170&class=2&zoom=9&lat=50.41&lon=4.64&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFTF

**Comment by cquest** [comment]
Yes, but we have another problem... geometry are offset a lot outside of France... which makes the analysis considering the road is missing.

I'll change it to avoid roads outside of french territory.

**Comment by frodrigo** [comment]
Well done. 50k osmose issues removed.
