### ISSUE TITLE
Add a check if the surface does not match the tracktype from highway=track

### ISSUE THREAD

**Issue by mcliquid** [osm-fr/osmose-backend#1468]
Driven by this [discussion](https://github.com/streetcomplete/StreetComplete/discussions/4063) from StreetComplete, I would like to introduce my idea to the Osmose Analyzer.

**Short**: I noticed that quite often a `surface=*` is mapped to a `highway=track` which does not match the existing `tracktype=*` (or the other way around). In these cases Osmose could give a information / Error. The goal should be that both entries correspond to reality and match each other.

**For example:**
- Warn if there's `surface=asphalt` and `tracktype=grade4`
- Warn if there's `surface=gravel` and `tracktype=grade1`
- Warn if there's `tracktype=grade1` and `surface=gravel`

Here is a rough list of cases where this error should be triggered:
`highway = track AND surface = unpaved|gravel|fine_gravel|compacted|pebblestone|dirt|earth|grass|grass_paver|mud|sand|woodchips|snow|ice|salt|rock|ground AND tracktype=grade1`

`highway = track AND surface = paved|asphalt|asphalt:lanes|chipseal|concrete|concrete:lanes|concrete:plates|paving_stones|sett|unhewn_cobblestone|cobblestone|cobblestone:flattened|metal|wood|stepping_stones AND tracktype = grade2|grade3|grade4|grade5`

**Comment by Famlam** [comment]
Like this one?
https://osmose.openstreetmap.fr/nl/map/#item=9001&zoom=17&lat=45.820472&lon=4.345231&level=3&tags=&fixable=&issue_uuid=0ce247e1-6c65-338c-f003-40cec3fc5a80

**Comment by Famlam** [comment]
> No, manual. Ping here when is done.

Ping ;) it was merged in JOSM

**Comment by frodrigo** [comment]
> > No, manual. Ping here when is done.
> 
> Ping ;) it was merged in JOSM

Code update done. Will be shipped on next deploy.

**Comment by Famlam** [comment]
I think this issue can be closed as fixed?

**Comment by frodrigo** [comment]
Yes deployed.
