### ISSUE TITLE
improvement of traffic_signals nearby

### ISSUE THREAD

**Issue by it4workflow** [osm-fr/osmose-backend#147]
with #133 a check for nearby highway=traffic_signals at crossing=traffic_signals has been introduced.

i think this check only works correctly if crossing=traffic_signals is tagged on a way an the end nodes of this way should tagged with highway=traffic_signals, see http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Traffic_signals_for_pedestrians

at the moment i think [this](http://osmose.openstreetmap.fr/de/map/#zoom=17&lat=50.5228038&lon=10.8827923&item=2090&level=2) is false-positive

**Comment by it4workflow** [comment]
and please note about http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#How_to_map:
`It is not a representation of a particular device. `

**Comment by frodrigo** [comment]
@grischard what do think of this ?

**Comment by grischard** [comment]
I do not think that the error you've linked to is a false positive. It's a pedestrian crossing where pedestrians are controlled by a light, but what's the situation for the road traffic? Will it affect me if I'm turning left into the dentist's parking? If I'm giving directions, should I turn left before or after the light?

It is unfortunate that `highway=traffic_signal` and `highway=crossing` both occupy the `highway` key. It would be good if we could clearly map such a simple, middle of the way pedestrian crossing with one node, but I don't see how we unambiguously could.

The `highway=traffic_signal` nodes aren't necessarily at the end of the way - they probably aren't more often than they are.

I've edited the area you've linked to, adding traffic lights for the road traffic around that pedestrian crossing, and hope that you agree that this is an unambiguous way of representing this pedestrian crossing.

**Comment by it4workflow** [comment]
>  It would be good if we could clearly map such a simple, middle of the way pedestrian crossing with one node, but I don't see how we unambiguously could.

+1

> I've edited the area you've linked to, adding traffic lights for the road traffic around that pedestrian crossing, and hope that you agree that this is an unambiguous way of representing this pedestrian crossing.

Surely, this could be a way.

> Will it affect me if I'm turning left into the dentist's parking? If I'm giving directions, should I turn left before or after the light?

Here a [mapillary](https://www.mapillary.com/app/?focus=photo&pKey=1TeTtetao7DMoX8cDGXtjA) picture for this (simple crossing.

**Comment by it4workflow** [comment]
> ...but what's the situation for the road traffic

hmm, okay, good question. i think it has now affect to the road traffic, because it is green 99,8% of the day. it's only red, when some school kids went off school and push the request button.

and i have to investigate this, but i think the traffic_signal (green light for road traffic) is only active between 7am-6pm.

so my real (first) intention was the view of the pedestrian crossing and that this is a controlled one.

**Comment by jojo4u** [comment]
Just use highway=traffic_signals + crossing=traffic_signals.

It's already done on 21% of all crossing=traffic_signals (http://taginfo.openstreetmap.org/tags/crossing=traffic_signals#combinations)

It's also supported by JOSM default style with different icons.

**Comment by frodrigo** [comment]
So nothing to do in Osmose-QA, If I'm wrong, please, reopen.
