### ISSUE TITLE
Area elements with tag cemetery=sector shown as Untagged area object

### ISSUE THREAD

**Issue by carlosarc87** [osm-fr/osmose-backend#1475]
item 3200
class 32002

https://wiki.openstreetmap.org/wiki/Tag:cemetery=sector
In the wiki you can read that is used in nodes and areas, not in ways.
It seems that the tag area=yes is needed because without the tag the element is taken as a way.

Example of an issue: http://osmose.openstreetmap.fr/en/issue/ab9bae4e-913f-1ed1-74c0-c4973e5ca372

Regards

**Comment by carlosarc87** [comment]
As you say I think it should work in the opposite way, but it does not.
iD and JOSM do not show the sector as an area. Could it be a problem from the editor?
I am not sure about removing the tag area=yes and let it be as if it was an area.

**Comment by frodrigo** [comment]
It was already the question to remove this check from Osmose.

You can let the data as is.

**Comment by carlosarc87** [comment]
I will let the tag area=yes, but it seems like mapping for the renderer. I hope it will be fixed.
I think this issue can be closed if there is no other question.
