### ISSUE TITLE
Typo in tag sides -> side in element advertising=billboard

### ISSUE THREAD

**Issue by carlosarc87** [osm-fr/osmose-backend#1476]
item 3150
class 1

Example: http://osmose.openstreetmap.fr/en/issue/97719283-de56-9a60-70e8-62150e9d1866

https://wiki.openstreetmap.org/wiki/Tag:advertising=billboard
https://wiki.openstreetmap.org/wiki/Key:sides

The tag sides is correct, so there is no typo here.

Regards

**Comment by frodrigo** [comment]
The check try to fix `side` to `sides`.
Should be blacklisted.
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_tag_typo.py#L51

**Comment by sekerob** [comment]
This has been a longer going issue, Change it from side to sides in response to the QA flag and it gets flagged again next round it should be changed from sides to side.

Similar in wizards Api-ip when IP is correct and Agip-eni when Eni is correct (in the ID Editor wizard), Cant win so hitting the false-positive button each time a fuel station gets updated with these brands, a very large number in Italy.

**Comment by Famlam** [comment]
Do you have an example issue in Osmose that still exists? @sekerob

**Comment by sekerob** [comment]
Took some recollecting effort, it's keepright who whines about a typo of 'sides', wants to make it 'side'. Do that and (think) Osmose flags that side should be sides. The wiki for totems spells it out as 'sides', so i stick to that, https://wiki.openstreetmap.org/wiki/Tag:advertising=totem . Giving it a false positive tag ends in an orange cloud over the item in keepright, never going away. Did about 5 in this place https://keepright.at/report_map.php?zoom=14&lat=42.46383&lon=14.21569 at Megalo, Chieti Scalo

Hope this makes you the wiser.

NB The ID Editor drop down list offers both side and sides, so what's a simple mapper to do.... move on, stop mapping totems which mostly are 2-3- some 4 sides, and the ones that are round.... 1 side.

ciao

**Comment by Famlam** [comment]
But can you give an example where Osmose still suggests to change side to sides or the other way around? (Keepright and ID are independent from Osmose as far as I know)

**Comment by sekerob** [comment]
@Famlam , not presently, but changing sides to side (pre code update) on any of these sampled (8 in fact at that mall) would certainly recreate the flagging in a day, a week, one problem or the other does not seem to be analysed every day. Keepright certainly seems not the refresh more frequent than every 14 days or so.

Independent.... they better start talking to each other and as this is frankly cavalli,

**Comment by sekerob** [comment]
Not going to be opening a new issue as it still seems the problem continues of values suddenly becoming invalid in the validation view of Osmose

1) values of no_parking and no_stopping on parking keys are now being declared invalid resulting in brown pin carpet bombing
2) ref:mise values, required on Italian fuel station are all getting the absent or invalid flag. Purple carpet bombing
3) StreetComplete asks for surface values on tracks where they mostly also have a grading type value. All declared suspicious, combinations. NO, different programs test different criteria. Anotherbrown pins carpet bomb.

The sum total, complete drown out in my Osmose issue list of the problems that actually matter, map looking ugly, a little mouse script starting to work it's way thru: Hit the X with a delay in the loop as the issue page list is slow to update.

Maybe the horse called Osmose should be walked to it's stable, door closed and cured outside of competition until the PTF's can be replaced with root cause PFs..

PS I map a lot so I get bunches of them, Small mappers just click, but sure as heck, not going to test e.g. the ref:mise roll has an actual expired value in it. All send to the false positive waste bin.

**Comment by Famlam** [comment]
Ok, first this is highly off-topic. But I'll answer them here anyway:

- Regarding the parking keys: earlier this year a new syntax was [approved by voting](https://wiki.openstreetmap.org/w/index.php?oldid=2289049), where no_parking and no_stopping were moved from parking:lane:* to parking:condition:*. As of yesterday, Osmose starts to warn people when the old syntax is used. It seems the region you are referring to could use an update if it's colored now ;). If you find an actual issue, please let us know.

- Regarding ref:mise, @fansanelli perhaps you can have a look? http://osmose.openstreetmap.fr/nl/issue/020a9361-cb39-3d8e-7f66-d0f668833de6 `ref:mise=4339` is present in the csv but seems to be flagged as invalid/missing. If it's a real issue, probably a new issue should be opened as this is very off-topic to this issue report.

- Regarding Streetcomplete issues vs. Osmose: please point us to an example where Osmose is wrong. In a new issue, preferably, and definitely with an example.

Also, don't mark everything as false positive unless it's really a false positive. You can just disable certain checks and only see whichever issues you want to see, using for example the checkboxes on the left side of the screen. For other people, the things you consider uninteresting are interesting. Maybe @frodrigo can implement a hour limit of 100 false positive markings per user to prevent such scripts if needed?

**Comment by frodrigo** [comment]
Late, but I post mine too.

> values of no_parking and no_stopping on parking keys are now being declared invalid resulting in brown pin carpet bombing

It linked to this https://github.com/osm-fr/osmose-backend/pull/1511 it follow changes on the Wiki.

> Not going to be opening a new issue

So, I will do for you.

> ref:mise values, required on Italian fuel station are all getting the absent or invalid flag. Purple carpet bombing

#1515

> StreetComplete asks for surface values on tracks where they mostly also have a grading type value. All declared suspicious, combinations.

Do you have a sample osmose reported issue about this ? (as new issue, please)

> NO, different programs test different criteria. Anotherbrown pins carpet bomb.

OSM folksonomy is hard to deal with, especially with the large number of checks run by Osmose (more than 1000).

Osmose sometime may be slow, or the (small) team not very reactive. But please, keep in mind it runs on donated resources by volunteer in their spare time.

Please open new issue when required, be patient on resolution and help if you have the abilities.
