### ISSUE TITLE
False positive: parking:lane:[side]=no + parking:condition:[side]=no_stopping

### ISSUE THREAD

**Issue by vincentvd1** [osm-fr/osmose-backend#1479]
Osmose gives a false positive when a highway is tagged with both `parking:lane:[side]no + parking:condition:[side]=no_stopping`.

No parking lane does not equal no parking. Depending on the situation (for example in the Netherlands), the absence of a parking lane does not prohibit you to stop. In the Netherlands, if a cycleway is present, you are not allowed to stop but on other roads it is for example allowed to stop to let out a passenger but it is not allowed to park, while still not saying anything about the presence of parking lanes.  

Link to a location: http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=52.267875&lon=6.150364&item=xxxx&level=1,2,3&tags=&fixable=&issue_uuid=6d062189-672c-b3da-2438-d8ea93f08b32
item details: http://osmose.openstreetmap.fr/en/issue/6d062189-672c-b3da-2438-d8ea93f08b32

**Comment by frodrigo** [comment]
Done
