### ISSUE TITLE
Some railway=* and highway=* combinations are okay

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#149]
* [railway=razed](http://osmose.openstreetmap.fr/en/error/8260584478)
* [railway=construction](http://osmose.openstreetmap.fr/en/error/8260582394)
* and railway=abandoned

can be combined with highway=* and be correct

**Comment by jocelynj** [comment]
Do you have the item number or a permalink to an error ? It will make it easier to find the incorrect analyser.

**Comment by grischard** [comment]
Ah, sorry the links in my original ticket don't work anymore.

They're all in 4030:

[railway=proposed](http://osmose.openstreetmap.fr/en/error/8316535865)
[railway=razed](http://osmose.openstreetmap.fr/en/error/8316538493)
[railway=construction](http://osmose.openstreetmap.fr/en/error/8316536678)

I can't find one for railway=abandoned right now.

**Comment by jocelynj** [comment]
Thanks. Error number are changing on every update, so they are not stable.
Here is a permalink to find this errors again later: [map](http://osmose.openstreetmap.fr/en/map/?lat=49.6131204&lon=6.1204666#zoom=17&lat=49.613125&lon=6.12054&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=4030&level=1%2C2%2C3&tags=&fixable=)
