### ISSUE TITLE
False positive for item 2060, class 19 in poland_slaskie

### ISSUE THREAD

**Issue by polish96** [osm-fr/osmose-backend#1490]
Item 2060
Class 19

Hi, while solving my problems in Poland I found that some problems persist even if the street name matches the address.

I am sharing links to examples:

https://osmose.openstreetmap.fr/pl/issue/ea87482d-dedd-6d38-46b1-d37b96217de8
https://osmose.openstreetmap.fr/pl/issue/ad7cc9cc-4fed-00f0-54ec-9d44e24bcf90
https://osmose.openstreetmap.fr/pl/issue/13a163fe-4612-f85e-05c4-74c65d29feec
https://osmose.openstreetmap.fr/pl/issue/0dbda2b3-60ac-0026-7a0a-8c8710775dd0
https://osmose.openstreetmap.fr/pl/issue/b732afc7-8400-e8f5-cc9e-503c32121b40
https://osmose.openstreetmap.fr/pl/issue/947b810e-cf9d-8412-48e6-f2feec5310a1

Most of the problems are with my address imports.

**Comment by polish96** [comment]
Not solved.

**Comment by polish96** [comment]
The problem persist even if the street name matches the address. I've marked a few thousand items as false positives but new ones pop up without being a mistake.

e.g.:

1. https://osmose.openstreetmap.fr/pl/map/#zoom=18&lat=50.127793&lon=19.114381&item=2060&level=1%2C2&issue_uuid=d7f75e73-fcdb-b850-39df-20ebff9d4938
2. https://osmose.openstreetmap.fr/pl/map/#zoom=18&lat=50.162264&lon=18.900722&item=2060&level=1%2C2&issue_uuid=d7f75e73-fcdb-b850-39df-20ebff9d4938
3. https://osmose.openstreetmap.fr/pl/map/#zoom=18&lat=50.273632&lon=19.021963&item=2060&level=1%2C2&issue_uuid=d7f75e73-fcdb-b850-39df-20ebff9d4938

**Comment by frodrigo** [comment]
There is possible corruption of OSM extract on Osmose backend for this same area #1494.

**Comment by frodrigo** [comment]
Reseting the copie of the extract clear the issues.
