### ISSUE TITLE
collection_times together with amenity=recycling

### ISSUE THREAD

**Issue by carlosarc87** [osm-fr/osmose-backend#1491]
_suspicious tag combination
collection_times together with amenity=recycling. Probably opening_hours is meant._

**item**: 9001
**class**: 9001002

**Key:collection_times** in OSM Wiki: https://wiki.openstreetmap.org/wiki/Key:collection_times
"The collection times of a [post box](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_box), [recycling container](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling) or other fixed location drop-off facility. The syntax is the same as for [opening hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours), including the hyphen because there are post boxes which are emptied several (undefined) times or one (undefined) time in a certain time frame."

Taginfo: https://taginfo.openstreetmap.org/keys/collection_times

Example: http://osmose.openstreetmap.fr/en/issue/75511e41-8729-8e29-dde5-4b66519b755b

**Comment by frodrigo** [comment]
This report is from JOSM validator.
Please report this issue to JOSM

https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss#L865

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
The osmose example link is no longer valid. Could you link the osm obect?

**Comment by carlosarc87** [comment]
> This report is from JOSM validator. Please report this issue to JOSM
> 
> https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss#L865
> 
> cc @Klumbumbus

This is another example
http://osmose.openstreetmap.fr/es/issue/d901d183-3029-cc13-5c4c-e35d933acdb1

**Comment by carlosarc87** [comment]
> The osmose example link is no longer valid. Could you link the osm obect?

http://osmose.openstreetmap.fr/es/issue/d901d183-3029-cc13-5c4c-e35d933acdb1

**Comment by carlosarc87** [comment]
I have created a ticket to JOSM https://josm.openstreetmap.de/ticket/22295
I think this issue can be closed.

Thanks for reply. Regards

**Comment by Klumbumbus** [comment]
Validator test adjusted in https://josm.openstreetmap.de/changeset/18546/josm
