### ISSUE TITLE
analyser_merge_parking_FR_BNLS.py

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#1492]
Hello,

Multiple false positives with the analysis this morning. It seems that the analysis used is very broad.

The database at https://transport.data.gouv.fr/datasets/base-nationale-des-lieux-de-stationnement (bnls.csv file) seems to be consistent with the reality of *off-street parking*.

And the analysis points to amenity=parking, certainly not along lanes, but not affected by the online BNLS either.

HTH

**Comment by frodrigo** [comment]
Something is broken since 4th July.

https://osmose.openstreetmap.fr/en/issues/graph.png?item=8131&class=53&start_date=2022-07

**Comment by deuzeffe** [comment]
Indeed... To unplug temporarly the analysis ? Or to replace the DB used by bnls.cvs ?

**Comment by frodrigo** [comment]
The issue is raised now, but it is linked to a change made last month.

The computation is made in 4326... so the distance is 200 degrees !

**Comment by cquest** [comment]
This explains that :(
