### ISSUE TITLE
Amenities ignored by analysis north of France

### ISSUE THREAD

**Issue by ThmVlm** [osm-fr/osmose-backend#1493]
Some amenities located in the very north of France (above lat 50.82) are not spotted by the analysis whereas they are well located in osm : 
- schools : http://osmose.openstreetmap.fr/fr/map/#zoom=10&lat=50.8514&lon=2.477&item=8030&level=1%2C2%2C3
- stations : http://osmose.openstreetmap.fr/fr/map/#zoom=10&lat=50.8514&lon=2.477&item=8050&level=1%2C2%2C3
- police : http://osmose.openstreetmap.fr/fr/map/#zoom=10&lat=50.8514&lon=2.477&item=8190&level=1%2C2%2C3
- gas stations : http://osmose.openstreetmap.fr/fr/map/#zoom=10&lat=50.8679&lon=2.419&item=8200&level=1%2C2%2C3

ThmVlm

**Comment by frodrigo** [comment]
Please, can you explain what is wrong for you, and what are you expected ?

**Comment by ThmVlm** [comment]
All this amenities in the very north of France are listed in osmose as missing, whereas they all already are in osm. 
It seems that the analysis ignores the amenities above latitude 50.82

**Comment by frodrigo** [comment]
Ok. I see your point.

It looks to be the case for various and unrelated data source.

But it is not the case for all data sources.

**Comment by frodrigo** [comment]
I do not see the same issue on local run.

@jocelynj do you think we can try to delete the exact from the backend ?
- france_nord_pas_de_calais_nord
- france_nord_pas_de_calais_pas_de_calais

**Comment by frodrigo** [comment]
Problem is linked to special backend `france_local_db`.

**Comment by frodrigo** [comment]
Fixed.
