### ISSUE TITLE
False positive: item 1170 (multipolygon), class 4, poland_swietokrzyskie + poland_slaskie

### ISSUE THREAD

**Issue by kartonage** [osm-fr/osmose-backend#1494]
Hej there,

I have noticed quite a bit of false positve entries for item 1170, class 4 in data of [poland_slaskie](https://osmose.openstreetmap.fr/en/issues/open?country=poland_slaskie&item=1170&class=4) and [poland_swietokrzyskie](https://osmose.openstreetmap.fr/en/issues/open?country=poland_swietokrzyskie&item=1170&class=4)

Seemingly new or modified ways are reported as errors. I marked a bunch (a few thousand) as false positives but new ones keep popping up without being an error. I have not noticed this with all other regions available, although there have been a few false postives recently here and there. Not as much as with these two though.

Swietokryskie map: https://osmose.openstreetmap.fr/en/map/#source=8698&item=1170&class=4&zoom=7&lat=50.948&lon=23.109&level=1
Slaskie map: https://osmose.openstreetmap.fr/en/map/#source=8661&item=1170&class=4&zoom=7&lat=50.948&lon=21.467&level=1

e.g.:
https://osmose.openstreetmap.fr/en/issue/2c49549a-aee4-30d7-b00e-873acd84a174
https://osmose.openstreetmap.fr/en/issue/3e943d86-e6df-319c-f02f-ecbe2093c161

Any issues with these particular regions?

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/en/issues/graph.png?country=poland_slaskie&item=1170&class=4&start_date=2022
https://osmose.openstreetmap.fr/en/issues/graph.png?country=poland_swietokrzyskie&item=1170&class=4&start_date=2022

Only those tow look to have issue
https://osmose.openstreetmap.fr/en/issues/open?item=1170&class=4

**Comment by frodrigo** [comment]
I run it locally and there is no the problem.

@jocelynj extract may be corrupted on the backend. Can you try to clean it, please?

**Comment by frodrigo** [comment]
Ok, now it is to 0 for the two area.

Closing. But report if issues pop again.
