### ISSUE TITLE
Bad geocoding

### ISSUE THREAD

**Issue by bibi6** [osm-fr/osmose-backend#150]
Hello, Bonjour,

http://osmose.openstreetmap.fr/fr/error/8312401752 signals that a townhall should be integrated. Problem is: it locates it in the neighbouring city...

Ceci signale une mairie à intégrer... mais le marqueur est dans le village voisin!

**Comment by frodrigo** [comment]
The location in Osmose is provoded as is from the data source :
https://www.data.gouv.fr/fr/datasets/service-public-fr-annuaire-de-l-administration-base-de-donnees-locales/

And I'm agree, it's of bad quality.
