### ISSUE TITLE
Broken tests due to HTTP code change

### ISSUE THREAD

**Issue by flacombe** [osm-fr/osmose-backend#1501]
Currently tests are broken due to HTTP code change for URL http://osmose.openstreetmap.fr/static/404-osmose-downloader-test-sdkhfqksf

Expected to get HTTP 404 but got HTTP 200.

Blocks #1495 #1500

**Comment by frodrigo** [comment]
Where this come from ?

**Comment by flacombe** [comment]
Right here: https://github.com/osm-fr/osmose-backend/blob/master/modules/downloader.py#L188

**Comment by frodrigo** [comment]
Fixed.
