### ISSUE TITLE
Exclude wikidata=* tag from "Similar values" check

### ISSUE THREAD

**Issue by ivanbranco** [osm-fr/osmose-backend#1504]
item 3060
class 30601
Detail: http://osmose.openstreetmap.fr/it/issue/194df08a-4973-76a3-1148-6f8c47b7cd52

I think wikidata=* tag should be excluded from the "Similar values" check. Of course those values are similar, the syntax is always "QXXXXX". In the example provided there are 4 values pointing 4 different persons.

**Comment by frodrigo** [comment]
Done.
