### ISSUE TITLE
False positive for parking:condition:[side] without parking:lane:[side] value

### ISSUE THREAD

**Issue by rskedgell** [osm-fr/osmose-backend#1506]
The tests in Highway_Parking_Lane.py reflect the situation before Proposed features/Parking lane conditionals (https://wiki.openstreetmap.org/w/index.php?oldid=2289049) was approved on 2022-01-21. 

This moved the values no_parking and no_stopping for parking:lane=* to parking:condition=*, so a false positive if raised for e.g. parking:condition:*=no_parking|no_stopping, but not for the now deprecated parking:lane:*=no_parking|no_stopping.

**Comment by frodrigo** [comment]
Ok, should be fixed here
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Parking_Lane.py

**Comment by frodrigo** [comment]
Done.

**Comment by blef00fr** [comment]
Osmose continues to report a warning when parking:condition:[side] is used without parking:lane:[side] 

According to the wiki at Key:parking:condition: "Both can be used independently of each other, they do not necessarily require the other "

So, what about this warning?

**Comment by Discostu36** [comment]
Issue should be re-opened, I still get this warning.

**Comment by Famlam** [comment]
Unlike the parking:condition (which often requires ground surveys), parking:lane can mostly be deduced from areal imagery. 
So I personally, when I fixed the bug in the initial post, kept this check in despite being an "allowed" situation. It's a good suggestion for things that could be improved easily. (Just like for instance `signals should have a railway:signal:direction=* tag`, `Unfinished power minor line`, `Unmapped surveillance camera`, `Operator can be completed with operator:wikidata` and several other errors).

**Comment by frodrigo** [comment]
Can we close this one now?

**Comment by blef00fr** [comment]
As far as my comment is concerned, I think so.
