### ISSUE TITLE
Invalid issues: Wikidata item does not exist

### ISSUE THREAD

**Issue by praszuk** [osm-fr/osmose-backend#1510]
A lot of invalid wikidata issues appeared today.
Probably all OSM objects with wikidata tags affected (at least in _poland_mazowieckie_ region).

```
Wikidata item does not exist
The linked Wikidata item <id> does not exists on Wikidata
```
Details:
source: 427751
item: 3031
class: 2

[Example view](https://osmose.openstreetmap.fr/pl/map/#item=3031&zoom=14&lat=52.192&lon=20.96882&level=1%2C2%2C3&tags=&fixable=)

[Example marker](https://osmose.openstreetmap.fr/pl/issue/b679ee82-6fd3-2a8a-b6df-d89d4bcadc2e)

[The URL for this item](https://osmose.openstreetmap.fr/pl/issues/open?item=3031) returns `TypeError: Failed to fetch`.

**Comment by deuzeffe** [comment]
Despite the fix, the issues are still there.

@frodrigo, depending on osmose analysis frequency or the bug is not actually fixed ?

**Comment by frodrigo** [comment]
Last update 2 days ago. I think it is not fixed, yet
http://osmose.openstreetmap.fr/fr/control/update_matrix?remote=46.4.22.142

**Comment by jarielmer** [comment]
With the upload 2 days ago there should have been 1617 such errors reported. Is it correct for me to assume that all in osmose existing and not resent errors will be deleted by the osmose-backend at the time the new report arrives?

**Comment by frodrigo** [comment]
It look like only a partial fix was done

https://osmose.openstreetmap.fr/en/issues/graph.png?item=3031&start_date=2022-08&class=2

https://osmose.openstreetmap.fr/en/issues/open?item=3031&class=2

Is the new dump complete ?

**Comment by jarielmer** [comment]
Just ran a new check. From what I can see it is complete. And there should only be around 1.5k such errors.

For example for `germany_berlin` we just sent an update with 0 class 2 errors. But osmose still shows [38837](https://osmose.openstreetmap.fr/en/issues/open?source=427584&item=3031&class=2).

Could the problem be in the reporting we do. If no error is found for the region we also don't send the class description. Do we need to send the class description even if there are no errors for this class?

**Comment by frodrigo** [comment]
> Could the problem be in the reporting we do. If no error is found for the region we also don't send the class description. Do we need to send the class description even if there are no errors for this class?
> 
> This is a very small change in our code. Just implemented it and will run another check. In 1.5h we should have new reports.

Yes, you should report it as empty to let Osmose frontend know about it.

**Comment by jarielmer** [comment]
Reports are sent with all class descriptions, but the errors are still on osmose. Is there a delay on the side of osmose? If not, has someone any other ideas?

This is the report for `germany_berlin` as an example: [germany_berlin.xml.zip](https://github.com/osm-fr/osmose-backend/files/9320834/germany_berlin.xml.zip)

**Comment by frodrigo** [comment]
It is good now. It is only cache on web browser side.
