### ISSUE TITLE
False positive for item 2060, class 19 in poland_slaskie

### ISSUE THREAD

**Issue by polish96** [osm-fr/osmose-backend#1513]
Hi,

I have noticed a lot of false positve for item 2060, class 19 in region poland_slaskie. The problem persist even if the street name matches the address.

I've marked a few thousand items as false positives but new ones pop up without being a mistake.

e.g.:

- https://osmose.openstreetmap.fr/pl/map/#zoom=18&lat=50.127793&lon=19.114381&item=2060&level=1%2C2&issue_uuid=d7f75e73-fcdb-b850-39df-20ebff9d4938
- https://osmose.openstreetmap.fr/pl/map/#zoom=18&lat=50.162264&lon=18.900722&item=2060&level=1%2C2&issue_uuid=d7f75e73-fcdb-b850-39df-20ebff9d4938
- https://osmose.openstreetmap.fr/pl/map/#zoom=18&lat=50.273632&lon=19.021963&item=2060&level=1%2C2&issue_uuid=d7f75e73-fcdb-b850-39df-20ebff9d4938

**Comment by frodrigo** [comment]
Same as #1490
