### ISSUE TITLE
ref:msal values, required on Italian pharmacies and para-farmacies (drug stores) are getting absent or invalid flag, falsely.

### ISSUE THREAD

**Issue by sekerob** [osm-fr/osmose-backend#1517]
Same as the ref:mise issue 1515, still more trickling thru, for no reason that makes sense, ref:msal code is dismissed for same cause

Sample: https://osmose.openstreetmap.fr/en/map/#item=7150&zoom=16&lat=42.44444&lon=13.82416&level=3&tags=&fixable=

The Ministry of health (Ministero della Salute), extract from some days ago), the Turno site (off hours service website for pharmacies) both say that ref:mise 10827 is valid. Spoke to the pharmacist yesterday while surveying Farindola, the good man is truly alive, able to climb those long steps leading up to his place.

PS It seems these multi failings gets kicked soon as any key value is added or changed such as yesterday checking several fuel stations if they have compressed air. Sure enough all 4 have the ref:mise ...

**Comment by frodrigo** [comment]
I do not see the issue pin on the map. Did you remove it ?
It helps to check. Do you have an other one, please ?

It look like there is no global issue with this one
https://osmose.openstreetmap.fr/en/issues/open?item=7150&country=italy%2a
https://osmose.openstreetmap.fr/en/issues/graph.png?item=7150&country=italy%2a

**Comment by sekerob** [comment]
Added some other values for pharmacy 10827 (The steps is a Via per corner sign, not a Salita) so guess in autoreflex hit the ok on the V in the personal list at https://osmose.openstreetmap.fr/en/byuser/SekeRob. Given the change probably this one is going to reappear tomorrow. See no other in the wider area I map in.

**Comment by frodrigo** [comment]
Still seeing nothing. Reopen with details if required.
