### ISSUE TITLE
Item 3080: and the right fix is?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#1522]
Hello,

For a natural=water + water=basin (that **is not** a swimming pool, but a little area in the fields), osmose analysis reports an issue 3080 (for mistagging leisure=swimming_pool as natural=water).

The right panel proposes to fix with:" If it is actually not a swimming pool then you can use e.g. `natural=water` + `water=pond`/`water=basin`." according to the wiki https://wiki.openstreetmap.org/wiki/Tag:water%3Dbasin.
And the pop-up to remove natural et replace it with landuse=reservoir/basin/pond.

So what is the right fix to apply? Maybe a suggestion to add `basin=*` would help?

![Screenshot 2022-08-18 at 13-07-52 Osmose](https://user-images.githubusercontent.com/36087963/185400190-765120ff-5680-49fa-b307-fe9ead743b20.png)

**Comment by frodrigo** [comment]
Strange, the check does not check the object is already correctly tagged. Could produce a lot of false positives.

http://osmose.openstreetmap.fr/en/issues/open?item=3080&class=1

Meanwhile the graphe is nice http://osmose.openstreetmap.fr/en/issues/graph.png?item=3080&class=1

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_natural_swimming-pool.py

**Comment by frodrigo** [comment]
Done. 50% of false positive removed !

**Comment by deuzeffe** [comment]
Fine! I've "lost" about 100 osmose's alerts :) Thx.
