### ISSUE TITLE
Unconnected tertiary roads

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1523]
Discovered this while working on the drive-through check:
item 1210, class 2 says:
https://github.com/osm-fr/osmose-backend/blob/c6c0e8a4598495c3b21c308081dbda92be0d1717/analysers/analyser_osmosis_highway_deadend.py#L230-L231

However, the check only looks for `level < 3` ways https://github.com/osm-fr/osmose-backend/blob/c6c0e8a4598495c3b21c308081dbda92be0d1717/analysers/analyser_osmosis_highway_deadend.py#L50
while `tertiary` roads are `level = 3`:
https://github.com/osm-fr/osmose-backend/blob/d580eb5a833528bbb8e2725771cdcf94f2de3d5e/analysers/Analyser_Osmosis.py#L59-L60

So in order to check for unconnected roads of tertiary level (as the description of the issue says), the check should be `level <= 3`
Not sure if this is intentional or whether it's a mistake; the fix is pretty easy, hence I thought I'll just bring it up.

**Comment by frodrigo** [comment]
The doc was added later than the code.
I think we should better fix the doc.

Meanwhile, the issue number is on a good trending
https://osmose.openstreetmap.fr/en/issues/graph.png?item=1210&class=2
and tertiary may be enabled.

**Comment by Famlam** [comment]
> Meanwhile, the issue number is on a good trending
> https://osmose.openstreetmap.fr/en/issues/graph.png?item=1210&class=2
> and tertiary may be enabled.

I would agree to just enable it, I do fear a bit that the many highway=tertiary connected to highway=construction will flood the map. 
Similar to i.e. https://osmose.openstreetmap.fr/nl/map/#zoom=18&lat=51.579814&lon=7.190047&item=1210&level=1&tags=&fixable=&class=2 (but then for tertiary, which is more common I think)

Your call :). I'm also fine with closing the issue

**Comment by frodrigo** [comment]
A local run should be done before on some area to test it.

> Similar to i.e. https://osmose.openstreetmap.fr/nl/map/#zoom=18&lat=51.579814&lon=7.190047&item=1210&level=1&tags=&fixable=&class=2 (but then for tertiary, which is more common I think)

Than bad mapping anyway. Not in construction part should not be open to traffic.

**Comment by Famlam** [comment]
> Than bad mapping anyway. Not in construction part should not be open to traffic.

I think it's ok if the construction only starts midway the highway, but indeed, https://osmose.openstreetmap.fr/nl/map/#item=1210&zoom=17&lat=52.151048&lon=4.436872&issue_uuid=81190390-7f36-91b1-8964-53373ae67f3f&level=1 would have been a better example, as the part towards the construction works is set to `access=no`. 

However, this isn't necessarily the case for i.e. primary to tertiary, as for example there might be (accessible) street side parking spaces until just before the construction starts. Hypothetical example:
![image](https://user-images.githubusercontent.com/1315520/186507250-c34c2088-bbf8-4eea-8830-22970296eeae.png)

I think if this analyser would be enabled for tertiary, the construction filter should be disabled.

**Comment by frodrigo** [comment]
You suggest to not check for construction way, but allow others to end on a construction way ?

**Comment by Famlam** [comment]
Correct, what I would propose is to allow highways to have a dead-end into a construction way. (That's a large amount of the current reports in my area and seems fully valid tagging to me). However, up to you.

I did a quick test yesterday with level <= 3, didn't give many issues on monaco and jersey; one mysterious issue in belgium_wallonia_german_community (way 93917359, no clue why that's flagged). Haven't ran any big areas though, as it takes so long on my pc 🙈

**Comment by Famlam** [comment]
Ran the analyser with `level <= 3` (rather than `level < 3`) on the following countries; only listing the items of `class=2`:
**San Marino**: no results
**Belgium Wallonia German comm.**: [way 93917359](https://www.openstreetmap.org/way/93917359) _= false positive_
**Jersey**: [way 167438797](https://www.openstreetmap.org/way/167438797) and [way 405695190](https://www.openstreetmap.org/way/405695190) 
**Monaco**: no results
**Switzerland Basel Stadt**: no results
**Sweden Gotland**: [way 67405426](https://www.openstreetmap.org/way/67405426), [way 55408443](https://www.openstreetmap.org/way/55408443), [way 198942515](https://www.openstreetmap.org/way/198942515), [way 50321765](https://www.openstreetmap.org/way/50321765), [way 199683922](https://www.openstreetmap.org/way/199683922), [way 38419234](https://www.openstreetmap.org/way/38419234), [way 199783381](https://www.openstreetmap.org/way/199783381), [way 55400006](https://www.openstreetmap.org/way/55400006) and [way 25800852](https://www.openstreetmap.org/way/25800852) 

As belgium_wallonia_german_community (just 11MB) took 45 minutes to run, I'm hesitating to run bigger areas. I do not understand why the false positive in the Belgium one shows up. 
I'm not sure what's wise with regards to the Sweden one… I'm only used to map in densely populated areas, where tertiary roads are always connected to many smaller roads, but I guess that in such a low-population area a relatively major road can just end somewhere. So maybe just close it after all.

**Comment by frodrigo** [comment]
@Famlam please, could you send a email to osmose-contact@openstreetmap.fr and we will give you access to our dev instance to test on real country.

Note, false positives noted on the frontend, are still produce by the backend, but just hidden on the frontend.

**Comment by Famlam** [comment]
Thank you for this offer! I'll send the email :)

I am however already concerned about that low-populated area (Sweden Gotland), as I don't know how to evaluate the validity of the errors in such cases. Hence, I tend to close this issue as I can't guarantee the results will be valid everywhere. What's your opinion on the Sweden Gotland results?

**Comment by Famlam** [comment]
Haven't received a response on the email yet, but I don't think I'll be able to convince myself sufficiently after seeing the Sweden one, so I'm closing this request of mine
