### ISSUE TITLE
Item #6070: analysis to be stopped?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#1526]
Hello,

As discussed on talk-fr, it seems that the analysis concerning item #6070 (Survey point out of boundary) is no longer relevant.

To be deleted?

**Comment by frodrigo** [comment]
Done. To be cleaned in the frontend.

Remove item 6070

**Comment by frodrigo** [comment]
> Done. To be cleaned in the frontend.
> 
> Remove item 6070

Done
