### ISSUE TITLE
Show (different) error when power pole is placed on building

### ISSUE THREAD

**Issue by pinkdroyd** [osm-fr/osmose-backend#153]
This seems happen a lot (at least here in Germany): power:pole being placed on the edge of a building that is tagged power:substation (see screenshot):
![pole-on-building](https://cloud.githubusercontent.com/assets/4980307/19315960/f2e36baa-909f-11e6-8346-e50ff5a4edef.png)

Osmose shows the error "Lone power tower or pole", instead it should display a message like "Power tower or pole on building". As a fix (in the openstreetmap-wiki, [here](https://wiki.openstreetmap.org/wiki/Osmose/issues#7040)) "Change to power:terminal" seems to fit.

**Comment by frodrigo** [comment]
The issues from your picture should be "Unfinished power minor line", "Lone power tower or pole" is for pole without line. Please, can you give a link.

power=pole should be replaced by power=terminal in your image, shouldn't it ?

**Comment by pinkdroyd** [comment]
Error can be found [here](http://osmose.openstreetmap.fr/en/map/#item=1010%2C1040%2C1050%2C1060%2C1070%2C1080%2C1090%2C1100%2C1110%2C1120%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C2xxx%2C3xxx%2C4xxx%2C5xxx%2C6xxx%2C7xxx%2C8xxx&level=1%2C2%2C3&tags=&fixable=&bbox=11.809326410293579%2C49.01271367809036%2C11.81954562664032%2C49.01591538868682&zoom=18&lat=49.013811&lon=11.813843&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT) (three times, actually).

> power=pole should be replaced by power=terminal in your image, shouldn't it ?

Yes, exactly

**Comment by frodrigo** [comment]
In the area you provide the Osmose-QA issues are outdated, since the OSM data have been update since last run of the check. I think the issues on the building will change to "Unfinished power minor line".

Nevertheless we need to support power=terminal is Osmose-QA.

**Comment by frodrigo** [comment]
Clearly my change do not fix the issues.
I will work again on this.

**Comment by frodrigo** [comment]
Now is no more reported as "Lone power tower or pole" but as Unfinished.

**Comment by pinkdroyd** [comment]
I do not think this is the ideal solution, an own error class would be better. Something like "Power tower or pole on or inside building". This would make it possible to filter, find and fix theses errors quickly.

**Comment by frodrigo** [comment]
Result are now coming. Most of the issues are in Germany.
http://osmose.openstreetmap.fr/en/errors/?item=1070&class=6,7

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#item=1070&class=6%2C7&zoom=15&lat=45.26641&lon=-0.2086&overlays=FFFFFFFFFFFFFFFFFFFFT&level=1%2C2%2C3&tags=&fixable=&limit=500

Some power=tower have building foundation imported from cadastre. How to deal with it?
![image](https://user-images.githubusercontent.com/1785486/45083585-871ef400-b0fc-11e8-8e52-2b56bb626987.png)
(cc @gustavecha)

**Comment by gustavecha** [comment]
Hi @frodrigo 
I us to remove those "fake" buildings.
Keep them as errors, this will ease detection.
