### ISSUE TITLE
Item #7010: some false positives?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#1531]
Hello,

I don't understand why Item #7010 analysis (Geodesic mark without building) returns this POI:
![Screenshot 2022-08-28 at 15-30-21 Osmose](https://user-images.githubusercontent.com/36087963/187076428-240075a7-9ab7-425c-9024-452ea0380d15.png)

or this other:
![Screenshot 2022-08-28 at 15-29-28 Osmose](https://user-images.githubusercontent.com/36087963/187076441-14fc41a5-62b8-4720-be05-09f955b28c56.png)

False positive or else?

**Comment by frodrigo** [comment]
It looks like to not working any more.

http://osmose.openstreetmap.fr/en/issues/open?item=7010

![image](https://user-images.githubusercontent.com/1785486/187652928-95e79eeb-218c-45f3-b30b-cb31f97f9708.png)

**Comment by frodrigo** [comment]
Fixing bad usage of diff mode.
