### ISSUE TITLE
Item #1050 : Reverse Roundabout

### ISSUE THREAD

**Issue by altilunium** [osm-fr/osmose-backend#1538]
Is there a database where Osmose keeps track of whether a country is "drive on the right" or "drive on the left"? 

Here is an example from [Indonesia](https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=-6.357587&lon=106.930055&item=xxxx&level=1&issue_uuid=fd861f98-431f-9adf-7868-b8bbb170238e), a "drive on the left" country. Clockwise roundabout is valid. But it's marked as invalid on Osmose.

![image](https://user-images.githubusercontent.com/70379302/188251315-eb916e81-1553-4baa-8a50-7651f25eff1f.png)

**Comment by frodrigo** [comment]
It set in configuration

https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L1146

It is the `driving_side` options at `right` by default.

The configuration for Indonesia is missing (or lost) in the configuration file.

**Comment by frodrigo** [comment]
Done.
