### ISSUE TITLE
debit_cards=yes should be valid

### ISSUE THREAD

**Issue by zyphlar** [osm-fr/osmose-backend#1539]
Here's an example: https://osmose.openstreetmap.fr/en/issue/b701acd1-d8f4-0f16-f372-d06b5bb9e549

The key is used all over the place and quite popular with 60,000 uses:

https://taginfo.openstreetmap.org/tags/payment%3Adebit_cards=yes#map

https://overpass-turbo.eu/s/1lAO

The reason I think there should not be an Osmose warning for this is because, at least in every place I've been in America in the last decade, there will be absolutely no indication whether a place takes debit cards versus credit cards: at this point if you have a card with a magnetic stripe that isn't Discover or American Express (aka Visa or Mastercard) then you can assume it will work anywhere on the American continent that accepts magnetic stripes. The payment logo on the door will just say "Visa/MasterCard/etc/etc" and the fact that you can "pay with debit" will be something you find out when you're at the register (or, in many cases, be totally transparent to you if you have a Visa/Mastercard-issued debit card like the vast majority of Americans.)

It used to be that you might see the Maestro logo for MasterCard Debit, or other processing network logos, but lately the only way you'll truly know if some debit network like PLUS or STAR or CO-OP is accepted is to try it: there won't be signage, employees won't know, and even the business owner who signed the contract with the processing firm won't know. I recently set up a credit card processing API with Stripe and have no idea which debit-not-credit networks may or may not be accepted: my assumption and expectation would be that they are, in fact I'd be surprised and upset if any brand failed to work worldwide. I know some processors and businesses explicitly don't support American Express or Discover, but that's it: not accepting Visa/MasterCard Debit and Credit is the same thing as not accepting cards here.

The most accurate tagging scheme to reflect American reality at this point would be `payment:cards=yes` and then further details if desired to clarify interesting situations like `payment:american_express=yes` -- it will be extremely difficult, much harder than determining the octane of gasoline offered or the wifi password or the presence of baby changing tables in all genders of the available restrooms, to determine if a certain business supports Mastercard's Maestro, Visa's PLUS, or any other variants.

The most detailed question you might think about walking in and asking a business is "do you accept debit, credit, amex and discover? What about EBT (government food aid cards?)" and even then "debit and credit" is more a synonym for "pin or signature" than any particular detail about processor brands. Even if I called a national chain like Starbucks or McDonald's and asked "do you accept Maestro Debit at all your locations?" they'd be unable to answer because most locations are franchises that can make many of their own decisions and contracts.

A much more important distinction at this point is whether a business accepts contactless (Apple and Google Pay) and chip (America's new mandatory version of chip and pin) not which debit brand they accept.

I don't know what the situation is outside North America, but within the continent at least I think this tag shouldn't generate a warning. The huge popularity of the tag should be an indicator that it isn't going away anytime soon. If there is any warning, it should probably be towards consolidating the situation into something like cards=yes rather than demanding that we document lots of irrelevant unknowable details.

**Comment by frodrigo** [comment]
item | 9002
-- | --
class | 9002013

This rule come from JOSM validator.
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/deprecated.mapcss#L710

cc @Klumbumbus

**Comment by sekerob** [comment]
Yup, been there, presented case 'who's wrong' and was sent into the woods with this tag and the same for credit_cards, IF you're talking about "payment:credit_cards=yes" (> 100k uses) and "payment:debit_cards=yes" (72511 uses). The 'debit_cards=yes' I missed to find in Taginfo. The case was that Osmose reports these as not precise enough, the German wiki on payment methods actually asks to detail each debit and credit card but the boss who closed the report was of the opinion that mappers have enough to do and I can assure you, it's pointless as ALL shops here accept Bancomat and Postamat and Visa and Mastercard and Maestro and Eurocard and so on, that it's really a question of What in Heavens insist on the spec out. Bitcoin if it's supported, ok worth noting but otherwise. debit and credit cards general defenition is to me enough and basta, so now I hit the X of ignore.

**Comment by frodrigo** [comment]
I think you both agree, but @zyphlar verbose issue is a bit confusing.

You both require stopping raisin issue from `payment:credit_cards=yes` and `payment:debit_cards=yes` from JOSM validator rules, right ?

If @Klumbumbus not interested in changing this in JOSM, and you provide outside references (wiki, ml...) abaout this, we can also backlist it in Osmose.

**Comment by sekerob** [comment]
Exactly, I got a very full ear of thoughts on the StreetComplete quest and then the subsequent alert in Osmose that it was imprecise to use these general payment method tags.

Specifically, I looked at multiple language wikis v.v. payment methods and only the German 'asked', I did not read an insist. Drop this rule is perfect, so the StreetComplete quest completing action is the closer of the case.

MTIA

**Comment by frodrigo** [comment]
From wiki

> payment:debit_cards : This is primarily used to specify if debit cards common in the local area are accepted. Specifying yes, while generalized, is still the most practical and useful to the consumer compared to the alternative of a mapper omitting payment information due to the inability, or impracticality of surveying every specific payment method at a location. However, in most cases, this tag should be used to specify that debit cards are not accepted. 

> payment:credit_cards : This is primarily used to specify if credit cards common in the local area are not accepted using no. Specifying yes, while generalized, is fine if it's not possible to exactly name the accepted cards. 

In short: 
> Specifying yes, while generalized, is fine if it's not possible to exactly name the accepted cards.

To conclude `*=yes` should not be reported as an issue.

**Comment by Klumbumbus** [comment]
Moved here: https://josm.openstreetmap.de/ticket/22367

**Comment by Klumbumbus** [comment]
Changed in JOSM in https://josm.openstreetmap.de/changeset/18557/josm

**Comment by zyphlar** [comment]
Very much appreciated, thank you! I agree it would be wonderful if we mapped every single accepted payment method everywhere, but practically speaking I'd rather map dog waste bag dispensers.

**Comment by frodrigo** [comment]
Thank all.
Will come on Osmose on next manual JOSM Validator rules.
Closing this issue.
