### ISSUE TITLE
Items #8380, #8381, #8382: DB source to be updated?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#1541]
Hello,

It seems that this analysis https://github.com/osm-fr/osmose-backend/pull/623 no longer works (eg https://osmose.openstreetmap.fr/fr/issues/open?item=8380 ; the same for the two others). Yet the url of the data source is the same : https://www.sandre.eaufrance.fr/atlas/srv/fre/catalog.search#/metadata/ebef2115-bee5-40bb-b5cc-4593d82ba334 (updated: 2021-12-10)

(I leave it to anyone who knows how to modify the code if necessary: I don't understand nothing about this kind of data catalogues).

HTH

**Comment by frodrigo** [comment]
Same for 8480 http://osmose.openstreetmap.fr/fr/issues/open?item=8480

**Comment by frodrigo** [comment]
> Same for 8480 http://osmose.openstreetmap.fr/fr/issues/open?item=8480

Fxing this one. But not linked to Merge_Wastewater_Plant_FR issue.

**Comment by frodrigo** [comment]
Also fixing this issue.
Bad filter on `DateMiseHorServiceOuvrageDepollution` field.

**Comment by frodrigo** [comment]
Fixed. It is back.
