### ISSUE TITLE
addr:street could also refer to official_name on highway=*

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1543]
item 2060
class 19
code https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_associatedStreet.py#L651
the conventions in Switzerland put the "ground" name in name=* and the official name in offiial_name=* in case of discrepancy between the ground and the state opendata
the analysis reports that addr:street has a street name (the official one) which was not found.
it would be nice if the analysis also checked official_name to avoid a false positive for every street with a sign not exactly identical to its official name

**Comment by Famlam** [comment]
A similar scenario is under discussion in NL, where it is proposed that motorways with an official name that is no-where indicated except in state documents (for example because a fuel station along a motorway _must_ legally have an address) while everyone refers to the motorway by its `ref`, would be tagged with only official_name. So I would support this.

https://forum.openstreetmap.org/viewtopic.php?pid=870317

**Comment by frodrigo** [comment]
See #949 #551

**Comment by Famlam** [comment]
The tagging proposal to tag streets that only carry a name on paper (without any indication that they really have a name; everyone (including street signs) only refer to the `ref`), as `official_name=*` + `noname=yes`, has been accepted and is also [documented](https://wiki.openstreetmap.org/wiki/Straatnamen_in_Nederland#Straatnaam_afgeleid_van_wegnummer) for the Dutch community. Also slowly issues start to pop up, ex: https://osmose.openstreetmap.fr/en/issue/248a0ee0-aec0-8430-0758-a76d188eb96e

@frodrigo I'm not sure if your reply means you prefer not to fix it or whether you'd accept a patch adding `official_name`? (I won't add alt_name and such; I can't think of good reasons why `name` and `official_name` wouldn't cover all addresses)

**Comment by frodrigo** [comment]
My issue with that is making data usage more complicated to have to join the `addr:street` with may think.

> Street name derived from road number
> If a street has a road number, the municipality may choose to derive the street name directly from it, for example, National Highway A3 or Provincial Road N999. Many municipalities have adopted this practice from the Model Regulation Naming and Numbering (Addresses) of the Association of Dutch Municipalities in their street naming policy.
> Place such street names in official_name=* instead of name=*. This ensures that data consumers using name=* and ref=* do not duplicate the road number. Also add noname=yes so that it is clear to fellow mappers and editor software that it is not intended to add a name=*.
> N.B. Because road number and street name are established in different ways, sometimes street name and road number may not match (anymore). 

From my local and cultural knowledge I find this weird. But I hope this come from a local community consensus.

**Comment by frodrigo** [comment]
@Famlam ok, let support `official_name` side of `name`.

**Comment by Famlam** [comment]
Thank you! It's a very easy patch. I verified the results with netherlands_zuid_holland

**Comment by frodrigo** [comment]
I see no significant changes in the results. Can you conf it is ok?

http://osmose.openstreetmap.fr/en/issues/open?item=2060&class=19&country=nether%2a

http://osmose.openstreetmap.fr/en/issues/graph.png?item=2060&class=19&country=france*&start_date=2022-09
http://osmose.openstreetmap.fr/en/issues/graph.png?item=2060&class=19&country=netherland*&start_date=2022-09

**Comment by Famlam** [comment]
Yeah, it's correct. It's a recent change by the Dutch community so not all highways are updated yet. Also, the majority of issues found is of course from residential areas (where a single apartment complex without nearby street can make up 100 reported addresses, in contrast to "numbered roads" which have maybe a single fuel station with address every 10 km).

**Comment by Famlam** [comment]
(p.s. I can't close this issue as fixed as I'm not the topic starter, so if you agree with me, please close it)
