### ISSUE TITLE
item 3032/class 30325 false positive : in Corsica, highways may have refs like "T 10"

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#1547]
Hello,

Osmose does raise issues « Invalid reference » for highways with ref beginning with "T ", eg http://osmose.openstreetmap.fr/fr/issue/09af319e-126b-8014-472c-e2fba11d71fa
The Corsica map of this issue looks like this : http://osmose.openstreetmap.fr/fr/map/#level=2&zoom=10&lat=41.916&lon=9.1557&tags=&fixable=&item=3032&class=30325

However, refs like "T 10" are normal cases in Corsica, France. "T" stands for "Territoriale", as in "Route Territoriale". See https://fr.wikipedia.org/wiki/Route_territoriale_en_Corse and https://fr.wikipedia.org/wiki/Route_territoriale_10.

Please, don't raise issue for highways with ref beginning with "T" in Corsica.

**Comment by frodrigo** [comment]
Should be added here with for FR or with a special case for Corsica.
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag_FR.py#L61

**Comment by frodrigo** [comment]
Add specific Corsica rule.

**Comment by frodrigo** [comment]
Fixed.
