### ISSUE TITLE
Tag conflict with jet bridges

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-backend#1556]
iD has a [preset called Jetway](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/aeroway/jet_bridge.json) that adds `highway=corridor`+`aeroway=jet_bridge`. This creates a lot of "Conflict between tags: aeroway, highway" false positives like this: https://osmose.openstreetmap.fr/en/issue/5be92ced-9269-7d0e-f200-203540ec85e5

**Comment by frodrigo** [comment]
There is no wiki entry about it. Maybe an other iD specific tag.

Anyway it could be added to the backlist.

https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Incompatibles.py#L37

**Comment by frodrigo** [comment]
Done.
