### ISSUE TITLE
add new analyse ref:FR:FANTOIR (mapcss)

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#1562]
ref:FR:FANTOIR regex is add in https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules
with this osmose info

throwWarning: "wrong ref:FR:FANTOIR";
    group: tr("validation rules Fantoir in France");
    -osmoseItemClassLevel: "9019/9019005/3";
    -osmoseTags: list("ref:FR:FANTOIR");
    -osmoseAssertNoMatchWithContext: list("way highway=residential name=impasse ref:FR:FANTOIR=75106S581T", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("node place=hamlet name=Laroudée ref:FR:FANTOIR=32340B023Z;32119B099T;32119B281R", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=residential name=impasse ref:FR:FANTOIR=no", "inside=FR");

thanks

**Comment by frodrigo** [comment]
Look goot to me, but juste note :
- Why not just group the two rule in one ?
- Why `{1,3}` and not just one or more `+` ?

**Comment by didier2020** [comment]
- one rule is now done,
-  it's one or more but i don't know how to write it ...

**Comment by frodrigo** [comment]
>     * it's one or more, i must replace '{1,3}' by '+'  ?

Yes

**Comment by frodrigo** [comment]
Will be shipped in next deploy.
