### ISSUE TITLE
False positive: bad tag value for sport=shot-put

### ISSUE THREAD

**Issue by bramoo** [osm-fr/osmose-backend#1564]
The way 1004803671 is tagged `sport=athletics;rugby_union;hockey;shot-put;long_jump`
Osmose is flagging it as bad tag value, apparently for the dash in shot-put, which [appears to be valid ](https://wiki.openstreetmap.org/wiki/Tag%3Asport%3Dshot-put)

[OSM link](https://www.openstreetmap.org/way/1004803671)
[Osmose details](https://osmose.openstreetmap.fr/en/issue/99110277-b7b5-519a-c5a1-efd8b8e49d62)

**Comment by frodrigo** [comment]
Done
