### ISSUE TITLE
Extend check of coulor

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1567]
I would like to propose to extend the check for colors to not only test for hexadecimal values, but also check if real color names are used.
For example: https://www.openstreetmap.org/node/8131853250 uses red-white rather than red;white. And taginfo shows a large amount of 'interesting' key values.

This can be done in two ways: 
- By updating the mapcss plugin
- Via a new python plugin

**Advantages of mapcss:**
 - Easy to add to the current file [colour.validator.mapcss](https://github.com/osm-fr/osmose-backend/blob/master/plugins/Colour.validator.mapcss) as something like:
`[colour][colour!~/^[a-z]+(; ?[a-z]+)*/][colour!~/^#/]`
- Catches a significant amount of the errors, especially if we add some more keys to the check

**Advantages of python:**
- Not limited to specific keys, we can just loop over all keys and find all that start or end with `colour`
- We can actually check for existing values, rather than just pattern recognition (e.g. if someone uses `rood` (Dutch) rather than `red`, it'd go undetected in pattern detection) <details><summary>color list</summary>```aliceblue, antiquewhite, aqua, aquamarine, azure, beige, bisque, black, blanchedalmond, blue, blueviolet, brown, burlywood, cadetblue, chartreuse, chocolate, coral, cornflowerblue, cornsilk, crimson, cyan, darkblue, darkcyan, darkgoldenrod, darkgray, darkgreen, darkgrey, darkkhaki, darkmagenta, darkolivegreen, darkorange, darkorchid, darkred, darksalmon, darkseagreen, darkslateblue, darkslategray, darkslategrey, darkturquoise, darkviolet, deeppink, deepskyblue, dimgray, dimgrey, dodgerblue, firebrick, floralwhite, forestgreen, fuchsia, gainsboro, ghostwhite, gold, goldenrod, gray, grey, green, greenyellow, honeydew, hotpink, indianred, indigo, ivory, khaki, lavender, lavenderblush, lawngreen, lemonchiffon, lightblue, lightcoral, lightcyan, lightgoldenrodyellow, lightgray, lightgreen, lightgrey, lightpink, lightsalmon, lightseagreen, lightskyblue, lightslategray, lightslategrey, lightsteelblue, lightyellow, lime, limegreen, linen, magenta, maroon, mediumaquamarine, mediumblue, mediumorchid, mediumpurple, mediumseagreen, mediumslateblue, mediumspringgreen, mediumturquoise, mediumvioletred, midnightblue, mintcream, mistyrose, moccasin, navajowhite, navy, oldlace, olive, olivedrab, orange, orangered, orchid, palegoldenrod, palegreen, paleturquoise, palevioletred, papayawhip, peachpuff, peru, pink, plum, powderblue, purple, red, rosybrown, royalblue, saddlebrown, salmon, sandybrown, seagreen, seashell, sienna, silver, skyblue, slateblue, slategray, slategrey, snow, springgreen, steelblue, tan, teal, thistle, tomato, turquoise, violet, wheat, white, whitesmoke, yellow, yellowgreen```</details>

To be able to avoid false positives (e.g. the python plugin shouldn't flag on items that are flagged by the mapcss test), it would be most convenient to deprecate the mapcss if the python plugin-method is chosen and have both the new and the existing checks implemented in the python plugin

Any preference? (If you like the idea of course)

**Comment by frodrigo** [comment]
> Not limited to specific keys, we can just loop over all keys and find all that start or end with colour

MapCSS can also do this.

* https://github.com/osm-fr/osmose-backend/blob/master/doc/2-PluginMapCSS.md
* https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation

```css
way[/^addr:/]  {}
```
> color list

The list is not so long, and can be included in MapCSS, I think.

The idea of MapCSS, is the check can be reused by other tools (like JOSM, you can add Osmose MapCSS  rules to your JOSM. And further I hope, one day, we can have a common rules set out of Osmose and JOSM).

**Comment by Famlam** [comment]
I'll work on it later this week(end) (and see if I can do some performance checks: I have bad experiences with very long regexes taking equally very long to evaluate, but that was like 5 years ago or so and more importantly, not in python)
I'll then probably add all keys with colors with >50k usages

> The idea of MapCSS, is the check can be reused by other tools (like JOSM, you can add Osmose MapCSS rules to your JOSM. And further I hope, one day, we can have a common rules set out of Osmose and JOSM).

Maybe also add them here? https://josm.openstreetmap.de/wiki/Rules

**Comment by Famlam** [comment]
Implemented all in the new PR. 

Regarding the timing, it seems the long regex is 'just' 10x slower than the mini-regex, according to this mini-code-snippet:
```py
import re
import datetime
colors = ['aliceblue', ' antiquewhite', ' aqua', ' aquamarine', ' azure', ' beige', ' bisque', ' black', ' blanchedalmond',
'blue', ' blueviolet', ' brown', ' burlywood', ' cadetblue', ' chartreuse', ' chocolate', ' coral', ' cornflowerblue',
'cornsilk', ' crimson', ' cyan', ' darkblue', ' darkcyan', ' darkgoldenrod', ' darkgray', ' darkgreen',
'darkgrey', ' darkkhaki', ' darkmagenta', ' darkolivegreen', ' darkorange', ' darkorchid', ' darkred',
'darksalmon', ' darkseagreen', ' darkslateblue', ' darkslategray', ' darkslategrey', ' darkturquoise',
'darkviolet', ' deeppink', ' deepskyblue', ' dimgray', ' dimgrey', ' dodgerblue', ' firebrick', ' floralwhite',
'forestgreen', ' fuchsia', ' gainsboro', ' ghostwhite', ' gold', ' goldenrod', ' gray', ' grey', ' green',
'greenyellow', ' honeydew', ' hotpink', ' indianred', ' indigo', ' ivory', ' khaki', ' lavender', ' lavenderblush',
'lawngreen', ' lemonchiffon', ' lightblue', ' lightcoral', ' lightcyan', ' lightgoldenrodyellow',
'lightgray', ' lightgreen', ' lightgrey', ' lightpink', ' lightsalmon', ' lightseagreen', ' lightskyblue',
'lightslategray', ' lightslategrey', ' lightsteelblue', ' lightyellow', ' lime', ' limegreen', ' linen',
'magenta', ' maroon', ' mediumaquamarine', ' mediumblue', ' mediumorchid', ' mediumpurple', ' mediumseagreen',
'mediumslateblue', ' mediumspringgreen', ' mediumturquoise', ' mediumvioletred', ' midnightblue',
'mintcream', ' mistyrose', ' moccasin', ' navajowhite', ' navy', ' oldlace', ' olive', ' olivedrab', ' orange',
'orangered', ' orchid', ' palegoldenrod', ' palegreen', ' paleturquoise', ' palevioletred', ' papayawhip',
'peachpuff', ' peru', ' pink', ' plum', ' powderblue', ' purple', ' red', ' rosybrown', ' royalblue', ' saddlebrown',
'salmon', ' sandybrown', ' seagreen', ' seashell', ' sienna', ' silver', ' skyblue', ' slateblue', ' slategray',
'slategrey', ' snow', ' springgreen', ' steelblue', ' tan', ' teal', ' thistle', ' tomato', ' turquoise',
'violet', ' wheat', ' white', ' whitesmoke', ' yellow', ' yellowgreen',
]

regex1 = re.compile(r'^[a-z]+(; ?[a-z]+)*')
regex2 = re.compile(r'^({0})(; ?({0}))*$'.format('|'.join(colors)))
maxruns = 100000
x=0

start_time = datetime.datetime.now()
for x in range(1,maxruns):
  re.search(regex1, "blauw")
end_time = datetime.datetime.now()
print(end_time - start_time)

start_time = datetime.datetime.now()
for x in range(1,maxruns):
  re.search(regex2, "blauw")
end_time = datetime.datetime.now()
print(end_time - start_time)
```

Which outputted on my pc in three runs:
0:00:00.186448
0:00:01.778752

0:00:00.116058
0:00:01.650812

0:00:00.131704
0:00:01.639274

**Comment by Famlam** [comment]
If it's easier for you: no need to reopen my issues if no-one besides us is involved: I know they'll take a while to deploy ;)

**Comment by frodrigo** [comment]
> If it's easier for you: no need to reopen my issues if no-one besides us is involved: I know they'll take a while to deploy ;)

Closed automatically on merging the PR. But I prefer tag the issue as "ready". And close once deployed and checked.

**Comment by frodrigo** [comment]
@Famlam results are ok for you? Can we close it?

**Comment by Famlam** [comment]
Yeah, I'm happy with the results.
I am however thinking of whether the message could be clearer. 'Unknown colour' may be a bit vague in cases where the actual issue is i.e. the use of capitals (like forestGreen rather than forestgreen) or the lack of ';' (like red / green instead of red;green)
Those are now marked as false positives.

Do you have suggestions? If not, we can close it

**Comment by frodrigo** [comment]
We may miss some doc attributes like `-osmoseFix`, or `-osmoseTrap` to explain this thing from the MapCSS.

**Comment by frodrigo** [comment]
> Yeah, although that'll be difficult to get into external mapcss rules I think.

It is not an issue. JOSM support/ignore rule starting with "-". Some JOSM MapCSS contrib files already have `-osmose` rules.

> Maybe `Unknown or invalid colour in tag X` as throwWarning message would be better for now, what do you think?

But yes, improving `throwWarning` first.
