### ISSUE TITLE
False positive on opening_hours with a ruleset override

### ISSUE THREAD

**Issue by xlii-chl** [osm-fr/osmose-backend#1568]
Parser detects an incorrect opening_hours on `Tu-Fr 11:00-19:00; Sa 10:00-22:15; 14:00-15:00 closed`

It seems valid on https://wiki.openstreetmap.org/wiki/Key:opening_hours#Syntax since it's just a ruleset overriding a previous ruleset.

[Openingh](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Tu-Fr%2011%3A00-19%3A00%3B%20Sa%2010%3A00-22%3A15%3B%2014%3A00-15%3A00%20closed&lat=48.7769&lon=9.1844&mode=0&DATE=1664152020000) is ok, [YoHours](https://projets.pavie.info/yohours/?oh=Tu-Fr%2011:00-19:00;%20Sa%2010:00-22:15;%2014:00-15:00%20closed) doesn't display anything.

Object :
* https://www.openstreetmap.org/node/4579458237
* http://localhost:8111/import?url=http://osmose.openstreetmap.fr/api/0.3/issue/dc81afc2-8ebe-2403-8024-ba2b8bdb3ed4/fix/0

(maybe duplicate of #1106 )

**Comment by Famlam** [comment]
http://osmose.openstreetmap.fr/nl/issue/dc81afc2-8ebe-2403-8024-ba2b8bdb3ed4

**Comment by frodrigo** [comment]
cc @dfaure

**Comment by Famlam** [comment]
Last time the reply came from @dfaure-kdab

**Comment by dfaure-kdab** [comment]
Ah, this is the same as https://bugs.kde.org/show_bug.cgi?id=445787 which I fixed long ago, so what's missing is to update KOpeningHours in osmose-backend again. Coming up, let's see if I remember how ;)

**Comment by dfaure-kdab** [comment]
Done but I'm still having problems testing the change.
I do
```
cd docker
docker-compose -f docker-compose.yml -f docker-compose-dev.yml build
docker-compose -f docker-compose.yml -f docker-compose-dev.yml run backend bash
```
and then `pytest -k Opening`, which is IIRC what worked to run the tests in `plugins/TagFix_Opening_Hours.py`,
but I get this error from pytest:

```

================================================================================================== ERRORS ===================================================================================================
____________________________________________________________________________________ ERROR collecting modules/OsmPbf.py _____________________________________________________________________________________
ImportError while importing test module '/opt/osmose-backend/modules/OsmPbf.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
modules/OsmPbf.py:22: in <module>
    from . import OsmPbf_libosmbf
modules/OsmPbf_libosmbf.py:24: in <module>
    from .osm_pbf_parser import osm_pbf_parser
E   ImportError: cannot import name 'osm_pbf_parser' from 'modules.osm_pbf_parser' (/opt/osmose-backend/modules/osm_pbf_parser/__init__.py)
```
(and the same from modules/OsmPbf_libosmbf.py)

This seems completely unrelated to my changes, so I must be doing something wrong?

**Comment by dfaure-kdab** [comment]
Done but I'm still having problems testing the change.
I do
```
cd docker
docker-compose -f docker-compose.yml -f docker-compose-dev.yml build
docker-compose -f docker-compose.yml -f docker-compose-dev.yml run backend bash
```
and then `pytest -k Opening`, which is IIRC what worked to run the tests in `plugins/TagFix_Opening_Hours.py`,
but I get this error from pytest:

```

================================================================================================== ERRORS ===================================================================================================
____________________________________________________________________________________ ERROR collecting modules/OsmPbf.py _____________________________________________________________________________________
ImportError while importing test module '/opt/osmose-backend/modules/OsmPbf.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
modules/OsmPbf.py:22: in <module>
    from . import OsmPbf_libosmbf
modules/OsmPbf_libosmbf.py:24: in <module>
    from .osm_pbf_parser import osm_pbf_parser
E   ImportError: cannot import name 'osm_pbf_parser' from 'modules.osm_pbf_parser' (/opt/osmose-backend/modules/osm_pbf_parser/__init__.py)
```
(and the same from modules/OsmPbf_libosmbf.py)

This seems completely unrelated to my changes, so I must be doing something wrong?

**Comment by frodrigo** [comment]
@dfaure-kdab using dev docker, you have to rebuild on first run because of mounting volume. https://github.com/osm-fr/osmose-backend/tree/master/docker#start-docker-backend-container

**Comment by Famlam** [comment]
Specifically running this line I guess:
cd modules/osm_pbf_parser/ && make && cd -

**Comment by xlii-chl** [comment]
This bug seems to still exist, Osmose gives an error on this opening_hours `Tu-Fr 10:00-19:00, Sa 10:00-18:00; 14:00-15:00 closed` which is valid.

* https://www.openstreetmap.org/node/9558673814
* http://osmose.openstreetmap.fr/api/0.3/issue/9da9a3ee-d43e-8fb4-af4f-55462a53b6a4/fix/0

The fix proposed by Osmose is not equivalent either.

Should I reopen this issue ? Create a new one ?

**Comment by frodrigo** [comment]
I add as test to check again this value, and it is ok.
https://github.com/frodrigo/osmose-backend/commit/1024dd4aad8098dab205f7faeb48bc1f506d40d6

I also update kopeninghours to v23.03.80 : https://github.com/frodrigo/osmose-backend/commit/4da5a72b637a0af599a0745cc5c53700e1a2ad6b

@jocelynj Maybe we need to check kopeninghours is updated on the backends.
