### ISSUE TITLE
5010-704 Encoding problem should detect unicode bi-directional markers worldwide

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#157]
The characters on the right of the table https://en.wikipedia.org/wiki/Bi-directional_text#Table_of_possible_BiDi-types are probably always wrong in OSM.

Osmose correctly detects the bad character at the end of https://www.openstreetmap.org/node/480488690

It would be good if this check ran worldwide.

**Comment by frodrigo** [comment]
Can you point the probleme in the code ?

**Comment by grischard** [comment]
I think the problem is that Name_Dictionary_fr.py only runs in French-speaking countries, when some of its rules could apply worldwide.

**Comment by frodrigo** [comment]
Name_Dictionary.py was previously split into Name_Dictionary.py and Name_Dictionary_fr.py with the idea that all rules from Name_Dictionary may be applied worldwide. But there is only one sub class, the fr one. We can probably make a non specific language subclass.

Concerning the BiDi I don't know which line of code results in this issue, yet.

**Comment by grischard** [comment]
CC @giggls

**Comment by grischard** [comment]
I think I've found it: [Name_Dictionary.py#L101](https://github.com/osm-fr/osmose-backend/blob/d96ec115e53c781e0b562425834293fb95e9554b/plugins/Name_Dictionary.py#L101) is really `self.DictEncoding[u"n<200e>"] = u"n"`, with [<200e>](http://www.fileformat.info/info/unicode/char/200e/index.htm) being the LTR character. Line 99 similarly checks for `s<200e>`. They're always wrong in OSM though, not only when preceded by 's' or 'n'.

Does this check already run worldwide?

If so, I'll prepare a PR to replace L99 and L101 with a table of these BiDi characters.

And just thinking aloud, should the encoding tests only run on names, or on every tag? @giggls, thoughts?

**Comment by giggls** [comment]
I would suggest to run it on any name tag (name:*, int_name, ...) but not on object tags like highway.
It is unlikely that they appear on those.

**Comment by grischard** [comment]
That junk is possibly present in every tag that could likely have been copy-pasted: operator, contact:*, addr:street, postcode, and so on.

**Comment by frodrigo** [comment]
Results:
http://osmose.openstreetmap.fr/fr/errors/?item=5010&class=704

**Comment by grischard** [comment]
It's interesting to see lots of items for places like Israel, Ukraine, Greece. I don't get any results when I click on them yet?

**Comment by frodrigo** [comment]
Your are probably talking about the other issue, note the &useDevItem=all at the end of the URL, since the item is still unreleased. Note also I have added one more commit, because they contains many false positifs
