### ISSUE TITLE
Wrong suggestion for tag 'brunch'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1571]
When detecting tag 'brunch', Osmose currently proposes to replace it by tag 'branch'.
See screenshot below.
Instead, it should propose to replace it by tag 'breakfast:brunch'.  (see https://wiki.openstreetmap.org/wiki/Key:breakfast )

![osmose_bad_suggestion_for_brunch](https://user-images.githubusercontent.com/58949423/192228266-6702e563-6e9d-42b7-b237-8a9e35256270.PNG)

**Comment by Famlam** [comment]
This check looks for misspelled keys (`brunch=*` isn't a known key) and suggests what it may have been based on commonly used tags in the area. It doesn't actually try to interpret what might be meant. Consider it like your Word spelling checker. So I think this is a valid warning, right?

**Comment by frodrigo** [comment]
As undocumented tag with de facto quasi no-usage, yes it is good report from Osmose.
