### ISSUE TITLE
Wrong suggestion for tag 'link'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1572]
When detecting tag 'link', Osmose currently proposes to replace it by tag 'line', even when value starts by 'http' or 'www'.
See screenshot below.
Instead, it should propose to replace it by tag 'website'.

![osmose_bad_suggestion_for_link](https://user-images.githubusercontent.com/58949423/192228746-7aabb023-2c34-4f5e-a34e-f7db6d12bab8.PNG)

**Comment by frodrigo** [comment]
As undocumented tag with de facto quasi no-usage, it is good report from Osmose.
