### ISSUE TITLE
Wrong suggestion for tag 'marking'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1573]
When detecting tag 'marking', osmose currently suggests to replace it by tag 'parking'. Which was wrong for all the cases I've seen worldwide.
See screenshot below.
Instead, I think it should propose to replace it by tag 'road_marking'. See https://wiki.openstreetmap.org/wiki/Key:road_marking

![osmose_bad_suggestion_for_marking](https://user-images.githubusercontent.com/58949423/192230177-2e9ff50f-e151-4521-a31c-bfddf4f60cb6.PNG)

**Comment by frodrigo** [comment]
As undocumented tag with de facto quasi no-usage, it is good report from Osmose.
