### ISSUE TITLE
Wrong suggestion for tag 'mine'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1574]
When detecting tag 'mine', Osmose currently proposes to replace it by tag 'line'. Which is wrong in all cases I've seen worldwide.
See screenshot below.
Instead, I suggest to replace it by tag 'name' or 'description' if they are not used yet. Else by tag 'note'.

![osmose_bad_suggestion_for_mine](https://user-images.githubusercontent.com/58949423/192231215-ad36c679-4755-4698-8c09-f5ad3d6415dc.PNG)

**Comment by frodrigo** [comment]
As undocumented tag with de facto quasi no-usage, it is good report from Osmose.
