### ISSUE TITLE
Wrong suggestion for tag 'retail'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1576]
When detecting tag 'retail', Osmose currently proposes to replace it by tag 'detail'. 
See screenshot example below.
Instead, maybe it should propose to replace it by tag 'shop' or else ?

![osmose_bad_suggestion_for_retail](https://user-images.githubusercontent.com/58949423/192232854-a4a10dc6-66f9-43b2-b817-0c8d0b0d00d8.PNG)

**Comment by frodrigo** [comment]
As undocumented tag with de facto quasi no-usage, yes it is good report from Osmose.
