### ISSUE TITLE
Wrong suggestion for tag 'sale'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1577]
When detecting tag 'sale', Osmose currently proposes to replace it either by tag 'salt' or 'male'. Which is completely wrong and frequent (i've seen this hundreds times worldwide).
See examples below.
Instead, it should propose to replace it by tag 'shop' or else.

![osmose_bad_suggestion_for_sale](https://user-images.githubusercontent.com/58949423/192234564-fce90e7a-6966-4a8c-a141-c10d15174649.PNG)
![osmose_bad_suggestion_for_sale2](https://user-images.githubusercontent.com/58949423/192234571-91b876d5-3168-4362-89d9-14bcc7ddbf0c.PNG)

**Comment by frodrigo** [comment]
As undocumented tag with de facto quasi no-usage, yes it is good report from Osmose.

Note it is a typo check. So it suggest fixing a typo. There is also other controls, like deprecated or tagcleaner, to replace tags.
