### ISSUE TITLE
False-positive for tag 'train'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1579]
When detecting tag 'train', Osmose currently proposes to replace it by tag 'drain'.
See example below.
This is wrong as 'train' is a valid tag. See https://wiki.openstreetmap.org/wiki/Key:train

![osmose_error_suggestion_for_train](https://user-images.githubusercontent.com/58949423/192236758-e31f5c29-ef5a-4dd5-bcc0-c4b5b22b6691.PNG)

**Comment by frodrigo** [comment]
Fixing this one, thank @Famlam

**Comment by frodrigo** [comment]
Deployed.
