### ISSUE TITLE
False - Positive for tag parking:condition:*=*

### ISSUE THREAD

**Issue by Bingo67** [osm-fr/osmose-backend#1580]
after an [approved proposal](https://wiki.openstreetmap.org/w/index.php?oldid=2289049) parking:lane:_side_=no_stopping or parking:lane:_side_=no_parking are deprecated and are substituted by parking:condition:_side_=no_stopping and parking:condition:_side_=no_parking. That means "parking:condition:[side] without value parking:lane:[side]" should not be wrong

**Comment by frodrigo** [comment]
cc @Famlam

**Comment by Bingo67** [comment]
maybe we need no change, I saw some mappers, who use e.g. the tag parking:condition:left=no_parking in combination with the tag parking:lane:left=no. But the value no should be used, when there is no place for parking. In most cases there is place for parking, but it is forbidden. So I think parking:lane:left=no in combination with parking:condition_left=no_parking is only used to show no errors on osmose. Maybe I'm wrong.

**Comment by Famlam** [comment]
Hmm, I agree that we could (should?) make an exception for `parking:condition:*=no/no_*` as in that case tagging the `parking:lane:*` is redundant tagging.

**Comment by frodrigo** [comment]
Deployed.
