### ISSUE TITLE
False positive for camra / camera on pubs

### ISSUE THREAD

**Issue by boothym** [osm-fr/osmose-backend#1581]
Osmose suggests that "camra=yes" should be changed to camera. For example: https://osmose.openstreetmap.fr/en/issue/ba483f1c-3126-450c-ff0c-c167a000d28a

However this is an incorrect suggestion as "camra" is used on pubs in the UK to indicate it is listed in the Campaign for Real Ale's Good Beer Guide. https://wiki.openstreetmap.org/wiki/Tag:camra=yes?uselang=en-GB

**Comment by frodrigo** [comment]
Fixing this one, thank @Famlam

**Comment by frodrigo** [comment]
Deployed.
