### ISSUE TITLE
False positive (or mistake in rule) on issue for code nat_ref

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#1586]
all this kind of issue :
http://osmose.openstreetmap.fr/fr/issue/84b8df86-9d4a-ec53-0b1f-60f81694a52f
where the last digit is 10 or more are false positive
for this ex nat_ref=59A902507_10D tested with josm without issue
and regex tested on 
https://regex101.com/
with
^([1-9][0-9]|0[1-9])[ANP](8|9)[0-9]{3}(|A|N)([0-9]?[0-9]|B1|B2)(|[A-Z]|[a-z])(|CD)_(1[0-9]|[1-9])D$
i don't see the mistake

**Comment by frodrigo** [comment]
Check here if the python code is ok
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Josm_FranceSpecificRules.py

**Comment by didier2020** [comment]
found error in self.re_33342623, where letter 'D' (n'est pas a la bonne position ; doit etre décalée sur la droite après la parenthese)
