### ISSUE TITLE
Mapcss generation fails with [key?!] selector

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1590]
I encountered that on the following rule:
```
way[oneway:bicycle?!][!oneway:mofa][oneway?][inside("NL")] {
  throwWarning: tr("{0} without {1}", "{0.tag}", "{1.key}");
  group: tr("NL overige problemen");
}
```
the mapcss generator fails (in a cascade of errors, but primarily due to 
`line XXX:19 no viable alternative at input 'way[oneway:bicycle?!'`
), after which everything fails.

As far as I could debug it, it seems related to `?!` not being defined as an existing selector in: 
https://github.com/osm-fr/osmose-backend/blob/ec6bc95e5091f2c77ba615e33abf9a5374fbc26f/mapcss/MapCSS.g4#L203-L206

I suspect that 
```
OP_NOT ? (osmtag | quoted) QUESTION_MARK ?
```
should be replaced by
```
OP_NOT ? (osmtag | quoted) ? |
(osmtag | quoted) QUESTION_MARK OP_NOT ?
```

**Comment by frodrigo** [comment]
I think you are right.

But unlike the other part, this new operator is not well documented.

I think it rather should be `(QUESTION_MARK OP_NOT ?) ?` or by adding a new operator `?!` as (eg) `QUESTION_MARK_NEGATED` (or BANG).

**Comment by Famlam** [comment]
> But unlike the other part, this new operator is not well documented.

The operator seems to be [defined](https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation) as meaning `not [key?]`:

> The value is evaluated to true, if it is either "yes", "true", or "1". All other values are evaluated to false.

Which probably means that nothing else needs to be changed on the `mapcss2osmose` side (I hope)

---------------------

Regarding: 

> I think it rather should be (QUESTION_MARK OP_NOT ?) ?

I would expect they produce the same result: my solution would exclude the possibility of `[!key?!]` (which I have no clue how that's supposed to evaluate, but in practice that'll probably never occur), but otherwise the result should be the same.

---------------------

My local system cannot run anything beyond ANTLR 4.9.3 (I probably have to switch to openjava at some point: still running the (up to date) 'regular' java). Am I allowed (and able) to install antlr on the dev server? Or would you be able to regenerate the parser for me with this change so I can test it?
