### ISSUE TITLE
Osmose mapcss tags extension

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1598]
Spin-off from [issue 1567](https://github.com/osm-fr/osmose-backend/issues/1567#issuecomment-1273849693)

Nice-to-have mapcss keys would be:
- `-osmoseDetails` (same as setting `details` in a regular python plugin)
- `-osmoseTrap` (same as setting `trap` in a regular python plugin)
- `-osmoseFix` (same as setting `fix` in a regular python plugin)
- `-osmoseResource` (same as setting `resource` in a regular python plugin)

- `-osmoseOnlyForCountry` (same as setting `only_for = [x]` in a regular python plugin, to limit the plugin to certain countries)
- `-osmoseNotForCountry` (same as setting `not_for = [x]` in a regular python plugin, to disable the plugin in certain countries)

**Comment by frodrigo** [comment]
>     * `-osmoseOnlyForCountry` (same as setting `only_for = [x]` in a regular python plugin, to limit the plugin to certain countries)
> 
>     * `-osmoseNotForCountry` (same as setting `not_for = [x]` in a regular python plugin, to disable the plugin in certain countries)

This two can be done using this already existing mapccs code `[inside("FR")] `

**Comment by Famlam** [comment]
> > ```
> > * `-osmoseOnlyForCountry` (same as setting `only_for = [x]` in a regular python plugin, to limit the plugin to certain countries)
> > 
> > * `-osmoseNotForCountry` (same as setting `not_for = [x]` in a regular python plugin, to disable the plugin in certain countries)
> > ```
> 
> This two can be done using this already existing mapccs code `[inside("FR")] `

That only works on a selector level

**Comment by frodrigo** [comment]
> > > ```
> > > * `-osmoseOnlyForCountry` (same as setting `only_for = [x]` in a regular python plugin, to limit the plugin to certain countries)
> > > 
> > > * `-osmoseNotForCountry` (same as setting `not_for = [x]` in a regular python plugin, to disable the plugin in certain countries)
> > > ```
> > 
> > 
> > This two can be done using this already existing mapccs code `[inside("FR")] `
> 
> That only works on a selector level

But, we do not report county in doc https://github.com/osm-fr/osmose-backend/blob/master/doc/0-Index.md#classes-of-issues

**Comment by Famlam** [comment]
I'll await #1782 to go live (to see if there's anything else to be adjusted), then add `-osmoseExample`. For some reason I missed that one.
