### ISSUE TITLE
Wrong suggestion in Japan (circular vs roundabout)

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1599]
There is no roundabout in Japan, only rotaries.
In Japan, Osmose should propose 'junction=circular' instead of 'junction=roundabout'.

See https://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout

**Comment by frodrigo** [comment]
Note sure what you are reporting here.

Please, can you set in github issues, a link to osmose map, a link to the detail of an osmose issue, or item and class ref.

**Comment by frodrigo** [comment]
Fixed
