### ISSUE TITLE
Osmose needs a control with higher prio than typo_check

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1600]
Currently by default (ie with at least all Severe controls enabled), Osmose overall gives bad suggestions for the tags below:
link  (suggests 'line' instead of 'website')
short (suggests 'sport' instead of 'short_name')
sale (suggests 'salt')
retail
ramp (suggests 'lamp')
mine
marking
brunch
And probably more

These bad suggestions come from the 'typo_check' control, and this is not a bug of the typo_check control (which works as expected by giving typo fix suggestions), but it is an issue of the Osmose current design which assumes these are typos, instead of assuming these are bad tag usages.
Osmose should have other controls (new or existing) that make correct suggestions for these tags, and that have higher priority/Severity than 'typo_check' , so that correct suggestions appear first by default.

**Comment by iiitomo** [comment]
Thx Famlam, but as far as i understand, https://github.com/osm-fr/osmose-backend/issues/1483 will not solve this issue, because typo_check will continue to propose tags that are close. To solve this issue, we need to blacklist some tags in typo_check, and have another control to propose the correct fix.

**Comment by Famlam** [comment]
Well, yeah, but suggesting (as example) line rather than link is correct behavior and should not be blacklisted. 1483 will prevent converting of valid tags to invalid tags (ramp to lamp for example)

**Comment by iiitomo** [comment]
I've seen hundreds usage of 'link' where the value was a URL. And none where it was a tipo for 'line'. So if we don't blacklist tipo_fix, then at least we should have another control to propose a more appropriate fix (e.g. 'website') before tipo_fix.

**Comment by Famlam** [comment]
So how would you propose we can distinguish between a typo and a wrong key? If someone has `marking=yes`, how do we know it should "actually" be lane_marking, road_marking or parking? Same for link: it can be a typo for line, but it could be website, contact:website, brand:website, or someone who wants to indicate that it's a linking feature between any kind of route.
Remember, it are suggestions, not requirements. Your Word (or whatever text editor) spell checker also cannot read minds on what is actually meant.

If it happens a lot, you might want to go through the deprecation process to get a key formally deprecated, then have i.e. JOSM (whose rules are imported in Osmose) create an warning.

**Comment by frodrigo** [comment]
Done using tagingo.
