### ISSUE TITLE
Error analyzer_merge_road_ES in Cáceres

### ISSUE THREAD

**Issue by JorgeSanzS** [osm-fr/osmose-backend#1604]
Error analyzer_merge_road_ES in Cáceres
In Cáceres analyzer_merge_road_ES does not work correctly. There are many false positives.
Hundreds of errors like this come out. https://osmose.openstreetmap.fr/en/issue/e9f6204e-c653-267f-5fda-360fd1b09f51
You can clearly see that the road is in OpenStreetMap. It happens along all the roads in the province of Cáceres.

**Comment by frodrigo** [comment]
Thank for report. There is an issue from download.osm.fr
https://github.com/osm-fr/infrastructure/issues/398

All others check on Osmose for this province are also bad.

**Comment by frodrigo** [comment]
New extract available. We have now to remove it from backend.

**Comment by jocelynj** [comment]
Old extracts have been removed from all backends.

**Comment by frodrigo** [comment]
Run with new extract done.
