### ISSUE TITLE
Duplicate fix from 2 controls

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1615]
Currently, several errors ('access=public', 'noexit=no' , and probably more) are detected by 2 controls: 'deprecated value' and 'deprecated tagging'.
Hopefully, both suggest the same fix, but this is confusing and time-consuming for Osmose users.
There ideally should be no duplicate between controls.

Examples: https://www.openstreetmap.org/node/2071563065
https://www.openstreetmap.org/node/3340987280
https://www.openstreetmap.org/node/3340986379
https://www.openstreetmap.org/node/3340989980
https://www.openstreetmap.org/node/3340989982
https://www.openstreetmap.org/way/304914609

Another example:
![IMG_20221023_211806](https://user-images.githubusercontent.com/58949423/197392470-21964565-90f0-4b76-a81a-5dddd288a5b8.jpg)
![IMG_20221023_211824](https://user-images.githubusercontent.com/58949423/197392473-91ec8568-b385-479b-89d9-d4101ee68a31.jpg)

**Comment by Famlam** [comment]
One comes from TagFix_Deprecated (which reads wiki.openstreetmap.org ), the other from JOSM.
I think it's unavoidable to have duplicates here, given that they're from two external sources
