### ISSUE TITLE
country not France for item=9019 and class=9019004 

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#1618]
9019 is for "spécific France"
but there is another country : see at http://osmose.openstreetmap.fr/fr/issues/open?item=9019&class=9019004

**Comment by Famlam** [comment]
Seems it needs to add `[inside("FR")]` to `node[highway=motorway_junction][ref=~/^\D/]`

**Comment by Famlam** [comment]
Update is failing on an assert... @frodrigo do you know who to cc for the French mapcss rules?

**Comment by frodrigo** [comment]
From history https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules?action=history
all last edit are from @didier2020 

There is one `assertMatch` in place of `-osmoseAssertNoMatchWithContext`, it is not the issue ?

**Comment by Famlam** [comment]
Ah the topic starter, oops 0:) 
Yeah, I had a similar issue (but just discarded the asserts) that Osmose evaluates inside(...) as false in asserts, while JOSM evaluates them as true.

**Comment by Famlam** [comment]
I figured I could also change this myself as from the remainder of the file it's clear that the `-osmoseAssert*` syntax is preferred over the `assert*`. Now it works https://github.com/osm-fr/osmose-backend/pull/1623

After the update has been live (and all non-France country results are gone again), it may be an idea to limit it to France by default in the config, similar to that Brazilian rules are limited to Brazil, Russian to RU, German to DE? Saves the server a lot of checks that only end when `and (mapcss.inside(self.father.config.options, 'FR'))` is evaluated, which is done after all other mapcss rule evaluations. Practically all rules are restricted to `[inside("FR")]` anyway. But as a Dutch person, I'll leave this to someone who's actually from France :)

Brazil example:
https://github.com/osm-fr/osmose-backend/blob/master/mapcss/item_map.py#L86

**Comment by frodrigo** [comment]
Done & fronted clean.
