### ISSUE TITLE
Use GTFS data for transport platform, area, route and route_master

### ISSUE THREAD

**Issue by sidjy** [osm-fr/osmose-backend#163]
Manu public transport operators publish GTFS open data (for exemple STIF https://opendata.stif.info/explore/dataset/offre-horaires-tc-gtfs-idf/information/ ). As it is a technical standard, it would bé useful to implement a parser in osmose back-end, so we can integrate at least transport platform and area easily for manu PT operators worldwide (for stop, route and route_master it is more difficult as we need to find the nearest way, and the used way segments). We need a convenient key between GTFS and OSM, perhaps a gtfs_id or ref:GTFS key?

**Comment by frodrigo** [comment]
A GTFS is just a CSV in a ZIP. If no join on the CSVs is required we can already do this.

**Comment by sidjy** [comment]
Indeed, we need some type of join on the CSV...
We can imagine some preprocessing on the GTFS/zipped CSV files to produce "ready to use" CSV files for osmose...

- routes.txt list the different lines of PT (all bus/rail/metro lines/...), equivalent to type=route_master OSM relation.
- Foreach line, trips.txt lists all the different trips, equivalent to type=route OSM relation.
- Foreach trip, stop_times.txt lists all the different stops, equivalent to OSM public_transport=platform.
- Foreach stop, stops.txt gives lat/lon coordinates and the name of the stop (public_transport=platform).

Directly parsing stops.txt without join can be done, but we loose some useful informations : we know it is a transport platform where passengers board or disembark from a transit vehicle, its name, its id, and its location, but we do not know which lines use it (and which type of PT : is it bus/rail/metro???). Is it enough to be useful ?

Note : there are realy many GTFS feeds around the world, see here : https://transitfeeds.com/about
Of course, quality of data will vary, but it would be useful to help integration of PT in OSM.

**Comment by frodrigo** [comment]
In fact I found two analysers already based on GTFS
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_public_transport_FR_transgironde.py
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_railway_railstation_FR.py

**Comment by frodrigo** [comment]
TrasitFeeds does not seem to provide data licence.

There is also https://navitia.opendatasoft.com and they provide a licence field in metadata.

**Comment by frodrigo** [comment]
@sidjy @nlehuby stops.txt from GTFS should be platform or stop position ?

**Comment by nlehuby** [comment]
The GTFS format puts no constraint on that : the GTFS stop is a logical stop (whereas OSM ones are physical ones). A GTFS stop can be a platform, a stop_position, or even the center of the stop area.
If you have a stop served by 3 bus lines, you can have 1 GTFS stop, 3 GTFS stops, but even 2 GTFS stops :confused: 
So you have to analyze the GTFS modelization to determine what to do precisely with the stops.
I think for the buses, stops are mostly platform or center of stop area, whereas for trains, they are mostly stop_position

You have the same fuzz with the routes : they are a group of trips so they can be lines (type = route_master), but they also can be just routes (type = route) or group of routes (nothing in OSM).

**Comment by sidjy** [comment]
A good solution would be to let the user determine if it is a platform or a
stop_position. A good hint for bus is the distance to nearest route: for
most cases in Ile de France GTFS stops for busses are platform.

**Comment by frodrigo** [comment]
We do it with stop. The others can't feet easly in Osmose.
