### ISSUE TITLE
Detect cycles in relation containment

### ISSUE THREAD

**Issue by brawer** [osm-fr/osmose-backend#1635]
Could Osmose detect cycles in the relation containment graph?

While writing some program that works with OSM relations, I found cycles in the containment graph. For example, [relation/2913585](https://www.openstreetmap.org/relation/2913585) is part of [relation/12762833](https://www.openstreetmap.org/relation/12762833), which is again part of the same relation where we started. If a naive implementation were to traverse this relationship graph, it would run into an infinite loop. This isn’t a super serious problem; checking for cycles is easy enough for data consumers. But it’s definitely a tagging mistake, so I wonder if Osmose could flag it.

In Switzerland, there’s currently three such cycles (as of November 1, 2022):
* [relation/2913585](https://www.openstreetmap.org/relation/2913585) ⟶  {relation/12762833, relation/12762834} ⟶  relation/2913585
* [relation/4012524](https://www.openstreetmap.org/relation/4012524) ⟶  {relation/12762831, relation/12762832} ⟶  relation/4012524
* [relation/9202820](https://www.openstreetmap.org/relation/9202820) ⟶  relation/13987412 ⟶  relation/9202820

**Comment by Famlam** [comment]
Analyser is live:
https://osmose.openstreetmap.fr/nl/map/#source=&item=1160&class=2&zoom=7&lat=45.813&lon=9.206&level=1%2C2

Regarding "In Switzerland, there’s currently three such cycles":
You might want to hide your annexation plans a bit better: 2 of them are still in Italy as of today 😋

**Comment by brawer** [comment]
Awesome, thank you! 😀
