### ISSUE TITLE
add `source:maxspeed=AT:urban:40` in TagFix_Maxspeed.py

### ISSUE THREAD

**Issue by mcliquid** [osm-fr/osmose-backend#1640]
**Item**: [3032](https://osmose.openstreetmap.fr/de/issues/open?status=open&item=3032)
**Class**: [303241](https://osmose.openstreetmap.fr/de/issues/open?item=3032&class=303241&country=austria)
**Location**: Austria

In Austria, it is common there to have various speed limits in built-up areas.

Under the town sign, a lower speed is then posted with the addition "Excluding priority roads" or more explicitly "Excluding L***".
In practice, the main thoroughfare in the town then has 50 km/h and all the others 40 or 30 km/h. The sign for this looks like this: https://commons.wikimedia.org/wiki/File:St_Gerold-town_sign-01ASD.jpg or https://commons.wikimedia.org/wiki/File:Nenzing-town_sign-01ASD.jpg.

In Austria, source:maxspeed=AT:urban40 and source:maxspeed=AT:urban:40 have become established for this purpose.

There should be an exception for both variants.

**Comment by frodrigo** [comment]
> Note: I've messed something up. See https://community.openstreetmap.org/t/osmose-meckert-uber-tempo-50-im-ortsverkehr/5113/

Please, can you provide an english summary.

**Comment by frodrigo** [comment]
> Would the solution be as follows? `'at:urban': ['30', '40', '50', '60'],`

We can do this. But should not b ?
```
'at:urban': ['30', '40', '50', '60'], // or just 50 ?
'at:urban40': 40,
'at:urban30': 30,
'at:urban60': 60,
```

**Comment by frodrigo** [comment]
Done.
