### ISSUE TITLE
Detect too small natural landuse=wood|forest

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1646]
Too small natural landuse=wood|forest are rather natural=tree or other thing.

![image](https://user-images.githubusercontent.com/1785486/201343891-0418c558-653d-4e82-ac95-b8a511c09548.png)
https://www.openstreetmap.org/way/129880985/history

**Comment by Famlam** [comment]
Seems we also got #684 fixed with this (well, the non-dubious cases ;) )

**Comment by frodrigo** [comment]
Not sure why we got no results 
http://osmose.openstreetmap.fr/en/issues/open?item=3100&useDevItem=all

**Comment by frodrigo** [comment]
> Not sure why we got no results http://osmose.openstreetmap.fr/en/issues/open?item=3100&useDevItem=all

http://osmose.openstreetmap.fr/en/issues/open?item=3100&useDevItem=true

useDevItem=all looks broken

**Comment by Famlam** [comment]
I think it is safe to make this item public, based on the results I see.

**Comment by frodrigo** [comment]
Thank. Enabled.
