### ISSUE TITLE
Abandoned railways

### ISSUE THREAD

**Issue by jidanni** [osm-fr/osmose-backend#1652]
https://wiki.openstreetmap.org/wiki/Tag:railway=abandoned  says
> You **may** indicate the type of the abandoned railway with a combination such as railway=abandoned + abandoned:railway=rail/light_rail/subway/tram

But if you don't it raises an issue!
https://www.openstreetmap.org/way/318895434

Okay, then please make the Wiki page say what is needed more firmly.

**Comment by Famlam** [comment]
It's a validator rule imported from https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/validator/openrailwaymap.validator.mapcss

You might want to raise this issue there?

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/en/issue/331860bb-0003-859a-7ae3-d41ce52f648b

Good to report directly to OpenRailwayMap/

I blacklist this rule on Osmose side.

**Comment by frodrigo** [comment]
Class removed from frontend.

Wait few days before closing here, in case of laggy results come.

https://osmose.openstreetmap.fr/en/issues/open?item=9015&class=9015027
