### ISSUE TITLE
tunnel=culvert should have waterway=* as well

### ISSUE THREAD

**Issue by ivanbranco** [osm-fr/osmose-backend#1658]
Hi, 

there's already a general check for the tunnel=* tag (item 9001 class 9001002). I would like to propose to make a more specific rule for one of its values which is tunnel=culvert. The Wiki says "A culvert is a device used to channel water", so I would expect this value to be matched with waterway=* only. At the moment we have 3914 highways tagged with tunnel=culvert ([overpass query](https://overpass-turbo.eu/s/1o2j)).

**Comment by frodrigo** [comment]
9001 rules are from JOSM

https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss

Do you have a specific rule in mind ?

cc @Klumbumbus

**Comment by ivanbranco** [comment]
I would just flag every _way_ tagged with _tunnel=culvert_ which is not tagged with _waterway=*_ as well, so I would expect all these ways to be flagged as an error: [overpass query](https://overpass-turbo.eu/s/1o2D)

**Comment by Famlam** [comment]
E.g. 

```
way[tunnel=culvert][highway][!waterway] {
  throwWarning: tr("{0} together with {1}", "{0.tag}", "{1.tag}");
  group: tr("suspicious tag combination");
}
```

**Comment by ivanbranco** [comment]
> This might be too much. Dried up / former streams can still have culverts

How are dried/former streams mapped?

**Comment by Famlam** [comment]
> How are dried/former streams mapped?

I guess that depends on the visibility in the landscape of the former stream. If it's just an ancient culvert without clear indication of a former stream, I'd only map the remaining culvert. But I'll leave it to @Klumbumbus to decide if - and if so - how he'll add it

**Comment by Famlam** [comment]
Also here: https://josm.openstreetmap.de/ticket/22547

**Comment by frodrigo** [comment]
I close it here as reported directly to JOSM

**Comment by Famlam** [comment]
Has been fixed on the side of JOSM, so we should (soon) update the mapcss rules on Osmose

**Comment by Famlam** [comment]
Rule has been deployed, example issue: https://osmose.openstreetmap.fr/nl/issue/5d2c612f-c13a-04a7-3953-3130fb65cffe
