### ISSUE TITLE
docker-compose build always compile (including unmodified) OH

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1661]
docker-compose build run pip -r requirements.txt
pip -r requirements.txt compile OH every time, even if there has been no change since the previous run.
non-docker slaves have [a script](https://github.com/osm-fr/osmose-backend/commit/11cadbf8f30d8cc3cb58ee7734aca7acd4b2e468) that prevents this when the file has not been modified
this script is not yet used by the docker build, which leads to an often unnecessary recompilation at each docker-compose build

**Comment by frodrigo** [comment]
Not sure to understand what you are doing.

Once re-run `docker-compose build`, it builds nothing if nothing have changed in requirements files.

**Comment by frodrigo** [comment]
After debug, the @Marc-marc-marc docker image have an issue, ldd not found the qt core lib, while still in the image.
Unable to reproduce elsewhere.
