### ISSUE TITLE
no issue for missing properties if traffic_sign:forward=* is used

### ISSUE THREAD

**Issue by tiptoptom** [osm-fr/osmose-backend#1665]
I think, this shouldn't be an issue?

https://osmose.openstreetmap.fr/en/issue/8e0e0928-3b03-17c6-6ad7-d8f2f33c8928

Untagged named object

The object is missing any tag which defines what kind of feature it is. This is unexpected for something with a name tag.

![grafik](https://user-images.githubusercontent.com/73886169/204790330-b610cc78-b1e0-4071-be1b-13bb58fd693c.png)

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/en/issue/8e0e0928-3b03-17c6-6ad7-d8f2f33c8928

Untagged named object

The object is missing any tag which defines what kind of feature it is. This is unexpected for something with a `name` tag.

**Comment by frodrigo** [comment]
Done.
