### ISSUE TITLE
exempt highway=raceway from "One way inaccessible or missing parking or parking entrance" check

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-backend#1667]
`highway=raceway` are often not accessible via clearly defined paths for safety reasons, usually they're fenced in and isolated, so they should be exempted from item 1210. See https://osmose.openstreetmap.fr/en/issue/7d0b9977-058d-6c20-8085-48f8d07505d5 for an example

**Comment by frodrigo** [comment]
Done, Thank @Famlam .
