### ISSUE TITLE
Parking plugin revision

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1672]
It seems that the parking proposal will be accepted on Dec 8; in that case a big revision of the parking plugin is required.
https://wiki.openstreetmap.org/wiki/Proposed_features/street_parking_revision

Perhaps it would be good to disable this plugin for a couple of days between acceptance of the proposal and updating the plugin, so we can await until the wiki is fully up to date again? @frodrigo ?

**Comment by Famlam** [comment]
Nevermind, it seems the plugin will not error with the new syntax, it nicely slips through.
So we can just wait until the new syntax has some usage

**Comment by Discostu36** [comment]
I think that now as the proposal has been accepted and the tags are used, Osmose should highlight the old tags as deprecated.

**Comment by frodrigo** [comment]
Osmose fetch deprecation from this page, it is automatic.

https://wiki.openstreetmap.org/wiki/Deprecated_features

**Comment by Famlam** [comment]
>Osmose fetch deprecation from this page, it is automatic.

Just curious, will it also fetch these ones? `parking:lane` itself isn't a common tag, only `parking:lane:left/right/both` (same for condition)

**Comment by frodrigo** [comment]
> > Osmose fetch deprecation from this page, it is automatic.
> 
> Just curious, will it also fetch these ones? `parking:lane` itself isn't a common tag, only `parking:lane:left/right/both` (same for condition)

Just `parking:lane=*` as on the wiki.

**Comment by Famlam** [comment]
Great!

**Comment by Discostu36** [comment]
The new tagging scheme already has thousands of uses. Could we re-open this for revision of the parking plugin?

**Comment by frodrigo** [comment]
Result here
http://osmose.openstreetmap.fr/en/issues/open?item=3161&class=31621,31622,31623,31624,31625,31626,31627,31628,31629

**Comment by Discostu36** [comment]
You didn't ask for my opinion, but I'll be so frank to give it nonetheless: I think it should be whitelisted for the reasons that you have given.

**Comment by frodrigo** [comment]
I did not really know this subject. So, as you say.

**Comment by Famlam** [comment]
Hmm, on second thought and a bit more research: there's only 59 such conflicting items (`highway=*` + `amenity=parking` + `parking:[unknownside]`) in Europe (and Europe has the highest numbers of parking:fee, parking:access, ...) so I think I'll leave it for now. The warning from TagRemove_Incompatible has a higher priority anyway.
