### ISSUE TITLE
1210 not-connected highway/cycleway / Small highway group apart from the main network or with insufficient access upstream

### ISSUE THREAD

**Issue by fititnt** [osm-fr/osmose-backend#1678]
**Please give a look at https://community.openstreetmap.org/t/1210-not-connected-highway-cycleway-small-highway-group-apart-from-the-main-network-or-with-insufficient-access-upstream/6421 .**

Potentially related issues here:
- https://github.com/osm-fr/osmose-backend/issues/339
- https://github.com/osm-fr/osmose-backend/issues/570
- https://github.com/osm-fr/osmose-backend/issues/1053
- (likely a few others)
---

While I somewhat understand the code behind the query (but not as experienced with OpenStreetMap data model), could someone give a hint on how this could work?

Note that I'm not asking to "correct" or disable  (in fact, neis do not even show this on the count, so this already is less visible) however I'm genuinely interested in know if there is something that could be done in an example like this https://osmose.openstreetmap.fr/pt/map/#zoom=15&lat=1.6492&lon=7.42027&item=1210%2C9xxx&level=1&issue_uuid=9e224030-7fc5-0f61-0d7e-128d7467b7eb (The place does already have an airport, and also a pier (both maybe just miss some tags) and even with some work, it is likely that this place could already have an highway=primary. However I'm curious if at least the airport and the pier may be just missing some tag.)

Thanks!

**Comment by Discostu36** [comment]
This validation rule seems to be really buggy. Take this for example:
https://osmose.openstreetmap.fr/de/issue/a0294c92-42c4-4ce3-63ee-05be45fefd6c

It is connected to a highway=primary:
https://www.openstreetmap.org/way/41212227
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=47.42334%2C9.58764%3B47.41120%2C9.62585#map=14/47.4188/9.6087

**Comment by Discostu36** [comment]
@Famlam Do you want me to open a separate issue?

**Comment by Famlam** [comment]
@Discostu36 That would IMO be preferred yes

**Comment by Discostu36** [comment]
Done: https://github.com/osm-fr/osmose-backend/issues/1679

**Comment by fititnt** [comment]
@Famlam sorry, I'm a bit new to OpenStreetMap, not sure how to connect 😅. I mean I had an issue once of a road over a building, so not sure how to connect this (if I move the road or create another way or something that someone could pass).

But here is the image for https://www.openstreetmap.org/edit#map=19/1.64431/7.42329

![Captura de tela de 2022-12-08 09-23-02](https://user-images.githubusercontent.com/812299/206445867-2242b178-b742-4dbb-b947-b41d9e4722ed.png)


## Question: example of how to connect road to pier?

If there's some example of a pier connected without causing other issues, I think I can understand how it works!

**Comment by fititnt** [comment]
By the way: there's some example of routable airport?? By the documentation, here https://www.openstreetmap.org/edit#map=16/1.6651/7.4128 have an airport, so in theory, like the pier, there's something not connected to allow the validation pass!

Image at the moment

![Captura de tela de 2022-12-08 09-31-07](https://user-images.githubusercontent.com/812299/206447052-f1cbde3b-2ad3-408e-b09b-a87af0a9d1d6.png)

**Comment by Famlam** [comment]
For the airport, I would argue that it's most logical to connect the entrance of the terminal building with i.e. a footway to the road network (since you're typically not able to enter anywhere else), however I see that `aeroway=terminal` is not yet included in the [code](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_floating_islands.py#L44) as an "end point".

Note that for this island the issue should be solved once the analyser has run again (typically within 48h) due to the now connected pier.

**Comment by fititnt** [comment]
Great! The https://github.com/osm-fr/osmose-backend/pull/1680 was even merged. That was fast!

@Famlam so, in this case, would also be a generic small `highway=service` between

```
aeroway=terminal
building=yes
```
and the
```
highway=tertiary
oneway=no
```
?

There is some tag or something to say that the  `highway=service` might be for people (not vehicles) or it would be implicit? I think that even if the airport does accept some type of cargo, in the case of terminal, would be only for people.

![Captura de tela de 2022-12-09 12-28-20](https://user-images.githubusercontent.com/812299/206736185-13e94a98-9fbd-49c7-b464-5d401a8ae9a0.png)

Link for the picture https://www.openstreetmap.org/edit?changeset=129862424#map=19/1.66481/7.41305

This small airport is the IATA:PCP and ICAO:FPPR (https://www.flightradar24.com/airport/pcp, https://metar-taf.com/airport/FPPR)

**Comment by Famlam** [comment]
I'm not familiar enough with the local situation to determine the proper type of road, but probably it's either highway=service (if cars can enter the terminal building too), or else one of highway=footway, highway=path or highway=pedestrian. Please see https://wiki.openstreetmap.org/wiki/Key:highway#Values and links thereon. But I believe that in case of doubt, the question about the road type to use might be more suited for the OSM forum rather than the osmose issue tracker ;)

**Comment by fititnt** [comment]
Thank you all! I also asked colleagues for help and they suggested that `highway=footway` would also be an option in this case.

Now in addition to the `man_made=pier` (it was working before, no issue necessary) now likely to be routable also via aeroway. Fantastic. I will also start to read more about routing in next weeks.

I'll close the issue here! Thanks again!!
