### ISSUE TITLE
 Item 1210 Class 4 only checks for connection inside admin level 4 borders?

### ISSUE THREAD

**Issue by Discostu36** [osm-fr/osmose-backend#1679]
Many ways in [Appenzell Innerrhoden](https://www.openstreetmap.org/relation/1686666) are marked with Item 1210 Class 4: Small highway group apart from the main network or with insufficient access upstream.

## Probable Cause
There is no `highway=primary` inside this canton, and the validation seems not to check outside the canton. 

## Probable solution
Maybe the check should not be confined to admin boundaries, or the admin level should be changed.

## Example
Way: [193971383](https://www.openstreetmap.org/way/807587822)
Issue: https://osmose.openstreetmap.fr/de/issue/a0294c92-42c4-4ce3-63ee-05be45fefd6c

It is connected to a `highway=primary`:
https://www.openstreetmap.org/way/41212227
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=47.42334%2C9.58764%3B47.41120%2C9.62585#map=14/47.4188/9.6087

**Comment by Discostu36** [comment]
In this comment, it sounds as this was deliberate, but I don't agree:

https://github.com/osm-fr/osmose-backend/issues/1361#issuecomment-1001636658

Having to cross a sub-national boundary to get to a primary highway is usually a non-issue and should not be a reason for this warning to show.

**Comment by Famlam** [comment]
@frodrigo I'm thinking along the line of adding something like
```sql
UNION
SELECT
  highways.linestring,
  highways.id
FROM
  relations AS ptrelation
  JOIN relation_members ON
    relation_members.type = 'W'
    relation_members.relation_id = relations.id
  JOIN highways ON
    highways.id = relation_members.member_id
WHERE
  ptrelation.tags!=''::hstore AND
  ptrelation.tags?'route' AND
  ptrelation.tags->'route' IN ('bus', 'trolleybus', 'tram')
```
to sql10, unless you know a way to properly deal with this border issue?

**Comment by frodrigo** [comment]
> In this comment, it sounds as this was deliberate, but I don't agree:
> 
> [#1361 (comment)](https://github.com/osm-fr/osmose-backend/issues/1361#issuecomment-1001636658)
> 
> Having to cross a sub-national boundary to get to a primary highway is usually a non-issue and should not be a reason for this warning to show.

It is not on purpose, but a technical limitation. Data check is done on extract split by on some boundaries.

> @frodrigo I'm thinking along the line of adding something like

I does not se the goal.

Maybe we rather could mark cross border highway also as network seed.

**Comment by frodrigo** [comment]
> That would be the best fix, but there is (as is correct) no node on the crossing of the `admin_level` boundary with the highway, so I'll have to leave this to you to program

Implementation idea : get the border ways from the clipping relation of the extract. The relation ID is in the config of the country. Then add to seed ways, the ones intersecting the borders ones, with `ST_Intersects`.

**Comment by Famlam** [comment]
> Implementation idea : get the border ways from the clipping relation of the extract. The relation ID is in the config of the country. Then add to seed ways, the ones intersecting the borders ones, with ST_Intersects.

Thanks! With that I can give it a try myself if you wish, but it'll probably be next week weekend earliest. Busy days ahead... (and no guarantee I'll succeed, I'm still a rookie in SQL).

**Comment by frodrigo** [comment]
Yes, I give the idea here because  I am also short on free time.

**Comment by jocelynj** [comment]
Some country extracts doesn't have the full relation for the country ID (mostly on geofabrik side). Could it cause an issue? Must we fix these extracts first?
They can be found by looking at `python -m tools.check-boundary-polygon`

**Comment by frodrigo** [comment]
> Some country extracts doesn't have the full relation for the country ID (mostly on geofabrik side). Could it cause an issue? Must we fix these extracts first? They can be found by looking at `python -m tools.check-boundary-polygon`

Yes. It could be good to have a ralition id for each area.

Note some area can use multiple relation ids.

**Comment by fititnt** [comment]
> Yes, I give the idea here because I am also short on free time.

It's a great project!

I do know the software stack and eventually could help on this kind of issue! Might take some time, but I'm slowly looking into the tools (in special ones related to either schema or validation), and for now mostly looking into how to convert files into RDF. The ones for validation/syntax check seems better SHACL+basic inference as it is easier to write focused rules (SQL rules is not a viable automate, but other kinds of file beyond the ones from name-suggestion-index/id-tagging-schema/JOSM presents might be convertible).

But as much as I could be helpful in near future, this issue with routing in particular, I suppose the challenge would be how to fix this type of warning without degrading performance (and solutions for this one already are likely to cause to cause problems). Maybe is not as bad I as imagine, but does not seems to be SQL query, but how to prepare data before run the queries. And the way osmose works, I will assume it would be very sensible to a change on this.

Sorry to not be helpful at short term, but I can understand this one is hard beyond what it seems. Even if you don't plan to touch this (and priorize other things), I think still relevant comment at hypothetical ways to do it.

**Comment by Famlam** [comment]
> Some country extracts doesn't have the full relation for the country ID (mostly on geofabrik side). Could it cause an issue? Must we fix these extracts first? They can be found by looking at `python -m tools.check-boundary-polygon`

I cannot run this script as I get `ModuleNotFoundError: No module named 'pwd'` (`pwd` is Linux specific) 
Can someone run this for me and give me an example extract with an incomplete relation? Then I can run the analyser on that country, see if it gives errors.

**Comment by frodrigo** [comment]
You can check poly report from last night https://github.com/osm-fr/osmose-backend/actions/runs/3718406824/jobs/6306584148

**Comment by jocelynj** [comment]
For the check-boundary-polygon, log can be found on https://github.com/osm-fr/osmose-backend/actions/runs/3718412767/jobs/6306595024#step:6:20

The interesting lines are the one like `Error(albania) poly inside boundary (r_id=53292, poly=http://download.geofabrik.de/europe/albania.poly)`

**Comment by Famlam** [comment]
Thanks both! The 'regular' countries look OK.
- running on usa_texas_central: bad reports like https://www.openstreetmap.org/way/20963608 are gone.
- running on albania: 618 of the original 621 ways remain, the other 3 were like https://www.openstreetmap.org/way/441164526
- running on slovenia: all but 2 of the ways remain, the other two were like https://www.openstreetmap.org/way/1008100633
- running on antarctica: 119 out of 119 remain

So I would say the new results look fine, even for "bad" / "special" extracts :)

**Comment by frodrigo** [comment]
Thank for implementation and the tests.
I even guess it will be faster.

**Comment by Famlam** [comment]
https://osmose.openstreetmap.fr/de/issues/graph.png?source=418620&item=1210&class=4

Problem solved ;) @Discostu36  thanks for reporting!

**Comment by Discostu36** [comment]
Thanks for fixing 👍
