### ISSUE TITLE
outer with (linear) tag + mono-outer MP relation with other (area) tag

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1681]
http://osmose.openstreetmap.fr/fr/issue/45e768f0-97d9-9dd3-01ab-03a37b7adb25
item 1170
class 11704
en This multipolygon is a simple polygon
en Multipolygon relation actually defines a simple polygon.
https://www.openstreetmap.org/way/252115086  barrier=fence -> describe a linear feature
this way is the (only) (outer) member of the relation https://www.openstreetmap.org/relation/6089345 landuse=meadow -> describe an area feature

indeed it's a simple polygon but due that the reality have 2 things ( a linear barrier and an area landuse), this usecase describe 2 features thus 2 objects in osm

**Comment by frodrigo** [comment]
I think the reported issue is right. You can move  `landuse=meadow` ti the way.

**Comment by Marc-marc-marc** [comment]
this would create two problems :
- you describe 2 things on one osm object, contrary to the rule "1 thing = 1 osm object"
- you have a mixed linear+array object, have a lot of tinkering with the data to try to guess what to do with it

**Comment by frodrigo** [comment]
> you describe 2 things on one osm object, contrary to the rule "1 thing = 1 osm object"

A fenced field = 1 object for me.

>  you have a mixed linear+array object, have a lot of tinkering with the data to try to guess what to do with it

Both, its depends on how you look at it. Not an issue for me.

**Comment by Famlam** [comment]
I agree that it's a valid warning (no multipolygon here, it's a single-object polygon) although I would probably map the fence as a separate way (fence = 1 object, and field = one object). (The fence probably has an entrance where it's interrupted, a field not). And if you split the fence at the gate without removing the MP first, you suddenly have your multipolygon with multiple 'outer' roles ;)
