### ISSUE TITLE
Exempt power=plant relations from Large relation check

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-backend#1683]
According to the wiki here: https://wiki.openstreetmap.org/wiki/Tag:power=plant some wind, solar, and hydro power plants use `type=site`+`power=plant`, and they are often spread across a large area, which flags them as a large relation, for example http://osmose.openstreetmap.fr/en/issue/5e83ffec-fe9a-eac1-9762-bd996bb9d305

**Comment by frodrigo** [comment]
You can flag exception as a false positive.

**Comment by frodrigo** [comment]
It is not about power, but exceptional large site.

**Comment by Famlam** [comment]
I did a little counting experiment.
- I opened the first 244 of the 1734 `type site` [issues](https://osmose.openstreetmap.fr/nl/issues/open?item=1160&limit=10000) and all 104 `type site` false positives. This is **18.9%** of all "large relation" issues for `type=site` relations
- 22 of the false positives involved `power=plant` + `plant:source=wind`; 106 of the first 244 `type site` issues involved `power=plant` + `plant:source=wind`. So total 128 wind parks. Assuming the 18.9% was representative, that means that if I opened 100% of the Osmose issues for `type=site`, I would have had **677** relations. 
- The majority of those seem to be correctly mapped
- There are **6564** relations with this tag combination in total on OSM. This means that about **10%** of all wind farms are incorrectly flagged as "big relations". 

Hence I think it might warrant a whitelist as it's pretty common for wind farms to be really big?
I mean, if I google it, I find that optimal wind-mill spacing in a wind park is about 500 meters (e.g. https://sciencing.com/places-wind-turbines-produce-electricity-5159049.html ), so for big parks you should easily get a "large relation": even the north sea alone contains multiple of over 100 mills

**Comment by frodrigo** [comment]
@Famlam ok,. Thank for digging into this. I a ok to withlist `power=plant` + `plant:source=wind`.

**Comment by Famlam** [comment]
> @Famlam ok,. Thank for digging into this. I a ok to withlist `power=plant` + `plant:source=wind`.

PR ready :) ! Tested on netherlands_flevoland, results look fine. (I neglected the `construction:power=plant` ones, those can be marked as false positives (which I'll do now ;) ))

**Comment by Famlam** [comment]
Seems to have removed about 800 relations based on the graph :)
https://osmose.openstreetmap.fr/nl/issues/graph.png?item=1160&start_date=2022-10
