### ISSUE TITLE
Local language should not be level 1 item in the United States

### ISSUE THREAD

**Issue by 1ec5** [osm-fr/osmose-backend#1692]
The “Default and local language name not the same” item should not be a level 1 major item in the United States.

## Background

The [United States](https://www.openstreetmap.org/changeset/58691705) boundary relation was tagged `default_language=en` [in 2018](https://www.openstreetmap.org/changeset/58691705). This is reasonable, because English is indeed the primary language for most purposes in most places. However, there is generally [no official language](https://en.wikipedia.org/wiki/Languages_of_the_United_States#Official_languages) in the country. Even in states that have an official language, this only protects the right of English speakers to use the English language, but preventing the use of other languages would be an unconstitutional violation of free speech. Indeed, while English is the official language of Indiana, [this town](https://www.openstreetmap.org/user/Minh%20Nguyen/diary/47362) names its streets primarily in German. Despite the official status of English in California, there are huge swaths of Los Angeles and Orange County where English is nowhere to be found on shop signs.

## Problem

Even if Osmose honors `default_language` on state and municipal boundaries, there’s still the problem that immigrant communities use languages other than English in places that do not neatly correspond to administrative boundaries. Moreover, it’s common for ethnic enclaves to use English for some purposes like government buildings and streets but for not other purposes like shops and places of worship.

For example, [this Vietnamese-speaking church](https://www.openstreetmap.org/way/746282501) is surrounded by streets named in English. [This Spanish-named Mexican restaurant](https://www.openstreetmap.org/node/6515611001) shares a building with shops named in two other languages. Both are reported as level 1 issues ([dd7b75eb-6f07-f05c-5416-d18beff42f71](https://osmose.openstreetmap.fr/en/issue/dd7b75eb-6f07-f05c-5416-d18beff42f71), [24e3d5f5-ecad-7876-3e2d-425bf15f4473](https://osmose.openstreetmap.fr/en/issue/24e3d5f5-ecad-7876-3e2d-425bf15f4473)).

## Proposed change

There may still be some value to flagging a language mismatch, in case a mapper neglects to update a `name:en` after updating `name` and some other name tag still matches. But this should be a less important issue, maybe even level 3.

**Comment by frodrigo** [comment]
First, thank you for a such good and detailed issue report!

Osmose does not use `default_language`. It have it own configuration. Osmose does not check for official languages, but for mapping languages.
Eg. https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L872

In Osmose we can configure one or many languages for an area. We can also configure multilingual area, like Brussels.

But as I understand what your describe, none of this fit your issue.

We can also disable the check for US, at country level, at state or sub state level (when slit in Osmose).

**Comment by frodrigo** [comment]
I disabling this rule for USA.
Keeping the language configurable still available for other checks.

**Comment by 1ec5** [comment]
Thanks, and apologies for the belated response. I agree with the change. It could make sense to define more granular multilingual areas, such as the indigenous reservations that are already labeled in two languages. But most would be much smaller than the state level, for example a city or even a neighborhood. Perhaps this would be too granular to be worth Osmose’s resources.

**Comment by frodrigo** [comment]
Deployed and data cleaned.

**Comment by 1ec5** [comment]
Thank you!
