### ISSUE TITLE
aeroway=parking_position causes false positives

### ISSUE THREAD

**Issue by aighes** [osm-fr/osmose-backend#1694]
Hello,

there seems to be an issue (false positive) in item: 4090 - unwanted tag on node for `aeroway=parking_position` Based on it should be used on the way the plane takes as well as for the actual stop position node. https://wiki.openstreetmap.org/wiki/Tag:aeroway=parking_position
Would be great this false positive can be excluded. 

For example: https://osmose.openstreetmap.fr/map/#username=aighes&item=4090&item=4090&zoom=17&lat=31.1692434&lon=121.8029762&level=1&tags=&fixable=&issue_uuid=571dbafc-67ae-68ce-f69b-44f4649190f5

**Comment by Famlam** [comment]
Are you sure this is intended to be on the node **and** way simultaneously? Based on how I read the wiki it seems like it should be either the node or the way. (Like most other items that can be mapped as node or way)

Item 4090 class 1
