### ISSUE TITLE
Cars can go down steps?

### ISSUE THREAD

**Issue by jidanni** [osm-fr/osmose-backend#1695]
![Screenshot_20221215-133319_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/207972412-266145c2-2d40-4c71-9e54-903559b89ffb.jpg)
Tags were:

```
access=permissive
bicycle=no
foot=yes
highway=steps
incline=down
```

If we have to enumerate every single possible item, then people won't bother with the hassle and nobody will use https://wiki.openstreetmap.org/wiki/Tag:access%3Dpermissive .

**Comment by Famlam** [comment]
What's your question exactly? Who are allowed to use these steps? If only pedestrians, you should use foot=permissive, not access=permissive.
(Assuming permissive is correct)

If only foot and cars, then use motorcar instead of access. If all motor_vehicles are allowed (including 2-wheeled ones) use that key

**Comment by frodrigo** [comment]
Osmose details about this issue says:

> The tags `access=yes` and `access=permissive` mark a feature as wide open to all transport modes. \
This is almost never the case and more specific tags should be used instead. \
For further detail, see [the wiki](https://wiki.openstreetmap.org/wiki/Key:access#Transport_mode_restrictions).

On the wiki we have:

> In practice, this combination is often used by mappers to modify (rather than enlarge) default values: for example, access=[permissive](https://wiki.openstreetmap.org/wiki/Tag:access%3Dpermissive) with [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=[steps](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps) is very unlikely to be traversable by a truck, whatever the tags may say.

> To avoid ambiguity, you may therefore want to avoid general tags access=[yes](https://wiki.openstreetmap.org/wiki/Tag:access%3Dyes) and access=[permissive](https://wiki.openstreetmap.org/wiki/Tag:access%3Dpermissive), and use more specific transport modes where appropriate. For example, to distinguish a [foot](https://wiki.openstreetmap.org/wiki/Key:foot)way with open access from one with private access, use tags like foot=[yes](https://wiki.openstreetmap.org/wiki/Tag:foot%3Dyes) instead of access=[yes](https://wiki.openstreetmap.org/wiki/Tag:access%3Dyes).

**Comment by jidanni** [comment]
OK, I fixed it:
foot=permissive
highway=steps
Thanks.
