### ISSUE TITLE
Split USA-Georgia

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1698]
Need a layout

Georgia has 159 counties. https://en.wikipedia.org/wiki/List_of_counties_in_Georgia

- Georgia State Patrol, 9 slices, https://en.wikipedia.org/wiki/Georgia_State_Patrol

**Comment by jocelynj** [comment]
For Georgia, I think that the State Patrol split some counties in two different slices - to be checked.

I had found this possible split too: https://georgiafbla.org/about/regions/

**Comment by frodrigo** [comment]
> For Georgia, I think that the State Patrol split some counties in two different slices - to be checked.

I do not see where it could be.
