### ISSUE TITLE
missing words in dictionnary

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1708]
French words 'évêque' and 'abîme' should be added to dictionary to avoid false positives.
Maybe it's a problem of accents.

**Comment by frodrigo** [comment]
Yes it is about accent. And should be fixed as recommended by Osmose.

**Comment by iiitomo** [comment]
My bad, wrong screenshot. Please check the one below.

![IMG_20221223_082419](https://user-images.githubusercontent.com/58949423/209452391-04701112-bdad-4a3f-811b-077c0d214e47.jpg)
