### ISSUE TITLE
word 'abîme' to be added to dictionnary

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1709]
French word 'abîme' should be added to dictionary to avoid false positives.
Maybe it's a problem of accents.

![IMG_20221223_082419](https://user-images.githubusercontent.com/58949423/209452441-4abd8d9a-b32d-4479-a1c7-4f8c7fa23d80.jpg)

**Comment by frodrigo** [comment]
Please use link in place of image, clickable and less resources required.
https://osmose.openstreetmap.fr/fr/issue/d0eea856-a457-046e-41ea-c79f409382ae

**Comment by frodrigo** [comment]
Add abîme and more words from false-positives in French dictionary.
