### ISSUE TITLE
Detect 8-shaped multipolygons

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#171]
Multipolygons where rings meet are ambiguous and can cause rendering issues.

Osmose should detect end nodes in ways in a multipolygon that don't belong to exactly two ways.

**Comment by frodrigo** [comment]
There is already a check about invalid polygon:
http://osmose.openstreetmap.fr/fr/errors/?item=1040
But not for multipolygon, yet.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=1040&class=2
