### ISSUE TITLE
Lane number included causes error 

### ISSUE THREAD

**Issue by jidanni** [osm-fr/osmose-backend#1714]
https://www.openstreetmap.org/node/8535428307#map=19/24.17715/120.72289 has an error about no street name. But the lane number is included so it is even better...

**Comment by Famlam** [comment]
https://osmose.openstreetmap.fr/nl/issue/7c5f0230-16a3-c1fe-aee4-671a6c495f52

Item 2060 class 19

**Comment by Famlam** [comment]
The `addr:street` tag of the address doesn't seem to match any `name=*` of the nearby roads, that's why it's giving the warning. What is wrong here?

**Comment by Famlam** [comment]
Correction: clicked the incorrect balloon...
https://osmose.openstreetmap.fr/nl/issue/c18a780c-255d-cd9a-61b0-bd268b631fec
Item 2060 class 19

`addr:street = 和順路426巷` (from the address)
`name = 何順路426巷` (from the street)

The first character differs

**Comment by jidanni** [comment]
Wow, indeed you found an error that was caused by me! This is a pretty sharp tool!
