### ISSUE TITLE
Issue suggestion: highway=crossing 's that aren't on a way

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-backend#1715]
I noticed after making an overpass query that there were multiple instances (60 nodes) of crossings that aren't connected to ways. 
Example: https://overpass-turbo.eu/s/1pu7
Flanders, Belgium has 60 of these nodes. I don't know about other regions.

![Screenshot_997](https://user-images.githubusercontent.com/1010226/209868531-ac1970ee-e8cd-462c-8302-9e456b8e16c9.png)

Might be useful to have this as an issue in osmose

**Comment by frodrigo** [comment]
Yes. But we already have it

http://osmose.openstreetmap.fr/nl/map/#item=7090&class=3&zoom=12&lat=51.23&lon=4.4147&level=1%2C2%2C3
