### ISSUE TITLE
Add a test for traffic_signals=* - less specific or undocumented values

### ISSUE THREAD

**Issue by rskedgell** [osm-fr/osmose-backend#1717]
Would it be possible to add a test for some values of traffic_signals=*, e.g.

traffic_signals=signal
From the wiki: "Since this kind of signal is assumed for highway=traffic_signals, please choose a more specific value for a more specialized signal."

traffic_signals=crossing
Not documented in the wiki, but more specific values are: level_crossing, pedestrian_crossing, cyclist_crossing

https://wiki.openstreetmap.org/wiki/Key:traffic_signals

**Comment by Famlam** [comment]
Personally I fully agree with taylor.smock at https://josm.openstreetmap.de/ticket/22611 that there is no warning needed.
For me, traffic_signals=signal implies "standard traffic signal". The wiki explicitly says: "please choose a more specific value **for a more specialized signal**." So it is a fine value for a normal signal, as far as I read it.
