### ISSUE TITLE
Split Nigeria - osmosis_building_overlaps

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1720]
https://en.wikipedia.org/wiki/Subdivisions_of_Nigeria

```
[out:csv(::id,name)];
relation(192787);
map_to_area -> .a;
relation(area.a)[admin_level=4];
out;
```

```
3698564	Yobe
3703236	Jigawa
3706956	Zamfara
3707368	Sokoto
3707933	Kebbi
3709353	Kaduna
3710302	Kano
3711481	Katsina
3713501	Abia
3715359	Akwa Ibom
3715505	Anambra
3715844	Bayelsa
3716076	Benue
3716250	Cross River
3716950	Delta
3717071	Ebonyi
3717119	Edo
3717154	Ekiti
3717212	Enugu
3717259	Federal Capital Territory
3717825	Imo
3717971	Kogi
3718090	Kwara
3718182	Lagos
3718384	Niger
3718463	Ogun
3718605	Ondo
3718720	Osun
3720358	Adamawa
3720422	Gombe
3720495	Nasarawa
3720554	Oyo
3720611	Plateau
3720743	Rivers
3720850	Taraba
3721167	Borno
3722233	Bauchi
```

**Comment by jocelynj** [comment]
There might be another issue with this country, as the pbf file is not that bigger compared to other countries in Africa. Stats is showing that "osmosis_building_overlaps" and "osmosis_highway_vs_building" take a very long time:
```
    4:06:31   osmosis_building_overlaps
    2:07:53   osmosis_highway_vs_building
    1:56:10   import osmosis data
    1:18:21   sax
    0:58:37   import osmosis post scripts
```
(with 12 hours for this specific run)

Could we be missing indexes on these two analyses? Or is the OSM data completely incorrect in Nigeria?


In addition, could we use these zones instead?  https://en.wikipedia.org/wiki/Geopolitical_zones_of_Nigeria

**Comment by frodrigo** [comment]
Yes, there is an issue with the query in change mode. It may takes 20s or 3h on the same backend. I do not got a full run to get the value.

I may affect other countries.

**Comment by frodrigo** [comment]
Even after fixing osmosis_building_overlaps, Nigeria take 9h.
I think we can split it anyway?

**Comment by jocelynj** [comment]
I agree that we should split Nigeria. Can we use the 6 Geopolitical zones from my link?

**Comment by frodrigo** [comment]
```
north_central,3716076,3717259,3717971,3718090,3718384,3720495,3720611
north_east,3698564,3720358,3720422,3720850,3721167,3722233
north_west,3703236,3706956,3707368,3707933,3709353,3710302,3711481
south_east,3713501,3715505,3717071,3717212,3717825
south_south,3715359,3715844,3716250,3716950,3717119,3720743
south_west,3717154,3718182,3718463,3718605,3718720,3720554
```

**Comment by jocelynj** [comment]
Diffs are now under generation on http://download.openstreetmap.fr/replication/africa/nigeria/

**Comment by jocelynj** [comment]
Nigeria is now split.
