### ISSUE TITLE
Access way to parking not required for some new parking=* values

### ISSUE THREAD

**Issue by rskedgell** [osm-fr/osmose-backend#1722]
The recent revisions of street parking tags introduced several new values for parking=*.

Some of these are typically parallel to a highway, like the existing parking=street_side and parking=lane, so should not require an access way for routing. This would apply to parking=on_kerb, parking=half_on_kerb and parking=shoulder.

Wiki edit by @Supaplex030 introducing these new values on 2022-12-09:
https://wiki.openstreetmap.org/w/index.php?title=Key:parking&oldid=2447798

**Comment by Famlam** [comment]
Just my curiosity, but how would these be mapped separately? Are there like markings half on the sidewalk - half on the road in some countries? There must be something physical in order to be mapped as a separate object (e.g. with amenity=parking), instead of as property of the way itself

**Comment by Famlam** [comment]
Lets see if it'll actually get used now it's documented.
Currently there's only 76 instances with such a tag worldwide (didn't check how many of those are tagged with `amenity=parking` rather than a mistagging of `parking:both=*kerb` on a `highway=*`)

**Comment by rskedgell** [comment]
@Famlam Thanks, that sounds reasonable. Hopefully we won't get many people adding highway=service ways to connect these to the highway, which was quite common before parking=street_side was accepted and these areas were all mapped as parking=surface.

**Comment by frodrigo** [comment]
More than 6 month later the number of object i still very low :
- [shoulder](https://taginfo.openstreetmap.org/tags/parking=shoulder) 42
- [on_kerb](https://taginfo.openstreetmap.org/tags/parking=on_kerb) 156
- [half_on_kerb](https://taginfo.openstreetmap.org/tags/parking=half_on_kerb) 75

I'm in favour of doing nothing.

**Comment by rskedgell** [comment]
@Famlam Agreed, take up has been very low, so I'm happy to close this and only revisit the issue if a problem actually occurs and it looks like osmose may have been a factor. (Apologies for taking so long to reply.)
