### ISSUE TITLE
false positive for typo detection: area

### ISSUE THREAD

**Issue by kcwu** [osm-fr/osmose-backend#173]
http://www.openstreetmap.org/node/3707766597 is area=yes
osmose says it is "Typo in tag" and suggests it should be "Area=yes".

But according to http://taginfo.osm.org/search?q=area, count(area) is 825279 while count(Area) is only 165.
Even for Taiwan region, area is still more than Area. http://taginfo.osm.kcwu.csie.org/search?q=area

**Comment by frodrigo** [comment]
The stats are done by object kind. So there is 1 "area" but 54 "Area" for nodes in Taiwan.

**Comment by kcwu** [comment]
Thanks for your quick response. I will fix them.
