### ISSUE TITLE
Validator Bug: All buildings on agricultural lands suddenly reported as being an 'inside' problem

### ISSUE THREAD

**Issue by sekerob** [osm-fr/osmose-backend#1731]
My level 3 list, (serious issues), was hit with 450 or so buildings inside agricultural/farming lands. sheds, barns, farm_auxiliary etc. A quick check lists another **331,535** or so https://osmose.openstreetmap.fr/en/issues/open?item=1310. 

Our living quarters are smack in the middle of a 3000 or so olive tree covered slope. Should I now tag buildings with an inside role and turn a simple polygon(SP) into a multipolygon(MP) or start mapping 2 lines parallel to the driveway and around the house to revising the SP outline and that for all the houses on the plot? How now to map/tag forward on?

BTW my 'urgent' Osmose level 3 repair list also got expanded recently by 1K lines or so of 'deprecated' parking xyz flags because of a new parking schema. I would propose to revise the flag rule to only flag these to _individual mappers_ if the the object is revised AFTER the new schema went into effect, any revised schema. 

The Individual mapper issue list found  e.g. at https://osmose.openstreetmap.fr/en/byuser/user?level=3 is restricted to 100 line items which causes for the 'real' new issues from the previous day mapping to be obfuscated.

Anyway, it's beyond me what the rationale and considerations were to introduce this QA check.

**Comment by Marc-marc-marc** [comment]
> living quarters



> Our living quarters are smack in the middle of a 3000 or so olive tree covered slope

our living quarters isn't an landuse=faarmalnd, it should exist a small farmyard or residential landuse arrounnd our living quarters.

**Comment by sekerob** [comment]
To follow up on how baffling this is, [seemingly] buildings on simple polygons of agricultural land are flagged, which is how I mostly do farming lands, buildings on multipolygon agricultural land are not. There must be millions upon millions around the OSM world map. And to top it off, not all buildings either, such as here https://www.openstreetmap.org/way/41839510 is flagged but not the others right around. Maybe another mapper got teed off and hit the X to ignore before me revisiting the issue, but as you can see on the adjacent farmland MP there are many buildings mapped without (artificial) areas around them. https://www.openstreetmap.org/way/41716299#map=16/48.4230/0.5072

Someone needs to present the 'rational' of why mappers have to do this and why [seemingly] on SPs and not on MPs. The top mapper of those flagged has 35000 to the name and the one close to me, Italy_veneto, 10,974. Can't see this 'ever' to change , so a reality check may be called for.

**Comment by frodrigo** [comment]
> not all buildings

To limit the reports, only the largest ones are reported

> buildings on multipolygon agricultural land are not

It is not implement (yet?)

@Famlam what do you think about this feedback ?

**Comment by Famlam** [comment]
> And to top it off, not all buildings either, such as here https://www.openstreetmap.org/way/41839510 is flagged but not the others right around.

Besides what Frodrigo says about the size restriction, there is also the restriction of (on purpose) only reporting 1 building per farmland, to avoid flooding the map with many issues. It is likely that someone who reshapes the farmland will check the entire farmland area anyway, and if not (i.e. if only solved for one building), the error will just re-appear for another building the next time the analyser runs.

> It is not implement (yet?)

It's indeed not implemented yet if you have a relation with `type=multipolygon+landuse=farmland`. It's just more complicated to do this check, as you would have to test that it's inside the "outer", but outside nor crossing each of the "inner"s, and a MP may consist of multiple outers that together form an area. It's not a bug, just an enhancement to increase the coverage of the check. Note that it will work for `inner` ways as there the tags are on the way itself.

@sekerob I still fail to see where we report anything that doesn't adhere to the wiki? Those huge landuses you give as example should probably all get split up in smaller landuses that actually only contain the farmland, not the roads, buildings, .... `landuse=farmland` represents the actual landuse (i.e. where crops are grown, a well defined border), not like `landuse=residential` which represents an "area where living is the most common usage". So is this just a feature request to implement it for MP too?

p.s. there's not millions of MP with this tag; there's 448 663 MP with landuse=farmland worldwide, compared to nearly 8 million ways :)

**Comment by sekerob** [comment]
@Famlam 

I was talking about millions of buildings, and yes, I've been parcelling everything, this adjacent sample just happening to be near where I got flagged after correcting something which makes one owner of all the other problems too and attempting to understand the, on face, inconsistency.

Knowing of whole valleys across the mountain that area mapped as giant farmland areas w/o any distinction or subdivision, orchards, vineyards too since one plot has apples, the next oranges and the next peaches, one red, one white not to speak of the different flavours of olives.

I asked for the logic and rational but as yet not found the wiki that tells what that is and what's in that wiki's. Writing up the 'this is how it must be done' is not rational.

Good to know btw it affects farmland only going by your words, 3/4 here is vineyard and orchard and meadow, although the Osmose flag speaks of 'agricultural' land which is all of the above.

Thanks for telling.

**Comment by Famlam** [comment]
> I was talking about millions of buildings, and yes, I've been parcelling everything, this adjacent sample just happening to be near where I got flagged after correcting something which makes one owner of all the other problems too and attempting to understand the, on face, inconsistency.

You know, you're not responsible for every error just because you're the last modifier :)

> Good to know btw it affects farmland only going by your words, 3/4 here is vineyard and orchard and meadow, although the Osmose flag speaks of 'agricultural' land which is all of the above.

No, it also affects vineyard, orchard, plant nurseries, I used farmland as an example just like you did.

> I asked for the logic and rational but as yet not found the wiki that tells what that is and what's in that wiki's. Writing up the 'this is how it must be done' is not rational.

The wiki says that landuse=farmland (or the others) it's the area where crops / plants / ... grow. So that's pretty clearly not the residential areas where you live. Also the wiki clearly says when to use farmyard instead of farmland for agricultural buildings. That's the rationale

**Comment by sekerob** [comment]
As to the wiki I found https://wiki.openstreetmap.org/wiki/Tag:landuse=farmland, it makes the 'assumption' that all buildings of farmers are on a farmyard or as is custom in many places a score of farmyards grouped together in a village often then outlined as residential area, with loose individual barns/roofs sprinkled around far and wide.

BTW, greenhouse horticulture areas have greenhouses on them tagged as a building type, they're flagged too. I'm pretty sure produce grows in them ;o).

Anyway, you may open the round archive and drop this topic in.

ciao

**Comment by Famlam** [comment]
I quote from the wiki:
> See the tag [landuse](https://wiki.openstreetmap.org/wiki/Key:landuse)=[farmyard](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfarmyard) instead to tag areas of land with farm buildings like farmhouses, dwellings, farmsteads, sheds, stables, barns, equipment sheds, feed bunkers, etc. plus the open space in between them and the shrubbery/trees around them.

Also, 
> [landuse](https://wiki.openstreetmap.org/wiki/Key:landuse)=[greenhouse_horticulture](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dgreenhouse_horticulture) - Land area used for growing plants in greenhouses

**Comment by sekerob** [comment]
@Famlam

Off Topic, v.v your note of "You know, you're not responsible for every error just because you're the last modifier :)", on your issue page listing header it prints since years

"This doesn't _means_ that this user is responsible for all these issues."

Think 'means' should be 'mean'

ciao
