### ISSUE TITLE
waste_disposal capacity in m3 should be a valid decimal value

### ISSUE THREAD

**Issue by carlosarc87** [osm-fr/osmose-backend#1733]
Invalid capacity value
"capacity" value X is not an integer

item: 3091
class: 30912

[Tag:amenity=waste_disposal](https://wiki.openstreetmap.org/wiki/Tag:amenity=waste_disposal): 
[capacity](https://wiki.openstreetmap.org/wiki/Key:capacity)=* - to specify the capacity in m³.

Examples:
http://osmose.openstreetmap.fr/es/issue/a812063f-771a-38c7-4a4f-5fd1b3f4986a
http://osmose.openstreetmap.fr/es/issues/open?source=425432&item=3091&class=30912

Regards

**Comment by Famlam** [comment]
Indeed. It should be excluded in https://github.com/osm-fr/osmose-backend/blob/master/plugins/Capacity.py#L53 as it can be non-integer

**Comment by carlosarc87** [comment]
Thank you so much, it seems to be working.
I am sorry, but I forgot to include amenity=recycling, that has the same problem.
I hope you can add it when it is possible.
Regards

**Comment by Famlam** [comment]
Hmm, `capacity` is used 7k times with that key, but not documented on the wiki. 
Could you update the wiki please? https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling#Useful_combinations

**Comment by carlosarc87** [comment]
The wiki was updated by other user a few minutes ago, regards

**Comment by Famlam** [comment]
Thanks! I'll let it sit for a couple of days in case someone disagrees with the wiki change and then update the code :)

**Comment by Famlam** [comment]
Not sure what I messed up in the first two attempts, but third PR seems to be ok :). Sorry for the PR-spam :)

**Comment by carlosarc87** [comment]
I have checked that it is fixed, thank you so much.
Regards
