### ISSUE TITLE
Default and local language name not the same in Sardinia

### ISSUE THREAD

**Issue by Tepepaz** [osm-fr/osmose-backend#1735]
I'm getting a lot of complaints from osmose about the mismatch between the default name= tag and the name:it= tag.

https://osmose.openstreetmap.fr/en/map/#zoom=9&lat=39.788&lon=9.157&item=5030%2C5060&level=1%2C2%2C3&username=&country=italy_sardegna&source=&class=

Items #5060
As you might already know, while Sardinia is part of Italy, here many names, even officially are kept in the original local (Sardinian) version. As long as Sardinian is considered a language, not only by linguists and the Italian government but also in OSM, in my opinion, it would be correct to whitelist the name:sc (and perhaps even loc_name and reg_name) tags to be compatible with the main name tag.

Itemes #5030
On other occasions, toponyms should have dual languages, and even in this case osmose does not accept it.

Here you can find the official guidelines
https://wiki.openstreetmap.org/wiki/Multilingual_names#Sardegna_(Sardinia)

**Comment by frodrigo** [comment]
We configure this Osmose here
https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L1559
as we already do for other multilingual area.

It will disable this kind of check.

Should we have to configure it as ['it', 'sc'] or ['it', 'sc', 'ca', co'] ?

As second step, we can enable multilingual checks.
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_Multilingual.py
If is exists a clear an consistent rule.

**Comment by Tepepaz** [comment]
Thanks for your reply. I would say that we should add all the languages spoken in Sardinia so ['it', 'sc', 'ca', 'co', 'lij'] to be fair to minorities too. This would be already helpful to declutter some pins from Sardinia.

What is the multilingual check going to check against? Naming a place or an object with more than one language is not mandatory nor necessary in Sardinia. There are a few places that do not have this possibility at all.
If it only checks that when a multilingual name is written, there are also all the single languages specified, it would be nice to have.

**Comment by frodrigo** [comment]
Multilingual check consistency between main name and locales names. There is no global standard way of doing this. A new rules should probably be implemented for Sardenia.

**Comment by Tepepaz** [comment]
> Multilingual check consistency between main name and locales names. There is no global standard way of doing this. A new rules should probably be implemented for Sardenia.

I wouldn't bother doing that as there is no stardard way of writing Sardinian. Locally everybody writes names according to their local Sardinian variant.

**Comment by frodrigo** [comment]
Configured. Will be live in few days.
