### ISSUE TITLE
Update or replace TagwatchCleaner

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1736]
The wiki page used in https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagWatchFrViPofm.py has been moved:
https://wiki.openstreetmap.org/w/index.php?title=User:FrViPofm/TagwatchCleaner&action=history
(Hence the tests are failing)

Is this list still being used? (And if so, isn't it better to have it as mapcss file, as far as it's not yet covered by i.e. JOSM?)

**Comment by frodrigo** [comment]
Yes. It still used and contains the most simplest cases.

It could be converted to mapcss. But I think it's should keep the more simplest forme it could have, for larger editor audience.
