### ISSUE TITLE
Validator issue: `turn` order check needs some optimization, when bicycle lanes are involved

### ISSUE THREAD

**Issue by sun-geo** [osm-fr/osmose-backend#1739]
It seems the checks for the `turn` order are working well for standard cases.

If there are bicycle lanes included the rules give false positives

Example osm way: 
https://www.openstreetmap.org/way/49600780

The object has tags like:
`lanes=2`
`bicycle:lanes=no|no|designated`
`vehicle:lanes=yes|yes|no`
`turn:lanes=left;through|through;right|through;right`

Don't be confused, because `lanes` only counts lanes for motorizes traffic (without bicycle lanes) and `turn:lanes` includes also turns for bicycle lanes, which are defined by `bicycle:lanes`

The double **through;right**|**through;right** seems correct see mapillary picture for this case:
https://www.mapillary.com/app/?pKey=1138349166656984&focus=photo&lat=51.314952700001&lng=12.374022700001&z=17&x=0.6492136208747495&y=0.7613661670191875&zoom=1.00990099009901

The permalink marker map: https://osmose.openstreetmap.fr/de/map/#zoom=18&lat=51.314805&lon=12.374446&item=3160&level=1%2C2%2C3&issue_uuid=55eafb89-9f7d-5ae7-77de-ae240b839a5d

Class number: 31607

Item Issue:
https://osmose.openstreetmap.fr/de/issue/7ebf1040-77bf-7ce5-93e8-b4e88110cead

**Comment by Famlam** [comment]
Fix is deployed :)

**Comment by sun-geo** [comment]
Thanks a lot - seems working as expected :-)
