### ISSUE TITLE
check for maxspeed combined with source:maxspeed=<country-code>:<category>

### ISSUE THREAD

**Issue by it4workflow** [osm-fr/osmose-backend#174]
according to https://wiki.openstreetmap.org/wiki/Speed_limits you could tag `maxspeed=<value>` and the legal form into `source:maxspeed=<country-code>:<category>`, except to UK and Romania

so i did a short command line osmfilter/grep check of `source:maxspeed=DE:rural` and got a lot of maxspeed values unequal to 100, so either the maxspeed value is incorrect or the source:maxspeed one.

and i think, this could be checked an marked as an issue, couldn't it?

ps: take note of the [list](https://wiki.openstreetmap.org/wiki/Speed_limits#Country_code.2Fcategory_conversion_table)

**Comment by grischard** [comment]
In the meanwhile, you can use an overpass query like this:

`way({{bbox}})[highway=residential](if:is_tag(maxspeed) && t[maxspeed]>50);out geom;`

**Comment by it4workflow** [comment]
according to my intention it would be:
```
way({{bbox}})["source:maxspeed"="DE:rural"](if:is_tag(maxspeed) && t[maxspeed]!=100);
way({{bbox}})["source:maxspeed"="DE:urban"](if:is_tag(maxspeed) && t[maxspeed]!=50);
out geom;
```

'highway=residential' could have a maxspeed > 50 (by traffic_sign)

**Comment by frodrigo** [comment]
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L244-L278

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=3032&class=303241

**Comment by frodrigo** [comment]
@it4workflow please can you especially check the result in Denmark and Greater London, there is numerous issues.

**Comment by osmtools** [comment]
hmm, i would say, that at https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L252 you forgot the exception for `dk:rural=80`, haven't you?
PS: it's me it4workflow

**Comment by osmtools** [comment]
for Greater London (and UK) i've created a [topic](https://forum.openstreetmap.org/viewtopic.php?id=59664) in the osm forum users uk.

in the osm wiki i've found [maxspeed in UK](http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Maxspeed#United_Kingdom) which mentions "built-up areas ... 30mph", but i don't know if this is `urban`

**Comment by SomeoneElseOSM** [comment]
A bit of info about how such things get tagged in the UK:

"source:maxspeed" is used for the source of the maxspeed tag (e.g. "sign").  "GB:rural" has no meaning here; legally there is no such thing as a "default rural speed limit".  The actual maxspeed type may be a sign, or dependant on road class, in which case something like "maxspeed=60-mph; maxspeed:type=GB:nsl_single" might be used, perhaps along with "source:maxspeed=sign".  See https://taginfo.openstreetmap.org/keys/maxspeed%3Atype .

**Comment by osmtools** [comment]
@SomeoneElseOSM The most issues in Greater London are

    maxspeed=30 mph
    source:maxspeed=GB:urban

see [w239512274](http://www.openstreetmap.org/way/239512274) and it was a really big [changeset](http://www.openstreetmap.org/changeset/41467667), which i think i will comment later on in the evening
