### ISSUE TITLE
duplicate relations in `osmose_config.py`

### ISSUE THREAD

**Issue by turbotimon** [osm-fr/osmose-backend#1746]
There are several duplicate relations ids in [osmose_config.py](https://github.com/osm-fr/osmose-backend/blob/0de8907bdb36e20c15a302bc9dbf000f4043bc9e/osmose_config.py)
Is that intended?

#### 1210746 duplicate in list (same country)
```
us_fl_region("gold_coast", (1210714,1210692,1210746,1210746 ...
```

#### 1027982 duplicate in list (same country)
```
us_ga_region("southwest", (1020676,1027990,1027981,1027982,1027982 ...
```

#### 1073766 duplicate in list (same country)
```
us_ga_region("southwest", (1020676,1027990,1027981,1027982,1027982,11739369,1028122,1059842,1028128,1027986,1073774,1027987,1073765,1073782,1073788,1028119,1028125,1073776,1074368,1073766,1073766 ...
```

#### 1907305 exists in two countries
```
us_mi_region("central", (1907303,1907305,1907324,1907331,1907335,359763,359764,571344,572130,572624,572689,574448,574462,582247,611155))
us_mi_region("northern_lower", (1586055,1586056,1907305,1907306,1907308,1907310,1907311,1907313,1907318,1907321,1907325,1907327,1907334,1907336,1907338,1907339,1907341))
```

#### 1411337 exists in two countries
```
us_co_region("denver", (1411327,1411333,1411337,1411338,1411339,1411346,1411351,442310))
us_co_region("northeast", (1411314,1411318,1411319,1411322,1411323,1411324,1411326,1411330,1411334,1411336,1411337,1411344,1411348))
```

**Comment by frodrigo** [comment]
Thank for report. We must add test on our side to detect that issues.

**Comment by frodrigo** [comment]
- I add a test
- I fix the config

@jocelynj I removed 1907305 from MI Central, others as just duplicate in the same list.
