### ISSUE TITLE
Wrong Issue "Bad tag strassen-nrw:abs=*"

### ISSUE THREAD

**Issue by bus-mt** [osm-fr/osmose-backend#175]
The tag strassen-nrw:abs=* is marked as "Bad Tag" / "Ungültiges Merkmal". The tag is part of an import described here: http://wiki.openstreetmap.org/wiki/Import/Catalogue/Strassen_NRW and is used all over NRW/DE.

**Comment by frodrigo** [comment]
It's reported besause of '-' in the first part of tag, it's not recommended. I have no idea what `strassen-nrw:abs` is, maybe it sould be `ref:strassen-nrw:abs` ?

http://taginfo.openstreetmap.org/search?q=strassen-nrw

**Comment by bus-mt** [comment]
It seems to be a kind of reference for sections of streets, originally used internally by Straßen.NRW. I don't know why they used a hyphen instead of an underscore in the name, but it is there. As the import was started several years ago and is used 7700 times, the tag should not be marked as "bad tag".
