### ISSUE TITLE
Issue promotes possibly incorrect solution

### ISSUE THREAD

**Issue by Helium314** [osm-fr/osmose-backend#1752]
Item 9015
Class 915007
"track numbers inside a station should be railway:track_ref, not name"
This issue is shown for `public_transport=platform`, `railway=platform_edge`, e.g. https://osmose.openstreetmap.fr/en/issue/4277c770-915a-7d4f-3ccb-f5cbb3f1856f

According to wiki and actual usage, [`railway:track_ref`](https://wiki.openstreetmap.org/wiki/Key%3Arailway%3Atrack_ref) should be on the actual track, not on a platform (edge). For the platform edge, [`ref` should be used](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dplatform_edge).

**Comment by frodrigo** [comment]
That from https://www.openrailwaymap.org/validator/openrailwaymap.validator.mapcss 
The openrailwaymap projet.
Please report to this project.
Same rule available in JOSM validator.

**Comment by Helium314** [comment]
This is fixed now in openrailwaymap, and should thus be fixed in Osmose too is I understand correctly.
So I'll close the issue.

**Comment by frodrigo** [comment]
Thank you. Will be fixed on next mapcss upstate.
