### ISSUE TITLE
Make clear no node at intersection

### ISSUE THREAD

**Issue by jidanni** [osm-fr/osmose-backend#1755]
Don't just say, "Highway intersecting highway."

Remember to also say, "With   no node at intersection."

**Comment by Famlam** [comment]
This is already in the detailed description, isn't it?

**Comment by jidanni** [comment]
![Screenshot_20230203_191225_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/216748164-f7854f9b-acd1-48b1-9ca1-b15280514f1c.jpg)

is all I saw.
No, clicking on things we see here didn't help either.

**Comment by Famlam** [comment]
![Screenshot_20230204-091049](https://user-images.githubusercontent.com/1315520/216756617-bd052025-b5d2-402e-84e4-4a70e2e741ac.png)

What app are you using? It doesn't look like Osmose UI (or I've always missed something). On Osmose I also get this detailed explanation. (Screenshot from phone; on computers it's on the right of the screen)

**Comment by frodrigo** [comment]
It is from Vespucci, using the osmose API.

**Comment by Famlam** [comment]
Hmm, so it's also a bug of Vespucci then, I think?

**Comment by frodrigo** [comment]
> Hmm, so not showing the detailed info is also a bug of Vespucci then, I think?

It is more a missing feature than a bug.

Cc @simonpoole

**Comment by simonpoole** [comment]
The 'More information' link will display more information. If this is helpful in this specific case is naturally difficult to determine without a concrete example of this specific issue.

**Comment by Famlam** [comment]
@simonpoole An (randomly picked) example can be found here:
Osmose map: [lat=51.703154&lon=8.741501](https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=51.703154&lon=8.741501&item=1070&level=1%2C2&tags=&fixable=&class=8)
Issue ID: [cd512438-0451-2b66-b653-ee32f12b973f](https://osmose.openstreetmap.fr/en/issue/cd512438-0451-2b66-b653-ee32f12b973f)
Ways: [1121040966](https://www.openstreetmap.org/way/1121040966) & [67847455](https://www.openstreetmap.org/way/67847455)

**Comment by simonpoole** [comment]
![Screenshot_20230204-211450_Vespucci.jpg](https://user-images.githubusercontent.com/1011860/216787953-03e5d299-04e6-4905-a054-e464b84efd6e.jpg)

Seems as if you have bern mislead.

**Comment by jidanni** [comment]
I see. The first time (in one day) the user presses 'more information' there might be several seconds delay, (screen seem dead). By that time the the user might have given up and pressed some of the (internal) links below that, getting an instant response.
