### ISSUE TITLE
Item #8202 (France): no correction provided

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#1759]
Hello,
I'm having trouble with item #8202 that osmose regularly shows up: I don't understand what to correct/check.

I seem to remember that the analysis comes from @cquest, but no suggestion for correction is made in the tooltip (e.g. https://osmose.openstreetmap.fr/fr/issue/0bdf6f62-1433-bbad-ba87-0bca22f04db9)

Any explanation/help welcome.

**Comment by frodrigo** [comment]
It is not a @cquest report.

It look like this issue : #1609

Maybe linked to bugged suggestion to remove the data.

**Comment by frodrigo** [comment]
> Maybe linked to bugged suggestion to remove the data.

Confirmed, try to remove non present fuel type.

**Comment by deuzeffe** [comment]
OK, got it. Thx to you!
