### ISSUE TITLE
fuel station integration : wrong tag

### ISSUE THREAD

**Issue by Stefal** [osm-fr/osmose-backend#176]
Hi !
The fuel station integration propositions want to add shop = convenience;gaz
the tag "gaz" is wrong, it should be "gas":
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dgas

And maybe shop=convenience + gas=yes is better than shop=convenience;gas

**Comment by frodrigo** [comment]
I fix the already integrated data.
