### ISSUE TITLE
amenity on rooftops

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1761]
I initially [proposed it to JOSM](https://josm.openstreetmap.de/ticket/22556) and it's still under consideration of a throwOther rule, but throwOthers are ignored in Osmose. Hence I was wondering what you think about adding this rule to Osmoses own rules?

```css
*[building=roof][amenity] {
  throwWarning: tr("{0} together with {1}, usually {1} is located underneath the {2}", "{0.tag}", "{1.tag}", "{0.value}");
  assertMatch: "way building=roof amenity=fuel";
  -osmoseItemClassLevel: "--------to-be-determined, probably item 3032--------";
}
```

Rationale: amenities are (almost) never located **on** a roof, usually beneath. So the proper tagging would be:
`building=roof + layer=1` for the roof 
`amenity=*` on a new node (or if the shape is known, on an area) underneath the roof area

**Comment by frodrigo** [comment]
Not sure about the addr of josm issue. But ok for amenity.

**Comment by Famlam** [comment]
Thanks :)

PR ready! If you prefer me to add it to the python file though, please let me know. (Most items in TagFix_MultipleTag could also be a mapcss rule and vice versa)

**Comment by frodrigo** [comment]
> Most items in TagFix_MultipleTag could also be a mapcss rule and vice versa

Yes, was done before MapCSS, some rules was converted to MapCSS but not all.

**Comment by Famlam** [comment]
> Yes, was done before MapCSS, some rules was converted to MapCSS but not all.

Would you want me to do so? (For the ones where it's easily possible?)

**Comment by frodrigo** [comment]
> > Yes, was done before MapCSS, some rules was converted to MapCSS but not all.
> 
> Would you want me to do so? (For the ones where it's easily possible?)

As you want.

**Comment by Famlam** [comment]
Sure, no problem :)

**Comment by Famlam** [comment]
Done

**Comment by frodrigo** [comment]
@Famlam I let you check the result and close the issue
https://osmose.openstreetmap.fr/en/issues/open?item=3032&class=30322

**Comment by Famlam** [comment]
Thanks! There's one minor debatable case (`building=roof + amenity=parking + parking=rooftop`; 77 cases worldwide). I'm personally fine with whitelisting it (although it would be better to have two separate objects, but I guess if the entire roof exists solely for parking...). Do you mind if I mix it in with #1765? Otherwise we'll get merge conflicts.

**Comment by 1ec5** [comment]
This warning appears to be [conflating](https://josm.openstreetmap.de/ticket/22556#comment:8) `amenity=fuel` with `man_made=fuel_pump`.

**Comment by Famlam** [comment]
This tag was invented 3 weeks ago, wiki didn't exist before the 22th of Februari.
Regardless, the building isn't the fuel amenity, so it also violates the one feature one object.

**Comment by 1ec5** [comment]
Ah you’re right, the more established tagging combination for a fuel pump is `amenity=vending` `vending=fuel`, which even has an iD preset.
