### ISSUE TITLE
Wikidata-check for living organism wrong

### ISSUE THREAD

**Issue by Nadyita** [osm-fr/osmose-backend#1768]
item: 3031
class: 8
example: https://osmose.openstreetmap.fr/de/issue/4b8c26da-53c5-5924-2e0a-db8c54aa0bdc

Nearly **all** wikidata-links in my area appear with the weird error that they are linking to living organisms when, in fact, none of them does. I'm getting errors about public transport networks, sport clubs, city districts… you name it. All of these are defined (through inheritance) as the **opposite** of a normal person, maybe that's the issue? Whatever the check you're using is doing, you should probably stop it immediately and hope people haven't blindly fixed them without thinking. There are *hundreds* of these over here. Every rail network, every city district, even libraries.

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/en/map/#item=3031&zoom=15&lat=52.38314&lon=9.83701&level=1%2C2%2C3

@turbotimon it is for you

**Comment by turbotimon** [comment]
Thanks for reporting, there seems to be a new path from "transit district" to "group of living things" on Wikidata.. I will implement an rule for that
![image](https://user-images.githubusercontent.com/57718207/221826858-e22efe13-0522-40d3-a25e-1af7710ab95f.png)

**Comment by Nadyita** [comment]
It's also happening for city-parts (https://osmose.openstreetmap.fr/de/issue/4e8c3ab8-1534-090a-c3e8-7544da0f0946), govenment institutions (https://osmose.openstreetmap.fr/de/issue/6c7cb24a-85f2-9070-9436-e59f4ee1ada0), NGOs (https://osmose.openstreetmap.fr/de/issue/99fd2cd0-d4da-2c7d-02a6-d9a2778ad936), companies (https://osmose.openstreetmap.fr/de/issue/0be88d07-20d2-f76f-b21f-b551d0eb2978) and sport clubs (https://osmose.openstreetmap.fr/de/issue/647a297e-70f4-016f-feaf-c0277e1da925)

**Comment by osm-spiregrain** [comment]
> It's also happening for city-parts...

... and schools (http://osmose.openstreetmap.fr/en/issue/2389c5b2-8d42-581f-58b5-3c30a22a8efa), and places (http://osmose.openstreetmap.fr/en/issue/fba98b8a-7ec5-484c-fe9b-044ea245b0bf).

**Comment by sekerob** [comment]
Yesterday had 1438 new pins by Osmose on my personal fingerpointing list, 1436 about living things not allowed to have wiki links, buried people and the like, 90%+ actually rejecting network:wikipedia and network:wikidata tags on bus routes, masters and stops. Just looking at the Italian map, another slaughterhouse added, this time of green pins. Tested a few in ID Editor deleting those tags and sure they do not know but to put the network:wikipedia/wikidata tags back.

**Comment by turbotimon** [comment]
I deactivated the "living organism" check for the moment, the issues should be gone from Osmose in a couple of hours.

I'm also working on improving this check as well as a guard to block the upload to Osmose if there are a signifikant increase in issues, so i can manually review them: https://gitlab.com/geometalab/osm-wikidata-quality-checker/-/issues/44

**Comment by turbotimon** [comment]
Thanks to everyone for reporting this, it is solved now
@frodrigo you may close this ticket

**Comment by frodrigo** [comment]
Thank you @turbotimon
