### ISSUE TITLE
Deprecated value, not tag

### ISSUE THREAD

**Issue by Stefal** [osm-fr/osmose-backend#177]
Hi !
An error like this one:
http://osmose.openstreetmap.fr/fr/error/9572302232
Says "Tag amenity is deprecated"

It's wrong. The value is deprecated, not the key.
This sentence should be:
"Tag amenity=nursery is deprecated" or
"Value nursery is deprecated"

I've tried to find what should be use to replace %(tag)s but I didn't find.

**Comment by frodrigo** [comment]
Good catch. Fix will be available in a few days on results data.
