### ISSUE TITLE
Clarification for 32301 (`Probably only for bottles, not any type of glass`)

### ISSUE THREAD

**Issue by opk12** [osm-fr/osmose-backend#1776]
For the class ID 32301 `Probably only for bottles, not any type of glass`:
- It should mention `glass material`, otherwise a non-native English speaker can interpret `type of glass` as `type of glass object`, to mean objects of any shape, without thinking about the material.
- It should point to the table entry for `recycling:glass` in the wiki article for [`amenity=recycling`](https://wiki.openstreetmap.org/wiki/Tag:amenity=recycling), because
  - most people do not know that different materials exist, so this warning can come out as weird / surprising;
  - to make an effective, well-informed survey, one needs to know the story explained there.

For example, someone recently proposed in the OSM Italy chat to dismiss all warnings in his town as false positives, because he could only think of soda-lime examples when he asked for info at the municipality. When he was pointed to the wiki's explanation, he said `I would have never found that reference`, which confirms that this warning is incomplete.

**Comment by Famlam** [comment]
I'll have a look at #1598 shortly, if easy, I can do this (resource = wiki link, example = glass types), else I'll have to take it back to the python code

**Comment by Famlam** [comment]
It now contains a description and a link to the source (wiki) in the panel on the right, see for example the error here:
https://osmose.openstreetmap.fr/nl/map/#source=14449&item=3230&class=32301&zoom=17&lat=51.226614&lon=1.390693&level=2&tags=&fixable=
(It will deploy worldwide in the coming days)
