### ISSUE TITLE
Handle direction=* whenever traffic_signals:direction is not set

### ISSUE THREAD

**Issue by Codain** [osm-fr/osmose-backend#178]
Hi,

Osmose detects traffic signals which doesn't have a traffic_signals:direction. But in the case where the traffic signal has a direction=* set this one is ignored.

Exemple:
http://osmose.openstreetmap.fr/fr/error/9687726111

Whenever direction=* is set, then it should take precedence over undefined *:direction.

The proposal is to trigger an error when none of traffic_signals:direction _and_ direction is set. If I understand well the sources in osmose-backend/analysers/analyser_osmosis_highway_traffic_signals.py line 106:

(NOT nodes.tags?'traffic_signals:direction' OR nodes.tags->'traffic_signals:direction' NOT IN('backward', 'forward'))

would become something like:

(NOT nodes.tags?'traffic_signals:direction' OR nodes.tags->'traffic_signals:direction' NOT IN('backward', 'forward')) AND (NOT nodes.tags?'direction' OR nodes.tags->'direction' NOT IN('backward', 'forward'))

**Comment by frodrigo** [comment]
Support `direction` on traffic signals.
Add the same for sqtop and give way.
