### ISSUE TITLE
Validation rule traffic sign: Unmapped road bump (Germany)

### ISSUE THREAD

**Issue by sun-geo** [osm-fr/osmose-backend#1790]
I'm happy about general traffic sign recognition validation.

I noticed the task (8300/34) seems to be not suitable in Germany in general, because there doesn't exist such a traffic sign at all.

item 	8300   -   traffic sign 
class 	34     -   Unmapped road bump
[osmose link for item 8300 and class 34](https://osmose.openstreetmap.fr/de/issue/625e2ddd-ab9c-d547-aadc-98a9651432f9)
`traffic_calming=bump`[wiki](https://wiki.openstreetmap.org/wiki/Tag%3Atraffic_calming%3Dbump) / `hazard=bump`[wiki](https://wiki.openstreetmap.org/wiki/Tag:hazard%3Dbump) / sign: ![Vienna_Convention_road_sign_Aa-7b-V1 svg](https://user-images.githubusercontent.com/47290585/226734632-df5eb799-8801-406c-8a6f-6825345a4d37.png) [bump sign commons wikimedia](https://commons.wikimedia.org/wiki/File:Vienna_Convention_road_sign_Aa-7b-V1.svg) / [bump sign Category commons wikimedia](https://commons.wikimedia.org/wiki/Category:Diagrams_of_bump_warning_road_signs)

Therefore maybe there are almost all issue marker false positive cases, because of other wrong recognized signs.
The automatic traffic sign recognition is mostly wrong - instead of the "Unmapped road bump" sign there are other signs recognized, eg. sign: ![Vienna_Convention_road_sign_Aa-7a-V1 svg](https://user-images.githubusercontent.com/47290585/226736364-ed387d70-54fb-403b-b6d1-d3d057ab1aa5.png) [uneven road sign commons wikimedia](https://commons.wikimedia.org/wiki/File:Vienna_Convention_road_sign_Aa-7a-V1.svg) / [uneven road sign Category commons wikimedia](https://commons.wikimedia.org/wiki/Category:Diagrams_of_uneven_surface_warning_road_signs)

which is a different tag in OSM, see `hazard=damaged_road`[wiki](https://wiki.openstreetmap.org/wiki/Tag:hazard%3Ddamaged_road)
Example: [osmose map link](https://osmose.openstreetmap.fr/de/map/#item=8300&class=34&zoom=18&lat=49.786372&lon=8.597509&level=1%2C2%2C3) / [mapillary link](https://www.mapillary.com/app/?pKey=1034019853800738&focus=photo&lat=49.786514639902&lng=8.5969196073756&z=17)

There are also many wrong cases of recognition by guide plate signs:
sign: ![Zeichen_626-30_-_Leitplatte_(750x500);_StVO_2013 svg](https://user-images.githubusercontent.com/47290585/226738474-b4c27e42-6fb2-4116-94fd-281dea745d70.png) / [guide plate sign commons wikimedia](https://commons.wikimedia.org/wiki/File:Zeichen_626-30_-_Leitplatte_(750x500);_StVO_2013.svg)
Examples: 
i) [osmose map link](https://osmose.openstreetmap.fr/de/map/#item=8300&class=34&zoom=18&lat=50.043098&lon=7.803071&level=1%2C2%2C3) / [mapillary link](https://www.mapillary.com/app/?pKey=198426548766765&focus=photo&lat=50.042887127303&lng=7.8028103869347&z=17&x=0.573130873683308&y=0.7624693471920744&zoom=3)
ii) [osmose map link](https://osmose.openstreetmap.fr/de/map/#item=8300&class=34&zoom=18&lat=50.065073&lon=8.220498&level=1%2C2%2C3&issue_uuid=6df9d6c0-db18-e099-d861-fbf7e8768ba7) / [mapillary link](https://www.mapillary.com/app/?pKey=4150310748340732&focus=photo&lat=50.065228350547&lng=8.2199129321687&z=17&x=0.6111848125356545&y=0.6619830825964246&zoom=3)

There are also minor wrong cases of recognition by the following signs:
parking sign: ![Zeichen_314-50_-_Parkhaus,_Parkgarage,_StVO_2017 svg](https://user-images.githubusercontent.com/47290585/226740972-2e74a0bd-ef39-44de-b65a-661b91b59d1c.png)  [parking sign commons wikimedia](https://commons.wikimedia.org/wiki/File:Zeichen_314-50_-_Parkhaus,_Parkgarage,_StVO_2017.svg)
Example: [osmose map link](https://osmose.openstreetmap.fr/de/map/#item=8300&class=34&zoom=18&lat=49.444977&lon=7.773637&level=1%2C2%2C3) / [mapillary link](https://www.mapillary.com/app/?pKey=307120021008240&focus=photo&lat=49.445160187256&lng=7.7728348336074&z=17&x=0.7359780627835698&y=0.4064480925318429&zoom=3)

slope signs:![Vienna_Convention_road_sign_Aa-2a-V1-1 svg](https://user-images.githubusercontent.com/47290585/226741583-aa2ac4e6-e91a-4229-8a8b-8075a4b4be97.png)/ [slope sign Category commons wikimedia](https://commons.wikimedia.org/wiki/Category:Diagrams_of_slope_signs_by_Vienna_Convention)
Example: [osmose map link](https://osmose.openstreetmap.fr/de/map/#item=8300&class=34&zoom=18&lat=50.118435&lon=8.083137&level=1%2C2%2C3) / [mapillary link](https://www.mapillary.com/app/?pKey=516086173141353&focus=photo&lat=50.118662930419&lng=8.0826405949118&z=17&x=0.6017226389290127&y=0.6257365760322096&zoom=3)

I don't know if this task works well for other countries, please check before switching off the rule for the entire world.

**Comment by Famlam** [comment]
Thank you for your detailed report! It's very easy to disable a non-existing traffic sign on a per-country basis (I did the same for the speed limit 110 for NL in the past) so I made a PR to fix this.
Should fix 1305 false positives in Germany: https://osmose.openstreetmap.fr/de/issues/open?item=8300&class=34&country=germany%2a

**Comment by frodrigo** [comment]
PR of @Famlam merged, but not deployed, yet.

About the wrond detection, is on Mapillary side. Osmose can do nothing about it, except disable some traffic sign if there is so much false-positives.

**Comment by sun-geo** [comment]
Thanks a lot of instant reply and the code updates.

In meantime I looked at wikipedia page:
https://en.wikipedia.org/wiki/Comparison_of_European_road_signs#Warning
 
So it seems, the bump sign is next to Germany also not available for Austria, Switzerland, Liechtenstein and Turkey.

**Comment by Famlam** [comment]
I went through a random set of matches from those countries:
- Liechtenstein doesn't have any detections (but it doesn't hurt to disable a non-existing traffic sign)
- The other three countries I only found false positives
I'll create a PR

**Comment by frodrigo** [comment]
Thank you.
For reminder, once deployed, frontend will need to be cleaned (manually) for this classes on this countries.

**Comment by Famlam** [comment]
@frodrigo I think this is deployed, correct? 
If so, can you clear this detection for Austria, Switzerland, Germany and Turkey on the frontend?

**Comment by frodrigo** [comment]
```
select array_agg(id) from sources where analyser = 'Merge_Traffic_Signs' and country like 'switzerland_%';
```

```
34001,34002,34003,34004,34005,34006,34007,34008,34009
402784,402835,402886,402937,30974,33000,33003,33006,33009,33012,33015,33018,33021,33024,33027,33030,33033,33038,33041,33044,33047,33050,33053,33056,33059,33062,33065,33068,33071,33074
418511,418566,418621,418676,418731,418786,418841,418896,418951,419006,419061,419116,419171,419226,419281,419336,419391,419446,419501,419556,419611,419666,419721,419776,419831,419886
33325
```

```
./item-class-source-remove.sh 8300 34 402784,402835,402886,402937,30974,33000,33003,33006,33009,33012,33015,33018,33021,33024,33027,33030,33033,33038,33041,33044,33047,33050,33053,33056,33059,33062,33065,33068,33071,33074
```

Removed
