### ISSUE TITLE
All public_transport merge seems to be missing

### ISSUE THREAD

**Issue by nlehuby** [osm-fr/osmose-backend#1793]
The public_tranport merges analysis are not available anymore (item 8040)

the frontend returns empty answer, as if the analysis does not exists :thinking: 

https://osmose.openstreetmap.fr/en/issues/open?item=8040
https://osmose.openstreetmap.fr/en/issues/open?item=8040&class=41
https://osmose.openstreetmap.fr/en/issues/open?item=8040&class=81
https://osmose.openstreetmap.fr/en/issues/open?item=8040&class=31
https://osmose.openstreetmap.fr/en/issues/open?item=8040&class=141
https://osmose.openstreetmap.fr/en/issues/open?item=8040&country=france_provence_alpes_cote_d_azur_alpes_maritimes

**Comment by frodrigo** [comment]
They have been temporary disabled (available under `useDevItem=all`), not sure why and when.

https://osmose.openstreetmap.fr/en/issues/open?item=8040useDevItem=all

**Comment by frodrigo** [comment]
I reactivated the item.

I not still not know why I disabled it. But probably for a request about data integration on Nice city (cc @jocelynj https://osmose.openstreetmap.fr/en/map/#source=429090&item=8040&class=111&zoom=14&lat=43.6976&lon=7.19016&level=1%2C2%2C3 )
