### ISSUE TITLE
"Could be integrated" features in France

### ISSUE THREAD

**Issue by ThomR38** [osm-fr/osmose-backend#1797]
Hello ,
I use Osmose to integrate open databases in Openstreetmap. 
Examples : 
- school, could be integrated (item 8031)
- pharmacy, could be integrated (item 8211)

For a few months, Osmose has not suggested any feature for integration. 
I could not find any explanation, such as automatic edits or code change, though I may have missed something. 

Is it possible to tell why there are no feature suggested anymore ?

**Comment by ThomR38** [comment]
I agree, there were a only a few pharmacies. I checked regularly and applied the suggestions when they were relevant. 

Currently, there are no suggestion, although some cases seem to be relevant. I tried to find some examples that could illustrate the subject : 
School : 
https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=44.836798&lon=4.893926&item=7070%2C8030%2C8031%2C8211&level=1%2C2%2C3

Pharmacy : 
https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=47.010287&lon=3.163649&item=7150%2C8210%2C8211&level=1%2C2%2C3

**Comment by frodrigo** [comment]
In fact all "Could be integrated" are affected by the same issue since the same date.

**Comment by frodrigo** [comment]
"need update" is also broken, but from beginning of march.

**Comment by frodrigo** [comment]
Both fixed.

**Comment by ThomR38** [comment]
Yes, it's working now. 
Thanks a lot !
