### ISSUE TITLE
No update of analysis merge_recycling_FR_sitcom40

### ISSUE THREAD

**Issue by vinber** [osm-fr/osmose-backend#1798]
https://osmose.openstreetmap.fr/fr/map/#zoom=13&lat=43.5391&lon=-1.37355&item=8120&level=1%2C2%2C3

There was not update of this analysis but there was an update of opendata files

**Comment by vinber** [comment]
an example
![image](https://user-images.githubusercontent.com/890869/228788753-52146eaa-a5bd-47e0-a95d-c1bee632f2fc.png)

https://osmose.openstreetmap.fr/fr/map/#zoom=15&lat=43.54078&lon=-1.38308&item=8120&level=1%2C2%2C3&issue_uuid=8e6bceb9-bcd7-83b7-3d9e-b88ab145b9bf

**Comment by frodrigo** [comment]
As you can see on the popup, the last analyser update is from today.

The fetch of the data source is cached, and update every 30 days.

**Comment by neo-64** [comment]
Hi, 

The data source can be updated daily. Can we update the cache every day? If this is not possible can we exceptionally force an update (we have filtered certain points)

THANKS

**Comment by frodrigo** [comment]
Switch to daily source data update done.
https://osmose.openstreetmap.fr/fr/issues/open?item=xxxx&source=440115
