### ISSUE TITLE
use "similar value" to detect typo in tracktype

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1800]
value "grace3" could be detected as similar to grade3
and/or catch all values not matching "^grade[1-5]$"

**Comment by Famlam** [comment]
There's only about 20 worldwide with a very close similarity (well, excluding grade6+)
https://taginfo.openstreetmap.org/keys/tracktype#values

Would be easier to add it to https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_BadValue.py#L95

**Comment by Famlam** [comment]
Merged, not deployed yet

**Comment by Famlam** [comment]
It's live in a large part of the world, rest will follow very soon :)
Example: https://osmose.openstreetmap.fr/nl/issue/3655a6d5-2869-a637-f92f-7e0351e2a7ce
