### ISSUE TITLE
split turkey

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1802]
[netherlands_noord_holland](https://buildbot.osmose.openstreetmap.fr/#/builders/684) >10h
[turkey](https://buildbot.osmose.openstreetmap.fr/#/builders/296) >6h

**Comment by Famlam** [comment]
>[netherlands_noord_holland](https://buildbot.osmose.openstreetmap.fr/#/builders/684) >10h

For the province of North Holland the only subdivision we have (that does not overlap with other provinces, such as the 'waterschappen') is the safety regions, to my knowledge:
https://www.openstreetmap.org/relation/11961484
https://www.openstreetmap.org/relation/11961489
https://www.openstreetmap.org/relation/11961490
https://www.openstreetmap.org/relation/11961483
https://www.openstreetmap.org/relation/11961491

(p.s. osmosis_highway_features is much slower than similar analysers, maybe that one needs some optimization?)

**Comment by frodrigo** [comment]
> [netherlands_noord_holland](https://buildbot.osmose.openstreetmap.fr/#/builders/684) >10h

But we got this time after it switched to slowest backend. It should not run on this backend.

> [turkey](https://buildbot.osmose.openstreetmap.fr/#/builders/296) >6h

Ok for Turkey. But last time we make a report we get:
```
   17:45:44   usa_new_york                                                                                               
   13:32:56   australia_new_south_wales                                                                                  
   12:48:49   mozambique                                                                                                 
   11:55:58   netherlands_gelderland                                                                                     
   11:31:50   bangladesh                                                                                                 
   11:01:46   netherlands_noord_holland                                                                                  
   10:25:30   nigeria                                                                                                    
   10:07:36   usa_michigan                                                                                               
    9:59:51   usa_virginia                                                                                               
    9:58:27   usa_arizona 
```

**Comment by Marc-marc-marc** [comment]
I don't see "splited" turkey on the fronted nor on buildbot

**Comment by frodrigo** [comment]
I close, as Turkey not in the longest extract to run.

**Comment by Marc-marc-marc** [comment]
>    17:45:44   usa_new_york                                                                                               
>    13:32:56   australia_new_south_wales                                                                                  
>    12:48:49   mozambique                                                                                                 

already splitted

>    11:55:58   netherlands_gelderland                                                                                     

take only 2h now

>    11:31:50   bangladesh          

no in buildbot config anymore
                                                                                       
>    11:01:46   netherlands_noord_holland      

only 3h
                                                                            
>    10:25:30   nigeria                 

already splited
                                                                                   
>    10:07:36   usa_michigan                    

already splited
                                                                           
>     9:59:51   usa_virginia                                                                                               

already splited

>     9:58:27   usa_arizona 

not yet :)
