### ISSUE TITLE
Edit suggestion suggests highway=residential_link

### ISSUE THREAD

**Issue by ramen2581** [osm-fr/osmose-backend#1804]
Item 1110 Class 3
Edit suggestion suggests highway=residential_link and unclassified_link which are not approved tags.
Edit: It's class 3 sorry.

**Comment by ramen2581** [comment]
https://osmose.openstreetmap.fr/en/issues/open?item=1110&class=1

**Comment by ramen2581** [comment]
I initially listed the wrong class sorry.
Here's a specific issue.
https://osmose.openstreetmap.fr/en/issue/a7548648-1de9-302c-a9e1-2d9dc4269f45

**Comment by ramen2581** [comment]
Example of bad edit caused by this issue. https://www.openstreetmap.org/way/940682168/history

**Comment by Famlam** [comment]
https://osmose.openstreetmap.fr/nl/issue/fe47fc8e-e96c-2caa-67c1-67af8952cbce

Also construction_link is proposed. I'll see if I can make a fix and a regression test (the latter is probably the most difficult)

**Comment by ramen2581** [comment]
Accidentally marked closed before checking. If this is live on the site it's not working.

**Comment by frodrigo** [comment]
Deployed yesterday. Update in progress.

**Comment by Famlam** [comment]
I think the fix is live worldwide now, except two US states (Delaware, Colorado) which will probably follow very soon but are behind for 9 days atm
