### ISSUE TITLE
False positive: use of ',' in addr:housenumber

### ISSUE THREAD

**Issue by simonpoole** [osm-fr/osmose-backend#181]
This likely due to a translation error.

',' is a legal separator for house number values, see https://wiki.openstreetmap.org/wiki/DE:Key:addr for the original text, the FR translation mentions ';' however that is not correct (from a practical pov applications have to be able to consume both).

See also https://wiki.openstreetmap.org/wiki/Proposed_features/House_numbers/Karlsruhe_Schema for the original proposal.

**Comment by frodrigo** [comment]
I found nothing about check for `,` or `;`.
But I found a check for `addr:housenumber` with special regex for Switzerland:
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Housenumber.py#L45
Seem too strict. And more over does not allow the comma.

**Comment by simonpoole** [comment]
the regex is OK for an individual house number, but not for a multi-number value, I'll tr and sumbit a PR tomorrow
@grischard probably not really your fault :-)

**Comment by grischard** [comment]
Are multiple house numbers like this something that exists on the ground, or is it an effect of incomplete mapping? It was my impression, from the data I could find, that Switzerland doesn't have joint house numbers, and that therefore it is useful to have a tool that shows you where better mapping would be good.

This is why I must come to Switzerland more often :).

**Comment by simonpoole** [comment]
@grischard sure, in general the mapping could be, at least theoretically, be refined in such circumstances (house numbers are assigned to entrances in principle, there is actually an expensive standards document defining that). However often in practice you don't have access to the actual placement of the numbers.

But that isn't the problem, the error message is "illegal character in value" or something similar, not "could be mapped better" which, knowing armchair osmose zeleots, will lead to "fixes" that will lead to information loss.

**Comment by frodrigo** [comment]
Sorry, I screw up on my first commit. Now all Swiss addresses are marked as "invalid".
I just push a fix.

**Comment by frodrigo** [comment]
All right

**Comment by simonpoole** [comment]
Thanks @frodrigo (sorry I didn't get around to fixing it myself, was bug fixing else where).
