### ISSUE TITLE
Default and local language name not the same in Belgium-Vlanderen

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1810]
https://osmose.openstreetmap.fr/fr/issue/cf61dd7e-78f6-054b-a432-020109dba139
https://www.openstreetmap.org/way/58509635
name=Gemeneweg
name:nl=Gemeneweg
I don't understand the issue, josm validator doesn't complain about it too.

**Comment by frodrigo** [comment]
It is on the border (as the name say). This issue is from France.
Mark it as flase positive.

**Comment by Famlam** [comment]
@Marc-marc-marc are you fine with closing this issue?

**Comment by Marc-marc-marc** [comment]
I think there is a problem in
- in the osm data: the dutch name is probably not applicable in France, it would need :left :right and find the source https://www.openstreetmap.org/relation/4237461 to confirm my guess, which in turn will cause false positives of a different name on the relation than the highway=* name
- The analysis should take into account this situation "on the border", but considering the small number of cases, I think that it is really not urgent or even something to deal with, unless someone is motivated to do it and that it is technically possible.
for me the issue can be closed in no-fix if you want
