### ISSUE TITLE
This indoor feature is not reachable 

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1813]
item | 1300
class | 2
a indoor room https://www.openstreetmap.org/way/1159640032
the door https://www.openstreetmap.org/node/4888497424
connected to the "external" network https://www.openstreetmap.org/way/1163077113
something missing in osm or bug ?

**Comment by Famlam** [comment]
It seems highway=path isn't included here:
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_indoor.py#L116

Not sure if that was intentional, @nlehuby ?

**Comment by nlehuby** [comment]
I would rather use footway in that case, but yes, path could be added here.

**Comment by Marc-marc-marc** [comment]
thanks for the improvement (long debate on whether or not a highway=* without a blue pedestrian sign is a footway asnothing prohibits me from cycling to enter some shops especially bike-related shops :) )

it is not only highway=path that is missing but also some values for 4 wheel-wide vehicles.
e.g. the room in a garage is accessible if it is connected with a highway=service (even if at the other end it may exist a pedestrian exit, even without the internal pedestrian path, it is already routable, including by foot using the highway=service if allowed (=for ex for the private garage next a house)

**Comment by frodrigo** [comment]
Deployed
