### ISSUE TITLE
Bad key suffix reported on ref:clochers.org and ref:refuges.info

### ISSUE THREAD

**Issue by Timo-Breumelhof** [osm-fr/osmose-backend#1823]
I had a look at the reported Osmose issues around me and noticed that almost all religious buildings report an warning.
I realize that the ref tag is not supposed to contain a . but I did not put them in there :-)

As an example:
https://osmose.openstreetmap.fr/en/issue/eca1f980-5451-0a11-a06d-1cc84b49dc00

---------------

Bad key suffix
Concerns tag: `ref:clochers.org=88487_1`
way 163391736[ josm](http://localhost:8111/load_object?objects=w163391736)[ iD](https://www.openstreetmap.org/edit?editor=id&way=163391736)[ edit](https://osmose.openstreetmap.fr/en/map/#)
amenity = place_of_worship
building = church
denomination = catholic
heritage = 3
heritage:operator = mhs
mhs:inscription_date = 1926-02-16
name = Église Notre-Dame-du-Val-d'Ajol
**ref:clochers.org = 88487_1**

-------------

According to this reply to my question, this is not an issue and the tag should not be edited:
https://community.openstreetmap.org/t/french-religious-building-deprecated-warning-on-osmose/98265/8

I think it would be good to add en exception for these tags so they don;t get listed as warnings, as now they might lead to less experienced Editors (like me) "correcting them"?

BTW , i noticed the same for 

--------------------

Bad key suffix
Concerns tag: `ref:refuges.info=4898`
way 865404932[ josm](http://localhost:8111/load_object?objects=w865404932)[ iD](https://www.openstreetmap.org/edit?editor=id&way=865404932)[ edit](https://osmose.openstreetmap.fr/en/map/#)
amenity = shelter
bin = no
building = yes
name = Abris des Peugeux
**ref:refuges.info = 4898**
shelter_type = weather_shelter

-----------------

**Comment by frodrigo** [comment]
See #1729 #1055
