### ISSUE TITLE
Consider a check for businesses missing opening_hours

### ISSUE THREAD

**Issue by CloCkWeRX** [osm-fr/osmose-backend#183]
This might stray a little from 'bad tagging' into 'implied attributes', but it would be interesting to see:

 * amenity=cafe|restaurant|fast_food|pub|bar, or shop=*
 * has no opening_hours attribute

While its hard to fix these with armchair mapping (could possibly check websites to discover), when you plug in osmose issues to vespucci for example; you'd get push notifications of businesses without hours that could be surveyed.

The only things I can think of that might need exclusion are indoor shops in malls; or stalls in marketplaces that are a bit more adhoc

**Comment by frodrigo** [comment]
It's not in the scope of Osmose-QA. Osmose-QA is more what should be than what date could be.
