### ISSUE TITLE
Unclear lane count

### ISSUE THREAD

**Issue by Helium314** [osm-fr/osmose-backend#1831]
I noticed the following issue:
https://osmose.openstreetmap.fr/en/issue/1649d0b8-c24a-b643-9f78-c0253378dda8
which is about "The number of lanes defined by many lane tags are not the same for a given direction."
However, the way has `lanes=2`, one lane is for everyone and the other one is for bus/taxi/bicycles, as indicated by (bicycle/bus/taxi)`:lanes=yes|designated`
So there is no lanes tag indicating any number other than 2.

The subtitle reads "(lanes(lanes:*)=2) - (non fullwidth=0) != (lanes(bicycle:lanes)=2) - (non fullwidth=1)", but there is no non-full-width name tagged anywhere.
So where does osmose find a non-full-width lane?

**Comment by Famlam** [comment]
For reference (item: 3160, class: 31608)
```
bicycle:lanes=yes|designated
bicycle=yes
bus:lanes=yes|designated
busway=lane
cycleway=share_busway
foot=no
highway=tertiary
lanes=2
lit=yes
maxspeed=30
name=Meiereistraße
oneway=yes
shoulder=no
sidewalk=none
smoothness=excellent
source:maxspeed=AT:zone:30
surface=asphalt
taxi:lanes=yes|designated
```

**Comment by Helium314** [comment]
Looking at it again, especially `(lanes(bicycle:lanes)=2) - (non fullwidth=1)`, it seems that some separate cycle lane might be expected.
Is `cycleway=share_busway` taken into account here?

**Comment by Famlam** [comment]
Fix is deployed
