### ISSUE TITLE
Report miss usage of landuse=village_green

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1833]
In many countries landuse=village_green is used just to get green area on the map. Eg in roundabout center.

https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dvillage_green

Idea to stop false positive:
- Inside roundabouts or between two roads
- Too small
- Too many `landuse=village_green` in the same area.
- ST_MaximumInscribedCircle

**Comment by Famlam** [comment]
I attemped this already in https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_polygon_small.py#L93, but with a very conservative value.

I guess bumping it up to 500m2 (22x22m square or 25m diameter round) should be no problem? Maybe even 1000m2 (31x31m square or 36 diameter).

**Comment by frodrigo** [comment]
The excessive usage of `landuse=village_green` could come from bad translation / preset in JOSM.

**Comment by Famlam** [comment]
I discovered why the existing validator didn't work anymore... apparently a ` snuck in somewhere without me noticing...
But since that analyser only checks for area (so a long, stretched piece of land would go undetected) it is still good to add an extra check with `ST_MaximumInscribedCircle`
