### ISSUE TITLE
fire_station in France

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osmose-backend#1834]
Hello,

In France, Osmose offers an integration of fire stations via the opendata of the BDTopo IGN.
The BDTopo is updated every quarter, but the records are always dated 06/2022

Is the update of the BDTopo manual or is the automatic update broken?

Thanks

**Comment by gendy54** [comment]
@cquest a priori tu sais comment régler le problème

**Comment by frodrigo** [comment]
@cquest up to date data is on the server, but the latest link is not on it.

**Comment by gendy54** [comment]
Je relance le truc. Qu'est-ce qui coince ?

**Comment by frodrigo** [comment]
I switched from opendatarchives.fr to get data directly from IGN. It less efficient, but it will be up to date.
Deploy in progress.

**Comment by frodrigo** [comment]
It is now up to date using "fresh" BD TOPO data http://osmose.openstreetmap.fr/fr/issues/open?item=8520&class=10600
