### ISSUE TITLE
lanes vs. :lanes

### ISSUE THREAD

**Issue by mueschel** [osm-fr/osmose-backend#184]
Example:  http://osmose.openstreetmap.fr/de/error/10209856412
Osmose compares the value from the "lanes" tag with the number of lanes in keys with "*:lanes" and throws an error if they don't match. In fact, this is rather common in case of explicitly mapped bicycle lanes. "lanes" is defined as full-width lanes for cars, while ":lanes" counts all lanes, including narrow ones for bicycles. 

An error should be shown in these cases:
- "lanes" is larger than the sum of ":lanes" - but not if it is smaller as described above
- different ":lanes" do not have the same number of lanes

**Comment by frodrigo** [comment]
There is no way to detect the `*:lanes` content extra lanes not counted into `lanes` ? Like a `cycleway` tag ?

In case you have nothing planned tonight you can review the check of lanes tags ;-) : https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Lanes.py

**Comment by mueschel** [comment]
A cycleway tag doesn't need to exist (good to have, but not a 'must'). Maybe this can be included as a sanity check, but I'm sure we can come up with examples where the number of :lanes is not equal the number of lanes and there is no cycleway involved.

In some cases it doesn't help because it can't tell the number of lanes:
https://www.mapillary.com/map/im/KvTjGhcGD0HJX98gp8SXqA
http://www.openstreetmap.org/way/413002103

On the check about "turn = left must be on the left lane":
https://www.mapillary.com/map/im/-Wj6hVidLFcZLHsvkX1WdQ
http://www.openstreetmap.org/way/406017374
I've seen this for regular traffic lanes as well, but don't have a picture.

I didn't read the rest of the check yet, it's too late to train my Python now ;)

**Comment by frodrigo** [comment]
I can allow diff of `lanes` and `*:lanes` number in case if some cycle tags аrе impliqued. Do you see other tags than cycle tags to allow this ?

**Comment by mueschel** [comment]
Currently I don't see further tags you can use.  But I remembered two other cases where this check might fail:
- sometimes turn lanes which are not full-width are mapped using *:lanes and width:lanes, but they don't count in lanes=*
- I know some cases of traffic islands that are mapped as   lanes:both_ways = 1, access:both_ways = no - this is not fully correct, but we lack a perfect way to map this.

Nevertheless, introducing this additional check will reduce the number of false positives significantly.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=3160
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=3160&start_date=2017-07
