### ISSUE TITLE
Plenty errors "Should be polygon, part of multipolygon or not having area tag"

### ISSUE THREAD

**Issue by pl71** [osm-fr/osmose-backend#185]
Hi,

Recently (from yesterday) all `natural=*` and `landuse=*` well closed ways are reported with the error in the subject line. For me this is some kind of bug giving so many false positives.
Otherwise, please explain what you mean with this error.

Example: http://www.openstreetmap.org/way/25236651#map=15/43.7423/23.6200
and the error: http://osmose.openstreetmap.fr/en/error/10472424729

Regards

Edit: Since when all natural tags should have also `area=yes` tag?

**Comment by frodrigo** [comment]
Back to normal.
