### ISSUE TITLE
Error 1230 - Duplicated Geometry - Nodes

### ISSUE THREAD

**Issue by pschonmann** [osm-fr/osmose-backend#186]
I have area where lots of E1230 is http://osmose.openstreetmap.fr/cs/map/#&item=1230&zoom=17&lat=50.0852945&lon=14.5070505&level=3

For example there is one error of them. http://osmose.openstreetmap.fr/cs/error/10529876535
When i look closer to the nodes
Located in France [WRONG][DELETED_NODE] - http://www.openstreetmap.org/node/3392080130
Located in Prague [OK]- http://www.openstreetmap.org/node/633560801

How can be compared two nodes which are in other countries :) Expect this as bug.  But i still see this as error on the map.
Can you look at this. Thank you.

**Comment by frodrigo** [comment]
same as #193

**Comment by jocelynj** [comment]
It should hopefully be fixed by b293e0d94264be7720a0fc3ea19ddc8312ab40ae.
