### ISSUE TITLE
border difference between extract and Osmose - Chile and Argentinia

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1860]
https://osmose.openstreetmap.fr/nl/map/#zoom=9&lat=-49.497&lon=-72.961&item=1170&level=1%2C2%2C3&tags=&fixable=&class=5

Edit: see next comment

~It seems analyser osmosis_relation_open (item 1170 class 5) has some issues when a multipolygon crosses an extract boundary.
Maybe this check can become redundant with the new table multipolygons (depending on whether the output of ST_IsValidReason will give a similar clear description of what's wrong). If not, probably a similar approach as https://github.com/osm-fr/osmose-backend/pull/1700/files should be employed, exempting ways crossing a border~

**Comment by frodrigo** [comment]
The issue may be with the boundary used by osmose.

The issue from a country (area) are clipped using the excat admin polygon. So the missing part of multipoly should be outside and clipped out. And so no issue raised.

**Comment by Famlam** [comment]
You are correct.

In the extract of Argentinia Santa Cruz, relation 11224568 is present, except way 818119734 (outer)
![image](https://github.com/osm-fr/osmose-backend/assets/1315520/325926d3-3322-47b5-afff-4cfbffc6f24e)

The "most outer nodes" of the ways this relation in the extract are: node 673003592 and node 6996495740
Both nodes are *outside* the country border as defined by Chile (way 492211221)
Both nodes are *inside* the country border as defined by Argentinia itself (way 410368381)

Osmose uses relation 153549 as the border, but this relation uses way 410368381 as outer
https://github.com/osm-fr/osmose-backend/blob/9fbe359f915dc7be024e091aa7cdc9e13c4a208f/osmose_config.py#L1508

Hence, the "missing way" is *outside* of the extract, but *inside* the borders of Argentinia used by Osmose
Hence, the 'border issues' are not removed by the server.

**Comment by Famlam** [comment]
I don't see an alternative relation for this. Is there a solution that Osmose can do?

(E.g. should the extract border be adjusted to also include this part in Argentinia, which would mean analysers analyse a part twice (once for Chile and for Argentinia))?

Or should I just mark them as false positives and hope the border conflict gets resolved soon?

**Comment by frodrigo** [comment]
I also do no see solution. This issue probably happen in all disputed border area.

Just mark it as false-positive?

**Comment by Famlam** [comment]
Marked all 18 crossings as false positives
