### ISSUE TITLE
TagFix_Postcode doesn't accept 5-digit ZIP codes for addr:postcode=* anymore

### ISSUE THREAD

**Issue by hrhino** [osm-fr/osmose-backend#1864]
See #1849: Osmose pulls postcode formats [from Wikipedia](https://en.wikipedia.org/w/index.php?title=List_of_postal_codes), and [a recent change thereto](https://en.wikipedia.org/w/index.php?title=List_of_postal_codes&diff=1153347765&oldid=1151168639) specifies that 5-digit ZIP codes are "area format" and 5+4-digit ZIP codes are "street-level format".

Because of this, Osmose is flagging more or less every element with an address including a ZIP code as invalid, since the near-universal practice in the US is to specify only the 5-digit version.

Can we please have a special case for the US? I tend to at least glance at Osmose flags on features to see if I can fix an issue but this makes the flagging nothing but noise.

Thanks!

**Comment by frodrigo** [comment]
We see this change, but unsure about that, as none of us is from USA.

As the 5-digits is also used for street level, it would not be better to fix the wiki allowing 5-digits and 5+4-digits at street level?

**Comment by frodrigo** [comment]
It generated 20 millions Osmose issues.

I hidden this item for now.

**Comment by 1ec5** [comment]
> As the 5-digits is also used for street level, it would not be better to fix the wiki allowing 5-digits and 5+4-digits at street level?

Wikipedia’s distinction between area- and street-level codes doesn’t fit the USPS system very well. A five-digit ZIP code technically identifies a delivery route, which may be as large as a county (for counties of low population density) or as small as a single building (for buildings that receive lots of mail). A ZIP+4 code could refer to a city block, a building, or a single addressee or P.O. box.

Anyways, I’m not sure what the level of specificity has to do with OSM address quality. The USPS accepts either code as valid; so should Osmose.

**Comment by frodrigo** [comment]
> allowing 5-digits and 5+4-digits at street level?

I edited the wiki page in this way.

**Comment by frodrigo** [comment]
All the osmose issues on the frontend base are now dropped.
I have re-enabled the item.
