### ISSUE TITLE
Recurring false positive: ref=* or possibly missing highway in the area

### ISSUE THREAD

**Issue by gupascal** [osm-fr/osmose-backend#187]
Hello,

Here ( http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.886033&lon=3.153795&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=xxxx&level=1%2C2%2C3&tags=&fixable= ) the error **"ref=\* or possibly missing highway in the area"** is reported with the comment **"A 71 (id_route500: 66257)"** and repeated all along the highway.
However, everything seems to be perfectly fine: all highway segments are tagged **"ref=A 71;A 89"**.
Maybe the semi-colon is not handled properly? Or did I missed something?

Hope this help.
Thanks

**Comment by frodrigo** [comment]
@cquest can you check this please?

**Comment by gupascal** [comment]
Same error here ( http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=45.760358&lon=3.088365 ) with D3. And there is no semi-colon this time. Again highway segments are correctly tagged with **"ref=D 3"** on OSM.

**Comment by frodrigo** [comment]
ping @cquest

**Comment by frodrigo** [comment]
Route 500 data must be first update to last version. (cc @cquest )

**Comment by cquest** [comment]
Route500 has been updated :)

**Comment by frodrigo** [comment]
This has no effect on
http://osmose.openstreetmap.fr/fr/errors/?source=14708&item=7170&class=2
http://osmose.openstreetmap.fr/fr/errors/graph.png?source=14708&item=7170&class=2

**Comment by cquest** [comment]
Je ne comprends pas le problème.
Route500 indique bien la présence de routes numérotées, exemple: http://osmose.openstreetmap.fr/fr/errors/?source=14708&item=7170&class=2

Il s'agit de la N 200

**Comment by frodrigo** [comment]
Je ne peut pas regarder avant la semaine prochaine. Mais la mise à jour des
données aurrait du avoir un impact important sur le nombre de signalements.
Ça n'a pas bougé du tout. Cf le graphique.

Le 25 oct. 2017 14:31, "Christian Quest" <notifications@github.com> a
écrit :

**Comment by cquest** [comment]
La mise a jour a été faite bien avant ma réponse à l'issue, je pense que c'est la pente vers juin/juillet.

**Comment by frodrigo** [comment]
Ok, ça a effectivement l'air bon maintement.
