### ISSUE TITLE
`highway=*` does not intersect building if `building = parking`

### ISSUE THREAD

**Issue by homersimpsons** [osm-fr/osmose-backend#1874]
- **Item**: 1070 objects overlap (Highway intersecting building)
- **class number**: 1
- **link details**: https://osmose.openstreetmap.fr/en/issue/0db3fac8-a502-4bd0-f232-cff0ffd7fcd9
- **map link**: https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=47.975847&lon=-4.094427&item=1070&level=2&tags=&fixable=

Currently osmose reports "Highway intersecting building" when `building = parking`, but in case of multi-storey parking we are still expecting to add the `building` tag, references:
- https://wiki.openstreetmap.org/wiki/Key:parking
- https://wiki.openstreetmap.org/wiki/Tag:parking%3Dmulti-storey
- https://wiki.openstreetmap.org/wiki/Tag:building%3Dparking

**Comment by Famlam** [comment]
I suspect we'll need to exclude buildings with `amenity=parking` (57k) or `building=parking` (22k). Probably the former (as many buildings are probably tagged building=yes, for example if there's shops on top of the parking).

(It should be fine for all level above ground floor levels as those are already filtered out as soon as they have a `level` or `layer` tag)

**Comment by homersimpsons** [comment]
It looks like this is already deployed. Thank you for the quick fix !

I am closing this, if there was a reason to keep it open, feel free to re-open.
