### ISSUE TITLE
analyser_osmosis_highway_area_access item=2130, class=2 produce duplicate issues

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1887]
At least item=2130, class=2  produce non distinguishable osmose issues in the frontend. Each issue overwrite the previous for the same node.
The result should contain a subclass, on fo each vehicle type.

https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_osmosis_highway_area_access.py#L221

Maybe a better way to fix it is to make only one report for the node ?

**Comment by frodrigo** [comment]
Required for https://github.com/osm-fr/osmose-frontend/pull/462

**Comment by Famlam** [comment]
I wouldn't know a way to keep this analyser flexible 
(i e. avoiding  `(3 lines for emergency) OR (3 lines for motorcycle) OR ( 3 lines for hgv) OR ...`) so I think subclasses are the simplest solution?

Probably there should be a generic test that no duplicates exist, since this would get unnoticed on the backend?

**Comment by frodrigo** [comment]
> I wouldn't know a way to keep this analyser flexible (i e. avoiding `(3 lines for emergency) OR (3 lines for motorcycle) OR ( 3 lines for hgv) OR ...`) so I think subclasses are the simplest solution?

Yes, I'm ok for that.

**Comment by Famlam** [comment]
Which parts exactly have to be unique for the issue ID hash?
(There is of course always a small possibility of two different errors getting the same ID, given the huge size of OSM and the large number of analysers)

**Comment by frodrigo** [comment]
UUID is computed here https://github.com/osm-fr/osmose-frontend/blob/master/control/update_utils.py#L265
