### ISSUE TITLE
osmosis_polygon_intersects should also filter multi-poly on min area

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1889]
Poly from ways are filtered on min area but multi-poly not.

https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_osmosis_polygon_intersects.py#L95

**Comment by Famlam** [comment]
They should practically all be filtered by the -2m buffer already, right?

(I didn't think there would be any multipolygons with a -2 buffer that would still have an area > 0. Technically it is possible in a very rare case of a >16m2 outer and another <3m2 outer, or a very small inner almost touching the outer lines)

**Comment by frodrigo** [comment]
But you think we need it on poly from ways, but not from multi-poly ?

**Comment by Famlam** [comment]
Not really. Maybe better to delete it. The few rare cases where there'll be a double warning (overlap & small polygon) probably don't outweigh having to keep this in mind if we ever change the limits of polygon_small.

**Comment by Famlam** [comment]
I'm still curious if you managed to find a MP that matched both analysers though :)
