### ISSUE TITLE
(Multi)polygon fixing effort

### ISSUE THREAD

**Issue by joto** [osm-fr/osmose-backend#189]
There is a major effort going on to fix broken (multi)polygons in OSM and also to finally get rid of *old-style* multipolygon relations. This will hopefully lead to simpler and more efficient software.

I wanted to make you aware of the effort and get you involved in the discussions. We'd also appreciate it if you can support this effort in any way. Find all the details at http://area.jochentopf.com/.

If that would be helpful for you, I can provide (daily updated) error lists or something like it.

**Comment by frodrigo** [comment]
Item about multiplygons:
* 1170/2 Inconsistant multipolygon nature with members nature http://osmose.openstreetmap.fr/en/errors/?item=1170&class=1&useDevItem=all
* 1170/3 Inconsistant multipolygon member nature http://osmose.openstreetmap.fr/en/errors/?item=1170&class=3&useDevItem=all
* 1170/11701 Inadequate role for multipolygon http://osmose.openstreetmap.fr/en/errors/?item=1170&class=11701&useDevItem=all
* 1170/11702 Inadequate member for multipolygon http://osmose.openstreetmap.fr/en/errors/?item=1170&class=11702&useDevItem=all
* 1170/11703 Missing outer role for multipolygon http://osmose.openstreetmap.fr/en/errors/?item=1170&class=11703&useDevItem=all
* 1170/11704 This multipolygon is a simple polygon http://osmose.openstreetmap.fr/en/errors/?item=1170&class=11704&useDevItem=all
* 1040/1 Invalid polygon http://osmose.openstreetmap.fr/en/errors/?item=1040&class=1
* 1040/2 Invalid multipolygon http://osmose.openstreetmap.fr/en/errors/?item=1040&class=2
* 6010/* Open relation type=multipolygon http://osmose.openstreetmap.fr/fr/errors/?item=6010

Related items:
* 1170/1 Double inner polygon http://osmose.openstreetmap.fr/en/errors/?item=1170&class=1
* 1170/4 Should be polygon, part of multipolygon or not having area tag http://osmose.openstreetmap.fr/en/errors/?item=1170&class=4
* 1160/1 Large relation http://osmose.openstreetmap.fr/en/errors/?item=1160&class=1
* 1240/12401 Way with one node http://osmose.openstreetmap.fr/en/errors/?item=1240&class=12401
* 1100/1100 Unclosed area http://osmose.openstreetmap.fr/en/errors/?item=1100&class=1100

All this checks are agnostic about the old and new fashioned multiplygon, as in Osmose we try to not force a way of mapping. But the old way is now clearly deprecated. I think we already have a large part of checks done. So we just need to unsupport the old fashioned multipolygon in existing analysers and add a new check to report thus as issues.
