### ISSUE TITLE
Camp pitches outside a camp site doesn't detect MP tourism=camp_site

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1898]
item 1290
class 1
https://osmose.openstreetmap.fr/fr/issue/98a6432b-8cd0-5e05-0d5c-d0e732818b9c
https://www.openstreetmap.org/way/686628047
https://www.openstreetmap.org/relation/14572936

**Comment by Famlam** [comment]
Seems deployed :)
