### ISSUE TITLE
False positive issue: Unknown access value "official" for key "foot"

### ISSUE THREAD

**Issue by zstadler** [osm-fr/osmose-backend#1907]
[The wiki](https://wiki.openstreetmap.org/w/index.php?title=Tag:access%3Dofficial&uselang=en) says:

> The value [*](https://wiki.openstreetmap.org/wiki/Key:*)=official must be used with a specific mode of transport. Examples: [bicycle](https://wiki.openstreetmap.org/wiki/Key:bicycle)=[official](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Dofficial) or [foot](https://wiki.openstreetmap.org/wiki/Key:foot)=[official](https://wiki.openstreetmap.org/wiki/Tag:foot%3Dofficial).

Therefor, an _**Unknown access value "official" for key "foot"**_ issue, [such as this issue](https://osmose.openstreetmap.fr/en/issue/e5c61eed-7120-9e4a-57f3-ba94167cd097), is a false positive.

**Comment by zstadler** [comment]
As far as I understand, the "deprecated" status is misleading. There was a proposal, but that proposal was abandoned. That does not make the value "officially deprecated".

I could not find any evidence of an official deprecation process, as the status suggests. If there is any, I would appreciate understanding what was the proposed alternative tagging for "official".

**Comment by Famlam** [comment]
Unofficially disrecommended in any other way also seems enough reason for me not to implement support for it.
Besides that, it's numbers are only going down in favor of designated.

**Comment by zstadler** [comment]
Thanks for providing the alternative tagging for "official", which is missing from the wiki page.
