### ISSUE TITLE
"Call" from OGC Service of a SDI regional plateform ?

### ISSUE THREAD

**Issue by jerbou** [osm-fr/osmose-backend#1908]
We have callback from our CKAN ressource manager not found.

CKAN_CURRENT_URL | '/dataset/e2ea75c7-0c44-4894-bd70-6c59a2e665da/resource/806a9dc0-e31d-47a9-ab8d-9da7f6401085/service_proxy?SERVICE%3DWFS%26VERSION%3D2.0.0%26REQUEST%3DGetFeature%26TYPENAME%3Dpei_b80f3a5%26OUTPUTFORMAT%3Dgeojson%26CRSNAME%3DEPSG%3A4326'

HTTP_USER_AGENT | 'python-requests - https://osmose.openstreetmap.fr/'

We made contact with the producer of the data, we made corrections, and we want to discuss / exchange with the people from Osmose who made the call. 

The URI and the url from the dataset :
https://trouver.ternum-bfc.fr/dataset/points-deau-incendie-pei-du-sdis-cote-dor/
the ressource has changed, and we want to stop the raise of the error, and the people "behind" Osmose user have to change / correct the OGC call (the "win" a correct ressource, and we "win" to stop a error message.)

The correct call for the ressource would be : (geojson)
https://trouver.ternum-bfc.fr/dataset/230e8d9c-8a4d-446c-b910-7d1f85aff047/resource/b991c949-8068-4f9d-ba6a-7765eb2e0504/service_proxy?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAME=poteaux_incendie_a11c796&OUTPUTFORMAT=geojson&CRSNAME=EPSG:4326

Best Regards.
IDéO BFC team

This issue is kind of related to  https://github.com/osm-fr/osmose-backend/issues/1166

**Comment by frodrigo** [comment]
Thank you for your report. Fixed, but not deployed yet.

**Comment by frodrigo** [comment]
Done.
