### ISSUE TITLE
Item 4130 - Marker jumps around, changing issue id

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1912]
The screenshots are from: https://osmose.openstreetmap.fr/nl/map/#zoom=16&lat=51.83874&lon=5.86743&item=4130&level=1%2C2%2C3&tags=&fixable

Item 4130 / class 1

The marker jumps around and (due to this) the issue ID changes all the time. Hence, if I want to mark this one as a false positive, I would have to mark it a dozen of times. 

For example,
- on 12-6 the issue ID was https://osmose.openstreetmap.fr/nl/issue/15da88fd-869f-8342-1c1e-690314061fd1
- on 20-6 the issue ID was https://osmose.openstreetmap.fr/nl/issue/2132165d-c7a3-8a5d-8908-f3d6a195805a

![image](https://github.com/osm-fr/osmose-backend/assets/1315520/28089086-1a77-4d4f-9b51-23fd54aa399b)
![image](https://github.com/osm-fr/osmose-backend/assets/1315520/5c752d38-487b-4861-ade6-7b7d10290017)
![image](https://github.com/osm-fr/osmose-backend/assets/1315520/05de0f2f-644a-4b41-bab7-5b5ecdd7ed22)

I guess there should be an `ORDER BY id` or `ORDER BY tid` at the end of the query?

**Comment by frodrigo** [comment]
Not sure. Because sub query already ordered. It is not required by SQL, but I think postgres keep the order. on the the group by.

We can try to refactor all order by to the main query.

**Comment by frodrigo** [comment]
@Famlam do you think it is ok now ?

**Comment by Famlam** [comment]
I'll check tonight. For some reason I can't find the marker for the item in the first post

**Comment by Famlam** [comment]
Seems pretty stable :)
