### ISSUE TITLE
Allow tag combination amenity=waste_basket and highway=street_lamp 

### ISSUE THREAD

**Issue by VladimirMorozov** [osm-fr/osmose-backend#1919]
For tags
amenity=waste_basket
highway=street_lamp 

An issue is reported:
Tag conflict
Conflict between tags: amenity, highway

If iD editor and StreetComplete support adding waste baskets to bus stops, then adding waste baskets to street lights when they are directly attached to them shouldn't be a problem.

Reported by:
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Incompatibles.py#L30
Example:
https://osmose.openstreetmap.fr/en/issue/1160bab1-e00d-f600-c55e-0dd5d0dff32e
https://www.openstreetmap.org/node/10129722119

**Comment by Famlam** [comment]
Shouldn't this be https://wiki.openstreetmap.org/wiki/Key:bin when combined in a single object?

**Comment by VladimirMorozov** [comment]
Not really clear from wiki, but it does avoid problems with "One feature, one OSM element" practice.
