### ISSUE TITLE
Item 8031: confusion sur les valeurs de school:FR

### ISSUE THREAD

**Issue by PmzDev** [osm-fr/osmose-backend#192]
Bonjour,
Dans l'analyse d'intégration des écoles, il y a beaucoup de faux positifs dus à une confusion entre school:FR=primaire et school:FR=elementaire.
Une école primaire a des classes de niveau maternelle et élémentaire.
Une école élémentaire a des classes du CP au CM2.
Cette distinction est claire dans le fichier de data.gouv.fr, mais les tags proposés par osmose sont inversés.

**Comment by frodrigo** [comment]
It's not the first time we have issues with this.
We already switch from élémentaire to primaire because primaire is more generic and includes élémentaire.
The original data are poorly clasified and have primaire lot of primaire schools classified with élémentaire.

**Comment by Bibi56** [comment]
I wanted to create a similar issue.
https://osmose.openstreetmap.fr/fr/error/26677298235
here the name/denomination in the database explicitly includes élémentaire and it matches lib_nature . The assumption is that the name/denomination is more reliable.



identifiant | 20050
-- | --
numero_uai | 0351672C
appellation_officielle_uai | Ecole élémentaire publique la Pierre Pourprée
denomination_principale_uai | ECOLE ELEMENTAIRE PUBLIQUE
patronyme_uai | LA PIERRE POURPREE
patronyme_groupé | LA PIERRE POURPREE
secteur_public_prive | PU
adresse_uai | 5 RUE DE MONTFORT
lieu_dit_uai |  
code_postal_uai | 35380
localite_acheminement_uai | PLELAN LE GRAND
X | 320241.8
Y | 6779294.6
app | MANUEL
loc | BATIMENT
etat_etablissement | 1
nature_uai | 151
lib_nature | ECOLE DE NIVEAU ELEMENTAIRE
sous_fic | 1
column |  
probleme |

**Comment by frodrigo** [comment]
There is an open issue on it #314. Can you make stats on the data and suggest the right thing to do, please?
