### ISSUE TITLE
Allow tag combination leisure=track  and oneway=yes 

### ISSUE THREAD

**Issue by VladimirMorozov** [osm-fr/osmose-backend#1920]
For tags
leisure=track 
oneway=yes 

An issue is reported:
Tag highway missing on oneway
Tag highway missing on oneway

It can be used, for example, to map athletics=long_jump
https://wiki.openstreetmap.org/wiki/Tag:sport%3Dathletics
But also probably not a mistake on pump tracks, racing tracks, etc.

Reported by:
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag2.validator.mapcss
Example:
https://osmose.openstreetmap.fr/en/issue/09671670-01f4-4570-7eeb-28955a53e25f
https://www.openstreetmap.org/way/1122118242

**Comment by Famlam** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag2.validator.mapcss#L103

JOSM also agrees in their similar rule ([issue link](https://josm.openstreetmap.de/ticket/19821)), see https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss#L500

**Comment by frodrigo** [comment]
Thank you @Famlam, merged, but not deployed yet.

**Comment by Famlam** [comment]
Seems deployed
