### ISSUE TITLE
Noexit on way with multiple exits on way with noexit

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1928]
item | 3210
class | 2
https://www.openstreetmap.org/way/218988087
the NE part of the way doesn't have any exist

PS: in the meantime, I fixed it by moving noexit=yes from way to the ending node

**Comment by Famlam** [comment]
https://github.com/osm-fr/osmose-backend/blob/0e316d065187addcff22b53f87513501ff17f4eb/analysers/analyser_osmosis_highway_noexit.py#L65

I suspect it's accidentally matching (and thus counting) all nodes, instead of end nodes, for w1

**Comment by frodrigo** [comment]
No, exit include footway or any other. It is not restricted to car. Here the way is connected to the cycleway. So it has exist.

**Comment by Famlam** [comment]
Ah, true, the leftmost part of the way shouldn't have noexit=yes

**Comment by Marc-marc-marc** [comment]
the problem is that the analysis could lead you to believe that you should delete noexit=yes.
but the contributor's intention was not to say that it was impossible to take the sidewalk at the beginning of the street, but to say that the terminal node is a dead end.
it would be nice to have 2 different classes:
- the terminal node is not a dead end: suggested fix : delete noexit=yes
- the terminal node is a dead end even if an intermediate node can be connected to another way: move the noexit=yes to the ending node.
(perhaps the opportunity to add this way -> ending node tag move also for the undetected case of ways without an intermediate node connected)
