### ISSUE TITLE
Item 3050 : add an exception for ref:refuges.info

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#1929]
This key is formed from the domain name [refuges.info](https://www.refuges.info).

item: 3050
class: 30501

Examples:
- [Cabane forestière du Bois-Durat](https://osmose.openstreetmap.fr/fr/map/#zoom=15&lat=44.71071&lon=6.64252&item=3050&level=1&issue_uuid=c2accdb6-5a35-cc63-cd0c-9ee4c80f766d)
- [List](https://osmose.openstreetmap.fr/fr/issues/open?country=france_rhone_alpes_haute_savoie&item=3050) in france_rhone_alpes_haute_savoie for item 3050.

See also #1055

**Comment by pyrog** [comment]
Duplicate of #1823

**Comment by alkino** [comment]
Should be closed

**Comment by frodrigo** [comment]
Before closing, wait for confirmation on the frontend
 https://osmose.openstreetmap.fr/en/issues/open?item=9002&class=9002011

**Comment by Famlam** [comment]
I think something may be wrong as the issue still exists on the frontend:
https://osmose.openstreetmap.fr/nl/map/#item=9002&class=9002011&limit=500&zoom=17&lat=56.105319&lon=36.5101&level=3&tags=&fixable=

**Comment by frodrigo** [comment]
We have changed Osmose. But now the same issue is raised from JSOM Validation rules.

https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/deprecated.mapcss#L680

Maybe it was not a so good idea to accept this change...

**Comment by Famlam** [comment]
Sorry, wrong link.
https://osmose.openstreetmap.fr/nl/map/#item=3050&class=&limit=500&zoom=18&lat=56.105333&lon=36.511538&level=1%2C2%2C3&tags=&fixable=&issue_uuid=49168c05-0169-cab7-4efc-cf234d04aec4

Well, there's no point in having a duplicate warning, and definitely not a prio-high for what seems like an (locally) long-accepted and documented key :). So *personally* I support this whitelist. But it needs to be fixed to work, the current fix seems to be incorrect

**Comment by frodrigo** [comment]
> But it needs to be fixed to work, the current fix seems to be incorrect

I made a PR for that #1959

Meanwhile. It also has to be fixed on JOSM side.

**Comment by Famlam** [comment]
@pyrog Can you file the necessary issue report at JOSM?

**Comment by frodrigo** [comment]
> @pyrog Can you file the necessary issue report at JOSM?

Now it is ok on Osmose side.
