### ISSUE TITLE
Wrong name for issue item=0&class=1

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#1931]
for ex look at
http://osmose.openstreetmap.fr/fr/issues/open?country=afghanistan&item=0&class=1

something wrong :
- class 1 is with sax and Osmosis_Building_Overlaps ?
- name of the class 1 "This indoor room should have a door"

**Comment by didier2020** [comment]
it‘s now fixed ...

**Comment by frodrigo** [comment]
Class overwride are random. Depending of update order.

**Comment by frodrigo** [comment]
Bad item=0 was removed here
https://github.com/osm-fr/osmose-backend/commit/046dd2243808c701f129fca4f0e2c4d38c2c9f44#diff-8f4a60d6a610930798736bfedf269112cfb944d56e7158333229650ce8268289L16

Frontend cleaned.
