### ISSUE TITLE
Invalid polygon reported on highway=raceway

### ISSUE THREAD

**Issue by VladimirMorozov** [osm-fr/osmose-backend#1935]
Racetrack is checked for polygon issue while it should be treated as a way

https://osmose.openstreetmap.fr/en/issue/a0843393-6374-c070-4408-972dd9d74e02
https://www.openstreetmap.org/way/232319662
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_polygon.py#L94

**Comment by Famlam** [comment]
I suspect the easiest solution is just to rename the title of the error to "Invalid polygon or closed way". After all, that's what this analyser checks, and the warning it gives (Ring Self-intersection) is valid.

**Comment by frodrigo** [comment]
> I suspect the easiest solution is just to rename the title of the error to "Invalid polygon or closed way". After all, that's what this analyser checks, and the warning it gives (Ring Self-intersection) is valid.

But the raceway here is not invalid. We may rather add an other exception like roller_coaster ?

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_polygon.py#L35

**Comment by Famlam** [comment]
> But the raceway here is not invalid

It crosses itself on two occasions. Wasn't that illegal for any way, regardless of it being a polygon, closed way or open way?
(Also for roller_coasters. Which usually also cross at different levels, but that's a different story. It was added in https://github.com/osm-fr/osmose-backend/commit/e53467c9ed2bff14b5aec4a52c315010950f6000 so I don't know which rollercoaster triggered this)

Anyway, your call if you want to warn for this. Unlike polygons, where rendering is very difficult if it's invalid, I don't see the big issue for ways (assuming that routing-data-users split ways internally at every crossing)

**Comment by frodrigo** [comment]
We should only do this check for closed ways with tags meaning for polygon.
