### ISSUE TITLE
False positive in 8290/1 could show issue with France polygon

### ISSUE THREAD

**Issue by flacombe** [osm-fr/osmose-backend#1939]
Hello

It seems that https://osmose.openstreetmap.fr/fr/issue/779edf16-8f40-e27b-fca1-3156a698449c (and many neighboring similar issues) around https://www.openstreetmap.org/?mlat=50.9499904&mlon=2.1729847#map=14/50.9469/2.1680 could be caused by too restrictive France polygon.

These Osmose issues are false positive.
https://www.openstreetmap.org/node/988122295 exists in OSM and it should be conflated properly.

Is there any duplicate issue about that?

Regards

**Comment by frodrigo** [comment]
Same as #1493

**Comment by frodrigo** [comment]
Close as duplicate.
