### ISSUE TITLE
wrong geocoding for townhall

### ISSUE THREAD

**Issue by JPapir** [osm-fr/osmose-backend#1943]
Hi,
I have an issue similar to #150 with the geocoding of a town hall. The difference is that the geocoding in the source (service-public.fr) seems to be perfectly correct : 

https://lannuaire.service-public.fr/grand-est/haute-marne/61149ba9-bad2-4e0e-9237-2a63da5cd845

Whereas [in osmosis, it's a few km wrong](https://osmose.openstreetmap.fr/fr/map/#zoom=17&lat=47.926159&lon=4.863059&item=xxxx&level=1%2C2%2C3&issue_uuid=e95cbd0b-f311-5964-433e-a4ed25834746) : 

![image](https://github.com/osm-fr/osmose-backend/assets/47297745/5fbc62fa-4f13-4143-a6bb-9d95b07153e8)

Item : 8110 / Class : 1
Source : [402686](https://osmose.openstreetmap.fr/fr/issues/open?item=xxxx&source=402686)

Even more disturbing : the object is already there in OSM ! [see here](https://www.openstreetmap.org/node/9918900042)

Question : why ?

My idea : the issue is located with the address, and in Dancevoir, there is a "rue de Verdun" similar to the "place de Verdun" of the townhall. But still : why is there no match between the existing townhall and the dataset which is used (and which is up-to-date, cf service-public.fr) ?

**Comment by frodrigo** [comment]
It use a 3 year old version
https://github.com/osm-fr/osmose-backend/blob/dev/merge_data/service_public_FR.csv.bz2

Almost all data from Opendata are fetched automatically an regularly. But not this one.

**Comment by frodrigo** [comment]
@nlehuby submitted a PR, now we have automatic update. But townhalls are no more part of the result. @nlehuby it is on purpose ?

@nlehuby it is also missing DROM+NC, still on purpose ?

**Comment by nlehuby** [comment]
which DROM is missing ?

![image](https://github.com/osm-fr/osmose-backend/assets/919962/7ecf0c2d-4961-408d-bb62-33188f584cd1)

**Comment by frodrigo** [comment]
![Capture d’écran_2023-07-18_17-55-55](https://github.com/osm-fr/osmose-backend/assets/1785486/8c42b711-6a37-482f-b8a7-ed03801a211b)

**Comment by frodrigo** [comment]
humm. Not sure in fact. Need to clean `Merge_ServicePublic`.

**Comment by frodrigo** [comment]
> humm. Not sure in fact. Need to clean Merge_ServicePublic.

I clean the results... but I clean too many thing, it will come back any way.
