### ISSUE TITLE
Dupplicate report on drivethroughs loop

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1946]
osmosis_highway_deadend drivethroughs `service=drive-through` (item=1210 class=5 france_rhone_alpes_isere osmosis_highway_deadend) reports duplicate issue on loop. Duplicate report is one issue to the frontend end. But it should report nothing as the end are not dead and (it is a loop).

Secondary issue. As it is a loop, there is entrance / exits at other nodes.

This ways is in this case
https://www.openstreetmap.org/way/1186289900

Maybe the only case world wide.

https://buildbot.osmose.openstreetmap.fr/#/builders/580/builds/1042/steps/3/logs/stdio

**Comment by Famlam** [comment]
Probably just checking that the drive through highway matches `AND NOT is_polygon` should fix this without impacting other drive-throughs, right?

(Floating islands are dealth with in another analyser)

**Comment by frodrigo** [comment]
Yes. Please look at this if you have free time.

**Comment by Famlam** [comment]
Seems deployed and fixed :)
