### ISSUE TITLE
Flag urls with click trackers

### ISSUE THREAD

**Issue by ivanbranco** [osm-fr/osmose-backend#1950]
I would like to propose a check to report click trackers in urls, such as: https://overpass-turbo.eu/s/1xaq

**Comment by Famlam** [comment]
Sounds like a nice idea (such tracker query parameters don't make sense to have in OSM.
I wonder if we'd be allowed to use the list from here:
https://github.com/duckduckgo/privacy-configuration/blob/main/features/tracking-parameters.json

**Comment by Famlam** [comment]
It's implemented and deployed :)
https://osmose.openstreetmap.fr/nl/map/#item=3093&source=&class=30934&username=&bbox=&zoom=7&lat=50.1&lon=6.507&level=1%2C2%2C3

**Comment by ivanbranco** [comment]
Thanks for your work
