### ISSUE TITLE
Waste basket hang on Street lamp create false positives

### ISSUE THREAD

**Issue by angoca** [osm-fr/osmose-backend#1952]
On elements like highway=street_lamps could be attached amenity=waste_basket. This creates a false issue.

This is an example: https://www.mapillary.com/app/?lat=4.709484429201893&lng=-74.0572447546972&z=19.47963180022495&pKey=856747492692701&x=0.6234034243391854&y=0.5078832528281554&zoom=0&focus=photo

**Comment by Famlam** [comment]
See https://github.com/osm-fr/osmose-backend/issues/1919
