### ISSUE TITLE
Handle multilingual wikipedia tags

### ISSUE THREAD

**Issue by Crashillo** [osm-fr/osmose-backend#1953]
Since some applications, such as OsmAnd, are able to display multiple wikipedia links, in those places where several languages co-exist, has become quite useful to include them (see [example](https://www.openstreetmap.org/relation/339549))

These uses face directly the rule [_Same wikipedia topic on other language_](https://osmose.openstreetmap.fr/es/issues/open?item=3031&class=30317), so the point is about implementing some exception rules to allow dealing with more than one language, according to the `default_language=*` of the surrounding area or specific rules (similar to https://github.com/osm-fr/osmose-backend/issues/1285)

So the point would be not displaying the following errors if the region has multiple languages:
https://github.com/osm-fr/osmose-backend/blob/71469f20f9b9c03542c9a9b38bfc059f84ee8ba5/plugins/TagFix_Wikipedia.py#L81-L86

In addition, the JOSM validation rules' behaviour referring to `wikipedia:lang` tags is quite similar to the `name:lang`, that is:
```
name=A
name:es=A
name:fr=B
```
the default tag must match with any language listed, therefore:
```
wikipedia=A
wikipedia:es=A
wikipedia:fr=B
```

**Comment by frodrigo** [comment]
Osmose is not about implementing new concepts on OSM, is about comply with existing one. The rule is to list only one wiki link in any language and let applications deal with inter wiki links to switch to other languages.

**Comment by frodrigo** [comment]
Ok, editing war is is valid point for me. We already implemented once for Ukraine 
https://github.com/osm-fr/osmose-backend/blob/dev/plugins/TagFix_Wikipedia.py#L134

Yes multilingual configuration may be used for that.

**Comment by ivanbranco** [comment]
> May you show me a screencast? I just tried in OsmAnd tapping on US places and their wikis are displayed in english
> 
> As far as I see, no application yet is able to deal with wikipedia interlanguage links. They show what it's by default.

![image](https://github.com/osm-fr/osmose-backend/assets/94002623/26f6510b-a0f0-4230-80a6-fc8d27fcf7c3)

**Comment by Crashillo** [comment]
@ivanbranco yeah, I turned that setting on, but that's not what I was expecting: you need to download previously all the wikipedia data in order to preview in your language, and you will see wikipedia POIs all over the map. My desired behaviour here will be able to open your browser picking the proper language (but this is a different matter out of scope)

**Comment by Famlam** [comment]
Fix deployed!
