### ISSUE TITLE
"Segregated" on tram crossings

### ISSUE THREAD

**Issue by tomeko1** [osm-fr/osmose-backend#1954]
Hi!

There is false positive error on foot+bicycle path crossing tram line when it is correctly tagged as railway=tram_crossing + segregated=yes.
Example here: https://osmose.openstreetmap.fr/pl/issue/285f7e87-64d2-3159-7339-fd945452436a

**Comment by Famlam** [comment]
This rule originates from JOSM. Could you please report it there?
https://josm.openstreetmap.de/newticket

**Comment by tomeko1** [comment]
Ok, thanks!

**Comment by Famlam** [comment]
Please let us know when it's resolved in JOSM. We have to manually synchronize the rules into Osmose after that

**Comment by matkoniecz** [comment]
JOSM appears to not complain about this (I enabled info-level warnings)

**Comment by Famlam** [comment]
That's odd, because this rule should trigger a warning for any JOSM user:
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss#L243

```
*[segregated                   ][!highway][railway!=crossing] {
  throwWarning: tr("{0} without {1} or {2}", "{0.key}", "{1.key}", "{2.tag}");
  group: tr("missing tag");
}
```

**Comment by matkoniecz** [comment]
it is possible, or maybe I am blind

I will likely report JOSM bug then and come back here when https://github.com/osm-fr/osmose-backend/issues/1954#issuecomment-2659517953 is true not only on technicality

**Comment by Famlam** [comment]
Ok. I can at least confirm that with the latest JOSM I get this warning
