### ISSUE TITLE
Highway_Parking_Lane, duplicate issue item=31625 class=3162

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1962]
Way https://www.openstreetmap.org/way/173095901 raise duplicate issue item=31625 class=3162

With
- parking:both 	lane
- parking:both:orientation 	parallel
- parking:condition:right:maxstay 	3
- parking:left 	no
- parking:left:reason 	narrow
- parking:right 	no
- parking:right:reason 	narrow

**Comment by Famlam** [comment]
I suspect it just requires `side` to be added to this line: https://github.com/osm-fr/osmose-backend/blob/dev/plugins/Highway_Parking_Lane.py#L245
Not tested though
