### ISSUE TITLE
Detect uses of `camp_site` or `caravan_site` that should be `camp_pitch`

### ISSUE THREAD

**Issue by musshorn** [osm-fr/osmose-backend#1978]
Issue:
Mappers can incorrectly tag pitches (the actual place you would setup a tent/park a caravan) as sites (the term typically give to the area the campground covers)

Tag Info:
https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcamp_site
https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site
https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcamp_pitch

Sample overpass query: 
https://overpass-turbo.eu/s/1yqu (not sure if there's a way to pass a generic "\d" so this only finds sites named "1")

Fix:
`*_site` would be converted to `camp_pitch` and the `name` is converted to `ref`

**Comment by Famlam** [comment]
Hereby an overpass for any numeric name: https://overpass-turbo.eu/s/1FHR

As far as I can see, just reporting the combination of these two tags would only result in one obvious false positive: https://www.openstreetmap.org/way/881218963 (which is a bit weirdly tagged anyway, so I'm fine with that)

**Comment by Famlam** [comment]
Hereby the results:
https://osmose.openstreetmap.fr/nl/issues/open?item=4040&source=&class=40401&username=&bbox=

I've marked the UK one that I referred to before as a false positive.
