### ISSUE TITLE
Add ```operator:wikidata=Q2178795``` to operator RTE

### ISSUE THREAD

**Issue by phd0** [osm-fr/osmose-backend#1990]
is it possible to add ```operator:wikidata=Q2178795``` for the 3 scripts :
 * analyser_merge_power_tower_FR.py
 * analyser_merge_power_branch_FR.py
 * analyser_merge_power_substation_FR.py
 like this : 
 ```  
            static1 = {
                        "power": "tower",
                        "operator": "RTE",
                        "operator:wikidata": "Q2178795"},
```
to facilitate additions from osmosis and reduce automatic issues from id ?

**Comment by flacombe** [comment]
Yes.

I'll take that on me, shortly.
