### ISSUE TITLE
male=yes and female=yes is correct

### ISSUE THREAD

**Issue by Mannivu** [osm-fr/osmose-backend#1993]
The issue ([example](https://osmose.openstreetmap.fr/it/issue/3210b596-0dda-ab15-ed1e-fe0da703da63)) that suggests that `male=yes` and `female=yes` used in combination might be wrong should be removed for hairdressers. Based [on the Wiki](https://wiki.openstreetmap.org/wiki/Tag:shop=hairdresser#Tags_to_use_in_combination) that is the correct way to tag an hairdresser that serves both male and female people.

**Comment by frodrigo** [comment]
It comes from JOSM validators rules 
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss#L670

You can reort it to JOSM.

**Comment by Mannivu** [comment]
I didn't know this was based on JOSM Validator. I will report it there. Thank you.
