### ISSUE TITLE
Should round building be reported as a problem

### ISSUE THREAD

**Issue by bmillemathias** [osm-fr/osmose-backend#200]
I shaped a lot of round buildings (which is a typical shape for buildings in Africa) during HOT sessions for fighting malaria, now they are reported as a problem " 7011 building shape" => https://osmose.openstreetmap.fr/en/byuser/?username=baptistemm&item=7011

I'm not sure it brings some value to report round buildings as an issue.

Regards

**Comment by frodrigo** [comment]
You rigth.
