### ISSUE TITLE
"Power substation is not known from operator" give too many false positives

### ISSUE THREAD

**Issue by PtiBzh** [osm-fr/osmose-backend#2009]
https://osmose.openstreetmap.fr/en/issues/open?item=7190&class=2

This analyser (7190/2) is giving issues for all substations not known by RTE and not tagged with `substation=minor_distribution`.
Perhaps we should limit this to substations with `operator=RTE`?

Ping @flacombe

**Comment by flacombe** [comment]
Several problems occurs here and combine to lead to this increased amount of 7190/2 warnings.

Some actual `minor_distribution` substations are wrongly tagged as `distribution`
https://www.openstreetmap.org/way/149424147

Some actual `distribution` substations are missing the `substation` key.
https://www.openstreetmap.org/way/143252196

It's not desirable to merge the two substations (transmition or distribution) analysis as they have their own logic.

The best solution is to change the select of 7190/2 analysis for `distribution` substations.
The analysis should only handle the ones that have `voltage` defined **and** strictly over 50 kV.
Given problem is many of them have values like `voltage=63000;20000` which aren't suitable for tests like `> 50000`.

Is it possible to find a workaround for such a condition `63000;20000 > 50000` in select clauses @frodrigo?

**Comment by frodrigo** [comment]
> Is it possible to find a workaround for such a condition 63000;20000 > 50000 in select clauses 

Select deals with multiple values, but not `>`.
https://github.com/osm-fr/osmose-backend/blob/dev/doc/4-Merge.md#select
Can you use a list of voltages ?

**Comment by flacombe** [comment]
That would be way better indeed, thanks.

#1996 lead to an increase of the problem I didn't imagine.
https://osmose.openstreetmap.fr/fr/issues/graph.png?item=7190&class=2&start_date=2023-08

I'll fix this shortly.

**Comment by Famlam** [comment]
If not, how about a regex match to find >50000V entries? For example (untested)
`(;|^)(\d{6,}|[5-9]\d{4})(;|$)`

**Comment by flacombe** [comment]
I'm currently trying this select:

```python
tags = [
          {"power": "substation", "substation": ["transmission"]},
          {
                "power": "substation",
                "substation": [False, "industrial", "generation", "traction", "distribution", "converter", "transition", "compensation"],
                "voltage": ["400000", "380000", "320000", "225000", "220000", "150000", "90000", "63000", "45000", "42000"]}
]
```

It doesn't match such areas which still appears in 8280/1
https://www.openstreetmap.org/way/230168571

Are we sure voltage=225000;15000 matches against the voltage list?

**Comment by frodrigo** [comment]
Right it is not implemented here. It is only supported for multiple ref.

Nevertheless it should be easy to implement here https://github.com/osm-fr/osmose-backend/blob/dev/analysers/Analyser_Merge.py#L1065

**Comment by flacombe** [comment]
I give a try to `cond = "string_to_array(" + k_value + "::text, ';')" + " && ARRAY['{}']".format("', '".join(map(lambda i: i.replace("'", "''"), filter(lambda i: i is not False, v))))`

**Comment by flacombe** [comment]
It is now fixed, only 247 warnings remain.
https://osmose.openstreetmap.fr/fr/issues/open?item=7190&class=2&country=france_local_db
