### ISSUE TITLE
Fractioned building not detected

### ISSUE THREAD

**Issue by bmillemathias** [osm-fr/osmose-backend#2010]
Hi there,

while reviewing fractioned building in the area I saw this one was not reported
https://www.openstreetmap.org/way/222368724/history

Best

**Comment by frodrigo** [comment]
It is not fractioned building here.

The small parts are with `wall=no` tag.

**Comment by bmillemathias** [comment]
sorry, this was not clear, I merged the building now (changeset 140884586
<https://www.openstreetmap.org/changeset/140884586>), but I referred to
before this changeset.
it was like this before
[image: image.png]
ways are 222368724 (small triangle).

is it more clear ?

thanks

**Comment by frodrigo** [comment]
It is based on an heuristic, and cannot catch all cases.
