### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by debyos** [osm-fr/osmose-backend#2014]
I am translating the [backend part of Osmose](https://app.transifex.com/openstreetmap-france/osmose/translate/#hu/backend/) and have some question where the English original may not be entirely clear:

_Check of tags `ref:INSEE` and `name` are consistent with the [COG database](https://www.insee.fr/fr/information/2560452)._

My question: Does this mean that they **should be** consistent with the database?

_The names on `place=*` may differ from the COG of INSEE, especially for merged city. It also happens in several occasions that local authorities are at odds with INSEE. **In this case, that's always been a priority for the field on OSM.**_

My question: What does the last phrase (in bold mean)? Should we use the code of INSEE or that one used by the local authorities? Or something completely different?

**Comment by frodrigo** [comment]
Here field means local authorities / ground

I propose the change this sentence by

> In this case, that's always been a priority for the local authorities / ground usage on OSM.

**Comment by Famlam** [comment]
I must say I also don't understand what the new suggestion means 🙈 . It's not clear to me where *that* refers to.
Do you perhaps mean: `In this case, always use the information from local authorities / ground usage`?
(Note: I have no clue what INSEE is; just replying to the grammar)

**Comment by debyos** [comment]
INSEE is the French statistics authority which gives an official code for
towns and villages:
https://en.wikipedia.org/wiki/INSEE_code

Famlam ***@***.***> ezt írta (időpont: 2023. szept. 10., Vas
0:19):

**Comment by frodrigo** [comment]
> Do you perhaps mean: In this case, always use the information from local authorities / ground usage?

Yes better.

**Comment by debyos** [comment]
Thank you, I have improved the HU translation.

**Comment by Famlam** [comment]
I'm afraid the updated translations were not synchronized yet, so it is possible that they might need to be re-translated in the next update 🙈 . Correct @jocelynj ?

**Comment by jocelynj** [comment]
Yes, you're right: the strings will need to be retranslated. I'm not sure if we can keep the previous translations, as they might be wrong, but it might be better than nothing. Any thought?

**Comment by Famlam** [comment]
> I'm not sure if we can keep the previous translations, as they might be wrong, but it might be better than nothing. Any thought?

I think we could keep it, if you can check the French translation is ok. The only language that I don't think we can check first-hand is Japanese, but I don't know how big the Japanese mapping community is in France (as this is a French plugin) and the string probably isn't too bad I suspect, even with the old translation?

---

> Check if tags `ref:INSEE` and `name` are consistent with the [COG database](https://www.insee.fr/fr/information/2560452)

Regarding this one it's only 3 existing translations (DE, NL, JA) + now HU. NL and DE are correct (the third one - Japanese - I cannot tell). 

---

> In this case, always use the information from local authorities / ground usage.

Regarding this one it's only in FR and JA (and now HU). If the French one is ok (which you should check for me :) ), I guess we can keep it (despite not knowing the JA one).
