### ISSUE TITLE
Translation question: prefixes

### ISSUE THREAD

**Issue by debyos** [osm-fr/osmose-backend#2015]
[_You can not simultaneously set a tag and the variants with `forward`, `backward` or `both_ways` **pre**fixes._](https://app.transifex.com/openstreetmap-france/osmose/translate/#hu/backend/446142787)

These seem rather [suffixes](https://wiki.openstreetmap.org/wiki/Forward_%26_backward,_left_%26_right)...

**Comment by Famlam** [comment]
From plugin highway_lanes.

You are right, this is a typo.

Probably we can bulk edit this in all translations after updating the plugin, @jocelynj ?

**Comment by jocelynj** [comment]
I'm not sure if it is good to replace "prefixes" by "suffixes" in translations, as it is likely that we have translated "prefixes" everywhere. I would suggest to just update the original string, and regenerate translations.

**Comment by Famlam** [comment]
Good point, forgot about that.
