### ISSUE TITLE
Translation question - local short code

### ISSUE THREAD

**Issue by debyos** [osm-fr/osmose-backend#2016]
_[Local short code can not be internationalized](https://app.transifex.com/openstreetmap-france/osmose/translate/#fr/backend/191441719)_

What does this mean? Could you provide an example?

**Comment by Famlam** [comment]
This is referring to shortened local phone numbers. Sometimes there's a short phone number that only works when called via a local phone

**Comment by Famlam** [comment]
For example, the city of Nijmegen can be called by a 5 or 10 digit phone number, but if you want to call from abroad, you have to use the 10 digit number (prefixed with +31). The short number cannot be called from outside.

**Comment by frodrigo** [comment]
> For example, the city of Nijmegen can be called by a 5 or 10 digit phone number, but if you want to call from abroad, you have to use the 10 digit number (prefixed with +31). The short number cannot be called from outside.

Not exactly, short number does not have a long version. Most know short number are for call emergency like 112 in EU or 911 in US. But there also other short numbers for commodity or commercial usage.

**Comment by Famlam** [comment]
Yes, the 10 digit one in my example is different from the 5 digit one, not a shortened version. I should have clarified that.

**Comment by Famlam** [comment]
@debyos does this answer your question?

**Comment by debyos** [comment]
Yes, it is fine so.
