### ISSUE TITLE
Translation question - "not known from operator"

### ISSUE THREAD

**Issue by debyos** [osm-fr/osmose-backend#2019]
- [Power connection _not known from operator_](https://app.transifex.com/openstreetmap-france/osmose/translate/#fr/backend/416523655)
- [Power substation is _not known from operator_](https://app.transifex.com/openstreetmap-france/osmose/translate/#fr/backend/416523660?q=text%3Apower)

What do these mean?
The operator of the power substation is not known?

And: what is a **power connection**? A line? A substation? All these (plus…)?

**Comment by frodrigo** [comment]
cc @flacombe

**Comment by flacombe** [comment]
''Not known from operator'' means the OSM feature is not found in the open data file (produced by the operator).
It may have been destroyed on ground or mistaken in OSM.

A power connection, in `merge_power_branch_FR` context, is a identical to a branch (a branch is a special kind of connection).
It occurs on a support (or in a junction box underground) which are not substations nor a line.

**Comment by debyos** [comment]
Thank you. Then I would suggest to use:

- Power **line branch** not known **by** the operator
- Power substation not known **by** the operator

**Comment by flacombe** [comment]
Understood thank you.

I'll combine it with my next PR.
