### ISSUE TITLE
Translation question - closed parking

### ISSUE THREAD

**Issue by debyos** [osm-fr/osmose-backend#2023]
[It is not street parking, it is **only** closed (with or without fee, for all or not...)](https://osmose.openstreetmap.fr/en/issue/81be4203-7fe5-c5a0-267c-622cb788189e)

What does it mean that the parking in _only_ closed?

**Comment by Famlam** [comment]
@vinber I think this is from https://github.com/osm-fr/osmose-backend/commit/5dc564492f26f2e1270b2b89396acfbad918e61e
Do you perhaps remember what you meant here?

**Comment by vinber** [comment]
I don't remember exactly and the link above doesn't work for me.

only closed -> off-road parking

**Comment by Famlam** [comment]
Thanks @vinber! Applied (but not live yet)

**Comment by Famlam** [comment]
Deployed, e.g. https://osmose.openstreetmap.fr/nl/issue/21728818-5b20-3bd6-af63-1bb70de16f04
