### ISSUE TITLE
Unconnected stream or wrong way flow

### ISSUE THREAD

**Issue by alpingio** [osm-fr/osmose-backend#2030]
Hi
I'm analyzing some issue reported by osmose issues (level3) 
I found many "Unconnected stream or wrong way flow" but they are connected and the flow is correct
Some examples
https://www.openstreetmap.org/way/104031142
https://www.openstreetmap.org/way/59762881
https://www.openstreetmap.org/way/246896742
https://www.openstreetmap.org/way/66471384
Could I report them as false positive?
Thanks!

**Comment by frodrigo** [comment]
It is a common issue about stream linking.

The way must be connected even into lake.

**Comment by alpingio** [comment]
In fact they are connected to a lake...or I'm wrong?
Thank you

**Comment by alpingio** [comment]
Maybe I understand , I should add the tag water=lake, but other lakes are resevoir https://wiki.openstreetmap.org/wiki/Tag:water=reservoir
like this one
https://www.openstreetmap.org/way/59763292
that it is reported by osmose
I've to report as false positive?
Thanks

**Comment by frodrigo** [comment]
No, the water ways must also flow into the lake like this
https://www.openstreetmap.org/way/51901661

**Comment by alpingio** [comment]
Ah... ok! Now is clear... thank you!
