### ISSUE TITLE
Country filter on API seems dysfonctionnal

### ISSUE THREAD

**Issue by NicolasPyIGN** [osm-fr/osmose-backend#2045]
Hi,

When requesting, by eg, https://osmose.openstreetmap.fr/api/0.3/issues.json?limit=10000&country=france*&full=true&status=false&start_date=2023-04-01&end_date=2023-10-12&useDevItem=false&source=14708&class=1&item=7170 I got a list of Osmose issues.

The first one is 4024471b-58d8-7577-1f88-a7ae8f9d1045 located http://osmose.openstreetmap.fr/fr/map/#zoom=14&item=7170%2C8530&level=2&lat=50.92911&lon=1.86364.

So, I hoped the requests return more than 0 Osmose issues...
https://osmose.openstreetmap.fr/api/0.3/issues.json?limit=10000&country=france_nord_pas_de_calais*&full=true&status=false&start_date=2023-04-01&end_date=2023-10-12&useDevItem=false&source=14708&class=1&item=7170
or
https://osmose.openstreetmap.fr/api/0.3/issues.json?limit=10000&country=france_nord_pas_de_calais_pas_de_calais*&full=true&status=false&start_date=2023-04-01&end_date=2023-10-12&useDevItem=false&source=14708&class=1&item=7170

So:
_Osmose issues exist at the france* country filter
_Osmose issues disappear at the france sub country filter (https://osmose.openstreetmap.fr/api/0.3/countries)
_Osmose issues still get requested by the frontend

Did I missed something ?

**Comment by frodrigo** [comment]
> Did I missed something ?

country param is not hierarchical. It may looks like it, but is is not. country is a list of values, could be filtered with `*`.

http://osmose.openstreetmap.fr/api/0.3/countries

Your osmose issue is linked to analyser running on country value "france". Note there is also an other special value for France "france_local_db".

Note: for now only France have such thing, as run are not centralized.

**Comment by NicolasPyIGN** [comment]
Ok, got it ; may the documentation be completed in order to be clearer on these point ?
Thanks anyyway for the prompt answer.
