### ISSUE TITLE
False poitive: markings

### ISSUE THREAD

**Issue by GITMichaelK** [osm-fr/osmose-backend#2055]
OSMOSE reports issues `markings` is a value for key `parking:[side]:reason / parking:[side]:restriction:reason` but reagring the [WIKI](https://wiki.openstreetmap.org/wiki/Street_parking#Marked_parking_spaces) this is absolutely correct.

**Comment by GITMichaelK** [comment]
Thanks @Frédéric Rodrigo for your reply,
> @GITMichaelK Do you have an Osmose link with this ?
Im sorry, I don't as I marked each one for myself as false-positive. May be, you have a chance to look at my history on OSMOSE: https://osmose.openstreetmap.fr/en/byuser/MichaelFS?level=3
I tried, but couldn't manage to get it.
But OVERPASS provides several nodes for this ...

> markings seam to be already supported : https://github.com/osm-fr/osmose-backend/blob/dev/plugins/Highway_Parking_Lane.py#L88
Sorry, I don't understand that page.
But I hope, my original text
> OSMOSE reports issues markings is a value for key parking:[side]:reason / parking:[side]:restriction:reason but reagring the WIKI this is absolutely correct.
explains my issue.
Please let me know, if con can provide more ...

Regards from Germany
Michael

**Comment by Famlam** [comment]
Are you referring to for example [this way](https://www.openstreetmap.org/way/154323381) that generates [this Osmose issue](https://osmose.openstreetmap.fr/en/issue/f2c0e3f7-3bbb-23a8-a4c7-4925583f28b8), e.g., a way tagged with `parking:left=markings`?

If so, the Osmose warning is correct: `markings` is not a documented value for `parking:left`.
Based on what I see on [Mapillary](https://www.mapillary.com/app/?z=17&lat=52.125541586694&lng=8.6780948568548&pKey=526069138530748&focus=photo&x=0.5345139724074132&y=0.6087760794270354&zoom=0.47974687276368483) I think the correct tagging would be: `parking:left=half_on_kerb`

If there are markings (I don't see them on Mapillary, but those are images from 2021) then a _second_ tag to be added is: `parking:left:markings=yes`. So the full tagging in that case would be:

```
parking:left=half_on_kerb
parking:left:markings=yes
parking:left:fee=no
```

For valid `parking:left=*` values, see https://wiki.openstreetmap.org/wiki/Street_parking#Parking_position
For valid `parking:left:markings=*` values, see https://wiki.openstreetmap.org/wiki/Street_parking#Marked_parking_spaces

**Comment by GITMichaelK** [comment]
Thank you @Famlam! If I remember correct, your example does not describe my problem. But actually I can't find a real one in detail. Unfortunately I flagged those in the OSMOSE-listing as false positive together with this post. May be, somebody can reset thiis? Otherwise time may solve it?
This [overpass-query](https://overpass-turbo.eu/s/1CRe) shows several nodes looking similar to my problem, if I remember correct.
If I could do anything too find it, please let me know.

**Comment by Famlam** [comment]
I went through the false positives of class 31624 (which gives the `markings is a value for key parking:[side]:reason / parking:[side]:restriction:reason`-warning) yesterday, didn't find any real false positive, and thus removed all of them. So it should re-appear within a day or so if the issue still exists.

There are no other false positives of a similar warning in Bamberg area (https://osmose.openstreetmap.fr/nl/issues/false-positive?item=3161&source=24808&limit=500). The only open issues related to `markings` are for way https://www.openstreetmap.org/way/1168448605 and https://www.openstreetmap.org/way/28294557 but those are valid warnings


Lets check again in two days.

**Comment by Famlam** [comment]
@GITMichaelK do you see this issue somewhere on the map? It should be visible now if it still existed

**Comment by Famlam** [comment]
I assume you didn't find any issues anymore? If you do, please reopen
