### ISSUE TITLE
geometry error for PL - osmosis_building_in_polygon

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#2058]
Reported from mail of @tkas 

for few days I got an error for analyser_osmosis_building_in_polygon for poland_lubelskie. Seems to have something in the data the library for parsing is not able to handle:

(current whole log on https://osm.fit.vutbr.cz/osmose/poland_lubelskie.log)

SELECT DISTINCT ON (poly_landuse.type_id)
  poly_landuse.type_id,
  buildings.id,
  -- Use the building location to point out the error, even though the landuse should be changed
  ST_AsText(way_locate(buildings.linestring)),
  buildings.tags->'building',
  poly_landuse.landuse
FROM
  buildings
  JOIN poly_landuse ON
    ST_Contains(poly_landuse.poly_proj, buildings.polygon_proj)
WHERE
  -- ignore e.g. small utility buildings that happen to be on the farmland or are fully surrounded by farmland
  buildings.area > 36 AND
  (NOT buildings.tags?'location' OR buildings.tags->'location' != 'underground')
ORDER BY
  poly_landuse.type_id
ESC[0m
2023-10-30 09:15:28   ESC[0;31merror: error on analyse osmosis_building_in_polygon...ESC[0m
2023-10-30 09:15:28     Traceback (most recent call last):
2023-10-30 09:15:28       File "/home/osmose/osmose-backend.git/./osmose_run.py", line 275, in execc
2023-10-30 09:15:28         analyser_obj.analyser()
2023-10-30 09:15:28       File "/home/osmose/osmose-backend.git/analysers/Analyser_Osmosis.py", line 290, in analyser
2023-10-30 09:15:28         self.analyser_osmosis_common()
2023-10-30 09:15:28       File "/home/osmose/osmose-backend.git/analysers/analyser_osmosis_building_in_polygon.py", line 102, in analyser_osmosis_common
2023-10-30 09:15:28         self.run(sql11, lambda res: {
2023-10-30 09:15:28       File "/home/osmose/osmose-backend.git/analysers/Analyser_Osmosis.py", line 583, in run
2023-10-30 09:15:28         self.run00(sql, callback_package)
2023-10-30 09:15:28       File "/home/osmose/osmose-backend.git/analysers/Analyser_Osmosis.py", line 535, in run00
2023-10-30 09:15:28         self.giscurs.execute(sql)
2023-10-30 09:15:28       File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 146, in execute
2023-10-30 09:15:28         return super().execute(query, vars)
2023-10-30 09:15:28                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-30 09:15:28     psycopg2.errors.InternalError_: GEOSContains: TopologyException: side location conflict at 603354.52571108926 5670280.9483742798. This can occur if the input geometry is invalid.
2023-10-30 09:15:28

I tried to cleanup data, cache etc. for this country part (for temporary error in data or data file itself), but does not helped.
Would you have any idea, where to look further?

**Comment by frodrigo** [comment]
The error com from this object https://www.openstreetmap.org/way/176646827

**Comment by Famlam** [comment]
Strange, as all tables are checked for validity of the geometry:
- [buildings](https://github.com/osm-fr/osmose-backend/blob/dev/analysers/Analyser_Osmosis.py#L230) & [ways](https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_osmosis_building_in_polygon.py#L40) via `is_polygon` ([which is false if no valid polygon can be constructed](https://github.com/osm-fr/osmose-backend/blob/dev/osmosis/ImportDatabase_Prepare.sql#L17))
- [multipolygons](https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_osmosis_building_in_polygon.py#L50) via its property `is_valid`

But probably because the object @frodrigo mentions (https://www.openstreetmap.org/way/176646827) crosses the outer of the farmland multipolygon (https://www.openstreetmap.org/way/289884082). So probably something is broken with is_valid of table multipolygons?

**Comment by frodrigo** [comment]
The two landuses are untouched for years.

As the issue may append really infrequently and as it works already for the whole world, I may suggest to just fix the data.

**Comment by Famlam** [comment]
I'm actually quite curious, is there a way to visualize the geometry constructed in multipolygon.poly? Somehow something valid was build from an invalid multipolygon.

**Comment by frodrigo** [comment]
Using psql on the db with redirected output to a file `\o` and use `St_AsGeoJSON` eg you can extract it. I am not used to this.

**Comment by tkas** [comment]
So do you want me to run some SQL or dig any more deeper? As the data seems not to be changed in months at least, it would be nice to know, why it started to show as error recently.

**Comment by Famlam** [comment]
@tkas I suspect the error is on Osmoses side. A couple days ago (Oct 14) https://github.com/osm-fr/osmose-backend/pull/2029 was deployed and that added multipolygon support to this analyser, and the data that causes this error involves a broken multipolygon.

I can also reproduce it on osm110.

**Comment by Famlam** [comment]
Surprisingly the geoJSON (which can be loaded in JOSM) obtained via the code below also shows an invalid polygon:
[geojson.zip](https://github.com/osm-fr/osmose-backend/files/13225271/geojson.zip)
```sql
SELECT
  --id,
  ST_AsGeoJSON(poly)
FROM
  multipolygons
WHERE
  is_valid AND
  ST_IsValid(poly) AND
  id = 11275234
``` 
so this may actually be a bug in ST_IsValid?

**Comment by tkas** [comment]
If it helps, I'm running:

root@osm:~# dpkg -l | grep postgresql-13
ii  postgresql-13                          13.12-1.pgdg120+1                       amd64        The World's Most Advanced Open Source Relational Database
ii  postgresql-13-postgis-2.5              2.5.5+dfsg-1.pgdg100+2                  amd64        Geographic objects support for PostgreSQL 13
ii  postgresql-13-postgis-2.5-scripts      2.5.5+dfsg-1.pgdg100+2                  all          Geographic objects support for PostgreSQL 13 -- SQL scripts

(devuan daedalus based on debian bookworm)

**Comment by Famlam** [comment]
Possibly, yes.
Surprisingly, `ST_IsValid(poly) = TRUE`, but `ST_IsValid(poly_proj) = FALSE`
Maybe we can just add this to the construction of table multipolygon: that both must be valid?

**Comment by frodrigo** [comment]
The configured geom is the right one https://maps.omniscale.com/en/openstreetmap/epsg-32634

Good point. Yes we can check for the projected geom.

I hope one day we will do all computation only in the projected geom.

**Comment by Famlam** [comment]
> Good point. Yes we can check for the projected geom.

Do you have a preference for:

```sql
SELECT
  *,
  ST_Transform(poly, {proj}) AS poly_proj,
  ST_IsValid(poly) AND ST_IsValid(ST_Transform(poly, {proj})) AS is_valid
FROM
  multi
```
or
```sql
SELECT
  *,
  ST_IsValid(poly) AND ST_IsValid(poly_proj) AS is_valid
FROM (
  SELECT
    *,
    ST_Transform(poly, {proj}) AS poly_proj
  FROM multi
) AS unusedvariable
```

Both get the same cost score from the sql planner*. The first one is shorter, the second one only calculates the `ST_Transform` once

*In a simplified test, where I replaced `multi` by `(SELECT id,tags,poly FROM multipolygons) AS x` to allow for quick testing. I have the impression the planner doesn't look at the `ST_*` functions?

**Comment by frodrigo** [comment]
The first one is better. Postgres use a cache on function call, so it really call `ST_Transform` only once.

**Comment by Famlam** [comment]
Made a very quick PR, haven't thoroughly tested it yet (as running the analysers without --skip-init is pretty slow)

**Comment by Famlam** [comment]
Seems ok with the new fix, no more errors in the log :)
