### ISSUE TITLE
STIF integration: Incorrect conversion of platforms to stop positions

### ISSUE THREAD

**Issue by Codain** [osm-fr/osmose-backend#207]
Use case: A bus platform (highway=bus_stop and public_transport=platform) has been tagged in Paris but with no ref:FR:STIF tag. For instance: http://www.openstreetmap.org/browse/node/260016832

Issue: Osmose proposes to make the integration with the STIF open data but by doing so always propose to replace public_transport=platform by public_transport=stop_position, which means it would no longer be a platform (where passengers wait) but a stop position (where the bus stops). For instance: http://osmose.openstreetmap.fr/fr/error/9237256331

Proposal: I deduce from this behaviour that the STIF database refers to stop positions and not platforms (correct?). If true, only nodes with (highway=bus_stop AND (public_transport=stop_position OR public_transport is not set)) shall be considered for association. If false, public_transport shall not be set/modified in the proposals.

**Comment by frodrigo** [comment]
We have disabled this analysis for buses beacause of inaccuracy.
But I see we forgot to remover the markers. The markers present on the map are from 2016 and never been updated since. We need to remove they.

@jocelynj please can you remove 8040/31 and 8041/33

**Comment by jocelynj** [comment]
I've just remove markers with item=8040+class=31 and item=8041+class=33.

**Comment by Codain** [comment]
Thank you, I suppose this solved the issue.
