### ISSUE TITLE
archaeological_site should be used in repacement of site_type

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osmose-backend#2082]
Hello,

osmose suggests for tumulus the tag 'site_type': 'tumulus'
Idem for menhir, dolmen and passage_grave

But the key https://wiki.openstreetmap.org/wiki/Key:site_type has been deprecated.

seems to concern items  #8010, 8011, 8012 and classes 10700,10701,10702,10703

see https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_poi_FR.py#L183

Thank you.

**Comment by Famlam** [comment]
Fixed (by frodrigo) :)
