### ISSUE TITLE
addr:place and street name

### ISSUE THREAD

**Issue by forstner-m** [osm-fr/osmose-backend#2085]
Hello,

I learnt from an OSM user that I am not allowed to name streets if I use the key "addr:place" for a building. But the street has a name because it is in a village and the houses around it also have the same address. However, this error is not displayed in OSMOSE. I am therefore unsure whether this rule even exists.
I realise that if I use the key "addr:street" for a building, the street in the vicinity must have a name.

Thank you!

Best regards,
Michael

**Comment by frodrigo** [comment]
Hello. I am not sure to understand what is you point with this issue. That a question ? do want something changed or added to Osmose ?

Note, Osmose dos not allows or not, it report possible issue, you can ignore it.

**Comment by forstner-m** [comment]
I do not want to create a new rule in OSMOSE. My question is whether there is a guideline in OSM that a street cannot have a name if the key "addr:place" is used on a building. Do you know this guideline? If this guideline exists, you can also create the rule in OSMOSE. Thanks...

**Comment by Famlam** [comment]
I suspect this is more a question for the OSM forums rather than the Osmose issue tracker? (In that case, giving an example there may be useful)

I'm not aware of any rules that forbid streets to have a name.

**Comment by forstner-m** [comment]
The naming of streets is supposedly not permitted here: https://www.openstreetmap.org/#map=18/48.66293/13.90919

But that should be okay: https://www.openstreetmap.org/#map=17/48.45577/13.95757

My opinion is that both methods are fine.

**Comment by Famlam** [comment]
In my personal opinion, the streets in Mayrhof should also have a name. How else would I know what the name of the streets in that mini-village are called? (Even if they have the same name as the village name, I wouldn't know that as the info is currently missing)

However, maybe this is a local Austrian custom, by the Austrian community? It definitely isn't something global

**Comment by Famlam** [comment]
If there are no street name signs or such, only city limit signs, then there's no indication that the streets have that same name, I think.
But as indicated I don't think this is a matter for Osmose (nor for my personal opinion; I'm looking at how I would tag it in NL), but something to sort out with the local community.
