### ISSUE TITLE
Lots of false positives in an area

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-backend#2087]
A couple weeks ago, lots of routing and structural errors started appearing in an area ([Unconnected highways](https://osmose.openstreetmap.fr/en/map/#zoom=10&lat=46.253&lon=-86.1779&item=1010%2C1040%2C1050%2C1060%2C1070%2C1080%2C1090%2C1100%2C1110%2C1120%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1260%2C1270%2C1280%2C1290%2C1300%2C1310%2C2xxx%2C3xxx%2C4xxx%2C5020%2C5040%2C5050%2C5060%2C5070%2C6xxx%2C7xxx%2C8xxx%2C9xxx&level=1&country=usa_michigan_upper_peninsula)) and ([open boundaries and rail crossings](https://osmose.openstreetmap.fr/en/map/#zoom=10&lat=46.3488&lon=-86.1102&item=1010%2C1040%2C1050%2C1080%2C1090%2C1100%2C1110%2C1120%2C1140%2C1150%2C1160%2C1180%2C1190%2C1210%2C1221%2C1230%2C1240%2C1250%2C1270%2C1280%2C1300%2C1310%2C2010%2C2020%2C2030%2C2040%2C2080%2C2090%2C2100%2C2110%2C2120%2C2130%2C2140%2C2150%2C2160%2C3xxx%2C4xxx%2C5020%2C5040%2C5050%2C5060%2C5070%2C6010%2C6020%2C6030%2C6040%2C7010%2C7011%2C7012%2C7020%2C7050%2C7051%2C7070%2C7080%2C7090%2C7100%2C7110%2C7120%2C7130%2C7150%2C7160%2C7170%2C7190%2C7220%2C7240%2C7250%2C9xxx&level=2&country=usa_michigan_upper_peninsula))

As far as I can tell, all of these are false positives, and i wanted to bring this up because it seems like a data issue on the backend.

**Comment by frodrigo** [comment]
As I can see the global number is issues is stable http://osmose.openstreetmap.fr/en/issues/graph.png?item=xxxx&country=usa_michigan_upper_peninsula (ignore the title of the graph)

> A couple weeks ago, lots of routing and structural errors started appearing in an area 

http://osmose.openstreetmap.fr/en/issues/graph.png?item=1210&country=usa_michigan_upper_peninsula

But something changed here.

It could be related to this
https://github.com/osm-fr/osmose-backend/commit/cefb7a9280f0496279fe5a7fe02eb90650bf68b4
https://github.com/osm-fr/osmose-backend/issues/1760

@jocelynj I think we fixed Osmose on this but not the PBF extract

**Comment by jocelynj** [comment]
I've regenerated all extracts of Michigan, and relaunched this job here: https://buildbot.osmose.openstreetmap.fr/#/builders/975/builds/338

Should we also do something else to not use the diff-mode on the backend side?

**Comment by frodrigo** [comment]
> I've regenerated all extracts of Michigan, and relaunched this job here: https://buildbot.osmose.openstreetmap.fr/#/builders/975/builds/338
> 
> Should we also do something else to not use the diff-mode on the backend side?

This analyser does not run in diff mode. So it is ok on that.

Nevertheless, the result are still the same.

@jocelynj We still have something wrong on the extract.
Here the .poly from download.fr

![image](https://github.com/osm-fr/osmose-backend/assets/1785486/837eba3d-0f63-4169-9749-cb2747957943)

While on Osmose we still have and other wrong configuration  :/
http://polygons.openstreetmap.fr/get_image.py?id=1582241,1582242,1801749,1801750,1898721,1907314,359765,582246,901500,901501&params=0

**Comment by jocelynj** [comment]
This time, it should be fine - I have updated the osmose-backend git clone on download.vm, updated the .poly file, and regenerated the extracts.

**Comment by frodrigo** [comment]
Markers and numbers look better now. Thank all.
