### ISSUE TITLE
Untagged area object for area:highway = steps area = yes

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#2103]
yes, this is not ideal tagging and area=yes is pointless there

no, it is not "Untagged area object"

```
Untagged area object
way 949544288[ josm](http://localhost:8111/load_object?objects=w949544288)[ iD](https://www.openstreetmap.org/edit?editor=id&way=949544288)[ edit](https://osmose.openstreetmap.fr/en/map/#)
area = yes
area:highway = steps
handrail = no
ramp = yes
ramp:stroller = yes
surface = paving_stones
```
```
source 	8420
item 	3200
class 	32002 
```

https://osmose.openstreetmap.fr/en/issue/f21d18e4-f17b-ac91-82ea-2935aa5dea6b

**Comment by frodrigo** [comment]
I suggest to just remove the `area=yes` on the OSM object.

**Comment by frodrigo** [comment]
Ok, I toke the fix from @Famlam

**Comment by matkoniecz** [comment]
> I suggest to just remove the area=yes on the OSM object.

I did this with other similar cases, but nevertheless this Osmose report was confusing/false positive.

Maybe it should be reported as low priority "unneded area=yes" error

**Comment by Famlam** [comment]
Most of these `unneeded area=yes`-warnings are already in JOSM. Might be good to add new ones there?

**Comment by Famlam** [comment]
I think this has been deployed
