### ISSUE TITLE
associatedStreet relation exit but error

### ISSUE THREAD

**Issue by lenny31** [osm-fr/osmose-backend#211]
addresses with the "associatedStreet" relation are in error "addr: housenumber or addr: addr: addr: addr: addr: addr: addr: addr: place or addr: hamlet must be in a associatedStreet relation"

les adresses avec la relation "associatedStreet" sortent en erreur "addr:housenumber or addr:housename without addr:street, addr:district, addr:quarter, addr:suburb, addr:place or addr:hamlet must be in a associatedStreet relation"

for example

http://www.openstreetmap.org/node/2036699018

> _" addr:housenumber or addr:housename without addr:street, addr:district, addr:quarter, addr:suburb, addr:place or addr:hamlet must be in a associatedStreet relation
node 2036699018 rawedit josm edit
addr:housenumber = 31
source = ToulouseMetropole
source:date = 2012/10/04
Signalé le : 2017-06-23"_

**Comment by frodrigo** [comment]
The issues is still here for you ?

**Comment by lenny31** [comment]
Correct, the issues are no longer there
En effet il n'y a plus de signalement
