### ISSUE TITLE
tram and service road can be reasonably mapped on one way

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#2117]
I am not very enthusiastic about mapping in https://www.openstreetmap.org/edit?editor=id&node=226839393#map=23/50.05661/19.94554 area but

```
Tag conflict
Conflict between tags: highway, railway
node 226839393[ josm](http://localhost:8111/load_object?objects=n226839393)[ iD](https://www.openstreetmap.org/edit?editor=id&node=226839393)[ edit](https://osmose.openstreetmap.fr/en/map/#)
crossing = uncontrolled
highway = crossing
railway = tram_crossing
```

is not valid warning, as they both can be on the same point when footway crosses both tram and busway

**Comment by Famlam** [comment]
Here's the location: https://www.openstreetmap.org/node/226839393
There's 1313 cases of this worldwide

**Comment by Famlam** [comment]
I think this has been deployed
