### ISSUE TITLE
Wrong tag "cycling infrastructure" for missing "maxspeed = 5" 

### ISSUE THREAD

**Issue by Langlaeufer** [osm-fr/osmose-backend#2119]
Since 1.1.24 following issues are listed within tags tags=bicycle,cycleway

E.g..
> Fahrradinfrastruktur fehlt
> Erkannt bei 2022-06-08

> maxspeed = 5
> source = Mapillary Traffic Signs
> survey:date = 2022-06-08

> Problem gemeldet am: 2024-01-01

maxspeed=5 is not a bicycle infrastructure issue.
please remove the bicycle or cycleway tag.

**Comment by frodrigo** [comment]
Do you have a link ? I am not sure to understand what do you mean.

**Comment by Langlaeufer** [comment]
https://osmose.openstreetmap.fr/de/issue/b34ac17c-8992-0073-bdad-0a536aab7c83

**Comment by frodrigo** [comment]
It is now fixed. It was a side effect of an other bug.
