### ISSUE TITLE
To allow addr:neighbourhood as assignment additional to addr:street ... modifications in Venice

### ISSUE THREAD

**Issue by lenny31** [osm-fr/osmose-backend#212]
In Venice the housenumber are in neighborhood :
http://www.openstreetmap.org/node/2486203200
​https://en.wikipedia.org/wiki/House_numbering : 
> " In Venice, Italy, houses are numbered within districts known as sestieri, resulting in just six series for the entire city. Similarly, small villages in Italy may also occasionally use a single progressive series for all house numbers.[12] In Genoa and in Florence houses are marked with black (sometimes also blue in Florence) numbers while businesses are usually (but not always) given red numbers, resulting in two distinct series for every street. The street numbers of businesses are denoted in writing (e.g. documents, online directories, etc.) by the addition of the letter "r" (e.g. "Via dei Servi 21r")."

​https://www.wikidata.org/wiki/Q1067867#sitelinks-wikipedia

sory for my bad english, in French 
Bonjour
Osmose signale des avertissements, pour les adresses sans nom de rue , alors qu'à Venise, c'est un cas particulier, les n° sont numérotés par quartiers (sestieri) et non par rue ; il me semble donc que addr:neighborhood ne devrait pas être considéré comme une erreur
J'ai ajouté les liens vers wikipedia et wikidata
cordialement
Leni

**Comment by frodrigo** [comment]
Wating for update:
http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=45.439836&lon=12.331737&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=xxxx&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
I made a typo in the tag. Need to wait again.

**Comment by frodrigo** [comment]
Done
