### ISSUE TITLE
False warnings for waterways that end at waterway=fish_pass

### ISSUE THREAD

**Issue by AurimasF** [osm-fr/osmose-backend#2124]
Item 1220, class 2-3.
Example issue: https://osmose.openstreetmap.fr/en/issue/a06cd9b1-4a94-83a2-8489-f6de078a502b

Waterways that are connected to waterway=fish_pass get flagged as "Unconnected stream/river or wrong way flow" when they shouldn't.

Similar situation to #2086.

**Comment by Famlam** [comment]
I'm not so sure whether the waterway=river should be directed to the fish pass. The wiki suggests to connect it to the water area instead.

**Comment by AurimasF** [comment]
If I disconnect waterway=fish_pass from the waterway=river, then JOSM validator complains with "Way end node near other highway".

**Comment by Famlam** [comment]
Ok, I see... I don't know... It seems strange to me to say that a river changes into a fish pass, that's like a motorway ending in a serviceway to become a motorway again. I'd than rather think that the little pieces between the actual fish pass and the "through" river ways should also be fish pass, as that's the purpose of that way (and does match the wiki)
E.g. like https://www.openstreetmap.org/way/370205188

**Comment by AurimasF** [comment]
> I'd than rather think that the little pieces between the actual fish pass and the "through" river ways should also be fish pass, as that's the purpose of that way (and does match the wiki) E.g. like https://www.openstreetmap.org/way/370205188
Yes, it sounds reasonable.
Fixed the issue by changing parts of the river.
