### ISSUE TITLE
Osmosis_Highway_Floating_Islands fails on pakistan

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2125]
I was trying to reproduce the error of `Osmosis_Highway_Floating_Islands` on `pakistan` (which failed for the past 36 days), but:
1. I can't see any builds in buildbot, so not sure where to find the server log showing the error
2. I don't get any error on backend when running on osm110
3. I don't see any duplicate error in the results (which, if it were present, would cause an error the frontend)
4. This analyzer doesn't have diff mode, so it can't be diff related

So I'm not sure what the error can be?

**Comment by frodrigo** [comment]
Here you can see Pakistan is running on the `is-svavar.k` backend.
http://osmose.openstreetmap.fr/fr/control/update_summary

The backend is up to date.

I think we does not have access to the logs of this backend.

**Comment by Famlam** [comment]
That makes debugging a bit more difficult... 

Possibly there's another error on frontend (I never built frontend myself, I only checked for duplicate results). Can you possibly see if something bad happens if you feed the results of pakistan/Osmosis_Highway_Floating_Islands into frontend locally?

The results of yesterday are in `/data/work/famlam/results/Analyser_Osmosis_Highway_Floating_Islands-pakistan.xml.bz2` if you want to avoid running the backend part ;)

**Comment by Famlam** [comment]
Seems fixed, I don't see a lag anymore in the update summary
