### ISSUE TITLE
Does the "france" analyser looks at France d'outre-mer ?

### ISSUE THREAD

**Issue by NicolasPyIGN** [osm-fr/osmose-backend#2131]
I'm now interested at looking at Osmose's issues in the France d'outre-mer (https://fr.wikipedia.org/wiki/France_d%27outre-mer), including Collectivité d'outre-mer (https://fr.wikipedia.org/wiki/Collectivit%C3%A9_d%27outre-mer) ; for the issues created after looking at IGNF's data (https://fr.wikipedia.org/wiki/BD_TOPO).

Following #2045 and https://forum.openstreetmap.fr/t/osmose-analyses-avec-bd-topo-sur-les-troncons-de-voies-ameliorations-proposees/19886 I undertsood that the main analyser to use for my task is "france" with the source 14708

I didn't succeed in finding the area/perimeter/bbox used by that analyser, and, following, if the France d'outre-mer is included.

Looking at the map https://osmose.openstreetmap.fr/en/map/#item=7170&class=1&country=france&zoom=15&lat=18.07238&lon=-63.07522&level=1%2C2%2C3 neither helped me.

Do you have some answer ?
Sincerely,

**Comment by frodrigo** [comment]
Now also in territories
https://osmose.openstreetmap.fr/fr/map/#zoom=11&lat=18.0087&lon=-62.9644&item=7170&level=1%2C2%2C3&tags=&fixable=&class=13

**Comment by NicolasPyIGN** [comment]
Thanks for that action !
