### ISSUE TITLE
Update kOpeningHours when released, remove workaround

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2136]
Now that [this PR at kOpeningHours](https://invent.kde.org/libraries/kopeninghours/-/merge_requests/103) was merged, we can remove the [workaround](https://github.com/osm-fr/osmose-backend/blob/dev/plugins/ConditionalRestrictions.py#L42) as soon as a new kOpeningHours release has been made.
Filing for future reference :)

Edit: not included yet in [v24.02.1](https://invent.kde.org/libraries/kopeninghours/-/commits/v24.02.1)

**Comment by Famlam** [comment]
Reopening as it seems something went wrong with the deploy, see:
https://github.com/osm-fr/osmose-backend/pull/2208#issuecomment-2103227786
There's lots of false positives

**Comment by frodrigo** [comment]
https://invent.kde.org/libraries/kopeninghours/-/merge_requests/109

**Comment by frodrigo** [comment]
> Reopening as it seems something went wrong with the deploy, see:
https://github.com/osm-fr/osmose-backend/pull/2208#issuecomment-2103227786
There's lots of false positives that shouldn't exist. Per the discussion, it might require kOpeningHours to be reinstalled

What do you thing about the status now (and the graph) ?

**Comment by Famlam** [comment]
I was expecting a straight line, but perhaps the increase corresponds to the amount of badly formatted conditionals that are now detected while they were not in the previous version. Let's close it for now. The issues that I referred to that were clear false positives are gone now
