### ISSUE TITLE
Update validation rule adress josm mapcss

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#2144]
France spécific rules in mapcss had been update 
to fix false positive issues for fantoir code.
https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules

Can you please upate osmose
https://github.com/osm-fr/osmose-backend/blob/dev/plugins/Josm_FranceSpecificRules.py
 
Thanks

**Comment by Famlam** [comment]
Merged, but not yet deployed

**Comment by didier2020** [comment]
hello, there is something wrong with mapcss/osmose ?

OK : https://regex101.com/r/z7tbjX/3
NOK : http://osmose.openstreetmap.fr/fr/issue/8a6050f8-f9c4-b827-3ecd-53102a4e513b

**Comment by frodrigo** [comment]
There is clearly an issue. To be checked if it do the same into JOSM. Not sure to be able to check it myself today.

**Comment by didier2020** [comment]
I don't know why, issue is about order in regex.

I've update josm rules. 
(J'aurais du être plus vigilant, désolé)

**Comment by frodrigo** [comment]
> I don't know why, issue is about order in regex.
> 
> I've update josm rules. (J'aurais du être plus vigilant, désolé)

Deployed

**Comment by Famlam** [comment]
I didn't debug it very much, but this seems implicit to Python:

**Comment by didier2020** [comment]
it now ok for me
