### ISSUE TITLE
Leisure=track with highway=footway seems legit

### ISSUE THREAD

**Issue by kaligrafy** [osm-fr/osmose-backend#2152]
item | 4030
class | 900

I think we should accept highway=footway and leisure=track on the same way. It happens a lot in parks where there is a foot path that is also used as an official running track.

How would you tag these otherwise if you want to allow normal pedestrian routing on the track?

**Comment by frodrigo** [comment]
No sure about that. Better to map the track with route=running , doesn't ?

**Comment by kaligrafy** [comment]
Seems right, as leisure=track is specified on the wiki as "typically not a part of the normal network of ways and paths". Never seen route=running used in my local area, so I learned something today!
