### ISSUE TITLE
Building:part and sport

### ISSUE THREAD

**Issue by Mahabarata** [osm-fr/osmose-backend#2157]
https://www.openstreetmap.org/way/1247676053

A hall_center has 2 building parts, one with specific sports and the other wih another sport.

Currently osmose indicates an issue in osm data on the 2 ways, it looks like building:part is not seen as a physical feature

**Comment by Famlam** [comment]
Solved on Josm's side, but not synchronized yet. We'll do that soon

**Comment by Famlam** [comment]
Fix deployed
