### ISSUE TITLE
Suggestion: add highway tags to subtitle to allow sorting.

### ISSUE THREAD

**Issue by ComradeRamen** [osm-fr/osmose-backend#2174]
Item:1210
I've been sorting issues locally after downloading them from the site but would be nice if highway tags were in the subtitle so I can sort on the website. 

I've been trying to add the "text" field myself but I haven't figured out how to test functionality properly yet. Idk if docker instructions could be updated or I'm just dense.

**Comment by frodrigo** [comment]
As it is a small change, you make the PR anyway.

If you have question on docker, you can ask.

**Comment by ComradeRamen** [comment]
https://github.com/osm-fr/osmose-backend/pull/2176
