### ISSUE TITLE
public_transport:version=1 routes don't appear in route_master relation.

### ISSUE THREAD

**Issue by FrakGart** [osm-fr/osmose-backend#218]
The route_master relation is part of the new public transport schema so old schema routes shouldn't be checked eg:

http://osmose.openstreetmap.fr/en/error/12920346910

In fact probably should check to make sure that the routes in a route_master are tagged public_transport:version=2 and flag an error if they aren't.

**Comment by frodrigo** [comment]
cc @nlehuby

**Comment by nlehuby** [comment]
We already have a test about the `public_transport:version` tag on public_transport route relations.

I think we were already adding route relations to route_master relations before the approval of the v2 of the public transport schema (with `backward` and `forward` roles, that have been removed by the schema).
Do you have knowledge about any route relation that we should NOT add to a route_master relation ? I can't think of any cases ...

**Comment by osmtools** [comment]
@nlehuby hmm, the german wiki page about [Public Transport](http://wiki.openstreetmap.org/wiki/DE:Public_transport#Master-Route) says:

> Master-Routen gibt es nicht im "alten" Public-Transport-Schema und im Oxomoa-Schema. (There aren't any master-routes in the "old" public transport schema or oxomoa-schema)

This hint isn't present in the english version?!

> Routen nach dem ersten Public-Transport-Schema enthalten, anders als Oxomoa- und PTv2-Routenrelationen alle Fahrtvarianten und -richtungen in einer Relation, die durch Rollen wie alternate, forward, backward usw. unterschieden wurden. (routes of the first public transport schema contains (different to oxomoa and PTv2) all route relations for all directions in only one relation with roles alternate, forward and backward)

So a few years ago i created such PTv1 route relations without creating such master-route-relations.
