### ISSUE TITLE
'Multiple tags' suggests toll instead of fee for trailhead

### ISSUE THREAD

**Issue by danieldegroot2** [osm-fr/osmose-backend#2180]
https://osmose.openstreetmap.fr/nl/map/#zoom=17&lat=52.652731&lon=-7.250956&item=3032%2C9xxx&level=1&tags=&useDevItem=

**Observed**
Suggests toll instead of fee for `highway=trailhead`; in this case tagged on museum building (this is POI/building, not road).

**Expected**
Trailhead (and maybe other tags) are excluded and/or road is restricted to certain valid types
(Minor issue, anyways)

OSM https://www.openstreetmap.org/way/1023719146

**Comment by Famlam** [comment]
Although I have mixed feelings about the combination with building=* (is the entire building, on all sides, marked with "here begins the tour", or is there just a sign somewhere at one point) I agree that trailhead can be a standalone area, and this should be exempted regardless.

**Comment by Famlam** [comment]
Fix deployed
