### ISSUE TITLE
POI nodes with area tags

### ISSUE THREAD

**Issue by danieldegroot2** [osm-fr/osmose-backend#2181]
POI `place` _nodes_ with other (_area_) tags like `landuse`, `tourism` can sometimes be problematic/redundant ('tag conflict').

It is case-specific. In some cases it is better to keep them apart, to avoid mistagging (and [tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer)) or duplicating objects ([One feature, one OSM element](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element)).

I have come across such tags being added to place nodes by accident

I don't have any specific suggestions for improvements. Maybe MapRoulette is better for such checks for now.

Related #2044, #1261

**Comment by Famlam** [comment]
Do you have a specific example other than the linked issues? If a case is very clear, we can of course whitelist it

**Comment by danieldegroot2** [comment]
This happened to `place` + `tourism=visitor_centre` for at least https://www.openstreetmap.org/node/29670269/history

**Comment by danieldegroot2** [comment]
`place` + `information` should already be [covered](https://github.com/osm-fr/osmose-backend/blob/01168324947c27ab6a8f0ad4c334dc58414bde95/plugins/TagRemove_Incompatibles.py#L42) (I will assume it works properly).
things like `place`/`building`/`industrial` + `landuse` and `building` + `industrial` conflict seems not covered.

**Comment by Famlam** [comment]
Ah, I thought you wanted to whitelist a combination, but instead you want to add new warnings.

So if I understand correctly, you propose to add checks for

1. ~`place + landuse`~
2. `building + landuse`
3. ~`industrial + landuse`~
4. ~`building + industrial`~

The 1st, 3th and 4th are very unlikely to be added as they're valid per the wiki ([1](https://wiki.openstreetmap.org/wiki/Tag:place=city%20block), [3](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dindustrial), [4](https://wiki.openstreetmap.org/wiki/Tag:building%3Dindustrial))

The 2nd will probably trigger similar debates as in #2044. Personally I'd have no objections against it though...

**Comment by danieldegroot2** [comment]
Understandable.

building == landuse may be where landuse tag may or may not be redundant
(note, there is also tagging scheme with `building:use` in use.)
`building=industrial` + `landuse=industrial` may need discussion with industrial mappers.

Few other examples from (island of) Ireland.
`building=*` + `landuse=construction` / `construction` (usually building is finished but construction tag not removed)
`building = *` + `landuse = military` + `military = *` (likely operator or function is military, or object has some legal designation, i.e. office or standalone bunker is perhaps not landuse)
`building` + `landuse=recreation_ground` / `leisure=park` / ... (likely operator or location is a park or similar, or it is fantasy/gaming vandalism.)
`building=*` + `landuse=religious` (would use for its plot of land eventhough there may be no other part used for religious purpose)
~~`building=no` + `landuse=*`~~ (ok, i.e. open-air church)
~~`building = *` + `landuse = greenhouse_horticulture`~~ (may be ok, at least on mixed use farmyard)

Anyhow, needs further research/discussion before implementing.
