### ISSUE TITLE
Pins to "Missing outer role for multipolygon" not jumping to location in JOSM or ID

### ISSUE THREAD

**Issue by sekerob** [osm-fr/osmose-backend#2195]
[Sample of subject](https://osmose.openstreetmap.fr/en/map/#zoom=7&lat=43.925&lon=13.623&item=xxxx&level=1&tags=multipolygon&fixable=&username=&issue_uuid=d130177d-4c53-06ec-a35a-be0264a5ecd1)  does not jump to JOSM thru the remote control function. For ID it just shows the world image, which makes it really hard to home in on what item needs a role assigned. The [relation link](https://www.openstreetmap.org/relation/17083857) itself also goes nowhere. Too hard to resolve, being level 1 / high priority issue would like to.

![image](https://github.com/osm-fr/osmose-frontend/assets/23308504/d361bf26-229e-4978-9ea9-f59c78215efb)

**Comment by Famlam** [comment]
I think this is such a special case. It's a multipolygon that as the only member has another multipolygon as outer. 

Also downloading it via JOSM directly (ctrl-shift-O -> r17083857 -> enable all 'download member *' options) won't give you any location, for instance.

We should however perhaps make the error more clear that it's an invalid outer in this case.

**Comment by sekerob** [comment]
Ctrl+Shift+O gets intercepted by my GPU app... /o\

![image](https://github.com/osm-fr/osmose-backend/assets/23308504/9ebf420c-81b5-4ca7-9e90-8eeb225c6cd0),

rummaging around on the W3, found File > download object, choose type, enter relation number

![image](https://github.com/osm-fr/osmose-backend/assets/23308504/c6f6eea6-095b-47d7-84a9-007e53d47f5a)

I true issue, with Streetside it shows all the pics as a junction but still not going where the issue is. But when using the relation toolbox and trying a reconstruct on this one member, it says

![image](https://github.com/osm-fr/osmose-backend/assets/23308504/fcd6b21b-525f-427f-8dd7-29b4ac7480f7)

Eventually, got that 2 member MP which for unknown reason was a cut up ring, merged, reconstructed, mapped the inner bare rock zone, made it a new relation and sent it up. We'll see tomorrow what gives.

**Comment by sekerob** [comment]
Thanks for that and as to disable, please don't.  Got now a working procedure the get to the outer MP by drilling thru in the relation toolbox which shows no elements were downloaded but with 'incomplete'. When then pulling down those elements it can be fixed rather swiftly. Not more than a dozen in Italy. Empty MPs should go. There's a fair collection in Paesi Bassi... something for Casper to put his teeth in :-)))

**Comment by Famlam** [comment]
Ok, then I won't disable it :)
