### ISSUE TITLE
Treat public transport platforms as valid footways

### ISSUE THREAD

**Issue by bxl-forever** [osm-fr/osmose-backend#220]
I am puzzled about the following situation reported by Osmose.
The situation is as such: there is a subway platform and a footway connects it towards an upwards escalator.  The footway has oneway=yes because it can only be used to leave the station—there are turnstiles.
http://osmose.openstreetmap.fr/en/error/12940600382

Osmose complains that this footway is inaccessible.  Indeed, there is no other highway=* way towards its starting point, but an area with public_transport=platform.

I suggest that we should treat a way tagged with public_transport=platform as something "walkable", and therefore that the checker would accept it.

Thanks.

**Comment by frodrigo** [comment]
@nlehuby What do you think of this ?

**Comment by nlehuby** [comment]
The wiki suggests to add `highway=footway` to the platform if it is connected to other ways : https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform

**Comment by bxl-forever** [comment]
OK, we’ll do that.  Thanks.
