### ISSUE TITLE
Check for trees that are too big

### ISSUE THREAD

**Issue by ivanbranco** [osm-fr/osmose-backend#2200]
According to the [Guinness World Records](https://www.guinnessworldrecords.com/world-records/living-tree-with-greatest-girth#:~:text=Generally%20speaking%2C%20however%2C%20the%20largest,m%20(141%20ft)%20recorded), the greatest circumference for a tree is 43m. I suggest implementing a check for trees with circumferences exceeding this value, as they are likely to be errors.

For instance, we currently have 2001 nodes in the database with a circumference of 45: https://overpass-turbo.eu/s/1JUU. Osmose could suggest to check them and 
1. delete the value if plainly wrong or
2. fix 'circumference=45' to 'circumference=0.45' or 'circumference=45 cm'

Another check could be on height. Trees taller than [Hyperion](https://en.wikipedia.org/wiki/Hyperion_(tree)) (tallest tree in the world with 116m) are likely to be errors.

**Comment by Famlam** [comment]
https://overpass-turbo.eu/s/1JWd
62638 trees worldwide affected by the circumference limit of 43m.

I suspect this might be interesting for JOSM, for their numerical validation rules (which we synchronize with Osmose). That way it benefits more people ànd people who add those trees get a warning prior to uploading it in the first place.

Could you report it to them please?
If they decline, we can still add it to Osmose directly :)

**Comment by sekerob** [comment]
Clicked on one where curiously the crown was given a lower value of 35 v 45. The JOSM tool with the measured values plugin gives good indication of crown size, seen many exceeding 150-200 m2. Maybe add a crown/trunk ratio test to home in further, venture to think if a mapper goes into mapping these, both will be tagged.

![image](https://github.com/osm-fr/osmose-backend/assets/23308504/f6daa488-c5fb-4f17-b99b-9fb48b9116b8)

**Comment by Famlam** [comment]
I'm not a biologist, so I'm not sure if there's trees where it could be true (a cactus perhaps?). I played around a bit to get some stats though:

This mapcss rule that compares `circumference` with `diameter_crown` and warns if the latter is smaller than the former gives 62489 results, of which 17620 with a circumference <= 43m:
```css
node[circumference][diameter_crown][to_float(tag("circumference")) > to_float(tag("diameter_crown"))] {
  throwWarning: tr("circumference larger than diameter_crown");
}
```

This mapcss rule finds (I think) all 73369 trees with a circumference > 43 m. Still excluding trees measured in feets, inches & other uncommon units of course.
```css
node[circumference=~/^([1-9][0-9]{2,}|[4-9][0-9])(\.[0-9]+)?( ?m)?$/][circumference!~/^4[0-3]/] {
  throwError: tr("TEST: circumference of new world record");
}
```

**Comment by ivanbranco** [comment]
Another idea I had (I implemented it in a MaprouletteChallenge here: https://maproulette.org/browse/challenges/44817) is to check for invalid species. Looking for species without a space " " would be enough, this would flag:

**Comment by frodrigo** [comment]
> Another idea I had (I created a MaprouletteChallenge here: https://maproulette.org/browse/challenges/44817) is to check for invalid species. Looking for species without a space " " would be enough (tree species are formed by two words), this would flag elements such as:

Note, there is already one, but limited to french. https://github.com/osm-fr/osmose-backend/blob/dev/plugins/TagFix_Tree_Lang_fr.py

**Comment by ivanbranco** [comment]
> > Another idea I had (I created a MaprouletteChallenge here: https://maproulette.org/browse/challenges/44817) is to check for invalid species. Looking for species without a space " " would be enough (tree species are formed by two words), this would flag elements such as:
> 
> Note, there is already one, but limited to french. https://github.com/osm-fr/osmose-backend/blob/dev/plugins/TagFix_Tree_Lang_fr.py

Cool!

Species could be used to suggest leaf_type and leaf_cycle. I created a list with the most popular (in OSM database) trees here: https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree/List_of_Species
My hope is that someday one QA tool would, for example, flag a species=Acer pseudoplatanus with "leaf_type=broadleaved and leaf_cycle=deciduous are missing, consider adding them" or "This tree is tagged as "Acer pseudoplatanus", but the current leaf_type is needleleaved. Species or leaf_type are wrong, check and fix it". But maybe I'm going to far :p

**Comment by Famlam** [comment]
> But maybe I'm going to far :p

It sounds like an interesting thing to implement!
I would however recommend filing this as a separate issue as this single issue is already about 3 different feature requests (big circumferences, circumference vs diameter_crown, and now this one) ;)

**Comment by Famlam** [comment]
@ivanbranco the results of the check of `species` vs. `leaf_*`, based on the documented values for species on the wiki page, can be found here: https://osmose.openstreetmap.fr/nl/issues/open?item=3120&class=31201 (results are still updating)

**Comment by Famlam** [comment]
And also the second part is live:
https://osmose.openstreetmap.fr/nl/map/#item=9006&class=9006033&loc=7/50.695/8.863&level=1%2C2%2C3
