### ISSUE TITLE
Filter expired postal codes in a safer way

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2203]
See https://github.com/osm-fr/osmose-backend/pull/2202#issuecomment-2055971398
After that issue is solved, we should filter expired postal codes, rather than hoping that older postal codes will always be on top of newer in the table. Probably by filtering on dates with the longer minus sign used for date ranges in that table

**Comment by Famlam** [comment]
Nevermind, for Canada it for instance lists `1971–1975` to reflect the starting date range...
In that case I don't really see a generic way to filter...

The alternative "safe way" would be to collect all old and new codes (meaning for Germany permitting NN, NNNN and NNNNN) but then we'd lose a lot of the detection power of the analyser.

**Comment by frodrigo** [comment]
At some point I improved the Wikipedia table myself to be usable by Osmose, and I also split the zone and the street level format. I think we can change the table to make it better if required on the date column.
