### ISSUE TITLE
Analyser_Merge stopped working - Empty bbox, abort

### ISSUE THREAD

**Issue by XioNoX** [osm-fr/osmose-backend#2204]
Forking the comment from https://github.com/osm-fr/osmose-backend/pull/2143#issuecomment-1982672075 for better visibility.

On March 7th, the results of `analyser_merge_bicycle_parking_FR_brest.py` went straight to 0. See for example in https://osmose.openstreetmap.fr/en/issues/graph.png?source=448196&item=815x

The [source data](https://www.data.gouv.fr/fr/datasets/r/16da3c74-e885-4563-94ef-a9b59d600d8e) seems to still be correct (loading it with other tools show the data as expected).
I was able to find an [older version (from Feb.)](https://github.com/osm-fr/osmose-backend/files/14984841/DEP_ACT_StationnementVelo-old.zip) of the same data on my computer but can't find any differences.

When running the script locally, it does show the error `Empty bbox, abort` in the logs. From: https://github.com/osm-fr/osmose-backend/blob/8872fefff150599b7dfa4171ed6488250158f05f/analysers/Analyser_Merge.py#L1282 )

As additional data point, I also wrote a very similar Analyser in https://github.com/osm-fr/osmose-backend/pull/2145 which is still working fine.

Any idea on what's going on and how to solve it ? Happy to help anyway I can.

Thanks

**Comment by frodrigo** [comment]
https://buildbot.osmose.openstreetmap.fr/#/builders/692/builds/1331/steps/3/logs/stdio

```
ogr2ogr -f PostgreSQL 'PG:dbname=osmose user=osmose password=-osmose- options=--search_path=france_bretagne_finistere,public ' -lco SCHEMA=osmose -nln 'bicycle_parking_fr_brest' -clipsrc 'POLYGON ((-4.151539862059942 47.76053131530047, -4.415959749286308 47.76015958051296, -4.530363610371559 47.95896362821816, -5.046547770842181 48.019179412093386, -5.019975331656217 48.0926160904607, -4.583494218990213 48.127325211311025, -4.7098428193789905 48.284398358730925, -4.913730308427237 48.26390696967531, -5.211314433838145 48.459100989577856, -5.066888847214807 48.529468449135784, -4.866304455704818 48.435702141382784, -4.832425220683625 48.55632105380964, -4.582735832892576 48.69387148694913, -4.033107956315517 48.80195085405825, -3.583587844881507 48.71767226680186, -3.4524102651694206 48.18878646473874, -3.634646089871678 48.11298176984943, -3.320201887544026 47.92075765279919, -3.517300743861276 47.72014117190676, -3.8174616523447646 47.72757514970712, -3.9810550631359227 47.80820079548827, -3.8842541241400004 47.71783389996919, -4.004557730859692 47.65647096396355, -4.078552252625548 47.807281028066235, -4.151539862059942 47.76053131530047), (-4.455808366708948 48.14392419512635, -4.423983300420286 48.15200442444278, -4.36376296767472 48.154858766707356, -4.45276661171805 48.17768591433142, -4.455808366708948 48.14392419512635))' -nlt PROMOTE_TO_MULTI -lco OVERWRITE=yes -lco GEOMETRY_NAME=geom -lco OVERWRITE=YES -lco LAUNDER=NO -skipfailures  -s_srs EPSG:4326 -t_srs EPSG:2154 '/vsizip//tmp/tmp_e7mg3b5.zip/DEP_ACT_StationnementVelo.shp' 
```

It uses `-s_srs EPSG:4326 -t_srs EPSG:2154`, but the source is in 2154 (an also the target).

It looks like wrong detection of the shp projection.
https://github.com/osm-fr/osmose-backend/blob/dev/analysers/Analyser_Merge.py#L791-L803

https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_merge_bicycle_parking_FR_brest.py

**Comment by XioNoX** [comment]
Thanks ! Indeed, the old file returns `EPSG:2154`, while the new one returns `IGNF:LAMB93` while using `gdalsrsinfo -e -o epsg DEP_ACT_StationnementVelo.shp`. For what I understand they're the same thing ?
Note that this is using  Ubuntu's `GDAL 3.7.1, released 2023/07/06`  but the docker image returns`EPSG:0` (more recent gdal version).

As a test I changed the following, it's brittle and only tested on that usecase, but it does work. Putting it here in case it can help.

```diff
diff --git analysers/Analyser_Merge.py analysers/Analyser_Merge.py
index 60f89297..3760ab7e 100644
--- analysers/Analyser_Merge.py
+++ analysers/Analyser_Merge.py
@@ -789,11 +789,13 @@ class GDAL(Parser):
                 self.source_layer.append(f"'{self.layer}'")
 
             if not self._srid:
-                match = re.search('EPSG:([0-9]+)', subprocess.run(["gdalsrsinfo", "-e", self.source_layer[0]], stdout=subprocess.PIPE).st>
-                if not match and len(self.source_layer) >= 2:
-                    match = re.search('EPSG:([0-9]+)', subprocess.run(["gdalsrsinfo", "-e", *self.source_layer], stdout=subprocess.PIPE).>
-                if match:
-                    self._srid = int(match.group(1))
+                projjson = json.loads(subprocess.run(["gdalsrsinfo", "-e", "-o", "PROJJSON", self.source_layer[0]], stdout=subprocess.PIP>
+                if not projjson and len(self.source_layer) >= 2:
+                    projjson = json.loads(subprocess.run(["gdalsrsinfo", "-e", "-o", "PROJJSON", *self.source_layer], stdout=subprocess.P>
+                if projjson['id']['authority'] == 'EPSG':
+                    self._srid = int(projjson['id']['code'])
+                if projjson['id']['code'] == 'LAMB93':
+                    self._srid = 2154
         except Exception as e:
             os.remove(self.tmp_file.name)
             raise e
```

**Comment by frodrigo** [comment]
I take you diff. I do not found better way to implement it.
