### ISSUE TITLE
This indoor room should have a door - false positive?

### ISSUE THREAD

**Issue by aixbrick** [osm-fr/osmose-backend#2210]
Hello,

Osmose reports about a missing door to that indoor room:

https://osmose.openstreetmap.fr/de/map/#loc=18/50.768207/6.091287&item=xxxx&level=1%2C2%2C3&issue_uuid=b3fa3786-28cb-7217-28a7-63a385d127ba
Item: 1300
Class: 53
https://osmose.openstreetmap.fr/de/issue/b3fa3786-28cb-7217-28a7-63a385d127ba

But there are already two doors: https://www.openstreetmap.org/node/6242200167 and https://www.openstreetmap.org/node/10963277554

The same issue is reported for other rooms in that building. Maybe false positives?

Regards

**Comment by Famlam** [comment]
Interesting, I'm wondering how this (for ways and relations) can ever evaluate the `if` as a non-False value. Is the latest version live on the server?

https://github.com/osm-fr/osmose-backend/blob/3e2183dfee8a1476081bac1fef0444d4288a35d2/plugins/indoor.py#L195-L200

**Comment by frodrigo** [comment]
Yes, curious.

All backends are up to date https://osmose.openstreetmap.fr/fr/control/update_summary

I look at the code history and never was active.

**Comment by frodrigo** [comment]
No country have reported issues about this, all at 0. But sample list is not empty !

https://osmose.openstreetmap.fr/de/issues/open?item=1300&class=53

There is pins in Germany and Switzerland.

https://osmose.openstreetmap.fr/de/map/#item=1300&class=53&loc=7/47.201/8.348&level=1%2C2%2C3

**Comment by Famlam** [comment]
Also no results if ran on osm110. Maybe try to clear the results server side anyway? See if they re-appear in a few days?

**Comment by frodrigo** [comment]
I clear this data front the frontend.
Let's wait to see if something come back.

**Comment by Famlam** [comment]
Nothing seems to have reappeared after clearing 2 weeks ago, so I guess we can consider this issue solved?
(Although it's still a mystery why they appeared in the first place)
