### ISSUE TITLE
Minor clarification for `missing oneway`

### ISSUE THREAD

**Issue by opk12** [osm-fr/osmose-backend#2213]
[This example](https://osmose.openstreetmap.fr/en/issue/e9e0aaaa-cf24-029f-2aff-a605b863c71e) of item 2030's entry `2. Missing oneway` is probably a false positive, from a quick look at the aerial imagery. What about mentioning `oneway=no` in the warning? The wiki [allows](https://wiki.openstreetmap.org/wiki/Key:oneway#oneway_=_no) the value `no` explicitly.

In particular, the warning says `After verifying that it is an access road to the roundabout and they
were well oriented, set the tag oneway=yes on the two segments.` ([source code](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_roundabout_level.py#L278)). It could say something like `If the road is two-way, set oneway=no or mark as a false positive`.

**Comment by Famlam** [comment]
Solved :)
