### ISSUE TITLE
Develop new analysers

### ISSUE THREAD

**Issue by AuBousquet** [osm-fr/osmose-backend#2214]
Hello. I am trying to develop new analysers for telecom data and I have two questions :

1. My dataset is locally stored in the `merge_data` folder. When I launch a merge analysis on the area where they are located, nothing happens. Should I do anything else than copying them into the merge_data folder before launching the analyses?
2. My data do not need to be finally integrated to the OSM dataset, but we would like to be able to visualize them using the frontend. Even if I do not really need the Merge_Analyser, I understand that I have to build one anyway, to be then able to make the Osmosis_Analyser work. Am I right?

Thank you in advance for your reply.

**Comment by frodrigo** [comment]
Adding an analyzer is required to interpret the data. It is the mapping configuration to conflate the specific data with OSM one.
- for linear network data eg look at https://github.com/osm-fr/osmose-backend/blob/37b2aee0ca11dc159c6a69c2f72aa898ffef463b/analysers/analyser_merge_power_line_FR.py#L25
- for punctual eg https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_merge_bicycle_parking_FR_niort.py

You can start by reading the doc, at least chapter 0 and 4.
https://github.com/osm-fr/osmose-backend/blob/dev/doc/4-Merge.md

**Comment by AuBousquet** [comment]
Thank you for your answer, I have already read this documentation and get inspired by 

My problem is that the new merge analyser I tried to develop is not working. Here is the code. https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_merge_power_line_FR.py#L25
https://github.com/AuBousquet/osmose-backend/pull/3/commits/c09a51fde52545cec3a9675235ffa7b53955f79c
Could you tell me what I am missing, knowing that my data are stored locally, in the `merge_data` folder?

**Comment by frodrigo** [comment]
You can check if the data are loaded int he database.

How do you lunch it ? Can you copy the log ?

**Comment by AuBousquet** [comment]
They are not. 
Here is the log, with the launched command.

https://pad.oslandia.net/s/yiobUjmki#

**Comment by frodrigo** [comment]
> They are not in the database.
> 
> Here is the log, with the launched command. https://pad.oslandia.net/s/yiobUjmki#
> 
> the temp file does not exist on my computer

It is not a public doc.

**Comment by AuBousquet** [comment]
[log.md](https://github.com/osm-fr/osmose-backend/files/15248458/log.md)
Here is the doc in markdown

**Comment by AuBousquet** [comment]
@frodrigo once the merge analysis is realised, is the merge operation with tables `ways`, `nodes`, etc. supposed to be manual? 

Is the osmosis analyser supposed to work on the original table imported in schema `osmose` or on tables located in the geographical schema: `ways`, `nodes`?

**Comment by frodrigo** [comment]
> once the merge analysis is realised, is the merge operation with tables ways, nodes, etc. supposed to be manual?

No. Analysis is the merge process.

> Is the osmosis analyser

osmosis is an other tool. This one is Osmose.

> Is the osmosis analyser supposed to work on the original table imported in schema osmose or on tables located in the geographical schema: ways, nodes?

Both, it merge both to produce the result file.

**Comment by AuBousquet** [comment]
Sorry, but I still do not really understand the understanding logic. If I want to merge an open-data source composed of two shapefiles, one of nodes and the other one of ways, do I need to:
- implement a class inheriting from Analyser_Merge class first to import data in the database and reformat it to the OSM nodes/ways format;
- and then implement a class inheriting from Analyser_Osmosis class to merge it to the downloaded OSM extract of the area and THEN analyse the integrity of the merged data.

Is this process right or am I misunderstanding something ?

For the second step, could you give me an example of an Osmosis_Analyser inherited class that work on imported open-data please? It looks like the other are analysing already merged data from the OSM extract, so I do not really understand how it should be implemented.

Thank you in advance.

**Comment by frodrigo** [comment]
> Sorry, but I still do not really understand the understanding logic. If I want to merge an open-data source composed of two shapefiles, one of nodes and the other one of ways, do I need to:

Osmose is for OSM data. The merge analyzer always merge one OpenData set with OSM. It is a tool to improve OSM.

**Comment by frodrigo** [comment]
So I not sure to understand your question. You can prepare data before running the analyzer itself by implementing a custom source. Osmose is not something like an ETL.

Eg of a custom source joining 2 CSV : https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_merge_fuel_IT.py#L92

**Comment by AuBousquet** [comment]
OK. Thank you. 

My main question is: is there a moment when the import data (in the `osmose` schema of the database) is really merged inside the `nodes`, `ways`, etc. tables of the OSM extract located in the other schema called like the downloaded country? Or should the analysis be done directly on the table located in the `osmose` schema when we are building a class inherited from `Analyser_Osmosis`?

Thank you in advance for your answer.

**Comment by frodrigo** [comment]
The merged data is not saved into the database, it produces the XML/geojson result for the frontend and a CSV of merged data.

**Comment by AuBousquet** [comment]
So if I want to analyse my two sources (one of type node and one of type way) all together in Osmose with a SQL analyser, I can either:
- import them manually into the `way` and `node` tables of the OSM extract schema ;
- work with the SQL analyser on the tables created in the `osmose` schema.

Which solution is more compatible with the Osmose logic according to you?

**Comment by AuBousquet** [comment]
@frodrigo Other question:
When I have my XML file, out of a merge analyser, what am I supposed to do with it? Which tool do you use to contribute to the OSM map with this file?

Thank you in advance for your answer.

**Comment by frodrigo** [comment]
I still not understand what you are trying to achieve.

> two sources all together

You wan to join two shapefiles before using it as one source in the Osmose analyser ?

> import them manually into the way and node tables of the OSM extract schema

The way and node table are load from the OSM data.

**Comment by AuBousquet** [comment]
I think I misunderstood the link with the frontend. Once your open-data has been analyzed by the back-end merge analyser, you need to validate the modifications via the frontend, isn't it? 

Then, it can be merged with OSM data, and analyzed by an osmosis analyser, and then validated again via the front-end.

That was the step I missed, I think.
