### ISSUE TITLE
Add analyser for overlapping highways

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2231]
https://www.openstreetmap.org/way/145265140 and https://www.openstreetmap.org/way/1175247716 fully overlap

However, there seems to be no analyser which detects these kind of complete overlaps.
Probably this holds for more types of linestring objects:
- highway
- railways
- waterways
- aeroways
- aerialways
- ... more?

Probably there should never be any overlap with linestring dimensions, except if one of the overlapping entries is a polygon. (E.g. a highway=pedestrian polygon can overlap with a linestring)

**Comment by frodrigo** [comment]
Note we already have analyser_osmosis_duplicated_geotag.py

**Comment by Famlam** [comment]
@didier2020 Fix is deployed and now detects the issue from the first post, thanks!
@frodrigo I do wonder about the spikes in the detection count, going up and down again: https://osmose.openstreetmap.fr/nl/issues/graph.png?item=1230&source=&class=1,2&username=&bbox=&start_date=2024-08. Do you see any logical explanation for this?

**Comment by didier2020** [comment]
> going up and down again: https://osmose.openstreetmap.fr/nl/issues/graph.png?item=1230&source=&class=1,2&username=&bbox=&start_date=2024-08. Do you see any logical explanation for this?

... Me , a lot issues in germany, 
https://www.openstreetmap.org/changeset/156711390 or https://www.openstreetmap.org/changeset/156711433

**Comment by Famlam** [comment]
Ah, thanks, then I guess it's safe to close this as fixed :)
