### ISSUE TITLE
False positive on light:colour values in color temperature format

### ISSUE THREAD

**Issue by Lumikeiju** [osm-fr/osmose-backend#2233]
The validator should not flag `light:colour` values entered as a colour temperature value and Kelvin unit (in the format `\d+\s[K]`, one or more digits, followed by a single whitespace, followed by exactly "K")

Item: 3091
Class: 30914
Subtitle: Unknown or invalid colour in tag 'light:colour'
Example: https://osmose.openstreetmap.fr/en/issue/f61e1c7c-43bd-5774-d242-e7ba50ee8268

**Comment by Famlam** [comment]
Thanks! The same holds for colors with `nm` units
https://wiki.openstreetmap.org/wiki/Key:light:colour

**Comment by Famlam** [comment]
Solved
