### ISSUE TITLE
False positive with mapillary unmapped maxspeed for `maxspeed:hgv:conditional`

### ISSUE THREAD

**Issue by Helium314** [osm-fr/osmose-backend#2241]
The Mapillary Unmapped Maxspeed issue (source 3400, item 8300, class 12) does appear near a way with `maxspeed:hgv:conditional` tagged.

Example: https://osmose.openstreetmap.fr/en/issue/dbd8296a-0a0e-11f1-9271-399b77d8c608 appears near https://www.openstreetmap.org/way/26922447

Could the nearby maxspeed check be extended to also understand `maxspeed:hgv:conditional`?

**Comment by Famlam** [comment]
Fixed
