### ISSUE TITLE
False positive with camp_pitch_out_of_camp_site

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-backend#2242]
https://osmose.openstreetmap.fr/en/issue/ed8b58e4-5207-c196-19fd-870b0023962d and https://osmose.openstreetmap.fr/en/issue/c18e9057-0bb8-9f63-6f7a-0f4013c590d3

Both https://www.openstreetmap.org/node/4985185474 and https://www.openstreetmap.org/node/4985185473 seem to be enclosed by https://www.openstreetmap.org/way/503134347, so not sure why they're being flagged

**Comment by Famlam** [comment]
Strangely enough I cannot reproduce this issue on osm110... 🤔

**Comment by frodrigo** [comment]
So, we may have a data corruption on the backend for usa_north_dakota.

https://buildbot.osmose.openstreetmap.fr/#/usa_north_dakota 

It is always build on the same backend.

@jocelynj

**Comment by jocelynj** [comment]
@frodrigo : this specific US state is using Geofabrik extracts. Do you want me to clear the extract cache on this backend?

**Comment by frodrigo** [comment]
Usually we have issue with osm-fr extracts, not geofabrik ones.

Maybe we can first check if the way 503134347 is in the extract ?

**Comment by jocelynj** [comment]
This way is present on the backend:
```xml
$ osmium getid -r -f xml /data/work/osmose/extracts/usa_north_dakota.osm.pbf w503134347
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.15.0">
  <node id="4934700049" version="2" timestamp="2020-01-30T23:40:18Z" lat="46.3707809" lon="-97.6265956"/>
  <node id="4934700050" version="1" timestamp="2017-06-25T00:27:40Z" lat="46.3719412" lon="-97.624729"/>
  <node id="4934700051" version="2" timestamp="2020-01-30T23:40:18Z" lat="46.3705218" lon="-97.6245761"/>
  <node id="4934700052" version="2" timestamp="2020-01-30T23:40:18Z" lat="46.3704626" lon="-97.6262685"/>
  <node id="4934700053" version="1" timestamp="2017-06-25T00:27:40Z" lat="46.3719542" lon="-97.6265556"/>
  <way id="503134347" version="1" timestamp="2017-06-25T00:27:45Z">
    <nd ref="4934700052"/>
    <nd ref="4934700051"/>
    <nd ref="4934700050"/>
    <nd ref="4934700053"/>
    <nd ref="4934700049"/>
    <nd ref="4934700052"/>
    <tag k="tourism" v="camp_site"/>
  </way>
</osm>
```

And the first node too:
```xml
$ osmium getid -r -f xml /data/work/osmose/extracts/usa_north_dakota.osm.pbf 4985185474
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.15.0">
  <node id="4985185474" version="2" timestamp="2020-01-30T23:40:18Z" lat="46.3706976" lon="-97.6259024">
    <tag k="ref" v="T3"/>
    <tag k="tourism" v="camp_pitch"/>
  </node>
</osm>

**Comment by Famlam** [comment]
@jocelynj as it's impossible to reproduce on osm110, and it only involves 2 cases, shall I just mark them as false positives? Or do you want to try debugging it further to find the root cause?

**Comment by frodrigo** [comment]
The issues are no more on the frontend database.
