### ISSUE TITLE
Add new analysis to detect minor_substations with operator=EDF/ERDF

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osmose-backend#2246]
We continue to have minor substations with operator=ERDF or EDF because the operator present on buildings wasn't updated when EDF has been splitted.

I have cleaned all substations and lines with ERDF (around 50 items), and I have planned to clean also operator=EDF.
But it can be good to add a new analysis to detect these cases and clean these items more regularly.

Maybe we can do this for other infrastructure operators who have changed their name? (GDF/Engie)

https://overpass-turbo.eu/s/1Nfo

**Comment by Jean-BaptisteC** [comment]
Another option:
We can add this check in substations integration analysis to suggest updating substation and not adding a new item
Example: https://www.openstreetmap.org/?mlat=48.3339165&mlon=6.6411846#map=19/48.33396/6.64144

**Comment by Famlam** [comment]
If it's a one-to-one conversion, then this could also easily be added to the French mapcss rules I think?
(But I'm not familiar with this, it's just a thought)

**Comment by frodrigo** [comment]
Yes. The right place to that is the JOSM MapCSS French Rules.

https://josm.openstreetmap.de/wiki/Fr%3ARules

**Comment by Jean-BaptisteC** [comment]
Thanks, I better understand how it's works with your presentation in SOTM FR

**Comment by Famlam** [comment]
@Jean-BaptisteC 
Is the following rule what you're looking for to have as a warning?
```css
node[power=substation][operator="EDF"][inside("FR")],
area[power=substation][operator="EDF"][inside("FR")] {
  throwWarning: tr("{0} together with {1}", "{0.tag}", "{1.tag}")
}
```

To test: 
1. Save the above in a file and call it "test2246.validator.mapcss" or something similar
2. open JOSM, go to preferences -> the side-tab Validator -> the tab Rules for tag checking -> "+" on the right
3. Add the file you just saved, and run JOSMs validator on any of such EDF substations
4. (Don't forget to remove it from the list in step 2 after you're done)

**Comment by Jean-BaptisteC** [comment]
Add warning on EDF is not adapted because EDF have some substations and power plant.
Warning is necessary on ERDF (older name of Enedis)

**Comment by Famlam** [comment]
Ah ok, I misunderstood your first post to be about substations of both EDF and ERDF. (I'm not from France)
For ERDF there is only 1 entry left, added 4 days ago, written in small capitals: https://www.openstreetmap.org/node/12072167609 (it was not really added newly: the same changeset removed it here: https://www.openstreetmap.org/node/2075195205/history)

Also GDF (1 substation, [w79256035](https://www.openstreetmap.org/way/79256035)) and Engie ([7 substations](https://overpass-turbo.eu/s/1OQ2)) have been mostly removed already.

If ERDF disappeared a long while ago I doubt people will continue adding it a lot?

**Comment by Jean-BaptisteC** [comment]
Yes you right, users don't adding a lot of operator=ERDF in the future.
But I'm sure they continue to add it because Enedis didn't plan to replace the name of the operator on the door of all substations.
I close the ticket
