### ISSUE TITLE
Bug when using the documentation about Docker

### ISSUE THREAD

**Issue by StC-OSM** [osm-fr/osmose-backend#2247]
I try to follow as strictly as possible the instructions in https://github.com/osm-fr/osmose-backend/blob/dev/docker/README.md, using a fresh Docker installation on a MacOS machine.  When I reach the "Running on a single country" section I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/osmose-backend/modules/../dictionaries/fr/reaccentue.pz'
ERROR: 1

```

**Comment by frodrigo** [comment]
Duplicate #1273

**Comment by frodrigo** [comment]
Fixed

**Comment by Famlam** [comment]
For what it's worth, this isn't restricted to macOS, also on Windows I've seen this a lot ;)
