### ISSUE TITLE
Add check for bridges connected to roads they cross

### ISSUE THREAD

**Issue by ComradeRamen** [osm-fr/osmose-backend#2249]
Bridges often get accidentally connected to the ways they cross. Examples: [307875034](https://www.openstreetmap.org/node/307875034),[8713078340](https://www.openstreetmap.org/node/8713078340),[11251420292](https://www.openstreetmap.org/node/11251420292),[2930285459](https://www.openstreetmap.org/node/2930285459) 9,000 nodes found globally when checking all highway tags

I found these by checking for nodes with connections within bridge and non-bridge ways. To avoid false positives, I checked that multiple bridge connections have the same highway tags and multiple non-bridge connections have the same highway tags, assigning single connections to nodes at the ends and double connections to nodes in the middle of a way.

I'm not sure where this analyzer would fit best

**Comment by ComradeRamen** [comment]
Highway Class Counts:
motorway: 443
motorway_link: 223
trunk: 855
trunk_link: 198
primary: 1327
primary_link: 70
secondary: 1131
secondary_link: 71
tertiary: 1507
tertiary_link: 44
unclassified: 901
residential: 1171
other: 10333

**Comment by Famlam** [comment]
Inconveniently it seems someone has fixed all your referred false positives.

I guess for connections with non-end nodes of the "bridge-way" this should be fairly fail-safe (and same for tunnels). E.g., this should always be bad (two uninterrupted ways of which one is a bridge, connected in a middle node)
![image](https://github.com/osm-fr/osmose-backend/assets/1315520/590f9dea-cfea-409d-9fc0-daf1d1d9b6f8)

It becomes more tricky with end nodes. E.g. a steps connecting to a bridge is not per se bad. And obviously the end node of the bridge way can be connected to anything.

Could you share the (probably) overpass query that you used to get those statistics?

**Comment by ComradeRamen** [comment]
Mappers will sometimes add turn restrictions as a "fix" which splits the ways. Others have used roads as members in boundary relations and will split the roads accordingly.
![image](https://github.com/osm-fr/osmose-backend/assets/150104144/a7c2bcec-4303-475d-ac92-0aabf80e6b53)

**Comment by ComradeRamen** [comment]
using this query in a python script
```
[out:xml];
way["bridge"]({south},{west},{north},{east});
>;
way(bn)["highway"];
(._;>;);
out meta;
```

**Comment by Famlam** [comment]
Hmm, that query also returns e.g. [this connection of ways](https://www.openstreetmap.org/node/736341939) , but I guess your script takes care of such cases?

I understand your concern w.r.t. splitting of roads. However, addressing this in a fail-proof way would (I think) become very complicated. E.g., in the following example, two bridges are connected with a non-bridge road at their end nodes, with turn restrictions, in a valid way.
![image](https://github.com/osm-fr/osmose-backend/assets/1315520/9a85f6c0-78b9-4843-8a30-156822ab8782)

**Comment by ComradeRamen** [comment]
Full [script](https://pastebin.com/ffhRwBpE) (mostly llm generated so not optimized)
Here are some of the end-node [connections](https://overpass-turbo.eu/s/1NId) it detected.
2732 of 9375 detections contain end-nodes

**Comment by ComradeRamen** [comment]
MapRoulete [challenge](https://maproulette.org/browse/challenges/48601) with just non-end connections.

**Comment by Famlam** [comment]
@ComradeRamen Results are here:
https://osmose.openstreetmap.fr/nl/issues/open?item=7012&source=&class=4,5,6,7&username=&bbox=

There's a notable amount of false positives involving highways as areas (usually `highway=pedestrian`). The fix for that is merged but not deployed yet.

**Comment by frodrigo** [comment]
> The fix for that is merged but not deployed yet.

Deployed
