### ISSUE TITLE
Allow litre (l) as an explicit unit for capacity if a volume is specified (e.g. for amenity=waste_disposal or amenity=grit_bin)

### ISSUE THREAD

**Issue by jajajaneeneenee** [osm-fr/osmose-backend#2251]
The value for capacity of a volume is normally specified in m³, but litre ("l") is also allowed (= documented) as an explicit specification (see [https://wiki.openstreetmap.org/wiki/Map_features/Units](https://wiki.openstreetmap.org/wiki/Map_features/Units)).

The integer capacity value check now reports an error if, for example, "capacity=350 l" is specified for amenity=grit_bin ("capacity" value "350 l" is not an integer).

I think, it should not throw an error. And not with m³ either. (Other volume units: I am not sure ... see below. But at least  "l" seems to be established and it is documented).

And, for example, for grit bins, the content is usually specified in liters and not in m³ on the container and is therefore probably preferred to be specified that way. I mention grit bin because I first encountered the problem with it – although there are currently only 147 cases of grit_bin + capacity (but growing ...) – but almost all of them with "l" (exact numbers see below). So this combination now has a nearly 100% Osmose error rate – I would say false positives. Therefore a special case ... But it also affects other tags (see below).

For waste disposals, there seem to be some incorrect information such as capacity=3200 (e.g. https://www.openstreetmap.org/node/10210997092), which would have to be a pretty large container... (capacity=800, etc. also occurs frequently). I think the unit "l" for litre is missing here – maybe because of incorrect validator messages people are using an integer only? Hoping someone will guess the right unit? Not a good idea in my opinion ... This is also why I am writing this issue.

I spontaneously think of these cases:

- amenity=waste_disposal (> 10 k uses with capacity=*, zero cases with "l", 360 cases with values > 100 – probably "l" missing)
- amenity=waste_basket (approx. 1600x used with capacity=*, 3 cases with "l" and 1335x with "litres")
- amenity=recycling (approx. 7700x used with capacity=*, 172 cases with "l")
- man_made=storage_tank (approx. 2000x used with capacity=*, 12 cases with "l", other cases with "gal" etc.)
- amenity=grit_bin (147x used with capacity=*, 143x with "l", 3x "l" missing => **>99% of the values in litre**)
- water=reservoir (> 100x used with capacity=*; not checked any further, but megalitres or hm3 seem to be used in some cases)
- emergency=water_tank (not checked any further)

(Because no key "volume" exists or is documented – [it is only used 336 times](https://taginfo.openstreetmap.org/keys/?key=volume#overview) – , "capacity" is probably used to specify the volume. And I think, it's OK.)

Further note: I also saw cases with undocumented volume units like:
- gal
- gals
- barrels
- litres
- megalitres
- Ml
- hm3
- there may be other volume units ...

I don't know if this is covered by another osmosis test or if it should be taken into account here as well. But there seems to be no widespread agreement yet on which volume units are OK other than "m³" and "l" (see also this [Wiki discussion ](https://wiki.openstreetmap.org/wiki/Talk:Map_features/Units#Volumes) from 2021 without result).

Note: See also (closed) issue #1733.

**Comment by Famlam** [comment]
Indeed, we should probably add some more exceptions to
https://github.com/osm-fr/osmose-backend/blob/72539f30ced6886ec7567037b76cc5a5fa444d8b/plugins/Capacity.py#L53

I guess we can just exclude the `water` key altogether (like `man_made`), and add the specific keys for `grit_bin` and `waste_disposal`. For emergency I'm not sure, probably just start with this specific tag.

**Comment by jajajaneeneenee** [comment]
Yes, I see ... it's tricky ...

The first solution would be fine for me at the moment (perhaps also add `waste_basket` to have that done too). 

It could perhaps be replaced by a regex if some more volume units are documented and/or established (it's perhaps not an infinite unit list and could be a still reasonable regex part like [l|litres|Megalitres|Ml|m3|Hm3|gal|gals|barrels] or some more units ...). I think this would at least significantly reduce the number of false positives.

A cleaner solution would certainly have been if someone had written a proposal for a `volume` key in time ... With clear specifications for the units etc. And to really only allow (restrict) `capacity` for integer capacity types which need no unit. But we are in the OpenStreepMap world ...

**Comment by jocelynj** [comment]
Note that `litres` can also be abbreviated as `L`, not only with `l`.

There was a discussion to use https://pint.readthedocs.io/en/stable/ as a python library to parse units. Could it be used to check if `capacity` is set to a valid volume measurement?

**Comment by Famlam** [comment]
I have a fix [ready](https://github.com/osm-fr/osmose-backend/tree/famlam-capacity-volume), just waiting for 2263 to be merged.
Only [a couple of units](https://github.com/osm-fr/osmose-backend/commit/10eebb91027a101fd7dacb8a7677c8c810db915b#diff-d376487ccb6816192f500423b8279401ea86f138eb7be2bbb05c26567be043e9R50-R55) are supported, limited to groups that have (some) use in OSM. E.g. I didn't add pint, quart, gill and a million others.

I realized that we can't replace the list with whitelisted tags because units are optional if the default unit is used. So to check if e.g. `capacity=9.8` is valid or not, we still have to check whether it belongs to e.g. `man_made=storage_tank` (valid) or `amenity=parking` (invalid)

**Comment by Famlam** [comment]
Deployed :)
