### ISSUE TITLE
False positive in test "Abbreviation of number should be in lowercase"

### ISSUE THREAD

**Issue by muralito** [osm-fr/osmose-backend#2254]
I don't know if osmose can handle rules based on the location of the analyzed object, but in spanish names (at least in Argentina and Uruguay) is common use, for the name of schools, to abbreviate "número" (number) in upper case.

See https://osmose.openstreetmap.fr/en/issue/c98241f9-2e49-bc90-88c5-ad7162690447
and https://osmose.openstreetmap.fr/en/issues/open?item=5010&class=905

The name of this school https://www.openstreetmap.org/node/3841949274 is correct, so this kind of situations shouldn't be reported as an issue, and similar issues closed as false positives if possible.

**Comment by frodrigo** [comment]
In Spain there is not just Spanish. But look ok anyway.

**Comment by frodrigo** [comment]
PR merged. It will require manual clearing in other Spanish speaking countries.

**Comment by frodrigo** [comment]
I deleted all issues 5010/905. Too hard to select. Let's the right one be back.

**Comment by muralito** [comment]
> I deleted all issues 5010/905. Too hard to select. Let's the right one be back.

Thanks.

**Comment by Famlam** [comment]
I think this is resolved? Only 8 left :)
