### ISSUE TITLE
Post Office integration: Internationalize the phone field

### ISSUE THREAD

**Issue by fgouget** [osm-fr/osmose-backend#226]
When Osmose suggests integrating a French Post Office it can sometime provide a value for the phone field. However when it does so it does not internationalize the phone number: it is does not prepend '+33' and remove the leading '0'. For instance it will suggest setting 'phone=0241822319' instead of the recommended 'phone=+33 2 41822319'.

And then quite often the number is '3631' which is not specific to the post office. As such it is of questionable value. Also, like all short numbers, as far as I know it cannot be called from outside France so it should not be internationalized. So internationalization must also recognize special numbers, or only be applied to numbers of the form '0[1-7][0-9]{8}' (not sure if 08xx and 09xx numbers can be internationalized).

(From trac bug report: https://trac.openstreetmap.fr/ticket/781)

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/error/13445585602
http://osmose.openstreetmap.fr/fr/error/13459311482

**Comment by frodrigo** [comment]
We missed a point.
There DOM data where the code is not +33.

**Comment by frodrigo** [comment]
Only 20 numbers. Do nothing for DOM.
