### ISSUE TITLE
FRANCE : sport : use data ES that gives sports centre and pitches

### ISSUE THREAD

**Issue by JLZIMMERMANN** [osm-fr/osmose-backend#2273]
In FRANCE since few months a new national database has been published online to let find sports infrastructures.
OSMOSE could help to integrate ID of "installations" and "équipements" and also check if OSM could add more pitches missing.

Database URL https://equipements.sports.gouv.fr/explore/dataset/data-es/table/

**Comment by frodrigo** [comment]
Already available since 2014 from https://equipements-sgsocialgouv.opendatasoft.com/explore/dataset/data-es/table/

https://osmose.openstreetmap.fr/fr/map/#loc=13/46.80902/1.70075&level=1%2C2%2C3&item=8170
