### ISSUE TITLE
building construction on complete is changed to building=building.

### ISSUE THREAD

**Issue by sekerob** [osm-fr/osmose-backend#2275]
Used SC yesterday to report a building construction complete (was per history tagged as building=construction). SC changed it to building=building. No good per ID and Osmose.

There show 481 entries per TagInfo in the OSM database.
https://taginfo.openstreetmap.org/search?q=building%3Dbuilding#tags

(Maybe the construction=house tag could be used to transfer the tag value to building=* and remove the construction tag on the go but if it's construction=building, more than often since there are 75k of these per TI, change the building tag to building=yes on completion).

**Comment by frodrigo** [comment]
This is not an issue to be reported to SC ?

**Comment by sekerob** [comment]
Well, it was an SC quest that changed building=construction to building=building upon answering the construction was complete. Who the owner is of the wheels I don't know, not want to know.

Until than, quest removed from SC to answer.

**Comment by sekerob** [comment]
Oh, sorry, searched for the SC backend and got Osmose backend as top reply by Mr Google.
