### ISSUE TITLE
new analyser_merge_milestone for guyane, mayotte and Saint-Pierre-et-Miquelon

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#2282]
i've update analyser_merge_milestone_FR_metropole at https://github.com/osm-fr/osmose-backend/pull/2281

i want to create new analyser(s) for other milestone but
i don't know how to do for RRN_2024_973-Guyane_shp, RRN_2024_975-Saint-Pierre-et-Miquelon_shp and RRN_2024_976-Mayotte_shp because of their spécific "projection"  set in BORNAGE_TOUT.prj

**Comment by frodrigo** [comment]
If the the shape file contains the project, and it is usually the case, there is nothing to do in particular about that.

**Comment by didier2020** [comment]
thanks, it's done but pull requests are not ok (?)

**Comment by frodrigo** [comment]
I see only the resource id change over the areas. Let's use only one analyser and just change the id according the the area.

You reuse (en rename) the existing `analyser_merge_milestone_FR_metropole.py`.

Look at this 
https://github.com/osm-fr/osmose-backend/blob/09e2bbfd30246de926d731c99bca6778e8c4f1f3/analysers/analyser_merge_healthcare_FR_finess.py#L47
https://github.com/osm-fr/osmose-backend/blob/09e2bbfd30246de926d731c99bca6778e8c4f1f3/analysers/analyser_merge_road_FR.py#L34

**Comment by didier2020** [comment]
something like

```python
        if config.db_schema == 'france_guyane':
            resource = 'e9288a97-faf1-4638-b3df-571ceae401f8'
        elif config.db_schema == 'france_saintpierreetmiquelon':
            resource = '9425939b-13f5-460d-a635-fcde0e05ade5'
        elif config.db_schema == 'france_mayotte':
            resource = '65060ce7-acc5-4546-a1ce-b9b47b40383f'
        else:
            resource = '90a65602-3ca4-41d7-bf7c-23d435c916e1'

...
            SHP(SourceDataGouv(
                attribution="data.gouv.fr:Ministère de la Transition écologique",
                dataset="57a837e2c751df5b90bb5dd4",
                resource=resource),
                zip='BORNAGE_TOUT.shp'),
```

**Comment by frodrigo** [comment]
> something like

Yes

**Comment by frodrigo** [comment]
Use `dep_code`, it is better.
