### ISSUE TITLE
Unfinished line on T connections (power 7040 class 2)

### ISSUE THREAD

**Issue by gustavecha** [osm-fr/osmose-backend#229]
Hi,
Some osmose tests look for unfinished linear features (like power lines, item 7040 class 2);
There are currently numerous false positive results, like this one : http://osmose.openstreetmap.fr/fr/error/13394096365

Osmose seems to look for the end of a line without proper tags, without checking for a connection to an equivalent feature.
The problem may occur in other similar tests

**Comment by pinkdroyd** [comment]
Also see (closed) issue #145

**Comment by gustavecha** [comment]
Thx @pinkdroyd for issue 145

I don't know why Frederic's commits didn't fix the issue in last April :(

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=7040&class=2,6
![image](https://user-images.githubusercontent.com/1785486/45083945-525f6c80-b0fd-11e8-8e8d-ec74d5f71b88.png)
