### ISSUE TITLE
South West of England Not Displaying Any Issues

### ISSUE THREAD

**Issue by DesertBear** [osm-fr/osmose-backend#2290]
Osmose is no longer displaying any issues in the south-west of England.  This issue occurs both with the Osmose overlay in the OpenStreetMap ID Editor and also directly on the [Osmose website](https://osmose.openstreetmap.fr/en/map/#loc=7/51.297/-2.532).

**Screenshot:**
![Untitled](https://github.com/user-attachments/assets/4c89abfb-7b97-4075-b4ad-07c57c0167cd)

**Comment by frodrigo** [comment]
The issue may come from polygons.openstreetmap.fr (used by Osmose). The poly looks ok on osm.org not on polygons.openstreetmap.fr

![image](https://github.com/user-attachments/assets/20b3049a-e36a-40ac-af58-23898d87acad)

**Comment by jocelynj** [comment]
The polygon generated by the website was fixed - http://polygons.openstreetmap.fr/get_image.py?id=151339&params=0.020000-0.005000-0.005000.

Errors are now reported on Osmose, but it seems that we have less errors than expected.

**Comment by frodrigo** [comment]
I see no change, but the polygon is in cache on backend side. We should wait, or clear it.

**Comment by jocelynj** [comment]
You’re right: it was cached on osm212. I’ve removed the 4 files linked to it (for http://polygons.openstreetmap.fr/get_wkt.py?params=0&id=151339 and http://polygons.openstreetmap.fr/index.py?id=151339)

**Comment by frodrigo** [comment]
We finally got it back. Thank all.
