### ISSUE TITLE
How process for adding suggestion from external dataset looks like?

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#2293]
If I found a large datasets that appears to be license-compatible with OpenStreetMap - is it possible to add it to Osmose suggestions?

I see some at https://github.com/osm-fr/osmose-backend/tree/master/analysers but I am not sure are you open to potentially adding more, and what kind of requirements/checks are needed first.

I looked at https://github.com/osm-fr/osmose-backend/blob/dev/CONTRIBUTING.md and I have not found anything about it

**Comment by frodrigo** [comment]
Yes, adding external dataset is welcome.

The doc is here, but only technical : https://github.com/osm-fr/osmose-backend/blob/dev/doc/4-Merge.md

The pre flight checklist is not written:
- license compatibility
- quality of the data
- agreement of the local community - the format may depend of the community, some see that as help to manual integration, other as disguised import or mechanical edit.

And last, not too large dataset, too large dataset or endless task is to avoid (eg avoid address points).

**Comment by matkoniecz** [comment]
thanks for a quick answer!

> And last, not too large dataset, too large dataset or endless task is to avoid (eg avoid address points).

oh, it sounds like what I had in mind will not be suitable at all as it completely fails this requirement
