### ISSUE TITLE
Merge of Electra EV charging station : wrong email, new wikidata Q, avoid all in uppercase

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#2296]
for ex https://www.openstreetmap.org/node/10915648445
https://osmose.openstreetmap.fr/fr/issue/eeccc11d-36cf-3322-3792-b3d0e7f6cf5b
item | 8411
class | 3

email is wrong : not the email about this osm item -> delete
operator:email is wrong, not the good firm -> fix help@go-electra.com
brand/operator/owner is in uppercase -> fix Electra
I have create Q128592938 for brand/network, we may add brand:wikidata and network:wikidata
and Q128597425 for owner:wikidata=Q128597425

**Comment by frodrigo** [comment]
I think it should be reported to https://github.com/Jungle-Bus/ref-EU-EVSE

**Comment by Marc-marc-marc** [comment]
done with https://github.com/Jungle-Bus/ref-EU-EVSE/issues/8
feel free to close this ticket if you think it's ok or keep open until upstream feed is fixed

**Comment by Marc-marc-marc** [comment]
according to https://github.com/Jungle-Bus/ref-EU-EVSE/issues/8#issuecomment-2271687486
a part of the issue need https://github.com/osm-fr/osmose-backend/pull/2300 to be fixed
