### ISSUE TITLE
Pakistan oneway deadend check is mostly false positives.

### ISSUE THREAD

**Issue by ComradeRamen** [osm-fr/osmose-backend#2303]
The oneway deadend check in [Pakistan
](https://osmose.openstreetmap.fr/en/issues/open?country=pakistan&item=1210&level=1,2,3&source=&class=3&username=&bbox=&limit=1500) is returning mostly false positives. 
![image](https://github.com/user-attachments/assets/780f2ab7-ef6d-47e0-a377-00d091298e7c)

**Comment by ComradeRamen** [comment]
[Lebanon](https://osmose.openstreetmap.fr/en/issues/graph.png?country=lebanon&item=1210&level=1,2,3&source=&class=3&username=&bbox=&limit=500) as well

**Comment by frodrigo** [comment]
Does not look linked to one of the recent changes of the analyser.

@jocelynj maybe corrupted extract on the backend?

**Comment by jocelynj** [comment]
Pakistan and Lebanon are both using extracts from Geofabrik, not from OSM-Fr. If I remember correctly, they are handled by an external server.

**Comment by Famlam** [comment]
Both Pakistan and Lebanon run on the server listed as `is-svavar.k` on the update_summary page. 

Given that class 3 only runs in normal mode, not diff mode, it should give the same results on `osm110` and `is-svavar` . However, on osm110 (with a freshly downloaded extract of Pakistan) I only get 134 issues for class 3, not the [1240](https://osmose.openstreetmap.fr/en/issues/graph.png?country=pakistan&item=1210&level=1,2,3&source=&class=3&username=&bbox=&limit=1500&start_date=2024) currently displayed on the frontend.

Pakistan also has very frequent issues with osmosis_highway_floating_islands failing to complete according to the update_matrix (which I've never been able to reproduce either) and displays quite some spurious warnings. I'm not sure if it's a coincidence, but floating_islands on frontend for Pakistan displays [16748](https://osmose.openstreetmap.fr/en/issues/graph.png?country=pakistan&item=1210&level=1,2,3&source=&class=4&username=&bbox=&start_date=2024) issues, floating_islands on osm110 only gives me 4650 results.

Both of the graphs also display a very interesting pattern where the issue count went to 0 in June just before they started to rise very rapidly.

So I don't think there is an issue with the analyser. Given the same data, osm110 should've returned the same results as the 'live' server.

**Comment by frodrigo** [comment]
Ok, thank you. I send a email to Svavar.

**Comment by Kjarrval** [comment]
Thanks for submitting this issue.

All country extracts in the tmp folder have been erased. Assumption is that fresh ones will be retrieved and processed on the next regular run.* If that doesn't solve this issue, feel free to send me another e-mail.

* Did a test with Turkmenistan which completed, although with errors that the Osmose results were already up-to-date.

**Comment by Famlam** [comment]
Lets keep it open for a bit, it seems the floating_islands analyser didn't successfully complete.
Not sure if it didn't run yet or whether there was an error

**Comment by Kjarrval** [comment]
It was the only one Pakistan analyser that didn't complete. Here's the error snippet from the log:

> 2024-08-12 10:31:12   ^[[0;31merror: error on analyse osmosis_highway_floating_islands...^[[0m
> 2024-08-12 10:31:12     Traceback (most recent call last):
> 2024-08-12 10:31:12       File "/osmose/backend/./osmose_run.py", line 275, in execc
> 2024-08-12 10:31:12         analyser_obj.analyser()
> 2024-08-12 10:31:12       File "/osmose/backend/analysers/Analyser_Osmosis.py", line 321, in analyser
> 2024-08-12 10:31:12         self.analyser_osmosis_common()
> 2024-08-12 10:31:12       File "/osmose/backend/analysers/analyser_osmosis_highway_floating_islands.py", line 146, in analyser_osmosis_common
> 2024-08-12 10:31:12         self.run(sqlb13)
> 2024-08-12 10:31:12       File "/osmose/backend/analysers/Analyser_Osmosis.py", line 631, in run
> 2024-08-12 10:31:12         self.run00(sql)
> 2024-08-12 10:31:12       File "/osmose/backend/analysers/Analyser_Osmosis.py", line 577, in run00
> 2024-08-12 10:31:12         self.giscurs.execute(sql)
> 2024-08-12 10:31:12       File "/home/kjarrval/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 146, in execute
> 2024-08-12 10:31:12         return super().execute(query, vars)
> 2024-08-12 10:31:12     psycopg2.errors.OutOfMemory: out of memory
> 2024-08-12 10:31:12     DETAIL:  Failed on request of size 221727528 in memory context "ExprContext".
> 2024-08-12 10:31:12

**Comment by Famlam** [comment]
> OutOfMemory
> sqlb13

**Comment by frodrigo** [comment]
Pakistan was updated. So I close.
Thank you all.
