### ISSUE TITLE
Support `FX` country code

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2318]
In [this modification](https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules?action=diff&version=94&old_version=93) the France-specific mapcss rules switched some rules from `[inside("FR")]` (all of France) to `[inside("FX")]` (only mainland France + nearby islands)

This is valid per https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation#Territoryselector
Also defined here: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations

However, when updated those rules unfortunately won't match anymore within Osmose as FX is not a known country code in the configuration. (Nor is there a 'dictionary' of country code aliases in the mapcss parser)

**Comment by frodrigo** [comment]
cc @didier2020

**Comment by didier2020** [comment]
i've update josm'rules, include dept description with 3 digit for
guyanne, St Pierre et Miquelon and Mayotte and miss Corse
(0[1-9]|1[0-9]|2[1-9]|[3-8][0-9]|9[0-5]|973|975|976)

**Comment by didier2020** [comment]
"""(Nor is there a 'dictionary' of country code aliases in the mapcss parser)"""
https://josm.openstreetmap.de/export/HEAD/josm/trunk/resources/data/boundaries.osm

**Comment by Famlam** [comment]
> """(Nor is there a 'dictionary' of country code aliases in the mapcss parser)""" https://josm.openstreetmap.de/export/HEAD/josm/trunk/resources/data/boundaries.osm

Sorry, I meant our mapcss parser ;)

I think we can just have a dictionary in there (or in mapcss2osmose already, out of the runtime python code) to convert FX to a list of FR-* values, if these are known

**Comment by Famlam** [comment]
@didier2020 I've just added support for `FX`.
