### ISSUE TITLE
Discordant maxspeed and source:maxspeed in Belgium

### ISSUE THREAD

**Issue by nobohan** [osm-fr/osmose-backend#232]
Hi, 

Recently (~10 days ago) appeared a lot of errors #3032 for the E25 motorway in South-East Belgium. The error says "discordant maxspeed and source:maxspeed". However, this seems correct to me: maxspeed = 120 and source:maxspeed=BE:motorway. In Belgium, the max speed limit for motorway is 120, not 130 as in France. 

Is it a rule that is misapplied to Belgium? 
Also, I could not find in this github repo where I can find the code corresponding to this issue? 

Thanks!

**Comment by nobohan** [comment]
OK, I think I found: we should add an entry:  `'be:motorway': ['120'],` in maxspeed_table in https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Maxspeed.py

**Comment by frodrigo** [comment]
Please can you fix the table in https://wiki.openstreetmap.org/wiki/Speed_limits
Il will also fix OSRM.

**Comment by nobohan** [comment]
I've fixed the table.
