### ISSUE TITLE
Google Open Buildings / google_africa_buildings is a valid source

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#2323]
item | 3020
class | 706

https://www.openstreetmap.org/way/1069265880
source=esri/Google_Africa_Buildings
or
https://www.openstreetmap.org/way/1069265603
source=esri/google_africa_buildings

but [Google Open Buildings has the ODbL as one of its licences](https://sites.research.google/open-buildings/), which makes it compatible with osm

**Comment by Famlam** [comment]
> **Why two licenses?**
> We wanted to make the data compatible for ingestion by those working with ODbL-licensed datasets (namely the OpenStreetMap community) while enabling people who don't use ODbL licensing to use it under the terms of the CC BY-4.0 license. We hoped to take away the burden of figuring out whether the two licenses were compatible and simply release the data set under both licenses.

I think you're correct. If I read https://community.openstreetmap.org/t/google-publishes-buildings-footprints-v3/101126 correctly (I'm not an expert of this legal stuff) I guess the attribution in `source=*` is mandatory too.

**Comment by Marc-marc-marc** [comment]
thanks
