### ISSUE TITLE
Potential false positive for natural rock shelter

### ISSUE THREAD

**Issue by Nekzuris** [osm-fr/osmose-backend#2326]
I'm not sure if this is a false positive:
`natural=stone` or `rock`
`amenity=shelter`
(`shelter_type=rock_shelter`)

https://osmose.openstreetmap.fr/fr/issue/b10ce891-ec0a-cb4c-1ee6-1be339e804be

**Comment by Famlam** [comment]
I honestly don't know either, I can argue in favor of either.
As there's only [16 of them worldwide](https://overpass-turbo.eu/s/1QKR), maybe it's best to just mark them as false positives for now? Just my opinion, not sure if others agree.
