### ISSUE TITLE
Large number of incorrect 30317 in Ukraine

### ISSUE THREAD

**Issue by nyurik** [osm-fr/osmose-backend#233]
http://osmose.openstreetmap.fr/en/errors/?source=14671&item=3031&class=30317

"Same wikipedia topic on other language"	28874

Ukraine it seems almost always uses both wikipedia and wikipedia=ru, yet for some reason, it suggests replacing existing wikipedia tag with some other ones.

**Comment by frodrigo** [comment]
Add an exception for Ukraine.

**Comment by frodrigo** [comment]
Done:
http://osmose.openstreetmap.fr/fr/errors/?source=14671&item=3031&class=30317
http://osmose.openstreetmap.fr/fr/errors/graph.png?source=14671&item=3031&class=30317
