### ISSUE TITLE
leisure=barefoot + highway=path/footway is a valid/mandatory/documented combination 

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#2331]
item | 4030
class | 900
https://www.openstreetmap.org/way/1050816230
Conflict between tags: highway, leisure
but wiki said : [Requires highway=path or highway=footway](https://wiki.openstreetmap.org/wiki/Tag:leisure=barefoot)

**Comment by Famlam** [comment]
The fix is live :)
