### ISSUE TITLE
bug with tag addr:street not matching a street name around

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#2342]
https://osmose.openstreetmap.fr/en/issue/ccae58df-0725-342d-cfdb-73de746ba44f
item 2060
class 19

https://www.openstreetmap.org/relation/7533821
highway=pedestrian
name=Place Nationale

https://www.openstreetmap.org/node/5777686516
addr:housenumber=5
addr:street=Place Nationale

**Comment by Famlam** [comment]
Duplicate of #2050

**Comment by Marc-marc-marc** [comment]
2050 is about a MP issue, this one is about a polygon, maybe not the same issue

**Comment by Famlam** [comment]
https://www.openstreetmap.org/relation/7533821 is a multipolygon too, what do you mean?

**Comment by Marc-marc-marc** [comment]
you are right, sorry
