### ISSUE TITLE
Bug in "Lone power tower or pole" check?

### ISSUE THREAD

**Issue by osmtools** [osm-fr/osmose-backend#235]
Is there a bug in "Lone power tower or pole" check?
http://osmose.openstreetmap.fr/de/errors/?item=7040&class=1

Just every power tower/pole has currently this error.

**Comment by frodrigo** [comment]
Do you still think there is a problem ? I don't see one. Lone power towers or poles are really alone.

**Comment by osmtools** [comment]
No, it's gone... everything is fine now.
