### ISSUE TITLE
Incorrect error message Invalid postcode

### ISSUE THREAD

**Issue by woodyBu** [osm-fr/osmose-backend#2351]
Hi,

the error messages “Invalid street level postcode 53844 for country code DE” are incorrect
https://osmose.openstreetmap.fr/de/map/#level=1%2C2%2C3&loc=17/50.77821/7.100168&item=3190
the zip codes are all correct here.

woodyBu

**Comment by frodrigo** [comment]
Date come from 
https://en.wikipedia.org/wiki/List_of_postal_codes

Maybe we have a parsing issue with historic data for DE.

**Comment by Famlam** [comment]
Could it be related to the change to the wiki on Oct 7?
It _should_ be fine for Germany as the table is read top-to-bottom (see #2202) and the newer entries overwrite the older?

**Comment by Famlam** [comment]
Solved :)
