### ISSUE TITLE
TagWatchFrViPofm.py : "meaning" of s<>r in self._update_ks_vs for quote management

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#2353]
what's the "meaning" of s<>r in self._update_ks_vs for quote management at https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagWatchFrViPofm.py#L76

**Comment by Famlam** [comment]
I'd say `k=key, v=value, r=regex, s=string`
I'm however very curious what FrViPofm itself means 😅 

Also I'm not sure why it displays `(rule ks)`, `(rule kr_vs)` etc in the message to the end user

**Comment by frodrigo** [comment]
Ask him directly @FrViPofm

**Comment by Famlam** [comment]
Oh, it is a username, I didn't realize that 🙈. Apologies 😅

**Comment by Famlam** [comment]
@Marc-marc-marc I assume your initial question has been answered by my first reply? Please reopen otherwise :)

**Comment by FrViPofm** [comment]
Sorry. I come late...
I wrote a parser for a French wiki page, long long time ago. But the code and osmose were simpler,. I'm very proud of being mentioned in the name of the function.. But I'm not the author.  I think I'm not skillful enough in python to write like that.
Sorry.

**Comment by FrViPofm** [comment]
@Famlam **Fr**iar **Vi**ncent **P**ottier **O**rdo **f**ratrum **m**inorum
