### ISSUE TITLE
Tree vs wiki plugin is (also) broken / universal wiki parser solution? 

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2357]
At this moment the tree vs wiki check is broken because:
1. ~the table is a mix of multi- and single-line entries (nevermind, probably this still works)~
2. Someone added the wikidata entries as link (thus adding a `|`)

Both break the parser. (Although it'll work for a few more days due to the cached version) 
cc @ivanbranco, see also #2224

This raises two questions for me:
1. What's the future of this table (because it's said to be intended for QA tools), 
2. Since we have a lot of wikidata parsers in various plugins (and corresponding issues every time someone adds a template, hyperlink, switches multi/single-lines..., is there a python package which can do this for us instead?
If not, I'll probably make a module with some universal functions like `remove_templates()` and `link_to_displaylink()`

Similar issues with tables: #2345 #2351

**Comment by ivanbranco** [comment]
That page was originally created by me with QA tools in mind, so if you confirm the Wikidata links are causing issues, I'd suggest reverting it to the previous state. It might also be helpful to add a note on the page, encouraging discussion before making significant changes to the table, especially since the table is actively used by at least one QA tool (this one).

**Comment by Famlam** [comment]
I found two libraries to parse wiki tables. I'll give that a try first :)

**Comment by Famlam** [comment]
The new wiki table parser seems to work, results are back :)

**Comment by Famlam** [comment]
@ivanbranco As a heads-up: someone again modified the wiki by adding a new column so everything is broken again, results will disappear as soon as the cache expires :(
I've added a warning to the wiki... and will look into fixing the code again.
