### ISSUE TITLE
Can't have correct solution for item 8110 (FR)

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#236]
Hello,

When osmose throws a warning for public service "Caisse d'allocations familiales (Caf) " not found (item 8110-FR), it suggests a fix with tag "office=administrative".

But, such a fix raises another warning : item 4010, "The tag or combination key/value is no longer used". Indeed, "office=administrative" is deprecated in favour of "office=government".

And changing value to "office=government" makes osmose to raise item-8110 again.

What is the correct fix for these warnings ?
While we are here, if "office=government" is required, what should be the value of "government=*" ? government=public_service ? government=social_services ?

**Comment by frodrigo** [comment]
There many office=administrative in
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_service_public_FR.py

Please, can you suggest appropriate government tag for each ?

**Comment by laurentriffard** [comment]
Hello @frodrigo,
who are you asking for suggestion ? me ?

**Comment by frodrigo** [comment]
@laurentriffard : yes you or anybody interested in.

**Comment by laurentriffard** [comment]
I don’t know if I’m the best person to make a proper suggestion. As Osmose may be normative, this should be discussed on french forum, no ?

Nevertheless, for « Caisse d'Allocations Familiales », « Caisse Primaire d'Assurance Maladie », I would suggest office=government + government=social_services. 

What are « ServicePublic_FR_CG_CR » ? Conseil Général and Conseil Régional ? In this case, I would suggest office=government + government=parliament (they are local parliament, no ?).

**Comment by deuzeffe** [comment]
Briefly:
- Analyser_Merge_ServicePublic_FR_EPIC: EPIC are so various in their goals than it seems hard to find a common tag;
- Analyser_Merge_ServicePublic_FR_CG_CR: prop. from @laurentriffard seems ok;
- Analyser_Merge_ServicePublic_FR_CAF: social_facility=outreach, network: Caisse Nationale des Allocations familiales;
- Analyser_Merge_ServicePublic_FR_CPAM: social_facility=outreach, network: Caisse Nationale de l'Assurance Maladie.

**Comment by frodrigo** [comment]
So, for EPIC we set `office=government`?

**Comment by deuzeffe** [comment]
To be sure, EPIC as _Établissement public à caractère industriel et commercial_?

**Comment by deuzeffe** [comment]
So do I ^^ (eg cf list on WP : https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:%C3%89tablissement_public_%C3%A0_caract%C3%A8re_industriel_et_commercial_en_France ) I can't find a relevant tag/key. 

If office=government is used, so government= must be specified. Can't be automated, I'm afraid.

**Comment by frodrigo** [comment]
Hey! I works (finally) :champagne:
