### ISSUE TITLE
Turn:lanes:forward and change:lanes:forward on oneway roads.

### ISSUE THREAD

**Issue by WilliamHarrisonGB** [osm-fr/osmose-backend#2360]
Greetings, I am currently the biggest solo mapper in my subfield of traffic infrastructure data in OSM as of right now. 
I am specialized in adding data for turn:lanes:*, change:lanes:*, maxspeed=*, lanes:* etc.
as with every project, I do my best to communicate with other fellow mappers in the city / area limits.
one of them told me that there were a lot of 'suspicious combination' errors related to turn:lanes:forward and one way roads and that it was interfering with the OSMOSE map.
I can definetly say that turn:lanes:forward and change:lanes:forward are exactly the same as turn:lanes and change:lanes on one way roads.
it only becomes a problem when its turn:lanes:backwards and change:lanes:backwards combined with oneway=yes.
I kindly ask for this to fixed, I wait for your thoughts on this,
Thank you.

**Comment by Famlam** [comment]
I looked one up for you. Item 9001, class 9001002
https://osmose.openstreetmap.fr/nl/issue/d1cb17e1-0d86-f56a-a724-b802162565bf

This rule originates from JOSM, specifically [this line](https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss#L316):
```
way[oneway?  ][/:forward/ ][!traffic_sign:forward ][bicycle:forward!=use_sidepath ][/^oneway:(bicycle|bus|mofa|moped|psv)$/!~/^no$/][!/^oneway:(.+:)?conditional$/],
```

The JOSM rules are only imported into Osmose. As a consequence we cannot change this ourselves, so you'd have to report it to them to get this changed. 
However, personally I would agree with JOSM that it does not make sense to use unnecessary `*:forward` suffixes.

**Comment by WilliamHarrisonGB** [comment]
Yes, I do agree that the suffix is unnecessary but it in itself should not provoke a suspicious tag combination.
Thank you for the guidance.
