### ISSUE TITLE
Delete false-positive route, is it a new route ?

### ISSUE THREAD

**Issue by NicolasPyIGN** [osm-fr/osmose-backend#2364]
Hi,
We discovered that https://osmose.openstreetmap.fr/api/docs contains a DELETE route for false-positive.
![Screenshot 2024-10-16 at 14-06-16 FastAPI - Swagger UI](https://github.com/user-attachments/assets/47672580-4228-41c1-bbc4-36722eb5e89d)

is it something already existing we missed or is it a new route ?

Since we are interested at the osmose false-positive, we are concerned by the governance of that route. Who can use it, for what purpose ?

**Comment by frodrigo** [comment]
The delete was here for long time.

Deleting a false positive make it appears again on the map. Anyone browsing the false positive web list or calling the API can use it.

**Comment by NicolasPyIGN** [comment]
If I understand clearly, "Anyone browsing the false positive web list or calling the API can use it." means that everyone can remove the false-positive tag of a Osmose report ; and if the discrepancy between OSM and the reference data still exist then a new Osmose report to be analyzed by contributors is created ?

**Comment by frodrigo** [comment]
Right.

**Comment by NicolasPyIGN** [comment]
As an NMCA, I check the false-positive Osmose reports attached to our data. If we disagree with that tag false-positive, aka our data is ok, do we need to delete the false positive ?

**Comment by frodrigo** [comment]
> NMCA

?

> do we need to delete the false positive ?

It could make a loop of flag / unflag as false positive if OSM vs IGN differ on definition or interpretation. I think it is better to not do it.
