### ISSUE TITLE
3030 + 8235 tag value: office=yes

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#2375]
"value
tag value: office=yes => office=* (rule ks_vs)"

Osmose suggests me to change `office=yes` to `office=*` which is ridiculous.

Also, I don't know what does "rule ks_vs" mean. Could you use more understandable language?

**Comment by Famlam** [comment]
Removing the `(rule [code])` from the user output is IMO a good idea (see also https://github.com/osm-fr/osmose-backend/issues/2353#issuecomment-2422610845 ) so I made a PR for that.

The results of this plugin are directly obtained from [this wiki page](https://wiki.openstreetmap.org/index.php?title=Tagging_mistakes) and can be edited by anyone. I suppose this `office=yes` rule is supposed to indicate that `office=yes` is not specific and a more specific value of `office` should be used.

**Comment by frodrigo** [comment]
Note there a long cache of the wiki page in Osmose.

If the report is too frequent in your area, we must think of adding "not for" (like "only for"). It is already implemented in Osmose but not on the wiki page.

**Comment by Famlam** [comment]
Should this issue remain open?
The `rule ks_vs`-message has been removed and this fix has been rolled out.
Regarding the specific `office=yes` case, it seems `office=yes` is pretty equally spread across the world, so I don't think not_for would resolve the request from the first post. I think a wiki update would be a better solution _if_ the rule is indeed bad. (However, I guess in nearly all cases office=yes can be replaced by at least one of the [other generic `office=*` tags](https://wiki.openstreetmap.org/wiki/Tag%3Aoffice%3Dyes) and at 85k cases worldwide it's a lot, but not too much, so I personally won't remove it)

**Comment by maro-21** [comment]
Sometimes it is not possible to determine the type of office. Office=yes is as correct as building=yes.

I removed it from Wiki and I hope it will be updated on Osmose as well.

I would prefer that Osmose find actual errors, not something like this. Which has similar priority to "add missing delivery=yes/no to amenity=restaurant".

**Comment by Famlam** [comment]
> I removed it from Wiki and I hope it will be updated on Osmose as well.

Should take 1-2 days, but this will happen automatically :)
A lot of entries will disappear, since I also removed a lot of duplicates of redundancies from the wiki earlier today
