### ISSUE TITLE
5080 false positives for "Close similar name" with roman numerals

### ISSUE THREAD

**Issue by Amunak** [osm-fr/osmose-backend#2383]
We have a lot of numbered streets in Prague with only a roman numeral distinguishing them, and Osmose reports them as suspicious (see [issues like this](https://osmose.openstreetmap.fr/en/issue/2dcdeaec-bf4f-9f3c-35d4-80d6c1c9356d)).

From reading [the source regex](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_name_close.py#L34) it seems like this case should be skipped, but isn't for some reason.

Can you look into it please?

**Comment by Famlam** [comment]
Interesting, there's more strange errors with those names. For instance "_No street with name "Herálecká II" found around_" directly next to a street with that name https://www.openstreetmap.org/way/234453526

**Comment by Famlam** [comment]
Oh, I see, there's a special character used:
`Ⅱ` and `Ⅲ` instead of `II` and `III`
(The first two are a single character, the latter multiple uppercase i)

Is this a common script thing in your alphabet / street numbering?

**Comment by Amunak** [comment]
Ahh interesting. I don't think you can even have characters like that in official street names; to me this appears more like a thing where an editor or maybe even the keyboard just automatically replaces the characters with the unicode for the roman numeral (or maybe the user just did it? Idk).

Like, technically it is a more correct representation, but I can also see how it could cause issues. With that being said I think the solution would be to just add the "number forms" [unicode range](https://en.wiktionary.org/wiki/Appendix:Unicode/Number_Forms) to the regex.

**Comment by Famlam** [comment]
I would agree it's wrong to warn about "close similar names" indeed, because it's like "street 1" vs "street 2", so we should fix that.

**Comment by Famlam** [comment]
Fix is deployed
