### ISSUE TITLE
False positives for fjords as ways

### ISSUE THREAD

**Issue by andrebk** [osm-fr/osmose-backend#2395]
Item: 1170
Class: 4
[Details page of an example of the issue](https://osmose.openstreetmap.fr/en/issue/abb9b8d7-ffa5-2d7b-6144-83464b374ece)

A consistent false positive recently popped up in Norway for fjords drawn as ways, stating that they "Should be polygon, part of multipolygon or not having area tag".  This is wrong. Drawing fjords as linear ways is established practice, and it is not required for them to a polygon or part of multipolygon. The ways marked with the issue do not have an area tag, so that is also not relevant.

I see there is some discussion in #1152 where some people think fjords should not be drawn as ways. This is incorrect according to the OSM wiki. From the [`natural=bay` page](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dbay):

> Bays are frequently mapped as nodes, and rarely as areas. Fjords are also mapped as linear ways.

> Fjords ([bay=fjord](https://wiki.openstreetmap.org/wiki/Tag:bay%3Dfjord)), which are long, narrow bays, may be mapped as a linear way.

And from the [`bay=fjord` page](https://wiki.openstreetmap.org/wiki/Tag:bay%3Dfjord):

>  #### Linear ways
> - Many fjords area mapped as linear ways, particularly narrow fjords without branches.
> - branches with a separate names may have a separate way connected to the main branch/trunk of the fjord.
> - branches are sometimes collected in a relation, together with the main branch/trunk of the fjord, in order to indicate separate names for each branch but still indicate which fjord they belong to.

Fjords _can_ also be mapped as areas using polygons or multipolygons, but this is not required and should therefore not be an error in osmose (especially not at the "high" severity level).

**Comment by Famlam** [comment]
`natural=bay` seems to be in the results since [2012](https://github.com/osm-fr/osmose-backend/commit/93aefc1273bfd65619f5bd6d821002a7602fa510) 

I'd be fine with removing it from the analyser here:
https://github.com/osm-fr/osmose-backend/blob/37b47850653e7978ddbd3151f7694f88a94a1b2e/analysers/analyser_osmosis_relation_multipolygon.py#L186

**Comment by Famlam** [comment]
Fair enough, so only whitelisting `bay=fjord`?

**Comment by andrebk** [comment]
> `natural=bay` seems to be in the results since [2012](https://github.com/osm-fr/osmose-backend/commit/93aefc1273bfd65619f5bd6d821002a7602fa510)

My apologies, seems it was only recent to me since a mapper added a bunch of fjords in my area.

> A bay that is not a fjord could be way ? Or way are only for fjords ?

From reading the wiki it seems that fjords are the only bays that are drawn as ways.

So it seems Famlams suggestion of whitelisting `bay=fjord` should be sufficient to resolve this.

**Comment by Famlam** [comment]
The fix has been deployed and the [number of detections](https://osmose.openstreetmap.fr/nl/issues/graph.png?item=1170&source=&class=4&username=&bbox=&start_date=2024-11&country=norway*) has reduced quite significantly.

Note that any fjord without the `bay=fjord` tag will still be flagged as error :)
