### ISSUE TITLE
Remove bus stop in analyser_merge_railway_railstation_FR.py

### ISSUE THREAD

**Issue by Olyon** [osm-fr/osmose-backend#240]
Les données de la SNCF contiennent les gares de train et aussi des arrêts utilisés par les cars TER. Ces arrêts de cars ne doivent pas être taggé railway=station.
Il faudrait faire un tri dans les données et ne s'occuper que des gares de trains.
Dans le fichier de données il semble y avoir des lignes avec un "stop_id" de la forme : 
StopArea:OCE80142927 pour des stop area regroupant 1 ou 2 stop point. 2 seulemnt quand la gare est un arrêt pour des train TER et des car TER.
StopPoint:OCETrain TER-80142927 pour les gare de train
StopPoint:OCECar TER-80142927 pour les arrêts de bus
Je pense qu'il ne faut s'occuper que des ligne StopPoint:OCETrain TER-80142927 donc verifier la presence du mot "Train"

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=8050
