### ISSUE TITLE
False positive unmapped max speed limit in US

### ISSUE THREAD

**Issue by smichae** [osm-fr/osmose-backend#2408]
This may be my lack of understanding about this validation, but many Mapillary-detected speed limits in my region seem to always be detected as unmapped in my region, but an adjacent highway way does have the maxspeed.  (This may also be a problem primarily where survey:date is added on the way - I have seen a few where survey:date is not on a way, and Osmose isn't flagging an issue). I have closed this particular detection (and a few on this same stretch of road) at least once and it has reappeared.

https://osmose.openstreetmap.fr/en/issue/3c2a70b7-759e-8358-c399-f6390c4ccef8

cycleway:both=no
highway=tertiary
lanes=3
lanes:backward=2
lanes:forward=1
lit=yes
mapillary=312881763836487
maxspeed=40 mph
name=South Morris Avenue
shoulder=no
sidewalk=right
surface=concrete
survey:date=2021-06-12
tiger:cfcc=A41
tiger:county=McLean, IL
tiger:name_base=Morris
tiger:name_direction_prefix=S
tiger:name_type=Ave
tiger:reviewed=no
tiger:zip_left=61704
tiger:zip_left_1=61704
tiger:zip_right=61704
tiger:zip_right_1=61704
turn:lanes:backward=left|through;right

https://www.openstreetmap.org/edit#map=19/40.449326/-89.005384

![image](https://github.com/user-attachments/assets/3abac42d-d06e-4b74-be72-094be3158cf2)

**Comment by Famlam** [comment]
On a very inspection it seems Osmose is mixing up mph and km/h.
Just to be sure, the full state of Illinois uses mph units for all speed signs, correct?

**Comment by smichae** [comment]
Correct, the whole state does use mph - I believe all other U.S. states do as well.

**Comment by Famlam** [comment]
Solved :)
