### ISSUE TITLE
UK Wales and Scotland fail to update

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2411]
https://github.com/osm-fr/osmose-backend/blob/ce2f1eb00aa40557ddd3a9c977e7f62df07270cc/osmose_config.py#L711-L712

It seems we're trying to download from 
`https://download.geofabrik.de/europe/great-britain/*`
(with `*` = `scotland` or `wales`)

However, this URL is (poorly) redirected to 
`https://download.geofabrik.de/europe/united-kingdom/*`
so the thing we're trying to download is:
`/united-kingdom.htmlwales-latest.osm.pbf`
rather than
`/united-kingdom/wales-latest.osm.pbf`

Hence, these two countries failed to update for the past 3 weeks.
I guess just changing the download URLs to `/united-kingdom/` would be sufficient? Or is there more needed?

@jocelynj

**Comment by jocelynj** [comment]
Yes, updating the osmose_config.py file should be enough. Then, I might need to remove the cache on the backend server's side, but it should work without any cleaning.

**Comment by Famlam** [comment]
Perfect, PR ready :)
