### ISSUE TITLE
mix-up with charging station and charge points - analyser_merge_charging_station_FR

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osmose-backend#2414]
Hello,

I think that the analyser suggests me to modify the charging station with the data of one of the two charge points, and then wrongly asks to also modify the number of socket:type2.
https://osmose.openstreetmap.fr/fr/map/#loc=18/48.760477/2.330276&level=1%2C2%2C3&item=8410%2C8411%2C8412

At the same time, it suggests to add a new charging station with the data of the other charge point of the station.

To be clear, there is ONE cupboard in the street allowing to charge two cars, one on each side.

Thanks ;-)

**Comment by frodrigo** [comment]
Have you checked at the source date ?

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_charging_station_FR.py#L65-L68

**Comment by zorglubu** [comment]
Now I did ;-)  , it looks two years old.
Is it a big work to update with https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/ ?
This source seems to be dayly updated.

**Comment by frodrigo** [comment]
No, the file is updated https://github.com/Jungle-Bus/ref-EU-EVSE/commits/gh-pages/

**Comment by zorglubu** [comment]
Sorry, I didn't understand. The data looks OK, but the way it is read seems not good. There are two lines for this adress, with the same id_station_local.
The ref ref:EU:EVSE = FR*SIG*PSIGE17311 provided by osmose is the one (id_station_itinerance) of a charging point, not the station.
Should I rather contact @nlehuby  ?

**Comment by zorglubu** [comment]
I close this issue? I will discuss it on https://github.com/Jungle-Bus/ref-EU-EVSE
Thank you frodrigo
