### ISSUE TITLE
Radio support (Tour, mât et pylône) update

### ISSUE THREAD

**Issue by Nekzuris** [osm-fr/osmose-backend#2418]
I don't understand how to fix [this](https://osmose.openstreetmap.fr/en/map/#item=8392&zoom=17&lat=48.2954195&lon=7.3127419&issue_uuid=0bd0f8f7-777f-441e-da15-06f041f87c00&loc=17/48.29542/7.312742&level=1).
I already check the data it's correct, what should I add? it's already there.
And I don't want to remove the source or the ref.

**Comment by frodrigo** [comment]
That may be wrong, but the issue is here because of the suggested changes
```
~operator = Orange Services Fixes
+man_made = mast 
```

**Comment by Nekzuris** [comment]
Okay, I should probably add the operator but the [mast vs tower](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcommunications_tower#Distinguish_between_other_kinds_of_communications_towers) is very debatable.

**Comment by frodrigo** [comment]
You can always mark the Osmose issue as false positive if justified.
