### ISSUE TITLE
Ambiguous sport values

### ISSUE THREAD

**Issue by boothym** [osm-fr/osmose-backend#245]
There are a number of sport=* values which should be discouraged. For example: football - should be refined to soccer, american/australian/canadian_football etc. and hockey should either be ice_hockey or field_hockey.

It would be good if Osmose highlighted these as values to fix under 3040, thanks.

**Comment by frodrigo** [comment]
This values can be integrated on this page ?
https://wiki.openstreetmap.org/wiki/Deprecated_features
Osmose already raise issues for tags in this page (item 4010)

**Comment by frodrigo** [comment]
You can also add it to this page:
http://wiki.openstreetmap.org/index.php?title=User:FrViPofm/TagwatchCleaner

The content of the page it's automatically fetched by Osmose-QA.

**Comment by frodrigo** [comment]
Feel free to reopen if needed.
