### ISSUE TITLE
Question mark in street name

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-backend#246]
Hello,
We had this street which is obviously having a false name : http://www.openstreetmap.org/way/465260615
I thought Osmose would show an issue for this, but it doesn't seem so. The presence of certain punctuation signs in street names could create an issue in Osmose, as they are not common (maybe not allowed in France ?).
Regards.

**Comment by frodrigo** [comment]
There is analysis (lovely crafted with unicode and regex) :
http://osmose.openstreetmap.fr/en/errors/?item=5070
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_Script.py
But it allows common chars.

**Comment by frodrigo** [comment]
http://overpass-turbo.eu/s/thz
There is false positives

**Comment by PanierAvide** [comment]
Thanks for the reply. In fact for various names we can have common characters like question mark, but for street names it might be more restrictive. See http://overpass-turbo.eu/s/tjC where every result is something invalid.

**Comment by PanierAvide** [comment]
Thanks for the reply. In fact for various names we can have common characters like question mark, but for street names it might be more restrictive. See http://overpass-turbo.eu/s/tjC where every result is something invalid.

**Comment by frodrigo** [comment]
Results are coming:
http://osmose.openstreetmap.fr/fr/errors/?item=5070&class=50705

**Comment by PanierAvide** [comment]
Some of the results are POIs like night clubs or pubs. Could be false positives ?

**Comment by frodrigo** [comment]
There is some false positive but not so much, deosn't ?

**Comment by frodrigo** [comment]
Yes, maybe in France, but you already cleaned it?

**Comment by PanierAvide** [comment]
No I haven't cleaned them. I haven't any idea of the ratio of false positive overall, maybe it is not significant (saw like 2 or 3 over ~15 checked items).

**Comment by PanierAvide** [comment]
Maybe we can assume it's not significant for the while. Thanks for creating this new kind of items :+1:
