### ISSUE TITLE
Is there a cache in front of the API ?

### ISSUE THREAD

**Issue by GuillaumeAmat** [osm-fr/osmose-backend#249]
I'm going to implement Osmose based layers in MapContrib and it will increase the number of requests to the Osmose API. MC does not have a huge traffic but I was wondering if you've got a cache anyway. Just in case ;)

**Comment by frodrigo** [comment]
There is no cache on the API. But there is one on the vector tiles.
https://github.com/osm-fr/osmose-frontend/blob/master/apache-site#L42

**Comment by GuillaumeAmat** [comment]
Yes but the vector tiles are not customizable... Thank you for the info!

**Comment by frodrigo** [comment]
You can use exactly the same param as the api. And you style the tile on
client side.
