### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by GuillaumeAmat** [osm-fr/osmose-backend#250]
Hi guys, it's me, again ^^

Can you consider accept cross origin requests by adding the right headers to your API responses?

Osmose-request is working great from a Node.js application but the requests are blocked when it's used in a web app...

Thanks in advance

**Comment by jocelynj** [comment]
Strange, I thought we already added CORS support.

Can you remind me the header to add ?

**Comment by GuillaumeAmat** [comment]
It's: `Access-Control-Allow-Origin: *`

**Comment by jocelynj** [comment]
I've checked several URLs, and this header is already present. Do you have an URL where it is not present ?
```
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Methods: GET, POST, PUT, DELETE
```

**Comment by frodrigo** [comment]
This method are missing on 302 redirect

**Comment by GuillaumeAmat** [comment]
Yep, just saw that too.

**Comment by frodrigo** [comment]
Ok, it's fixed.

**Comment by GuillaumeAmat** [comment]
Thanks!
