### ISSUE TITLE
Terrain de sport non intégré : création d'un noeud sur le terrain existant

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#253]
https://osmose.openstreetmap.fr/fr/error/14878691773
source | 5833
item | 8170
class | 156
subclass | 1381113396
elems |  
lat lon | 45.0455900 6.3106900
Osmose propose de créer un nouveau objet 
leisure | pitch
sport | basketball
exactement à l'emplacement d'un polygone sport=basketball
Il faudrait plutôt proposer l'ajout des tag manquant sur le polygone existant.

**Comment by frodrigo** [comment]
It should be the item 8171 in place of 8170 for merge. But it does not exists, and there a good reason if so (I don't remember which one).
