### ISSUE TITLE
Post Office updated: name in capital letters

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#254]
le nom proposé par Osmose n'est pas mis en forme au niveau majuscule/minuscule et ceci tant lors de la création du tag name que lors d'une maj
exemple 1 : 
https://osmose.openstreetmap.fr/fr/error/14891087900
source | 1155
item | 8022
class | 4
subclass | 190176030
pas de tag name existant
tag name proposé : name | OYONNAX

exemple 2 : 
https://osmose.openstreetmap.fr/fr/error/14891089145
source | 1155
item | 8022
class | 4
subclass | 1178160257
tag existant : name | Beaufort
tag proposé : name | BEAUFORT

**Comment by frodrigo** [comment]
The lower case name can't be deduced from the upper case one.
Upper case are more false than lower case, so you can lower the name yourself. It's better than thinking is already correct.
