### ISSUE TITLE
False error messages #3060

### ISSUE THREAD

**Issue by Schroecker** [osm-fr/osmose-backend#255]
Hello,
There is a general problem with pipeline=marker tag **position**. A lot of false error-messages item=3060.
Position means, the exact (real) position of the pipeline, notated on a marker plate.  4 values are for left;right;distance;heading. Near values are possible.  You should check if left AND right > 0.
Thanks
Hugo Amann

**Comment by frodrigo** [comment]
Item 3060 just check for duplicate values in the list of values.
If I understand well values of position tag may (have to ?) be a list of numbers. So it allows duplicate and we have to backlist the tag position from this check.

https://taginfo.openstreetmap.org/keys/position#values
I read the wiki but it's really not enghout clear to me. Maybe some example are missing.
https://wiki.openstreetmap.org/wiki/Tag:pipeline%3Dmarker

**Comment by Schroecker** [comment]
Hello Frederic Rodrigo,

 

yes, I suggest to backlist the tag position from this check. I will mail to the proposer of the tag for better examples in the wiki.

 

Thanks

Hugo Amann

 

Gesendet: Sonntag, 31. Dezember 2017 um 11:13 Uhr
Von: "Frédéric Rodrigo" <notifications@github.com>
An: osm-fr/osmose-backend <osmose-backend@noreply.github.com>
Cc: Schroecker <hugo.amann@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [osm-fr/osmose-backend] False error messages #3060 (#255)


Item 3060 just check for duplicate values in the list of values.
If I understand well values of position tag may (have to ?) be a list of numbers. So it allows duplicate and we have to backlist the tag position from this check.

https://taginfo.openstreetmap.org/keys/position#values
I read the wiki but it's really not enghout clear to me. Maybe some example are missing.
https://wiki.openstreetmap.org/wiki/Tag:pipeline%3Dmarker

**Comment by frodrigo** [comment]
Should be fixed. Please reopen if not.
