### ISSUE TITLE
Hole between administrative boundaries of admin_level 8

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#256]
https://osmose.openstreetmap.fr/fr/error/14978396479
source | 86
item | 6060
class | 1
subclass | 1929694070
lat lon | 45.8110130 3.1910035

thanks for adding admin_level to the report, it help a lot. but I still didn't find what error was found.
this lat&lon is inside a boundary https://www.openstreetmap.org/relation/125611
the 5 way used as outer for this boundary is also used as outer the nearby boundary.
so where is the hole ? may the repport can have a better location and also the way id behind which there's a hole

**Comment by frodrigo** [comment]
The error is gone. Did you mark it as fixed or false-positive ?

**Comment by juhanjuku** [comment]
Same here, I cant' find where is error:
http://osmose.openstreetmap.fr/en/error/15007805649
http://osmose.openstreetmap.fr/en/error/15007805644
and more.

**Comment by Marc-marc-marc** [comment]
no I didn't mark it nor fixed nor fale-positive
but the id of the error seems to change after every run
https://osmose.openstreetmap.fr/fr/error/15040613761
https://osmose.openstreetmap.fr/fr/map/#zoom=15&lat=45.81306&lon=3.18693&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=6060&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
One year ago I think I break something
0ad416d5993c34ae94b60138752e484cbdfc8085
be4b7e55f05c3a00c36799f855c735b9db817295

![graph](https://user-images.githubusercontent.com/1785486/34499977-110d0d2e-f009-11e7-8b8a-55ab7eeaacac.png)
![graph-de](https://user-images.githubusercontent.com/1785486/34499978-1141f156-f009-11e7-9005-5e544760e024.png)
![graph-fr](https://user-images.githubusercontent.com/1785486/34499979-11699184-f009-11e7-9929-7bf5d47e9469.png)

**Comment by frodrigo** [comment]
Ok found the issue.

**Comment by frodrigo** [comment]
![image](https://user-images.githubusercontent.com/1785486/35118252-7fb7281a-fc91-11e7-95d9-f60a733bc2c2.png)
