### ISSUE TITLE
Historical monument update name=Maison

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#257]
source | 5150
item | 8012
class | 4
subclass | 1876798301

change name=Maison and name=Immeuble
into historic=building

Also in "Historical monument, integration suggestion"

**Comment by frodrigo** [comment]
Do you suggest to make a back list of words ?

**Comment by Marc-marc-marc** [comment]
a "not-a-name" list with correct equivalent tags in osm for those infos found in "Historical monument" source.
