### ISSUE TITLE
Djibouti local language

### ISSUE THREAD

**Issue by roptat** [osm-fr/osmose-backend#258]
Hi,

Djibouti's official languages are french and arabic (see https://en.wikipedia.org/wiki/Djibouti#Languages). Currently, osmose considers only french, leading to a lot of errors. On OSM, names are tagged either as name="&lt;fr&gt; &lt;ar&gt;" or name="&lt;fr&gt; / &lt;ar&gt;", with name:fr and name:ar in both cases.

**Comment by frodrigo** [comment]
Result of multilingual check are here. But I don't understand why monolingual results still here.
http://osmose.openstreetmap.fr/fr/errors/?country=djibouti&item=5060

**Comment by frodrigo** [comment]
The data are now clean.

**Comment by roptat** [comment]
well done, thanks :)
