### ISSUE TITLE
API : /error/ID/done response has no CORS headers

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-backend#259]
Hello,
I started using Osmose API for a project I'm working on. As it will allow to fix some Osmose issues, my app makes calls against API to let other users know that an issue was fixed. So I use the `GET /error/ID/done` call. However, the response doesn't have the CORS headers:
```
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Wed, 03 Jan 2018 13:51:09 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 374
Connection: keep-alive
Vary: Accept-Encoding
Content-Encoding: gzip
```

So it creates an exception client-side. Can you add them ? Thanks :-)

**Comment by frodrigo** [comment]
The right end point is:
```
/api/0.2/error/<err_id:int>/<status:re:(done|false)>
```

**Comment by PanierAvide** [comment]
The URL I'm using is `http://osmose.openstreetmap.fr/fr/api/0.2/error/ID/done`, but it does the same with `http://osmose.openstreetmap.fr/api/0.2/error/ID/done`.

**Comment by frodrigo** [comment]
Maybe linked to the use of `abort 200`
https://github.com/osm-fr/osmose-frontend/blob/master/error.py#L238
