### ISSUE TITLE
some datas seems out of sync

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#260]
l'impression qu'osmose est desyncro...
par exemple
https://osmose.openstreetmap.fr/fr/map/?item=8031&zoom=17&lat=50.2782808&lon=3.9853449#zoom=18&lat=50.278286&lon=3.985397&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=8031&level=1%2C2%2C3&tags=&fixable=
https://osmose.openstreetmap.fr/fr/error/11741445500
osmose croit que l'objet a un tag phone	03 27 53 03 53 alors que ce tag a été modifié il y a 3 mois
https://www.openstreetmap.org/relation/255112

autre exemple
https://osmose.openstreetmap.fr/fr/map/#source=1156&item=8030&class=1&item=8030&zoom=22&lat=48.6476804&lon=-2.0280323&level=3
https://osmose.openstreetmap.fr/fr/error/11741397270
alors que l'école a été intégrée dimanche 
https://www.openstreetmap.org/way/141689526/history

**Comment by Marc-marc-marc** [comment]
il y a visiblement un problème + import que quelques objets affectés
https://osmose.openstreetmap.fr/fr/errors/graph.png?source=668&item=2060&class=1
j'ai regardé un exemple donné sur talk-fr
https://www.openstreetmap.org/node/2033777425
https://www.openstreetmap.org/relation/2597631
l'associatedstreet et le noeud addr sont non modifié depuis 5 ans

**Comment by Marc-marc-marc** [comment]
Freed me signale sur irc que le pic d'erreur addr: est résorbé.
par contre les 2 erreurs du premier post sont toujours là.
a noter qu'ils ont tous les 2 un timestamp avril 2017

**Comment by Marc-marc-marc** [comment]
nouvel exemple signalé sur talk-fr : https://osmose.openstreetmap.fr/fr/error/14087114258
timestamp 2017-10-25 13:00:52 mais toujours affiché alors que la ref a été entre temps ajoutée sur la route

**Comment by jocelynj** [comment]
À ce que je vois pour la première erreur:
  - le backend envoie bien le nouveau numéro de téléphone, avec une class=2
  - le frontend a l'ancien numéro de téléphone, mais sur class=3.

@frodrigo: est-ce qu'il serait possible que des erreurs auraient changé de classe dans analyser_merge_school_FR.py, et qu'on n'ait pas supprimés les anciennes erreurs ?

Par ailleurs, je rajouterais bien une colonne timestamp dans la table markers pour savoir de quand ça date exactement...

**Comment by jocelynj** [comment]
Je confirme:
```
osmose_frontend=> select source,class,timestamp from dynpoi_class where source = 1156 order by timestamp;
 source | class |      timestamp      
--------+-------+---------------------
   1156 |    23 | 2017-04-30 01:32:58
   1156 |    24 | 2017-04-30 01:32:58
   1156 |    21 | 2017-04-30 01:32:58
   1156 |    22 | 2017-04-30 01:32:58
   1156 |    41 | 2017-04-30 01:33:08
   1156 |    43 | 2017-04-30 01:33:08
   1156 |    42 | 2017-04-30 01:33:08
   1156 |    44 | 2017-04-30 01:33:08
   1156 |     2 | 2017-04-30 01:33:18
   1156 |     4 | 2017-04-30 01:33:18
   1156 |     1 | 2017-04-30 01:33:18
   1156 |     3 | 2017-04-30 01:33:18
   1156 |    34 | 2017-04-30 01:49:25
   1156 |    33 | 2017-04-30 01:49:25
   1156 |    32 | 2017-04-30 01:49:25
   1156 |    31 | 2017-04-30 01:49:25
   1156 |    11 | 2018-01-10 08:59:02
   1156 |    14 | 2018-01-10 08:59:02
   1156 |    12 | 2018-01-10 08:59:02
   1156 |    13 | 2018-01-10 08:59:02
```

**Comment by frodrigo** [comment]
Ok, the data are up to date for schools.
Need to look at the next update.

**Comment by jocelynj** [comment]
En fait, seule la guadeloupe a des erreurs détectées:
```
osmose_frontend=> select country,analyser,source,class,timestamp,count from dynpoi_class join source on dynpoi_class.source = source.id where analyser='merge_school_FR' order by timestamp;
      country      |    analyser     | source | class |      timestamp      | count 
-------------------+-----------------+--------+-------+---------------------+-------
 france_guyane     | merge_school_FR |  26512 |    12 | 2018-01-16 21:44:02 |     0
 france_guyane     | merge_school_FR |  26512 |    13 | 2018-01-16 21:44:02 |     0
 france_guyane     | merge_school_FR |  26512 |    14 | 2018-01-16 21:44:02 |     0
 france_guyane     | merge_school_FR |  26512 |    11 | 2018-01-16 21:44:02 |     0
 france_martinique | merge_school_FR |  26523 |    12 | 2018-01-16 21:44:02 |     0
 france_martinique | merge_school_FR |  26523 |    14 | 2018-01-16 21:44:02 |     0
 france_martinique | merge_school_FR |  26523 |    13 | 2018-01-16 21:44:02 |     0
 france_martinique | merge_school_FR |  26523 |    11 | 2018-01-16 21:44:02 |     0
 france_reunion    | merge_school_FR |  26545 |    11 | 2018-01-17 21:43:02 |     0
 france_guadeloupe | merge_school_FR |  26501 |    12 | 2018-01-17 21:43:02 |   147
 france_guadeloupe | merge_school_FR |  26501 |    13 | 2018-01-17 21:43:02 |    14
 france_guadeloupe | merge_school_FR |  26501 |    14 | 2018-01-17 21:43:02 |    16
 france_guadeloupe | merge_school_FR |  26501 |    11 | 2018-01-17 21:43:02 |   366
 france_mayotte    | merge_school_FR |  26534 |    14 | 2018-01-17 21:43:02 |     0
 france_reunion    | merge_school_FR |  26545 |    14 | 2018-01-17 21:43:02 |     0
 france_reunion    | merge_school_FR |  26545 |    13 | 2018-01-17 21:43:02 |     0
 france_reunion    | merge_school_FR |  26545 |    12 | 2018-01-17 21:43:02 |     0
 france_mayotte    | merge_school_FR |  26534 |    11 | 2018-01-17 21:43:02 |     0
 france_mayotte    | merge_school_FR |  26534 |    12 | 2018-01-17 21:43:02 |     0
 france_mayotte    | merge_school_FR |  26534 |    13 | 2018-01-17 21:43:02 |     0
 france_local_db   | merge_school_FR |   1156 |    11 | 2018-01-18 02:49:02 |     0
 france_local_db   | merge_school_FR |   1156 |    12 | 2018-01-18 02:49:02 |     0
 france_local_db   | merge_school_FR |   1156 |    13 | 2018-01-18 02:49:02 |     0
 france_local_db   | merge_school_FR |   1156 |    14 | 2018-01-18 02:49:02 |     0
```

**Comment by frodrigo** [comment]
After the data clean, the problem is still here:
http://osmose.openstreetmap.fr/fr/errors/?item=8030&class=11

**Comment by frodrigo** [comment]
Done ! :champagne:
