### ISSUE TITLE
Error 3180 (no U-turn) whenever restriction type is give_way

### ISSUE THREAD

**Issue by Codain** [osm-fr/osmose-backend#261]
For instance: http://osmose.openstreetmap.fr/fr/error/15074781088
This is not a no U-turn restriction.

Whenever a give_way restiction is tagged Osmose detects a U-turn restriction. U-turn restictions are mapped using restriction=no_u_turn or restriction:*=no_u_turn (see https://wiki.openstreetmap.org/wiki/Relation:restriction#Tags).

Proposal: review conditions to match only restrictions with no_u_turn.

**Comment by frodrigo** [comment]
The link is no more valid and I don't understand what exactly you are talking about.
Can you copy the relation id or a link to the location and the item/class number of the issue please.

**Comment by Codain** [comment]
Other occurence: http://osmose.openstreetmap.fr/fr/error/15172292065 which concerns relation http://www.openstreetmap.org/relation/7493560

This relation is a Give-way relation for bicycles, not a U-turn relation.

This check shall apply only on u-turn relations.

**Comment by frodrigo** [comment]
Ok, made a fix.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=3180&class=31801&start_date=2018

**Comment by Codain** [comment]
Thanks everyone!
