### ISSUE TITLE
Question regarding "Conflict between tags: amenity, natural"

### ISSUE THREAD

**Issue by dazer** [osm-fr/osmose-backend#265]
What is the rationale to throw this level 1 error?.
As per the answer to my rendering question in https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dfountain, it seems like a fairly innocuous combination. Maybe it's just an exceptional case, but that combo, currently, looks like the most appropriate way to label the water area in ornamental fountains.

**Comment by frodrigo** [comment]
#307 #308

**Comment by frodrigo** [comment]
Stats of co-usage on France (it's my larger database)
```
 count | natural |    amenity    
-------+---------+---------------
   194 | water   | fountain    <------------
    37 | water   | lavoir
     8 | heath   | parking
     7 | water   | swimming_pool
```
Do you have idea of other couples ?

**Comment by frodrigo** [comment]
Done, but low impact.

**Comment by hungerburg** [comment]
Hmm, looks like the conflict gets flagged again; Seems overzealous to draw the basin and the fountain separately, they are one and the same. Fountain alone does not show the water surface in mapnik/anywhere?

**Comment by frodrigo** [comment]
Still here https://github.com/frodrigo/osmose-backend/blob/master/plugins/TagRemove_Incompatibles.py#L48
Maybe with other tags?
Do you have a link?

**Comment by hungerburg** [comment]
Hello frodrigo, out of my level 1 issues, there are four of those - https://osmose.openstreetmap.fr/en/byuser/Hungerburg?username=Hungerburg&item=4030 - perhaps, because the changes only were done recently. Look out! they are all natural=water, not landuse=water, never heard of that second option though.

**Comment by frodrigo** [comment]
Ok, was done on landuse=water move the rule to natural=water.
