### ISSUE TITLE
noexit test : wrong positive

### ISSUE THREAD

**Issue by Stefal** [osm-fr/osmose-backend#266]
Hi!
I see a lot of false positive on the missing noexit tag:
- highway=steps
- highway=track

I think these highway's type should be excluded from the analysis.

**Comment by VARVAR8** [comment]
and highway=path too (n5362898807, n5362898809, n5362898808, n5362898810 - issues as an error)

**Comment by frodrigo** [comment]
I added only 'steps' to the blacklist.
About 'track' and 'path' I'm not sure, most of issues are valid.

**Comment by Stefal** [comment]
I see a lot of paths/tracks that are ending on surface (meadow, farmland, forest...)

**Comment by frodrigo** [comment]
So, blacklisting steps has almost no effect:
http://osmose.openstreetmap.fr/fr/errors/?item=1270
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=1270&start_date=2018

**Comment by pezacz** [comment]
Another false positive here: http://osmose.openstreetmap.fr/en/error/16211473083
Ends on no access road, but assumes there is exit.

**Comment by frodrigo** [comment]
> Ends on no access road, but assumes there is exit.

https://wiki.openstreetmap.org/wiki/Key:noexit :
Use the noexit=yes tag at the end of a highway=* to indicate that there is **no possibility to travel further by any transport mode** along a formal path or route.

**Comment by frodrigo** [comment]
Please, reopen if required.
