### ISSUE TITLE
"bug" 30317 in Ukraine

### ISSUE THREAD

**Issue by VARVAR8** [osm-fr/osmose-backend#267]
http://osmose.openstreetmap.fr/en/errors/?source=14671&item=3031&class=30317
"Same wikipedia topic on other language" 28298

Ukraine it seems almost always uses both wikipedia=uk:*** and wikipedia:ru=***, yet for some reason, OSMOSE  suggests replacing existing wikipedia=uk:*** tag with wikipedia=ru:***, (while destroying the Ukrainian tag). Please fix this item. Tnks

**Comment by frodrigo** [comment]
Duplicate of #233

**Comment by frodrigo** [comment]
Add an exception for Ukraine.

**Comment by VARVAR8** [comment]
but the markers along with the editor window (wikipedia = ru: ******) on the map still remain.

**Comment by frodrigo** [comment]
Done:
http://osmose.openstreetmap.fr/fr/errors/?source=14671&item=3031&class=30317
http://osmose.openstreetmap.fr/fr/errors/graph.png?source=14671&item=3031&class=30317
