### ISSUE TITLE
Ukraine. Some value chars does not match the language charset. (COMBINING ACUTE ACCENT, 0x0301)

### ISSUE THREAD

**Issue by VARVAR8** [osm-fr/osmose-backend#268]
Some value chars does not match the language charset

Author. Please, read this: 
1. https://uk.wikipedia.org/wiki/%D0%9D%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D1%81#%D0%9F%D0%BE%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8F_%D0%BD%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D1%81%D1%83_%D0%B2_Unicode
2. https://uk.wikipedia.org/wiki/%D0%90%D0%BA%D1%83%D1%82
3. https://uk.wikipedia.org/wiki/%D0%9E%D0%BC%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8

COMBINING ACUTE ACCENT, 0x0301 for Ukrainian language - is normal

Examples OSMOSE "bugs"
"name:uk:word_stress"="Шкарпи́" unexpected char "́" (COMBINING ACUTE ACCENT, 0x0301) 
http://www.openstreetmap.org/browse/relation/6718235

"name:uk:word_stress"="Бу́рти" unexpected char "́" (COMBINING ACUTE ACCENT, 0x0301) 
https://www.openstreetmap.org/relation/7440899

**Comment by frodrigo** [comment]
For now "uk" is mapped only to unicode block "Cyrillic":
https://www.compart.com/en/unicode/block/U+0400

**Comment by frodrigo** [comment]
Done a fix.
Do you see other thing missing about the support of Ukrainian?

**Comment by VARVAR8** [comment]
Thank you guys for the help. But issues markers on the map still remain...

**Comment by frodrigo** [comment]
Please wait. It takes few days to apply.

**Comment by VARVAR8** [comment]
By the way, I forgot to message. Emphasis should **only** be the key value name:uk:word_stress (possibly name:ru:word_stress)

The accute has the right to be only at the value of the key name:uk:word_stress (possibly name:ru:word_stress). In other names ACCUTE SIGN does not apply.

Examples:
name:uk:word_stress"="Поно́ра"
name:uk:word_stress"="Бу́рти"

**Comment by frodrigo** [comment]
I will no restrict to word_stress and keep the code as is to check all "uk" name.

http://osmose.openstreetmap.fr/fr/errors/?source=14671&item=5070&class=50701
http://osmose.openstreetmap.fr/fr/errors/graph.png?source=14671&item=5070&class=50701

It's ok for you ?

**Comment by VARVAR8** [comment]
**name:uk:word_stress only** (according to OSM Ukraine community rules)
in other (name:***)'s the accute sign should not be. thanks

**Comment by frodrigo** [comment]
I will not do fine tuning because it is overcomplicated to do this only for
word stress.

Le 2 févr. 2018 09:21, "VARVAR8" <notifications@github.com> a écrit :

*name🇬🇧word_stress only* (according to OSM Ukraine community rules)
in other (name:***)'s the accute sign should not be. thanks

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/osm-fr/osmose-backend/issues/268#issuecomment-362517562>,
or mute the thread
