### ISSUE TITLE
Ukraine. The abbreviation "АГНКС" and "АЗС is not a mistake

### ISSUE THREAD

**Issue by VARVAR8** [osm-fr/osmose-backend#269]
http://osmose.openstreetmap.fr/en/errors/?source=14671&item=5010&class=803

Abbreviations on the roads of Ukraine (and the country of the former USSR) "АГНКС" (Compressed natural gas - CNG) and "АЗС (Petrol filling station)" are not mistakes.
proofs:
1.
https://uk.wikipedia.org/wiki/%D0%90%D0%93%D0%9D%D0%9A%D0%A1
2.
https://uk.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BD%D0%B0_%D1%81%D1%82%D0%B0%D0%BD%D1%86%D1%96%D1%8F
3. 
https://drive.google.com/open?id=1-LTGaL2brNRJMOX5Gn8xM9uJmYP2QMxZ
https://drive.google.com/open?id=1ER6zduO0_u8u9XMmBkpdnTlnakzH8M52
4.
http://overpass-turbo.eu/s/vzB

**Comment by frodrigo** [comment]
It's justified to have the fuel type in the name? Shouldn't be only tagged with fuel:xx=yes ?
Also, the number of issues like this are low.

The rule check for at least 5 upper letters, without exception.

**Comment by frodrigo** [comment]
Please reopen if needed.
