### ISSUE TITLE
Item 1270. Almost junction, join or use noexit tag. Help understand what the problem here

### ISSUE THREAD

**Issue by VARVAR8** [osm-fr/osmose-backend#270]
http://osmose.openstreetmap.fr/uk/byuser/VARVAR8?username=VARVAR8&item=1270
All nodes and ways are connected. What is the problem?

**Comment by frodrigo** [comment]
https://wiki.openstreetmap.org/wiki/Key:noexit

**Comment by VARVAR8** [comment]
Thanks
