### ISSUE TITLE
lanes vs. lanes:bus conflict

### ISSUE THREAD

**Issue by fgouget** [osm-fr/osmose-backend#275]
Osmose is reporting an error about lanes on the [avenue du Prado](https://www.openstreetmap.org/way/430174374) in Marseille:
http://osmose.openstreetmap.fr/en/error/16009755790

> on two way, (lanes=8) != (lanes:forward=3) + (lanes:backward=3) + (lanes:both_ways=None) - (non fullwidth=0) - (non fullwidth forward=0) - (non fullwidth backward=0) - (non fullwidth both_ways=0)

The problem is lanes=8 which I think is incorrect. It seems like it comes from the following tag combination:
- lanes = 6
- lanes:bus = 2

However the [wiki](https://wiki.openstreetmap.org/wiki/Key:lanes) says:
> The lanes=* key should be used to specify the total number of marked lanes of a road.

So I don't think adding lanes and lanes:bus is correct.

The wiki also says yo can specify how many of the total number of lanes are for specific types of vehicles with lanes:bus, etc.
> Additionally to the total number of lanes, consider to tag the number of lanes for PSV with lanes:psv=*, lanes:bus=* and lanes:taxi=*.

The [French version](https://wiki.openstreetmap.org/wiki/FR:Key:lanes) is quite specific about this interpretation:
> En complément du nombre total de voies, on peut tagger le nombre de voies spécifiques aux transports en commun avec lanes:psv=*, lanes:bus=* et lanes:taxi=*.

So I think Osmose is incorrectly adding lanes and lanes:bus when computing the total number of lanes.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Lanes.py#L207

**Comment by fgouget** [comment]
I think the problem is more in the loop on line 140:

```
140    for tag in tags_lanes:
            if tag == 'lanes' or tag.startswith('lanes:'):    # --> matches lanes and lanes:bus
                try:
                    n = int(tags_lanes[tag])    # --> set to 6 and then 2
                    parts = tag.split(':')
                    direction = ''
                    if len(parts) > 1:
                        if parts[-1] in ['forward', 'backward', 'both_ways']:    # --> never matches
                            direction = ':'+parts[-1]
                    if number['lanes'].get(direction) == None:
                        number['lanes'][direction] = 0
151                 number['lanes'][direction] += n    # --> so here direction == '' in both cases
            # and here number['lanes'][''] = 0+6+2
```

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=3160&class=31604
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=3160&class=31604&start_date=2018
