### ISSUE TITLE
Item deprecated vs low precision tag

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#276]
Bonjour à tous,

À la suite de l'intégration (à la demande) du validateur de JOSM dans osmose, remontent de nombreux signalements précédemment passés sous silence par osmose (jusque là, tout va vaguement bien). 

Mais, soit la remontée suivante : http://osmose.openstreetmap.fr/fr/byuser/?username=deuzeffe&item=9002 L'item est dit « deprecated » alors que la vrai raison est une valeur de tag imprécise. (ce qui donne « {0.key}={0.value} est imprécis. Veuillez remplacer « {0.value} » par une valeur spécifique.» dans la première ligne de l'infobulle, c'est meunion ^^)

Est-ce que c'est possible de changer « deprecated » pour un terme plus... précis, dans ce cas (précis, donc...) ?

Il est a noter que la valeur du tag est proposée dans ID (oui, je sais...) et sur le wiki. Même s'il faut différencier améliorations et corrections d'erreur (merci Marc-marc), ça vaut le coup (ou pas) ?

(si mon message n'est pas dans la bonne case, bin... bougez-le là où il faut, dixit Stereo et Marc-marc sur IRC)

++

**Comment by frodrigo** [comment]
All this come from JOSM. "Deprecated" is the main thematic categorie, it include may other things.

You can suggested to JOSM project to split away this kind of issue from the deprecated file to a new one

https://josm.openstreetmap.de/newticket
https://josm.openstreetmap.de/browser/josm/trunk/data/validator/deprecated.mapcss
https://josm.openstreetmap.de/wiki/Help/Dialog/Validator
https://josm.openstreetmap.de/wiki/Help/Validator/MapCSSTagChecker

**Comment by frodrigo** [comment]
FYI @Klumbumbus

**Comment by Klumbumbus** [comment]
I don't think it really makes sense and is worth the trouble to split the JOSM file. Maybe rename it to deprecated_or_imprecise in JOSM or osmose?

@don-vip ?

**Comment by don-vip** [comment]
If we split the file it's harder to keep track of changes. But it has benefits for end-users: they can for example enable "deprecated" rules, and disable "imprecise" ones. So I'd say for this one case, this is worth the effort. I guess we can find a lot of "imprecise" rules.

**Comment by Klumbumbus** [comment]
The new file should be auto enabled also at existing JOSM installations. (I think you did this once with territories.mapcss too). Otherwise a lot of users would loose rules and they would't notice.

**Comment by don-vip** [comment]
of course :)
