### ISSUE TITLE
ignore error 3050 for ref:NîmesMétropole

### ISSUE THREAD

**Issue by geostonemarten** [osm-fr/osmose-backend#277]
Hi, 

Can you ignore error for **ref:NîmesMétropole** key? This key is created by Nîmes Métopole to put in sync data as same RFF or LaPoste

**Comment by frodrigo** [comment]
It's reported because it's not advisable for a key in OSM
I did not found the right page in the wiki, but I found this at least: https://wiki.openstreetmap.org/wiki/Any_tags_you_like#Syntactic_conventions_for_new_tags

Advisable chars list is "-_:a-zA-Z_0-9<>°"

**Comment by frodrigo** [comment]
Please reopen if you are disagree.

**Comment by frodrigo** [comment]
Actually we do it.
