### ISSUE TITLE
does make sense ? - missing tag  lanes:forward without lanes:backward

### ISSUE THREAD

**Issue by pezacz** [osm-fr/osmose-backend#279]
http://osmose.openstreetmap.fr/en/error/16315875970

Unless there is third choice, either lanes:forward or lanes:backward should suffice, because if not specified, lanes:backward equals (lanes - lanes:forward).
Also Wiki doesn't mention necessity of tagging counts for BOTH directions:

https://wiki.openstreetmap.org/wiki/Lanes

-either wiki should get updated, JOSM validator as well
-or this check should be relaxed

**Comment by frodrigo** [comment]
The link you give is no more valide. As is written in issue template, please, give us more details like item  number or permalink to the map.

**Comment by frodrigo** [comment]
Please reopen with a sample if required.
