### ISSUE TITLE
Broken highway level continuity

### ISSUE THREAD

**Issue by pezacz** [osm-fr/osmose-backend#280]
http://osmose.openstreetmap.fr/en/error/16316023192

It is standard situation - highway goes to highway level=1, bridge=yes and continues as level=0

That should be raised when bridge tag is missing or more than 1 level difference IMHO

**Comment by frodrigo** [comment]
The case you point is a non sens. There is no reason to change the level for a small part that link main way to the city.

**Comment by frodrigo** [comment]
Please reopen if not agree with my point of view.
