### ISSUE TITLE
False positive: missing tag, highway without a reference

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#281]
False positive: missing tag, highway without a reference.
 
Undocumented issue (https://wiki.openstreetmap.org/wiki/Osmose/issues#9004).
(No class number available)

Applies to: highway = secondary/tertiary

Issue: most highway = secondary/tertiary do not have a Reference set.
At least not in the Netherlands. Not "on the ground".
Only Reference: name=*.

**Comment by frodrigo** [comment]
This issue come from the JOSM validator MapCSS file.

https://josm.openstreetmap.de/browser/josm/trunk/data/validator/highway.mapcss#L55

You can report it to the JOSM project :
https://josm.openstreetmap.de/newticket

https://josm.openstreetmap.de/wiki/Help/Dialog/Validator
https://josm.openstreetmap.de/wiki/Help/Validator/MapCSSTagChecker

Note, the JOSM MapCSS validator report this issue as `throwOther`, but this level of issues has been discontinued in Osmose report. This will disappear from Osmose, but stay in JOSM validation results.

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
The "Other" level in JOSM is intended for "hints" for possible incomplete or wrong tagging. This can include false positives. I don't see a reason to change this specific rule in JOSM atm and as these rules are no longer pushed to osmose I think we can close this issue.
