### ISSUE TITLE
Old error, fixed, still shown

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#282]
Hello,

This error http://osmose.openstreetmap.fr/fr/error/14087177376 was fixed more than a week ago (https://www.openstreetmap.org/way/391437254) It's still "pinned" on the map (even if the ref of the road is explicit...)

HTH

**Comment by frodrigo** [comment]
source | 14708
item | 7170
class | 2
subclass | 1
title ref=* or possibly missing highway in the area
subtitle D 110 (id_route500: 1687)

**Comment by frodrigo** [comment]
@cquest your data base is no more update ?

**Comment by deuzeffe** [comment]
Another one (http://osmose.openstreetmap.fr/fr/error/16450062953 // https://www.openstreetmap.org/way/40205255):

source | 27266
item | 1270
class | 1
subclass | 0
title	Jonction imparfaite, joindre le nœud ou utiliser l’attribut “noexit” si sans issue

**Comment by frodrigo** [comment]
Item 1270 and 7170 does not provide from the same source

**Comment by frodrigo** [comment]
Appear fixed. Reopen if required.
