### ISSUE TITLE
tracktype without highway

### ISSUE THREAD

**Issue by osmtools** [osm-fr/osmose-backend#283]
https://www.openstreetmap.org/way/450070854 is tagged as

> disused:highway = track
incline = down
smoothness = impassable
surface = grass
tracktype = grade4

I think this and others** checks should note the lifecycle prefixes, right?
Or should i use "false positive" in this case?

**
`smoothness without highway or amenity={2.value}`
`incline without highway, railway or aeroway={3.value}`

and hmm, isn't there any `surface without highway...` check?

**Comment by frodrigo** [comment]
The link to issue on osmose: http://osmose.openstreetmap.fr/en/error/16525945661

This issue come from the JOSM validator MapCSS file.

https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss#L72

You can report it to the JOSM project :
https://josm.openstreetmap.de/newticket

https://josm.openstreetmap.de/wiki/Help/Dialog/Validator
https://josm.openstreetmap.de/wiki/Help/Validator/MapCSSTagChecker

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
If there exists really no usable path/way/street at all anymore then the tags should be removed or the way deleted. As long as there is still any sort of path/way/street it should be tagged with highway=* (and possible access=*, smoothness=*, surface=*, informal=yes,...)

Judging from the last changeset comment "...sehr stark zugewachsen, auch für Fußgänger fast nicht passierbar. " it should rather be tagged with highway=path and additional tags.

**Comment by Schroecker** [comment]
It seems in general, that the life-cycle prefix will not be recognized. There are similar issues for example with "abandoned". To use "false positiv" is not the right way.

**Comment by osmtools** [comment]
or "area:highway", see https://www.openstreetmap.org/way/535735230

> If there exists really no usable path/way/street at all anymore then the tags should be removed or the way deleted. 

@Klumbumbus surely, but isn't it so intended to use lifecycle prefixes (on the main tag) AND keep the other tags?

PS: and yes, i think i will downgrade this mentioned way to `path` and set it to `smoothness=impassable`

**Comment by Klumbumbus** [comment]
>It seems in general, that the life-cycle prefix will not be recognized.

Yes, lifecycle prefixes are not yet handled in the JOSM validator rules at all. I just created a JOSM ticket to discuss how we could handle prefixes in mapcss in the future, https://josm.openstreetmap.de/ticket/16093.

>isn't it so intended to use lifecycle prefixes (on the main tag) AND keep the other tags?

https://wiki.openstreetmap.org/wiki/Lifecycle_prefix says "Add a namespace prefix (for example "disused:") to **all keys which are no longer relevant** to the current state of an object." As disused:highway doesn't really make sense to me, let's use the following example: razed:highway=track, then other tags like tracktype, smoothness, surface,... should also get the razed:prefix. For other values like incline it is debatable if it should get the prefix too in case of "razed:". In case of "proposed:" or "constrution:" it seems valid to not use a prefix on incline.

>or "area:highway", see https://www.openstreetmap.org/way/535735230

I'll check if it makes sense to add "area:highway" to some rules.

**Comment by frodrigo** [comment]
To further talk go to https://josm.openstreetmap.de/ticket/16093

**Comment by Klumbumbus** [comment]
>or "area:highway", see https://www.openstreetmap.org/way/535735230

I thought again about this and I think it is not good to double infomation like surface or smoothness from the highway way to the highway area:highway. This is redundant information which will differ quickly. This is also written at https://wiki.openstreetmap.org/wiki/Proposed_features/Street_area:

>"It seems to be helpful to collect information about of the type of road, in particular for area:highway=footway/cycleway because this information can be easily used for different rendering of the map.
What is definitely not necessarily? Street name=*, number of lanes, surface, smoothness, maxspeed, address names etc. These attributes are a part of highways and can be extracted. "

So the warning in this case is correct in my eyes.

**Comment by Klumbumbus** [comment]
>https://wiki.openstreetmap.org/wiki/Proposed_features/area:highway#Additional_Keys

Thats another proposal. I think the most recent proposal for area:highway tagging is https://wiki.openstreetmap.org/wiki/Proposed_features/Street_area

**Comment by osmtools** [comment]
In deed, both started in 2011 but StreetArea updated 2015. So i will remove the additonal tags.
Thanks klumbumbus to figure this out.
