### ISSUE TITLE
False Error Message item 9001

### ISSUE THREAD

**Issue by Schroecker** [osm-fr/osmose-backend#284]
Hello,
False Error Message
item 9001 class 9001001
missing tag    information without tourism=viewpoint
but the tag exist!
http://osmose.openstreetmap.fr/de/error/16543993988
username | Schröcker

node 3086752672 rawedit josm edit
information = map
map_type = toposcope
source = survey
tourism = viewpoint

**Comment by frodrigo** [comment]
This issue come from the JOSM validator MapCSS file.

https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss#L94
*[information                  ][tourism!=information]

You can report it to the JOSM project :
https://josm.openstreetmap.de/newticket

https://josm.openstreetmap.de/wiki/Help/Dialog/Validator
https://josm.openstreetmap.de/wiki/Help/Validator/MapCSSTagChecker

But I think you should better map the the map, the viewpoint, the survey point and the toposcope distinctly.

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
The osmose error is not available anymore. However if the message was really "missing tag information without tourism=viewpoint" then there is something wrong with the osmose mapcss interpreter. If it was "missing tag information without tourism=information" then it's not a false positive. information=* is a refinement of tourism=information, which is missing at that node. (see https://wiki.openstreetmap.org/wiki/Key:information)

There should be two nodes. One with tourism=viewpoint and one with tourism=information, information=map, map_type=toposcope.

**Comment by frodrigo** [comment]
The id changed but still available here:
http://osmose.openstreetmap.fr/en/error/16657526766
http://osmose.openstreetmap.fr/en/map/#zoom=19&lat=49.33237&lon=8.09507

missing tag
**information without tourism=viewpoint**
node 3086752672 rawedit josm edit
information = map
map_type = toposcope
source = survey
tourism = viewpoint 

You're right, there a problem with the message.
