### ISSUE TITLE
OpenData : màj base RES

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#285]
'soir,

La base Recensement des Équipements sportifs la plus récente est dispo. ici : https://www.data.gouv.fr/s/resources/recensement-des-equipements-sportifs-espaces-et-sites-de-pratiques/20180112-114703/20180110_RES_FichesEquipements.zip

En remplacement de celle de 2015.
HTH

**Comment by frodrigo** [comment]
It's the same already used, the data from source are automatically update (but mot the source tag content).
