### ISSUE TITLE
move not-boundary type=multipolygon from 6010 into 1170

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#286]
source | 3
item | 6010
class | 2
elems | node4006800169_relation1485391
lat lon | 47.2749358 -70.6098853
title | enOpen relation type=multipolygon
natural | wood
https://osmose.openstreetmap.fr/map/?item=6010&zoom=17&lat=47.2749358&lon=-70.6098853

it should be better to split
Relation type=multipolygon that aren't a boundary in 1170
keep only Relation type=multipolygon the old schema of boundary in 6010

**Comment by frodrigo** [comment]
6010/3 → 1170/2

**Comment by frodrigo** [comment]
1170/2 → 1170/5
