### ISSUE TITLE
Validate phone numbers

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#290]
This is an enhancement request to validate phone numbers. 

tags: phone, fax, contact:phone, contact:fax

regex should be something like ^+[0-9 -]*$

- begins with +
- remainder is only characters 0 to 9, space, hyphen

https://wiki.openstreetmap.org/wiki/Key:phone

possibly you might want to allow a single "x" for extension (not documented on the wiki, but used in Canada)... eg +1-800-555-0000x1234

**Comment by matthewdarwin** [comment]
I would think that plugin could be modified for Canada, USA and several other countries that use the North American calling plan.  https://en.wikipedia.org/wiki/North_American_Numbering_Plan 

The topic of the correct phone number for Canada was discussed on talk-ca. https://lists.openstreetmap.org/pipermail/talk-ca/2018-February/008350.html   I'm not sure if other countries in North America would align to that discussion or not.  Could start with Canada

I guess you would like someone in Canada to write a new plug-in based on the FR one?  I will ask at the next OSM meetup next week if anyone is interested in working on this.

**Comment by matthewdarwin** [comment]
Is there any development guide on how to build/test the new plugin?  

I assume I should:
* copy Phone_fr.py to Phone_ca.py
* change only_for = ["FR", "NC"] to "CA"
* modify the regex to whatever i need (add more checks if necessary)
* I should pick new error codes instead of 3092*?  Which numbers?
* The test section should show how to fix a bad number to a good number, I assume.

Any hints on how to set up a development environment to make it easy to test?  (ie disable all the other tests so just this one runs, don't clear database so re-use, or other things). 

If there is developer guide somewhere, please point me to it... I didn't find it.

Currently I am just running the tests in kind of production mode using docker image... so probably need to do something different for development.

**Comment by frodrigo** [comment]
>    copy Phone_fr.py to Phone_ca.py
Yes
>    change only_for = ["FR", "NC"] to "CA"
Yes
>    modify the regex to whatever i need (add more checks if necessary)
Yes, run test with `nosetest Phone_fr.py`
>    I should pick new error codes instead of 3092*? Which numbers?
Yes, pick 309211/309212/309213
    The test section should show how to fix a bad number to a good number, I assume.
> Yes

Maybe you need to remove the "National short code" for CA.

Run only the sax analyser to speed up your test on the full extract.
```
python ./osmose_run.py --no-clean --country=italy_trentino_alto_adige --analyser=sax
```

**Comment by matthewdarwin** [comment]
Thanks for the hints.  I will update after I have some progress...

**Comment by frodrigo** [comment]
Any news, need help ?

**Comment by matthewdarwin** [comment]
My docker image is running fine for running "production", but I need to get a development environment setup... sorry, been a bit busy on other things.

**Comment by mojoaxel** [comment]
Due to the [wiki Key:phone](https://wiki.openstreetmap.org/wiki/Key:phone) numbers should be in the [ITU-T E.123](http://en.wikipedia.org/wiki/E.123) / [DIN 5008](http://en.wikipedia.org/wiki/de:DIN_5008) format.
If e.g. CA uses a different phone format this should be discussed e.g. in the [discussion page of the wiki](https://wiki.openstreetmap.org/wiki/Talk:Key:phone) and mentioned on the wiki page.

_I just want to encourage somebody with python skills to introduce this globaly_ :+1:

**Comment by frodrigo** [comment]
I add the Canada to the check. It does check to add prefix and make format validation.

**Comment by fgouget** [comment]
The following https://overpass-turbo.eu/ query provides interesting results:

{{geocodeArea:CA}}->.searchArea;
(
  node["phone"~"[^0-9+ ]"](area.searchArea);
);
out;


* Some phone fields contain a semi-colon separated list of phone numbers (allowed according to the Wiki).
* Some contain a '#' or '/' separated list of phone numbers!
* I even saw one using '-'-separated phone number list which is quite ambiguous since dashes are sometimes used instead of spaces.
* Some phone numbers contain an extraneous "(0)" (clearly wrong).
* Some use dots instead of spaces to separate the different parts. But the Wiki recommends following the ITU-T E.123 which mandates using spaces.
* In Ireland using dashes instead of spaces seems quite popular. And it's semi-documented on the Wiki (it's in parentheses without an explanation of why)
* I have seen one phone number with the 'x'.
* In the US and Canada some use letters as mnemonics for the corresponding numbers. For instance USA for 872. The Wiki makes no mention of this which means it probably should not be allowed.

So the Phone plugin could be extended to detect these additional issues and suggest fixes. Except for '(0)' they could probably work worldwide too.

Also if a node has errors in "phone" and "fax" it will create two issues instead of one offering to fix both.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=3092

**Comment by frodrigo** [comment]
Also check for beginning with "00" in place of "+".

**Comment by frodrigo** [comment]
@matthewdarwin partially rewroted with country generic support, and enabled on Canada, France and New Caledonia

http://osmose.openstreetmap.fr/en/errors/?item=3092&country=canada*

Open for comment.

**Comment by frodrigo** [comment]
Supported parameters:
- phone_code
- phone_len
- phone_len_short
- phone_format
- phone_international

- FR: https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L241
- NC: https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L487
- CA: https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L776

**Comment by mojoaxel** [comment]
> FR: https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L241

Can please somebody add "DE" as well. The format is defined in [DIN 5008](https://de.wikipedia.org/wiki/DIN_5008) and the regex should be something like this: 
```
^(+[0-9]+ |0)[1-9]{2,} [0-9]{2,}(-[0-9]{1,}|)$
```
Thanks!
_(Python is not my thing...)_

**Comment by matthewdarwin** [comment]
Great, thanks for looking at this. I think the Canada regex should be tighter.  Either all space or all hyphen... not a mismatch. So I think that is:
```
^([+]%s-[0-9]{3}-[0-9]{3}-[0-9]{4}|[+]%s [0-9]{3} [0-9]{3} [0-9]{4})$
```
Optional extension would be nice too, even though not defined in the osm wiki
```
^([+]%s-[0-9]{3}-[0-9]{3}-[0-9]{4}|[+]%s [0-9]{3} [0-9]{3} [0-9]{4})(x[0-9]+)?$
```

Auto-correct should suggest to fix with all hypens, since that is the majority of phone numbers in Canada.

If you want to add specific validation to phone:tollfree then the phone number must start with:
+1-800, +1-844, +1-855, +1-866, +1-877 +1-888 (https://en.wikipedia.org/wiki/North_American_Numbering_Plan)

original code:
```
canada_province = gen_country('north-america', 'canada', language='en', phone_code="1", phone_len=10, phone_format=r"^[+]%s[- ][0-9]{3}[- ][0-9]{3}[- ][0-9]{4}$", exclude=[
    'osmosis_waterway',
])
```

Here is the phone number formats (with counts) from about 2 months ago for all of Canada:

```
  35117 phone"+#-###-###-####
   1673 fax"+#-###-###-####
   1151 contact:phone"+#-###-###-####
    874 phone"+# ### ### ####
    275 phone"+# ###-###-####
    159 contact:fax"+#-###-###-####
    117 phone:tollfree"+#-###-###-####
    111 phone"+# ### ###-####
    106 phone"###-####
     91 phone"(###) ###-####
     83 phone"#-###-###-####
     73 phone"###-###-####
     67 phone"### ###-####
     51 phone"+#-###-###-####;+#-###-###-####
     51 phone"+# (###) ###-####
     45 phone"##########
     30 phone"+#-###-###-####x###
     25 phone"+#-###-###-AAAA
     24 phone"+#-###-###-####x####
     21 phone"+###########
     16 phone"+####-###-####
     12 phone"###########
     11 phone"+# (###)###-####
      9 phone"+#-###-###-####x#
      9 phone"(###)###-####
      8 contact:phone:tollfree"+#-###-###-####
      6 fax"+# ###-###-####
      5 phone"+#-###-###-####;+#-###-###-#### (...)
      5 fax"+# ### ###-####
      5 fax"###-###-####
      4 phone"+#-###-###-#### (...)
      4 phone"+#-### ###-####
      4 contact:phone"+# ###-###-####
      3 phone"+#-###-###-####x##
      3 phone"+#-###-###-#AAA
      3 phone"+#### ###-####
      3 phone"+# ### #######
      3 phone"(###)-###-####
      3 phone"###.###.####
      3 phone"### ### ####
      3 phone"# (###) ###-####
      2 source:phone"survey
      2 service:fax"yes
      2 phone"+#-###-##-AAAAA
      2 phone"+#-###-###-###
      2 phone"+#  (###) ###-####
      2 phone"(###) ### ####
      2 fax"+# (###) ###-####
      2 fax"+# ### ### ####
      2 fax"(###)-###-####
      2 contact:phone"+#-###-###-####x#####
      2 contact:phone"(###) ###-####
      1 telephone"+#-###-###-####,+#-###-###-####
      1 phone"+#-###-###-####x# (...);+#-###-###-####x# (...)
      1 phone"+#-###-###-####x#####
      1 phone"+#-### ###-#### x ###
      1 phone:tollfree"+#-###-###-####x# (...)
      1 phone:tollfree"+#-###-###-AAAA
      1 phone:tollfree"+#-###-###-#### (...)
      1 phone"(###) ###-#### poste ####
      1 phone:office"+#-###-###-####
      1 phone"+#-###-###-####; #-###-###-#### &###;headoffice&###;
      1 phone"+#-###-AAAAAAA
      1 phone"+#-###-AAA-AAAA
      1 phone"+#-###-AAAAA-##
      1 phone"+#-###-AA-AA-###
      1 phone"+#-###-###-#### (...);+#-###-###-AAAA (...)
      1 phone"### ###-#### A#
      1 phone"+`-#`#-###-####
      1 phone"+#-###=###=####
      1 phone"+#-###-###-####;+#-###-###-####;+#-###-###-####
      1 phone"+#-###-###-####;+#-###-###-####(...)
      1 phone"+#-###-###-####;+#-###-###-#### (...);+#-###-###-#### (...);+#-###-###-#### (...)
      1 phone"+#-###-###-#####
      1 phone"+#-###-###-#### (...);+#-###-###-#### (...)
      1 phone"+#-###-###-####
      1 phone"+#-###-####
      1 phone"+#-### ### ####
      1 phone"+#(###)###-####
      1 phone"+# -###-###-####
      1 phone"+# (###) ###-#### (###)
      1 phone"+# ###-###-###
      1 phone"+# ##########
      1 phone"+# ### ####
      1 phone"+# ### ### ###
      1 phone"+# # ### ###-####
      1 phone"+#  ### ###-####
      1 phone"+ #-###-###-####
      1 phone"+ # ###-###-####
      1 phone"#-###-###-####
      1 phone"#+-###-###-####
      1 phone"#+###-###-####
      1 phone"###- ###- ####
      1 phone"###) ###-####
      1 phone"############  35117 phone"+#-###-###-####
   1673 fax"+#-###-###-####
   1151 contact:phone"+#-###-###-####
    874 phone"+# ### ### ####
    275 phone"+# ###-###-####
    159 contact:fax"+#-###-###-####
    117 phone:tollfree"+#-###-###-####
    111 phone"+# ### ###-####
    106 phone"###-####
     91 phone"(###) ###-####
     83 phone"#-###-###-####
     73 phone"###-###-####
     67 phone"### ###-####
     51 phone"+#-###-###-####;+#-###-###-####
     51 phone"+# (###) ###-####
     45 phone"##########
     30 phone"+#-###-###-####x###
     25 phone"+#-###-###-AAAA
     24 phone"+#-###-###-####x####
     21 phone"+###########
     16 phone"+####-###-####
     12 phone"###########
     11 phone"+# (###)###-####
      9 phone"+#-###-###-####x#
      9 phone"(###)###-####
      8 contact:phone:tollfree"+#-###-###-####
      6 fax"+# ###-###-####
      5 phone"+#-###-###-####;+#-###-###-#### (...)
      5 fax"+# ### ###-####
      5 fax"###-###-####
      4 phone"+#-###-###-#### (...)
      4 phone"+#-### ###-####
      4 contact:phone"+# ###-###-####
      3 phone"+#-###-###-####x##
      3 phone"+#-###-###-#AAA
      3 phone"+#### ###-####
      3 phone"+# ### #######
      3 phone"(###)-###-####
      3 phone"###.###.####
      3 phone"### ### ####
      3 phone"# (###) ###-####
      2 source:phone"survey
      2 service:fax"yes
      2 phone"+#-###-##-AAAAA
      2 phone"+#-###-###-###
      2 phone"+#  (###) ###-####
      2 phone"(###) ### ####
      2 fax"+# (###) ###-####
      2 fax"+# ### ### ####
      2 fax"(###)-###-####
      2 contact:phone"+#-###-###-####x#####
      2 contact:phone"(###) ###-####
      1 telephone"+#-###-###-####,+#-###-###-####
      1 phone"+#-###-###-####x# (...);+#-###-###-####x# (...)
      1 phone"+#-###-###-####x#####
      1 phone"+#-### ###-#### x ###
      1 phone:tollfree"+#-###-###-####x# (...)
      1 phone:tollfree"+#-###-###-AAAA
      1 phone:tollfree"+#-###-###-#### (...)
      1 phone"(###) ###-#### poste ####
      1 phone:office"+#-###-###-####
      1 phone"+#-###-###-####; #-###-###-#### &###;headoffice&###;
      1 phone"+#-###-AAAAAAA
      1 phone"+#-###-AAA-AAAA
      1 phone"+#-###-AAAAA-##
      1 phone"+#-###-AA-AA-###
      1 phone"+#-###-###-#### (...);+#-###-###-AAAA (...)
      1 phone"### ###-#### A#
      1 phone"+`-#`#-###-####
      1 phone"+#-###=###=####
      1 phone"+#-###-###-####;+#-###-###-####;+#-###-###-####
      1 phone"+#-###-###-####;+#-###-###-####(...)
      1 phone"+#-###-###-####;+#-###-###-#### (...);+#-###-###-#### (...);+#-###-###-#### (...)
      1 phone"+#-###-###-#####
      1 phone"+#-###-###-#### (...);+#-###-###-#### (...)
      1 phone"+#-###-###-####
      1 phone"+#-###-####
      1 phone"+#-### ### ####
      1 phone"+#(###)###-####
      1 phone"+# -###-###-####
      1 phone"+# (###) ###-#### (###)
      1 phone"+# ###-###-###
      1 phone"+# ##########
      1 phone"+# ### ####
      1 phone"+# ### ### ###
      1 phone"+# # ### ###-####
      1 phone"+#  ### ###-####
      1 phone"+ #-###-###-####
      1 phone"+ # ###-###-####
      1 phone"#-###-###-####
      1 phone"#+-###-###-####
      1 phone"#+###-###-####
      1 phone"###- ###- ####
      1 phone"###) ###-####
      1 phone"############
      1 phone"### ###-#####
      1 phone"# -###-###-####
      1 phone"# ### ###-####
      1 phone"# ### ### ####
      1 operator:phone"+#-###-###-####
      1 manager:phone"+#-###-###-####
      1 fax:tollfree"+#-###-###-####
      1 fax"+#-###+###-####
      1 fax"+#### ### ####
      1 fax"+## ## ### ####
      1 fax"+# ##########
      1 fax"#-###-###-####
      1 fax"###-####
      1 contact:tty"+#-###-###-####
      1 contact:phone:tty"+#-###-###-####
      1 contact:phone"+#-###-###-AAAA
      1 contact:phone"+#(###) ###-####
      1 contact:phone"+# ###-###-#### ######
      1 contact:phone"+# ### ### ####
      1 contact:phone"###-###-###-####
      1 contact:phone"###-###-####
      1 contact:phone"###########
      1 contact:fax"+# ###-###-####
      1 phone"### ###-#####
      1 phone"# -###-###-####
      1 phone"# ### ###-####
      1 phone"# ### ### ####
      1 operator:phone"+#-###-###-####
      1 manager:phone"+#-###-###-####
      1 fax:tollfree"+#-###-###-####
      1 fax"+#-###+###-####
      1 fax"+#### ### ####
      1 fax"+## ## ### ####
      1 fax"+# ##########
      1 fax"#-###-###-####
      1 fax"###-####
      1 contact:tty"+#-###-###-####
      1 contact:phone:tty"+#-###-###-####
      1 contact:phone"+#-###-###-AAAA
      1 contact:phone"+#(###) ###-####
      1 contact:phone"+# ###-###-#### ######
      1 contact:phone"+# ### ### ####
      1 contact:phone"###-###-###-####
      1 contact:phone"###-###-####
      1 contact:phone"###########
      1 contact:fax"+# ###-###-####
```

**Comment by frodrigo** [comment]
I see on the web, at least for Quebec, the advice is to mix space and hyphen.

I don't what to suggest to replace space with hyphen. It's not really wrong. I prefer focus on real problem and avoid contributors fixing very low level issue. By experience, when asking to much to contributors, the just skip the check.

**Comment by matthewdarwin** [comment]
There was much less cleanup of phone numbers in Quebec compared to the rest of the country... Was waiting to have this validation check.

**Comment by frodrigo** [comment]
Not sure what you suggest to do with Canadian toll free number. You can't call from abroad (NANP)?

**Comment by matthewdarwin** [comment]
Toll free numbers can be restricted to be only callable from certain locations (eg you must be in Canada to call a Canada number, or they can be open to anywhere... I think usually they are only open to canada/us, but I am not expert here).  Toll free numbers always start with the specific prefix +1-800, +1-844, +1-855, +1-866, +1-877, +1-888.  Anything else is not a toll-free number (local numbers are toll-free as well, but people don't refer to those as toll-free).  

So it is normal for business like hotels to have 2 phone numbers: a local phone number and a toll-free phone number.

**Comment by frodrigo** [comment]
`phone:tollfree` is not checked yet. But there are few, and all in the NANP area.

https://taginfo.openstreetmap.org/keys/phone%3Atollfree#map

**Comment by frodrigo** [comment]
@mojoaxel Please let us ensure it works on few countries first. Nevertheless can you look to all other paremeters in configration and suggest values for DE (phone_code, phone_len, phone_len_short, phone_format, phone_international)?

**Comment by frodrigo** [comment]
Please open new issues for new countries, or changes.
