### ISSUE TITLE
capacity 0 Opendata

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#291]
source | 3990
item | 8150
class | 11
subclass | 1663004961
lat lon | 43.3354333 -0.4308724
fr Parking à vélo de la CAPP non intégré
tags_create
 amenitybicycle_parking
 capacity0
 sourceCommunauté d'Agglomération Pau-Pyrénées - 01/2013

I have no idea is capacity is a bug or a unknown value that need to be dropped or if it's meaning is that this parking doesn't exist anymore but create a tag with capacity=0 look like a no meaning value

**Comment by frodrigo** [comment]
Please, can you look at the data provider, or ask it ?
