### ISSUE TITLE
false positive detection of unreachable oneway item 1210

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#292]
This reports item 1210: 
One way inaccessible or missing parking or parking entrance
https://osmose.openstreetmap.fr/en/error/17302435917

It is reported along this section four times. on each u-turn land and on the bridge segments.

I can only see the oneway=-1 or the main road where is branches off as unusual tagging.
Is in sql130 the handling of oneway=-1 broken? Or does it need to be handled different here, as the direction of the way needs to be reversed...

**Comment by frodrigo** [comment]
```sql
generate_subscripts(nodes, 1, tags?'oneway' AND tags->'oneway' = '-1')
```
The last argument set the direction of the generation. So here it's handled.

The link you provide is no more valid. Can you provide a permalink please.

**Comment by stephankn** [comment]
Here a permalink to the area.

The tagging is not optimal, but correct. I still suspect it has something to do with the way tagged as oneway=-1. Where it connects to the oneway=yes errors are reported.

http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=18.326677&lon=99.387403&item=1210&level=1&tags=&fixable=&overlays=FFFFFFFFFFFFFFFFFFFFT

![image](https://user-images.githubusercontent.com/251140/39399932-2589a554-4b27-11e8-869f-b6bda803e0bd.png)

**Comment by stephankn** [comment]
I just reversed the two northern ways. If two of the errors go away tomorrow it is proven to be caused by incorrect evaluation of the oneway=-1 tags.

**Comment by frodrigo** [comment]
I'm currently load the country into db to test the sql on it.

**Comment by stephankn** [comment]
Can you run analyzers on stand-alone files?
If my theory is correct it should complain about the following minimalistic case:

[repro-osmose-oneway.zip](https://github.com/osm-fr/osmose-backend/files/1958116/repro-osmose-oneway.zip)

maybe IDs need to be edited to be positive...

**Comment by stephankn** [comment]
After reversing the direction of the northern way and getting rid of the oneway=-1 two of the four issues are gone. So it is confirmed that it is related to oneway=-1 not correctly handled.

**Comment by frodrigo** [comment]
It's now fixed.
http://osmose.openstreetmap.fr/en/errors/graph.png?item=1210&class=3&start_date=2018
