### ISSUE TITLE
item 8110 - Public service not integrated : to fix with deprecated tag 

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#293]
source | 2300
item | 8110
class | 11
title | en | Public service not integrated
subtitle | fr | Caisse d'allocations familiales
...
tags_create | office | administrative

Moreover, no "fix-edit"

HTH

**Comment by frodrigo** [comment]
Duplicate of #236 ?

**Comment by deuzeffe** [comment]
Yes.

**Comment by frodrigo** [comment]
Please, can you help on the first issue.

**Comment by deuzeffe** [comment]
@frodrigo like this https://github.com/osm-fr/osmose-backend/issues/236#issuecomment-385467249 ?
