### ISSUE TITLE
Missing from/to tag on a public_transport route relation should not apply to bus routes

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#294]
[i=2140][c=21405] Missing from/to tag on a public_transport route relation
examples: r4070212 r7380509 

According to https://wiki.openstreetmap.org/wiki/Relation:route#Public_transport_routes  "from" and "to" tags are not documented for route=bus.  (It is documented for rail though).

So I think this error should not appear if type=bus, type=trolleybus, type=share_taxi

**Comment by matthewdarwin** [comment]
https://osmose.openstreetmap.fr/en/errors?country=canada_ontario&item=2140&level=1%2C2%2C3

eg https://osmose.openstreetmap.fr/en/error/17454520193

**Comment by frodrigo** [comment]
cc @nlehuby

**Comment by nlehuby** [comment]
Thank you for your feedback.

These tags provide useful metadata about the route variants. Do you know any cases where adding those would be bad ?

BTW, the `from` and `to` tags are recommended according to the approved [public_transport proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Route_direction.2Fvariant), I think we should update the wiki.

**Comment by matthewdarwin** [comment]
The existing routes that have this issue are bi-directional, which according to the public transport proposal page is not recommended.  If there routes were one-way, then I would not have problems with these tags.  (I don't know how to tag from/to on a bi-directional route)

It would be very helpful if the https://wiki.openstreetmap.org/wiki/Public_transport page was up-to-date as to what was accepted in the proposal https://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Route_direction.2Fvariant   I am relatively new to OSM so I don't have the history.

So, yes I am fine leaving the error checks, if the error checks match the wiki.   I see other differences between the two pages as well.
