### ISSUE TITLE
500 server error on https://osmose.openstreetmap.fr/en/errors/false-positive

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#295]
Error: 500 Internal Server Error

Sorry, the requested URL 'https://osmose.openstreetmap.fr/en/errors/false-positive' caused an error:

Internal Server Error

-------

It comes from a link on this page: https://osmose.openstreetmap.fr/en/?country=canada_ontario&item=2140&level=1%2C2%2C3

**Comment by frodrigo** [comment]
The same ?
http://osmose.openstreetmap.fr/fr/errors/false-positive?source=30984&item=8280&class=11
http://osmose.openstreetmap.fr/fr/errors/done?source=30984&item=8280&class=11
