### ISSUE TITLE
Integration French pharmacies: updated DB? - FINESS

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#298]
Hello,

The DB presently used to integrate pharmacies in France (Celtipharm 2014) seems outdated. Maybe another should replace it, for ex. https://www.data.gouv.fr/fr/datasets/finess-extraction-du-fichier-des-etablissements/ Hope it's easy to extract a DB for pharmacies only...

HTH

**Comment by frodrigo** [comment]
@jocelynj the analyser name have changed, password update is required on frontend, isn't it?
http://dev.osmose.openstreetmap.fr/fr/errors/?item=8210

**Comment by jocelynj** [comment]
Yes, a password update is required, but it was already done on both frontend.

**Comment by frodrigo** [comment]
Ok I was looking at the bad thing.
We have now duplicate results: http://osmose.openstreetmap.fr/fr/errors/?item=8210
