### ISSUE TITLE
Integration "college" (France): new DB?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#299]
Hello,

The DB used for: 

item 8030 
cl 100 
source | 2299 | merge_college_FR-france_local_db

is no long available (https://www.data.gouv.fr/DataSet/30382046 // 404) and strongly outdated (Office national d'information sur les enseignements et les professions - 11/2011). 

Maybe this other DB https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-principaux-etablissements-enseignement-superieur/?disjunctive.type_d_etablissement&disjunctive.typologie_d_universites_et_assimiles can be a better one.

HTH

**Comment by frodrigo** [comment]
Your DB contains only 247 rows.

I found this other data set:
https://www.data.gouv.fr/fr/datasets/etablissements-denseignement-superieur-2/
with 3600 rows.

The original data set contains 4300 rows.

**Comment by deuzeffe** [comment]
Gasp, new DB but not complete enough :( 

Maybe the dataset your found can replace the 2011 DB (same productor).

**Comment by frodrigo** [comment]
Colleges back to business
http://osmose.openstreetmap.fr/en/errors/?item=8030,8031,8032,7070&class=100,101,102,103
