### ISSUE TITLE
Integration French DSO Enedis distribution substations

### ISSUE THREAD

**Issue by gustavecha** [osm-fr/osmose-backend#300]
Hi

This file is available from today to map French power distribution substations operated by Enedis (95% of population)
https://data.enedis.fr/explore/dataset/poste-electrique/

There are about 730k nodes which are all public distribution substations splitted between 2 main OSM approaches : power=substation + substation=minor_distribution + operator=Enedis + voltage=20000;400
These can be :
* building (area building=yes + location=indoor)
* street cabinet (node/area man_made=street_cabinet + street_cabinet=power)
* indoor in a larger building (node location=indoor)

Or power=* + transformer=distribution + operator=Enedis (thanks to @Penegal)
These can be pole mounted transformers without power=substation on them.

All objects with operator={EDF,ERDF} should conflate with nodes in the file but be modified with operator=Enedis which is the only recommended value.

Available to review and test any new validator involving this new file, all the best

**Comment by GeorgeKaplan** [comment]
A similar conflation analysis could be run with the other dataset : https://data.enedis.fr/explore/dataset/poste-source/ which lists the HTB/HTA electric substations.

**Comment by Penegal** [comment]
@gustavecha: note that many objects in the `poste-electrique` dataset are in fact pole-mounted transformers and that, for them, a recently approved proposal added the `voltage:primary` and `voltage:secondary` keys, in order to unambiguously model transformer voltages.

**Comment by gustavecha** [comment]
Ooops
This is right pole mounted transformers are "substations" but won't get power=substation on OSM (since power=pole is used on the node).

Osmose have to conflate with power=* + transformer=distribution + operator=Enedis to don't warn about mistaken missing objects.
Since Enedis doesn't provide the class of substation in poste-electrique dataset, osmose is only able to propose building=yes + power=substation on every 731k nodes in case of missing substation. User will have to check if it's an actual building prior to solve any issue.

Can't those pole mounted transformers get substation=minor_substation too ?

**Comment by Penegal** [comment]
That would likely be an error: these are supposed to be tagged `power=pole+transformer=distribution`.

**Comment by gustavecha** [comment]
Logically, it's a substation.
The pole, substation and transformer are located on the same node.

Nevermind, this was only wondering

**Comment by frodrigo** [comment]
So. The content of the initial request is still the target ? If not please, can you make again a summary.

**Comment by gustavecha** [comment]
Yes the content of initial request is up to date and is the target

**Comment by frodrigo** [comment]
Wow, what a niggard open data set!
Have you checked for quality of location? What conflation distance do you suggest?
The actual Osmose code does not support alternative suggestions integration.

The first analyser code and the results are here: http://osm110.openstreetmap.fr/~fred/enedis/

**Comment by frodrigo** [comment]
I rerun the analyser with 50m and without the commented lines. I replaced the results file.

> alternative suggestion integration
- power=substation + substation=minor_distribution + operator=Enedis + voltage=20000;400 + building=yes + location=indoor
- power=substation + substation=minor_distribution + operator=Enedis + voltage=20000;400 + man_made=street_cabinet + street_cabinet=power
- power=substation + substation=minor_distribution + operator=Enedis + voltage=20000;400 + location=indoor
- power=* + transformer=distribution + operator=Enedis (witch values should be generated in place of * ?)

Osmose code for now, can only produce one set of tags in the case of OpenData

One change VS multiple changes
![image](https://user-images.githubusercontent.com/1785486/40283602-2050d538-5c81-11e8-97cc-8a8d71cc4311.png)

**Comment by gustavecha** [comment]
> Osmose code for now, can only produce one set of tags in the case of OpenData
Sure, no problem with this.
For now, initial request mention every combination for conflation with existing only.

We lack some data in Enedis file to determine which combination have to be used when a node is missing in OSM.
Since location are pretty approximative it would be dangerous to arbitrary set any missing object in a building just because the lat/lng seem to say so.

I see no problem in results, can you put it on osmose test instance please?

**Comment by frodrigo** [comment]
Just to be sure:
We match again:
- power=substation + substation=minor_distribution + operator=|EDF|ERDF|Enedis
- power=* + transformer=distribution + operator=|EDF|ERDF|Enedis

We produce only:
- power=substation + substation=minor_distribution + operator=Enedis + voltage=20000;400

It's correct ?

**Comment by gustavecha** [comment]
Yes that's correct !

**Comment by frodrigo** [comment]
The result is available here:
http://osmose.openstreetmap.fr/en/errors/?source=30984&item=8280&class=11
http://osmose.openstreetmap.fr/en/map/#source=30984&item=8280&class=11

**Comment by gustavecha** [comment]
Thank you Frédéric

There are some false positive like this : 
http://osmose.openstreetmap.fr/en/error/17961801568 <=> https://www.openstreetmap.org/way/70574353
It seems that existing substations in buildings (area) aren't detected, aren't they ?

**Comment by frodrigo** [comment]
Yes there is ways.
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_power_substation_minor_FR.py#L43

But I don't know why, this is not the right version of the code.

**Comment by gustavecha** [comment]
Agreed
It seems that substations as nodes aren't seen too
http://osmose.openstreetmap.fr/en/error/17961799520 <=> https://www.openstreetmap.org/node/2417073560

**Comment by gustavecha** [comment]
It works like a charm
Thank you a lot @frodrigo !
