### ISSUE TITLE
Advice for RAM/CPU for running backends

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#302]
I am running a copy of osmose-backend locally in a docker container.   The pdf for the region I have is 600MB (canada_ontario.osm.pbf)

Do you have any advice on how much RAM/CPU should I have to run osmose-backend efficiently on this size of data?

On my test machine with 8 i7 cores and 24GB RAM, this analysis takes over 3 hours.... probably needs more RAM?  Only 1 CPU seems to be busy at a time.

docker run -it --rm -v osmose-data-volume:/data/work/osmose osm-fr/osmose_backend --country=canada_ontario

**Comment by frodrigo** [comment]
3h is a good time. 
See stats on our cluster: http://buildbot.osmose.openstreetmap.fr/builders/canada_ontario/builds/350
It's take 8h.

**Comment by jocelynj** [comment]
Note that the process mostly uses only one cpu, so having 8 cpus won't change the speed.

Using a faster hard drive to store the pbf file or the postgresql database should have an impact if you want to make it faster.

**Comment by matthewdarwin** [comment]
Sorry my original time was off... 5.5 hrs.
Yes, I see that mostly only one cpu was used.... I was just using the machine I had on hand for testing.
So you have confirmed my thought that more RAM would be better (this would be used as disk I/O cache).  I will test again with 32GB RAM...
