### ISSUE TITLE
French TSO RTE and GRTGaz are moving their opendata platform

### ISSUE THREAD

**Issue by gustavecha** [osm-fr/osmose-backend#303]
Hi,

Please note that RTE and GRTGaz are moveing from their own opendata platforms to mutualised 
https://opendata.reseaux-energies.fr/

Files are remaining the same.
Items 8280, 8281 et 8290 may be impacted.

RTE is updating its files 3 times a year, does Osmose get updated automatically ?

**Comment by frodrigo** [comment]
There is also this one:
http://osmose.openstreetmap.fr/fr/errors/?item=8270,7180,8271,8272&useDevItem=all
But the  new data set no more have coordinates (previously at IRIS level).
"Registre 2015 des installations de production raccordées au Réseau de Transport d'Electricité"

**Comment by gustavecha** [comment]
Good point.

New dataset is here : https://opendata.reseaux-energies.fr/explore/dataset/registre-national-parc-prod-stock-elec-agrege/information/?disjunctive.libelle_departement&disjunctive.libelle_region&disjunctive.libelletension&disjunctive.libelle_filiere&disjunctive.libelle_combustible&disjunctive.libelle_combustible_secondaire&disjunctive.libelle_technologie&sort=libelle_commune
Data quality is pretty poor (bad generator amount in some production facilities, wrong dates and so on... we're working with RTE to improve this), but even without coordinates, it is useful to check data in existing osm objects.
Conflation is currently possible on name only, but I'll suggest to add EIC code (OSM ref:EU:ENTSOE_EIC) for better matching.
