### ISSUE TITLE
reports may be duplicated when retrieved via API

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#306]
I am using osmose via Vespucci. Sorry if I made a wrong guess and it is a Vespucci bug. It appears that some issues are reported twice, I encountered some that appeared multiple times. Below I attach all info that Vespucci provides about one of duplicated reports.

![screenshot_2018-06-05-07-21-16-423_de blau android](https://user-images.githubusercontent.com/899988/40956572-53f03160-6891-11e8-8975-60ee8a0fd5f6.png)
![screenshot_2018-06-05-07-21-05-237_de blau android](https://user-images.githubusercontent.com/899988/40956571-53ef4a0c-6891-11e8-8611-487db7e135d8.png)

**Comment by matkoniecz** [comment]
Is there some way that I can help with investing what went wrong?

**Comment by frodrigo** [comment]
I do not investigate. But do you also try to report the issue to Vespucci? Why do you think is on Osmose-QA side ?
You can try to call the Osmose API on the same area.

**Comment by matkoniecz** [comment]
> Why do you think is on Osmose-QA side ?

Vespucci shows two different ids - I assumed that this are Osmose ids of errors.

>  You can try to call the Osmose API on the same area.

I will try that. Is https://wiki.openstreetmap.org/wiki/Osmose/api/0.2 the best available documentation of API?

**Comment by frodrigo** [comment]
Do you have some id ? on the picture it is the same id.

Content of Osmose issues can be show at: http://osmose.openstreetmap.fr/fr/error/{{ID}}

**Comment by matkoniecz** [comment]
> on the picture it is the same id.

Node id is the same, error id is different.

http://osmose.openstreetmap.fr/fr/error/18051304841
http://osmose.openstreetmap.fr/fr/error/18025717464

are reporting 410 (Gone), maybe because Vespucci is showing wrong ids, maybe because I marked this errors as resolved.

**Comment by matkoniecz** [comment]
I will report next encountered pair.

**Comment by matkoniecz** [comment]
I am currently unable to reproduce it. Thanks for an API hint, I will use it in next reports.
