### ISSUE TITLE
exclude place=square on area=yes ways from "Conflict between tags: place, highway"

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#307]
http://osmose.openstreetmap.fr/en/error/18381437210

I am not fan of tagging like

```
area = yes
highway = pedestrian
name = Plac świętego Idziego
name:de = Sankt-Giles-Platz
place = square
surface = paving_stones 
```

at https://www.openstreetmap.org/way/238862283

but it is not something worth reporting in validator

**Comment by frodrigo** [comment]
For now, there is no exception to this rule.

**Comment by matkoniecz** [comment]
Why? Do you think that tagging like this is wrong?

**Comment by frodrigo** [comment]
Done, but low impact.
