### ISSUE TITLE
ignore landuse=school with amenity=school on "Conflict between tags: amenity, landuse"

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#308]
I am not fan of landuse=school but it is not a real error to use it. See for example https://www.openstreetmap.org/way/304389877 reported in http://osmose.openstreetmap.fr/en/error/18381444244

**Comment by frodrigo** [comment]
For now, there is no exception to this rule.

**Comment by matkoniecz** [comment]
Why? Do you think that landuse=school is so bad idea that it should be reported as problem with the highest severity?

**Comment by frodrigo** [comment]
For now there is no exception support in the analyser. More over, I'm not sure what about should be an exception or not. Do you have a general approach to this issue?

**Comment by frodrigo** [comment]
Stats of co-usage on France (it's my larger database)
```
 count |   landuse   |      amenity       
-------+-------------+--------------------
    69 | cemetery    | grave_yard
    57 | school      | school  <---
    41 | military    | police  <---
    41 | industrial  | recycling  <---
    36 | residential | low-income housing
    28 | basin       | fountain
    21 | basin       | watering_place
    13 | residential | social_facility
    10 | religious   | monastery
     8 | landfill    | recycling
     7 | basin       | lavoir
     5 | grass       | parking
     5 | hospital    | hospital
     5 | basin       | swimming_pool
```
What do you think of creating exception for marked couples ?
Do you have idea of other couples ?

**Comment by matkoniecz** [comment]
- amenity=school + landuse=school and landuse=industrial + amenity=recycling makes perfect sense and IMHO should be whitelisted.

I am surprised landuse=military + amenity=police.

>  Do you have idea of other couples ?

Based on my city:

- amenity=marketplace, landuse=retail www.openstreetmap.org/relation/6003115
- amenity=monastery, landuse=religious https://www.openstreetmap.org/way/163416516

**Comment by frodrigo** [comment]
> I am surprised landuse=military + amenity=police.

Ok, I skip this one, it's maybe too specific in France (we have 3 police forces, and one is part of military forces)

> amenity=marketplace, landuse=retail 

OK

> amenity=monastery, landuse=religious

landuse=religious brrr, it's even strange than landuse=military, and the couple have too few occurrences in the world.

**Comment by frodrigo** [comment]
Done, but low impact.

**Comment by matkoniecz** [comment]
Thanks for removing these false positives (I am thanking also for #307)!
