### ISSUE TITLE
is something broken with germany_thueringen?

### ISSUE THREAD

**Issue by osmtools** [osm-fr/osmose-backend#309]
Since a few days, my personally [user issues](http://osmose.openstreetmap.fr/de/byuser/Harald%20Hartmann) are empty (got 22 problems), and in my area there aren't any low level issues. Example: there are some fixme Objects, have a look at this overpass [query](http://overpass-turbo.eu/s/zMM), but not in osmose.
Also the Need fix germany_thueringen -sax [graph](http://osmose.openstreetmap.fr/de/errors/graph.png?source=9308&item=4061&class=40610) looks a little bit strange.

**Comment by frodrigo** [comment]
It's a global issue. It's linked to the RGPD changes. Geofabrik extract no more content user data, unless explicitly downloaded with loggin. Osmose-QA does not made the necessary changes yet.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/issues/310
https://github.com/osm-fr/osmose-frontend/issues/97

**Comment by frodrigo** [comment]
It is not specific to sax analyser on germany_thueringen. All the other analyser of this country have an issue : http://osmose.openstreetmap.fr/fr/errors/graph.png?country=germany_thueringen

@jocelynj maybe we need to reset it ?

**Comment by osmtools** [comment]
> It's a global issue. It's linked to the RGPD changes.

An issues only for new errors, right? Because i've checked other users as well and their issue list is filled.
And i'm working only in germany_thueringen, so i think it's defintely a problem, as you mentioned above.

**Comment by frodrigo** [comment]
RGPD. Yes we done nothing yet, so the sock of issue in Osmose QA  lowering since the user input data is no more present.

**Comment by frodrigo** [comment]
The extract was corrupted. Is now fixed. Thank you for your report.
