### ISSUE TITLE
Check opening_hours is well-formed

### ISSUE THREAD

**Issue by Ekleog** [osm-fr/osmose-backend#312]
I think the title says it all.

Anyway, thank you for your work on osmose! :+1:

**Comment by jocelynj** [comment]
Do you know if there is a possible check or rule that we can use ?

**Comment by frodrigo** [comment]
https://gist.github.com/rezemika/92debb574a9b73ec328b3751b1214a56

**Comment by frodrigo** [comment]
@rezemika interested to plug you validator/corrector of opening_hours into Osmose-QA ?

**Comment by rezemika** [comment]
@frodrigo : It would be a pleasure. However, I don't really understand the way validators are implemented. Do you know if there is a doc somewhere?

**Comment by rezemika** [comment]
I cleaned the code and made of module of it, here is the repo: https://github.com/rezemika/oh_sanitizer ;)

**Comment by frodrigo** [comment]
@rezemika do you plan to make yourself the support into Osmose-QA, or not ? I can do it if you want.

**Comment by rezemika** [comment]
@frodrigo : Sorry for the late, I was quite busy the last days.

I tried the following, but I'm not sure of the class errors or items to use, so feel free to comment and criticize: https://gist.github.com/rezemika/717c70d9f8fc1b828a106a9ef9a22bf8
I used directly the package `oh_sanitizer`. Indeed, it's possible to directly copy its code in the file.

**Comment by frodrigo** [comment]
Done on https://github.com/frodrigo/osmose-backend/commits/dev https://github.com/frodrigo/osmose-backend/commit/8b04f5ca59475baa0462e94d82ac271783d35aaf
Waiting for https://github.com/rezemika/oh_sanitizer/issues/2

**Comment by frodrigo** [comment]
Still missing some countries (@jocelynj ?)

**Comment by frodrigo** [comment]
With the Debian package of lark-parser by @jocelynj it can now run on all osm-fr server.
![image](https://user-images.githubusercontent.com/1785486/46176637-6fc4c800-c2b0-11e8-9abb-45d2d776f3e5.png)

**Comment by frodrigo** [comment]
Now all backend server can have lark-parser.

**Comment by frodrigo** [comment]
Here we are!
Now we can activate publicly this new item.

**Comment by frodrigo** [comment]
https://twitter.com/osmose_qa/status/1050649492888870912
