### ISSUE TITLE
School-fr

### ISSUE THREAD

**Issue by vinber** [osm-fr/osmose-backend#314]
About merge with school-fr, there's an error here : https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_school_FR.py

School_FR_nature_uai = 
"151": u"primaire", -> "élémentaire"
        "152": u"primaire", -> "élémentaire"
"153": u"primaire", -> "élémentaire"

Source : https://www.data.gouv.fr/fr/datasets/r/e17a0a8e-54e6-4a53-9262-e087401c0046

**Comment by frodrigo** [comment]
No. There an issue with original data.
https://github.com/osm-fr/osmose-backend/commit/e832aa4febc6bd6df7827c369347b3b06873df1f#diff-018a8a6be6d2380a10dbebc5414bf692

**Comment by vinber** [comment]
sorry, i'm not sure to understand.
I think it's "élémentaire" the good one.

 in https://www.data.gouv.fr/fr/datasets/r/e17a0a8e-54e6-4a53-9262-e087401c0046, there's :+1: 

151 | ECOLE DE NIVEAU ELEMENTAIRE
152 | ECOLE ELEMENTAIRE ANNEXE D ESPE
153 | ECOLE ELEMENTAIRE D 'APPLICATION

"élémentaire" it's for child between 6-12 and "primaire" it's "maternelle" + "élémentaire".

In many case, Osmose suggest to put "primaire" but it's "élémentaire"

**Comment by frodrigo** [comment]
"primaire" was set because for 151, 152, 153 there is not only "élémentaire" but also "maternelle" + "élémentaire".
"primaire" is more generic, as "élémentaire" was not always true.

**Comment by Bibi56** [comment]
@frodrigo is right, in short it's a mess ;-(.
I checked the dataset for cleary names écoles and found that écoles named `*primaire*` resp.  `*maternelle*` and `*élémentaire*` include not least than 5 resp 6 and 6 different values:

id|tltle|count `*primaire*` | count `*maternelle*` | count `*élémentaire*`
---|--|--|--|--
151 | ECOLE DE NIVEAU ELEMENTAIRE | 25113 | **90** | 9640
163 | ECOLE DE NIVEAU ELEMENTAIRE SPECIALISEE | 9 | 0 | 20
152 | ECOLE ELEMENTAIRE ANNEXE D IUFM | 6 | 0 | 4
153 | ECOLE ELEMENTAIRE D APPLICATION | 185 | 0 | 152
---|--|--|--|--
101 | ECOLE MATERNELLE | **95** | 15108 | 12
102 | ECOLE MATERNELLE ANNEXE D IUFM | 0 | 7 | 0
103 | ECOLE MATERNELLE D APPLICATION | 0 | 1 | 0 
111 | ECOLE MATERNELLE SPECIALISEE | 0 | 1 |  0 | 0
---|--|--|--|--
170 | ECOLE SANS EFFECTIFS PERMANENTS | 0 | 1 | 1

So we have 60 maternelles (according to their names) that are *not* declared as maternelle. Bad as we could be more precise.
More problematic 95 primaires (according to their names) that *are* declared as maternelle. Here something is wrong, not sure if the name or the classification (probably the classification but it could also be a primaire where the élémentaire closed but the name was preserved)

**Comment by frodrigo** [comment]
So we keep as is. Please reopen if you still want some improv.

**Comment by deuzeffe** [comment]
@Bibi56 À noter que l'analyse osmose fait appel à une DB en OD des établissements (avec dénomination et UAI à jour) plus récente (cf https://github.com/osm-fr/osmose-backend/issues/489) que celle utilisée en 2018 et qu'il y a eu des changements de dénomination/catégorie dans la base elle-même. Ça n'explique probablement pas toutes les différences mais certaines, sûrement que oui ^^

**Comment by Bibi56** [comment]
@deuzeffe  j'utilisais https://raw.githubusercontent.com/osm-fr/osmose-backend/master/merge_data/school_FR.csv.bz2 qui était celle utilisée par Fred.
Tu nous refais les stats avec les nouvelles données ?
Elle sont mieux mais pas parfaites :

Attribut | Valeur
-- | --
Code établissement | 0500852E
Appellation officielle | Ecole maternelle
Dénomination principale | ECOLE **PRIMAIRE**
Code nature | 151
Nature | ECOLE DE NIVEAU ELEMENTAIRE

**Comment by deuzeffe** [comment]
@Bibi56 oui, mais ça c'était avant :) maternelle appartient à primaire, rien d'anormal. En revanche, le "niveau élémentaire" m'interpelle... Bref, faut voir sur le terrain :P

**Comment by Bibi56** [comment]
@deuzeffe je comprends ta logique mais si c'est juste une maternelle on dit que c'est une maternelle, on ne généralise pas inutilement à primaire. Sur la nature pas de soucis par contre car "ECOLE DE NIVEAU ELEMENTAIRE" veut dire "ECOLE PRIMAIRE" dans ce fichier. C'est faux mais toujours faux (sauf pour les écoles élémentaires ^^).

**Comment by deuzeffe** [comment]
@Bibi56 La base source est là : https://data.education.gouv.fr/explore/dataset/fr-en-adresse-et-geolocalisation-etablissements-premier-et-second-degre/ Je te laisse l'explorer ;p
