### ISSUE TITLE
Item 8300 : traffic signs mapillary

### ISSUE THREAD

**Issue by operon** [osm-fr/osmose-backend#315]
For item 8300 and class=11 for exemple "maxspeed=70"

exemple : http://osmose.openstreetmap.fr/fr/error/18692257295
http://osmose.openstreetmap.fr/fr/map/#item=8300&class=11&zoom=13&lat=46.3469&lon=3.3185&overlays=FFFFFFFFFFFFFFFFFFFFT&level=1%2C2%2C3&tags=&fixable=

the maxspeed:backward and maxspeed:forward seems not to be recognized ??

i think to maxspeed:hgv or maxspeed:trailer,....

**Comment by frodrigo** [comment]
It's already in the code, waiting for integration and deployment: https://github.com/frodrigo/osmose-backend/commit/dd2895e2f30ff5c92a4bf32e90b54e381b12d43c

**Comment by operon** [comment]
Good,

But in code, I do not see 

- maxspeed:trailer=...
- maxspeed:forward/backward:hgv=...
- maxspeed:forward/backward:conditional=...
Good,

**Comment by frodrigo** [comment]
This tags are not so common. Each entry cost, so chooses must be done.
Even on https://github.com/frodrigo/osmose-backend/commit/dd2895e2f30ff5c92a4bf32e90b54e381b12d43c I do not add all tags to all speeds.
