### ISSUE TITLE
old timestamp issue

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#317]
http://osmose.openstreetmap.fr/fr/error/16674624680
source | 105
item | 9014
class | 9014003
subclass | 364316040
elems | node1596702382
lat lon | 48.6374387 -2.0139445
title | enSpecify if it is a stop (platform) or a location on the road (stop_position) | en | Specify if it is a stop (platform) or a location on the road (stop_position)
en | Specify if it is a stop (platform) or a location on the road (stop_position)
subtitle | enSpecify if it is a stop (platform) or a location on the road (stop_position) | en | Specify if it is a stop (platform) or a location on the road (stop_position)
en | Specify if it is a stop (platform) or a location on the road (stop_position)
timestamp | 2018-03-17 21:43:03

it's maybe a class change..

**Comment by frodrigo** [comment]
9014/9014003 was a temporary duplicate item of 2140/21411.

Full list of temporary 9014:
- 9014001
- 9014003
- 9014004
- 9014011
- 9014012
- 9014015
- 9014016
- 9014017
- 9014018

1. Remove temporary classes
2. Some countries still report this class numbers (cc @jocelynj )

**Comment by frodrigo** [comment]
Removed
