### ISSUE TITLE
Street way should be inside the associatedStreet

### ISSUE THREAD

**Issue by nlehuby** [osm-fr/osmose-backend#318]
Could we have an additional test about associatedStreet ?
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_associatedStreet.py

I would like to check for cases where an associatedStreet relation exists but some ways are not yet inside the relation.

For instance I have this street with 3 ways, but only one of them is inside the associatedStreet relation:
![capture du 2018-08-01 11-53-04](https://user-images.githubusercontent.com/919962/43514901-7fcb9424-9581-11e8-8cd2-413b05c37ac4.png)

**Comment by nlehuby** [comment]
Here is another one:
![capture du 2018-08-01 11-57-25](https://user-images.githubusercontent.com/919962/43515157-1daa29d0-9582-11e8-8e18-fbe7a722836b.png)

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=2060&class=18

**Comment by nlehuby** [comment]
Thanks :+1:
