### ISSUE TITLE
Feature request: detect duplicate object by names

### ISSUE THREAD

**Issue by d1g** [osm-fr/osmose-backend#32]
Warn user when there similarly named features within proximity.

osmose should warn user about feature with same name, provide link to http://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element and suggest to use relation type=multipolygon or type=site.

Bonus points for transliterated text (Ελληνική Δημοκρατία - Hellēnikē Dēmokratia etc)
Bonus points for advanced string comparison features (support for articles, mixed case, umlaut)
Bonus points for fuzzy matching, preferably done as separate check/process.

**Comment by frodrigo** [comment]
Osmose-QA is not a place to raise wranning.
Many different objects can share a common name because there are in a common place : plaza, bus stop, post office...
