### ISSUE TITLE
New rules for bike

### ISSUE THREAD

**Issue by monsieuraa** [osm-fr/osmose-backend#323]
I made a set of rules for JOSM for bike analyses. I join my file if you want to integrate it in Osmose.
This is not very clean but it is usable. 

Thanks
[BikeRules.mapcss.txt](https://github.com/osm-fr/osmose-backend/files/2302583/BikeRules.mapcss.txt)

**Comment by monsieuraa** [comment]
I made some modification, tell me if you want something else 
[BikeRules.mapcss.txt](https://github.com/osm-fr/osmose-backend/files/2306791/BikeRules.mapcss.txt)

**Comment by frodrigo** [comment]
https://semestriel.framapad.org/p/rl2ht5LiCP

**Comment by frodrigo** [comment]
But!
Message parameters are not filled with values.

**Comment by frodrigo** [comment]
Already existing, only switch to mapcss:
- http://osmose.openstreetmap.fr/fr/errors/?item=2030&class=20301 : not ok, duplicate class usage 

New
- http://osmose.openstreetmap.fr/fr/errors/?item=2030&class=20302 : look good
- http://osmose.openstreetmap.fr/fr/errors/?item=2080&class=20805 : look good
- http://osmose.openstreetmap.fr/fr/errors/?item=3032&class=30328 : look good
- http://osmose.openstreetmap.fr/fr/errors/?item=3032&class=30329 :  Only 2 in the world ! We keep this rule anyway ?
- http://osmose.openstreetmap.fr/fr/errors/?item=4030&class=40301 : look good

**Comment by monsieuraa** [comment]
Yes I think we don't have to keep the class 30329

**Comment by frodrigo** [comment]
Already existing, only switch to mapcss:

- http://osmose.openstreetmap.fr/fr/errors/?item=2030&class=20301 : look good, but more issues than previous

New

- http://osmose.openstreetmap.fr/fr/errors/?item=4010&class=40101 : look good
- http://osmose.openstreetmap.fr/fr/errors/?item=2030&class=20302 : look good
- http://osmose.openstreetmap.fr/fr/errors/?item=2080&class=20805 : look good
- http://osmose.openstreetmap.fr/fr/errors/?item=3032&class=30328 : look good
- http://osmose.openstreetmap.fr/fr/errors/?item=4030&class=40301 : look good

**Comment by frodrigo** [comment]
https://twitter.com/osmose_qa/status/1051409496168456192
