### ISSUE TITLE
Detect missing zone30, living_street by neighborhood

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#326]
Use buffer/concave hull to detect missing tagging

**Comment by frodrigo** [comment]
https://opendata.paris.fr/explore/dataset/zones-de-circulation-apaisee-a-paris/map/?location=13,48.85088,2.35459

**Comment by Phyks** [comment]
Typical example here close to Montparnasse in Paris where it is quite easy to see that a couple of segments are missing the zone30 tag:

![2018-08-25-164410](https://user-images.githubusercontent.com/3856586/44619407-2daa0000-a886-11e8-843e-2f9b3193c7ad.png)

**Comment by frodrigo** [comment]
I run some tests  on Paris. It's promising.

![image](https://user-images.githubusercontent.com/1785486/44620296-efb2d900-a891-11e8-8bbf-8c0157086171.png)

The data: [30.zip](https://github.com/osm-fr/osmose-backend/files/2320847/30.zip)

```sql
DROP TABLE IF EXISTS z30;
CREATE TEMP TABLE z30 AS
SELECT
  id,
  tags,
  ST_Transform(linestring, 2154) AS linestring
FROM
  ways
WHERE
  tags != ''::hstore AND
  tags?'zone:maxspeed' AND
  ways.linestring && st_setsrid(st_makeline(st_makepoint(2.2057,48.9055), st_makepoint(2.409, 48.827)), 4326)
;

DROP TABLE IF EXISTS a30;
CREATE TEMP TABLE a30 AS
SELECT
  1 AS a,
  ST_Transform(linestring, 4326) AS linestring
FROM (
  SELECT
    ST_Buffer(
      (ST_Dump(
        ST_Union(ST_Buffer(linestring, 60))
       )).geom,
      -61
    ) AS linestring
  FROM
    z30
) AS t
WHERE
  ST_IsValid(linestring) AND
  NOT ST_IsEmpty(linestring)
;


SELECT
  highways.id,
  highways.tags
FROM
  a30
  JOIN ways AS highways ON
    highways.tags != ''::hstore AND
    highways.tags?'highway' AND
    highways.tags->'highway' IN ('residential', 'unclassified', 'tertiary') AND
    NOT highways.tags?'zone:maxspeed' AND
    (NOT highways.tags?'maxspeed' OR highways.tags->'maxspeed' = '30') AND
    highways.linestring && st_setsrid(st_makeline(st_makepoint(2.2057,48.9055), st_makepoint(2.409, 48.827)), 4326) AND
    highways.linestring && a30.linestring AND
    ST_Length(ST_Intersection(highways.linestring, a30.linestring)) / ST_Length(highways.linestring) > 0.8
;
```

On the test area I get 78 ways: 253982929,22653485,184124924,53792389,25471929,570748422,492851440,425721608,12204109,14647716,45395928,609286173,22946771,4216669,14348628,15919440,247516249,3127178,130075302,130075305,59461540,29992089,22468100,8415026,143407393,23369311,27089069,236877988,27817543,27817544,106394299,551932769,555481948,56000349,56000401,19580381,29712377,4039916,15275486,23696477,23235939,23706674,16877242,400285512,72072067,72072068,72072072,360133450,62117003,40036977,307333243,255109304,217588511,188450862,167966628,50481178,50481558,38273578,149738191,118764518,114992310,114992315,22770936,23300771,112631446,114014398,4574366,22972089,286549,390298295,390298292,306392295,172312427,83262392,22706102,4227124,19780769,62316777

**Comment by frodrigo** [comment]
I improve the process to remove small holes in polygons. The computation is more complex but better.
I also compare the data OSM with the Opendata of Paris, it does not match well.

Green: OSM
Red: possible missing tag in OSM
Yellow: OpenData
![image](https://user-images.githubusercontent.com/1785486/44622226-cfe0dc80-a8b4-11e8-9f9e-9274a825ce86.png)

**Comment by frodrigo** [comment]
We need to check results to establish if it's working well or have to false positives.

**Comment by frodrigo** [comment]
beta.osmose.openstreetmap.fr/fr/errors/?item=1210&class=20,30&useDevItem=all

**Comment by frodrigo** [comment]
Item is now public
http://osmose.openstreetmap.fr/fr/errors/?item=2150&class=20,30

**Comment by Phyks** [comment]
Great, thanks!
