### ISSUE TITLE
" street name contains ß" is a broken check for Germany

### ISSUE THREAD

**Issue by flohoff** [osm-fr/osmose-backend#327]
"Straße" ist the valid word in German so with this check all Roads in Germany are now flagged as a false negative:

Class 9009003 "street name contains ß" 

Flo

**Comment by frodrigo** [comment]
While we are waiting for fix integration and analysis data update I disable the display of this item on the Osmose frontend.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=9009&class=9009003&useDevItem=all&country=germany*

**Comment by frodrigo** [comment]
Resolved
