### ISSUE TITLE
Check for network key on public_transport=platform is not valid.

### ISSUE THREAD

**Issue by FrakGart** [osm-fr/osmose-backend#329]
The item 9014 class 9014007 check is not correct for PTv2. For example:

http://osmose.openstreetmap.fr/en/error/19745622335

There is nothing in the specifications for PTv2:

https://wiki.openstreetmap.org/w/index.php?oldid=625726

that says you can't put a network key on a public_transport=platform object.

**Comment by frodrigo** [comment]
cc @nlehuby @prhod
