### ISSUE TITLE
Guyane à Paris :)

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#332]
https://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=48.853029&lon=2.349314&item=8110
source | 2300
item | 8110
class | 11
subclass | 22134356
lat lon | 48.8532940 2.3486790
Caisse d'allocations familiales (Caf) de Guyane - accueil de Matoury, 22 rue Awara-Dende, Caisse d'allocations familiales de Guyane, Marais Leblond, 97351, 97305, Matoury, Cayenne Cedex (géocodé à la rue)

géocodé à la rue mais la Guyane est loin de Paris :)

**Comment by frodrigo** [comment]
Geolocalization come from original dataset
Please report directly to : https://www.data.gouv.fr/fr/datasets/service-public-fr-annuaire-de-l-administration-base-de-donnees-locales/
