### ISSUE TITLE
Discordant maxspeed and source:maxspeed in Belgium: regional difference

### ISSUE THREAD

**Issue by hgcvm** [osm-fr/osmose-backend#334]
Please add 
'be-vlg:rural ': ['70'],
to the file https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Maxspeed.py
. In Belgium the maximum speed in rural areas is 70 in the region Flanders. This is also mentioned in the wiki: https://wiki.openstreetmap.org/wiki/Key:source:maxspeed#Belgium

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?source=3763&item=3032&class=303241

**Comment by hgcvm** [comment]
Could I come back on this issue? It appears to me the problem still exists. For example: http://osmose.openstreetmap.fr/en/error/23641102996
This shouldn't be an Osmose warning, as `source:maxspeed = BE-VLG:rural ` and `maxspeed = 70 ` mean the same thing. In BE-VLG on rural roads, the maximum speed is indeed 70.
Or am I missing something here?
Thanks.

**Comment by frodrigo** [comment]
The setting is here: https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Maxspeed.py#L39

But I got the issue, there is an extra space.

**Comment by hgcvm** [comment]
Thanks frodrigo, that must be it! I didn't see that extra space.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?source=3727&item=3032&class=303241

**Comment by frodrigo** [comment]
Done. Only 127 issue left.

**Comment by hgcvm** [comment]
Sorry to have to bring this back up, but it seems that still a lot of false positives get reported on this issue:
http://osmose.openstreetmap.fr/en/map/#zoom=9&lat=50.825&lon=4.784&item=3032&level=1&tags=&fixable=

**Comment by jocelynj** [comment]
One of the backend wasn't correctly updated with the update script :(
I've just forced an update, and will add this backend in the script.
