### ISSUE TITLE
highway=elevator and railway=subway_entrance should be compatible

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osmose-backend#335]
Hey,
In my opinion **highway=elevator** and **railway=subway_entrance** on the same node shouldn't create a warning.
This is reported by [Error 4030](https://wiki.openstreetmap.org/wiki/FR:Osmose/issues#4030)
and you'll find an example on this node https://www.openstreetmap.org/node/1272604556 (issue not closed) and https://www.openstreetmap.org/node/5498737416 (I reported this issue as a positive false).

A subway entrance, even if it's not explicitly specified on the wiki (https://wiki.openstreetmap.org/wiki/Tag:railway%3Dsubway_entrance) can definitely be an elevator as much as steps or an entrance of a building. In my point of view it's a very normal way to tag this object.

I mapped several entrances in Paris's area (cf. https://overpass-turbo.eu/s/Cjy) and I intent to map more of them.

Could you please explain if necessary the reasons behind this warning?
Thanks

**Comment by frodrigo** [comment]
By default highway + railway raise a warning.
I whitelisted your case.

**Comment by overflorian** [comment]
that's great, thanks Fred

**Comment by frodrigo** [comment]
We have the code. Please wait for it to be in use.

**Comment by frodrigo** [comment]
Should be OK, please reopen if not.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=4030&class=900

**Comment by overflorian** [comment]
Very cool, thanks Fred
