### ISSUE TITLE
Why: "Unconnected cycleway"?

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#337]
Why: "Unconnected cycleway"?

Bicycle routing is oké: verified in three different directions (and reverse):
- Milandweg - Milandweg
- Milandweg - Toegang
- Milandweg - Oude Meije

I don't understand:
- No unconnected highway segments or nodes;
- No duplicated highway segment;
- No highway type change;
- JOSM validation does not find any errors or warnings.

And this is just one example... I have seen more.

source | 5069
-- | --
item | 1210
class | 1
subclass | 0
elems | way137821865
lat lon | 52.1372778 4.8617855

![image](https://user-images.githubusercontent.com/20150550/46278309-1259a100-c566-11e8-99b4-773ae7c3ea46.png)

![image](https://user-images.githubusercontent.com/20150550/46279047-551c7880-c568-11e8-9247-f80da6496573.png)

**Comment by frodrigo** [comment]
No major change after the extract rebuilt. Way and see a bit more.
http://osmose.openstreetmap.fr/fr/errors/graph.png?country=netherlands_*&item=1210&level=1%2C2%2C3&class=1

**Comment by frodrigo** [comment]
The issue is really solved in the data. Waiting for recompute and update.

**Comment by frodrigo** [comment]
@jocelynj need to clean the extract on the backend server to fetch new ones ?

**Comment by jocelynj** [comment]
For the moment, only the following extracts were generated with completeWays:
  - south-america
  - central-america
  - russia

I'm launching the remaining continents.

And you're right that we will have to remove all extracts and diffs from osmose backends.

**Comment by frodrigo** [comment]
@jocelynj All extract have now be rebuilt ?

**Comment by frodrigo** [comment]
Now all extracts have been regenerated, and all Osmose backend copy cleaned.
