### ISSUE TITLE
False positive: Small highway group apart from the main network or with insufficient access upstream 

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#339]
"Small highway group apart from the main network or with insufficient access upstream" is a correct warning for non-routable highways.
Keep Right: "This way is not connected to the rest of the map".

But in case of an island this is a very incorrect warning. All highways on an island are having a false positive!
By the way: the island does have - routable - access by ferry boat!

source | 32960
-- | --
item | 1210
class | 4
subclass | 1
elems | way52078916
lat lon | 53.2929223 5.0462114
title | Small highway group apart from the main network or with insufficient access upstream

![image](https://user-images.githubusercontent.com/20150550/46311478-9f324800-c5c2-11e8-94ed-75c20c4720d3.png)

![image](https://user-images.githubusercontent.com/20150550/46311514-c1c46100-c5c2-11e8-9e11-41c8859831db.png)

**Comment by frodrigo** [comment]
Pier and ferries are already considered
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_floating_islands.py#L34-L35

Need futher analyse to debug this.

**Comment by frodrigo** [comment]
Fixed (data update still in progress, but will finish tomorrow)
