### ISSUE TITLE
False positive: Unconnected way

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#340]
False positive: Unconnected way

These ways are connected to the map. Therefore not: "Unconnected way(s)".
All ways have [access=no]. Which is not 100% correct. More correct would be: [access=private] (farmland).
However: even [access=no] does not imply "Unconnected way".

source | 32963
-- | --
item | 1210
class | 4
subclass | 1
elems | way232671107
lat lon | 52.1673654 4.8852185
title | Small highway group apart from the main network or with insufficient access upstream

![image](https://user-images.githubusercontent.com/20150550/46312379-313b5000-c5c5-11e8-8103-524ca896c5d7.png)

**Comment by frodrigo** [comment]
duplicate #339
