### ISSUE TITLE
False Positive: Unconnected way ?

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#341]
False Positive: "Unconnected way" ?

Why is this bridge considered to be an unconnected way?
And why is a similar (almost identical) bridge not considered to be an unconnected way?

IMO: too many false positives are making this validation rather useless and polluting.

source | 5069
-- | --
item | 1210
class | 2
subclass | 0
elems | way7352878
lat lon | 52.0694200 4.8442000
title | Unconnected way

![image](https://user-images.githubusercontent.com/20150550/46336526-5b275d80-c62b-11e8-92a5-e162ab6069b2.png)

**Comment by frodrigo** [comment]
duplicate #337 same as cycleway
