### ISSUE TITLE
Too many false positives: Small highway group apart from the main network or with insufficient access upstream

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#342]
False positives: Small highway group apart from the main network or with insufficient access upstream
All warnings are having "High severity".

These false positives are "blurring" the real issues.

All ways are:
- [highway=service], [service=driveway]
- dead-end ways
- access to private property (residential houses)
- connected to the main network
- sufficient access upstream

source | 32963
-- | --
item | 1210
class | 4
subclass | 1
elems | way570552526
lat lon | 52.2276934 4.9229803
title | Small highway group apart from the main network or with insufficient access upstream

![image](https://user-images.githubusercontent.com/20150550/46349327-fdf2d280-c651-11e8-8c33-450497beff82.png)

**Comment by frodrigo** [comment]
duplicate #339

**Comment by osmtools** [comment]
@frodrigo is this really fixed with #339? i just get a warning for [this](http://osmose.openstreetmap.fr/de/error/24622116396) way, which fit to that described above (private dead-end driveway to a house)

**Comment by frodrigo** [comment]
Yes, something is wrong, I only see false positives.

**Comment by frodrigo** [comment]
I look closer, and now I see no issue with it. Can you point me problems, please ?
