### ISSUE TITLE
false positive on "Pharmacie without ref:FR:FINESS"

### ISSUE THREAD

**Issue by bmillemathias** [osm-fr/osmose-backend#347]
I got false positive errors "Pharmacie without ref:FR:FINESS" where the pharmacy has actually a ref:FR:FINESS with the same ID than the one reported as missing.

example on the map 
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=43.619131&lon=6.973384&item=7150&level=3&tags=&fixable=

detail for a pharmacy
http://osmose.openstreetmap.fr/en/error/20356689907

**Comment by frodrigo** [comment]
We update this two days ago. And you are right, that bad!
Now we try to match the healthcare=laboratory from OpenData again OSM Pharmacie.

**Comment by frodrigo** [comment]
cc @vinber

**Comment by frodrigo** [comment]
Error in configuration found.

**Comment by frodrigo** [comment]
Data updated
