### ISSUE TITLE
osmose erronously wants ref:UAI for kindergarten [créche]

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#348]
Hello,

Osmose reports issues item=7070, class=2 « School without ref:UAI or invalid » like this one : 
http://osmose.openstreetmap.fr/fr/error/20360147524

This kindergarten really is a « crèche », not a school (« maternelle »), and thus does not have a ref:UAI.

Unless I’m wrong, « crèches » are tagged with amenity=kindergarten + kindergarten:FR=*
and « écoles maternelles » are tagged with  amenity=kindergarten + school:FR=maternelle. So, Osmose should not request  ref:UAI when object is tagged with kindergarten:FR=*.

cheers
~~
laurent

**Comment by frodrigo** [comment]
Duplicate #126
