### ISSUE TITLE
osmose complains about missing speed limit (from mapillary) where as road is already tagged

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#350]
issue: http://osmose.openstreetmap.fr/en/error/20270216537

message is: 
```
maxspeed=40 mph Traffic signs for max speed limit 40 mph observed around but not associated tags Observed on 2017-07-12 
```
Issues:
- The error message says "mph", but Canada uses "km/h".
- The road is already tagged with maxspeed = 40, so not sure there is anything to do here.

**Comment by frodrigo** [comment]
Canadian look like US mph traffic sign limit. So first, Mapillary is worng. Then, because of this mistake we add a filter on mph / hm/h per country. But you area is not yet updated with this new filter.

Please, just wait.

**Comment by matthewdarwin** [comment]
Yes, Canada and US generally use the same traffic signs, but Canada is metric.

**Comment by matthewdarwin** [comment]
It seems there are no speed limit errors at all now (Ottawa, Canada area).  I am suspicious that is is not correct, because I'm sure there are roads with speed limits which are not tagged yet.

**Comment by matthewdarwin** [comment]
See the speed limit sign in this area, for example.  https://www.mapillary.com/app/?lat=45.385520025465866&lng=-75.96733650810961&z=17.622865970063497&menu=false&signs=true  

OSMOSE doesn't show any errors, but there are no roads taggged with the speed limit.

http://osmose.openstreetmap.fr/en/map/#item=8300&country=canada_ontario&zoom=17&lat=45.385117&lon=-75.966908&level=1%2C2%2C3&tags=&fixable=

**Comment by matthewdarwin** [comment]
ok thanks... I will check it on Friday.

**Comment by boothym** [comment]
@frodrigo the opposite issue is occurring in the UK which uses mph, osmose seems to expect km/h.

**Comment by frodrigo** [comment]
Can you give me a link?
GB is already on the mph country list.

**Comment by boothym** [comment]
Hope the links work:

http://osmose.openstreetmap.fr/en/map/#item=8300&zoom=17&lat=56.052868&lon=-3.305641&level=1%2C2%2C3&tags=&fixable=

http://osmose.openstreetmap.fr/en/error/22220986164

**Comment by boothym** [comment]
@frodrigo Hi, the problem still exists for the UK, are you able to try and fix this issue? Thanks

http://osmose.openstreetmap.fr/en/map/#item=8300&zoom=13&lat=56.0635&lon=-3.4104&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
@boothym it's an other error. I open a new issue.
