### ISSUE TITLE
suspicious tag combination waterway=lock_gate together with bridge=yes... seems ok to me

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#354]
Re: error: http://osmose.openstreetmap.fr/en/api/0.2/error/20515247069

For this way: https://www.openstreetmap.org/way/265351179, it has:
waterway = lock_gate
bridge = yes

This seems correct, it is both a lock gate and a way to cross over as seen here: https://www.mapillary.com/app/?signs=true&lat=45.38399711249997&lng=-75.69995082888886&z=20&pKey=X9DqhOkBRh-GS3Enyh3tRg&focus=photo

How can we avoid this error systematically as we have a lot of locks which also serve a bridge to allow people to cross.  (Not all locks allow people to cross, only some of them)

**Comment by frodrigo** [comment]
Reopen if required.

**Comment by matthewdarwin** [comment]
The issue remains http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=45.38456&lon=-75.697212&item=xxxx&level=1%2C2&tags=&fixable=

http://osmose.openstreetmap.fr/en/error/20768752956

**Comment by frodrigo** [comment]
There other on the lock gate spot. Reopen if your think we also deals with the other.
