### ISSUE TITLE
traffic_signals:direction=forward/backward not fixable "online"

### ISSUE THREAD

**Issue by RedEmile** [osm-fr/osmose-backend#360]
Hi,
it's not useful to fix_edit any "traffic_signals:direction" online (osmose-editor). You can't decide whether it's "forward" or "backward" without knowing the direction of the OSM-way. For example, in JOSM you need to click on the way to get the direction first before making the decision.

2nd: Is it possible to get a list of all the "traffic_signals:direction" that has been added using the osmose editor (maybe with overpass?)? It would be useful to control whether there are now any wrong "traffic_signals:direction" caused by that problem.

**Comment by frodrigo** [comment]
The geometry display on marker click was added mainly to address this problem.
But the way geometry is still missing on the kind of issue report.

2/ I think its possible with overpass. I think the number of results object should be very close to 0.

**Comment by RedEmile** [comment]
Thanks for responding so quickly!

It's not a problem to have a marker on missing directions on traffic_signals, stop signs, etc. But currently you can't solve that ONLINE correctly. But that is what is suggested by Osmose.
So what I'd suggest: just disable "fixabe=online" in Osmose.

**Comment by zzptichka** [comment]
Would be great to solve this on frontend, i.e. add an overlay or a tile service that can show way directions. Saves a lot of time adding directions to all those stop signs from osmose rather than josm/id.

**Comment by RedEmile** [comment]
@ zzptichka: what you propose would be even better.

**Comment by frodrigo** [comment]
![image](https://user-images.githubusercontent.com/1785486/48097100-34a3a600-e219-11e8-97b6-3c2a02b3b32a.png)

**Comment by zzptichka** [comment]
Is this feature live planet-wide?
For some reason it's still highlighted with red node[in Canada](http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.347464&lon=-75.830636&item=2090%2C8300&level=1%2C2&tags=&fixable=)
While appearing properly with green node+way [in Belgium for example](http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=50.85124&lon=4.279142&item=2090%2C8300&level=1%2C2&tags=&fixable=)

**Comment by frodrigo** [comment]
Yes, it will be available world wide.
In the the popup you can get the date of update. Is not the same for Canada and Belgium.
Actually we are facing to issue and lag on data update. We are encountering problems with with some of the analyser servers.
http://buildbot.osmose.openstreetmap.fr/grid

**Comment by matthewdarwin** [comment]
@frodrigo do you need more server capacity?  I would like to see canada_* updated more often.  I have some spare sever capacity here.

**Comment by frodrigo** [comment]
@matthewdarwin one or more vm would help us a lot right now. The minimum configuration per vm is about 4 GB of RAM, 50 GB of hard disk space (ideally ssd, double if possible), 1 cpu core/vm. Thank.
