### ISSUE TITLE
Allow footway=sidewalk with highway=construction, construction=footway

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#361]
http://osmose.openstreetmap.fr/en/error/20615638428

https://www.openstreetmap.org/way/635795332#map=19/50.07256/19.91756

source | 8420
-- | --
item | 2080
class | 20805
subclass | 0
elems | way635795332

**Comment by frodrigo** [comment]
It's now OK for you ?

**Comment by matkoniecz** [comment]
Should be ok based on what I see in code, I will report a new issue if that will turn out to be buggy
