### ISSUE TITLE
"oneway=yes together with lanes:backward" should not be reported for ways with oneway:psv=no 

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#363]
http://osmose.openstreetmap.fr/en/error/20615629155

source | 8420
-- | --
item | 9001
class | 9001002
subclass | 1742397708
elems | way364784222

https://www.openstreetmap.org/way/364784222

**Comment by frodrigo** [comment]
From JOSM, rule already removed.
This issue will go away with the upcoming MapCSS code update.
