### ISSUE TITLE
"Missing access to parking" for parking with access=yes tag

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#366]
source | 15435
-- | --
item | 3161
class | 2
subclass | 0
elems | way589419765

https://www.openstreetmap.org/way/589419765

access is tagged, according to osmose itself - why it complains?

**Comment by deuzeffe** [comment]
Need access way (such as highway=service or tertiary) I guess.

**Comment by frodrigo** [comment]
Missing access to parking --> Missing highway to parking
