### ISSUE TITLE
"Opposite or opposite lane in the same way of the oneway" is unclear

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#368]
I have no idea what is supposed to be fixed

source | 8420
-- | --
item | 2030
class | 20302

cycleway:right | opposite |  
-- | -- | --
highway | residential |  
lit | yes |  
maxspeed | 30 |  
maxspeed:type | PL:zone30 |  
name | Zarzecze |  
oneway | yes |  
oneway:bicycle | no |  
surface | asphalt

https://www.openstreetmap.org/way/530037103

**Comment by frodrigo** [comment]
Opposite have no side. It's global street property.
Maybe that mean `cycleway:right=opposite_lane` (or not)?
https://wiki.openstreetmap.org/wiki/Key:cycleway

**Comment by matkoniecz** [comment]
It is street oneway for cars, two-way for cyclists, without a separate bicycle lane, with bicycle markings on the right side of the road.

Also, cyclists can use one side of the road only so I would not treat it as wrong.  Given that in addition iD strongly encourages to use `cycleway:right` or `cycleway:left` I prefer to focus on things that are clearly wrong.

**Comment by matkoniecz** [comment]
Though it should be `cycleway:left=opposite` (or `cycleway=opposite`) what I fixed now.

**Comment by frodrigo** [comment]
cc @monsieuraa
