### ISSUE TITLE
reduce " Possible missing traffic_signals:direction tag or crossing on traffic signals " to the lowest priority

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#371]
It is not really important information (it is quite rare to have crossing or junction where some ways have traffic lights and some not - so for routing it is OK to just double count traffic lights). In addition, it is highly obnoxious to map.

I suggest to lower its importance to the lowest possible.

source | 26997
-- | --
item | 2090
class | 3
subclass | 0
elems | node2420286406

http://osmose.openstreetmap.fr/en/error/20615959379

EDIT: it seems that it requires change like https://github.com/frodrigo/osmose-backend/commit/72736b90f8c462e56ac2095e0938611fbd961079

**Comment by frodrigo** [comment]
No, it's not OK to double count the traffic lights.
It's because it's have real impact on routing and can make ugly result, that why this check have been created.

**Comment by matkoniecz** [comment]
But is it really deserving its current priority?
