### ISSUE TITLE
Missing access way to parking reported for correctly tagged parkings

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#372]
source | 15435
-- | --
item | 3161
class | 2
subclass | 0
elems | way589419765

https://www.openstreetmap.org/way/589419765

access is tagged, according to osmose itself - why it complains?

What is wrong with areas like https://www.openstreetmap.org/way/589419765 that are small parkings along a way and there is no road going through them?

Maybe it should be reported only for large parking areas? Or disabled in Poland?

**Comment by frodrigo** [comment]
A way must touch the parking.

Note: please remove the default place holder test when you create an issue.

**Comment by matkoniecz** [comment]
> A way must touch the parking.

So how https://www.openstreetmap.org/way/589419765 should be tagged? Parking area is tagged correctly, centerline of road is tagged correctly, there is no separate service road with access.

Can I propose filtering out small parking areas from this rule?

Maybe accept also `area:highway` area touching parking area? I am not fan of this level of micromapping, but at least it would not be wrong unlike say

![selection_002](https://user-images.githubusercontent.com/899988/47486850-90e1ef80-d841-11e8-90f7-10c09b9b035d.png)


> Note: please remove the default place holder test when you create an issue.

I have an idea how to permanently fix this issue. See #373

**Comment by deuzeffe** [comment]
Parking or parking_lane ?

**Comment by matkoniecz** [comment]
From quick look at https://wiki.openstreetmap.org/wiki/Key:parking:lane it seems to be for "Cars parking on the street", not sure whatever it applies also to parkings near street.

And anyway mapping as areas is popular in Poland - see for example capital https://www.openstreetmap.org/#map=19/52.22646/21.00986

**Comment by deuzeffe** [comment]
Imho, parking_lane tag is perfectly designated to parking "near" street ie park places without way between street and place. A contrario, amenity=parking tag is adapted to a surface with an access way needed. It's just my (humble) opinion.
