### ISSUE TITLE
ref:UAI website for item 7070 cl 101, item 8030 cl 100, item 8031 cl 102, item 8032 cl103

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#374]
Hello,
All classes are about "Enseignement sup." (college or university), ok. 

In the popup, the ref:UAI is linked with directory for first and secondary schools (eg http://www.education.gouv.fr/pid24302/annuaire-resultat-recherche.html?lycee_name=0870992F). It should be linked with college/university directory; unfortunately, I only know this search engine : http://www.education.gouv.fr/acce_public/index.php witch browses all the educational DB. 

It's ok that the issue is NOT about analysis itself (analyser_merge_college_FR.py seems ok) but ONLY the link of ref:UAI in the popup. 

Maybe you have to reconsider the item classif. for ens. sup. (a separate item ?) ? I don't know. Sorry if I do you more work :((

**Comment by deuzeffe** [comment]
oooooops, sorry for the wrong repository :(

**Comment by frodrigo** [comment]
Reopen if required.
