### ISSUE TITLE
False positive "Number twice in the street" ?

### ISSUE THREAD

**Issue by arnaud-jacquemin** [osm-fr/osmose-backend#376]
Hello,

I don't understand some "_Number twice in the street_" errors, because I don't find where the duplicates are...

source | 698
-- | --
item | 2060
class | 6
subclass | 1

The error message is : _Multiple numbers "_X_" in way "Cité Saint-Éloi"_

https://osmose.openstreetmap.fr/fr/error/20651754170
elems | node3150289780

https://osmose.openstreetmap.fr/fr/error/20651754175
elems | node3150289782

https://osmose.openstreetmap.fr/fr/error/20651754180
elems | node3150289784

https://osmose.openstreetmap.fr/fr/error/20651754168
elems | node3150289778

https://osmose.openstreetmap.fr/fr/error/20651754173
elems | node3150289781

https://osmose.openstreetmap.fr/fr/error/20651754177
elems | node3150289783

They all show up there : https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.641485&lon=3.022066

Are they false positive, or am I missing something ?

Thanks in advance

**Comment by frodrigo** [comment]
There is an other street with the same name in the neighbourhood :
https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=50.64143%2C3.02195%3B50.64063%2C3.02406#map=18/50.64073/3.02359

**Comment by arnaud-jacquemin** [comment]
Thank you very much @frodrigo !
I didn't know that other street... I will do a survey to check if it really has the same name. If it were true, it would be a mess for the postman!
Maybe this is a question for the frontend... but shouldn't Osmose highlight the second street, so the contributor can understand the problem?

**Comment by frodrigo** [comment]
Reopen if required.
