### ISSUE TITLE
mapillary signs: roundabout detection is not working properly? Is the sign not close enough to the actual roundabout?

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#377]
item 8300
There are several examples in Ottawa, Canada where there are roundabouts, and mapillary sign detection for roundabouts and also a warning from OSMOSE that there is not a roundabout.  See here for several examples of it.

http://osmose.openstreetmap.fr/en/map/#zoom=16&lat=45.26942&lon=-75.8921&item=8300&level=1%2C2&tags=&fixable=
Also here:
http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=45.300825&lon=-75.930656&item=8300&level=1%2C2&tags=&fixable=

Not sure if this is related to https://github.com/osm-fr/osmose-backend/issues/359

**Comment by frodrigo** [comment]
Yes, it seem related to the change for #359
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=8300&class=32&start_date=2018-10

The conflation distance is 500m:
https://github.com/frodrigo/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json#L588
