### ISSUE TITLE
Traffic signs: maxspeed false positives

### ISSUE THREAD

**Issue by zzptichka** [osm-fr/osmose-backend#378]
Osmose says maxspeed=80 tag is missing, even though the sign was detected right next to the road with maxspeed=80: 
http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=45.317908&lon=-75.785891&item=8300&level=1%2C2&tags=&fixable=
Possibly related to #377?

Other similar warnings: http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=45.32303&lon=-75.771418&item=8300&level=1%2C2&tags=&fixable=
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.292473&lon=-75.744355&item=8300&level=1%2C2&tags=&fixable=

**Comment by frodrigo** [comment]
You are right. The issue is more extended than I expected.

**Comment by zzptichka** [comment]
Looks like this warning blew up again with false positives everywhere. Example (all these roads have correct maxspeed tag): http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=45.343688&lon=-75.83091&item=8300&level=1%2C2&tags=&fixable=

**Comment by frodrigo** [comment]
The previous fix was not good, and mix north America speed limit traffic sign with mile limit.

We setup a new fix yesterday.

This time it's configuration issue with: `maxspeed = 40{speed_limit_unit}`, the speed unit replacement is missing.

**Comment by frodrigo** [comment]
Ok. Now it's good.
