### ISSUE TITLE
Object tagged twice - Stop using bbox

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#379]
item=4080 "Object tagged twice"
Stop using bbox

**Comment by Marc-marc-marc** [comment]
I also find too many false positives. maybe it's better to begging with the additional criterion node-in-polygon.
sport field also it a too high false positive rate (a sport=table_tennis field mapped with a node near another field mapped as a polygon)

**Comment by frodrigo** [comment]
Please, wait for the integration of this fix before.

**Comment by frodrigo** [comment]
@Marc-marc-marc Updated for Switzerland
