### ISSUE TITLE
Feature request: Mapillary Objects 

### ISSUE THREAD

**Issue by zzptichka** [osm-fr/osmose-backend#380]
In addition to traffic signs, Mapillary offers some [objects as well!](https://www.mapillary.com/developer/api-documentation/#segmentations)
Among those interesting for adding to OSM are 
* construction--structure--tunnel
* construction--flat--crosswalk-plain
* construction--structure--bridge
* object--bench
* object--bike-rack
* object--fire-hydrant
* object--parking-meter
* object--traffic-light--xxx
* object--trash-can

Are there plans to add those to Osmose?

**Comment by frodrigo** [comment]
Sure. But let make the traffic signs part fully working before.

**Comment by zzptichka** [comment]
Good to see this feature getting traction.  
When can we expect for the warnings to go pop up?

**Comment by frodrigo** [comment]
Result are already here, but this item is still hidden as adjustments ( 522013307213202d3d5263b9a1f9c6c5c4aabfb1 ) need to be deployed.
http://osmose.openstreetmap.fr/en/errors/?item=8360&useDevItem=all

Nevertheless feedback is welcome.

**Comment by zzptichka** [comment]
Is it possible to see these errors on the map already? Or it needs to be deployed first? If so, when? Thanks.

**Comment by frodrigo** [comment]
Just clikc on map in the bar menu.

**Comment by zzptichka** [comment]
Noticed that Mapillary detects railway crossing light as "Traffic light - Other" which leads to false positives for this analyser. [Example](https://www.mapillary.com/app/?focus=photo&pKey=mkZfbThYuzQrI22pj-dpTA&signs=true&points=true).
Possible solutions in this case:
- In addition to `highway=traffic_light` also check for nodes with `crossing:light=yes` nearby.
- Exclude "Traffic light - Other" from detection.
- The best solution would be to make it a separate error that would check if there is `railway=crossing` or `railway=level_crossing` nearby and if there is no `crossing:light=yes` offer to add it.

**Comment by frodrigo** [comment]
`crossing:light=yes` was added few hours ago.
The imagery detection is fuzzy, I prefer keep the all traffic-light in the same group.
