### ISSUE TITLE
Conflict between tags: amenity, highway for sheltered bus stop

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#382]
I would not tag it this way, but IMHO this tagging is not invalid

source | 8420
-- | --
item | 4030
class | 900
subclass | 1
elems | way601071397
lat lon | 50.0882809 19.9473166

https://www.openstreetmap.org/way/601071397

**Comment by frodrigo** [comment]
@nlehuby what do you think about this ?

**Comment by nlehuby** [comment]
I would not map it that way either!

**Comment by frodrigo** [comment]
Please reopen if required.

**Comment by matkoniecz** [comment]
So you think that this tagging style is unacceptable and should never be used? And that I should remove amenity=shelter from https://www.openstreetmap.org/way/601071397 ?
