### ISSUE TITLE
Docker/Documentation: typo in URL_FRONTEND template in docker-compose.yml

### ISSUE THREAD

**Issue by allier-osm** [osm-fr/osmose-backend#386]
In docker-compose.yml, the template for ```URL_FRONTEND``` is currently:

https://github.com/osm-fr/osmose-backend/blob/95a62ff861e6a7e59afd84860e6b271a6973dc42/docker/docker-compose.yml#L22

The template should be:
```
URL_FRONTEND=frontend:20009
```
(no protocol, no trailing slash)

(Note: the template for ```URL_FRONTEND_UPDATE``` is correct)

**Comment by frodrigo** [comment]
You are right, can you make a pull request, please?

**Comment by allier-osm** [comment]
Sure. I have found other typos: do you prefer separate issues for each, or everything gathered under this issue?

**Comment by frodrigo** [comment]
Group them under the same PR.

**Comment by allier-osm** [comment]
OK, I assume you meant several GitHub issues and one single PR.

**Comment by allier-osm** [comment]
Actually ```URL_FRONTEND=frontend:20009``` does not allow for accessing the application from the host, since ```frontend``` is the hostname on the internal virtual network created by Docker.
It probably makes more sense to set:
```URL_FRONTEND=localhost:20009```
since the most likely use case is to test the web application from the host.
