### ISSUE TITLE
"Almost junction, join or use noexit tag" false positives related to highway=construction

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#391]
source | 27998
-- | --
item | 1270
class | 1
subclass | 0
elems | node264111775_way24346224
lat lon | 50.0767759 19.9429179

Maybe highway=construction also should be considered as a road in this check? Or at least exclude cases where road continues as highway=construction?

**Comment by frodrigo** [comment]
It's technically doable. But I will not, it's require many changes on all other analysers dealing with highways.
Please, just mark it as false positive.

**Comment by hungerburg** [comment]
Been marked as false positive, issue comes up again the next day - eg http://osmose.openstreetmap.fr/en/error/15ef5978-fcee-8cc6-645d-bdba0c350330 - its an underground corridor that connects two tunnels, which will be under construction for five more years at least

**Comment by frodrigo** [comment]
The unicity of issue and stable id is a work in progress.

**Comment by hungerburg** [comment]
@frodrigo Thank you, good to know

**Comment by frodrigo** [comment]
Should be fixed now.

**Comment by hungerburg** [comment]
I gave it a try.
