### ISSUE TITLE
swimming_pool confusions

### ISSUE THREAD

**Issue by nlehuby** [osm-fr/osmose-backend#394]
We need to create some analyser on `leisure=swimming_pool` that may be instead `leisure=sports_centre + sport=swimming`: this is a very common tag confusion.

Here are a few criteria to check (overpass) :
```
nwr["leisure"="swimming_pool"][website](area.searchArea);
nwr["leisure"="swimming_pool"]["contact:website"](area.searchArea);
nwr["leisure"="swimming_pool"][url](area.searchArea);
nwr["leisure"="swimming_pool"]["contact:url"](area.searchArea);
nwr["leisure"="swimming_pool"][phone](area.searchArea);
nwr["leisure"="swimming_pool"]["contact:phone"](area.searchArea);
nwr["leisure"="swimming_pool"][wikipedia](area.searchArea);
nwr["leisure"="swimming_pool"][name](area.searchArea);
nwr["leisure"="swimming_pool"][building=yes](area.searchArea);
```

Should we have a sax or a mapcss analysis to check these ?

**Comment by frodrigo** [comment]
Since it require spatial analysis it can only be done with SQL.

**Comment by nlehuby** [comment]
ok, i've created the [mapcss ruleset](https://josm.openstreetmap.de/wiki/Rules/SuspisciousSwimming_Pool). What should I do now to have these tests in Osmose ?

**Comment by frodrigo** [comment]
In place of node + way + relation your can use *.
You can group all rules with same results.

To need to add osmose attributes, look at mapcss files in osmose backend.

**Comment by frodrigo** [comment]
I made a part of the changes on the wiki.

**Comment by nlehuby** [comment]
I've added a few `assertMatch` and `assertNoMatch`. Is there any Osmose attributes needed ?

**Comment by frodrigo** [comment]
I add
```mapcss
        osmoseItemClassLevel: "3080/30801/2";
        osmoseTags: list("tag", "fix:chair");
```
It is required to set the result somewhere in the item menu.

The group attribute is not required anymore. You should merge it with throwWarning.

**Comment by nlehuby** [comment]
Can you please give me an example of mapcss file where these attributes are used ?

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Bicycle.validator.mapcss
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Power.validator.mapcss

**Comment by nlehuby** [comment]
If I add these osmose attributes, the mapcss file does not load in JOSM anymore.
Do I need to maintain two separate versions of the analysis, one for JOSM and the other one for Osmose ?

**Comment by frodrigo** [comment]
You are right, it's not working.

**Comment by frodrigo** [comment]
https://josm.openstreetmap.de/ticket/17053#ticket

**Comment by nlehuby** [comment]
Any updates on this topic ?

**Comment by frodrigo** [comment]
We are waiting for the next JOSM release (>14481) to add again the Osmose part.

**Comment by nlehuby** [comment]
I've updated the wiki to add the osmose metadata in the ruleset.

**Comment by nlehuby** [comment]
Any update on this ? What is the process to use the mapcss from the wiki in Osmose ?

**Comment by frodrigo** [comment]
Still need to be integrated.
The goal is to reuse the rules in JOSM and Osmose (and others).

We are are now porting Osmose from python2 to 3. So I avoid adding feature during the process.

**Comment by frodrigo** [comment]
Jocelynj reported a typo Suspi**s**cious -> Suspicious. I fix the content of the page https://josm.openstreetmap.de/wiki/Rules/SuspisciousSwimming_Pool
But the page still need to be renamed.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#item=&class=30811&useDevItem=all

**Comment by nlehuby** [comment]
:+1:

**Comment by frodrigo** [comment]
After 5 month, here we are! It's publicly active on Osmose:
http://osmose.openstreetmap.fr/en/errors/?item=3080&class=30801

**Comment by nlehuby** [comment]
:tada: 

Thanks!
