### ISSUE TITLE
Question: lanes check - wrong tagging or false positive?

### ISSUE THREAD

**Issue by majkaz** [osm-fr/osmose-backend#395]
Not sure where the error comes from for error [nr. 20909067052](http://osmose.openstreetmap.fr/cs/error/20909067052). How it looks [on the ground](https://mapy.cz/zakladni?x=14.4917153&y=48.9781341&z=18&pano=1&pid=57158401&yaw=4.706&fov=0.607&pitch=0.073).

IMHO, the [bus:lanes](https://wiki.openstreetmap.org/wiki/Bus_lanes#The_bus:lanes.3D.2A_scheme) schema is valid tagging. It seems that the check is ignoring this and forcing the lanes:psv schema - at least this seams to be the reason for the error.

**Comment by frodrigo** [comment]
Reopen if required with more details.
