### ISSUE TITLE
Some checks on Persian values

### ISSUE THREAD

**Issue by iriman** [osm-fr/osmose-backend#398]
Inside boundary of Iran we use "name" tag for Persian names.
Outside Iran we use suffix ":fa" for tagging Persian values.

There are two common errors that are raised by some users who are using Arabic keyboard instead of Persian keyboard:

- Using "ي" ARABIC LETTER YEH (U+064A), which should be replaced by "ی" ARABIC LETTER FARSI YEH (U+06CC).
- Using "ك" ARABIC LETTER KAF (U+0643), which should be replaced by "ک" ARABIC LETTER KEHEH (U+06A9).

An example node: https://www.openstreetmap.org/node/5855735186

There may be some traps like someone writes Arabic name in Persian tag which can be mentioned on wiki help.

thanks

**Comment by frodrigo** [comment]
Results are now available
http://osmose.openstreetmap.fr/fa/errors/?source=22034&item=5010&class=50109001
It's OK for you ?

**Comment by iriman** [comment]
Yes, thanks a lot. 

one tiny thing: Please replace the main title of issue with something like "Arabic letter detected in Farsi name". Curently it always says "In Farsi, the Arabic letter 'ك' should be replaced by 'ک'"

**Comment by frodrigo** [comment]
Ok. Title will be fixed o next data update.
