### ISSUE TITLE
Remplacement of man_made=MDF with telecom=exchange

### ISSUE THREAD

**Issue by gustavecha** [osm-fr/osmose-backend#400]
Hi,

Recently telecom=exchange was reviewed and adopted to map telephone exchanges places.
There about 7k of man_made=MDF objects that should be carefully retagged.
https://taginfo.openstreetmap.org/search?q=man_made%3DMDF

Is this possible to add this tag to a "to be replaced" analysis and propose to replace it with telecom=exchange please?

Thanks in avance

**Comment by frodrigo** [comment]
It's deprecated as it can be added into: https://wiki.openstreetmap.org/wiki/Deprecated_features
Osmose use this wiki page.

**Comment by gustavecha** [comment]
Nice, thank you

I've update the deprecated template
