### ISSUE TITLE
No updates are reported as errors (code 4)

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#402]
My backend instance often fails due to OSM extracts not being updated and so no updated data delivered to the frontend.
This makes it failing with error code 4 in case a single analyzer could not send fresh data.

https://github.com/osm-fr/osmose-backend/blob/master/osmose_run.py#L292

As I monitor my instance with Zabbix I get an alert for every country/state where this fails. Often these sum up to over hundred alerts.
These seriously clutter the monitoring system and make it hard to distinguish these from real problems.

I suggest to turn this into a warning and not returning an error for it.

What needs to be discussed is how a situation could be detected where extracts gone stale and do not update at all for a longer time.
Using the error code 4 for this purpose sounds wrong, so the monitoring for stale data updates should be done separate of this.
Would it be possible to provide the "delay" of a single country by API? then I could monitor that and again warn if it exceeds a threshold.

I am going to push some changes to frontend/backend to implement the warning handling. Please comment on it.

**Comment by frodrigo** [comment]
We now have this in the frontend API:
https://github.com/osm-fr/osmose-frontend/blob/master/control.py#L294
The idea in the backend is to get the timestamp before running the analysis, and if there will be something to update, then run the analysis. But this is still not done.

**Comment by stephankn** [comment]
This sounds then like a suitable interface to check for stalled processing.

How about changing the current FAIL into a WARNING as proposed in my PR above? So osmose_run will no longer report an error is such situations?

**Comment by frodrigo** [comment]
3fdac9144d4136bbeee4b8c1d36344f21f9cda46
ab2bda1ae5b058f2689d24e44ba64ae07cb7ef5e
Does not report error if "FAIL: Already up to date" happen after a timeout.

**Comment by frodrigo** [comment]
Now it's OK.
