### ISSUE TITLE
calling git describe on non-git directory in Docker

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#404]
osmose_run.py tries to call `git describe`. This is useless since osmose-backend inside Docker is no git repository. This folder is explicitly excluded from being added (see `.dockerignore`).

https://github.com/osm-fr/osmose-backend/blob/master/osmose_run.py#L68

**Comment by frodrigo** [comment]
The idea is to mount the source code as a volume and got back .git again. Mounting the source avoid to rebuild the image at each update.
BTW, I have a branch changing most on the Docker part : https://github.com/frodrigo/osmose-backend/commits/docker

**Comment by stephankn** [comment]
Uh, sounds complicated. Why not simply passing in the `git describe` value as an ARG to later assign this to ENV inside docker? Sounds much cleaner than importing sources into the image and running git inside the container.
Versions will not change after the image was created. So no need to determine the version multiple times.

**Comment by jocelynj** [comment]
In fact, we might need two versions:
  - the one from origin/master
  - the one from HEAD

This is because HEAD might not be up-to-date with origin/master.

**Comment by frodrigo** [comment]
Now, It's OK for you? Can we close this?
