### ISSUE TITLE
stop considering shop=wine as invalid

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#410]
Proposed change `tag value: shop=wine => shop=alcohol ` is harmful as it removes information what kind of alcohol is sold at a given shop.

Also, in addition wine selling shop are sufficiently popular that there is no good justification for trying to eradicate this tag.

**Comment by frodrigo** [comment]
You are right. I dislike this rule too.
I removed it from https://wiki.openstreetmap.org/wiki/User:FrViPofm/TagwatchCleaner
It will be updated on next cache update.
