### ISSUE TITLE
"Intersection of unrelated highway and waterway objects" reported for valid data

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#416]
http://osmose.openstreetmap.fr/en/error/21257925520

source | 15830
-- | --
item | 1250
class | 2
subclass | 0
elems | way26536195_way26534617
lat lon | 50.1074565 19.9458172

I see nothing really wrong with https://www.openstreetmap.org/way/26536195

**Comment by frodrigo** [comment]
Bad support of ford on way.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.107389&lon=19.946314&item=xxxx&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
Clearly the fix does not work.

**Comment by frodrigo** [comment]
The backend computing the Poland is not up to date, still running old rules.

**Comment by frodrigo** [comment]
:tada: It's done!
