### ISSUE TITLE
Djibouti locale analysis

### ISSUE THREAD

**Issue by roptat** [osm-fr/osmose-backend#425]
Hi,

Here I am again with some issues with locales in Djibouti :)

This time, I have a specific issue with this marker: http://osmose.openstreetmap.fr/en/error/21573247156 (and similar in the area). According to the wiki, the multilingual name should have the format "<french> <arabic>" (with a space in between) except when the name contains a number, which is the case for "Avenue 17 / جادة 17", where the names should be separated by a forward slash.

Currently osmose reports those as:

```
The name tag contains two names
name=Avenue 17 / جادة 17
```

Thank you!

**Comment by frodrigo** [comment]
- "/" now allowed in name.
- Specific multilingual name support for Djibouti, allow and split on "/" support.
http://osmose.openstreetmap.fr/en/errors/?item=5030&class=705&country=djibouti
http://osmose.openstreetmap.fr/en/errors/?country=djibouti&item=5060&level=1%2C2%2C3
