### ISSUE TITLE
I don't understand this error

### ISSUE THREAD

**Issue by vinber** [osm-fr/osmose-backend#427]
http://osmose.openstreetmap.fr/fr/error/21738294272

17238 is the "ref insee" of Moings

and url of ref:insee is on Mérimée ?

**Comment by frodrigo** [comment]
clé | valeur
-- | --
source | 217
item | 6040
class | 801
subclass | 0
elems | node359869750
lat lon | 45.4794444 -0.3597222
en | INSEE code cannot be found in INSEE database
fr | Le code INSEE est introuvable dans la base de l’INSEE
subtitle | en17238 | en | 17238
en | 17238
timestamp | 2018-12-24 21:14:02



clé | valeur
-- | --
elem_index | 0
type id | N 359869750
tags | addr:postcode17500                 nameMoings                 placevillage                 population170                 ref:FR:SIREN211702386                 ref:INSEE17238http://www.culture.gouv.fr/public/mistral/merimee_fr?ACTION=CHERCHER&FIELD_1=cmer1&VALUE_1=17238                 source:populationINSEE 2013 | addr:postcode | 17500 |   | name | Moings |   | place | village |   | population | 170 |   | ref:FR:SIREN | 211702386 |   | ref:INSEE | 17238 | http://www.culture.gouv.fr/public/mistral/merimee_fr?ACTION=CHERCHER&FIELD_1=cmer1&VALUE_1=17238 | source:population | INSEE 2013 |  
addr:postcode | 17500 |  
name | Moings |  
place | village |  
population | 170 |  
ref:FR:SIREN | 211702386 |  
ref:INSEE | 17238 | http://www.culture.gouv.fr/public/mistral/merimee_fr?ACTION=CHERCHER&FIELD_1=cmer1&VALUE_1=17238
source:population | INSEE 2013 |  
username |

**Comment by frodrigo** [comment]
It come from a match with this rule:
https://github.com/osm-fr/osmose-frontend/blob/master/tools/tag2link_sources.xml#L141
There is more rules to match here:
https://github.com/osm-fr/osmose-frontend/blob/master/tools/tag2link_sources.xml#L88
but in Osmose keep only one to build the link.
Note, the Mérimée link list Monuments of the Municipality.
