### ISSUE TITLE
ref swisstopo:SHN

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#429]
En cas d'erreur “ref” manquant pour la municipalité : swisstopo:SHN", proposer l'ajout du tag swisstopo:SHN qui se construit de la manière suivante : 
le code pays "CH" + la valeur de la clef swisstopo:BEZIRKSNUM + la valeur de la clef swisstopo:BFS_NUMMER
peut-être faudrait-il aussi rétrograder cette anomalie en niveau 2 voir 3 car sans réelle conséquence pratique

**Comment by frodrigo** [comment]
Check for the two keys.

http://osmose.openstreetmap.fr/fr/errors/?country=switzerland&item=7120&class=3

**Comment by frodrigo** [comment]
OK. Works. But the issue title is wrong: "Missing municipality ref ine:municipio".

**Comment by frodrigo** [comment]
Now is `ref:ISTAT`, like random ref taken form config.
