### ISSUE TITLE
also check maxspeed:forward

### ISSUE THREAD

**Issue by elgaard** [osm-fr/osmose-backend#430]

**Comment by operon** [comment]
For maxspeed test, check also maxspeed: ...
Example maxspeed: trailer or maxspeed: conditional

**Comment by frodrigo** [comment]
`maxspeed:forward` and `maxspeed:backward` are already done but only on selected speed. I add it for all speed values.

I will not add, for now `maxspeed:trailer`, too few tags. `maxspeed:conditional` have variable value, and it's not supported.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=8300
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=8300&start_date=2019-03

**Comment by frodrigo** [comment]
Something go wrong. The graph should not go up.

**Comment by frodrigo** [comment]
I see nothing wrong with the actual state. Maybe linked to other update deployed at the same time that flush the cache.

Only France have this issue: http://osmose.openstreetmap.fr/fr/errors/graph.png?item=8300&start_date=2019-03&country=france*
Other country are right: http://osmose.openstreetmap.fr/fr/errors/graph.png?item=8300&start_date=2019-03&country=germany*
