### ISSUE TITLE
False positive in "Duplicated similar values" for explicitly tagged maxspeed in Poland

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#436]
Note: while maybe tagging `maxspeed=PL:rural` may be preferable this way is tagged correctly. Number of cases is ridiculous, but it is not fault of mapper.

http://osmose.openstreetmap.fr/en/error/22358635443

> Duplicated similar values maxspeed:hgv:forward:conditional=90 @ (weight<=3.5); 70 @ (weight>3.5)

This complaint is invalid and can not be solved.

**Comment by frodrigo** [comment]
It should be ok. Please reopen if not.
