### ISSUE TITLE
False positive "Discordant maxspeed and source:maxspeed" in Poland.

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#437]
Tagging that road has rural speed limit is done in many ways.

1. Explicit tagging of maxspeeds
1. Explicit tagging of maxspeeds and symbolic value `Pl:rural` in `source:maxspeed`
1. symbolic value `Pl:rural` in `maxspeed`
1. at least one more system

This is messy and hairy and there is plenty to complain but in http://osmose.openstreetmap.fr/en/error/22358635600 there is no valid reason to complain about "Discordant maxspeed and source:maxspeed"

highway | residential |  
lit | no |  
maxspeed | 90 |  
maxspeed:bus | 70 |  
maxspeed:hgv:conditional | 90 @ (weight<=3.5); 70 @ (weight>3.5) |  
maxspeed:trailer | 70 |  
noname | yes |  
source:maxspeed | PL:rural |  
surface | asphalt

**Comment by frodrigo** [comment]
In Osmose and OSRM the PL:rural is 100 (I make both).
- https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L293
- https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Maxspeed.py#L59
This is wrong, or the `PL:rural` mean multiples values ?

**Comment by matkoniecz** [comment]
Oh right, it is even worse.

https://pl.wikipedia.org/wiki/Wzory_znak%C3%B3w_i_sygna%C5%82%C3%B3w_drogowych_w_Polsce#/media/File:Znak_D-39._Ograniczenia_pr%C4%99dko%C5%9Bci_w_Polsce_od_2011.svg

`PL:rural` means maxspeed 90 for cases where there is single lane in one direction and road is not an express road.

`PL:rural` means maxspeed 100 for dual carriageway with multiple lanes

also `PL:rural` means maxspeed 100 for express roads that are not dual carriageways

See previous discussion in https://github.com/westnordost/StreetComplete/issues/1101

Also, search for "PL" in https://wiki.openstreetmap.org/wiki/Default_speed_limits that attempts to document this.


--------

For OSRM intepreting PL:rural as 100 is probably fine (is there a big difference between 90 and 100?)

For Osmose I would allow both 90 and 100.

Or allow 90 only where `oneway!=yes` and `motorroad!=yes` and 100 only where `oneway=yes` or `motorroad=yes`.

**Comment by frodrigo** [comment]
I can't handle the full complexity, but I can do this:
```
PL:urban = [50, 60]
PL:rural = [90, 100]
PL:trunk = [100, 120]
PL:motorway = [140]
```
It's ok for you?

**Comment by matkoniecz** [comment]
PL:urban should be always 50 (60 is during night 23:00 - 5:00 and handled with `maxspeed:conditional`).

```
PL:urban = [50]
PL:rural = [90, 100]
PL:trunk = [100, 120]
PL:motorway = [140]
```

will be OK

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=3032&class=303241&country=poland*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=3032&class=303241&country=poland*

**Comment by matkoniecz** [comment]
I get 
```
Traceback (most recent call last):
  File "/data/project/osmose/frontend/errors.py", line 136, in graph
    data = errors_graph.make_plt(db, options, format)
  File "/data/project/osmose/frontend/errors_graph.py", line 113, in make_plt
    return plot(data, text+' '+src, format)
  File "/data/project/osmose/frontend/errors_graph.py", line 146, in plot
    locator.refresh()
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/matplotlib/dates.py", line 1269, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/matplotlib/dates.py", line 1026, in viewlim_to_dt
    .format(vmin))
ValueError: view limit minimum -0.001 is less than 1 and is an invalid Matplotlib date value. This often happens if you pass a non-datetime value to an axis that has datetime units
```
in the second link

**Comment by frodrigo** [comment]
The github link miss the `*` at the end. But wait, the code was enabled this night, and the results are not yet here.

**Comment by frodrigo** [comment]
Backend server still not uptodate.

**Comment by frodrigo** [comment]
Uptodate. We move from 18 000 to 900!
