### ISSUE TITLE
Check give way cycling restrictions

### ISSUE THREAD

**Issue by Phyks** [osm-fr/osmose-backend#443]
Hi,

There is a quite large number of "give way" cycle relations at traffic lights (see https://wiki.openstreetmap.org/wiki/FR:Bicycle#Panonceaux_de_C.C3.A9dez-le-passage_cycliste_au_feu, in French) which seems to be invalid and not usable in Paris (and probably in other places as well).

According to the wiki, such a relation should have at least 3 members: via, from and to. Quite a lot of such relations just have the via member, making them really difficult to use.

I think this would be a good candidate for an Osmose analyser: check for such relations that there is at least one from, one via and one to member.

If you think this is something interesting to have, I could probably handle writing the analyser (although I have limited Osmose backend code experience :).

Best,

**Comment by frodrigo** [comment]
This can be generalised to other relations ?

**Comment by Phyks** [comment]
Hmm, probably but I don't know much about other such restrictions relations. Actually, I was reviewing current bicycle give way relations, hoping to be able to use them for another project, and discovered that quite a lot of them are tagged in a very unusable way, hence the idea for an analyser for this.

I just started to have a look at the closest analysers in Osmose, and it seems something like https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_restriction.py#L26 is already doing most of the job actually.

**Comment by frodrigo** [comment]
You are right. You sure it's not already done ?

**Comment by Phyks** [comment]
Indeed, you are right, this is just "normal" priority, I missed it at first: http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=48.839547&lon=2.356031&item=xxxx&level=1%2C2%2C3&tags=&fixable=.

This might be worth increasing its priority to make it more visible, not sure. Anyways, this issue can be closed I think.
