### ISSUE TITLE
Mappilary traffic signs maxheight

### ISSUE THREAD

**Issue by operon** [osm-fr/osmose-backend#446]
- Item 8300 class 20
- https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json
- https://www.openstreetmap.org/node/5036352231/history
- http://osmose.openstreetmap.fr/fr/error/23106515732

The test is only on highway ? for exemple the maxheight limit in on node on highway

**Comment by frodrigo** [comment]
- Move `otype` to `select_tags`.
- Add `nodes` for maxheight

Check if there is other mappings to update.

**Comment by frodrigo** [comment]
Only add nodes for maxheight.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=8300
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=8300&start_date=2019-03

**Comment by frodrigo** [comment]
Something go wrong. The graph should not go up.

**Comment by operon** [comment]
An increase in detection by Mapillary? with coincidence of dates
http://osmose.openstreetmap.fr/fr/error/23937389597 not normally

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/fr/errors/graph.png?item=8300&class=20&country=france*&start_date=2019

All up are only from France.

**Comment by frodrigo** [comment]
I see nothing wrong with the actual state. Maybe linked to other update deployed at the same time that flush the cache.
