### ISSUE TITLE
New check: barrier=fence with material=*

### ISSUE THREAD

**Issue by Discostu36** [osm-fr/osmose-backend#447]
This is a mistake that I made several times and it seems like I'm not the only one.

- barrier=fence should not be used with material=*
- fence_type=* should be used instead.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=3032&class=303210
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=3032&class=303210

**Comment by Discostu36** [comment]
Thanks! But "material", not "materal" :-)

**Comment by frodrigo** [comment]
Now it's better.

**Comment by frodrigo** [comment]
Ask for remove of this on #803
