### ISSUE TITLE
"Object must be close to coast or water" man_made=pier in or near multipolygon

### ISSUE THREAD

**Issue by AdVerburg** [osm-fr/osmose-backend#448]
● 1221 far from water
● http://osmose.openstreetmap.fr/en/errors/?country=netherlands_flevoland&item=1221&level=1%2C2%2C3
● http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=52.839807&lon=5.707397&item=1221&level=1%2C2%2C3&tags=&fixable=

When the a man_made=pier is in or near water of type=**multipolygon** then this object is marked.
In my opinion this is false positive.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?country=&item=1221&level=1%2C2%2C3
