### ISSUE TITLE
Conflict between tags: leisure, natural: marina with water

### ISSUE THREAD

**Issue by AdVerburg** [osm-fr/osmose-backend#449]
● 4030 incompatible tags → Conflict between tags: leisure, natural
• http://osmose.openstreetmap.fr/en/map/#zoom=16&lat=52.84983&lon=5.684&item=0000%2C0001%2C4030&level=1%2C2%2C3&tags=&fixable=

• http://osmose.openstreetmap.fr/en/errors/?country=netherlands_friesland&item=4030&level=1

With an **area** tagged as leisure=marina **and** natural=water this is marked as "incompatible tags".
But in a harbour without water is hard to navigate.
The standard OSM renders a marina without water as dry land.
Therefore I consider this as a false positive.

**Comment by frodrigo** [comment]
White listed.
