### ISSUE TITLE
Support request: How to use it

### ISSUE THREAD

**Issue by borazslo** [osm-fr/osmose-backend#45]
I would like to work on a new analyser. How can I test my new analyser?
- I cloned the repository
- I've installed all the dependencies and extensions
So how can I "run" my analyser? How can I check out wether I like its result?

**Comment by frodrigo** [comment]
You can show at this to have in introduction :
http://fr.slideshare.net/FredericRodrigo/20130906-sotmbirminghamosmose

Once you choose your analyser type (mainly osmosis or sax plugin), and code it. Run osmose_run.py

But in first place I recommend you to steup a running osmose backend first, try on a small area or country first.

Please, ask any question you have. You can contact us for help on osmose-contact@openstreetmap.fr.

**Comment by jocelynj** [comment]
Note that for sax analysers (which are in plugins directory, and don't check geometry), we tend to add unit testing to all python files. They can be launched with "nosetests plugins/<file.py>"
