### ISSUE TITLE
French tax office

### ISSUE THREAD

**Issue by lmagreault** [osm-fr/osmose-backend#450]
Item 8110 class 10
https://osmose.openstreetmap.fr/fr/errors?source=402690
https://osmose.openstreetmap.fr/fr/map/#item=8110&zoom=18&lat=46.390492&lon=5.565025&level=1%2C2%2C3&tags=&fixable=

Suggest tag for french local tax office is office=tax but office=government and government=tax looks more accurate and used.

Other thing, "Trésorerie" is a division of a "Centre des Finances Publiques" and the building's names are "Centre des Finances Publiques".
Example : https://www.mapillary.com/app/?lat=46.575791651601236&lng=5.750895560138125&z=17&pKey=zNXbYL5tPXfJz0vzQJM5gQ&focus=photo

"Service-public" tax office's lists are confusing and mix "Centre des Finances Publiques" and "Trésorerie".
Example : https://lannuaire.service-public.fr/navigation/bourgogne-franche-comte/jura/tresorerie

So detections of "Public service not integrated" for "Centre des Finances Publiques" named "Trésorerie" in "Service-public" source look false positive?

**Comment by frodrigo** [comment]
Thank for your return. The tags in this area have evolved since this analyser was created.

**Comment by frodrigo** [comment]
'Public service' is very large is this analyser, data comme from: https://www.data.gouv.fr/fr/datasets/service-public-fr-annuaire-de-l-administration-base-de-donnees-locales/

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=8110&class=10
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=8110&class=10

https://taginfo.openstreetmap.fr/tags/office=tax
167 objects to check and switch tags.

**Comment by frodrigo** [comment]
Tags change in OSM done.
