### ISSUE TITLE
Post box not integrated

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#463]
* [error/23571842162](http://osmose.openstreetmap.fr/fr/error/23571842162).

This mailbox is already added to OSM ([node/6228053157](https://www.openstreetmap.org/node/6228053157)).
It's ref is not yet added (see [error/23571980276](http://osmose.openstreetmap.fr/fr/error/23571980276)).

**Comment by frodrigo** [comment]
For this check the join is done on the ref. So the ref is required.
