### ISSUE TITLE
Power substation without ref:FR:RTE

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#464]
* [error/23572932314](http://osmose.openstreetmap.fr/fr/error/23572932314)

This is `minor_distribution` substation not available in [Enedis OpenData](https://www.enedis.fr/cartographie-des-reseaux-aeriens-denedis).
Probably a private substation (so we could add `substation=industrial` + `voltage=20000;400`).

In this case the reference should be [ref:ERDF:gdo](https://wiki.openstreetmap.org/wiki/FR:Key:ref:ERDF:gdo) (not [ref:FR:RTE](https://wiki.openstreetmap.org/wiki/Key:ref:FR:RTE)) ?

**Note:** In this french department, a lot of substations don't have any visible **references**, just **names**.
So the error's label could be _"Power substation without ref:FR:gdo or name"_ ?

**PS:** The substation is visible on [Street view:
![substation](https://user-images.githubusercontent.com/2158081/53439557-907d7f00-3a02-11e9-980e-32b997491132.jpg)](https://www.google.com/maps/@46.5644929,5.7666355,3a,28.4y,60.04h,91.6t/data=!3m6!1e1!3m4!1s8IDtaJ8vpaRiyoUv5PrWpg!2e0!7i13312!8i6656)
```

**Comment by frodrigo** [comment]
What is the issue about ?

For me too it look like a minor_substation.

ping @flacombe

**Comment by pyrog** [comment]
> What is the issue about ?

The error label is not clear. Osmose should suggest to add more tags (name, ref:ERDF:gdo…)

Is it the only case (so I will fix the data) ?
Or is there hundreds of error like this (so Osmose should be improved) ?

**Comment by frodrigo** [comment]
If it talk about RTE is because the location come from RTE opendata.

**Comment by pyrog** [comment]
> If it talk about RTE is because the location come from RTE opendata.

Understood, thanks 😀.
Is it possible to display a link to the RTE opendata record ?

**Comment by frodrigo** [comment]
Yes. Pull request are accepted.
- https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_power_substation_FR.py
- https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_power_substation_minor_FR.py

**Comment by flacombe** [comment]
Hi

Osmose actually suggest missing ref:FR:RTE since it can't properly determine its precise type.
Should it warns for such missing refs with a corresponding point in the opendata dataset only?

In this situation such substation can't be operated by RTE or even host high voltage B equipments then should never have a ref:FR:RTE

All the best
François
