### ISSUE TITLE
Power minor_distribution substation not integrated

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#465]
* [error/23576718709](http://osmose.openstreetmap.fr/fr/error/23576718709)

Osmose suggest to integrate a substation.
In this case, there is a [way](https://www.openstreetmap.org/way/202373660) tagged as `power=transformer`by newbie (in fact me, before I understand how to map correctly power substations).

As beginners could tag them improperly as transformers, could you suggest to remove `power=transformer` and add the "good" tags (See #451).

**Comment by frodrigo** [comment]
I prefer let the contributor look at the data rather than match to invalid data.
