### ISSUE TITLE
import new validator rules from JOSM

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#467]
Especially warning on `shop=yes` (see https://github.com/gravitystorm/openstreetmap-carto/issues/3697 https://josm.openstreetmap.de/ticket/17377 https://github.com/openstreetmap/iD/issues/5955 for `shop=yes` related issues)

**Comment by frodrigo** [comment]
Before next JOSM MapcCSS update into Osmose need to clarify the port of Osmose check to JOSM MapCSS to avoid duplicate check.

Since Radiant Solutions starts porting Osmose rules de JOSM MapCSS the situation is not clear.

**Comment by frodrigo** [comment]
cc @don-vip

**Comment by frodrigo** [comment]
Hopefully the merge from Osmose validator in JOSM is not yet done. So I promptly update the mapcss from JOSM in Osmose.
