### ISSUE TITLE
complain about amenity=parking named Parking/parking

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#468]
Such descriptive name is never correct

See https://www.openstreetmap.org/node/5819963940#map=17/54.08131/15.02039 for an example

See http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=54.081408&lon=15.017398&item=xxxx&level=1%2C2%2C3&tags=&fixable= that osmose is not complaining about it.

**Comment by rivermont** [comment]
Perhaps it could check for amenities with `name=` matching the value of the main tag? This would likely create false positives but could catch a lot of buildings named 'house' or 'building,' etc.  
Similar to iD's "Generic Name" check.

**Comment by matkoniecz** [comment]
Note that this validator warning should be included already thanks to importing JOSM warnings.

See https://josm.openstreetmap.de/ticket/17100 where many warning similar to one requested here were added.

**Comment by matkoniecz** [comment]
Implemented indirectly by ma patch and directly by importing JOSM rules.

See for example http://osmose.openstreetmap.fr/en/error/31577599357

Thanks for creating and maintaining import of JOSM rules!
