### ISSUE TITLE
s/amenity=dancing_school/leisure=dance + dance:teaching=yes

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#469]
Hello,

- http://osmose.openstreetmap.fr/fr/error/23618228015

clé | valeur
-- | --
source | 5833
item | 8170
class | 88
subclass | 1419197878
title |  fr Terrain de sport non intégré Salle de danse

Correction | clé | valeur
-- | -- | --
tags_create | amenity |  dancing_school

- Sauf que : abandonné (2010) : https://wiki.openstreetmap.org/wiki/Proposed_features/Dancing_school

- Donc : "Please use leisure=dance + dance:teaching=yes instead." (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddancing_school)

HTH

**Comment by frodrigo** [comment]
Change done.

200 objet in France to check en switch tags : https://taginfo.openstreetmap.fr/tags/amenity=dancing_school#overview

**Comment by frodrigo** [comment]
Tags change in OSM done.
