### ISSUE TITLE
Unfinished power line at location transitions

### ISSUE THREAD

**Issue by flacombe** [osm-fr/osmose-backend#471]
Hi all,

It is currently observed that location:transition=yes isn't enough to say a line is finished on a given pole.

Can item 7040 class 6 be updated to look forward this tag please?
location:transition=yes
https://wiki.openstreetmap.org/wiki/Tag:location:transition%3Dyes

pole:type=anchor or pole:type=termination are currently under discussion on https://wiki.openstreetmap.org/wiki/Proposed_features/Lines_clamps

All the best

**Comment by frodrigo** [comment]
Not sure what you are requested for.

You want `location:transition=yes` to supported as line end ? But is just a transition point, not the end.

**Comment by pyrog** [comment]
For me, it mark the end of line.

In reality, the line continue as an underground cable, but unfortunately, we usually couldn't map it.

**Comment by flacombe** [comment]
Indeed it's not the end of the overhead line properly.
Nevertheless, many poles are only mapped with it and not pole:type=termination (which is a poor choice for a key name imho)

I think that item 7040 can rise no issue on location:transition=yes if and only if a line finishes on it.

**Comment by flacombe** [comment]
This issue has been solved long ago with https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_osmosis_powerline.py#L100, not a problem anymore.
