### ISSUE TITLE
Validate DE phone numbers

### ISSUE THREAD

**Issue by mojoaxel** [osm-fr/osmose-backend#472]
Due to the [wiki Key:phone](https://wiki.openstreetmap.org/wiki/Key:phone) numbers should be in the [ITU-T E.123](http://en.wikipedia.org/wiki/E.123) / [DIN 5008](http://en.wikipedia.org/wiki/de:DIN_5008) format.

`+<country code> <area code> <local number>[-<extension>]`

### Format
* phone_code: [49](https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany)
* phone_len: [11](https://de.wikipedia.org/wiki/Rufnummer#L%C3%A4nge_von_Rufnummern)
* phone_len_short: ?
* phone_format: ?
* phone_international: 00

### Usefull links:
* https://wiki.openstreetmap.org/wiki/Key:phone

**Comment by frodrigo** [comment]
phone_international is the prefix to make international call when not using mobile, it's an alias for '+' of mobile phone. Usually '00' or '011'.

**Comment by frodrigo** [comment]
https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany

According to Wikipedia, phone numbers are of variable length. Do you know the range of length?

When you write a German number in Germany, it's always start with a "0", and remove this "0" on international form, when adding +49? (like in France?)

https://overpass-turbo.eu/s/GXf

**Comment by mojoaxel** [comment]
> When you write a German number in Germany, it's always start with a "0", and remove this "0" on international form, when adding +49? (like in France?)

Yes! e.g 0911 123456  --> +49 911 123456

**Comment by frodrigo** [comment]
A first batch of phone numbers raised as issues, with fix when possible.

Please can review it. And explain what should be done for some cases.

```
<tag k="phone" v="+49 03375/56490" /> --> +49 3375/56490" />
<tag k="phone" v="+49 35475 482<U+200E>" />
<tag k="phone" v="+49 35475 482<U+200E>" />
<tag k="phone" v="+49 03362/3261" /> --> +49 3362/3261" />
<tag k="phone" v="+49 35603 75817<U+200E>" />
<tag k="phone" v="0800 1008669" /> --> +49 800 1008669" />
<tag k="phone" v="+49 3877 902068 or 79195" />
<tag k="phone" v="035451 343" /> --> +49 35451 343" />
<tag k="phone" v="+49 03327/730313" /> --> +49 3327/730313" />
<tag k="phone" v="03385/54030" /> --> +49 3385/54030" />
<tag k="phone" v="0335 23556" /> --> +49 335 23556" />
<tag k="phone" v="+49 335 4015757 <U+200E>" />
<tag k="phone" v="0049-(0)33433-157782" /> --> +49-(0)33433-157782" />
<tag k="phone" v="0049-(0)33433-157782" />
<tag k="phone" v="+49 0335 23708" /> --> +49 335 23708" />
<tag k="phone" v="0335 414250" /> --> +49 335 414250" />
<tag k="phone" v="035365 2923" /> --> +49 35365 2923" />
<tag k="phone" v="039846982" /> --> +49 39846982" />
<tag k="phone" v="+49 033748 205959" /> --> +49 33748 205959" />
<tag k="phone" v="03545217000" /> --> +49 3545217000" />
<tag k="phone" v="+49 35341 471936" />
<tag k="phone" v="0309444293" /> --> +49 309444293" />
<tag k="phone" v="033365 366" /> --> +49 33365 366" />
<tag k="phone" v="033053 / 71 924, 71 392, 0179 / 20 57 369" /> --> 033053; 71 924, 71 392, 0179; 20 57 369" />
<tag k="phone" v="+49 3877 904154 or 904429" />
<tag k="phone" v="+49 (0) 33203 / 22 556" /> --> +49 (0) 33203; 22 556" />
<tag k="phone" v="+49 33056 81508<U+200E>" />
<tag k="phone" v="+49 33704 66031, +49 173 9043347" />
<tag k="phone" v="035696 329" /> --> +49 35696 329" />
<tag k="phone" v="+49 3877 75125 or 562184, +49 151 12013029" />
<tag k="phone" v="+49 38792 7626, +49 173 6136845" />
<tag k="phone" v="03877 904118" /> --> +49 3877 904118" />
<tag k="phone" v="0335 414050" /> --> +49 335 414050" />
<tag k="phone" v="+49 3372 442420<U+200E>" />
<tag k="phone" v="03 39 71 5 23 50" /> --> +49 3 39 71 5 23 50" />
<tag k="phone" v="033920 69291" /> --> +49 33920 69291" />
<tag k="phone" v="033920 69291" />
<tag k="phone" v="03552890359" /> --> +49 3552890359" />
<tag k="phone" v="033606 78856" /> --> +49 33606 78856" />
<tag k="phone" v="03331-2629-0" /> --> +49 3331-2629-0" />
<tag k="phone" v="03334239764" /> --> +49 3334239764" />
<tag k="phone" v="033435 / 15279" /> --> 033435; 15279" />
<tag k="phone" v="+49 033435 386" /> --> +49 33435 386" />
<tag k="phone" v="+49 (0) 33203 - 60 87 20" /> --> +49 (0) 33203; 60 87 20" />
<tag k="phone" v="0171-2115743" /> --> +49 171-2115743" />
<tag k="phone" v="03385/541910" /> --> +49 3385/541910" />
<tag k="phone" v="03385/541910" />
<tag k="phone" v="03984 7180305" /> --> +49 3984 7180305" />
<tag k="phone" v="+49 03 37 68 5 02 24" /> --> +49 3 37 68 5 02 24" />
<tag k="phone" v="03394-433562" /> --> +49 3394-433562" />
<tag k="phone" v="033849 50095" /> --> +49 33849 50095" />
<tag k="phone" v="033849 50095" />
<tag k="phone" v="03877 405691" /> --> +49 3877 405691" />
<tag k="phone" v="0049 3361 710 001" /> --> +49 3361 710 001" />
<tag k="phone" v="033931-38525" /> --> +49 33931-38525" />
<tag k="phone" v="+49 3561 432433 <U+200E>" />
<tag k="phone" v="+49033638-48398220" /> --> +49 33638-48398220" />
<tag k="phone" v="033768 208641" /> --> +49 33768 208641" />
<tag k="phone" v="0334688991" /> --> +49 334688991" />
<tag k="phone" v="033476/5192" /> --> +49 33476/5192" />
```

**Comment by mojoaxel** [comment]
Thanks! I see problems with the following:

### Alternative numbers
```
<tag k="phone" v="+49 03375/56490" /> --> +49 3375/56490" />
<tag k="phone" v="033053 / 71 924, 71 392, 0179 / 20 57 369" /> --> 033053; 71 924, 71 392, 0179; 20 57 369" />
```
I think here the user ment to show an alternative number!? 
For that I think two entries should be added.

**Comment by matthewdarwin** [comment]
Should use semi-colon ";" to separate phone numbers probably.  Not sure if osmose supports that.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Phone.py#L91

` / ` and ` - ` with space are see as bad number separator, so the fix is to replace by `; `. But in Germany there is an other usage this these.

**Comment by frodrigo** [comment]
I see two fixes to do:
- suggest to replace `,` by `;`,
- in Germany, do not suggest to replace ` / ` and ` - ` by `;`

**Comment by frodrigo** [comment]
Results are now coming online:

http://osmose.openstreetmap.fr/en/errors/?country=germany_*&item=3092

Please review.

**Comment by mojoaxel** [comment]
Very helpfull! Thanks!!

I still see some thinks I would like to be changed:
* [2539801360](https://www.openstreetmap.org/node/2539801360): `+49 911/6608486` should be `+49 911 6608486`
* [2789324710](https://www.openstreetmap.org/node/2789324710): `+49 9119237105` should be `+49 911 9237105`
* [4265071089](https://www.openstreetmap.org/node/4265071089): `+49 911/76670-0` should be `+49 911 76670-0`
* [251650263](https://www.openstreetmap.org/way/251650263): `+49 9103797322` should be `+49 9103 797322` 

Here is what I would recommend (from the list above):

phone | fix
-- | --
+49 03375/56490 | +49 3375 56490
+49 03362/3261 | +49 3362 3261
+49 3877 902068 or 79195 |  +49 3877 902068; +49 3877 79195 
+49 03327/730313 | +49 3327 730313
03385/54030 | +49 3385 54030
0049-(0)33433-157782 | +49 33433 157782
039846982 | +49 398 46982
033053 / 71 924, 71 392, 0179 / 20 57 369 | +49 33053 7192; +49 33053 71392; +49 179 2057369
+49 3877 904154 or 904429 |  +49 3877 904154; +49 3877 904429
+49 (0) 33203 / 22 556 | +49 33203 22556
+49 38792 7626, +49 173 6136845 | +49 38792 7626; +49 173 6136845 
03331-2629-0 | +49 3331 2629-0
03394-433562 | +49 3394 433562
0049 3361 710 001 | +49 3361 710001
033476/5192 | +49 33476 5192

**Comment by frodrigo** [comment]
The implemented rules does not work on number layout. It even respect the original layout on fix.
