### ISSUE TITLE
item 9001 cl 9001001 : message for amenity=lavoir + water=yes/no

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#475]
Hello,

It appears that osmose throws message for objects amenity=lavoir + water=yes/no, complaining  "natural without water=intermittent". See for example https://osmose.openstreetmap.fr/en/error/24176895688 or https://osmose.openstreetmap.fr/fr/error/24176895687

However, this is a documented usage : https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlavoir#Which_tag_to_use_.3F

Please, don't throw message for this use case.

**Comment by frodrigo** [comment]
source | 411632
-- | --
item | 9001
class | 9001001
subclass | 2074767689
elems | way668554081
lat lon | 45.5893244 5.2279955



key | value
-- | --
elem_index | 0
type id | W 668554081
tags | amenitylavoir                 shelteryes                 waterno | amenity | lavoir |   | shelter | yes |   | water | no |  
amenity | lavoir |  
shelter | yes |  
water | no |  
username | laurent-38



It is from JOSM MapCSS validation rule
- https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss#L495
- https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss#L499

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
Fixed in JOSM in https://josm.openstreetmap.de/changeset/14883/josm

**Comment by frodrigo** [comment]
Thank.

Osmose updated from JOSM MapCSS.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=9001&class=9001001

http://osmose.openstreetmap.fr/fr/errors/graph.png?item=9001&class=9001001&start_date=2019-03

**Comment by laurentriffard** [comment]
Thank you for the fix.
