### ISSUE TITLE
"Duplicate wikipedia tag" appropriate for duplicated physical structures

### ISSUE THREAD

**Issue by osm-spiregrain** [osm-fr/osmose-backend#476]
Hi there.   There is a chain of 18th century fortifications along the south-east coast of England called "Martello Towers".   Naturally, many of them are mapped and there is a wikidata item for them.  

At present, Osmose complains that these multiple objects shouldn't have identical wikidata entries.   Is that appropriate?

- the item and class number: - 4130 1
- a link to detail of this marker- http://osmose.openstreetmap.fr/en/error/24227486048 
- Wikipedia page - https://en.wikipedia.org/wiki/Martello_tower

**Comment by frodrigo** [comment]
I think is not appropriate, it's as class of building, like castel. The Wikipedia tag should only contain the page title of the instance of the tower, if there is, like this: https://en.wikipedia.org/wiki/Shoal_Tower

**Comment by frodrigo** [comment]
Please. Reopen if required.
