### ISSUE TITLE
item 1260 cl 4 : false positive "Public transport relation route not in route_master relation"

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#477]
Hello,

I can't understand this warning : https://osmose.openstreetmap.fr/fr/error/24589201405

key | value
-- | --
source | 411669
item | 1260
class | 4
subclass | 0
elems | relation4077353
lat lon | 45.6326171 5.1466700
title |  en  Public transport relation route not in route_master relation      
subtitle |  
timestamp | 2019-03-23 05:42:02

key | value
-- | --
elem_index | 0
type id | R 4077353
tags | … | 
colour | #4abfee |  
from | La Verpillière - Mairie |  
name | B : Verpillère => Villefontaine |  
network | Ruban |  
opening_hours | Mo-Sa 06:00-19:00 |  
operator | SERUS |  
public_transport:version | 2 |  
ref | B |  
route | bus |  
to | Villefontaine - Mas de la Raz |  
type | route |  
username | laurent-38

Indeed, [relation 4077353](https://www.openstreetmap.org/relation/4077353) (`type=route + route=bus`) is member of [relation 4033705](https://www.openstreetmap.org/relation/4033705) (`type=route_master + route_master=bus`).

What's wrong here ?

**Comment by frodrigo** [comment]
At first look, OSM data look right.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_public_transport.py#L203

**Comment by frodrigo** [comment]
The master relation is missing the france_rhone_alpes_isere extract.

http://osmose.openstreetmap.fr/fr/errors/graph.png?item=1260&class=4&country=france*&start_date=2019

Maybe linked to the switch from regions to departements in France.

cc @jocelynj

**Comment by frodrigo** [comment]
@jocelynj nothing change, need to clear extract caches of backend?

**Comment by jocelynj** [comment]
Yes, the extracts are now re-generated, and the cache on backend has to be cleaned.

**Comment by frodrigo** [comment]
The extract is ok, but Osmose still report too many missing relations.

**Comment by laurentriffard** [comment]
Hi frodigo,
it seems to be ok since yesterday, see http://osmose.openstreetmap.fr/fr/errors/graph.png?country=france_rhone_alpes_isere&item=1260&class=4.
All my false positives disappeared.
Thank you.

**Comment by frodrigo** [comment]
I just keep it open to remind me about the others.

http://osmose.openstreetmap.fr/fr/errors/graph.png?item=1260&class=4&country=france*&start_date=2019

**Comment by frodrigo** [comment]
Found only one suspect, to be checked:
http://osmose.openstreetmap.fr/fr/map/#item=1260&class=4&country=france*&start_date=2019&zoom=16&lat=48.94892&lon=2.33709&level=1%2C2%2C3&tags=&fixable=
