### ISSUE TITLE
Detect wrong highway connections

### ISSUE THREAD

**Issue by naoliv** [osm-fr/osmose-backend#48]
I don't know what osmose already detects or if this is wanted, but could osmose detect:
1) `highway` connected to `waterway|water` without `ford`
2) `highway` connected to `power=line|minor_line`
3) `highway` connected to `landuse`

**Comment by frodrigo** [comment]
1 and 2 are planned, 3 is not an error

**Comment by naoliv** [comment]
For 3 I was thinking on objects like this http://www.openstreetmap.org/way/200167311 where the user joined the landuse to the highways.
It's not *wrong* but it's also not a good mapping practice (for me, at least).

**Comment by frodrigo** [comment]
I agree, but it's not worng and it's too common.

**Comment by frodrigo** [comment]
duplicate #43

**Comment by jocelynj** [comment]
1) was fixed by commit 1c5584019245187064a71f7cfcaf4f30f3b6202a.

**Comment by frodrigo** [comment]
2) is also done
