### ISSUE TITLE
Detect highway=speed_camera nodes that are not part of a highway

### ISSUE THREAD

**Issue by stefanb** [osm-fr/osmose-backend#482]
Speed cameras are tagged per
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera
which mentions:

> This node is tagged
> - **on the highway**, next to where the actual speed camera is, or
> - at the actual position of the camera next to the highway with an enforcement relation.

Sometimes mappers put a `highway`=`speed_camera` node on the exact location of the camera, by the road instead of on the road itself. The navigation applications do not consider such cameras as relevant.

It would be nice to get a warning in such cases.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=1280&useDevItem=all

**Comment by frodrigo** [comment]
@stefanb the check is setup. But I'm worried about change is OSM based on this. If the contributor move the node to way we lost some kind of information about the probably direction. But the wiki miss the point of the direction, look at https://wiki.openstreetmap.org/wiki/Talk:Tag:highway%3Dspeed_camera

**Comment by stefanb** [comment]
Thanks, seems to work perfectly!
