### ISSUE TITLE
Question for translation

### ISSUE THREAD

**Issue by debyos** [osm-fr/osmose-backend#483]
Dear All,

what do the followings mean:

- rule ks_vs
- rule ks_vr
- rule kr_vs
- rule kr
- rule ks 

Thanks

Gábor

**Comment by frodrigo** [comment]
It come from this code : https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagWatchFrViPofm.py

Not sure but I think ks mean keys, vs values, vr value regex, kr key regex.
