### ISSUE TITLE
Mailbox without reference

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#484]
[Osmose item 7051 classe 3](https://osmose.openstreetmap.fr/fr/map/#item=7051&zoom=17&lat=47.810265&lon=-3.480574&level=3&tags=&fixable=) signale une bàl sans référence.

Pourtant le [noeud](https://www.openstreetmap.org/node/4214968210) correspondant comporte bien : 

ref:FR:LaPoste | A1C4M4
-- | --

et l'élément est toujours disponible en [OD LA Poste](https://datanova.legroupe.laposte.fr/explore/dataset/laposte_boiterue/map/?disjunctive.lb_voie_ext&disjunctive.lb_com&disjunctive.co_insee_com&disjunctive.co_postal&disjunctive.lb_type_geo&disjunctive.syst_proj_ini&location=16,47.82575,-3.49265&basemap=jawg.streets) avec cette référence.

J'en ai d'autres ;-(

**Comment by deuzeffe** [comment]
Peut-être parce que pour les BàL, le tag est "ref=*" et non "ref:FR:LaPoste=*" qui est pour les bureaux de poste ?

**Comment by frodrigo** [comment]
Tous à fait c'est bien ça. Le message n'est pas assez clair.

**Comment by Bibi56** [comment]
OK d'Oc. Je vois aussi une bàl dans OSM et inconnue de La Poste. Pourtant elle existe bien. Je devrais m'y poster une lettre pour vérifier que la bàl est bien relevée ;-)

**Comment by Bibi56** [comment]
je laisse ouvert, pour changer le message d'erreur.

**Comment by deuzeffe** [comment]
> OK d'Oc. Je vois aussi une bàl dans OSM et inconnue de La Poste. Pourtant elle existe bien. Je devrais m'y poster une lettre pour vérifier que la bàl est bien relevée ;-)

Et prends la plaque d'identification en photo :-)

Il m'est arrivé de trouver une BàL physique à plus de 400 m de sa géoloc. dans le fichier OD de La Poste.

**Comment by Bibi56** [comment]
petite joueuse, mon record était d'1 km (codée au rond-point portant le nom du lieu-dit mais soit disant codée au numéro). Heureusement le postier n'utilise pas l'OD de la Poste pour faire son travail ;-)

Ceci dit c'est un bon indice, je fais le pari que la bàl sans réf c'est la A1C4N0.

**Comment by Bibi56** [comment]
Ceci dit pour corriger le problème globalement, https://overpass-turbo.eu/s/Iii le fait (voir les données) mais je ne sais comment le pousser vers OSM : JOSM ne voit rien.

**Comment by frodrigo** [comment]
Post box without tag "ref" or invalid
