### ISSUE TITLE
suggest that bridge_name and bridge_name:* be replaced with bridge:name and bridge:name:*

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#487]
According to http://weeklyosm.eu/archives/11906 bridge:name is preferred over bridge_name.  It is also more popular according to taginfo.  So it would be good for osmose to auto-suggest changing those tags.

eg https://www.openstreetmap.org/way/318737543

**Comment by frodrigo** [comment]
Please add it to https://wiki.openstreetmap.org/w/index.php?title=User:FrViPofm/TagwatchCleaner

**Comment by matthewdarwin** [comment]
Added

**Comment by frodrigo** [comment]
It will be fetched at next cache expiration.
