### ISSUE TITLE
Skip "Default and local language name not the same" for large objects in multiple countries

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#488]
For some objects, especially routes, it is impossible to use both (or more) local names at once.

Would it be possible to skip objects that are in multiple countries, and name matches at least one of local languages from this check?
 
Example of an affected area: http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.262342&lon=19.01794&item=xxxx&level=1&tags=&fixable=

```
 Default and local language name not the same
relation 9331996 rawedit analyse1 analyse2 josm edit
from = Wien Erdberg, Busterminal VIB
name = Flixbus N918: Wien <=> Warschau
name:cs = Flixbus N918: Vídeň <=> Varšava
name:de = Flixbus N918: Wien <=> Warschau
name:pl = Flixbus N918: Wiedeń <=> Warszawa
network = Flixbus
operator = Flixbus
public_transport:version = 2
ref = N918 
```

**Comment by frodrigo** [comment]
There are not the majority of objects, so far. Just mark as false-positive.

**Comment by matkoniecz** [comment]
There is enough of them to be obnoxious. Is it very complicated to skip such objects?

I like validators, but I extremely dislike false positives, especially automatically detectable false positives.

**Comment by frodrigo** [comment]
A such check does not feet the design of Osmose about borders.
Nevertheless is to doable, but require time to work on it.

**Comment by frodrigo** [comment]
Duplicate #353

**Comment by Yogurt4** [comment]
frodrigo: It's similar to #353 but not a duplicate. And definitely not "completed", none of them, till the present day.

**Comment by matkoniecz** [comment]
> And definitely not "completed", none of them, till the present day.

Note that Github is silly with two-state closure (labels should be used for that) and this closure is likely predating this rename.

Though it is not a duplicate of #353 and is not covered by "In the Netherlands "we" use English language as default language (for OpenStreetMap)."
