### ISSUE TITLE
analyser_merge_school_FR.py: updated DB

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#489]
Hello,

In analyser_merge_school_FR.py to replace :

Lines 61 & 63:

u"https://www.data.gouv.fr/fr/datasets/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres/",

CSV(Source(attribution = u"data.gouv.fr:Éducation Nationale", millesime = "05/2016",

by
u"https://www.data.gouv.fr/fr/datasets/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres-1/",

CSV(Source(attribution = u"data.gouv.fr:Éducation Nationale", millesime = "12/2018",

HTH

**Comment by frodrigo** [comment]
Still not update on Osmose, a bug remain.

**Comment by deuzeffe** [comment]
Oops. My bad :|

**Comment by frodrigo** [comment]
Done.
http://osmose.openstreetmap.fr/en/map/#zoom=15&lat=44.80437&lon=-0.63344&item=8030%2C8031%2C8032&level=1%2C2%2C3&tags=&fixable=

Guyane still missing.
