### ISSUE TITLE
Suggestions for opening_hours fixes

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-backend#490]
I am starting a personal project to fix opening_hours.  I see a lot of patterns that could be handled by auto-correction (suggestion) mechanism.  
1) What is a helpful way to report suggested multiple auto-corrections?
2) Could you point me to where this is handled in the code?

**Comment by frodrigo** [comment]
The opening_hours parser is here : https://github.com/osm-fr/osmose-backend/tree/master/modules/oh_sanitizer it's based on oh_sanitizer project, but now it's a fork.

It called from
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Opening_Hours.py

As you can see on #433 many fixes was done, but I'm still unsatisfied with the result. I'm thinking of replacing the underlayer lark parser. Nevertheless the grammar can still be improved.

**Comment by HubMiner** [comment]
Reporting suggested corrections: I started using "false positives" report.

field.ebnf - would it help to add russian keywords?

test_valid_fields(self) - I assume only passing unit tests should be added?

**Comment by frodrigo** [comment]
Yes translations will help. But we need to move out the multiple translations, and only apply the good ones for the current country.

**Comment by HubMiner** [comment]
I was not able to figure out Python modules dependencies to install in Windows, sorry.

**Comment by HubMiner** [comment]
Here are some of the combinations I observed.  Please let me know if this is helpful, and I should post more of these.

Mon-Fri: 8:00AM to 6:00PM
Mo-Fr 08:00-18:00

Mon-Fri: 9:00 AM to 5:00 PM
Mo-Fr 09:00-17:00

Mon-Fri:8:00 AM to 5:00 PM
Mo-Fr 08:00-17:00

Mon-Fri: 9am-5pm Sat: 9am-3pm Sun: Closed
Mo-Fr 09:00-17:00; Sa 09:00-15:00; Su closed

3-11
15:00-23:00

Mon-Sun: Open 24 Hours 
24/7

Monday-Sunday: Open 24 Hours
24/7

24 Hours
24/7

Monday-Friday: 7:00AM to 5:00PM
Mo-Fr 07:00-17:00

11 AM Till 1 AM
11:00-01:00

Mon-Thu: 10:00 AM to 6:00 PM, Fri: 11:00 AM to 6:00 PM, Sat: 10:00 AM to 5:00 PM
Mo-Th 10:00-18:00; Fr 11:00-18:00; Sa 10:00-17:00

Weekdays 10 AM- 5 PM, Weekends 9 AM - 6 PM
Mo-Fr 10:00-17:00; Sa,Su 09:00-18:00

Mo-Thurs 11 AM - 10 PM / Fri-Sat 11 AM - 10:30 PM / Sun 11 AM - 9:30 PM 
Mo-Th 11:00-2@:00; Fr-Sa 11:00-22:00; Su 11:00-21:30

7:30 am - 5:30 pm M-F
Mo-Fr 07:30-17:30

Su – Th: 10:30am - 11pm; F & Sa: 10:30am - 12am 
Su–Th 10:30-23:00; Fr,Sa: 10:30-00:00

M-F 10am-8pm Saturday 10am-7pm Sunday 11am-5pm 
Mo-Fr 10:00-20:00; Sa 10:00-19:00; Su 11:00-17:00

M-F 9am-9pm, Sa-Su 9am-5pm 
Mo-Fr 09:00-21:00, Sa-Su 09:00-17:00

Monday-Thursday (7:00am-7:00pm) Friday(9:00am-5:00pm) 
Mo-Th 07:00-19:00; Fr 09:00-17:00

Monday-Thursday 9am-8pm, Friday 9am-6pm, Saturday 9am-4pm, closed Sunday
Mo-Th 09:00-20:00, Fr 09:00-18:00, Sa 09:00-16:00, Su closed

Monday - Sunday : 7:00AM to 7:00PM 
09:00-21:00

Mon-Thu: 4:00 PM to 10:00 PM, Fri: 4:00 PM to 11:00 PM, Sat: 11:00 AM to 11:00 PM, Sun: 11:00 AM to 8:00 PM 
Mo-Th 16:00-22:00; Fr 16:00-23:00; Sa 11:00-23:00; Su 11:00-20:00

12PM to 8PM 
12:00-20:00

daylight only 
dawn-dusk

(Mo-Fr 06:00-13:00) 
Mo-Fr 06:00-13:00

Mon-Sat:10PM-6PM; Sun: Closed
Mo-Sa 10:00-18:00; Su closed

Mon: 8:00AM to 6:00PM, Wed: 9:00AM to 7:00PM, Fri: 9:00AM to 6:00PM
Mo 8:00AM to 6:00PM; Wed: 9:00AM to 7:00PM; Fri: 9:00AM to 6:00PM

Monday to Thursday: 11:00AM to 9:30PM, Friday: 11:00AM to 10:00PM Saturday: 12:00PM to 10:00PM,Sunday: 12:00PM to 9:00PM 
Mo-Th 11:00-21:30; Fr 11:00-22:00; Sa 12:00-22:00; Su 12:00-21:00

Mon-Tue & Thu-Fri: 8:00AM to 6:00PM, Wed: 8:00AM to 6:30PM, Sat: 8:00AM to 5:00PM;Mo,Tu, Th, Fr 08:00-18:00;We 08:00-18:30;Sa 08:00-17:00;Su off 
Mo,Tu,Th,Fr 08:00-18:00; We 08:00-18:30; Sa 08:00-17:00; Su off

Mo-Su 10:00 AM - 02:00 AM 
10:00-02:00

Mo-Thu 10a-9p, Fri-Sat 10a-6p, Su 1a-5p 
Mo-Th 10:00-21:00; Fr-Sa 10:00-18:00; Su 01:00-17:00

Mon-Tue: 10:00AM to 10:00PM, Wed-Thu: 10:00AM to 11:00PM, Fri-Sat: 11:00AM to 11:00PM, Sun: 12:00PM to 8:00PM 
Mo-Tu 10:00-22:00; We-Th 10:00-23:00; Fr-Sa 11:00-23:00; Su 12:00-20:00

Mon-Fri 9:00AM to 6:00PM Sat 9:00AM to 3:00PM 
Mo-Fr 09:00-18:00; Sa 09:00-15:00

Mo-Fr 07:00-19:00 Sa 09:00-19:00 Su 11:00-18:00 
Mo-Fr 07:00-19:00; Sa 09:00-19:00; Su 11:00-18:00

Thursday from 6-10pm
Th 18:00-22:00

June 01 - August 31: Monday - Saturday, 12:00 PM - 04:00 PM. September 01 - May 31, Thursdays only, 10:00 AM - 02:00 PM 
Jun 01-Aug 31: Mo-Sa 12:00-16:00; Sep 01-May 31: Th 10:00-14:00

Summer (Memorial Day to Labor Day) Mon, Tues, Thurs, Fri: 9am - 5pm Wed: 9am - 7pm Sat: 9am - 2pm Winter (Labor Day to Memorial Day) Mon, Tues, Thurs, Fri: 10am - 5pm Wed: 10am - 7pm Sat: 10 am - 2 pm
May Mo[-1]-Sep Mo[1]: Mo-Fr 09:00-17:00, We 09:00-19:00, Sa 09:00-14:00 ; Sep Mo[1] - May Mo[-1]: Mo-Fr 09:00-17:00, We 10:00-19:00, Sa 10:00-14:00

Summer (Memorial Day to Labor Day) Mon, Tues, Thurs, Fri: 9am - 5pm Wed: 9am - 7pm Sat: 9am - 2pm
May Mo[-1]-Sep Mo[1]: Mo-Fr 09:00-17:00, We 09:00-19:00, Sa 09:00-14:00 

Winter (Labor Day to Memorial Day) Mon, Tues, Thurs, Fri: 10am - 5pm Wed: 10am - 7pm Sat: 10 am - 2 pm
Sep Mo[1] - May Mo[-1]: Mo-Fr 09:00-17:00, We 10:00-19:00, Sa 10:00-14:00

Closed For Winters
Nov-Feb closed

10 AM-? 
10:00+

Sat-TR: 6:00AM-3:00PM;F: 6:00AM-7:00PM;Open 4AM Deer Season 
Sa-Th 06:00-15:00; Fr 06:00-19:00; "Open 4AM Deer Season"

M-F: 8:30AM to 4:30PM;Sat: 8:30 to Noon 
Mo-Fr 08:30-16:30; Sa 08:30-12:00

1st Thurs: 3:30-6PM;2nd Wed 9:30AM-Noon;3rd Friday 9:30A;4th Friday 2:30-5:30PM 
Th[1] 15:30-18:00; We[2] 09:30-12:00; Fr[3] 09:30-12:00; Fr[3] 14:30-17:30

M-F:9-5;Sat:9-Noon;Sun:By Appt
Mo-Fr 09:00-17:00; Sa 09:00-12:00; Su "By Appt"

Tue-Fri: 11:00AM-4:30PM;Sat:10:00AM-2:30PM
Tu-Fr 11:00-16:30; Sa 10:00-14:30

T&TR:10-3;W:10-6;Sat:10-1
Tu,Th 10-15; We 10-18; Sa 10-13

Sun 1-4, memorial day to labor day 
May Mo[-1]-Sep Mo[1]: Su 13:00-16:00

Mon., Tues.,Wed., Fri.: 10:00 a.m. - 6:00 p.m. Thurs. Noon - 8:00 p.m. Saturdays: 10:00 a.m. - 2:00 p.m.
Mo-Fr 10:00-18:00; Th 12:00-20:00; Sa 10:00-14:00

Monday and Wednesday | 10 a.m.-8 p.m. Tuesday, Thursday and Friday | 10 a.m.-5 p.m. Saturdays | 10 a.m.-1 p.m 
Mo,We 10:00-20:00; Tu,Th,Fr 10:00-17:00; Sa 10:00-13:00

7a - 4pm M-F 
Mo-Fr 07:00-16:00

9am to 8pm 
09:00-20:00

Mo-Fr 07:00-21:00, Sat 07:00-20:00, Sun 09:00-18:00 
Mo-Fr 07:00-21:00, Sa 07:00-20:00, Su 09:00-18:00

Mon- Tue Closed, Wed- Sat 11-6, Sun 1-4 
Mo-Tu closed, We-Sa 11:00-18:00, Su 01:00-16:00

Mon-Thu & Sun: 12:00PM to 2:00AM, Fri-Sat: 12:00PM to 2:30AM 
Mo-Th,Su 12:00-02:00; Fr-Sa 12:00-02:30

**Comment by frodrigo** [comment]
@rezemika @fgouget interested to look at this issue ?

**Comment by rezemika** [comment]
Sorry, I'm in an exam period and I don't have so much time... To be honest, I don't know if I will be able to maintain this project on the long term... :/

**Comment by frodrigo** [comment]
If nobody able to maintain or fix this plugin I will disable it. Sorry for all time already spend on it.
Too many issues opened on it #433 #490 #492 #498.

**Comment by HubMiner** [comment]
@frodrigo, in the interest of reducing backlog to meaningful scope: should I cancel this request, and I'll slowly work through this long list over time, submitting and addressing specific cases?

If anyone else is interested in addressing these, I will gladly work together.
