### ISSUE TITLE
New feature: find overlapping interpolations

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#491]
In Canada we have a lot of poor interpolation data due to how "Canvec" data is imported into OSM.

I wrote a script that uses overpass data to find these problems.  However, it would be much better to have this integrated into OSMOSE.  Code is located here: https://gist.github.com/matthewdarwin/4dd2712f7401dbd789b68e28d57b3614

Input required:

```
[out:json][timeout:900];
(
        way["addr:interpolation"](44.96,-76.35,45.54,-75.23);
        node(w)["addr:housenumber"](44.96,-76.35,45.54,-75.23);
);
(._;>;);
out body;
```

**Comment by frodrigo** [comment]
Please, can you explain what do the code? To integrate to to Osmose we probably have to rewrite it as SQL.

**Comment by matthewdarwin** [comment]
Yes, I'm sure it needs to be re-written. 

An interpolation line (way) should have 2 nodes with addresses... One at each end.  An interpolation should not have any other information attached.  This script finds interpolations that do not match this criteria by having

1) not enough addresses
2) too many addresses
3) interpolation overlaps another interpolation
It doesn't check that the addresses are actually at the end of the way or not.... that could be improved.

The cleanup usually involves manually joining or removing adjacent interpolations.

Basically the script puts all the address nodes into a hash by lat/long (hash value storing number of occurrences).  Then it puts all the nodes on the way into a hash by lat/long (hash value storing number of occurrences).  Then it count how many of those lat/long are used along each interpolation line multiple times, or if there are more than 2 addresses. It's fairly simplistic but finds a lot of errors.

Maybe some sample output would help:

```
[IIA] (w75693037) using (n893594082) has count_address=<1>, and count_other=<0> assigned to the interpolation
[IIA] (w75695529) has count_address=<0>, and count_other=<0> assigned to the interpolation
[IIA] (w87644777) using (n1019319263,n1019319689) has count_address=<2>, and count_other=<1> assigned to the interpolation
[IIA] (w87645003) using (n1019319152,n1019318030) has count_address=<2>, and count_other=<15> assigned to the interpolation
```

**Comment by matthewdarwin** [comment]
Other possible enhancement, if the "addr:interpolation" on the way is "even", then check the "address:housenumber" are actually divisible by 2 on the nodes.  Similarly for "addr:interpolation" = "odd".

**Comment by matthewdarwin** [comment]
OSM Inspector also finds "needless interpolations"

http://tools.geofabrik.de/osmi/?view=addresses&lon=-76.19521&lat=45.22189&zoom=18&overlays=no_addr_street,street_not_found,place_not_found,misformatted_housenumber_lenient,interpolation,interpolation_errors

**Comment by frodrigo** [comment]
- Unless I'm wrong, an interpolation way can more then 2 addr nodes in addition of the both ends.
- "interpolation overlaps another interpolation": what do you mean by "overlaps"? connected at a same addr node ? Can we replace by testing geometrical intersection?

**Comment by frodrigo** [comment]
I build a whole new analyser for interpolations including your rules and others.

On Ontario:
- class / count / label
- 100 / 154 / Interpolation on nodes without tag "addr:housenumber"
- 101 / 550 / "addr:housenumber" in multiple interpolations
- 102 / 2603 / Interpolation intersection
- 103 / 29 / Interpolation ends should have tag "addr:housenumber"
- 104 / 55492 / Interpolation ends should have have different tag "addr:housenumber
- 16 / 549 / Interpolation on nodes of multiple street names (this rule already exists)

Some output samples to review.

Class 100
node version="1" user="" lat="43.8258441" lon="-79.0942648" id="412041831"
node version="1" user="" lat="43.8253454" lon="-79.0940744" id="412041833"
node version="2" user="" lat="43.5917095" lon="-79.6367187" id="432783138"
node version="1" user="" lat="43.5919058" lon="-79.6365015" id="600645224"
node version="2" user="" lat="43.6715305" lon="-79.4084033" id="5942866526"
node version="2" user="" lat="43.6709164" lon="-79.4089684" id="5942866505"
node version="2" user="" lat="43.6720811" lon="-79.4086392" id="5942865784"
node version="3" user="" lat="43.6463118" lon="-79.4275874" id="803216782"
node version="2" user="" lat="43.7099455" lon="-79.4814549" id="2092891196"
node version="1" user="" lat="43.6889127" lon="-79.4425459" id="6426955279"
node version="1" user="" lat="43.6904972" lon="-79.4431879" id="6426947067"
node version="1" user="" lat="43.6865896" lon="-79.4428265" id="6223716789"
node version="3" user="" lat="43.7191659" lon="-79.3993603" id="803420235"
node version="1" user="" lat="43.7190491" lon="-79.3999108" id="2970304034"
node version="6" user="" lat="43.7303997" lon="-79.4037642" id="517227442"
node version="1" user="" lat="43.6881452" lon="-79.4254288" id="6402058960"
node version="2" user="" lat="43.6603664" lon="-79.3661925" id="4253515371"
node version="3" user="" lat="43.6835973" lon="-79.3231464" id="874979374"
node version="2" user="" lat="44.2604004" lon="-76.5590952" id="276021858"
node version="2" user="" lat="44.4643285" lon="-76.500663" id="805313947"

Class 101
node version="3" user="" lat="44.7465674" lon="-79.8895241" id="388944442"
node version="5" user="" lat="43.623376" lon="-79.5955129" id="390361537"
node version="4" user="" lat="43.6226404" lon="-79.5940482" id="390361627"
node version="4" user="" lat="43.777283" lon="-79.3854896" id="391072100"
node version="4" user="" lat="43.7776134" lon="-79.385481" id="391072102"
node version="3" user="" lat="43.6048676" lon="-79.6043888" id="626060941"
node version="3" user="" lat="43.5955693" lon="-79.6622404" id="653012804"
node version="4" user="" lat="43.6496398" lon="-79.4338091" id="803230824"
node version="3" user="" lat="43.7292765" lon="-79.4984357" id="803328404"
node version="3" user="" lat="43.712789" lon="-79.3588683" id="803513340"
node version="3" user="" lat="44.3879757" lon="-76.7708342" id="805364147"
node version="4" user="" lat="44.0473928" lon="-80.1629034" id="807078904"
node version="2" user="" lat="44.0408901" lon="-80.194268" id="807079004"
node version="2" user="" lat="44.0620355" lon="-80.2344903" id="807079040"
node version="2" user="" lat="44.000029" lon="-80.2041792" id="807079051"
node version="2" user="" lat="44.0135779" lon="-80.1883637" id="807079069"
node version="2" user="" lat="44.0585487" lon="-80.2484321" id="807079151"
node version="2" user="" lat="44.0582703" lon="-80.2486811" id="807079260"
node version="2" user="" lat="44.0585009" lon="-80.2486689" id="807079372"
node version="3" user="" lat="44.0513542" lon="-80.1470069" id="807079420"

Class 102
location lat="43.7789535010413" lon="-79.3862862479999" /
location lat="43.7793800810721" lon="-79.3864699511133" /
location lat="43.6587086088531" lon="-79.4228058173466" /
location lat="43.6592142056032" lon="-79.4203145583811" /
location lat="43.7132200175036" lon="-79.3776875394199" /
location lat="43.6934426100926" lon="-79.348048788092" /
location lat="43.7444396" lon="-79.2834182" /
location lat="43.7442791" lon="-79.2833313" /
location lat="43.6606903206638" lon="-79.3533606674408" /
location lat="43.6806585201856" lon="-79.3478937273101" /
location lat="43.6824734558535" lon="-79.3508646108955" /
location lat="43.6813854303485" lon="-79.3032702255524" /
location lat="43.6812317516362" lon="-79.3039160619717" /
location lat="44.3290098948854" lon="-76.875880356168" /
location lat="44.2417643326678" lon="-76.4946924097487" /
location lat="44.0046321315931" lon="-80.0000558858311" /
location lat="43.9999751258721" lon="-80.1173248368901" /
location lat="43.561919331935" lon="-79.7692811414966" /
location lat="43.5342757172984" lon="-79.8540812650623" /
location lat="43.5323153907924" lon="-79.8562507438093" /

Class 103
location lat="43.8258441" lon="-79.0942648" /
location lat="43.8253454" lon="-79.0940744" /
location lat="43.7191659" lon="-79.3993603" /
location lat="44.4643285" lon="-76.500663" /
location lat="43.5845669" lon="-79.7901769" /
location lat="43.6690835" lon="-79.8271626" /
location lat="43.7057161" lon="-79.7633057" /
location lat="43.6665271" lon="-79.4634227" /
location lat="43.6613376" lon="-79.6080661" /
location lat="43.8421994" lon="-79.3215636" /
location lat="43.7048776" lon="-79.6901207" /
location lat="43.885452" lon="-79.3004054" /
location lat="43.1646081" lon="-80.2971853" /
location lat="43.1645322" lon="-80.2976756" /
location lat="43.1646262" lon="-80.2970682" /
location lat="43.1645662" lon="-80.2977454" /
location lat="43.1029563" lon="-80.875" /
location lat="43.2226117" lon="-80.6427362" /
location lat="43.2468544" lon="-80.652883" /
location lat="43.3611389" lon="-80.358543" /

Class 104
location lat="43.6214899" lon="-79.4850561" /
location lat="43.6232252" lon="-79.4927109" /
location lat="43.6220844" lon="-79.4816704" /
location lat="43.6703197" lon="-79.4136539" /
location lat="43.6710442" lon="-79.4160027" /
location lat="43.6680722" lon="-79.4121041" /
location lat="43.6822708" lon="-79.4234612" /
location lat="43.6791922" lon="-79.4285648" /
location lat="43.6800675" lon="-79.4360661" /
location lat="43.6848026" lon="-79.3840318" /
location lat="43.6763662" lon="-79.3977062" /
location lat="43.6833908" lon="-79.4025246" /
location lat="43.6779799" lon="-79.40495" /
location lat="43.6839975" lon="-79.3795448" /
location lat="43.6744156" lon="-79.3777868" /
location lat="43.6376802" lon="-79.4201911" /
location lat="43.6513481" lon="-79.4309949" /
location lat="43.654227" lon="-79.4370266" /
location lat="43.7031585" lon="-79.476653" /
location lat="43.6888723" lon="-79.4942748" /

Class 16
location lat="43.7085934" lon="-79.271995" /
location lat="43.6497298" lon="-79.4352926" /
location lat="43.6496398" lon="-79.4338091" /
location lat="43.7292765" lon="-79.4984357" /
location lat="43.7292765" lon="-79.4984357" /
location lat="43.7386047" lon="-79.4023179" /
location lat="43.7310659" lon="-79.4039268" /
location lat="43.713243" lon="-79.3570573" /
location lat="43.7121096" lon="-79.3585857" /
location lat="43.6719" lon="-79.2958683" /
location lat="43.9155147" lon="-80.0865688" /
location lat="44.2255186" lon="-76.493246" /
location lat="44.2390212" lon="-76.4906908" /
location lat="44.2253978" lon="-76.4935034" /
location lat="43.5162897" lon="-79.8025995" /
location lat="43.531512" lon="-79.8434416" /
location lat="43.5303509" lon="-79.8424129" /
location lat="43.5202567" lon="-79.8506876" /
location lat="43.5115247" lon="-79.8406228" /
location lat="43.5108912" lon="-79.840178" /

**Comment by matthewdarwin** [comment]
Re: 
>>   Unless I'm wrong, an interpolation way can more then 2 addr nodes in addition of the both ends.

I am not sure.  I don't see it used that way in Canada.  Always 2 addresses, one at each end, unless it is broken.

>>    "interpolation overlaps another interpolation": what do you mean by "overlaps"? connected at a same addr node ? Can we replace by testing geometrical intersection?

Yes.

**Comment by frodrigo** [comment]
Results expects at: http://osmose.openstreetmap.fr/en/errors/?item=2060&class=100,101,102,103,104

**Comment by frodrigo** [comment]
Analyser does not report this kind of thing: https://www.openstreetmap.org/way/85894260

**Comment by frodrigo** [comment]
Add class 20601 "Misusing addr:interpolation in combination with other tags"
http://osmose.openstreetmap.fr/en/errors/?item=2060&class=100,101,102,103,104,20601
