### ISSUE TITLE
opening_hours false positive: date range 00-24

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-backend#492]
Sample false positive:
May 3-Sep 08:00,00:00-24:00
https://www.openstreetmap.org/node/2933398141

The value is valid according to 
https://openingh.openstreetmap.de/evaluation_tool/

**Comment by HubMiner** [comment]
I was wrong (this is not false positive); updated request:
Original value: May 3-Sep 8, 00:00-24:00
Suggested value: May 03-Sep 08 00:00-24:00

**Comment by frodrigo** [comment]
The issue is no more on Osmose.
It's about bad fix on `May 3-Sep 8,00:00-24:00` to `May 3-Sep 08:00,00:00-24:00`?

**Comment by Bibi56** [comment]
24/7 is a more usual way to say that.

**Comment by frodrigo** [comment]
The question is not about doing it better in canonical way. But just make right suggestion. If I'm right the issue is on Sep 8, not hours.

**Comment by HubMiner** [comment]
As frodrigo said, the issue was about bad proposed fix where ":00" was added to date.

Comma before hours is confusing but is valid according to https://openingh.openstreetmap.de/evaluation_tool/

Bibi56, all of the following are valid and evaluate to the same (according to the same tool), but that would be additional enhancement.
May 3-Sep 8 00:00-24:00
May 3-Sep 8 24/7
May 3-Sep 8, 24/7
May 3-Sep 8, 24/7 open

**Comment by frodrigo** [comment]
@rezemika @fgouget interested to look at this issue ?

**Comment by rezemika** [comment]
Ah OH Sanitizer considers alone digits as hours if they are separated by commas, it could be possible to fix this, but it would remove some fix capabilities. Unfortunately, I am quite overwhelmed these times...

**Comment by frodrigo** [comment]
If nobody able to maintain or fix this plugin I will disable it. Sorry for all time already spend on it.
Too many issues opened on it #433 #490 #492 #498.

**Comment by frodrigo** [comment]
This item is now hidden on the Osmose Frontend.
Can be accessed via http://osmose.openstreetmap.fr/en/errors/?item=3250&useDevItem=all
