### ISSUE TITLE
New feature: street not found nearby

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#493]
OSM Inspector has a great tool to highlight addresses assigned to a street, but the street does not exist.  I use this all the time, and it would be great if OSMOSE had the same thing.  It is great for finding minor spelling errors.
 
I think they use something like a 1km radius.

http://tools.geofabrik.de/osmi/?view=addresses&lon=-77.80103&lat=44.44441&zoom=12&overlays=street_not_found

**Comment by frodrigo** [comment]
Osmose already have a set of check about this:
- https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_associatedStreet.py#L576
- http://osmose.openstreetmap.fr/en/errors/?country=canada*&item=2060

**Comment by matthewdarwin** [comment]
It seems to be not working then, because http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=44.504698&lon=-77.474666&item=1010%2C1040%2C1050%2C1060%2C1070%2C1080%2C1090%2C1100%2C1110%2C1120%2C1140%2C1150%2C1160%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1260%2C1270%2C2xxx%2C3xxx%2C4xxx%2C5xxx%2C6xxx%2C7xxx%2C8xxx%2C9xxx&level=1%2C2%2C3&tags=&fixable= should show lots of these errors, but I see none.

**Comment by frodrigo** [comment]
The check look for `addr:street` (and other) tag. Not looking for the street with the same name around (but it's done when using associatedStreet relation https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_associatedStreet.py#L582 ). This check was primarily done to cross check the consistency of associatedStreet relations. But we can extend it to relationless addr:street.

**Comment by frodrigo** [comment]
Results expects here: http://osmose.openstreetmap.fr/en/errors/?item=2060&class=19

But first results on Ontario show the distance to the street should be increased. It's at 200m.

**Comment by frodrigo** [comment]
I have an issue with this. Larger distance induce longer computation.

Number of addr:street nodes by distances to the street in Ontario. At range 1990-2000m still 25 566 nodes.
![image](https://user-images.githubusercontent.com/1785486/57572557-5b3ad780-741c-11e9-9a75-b426cdfc48ff.png)

Run a computation up to 5000m, but still computing. Such large range no make sens in European countries. I think it should be a country specific parameter.

**Comment by matthewdarwin** [comment]
Thanks for working on this.  Sorry for the extra challenge! :-)

There may be many errors in Ontario as roads got renamed but the associated addressees (usually interpolations) did not. Telenav was doing this until I mentioned it to them about 1 year ago.  But it definitely needs to be more than 200m for rural areas.

Not sure if you can do something based on density.... if there are lots of addresses, then the boundary is much closer and when there are fewer addresses, boundary gets further.   Then it would work better anywhere.  The middle of a city is very different than the middle of countryside.

Ottawa (where I live https://www.openstreetmap.org/relation/4136816) has more rural areas than urban areas, but most people live in urban area.... so having a formula that works on county boundaries won't work to determine urban/rural split.

**Comment by frodrigo** [comment]
Distance is now at 500m for all countries.

**Comment by frodrigo** [comment]
Canada and New Zeeland have now the distance set to 2000m. Ask for more.

Note: all region still not up to date
http://osmose.openstreetmap.fr/en/errors/?country=canada*&item=2060&class=19
http://osmose.openstreetmap.fr/en/errors/graph.png?item=2060&class=19&country=canada*
