### ISSUE TITLE
opening_hours: "12pm - 12am"

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-backend#498]
opening_hours autocorrection does not handle 12 correctly.
Hopefully this is the representative example:
"12pm - 12am" should return  "12:00-00:00" or "12:00-24:00"; currently returns "24:00-12:00".

**Comment by frodrigo** [comment]
@rezemika @fgouget interested to look at this issue ?

**Comment by frodrigo** [comment]
If nobody able to maintain or fix this plugin I will disable it. Sorry for all time already spend on it.
Too many issues opened on it #433 #490 #492 #498.

**Comment by frodrigo** [comment]
This item is now hidden on the Osmose Frontend.
Can be accessed via http://osmose.openstreetmap.fr/en/errors/?item=3250&useDevItem=all
