### ISSUE TITLE
integration sports : mauvais tag

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#499]
Item 9001
Class 9001001

En intégrant avec Osmose un jeu de paintball, Osmose propose ;

Tag | Value
-- | --
source | Le ministère de la ville, de la jeunesse et des sports - 01/2018
sport | shooting
surface | grass
__type__ | paintball

type est déprécié, il faudrait  shooting : 

Tag | Value
-- | --
__shooting__ | paintball
source | Le ministère de la ville, de la jeunesse et des sports - 01/2018
sport | shooting
surface | grass

Extrait du Wiki :

Tag | Description | Values
-- | -- | --
/shooting=clay_pigeon/shooting=indoor_range type=* | Indicate the type of shooting. Do not use type=*, which is meant to specify the type of relations (such as type=multipolygon). | range or clay_pigeon or paintball or indoor_range

**Comment by frodrigo** [comment]
Result expected here : http://osmose.openstreetmap.fr/en/errors/?source=5833&item=8170&class=183

**Comment by frodrigo** [comment]
@Bibi56 you could migrate already integrated data.

**Comment by Bibi56** [comment]
@frodrigo looks good now. Thanks.
