### ISSUE TITLE
French postal codes and Osmose : which tagging?

### ISSUE THREAD

**Issue by bibi6** [osm-fr/osmose-backend#504]
Hi,

I'm puzzled with the way Osmose signals issues with postal codes in France...

Please have a look on these two neighbouring villages:
Lourches: https://www.openstreetmap.org/relation/56082#map=14/50.3110/3.3411
Rœulx: https://www.openstreetmap.org/relation/56093#map=14/50.3110/3.3411

The postal code of the former is tagged with "postal_code". It is signalled by Osmose by 2 issues: http://osmose.openstreetmap.fr/fr/error/26517612431, http://osmose.openstreetmap.fr/fr/error/26517611530 . "So far so good, then, change the tag postal_code to addr:postcode!" But...

The latter is tagged with addr:postcode, and Osmose still signals it! http://osmose.openstreetmap.fr/fr/error/26496525511

So, what is the good practice for tagging postal codes? From what I see from Overpass in my region, it looks like addr:postcode is mostly used in France... and postal_code in Belgium :s 
addr:postcode : https://overpass-turbo.eu/map.html?Q=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Cboundary%20and%20addr%3Apostcode%E2%80%9D%0A*%2F%0A%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Cboundary%20and%20addr%3Apostcode%E2%80%9D%0A%20%20relation%5B%22boundary%22%5D%5B%22addr%3Apostcode%22%5D(49.62316641036844%2C2.6477050781249996%2C50.89263913111063%2C4.36431884765625)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B
postal_code: https://overpass-turbo.eu/map.html?Q=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Cboundary%20and%20addr%3Apostcode%E2%80%9D%0A*%2F%0A[out%3Ajson][timeout%3A25]%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Cboundary%20and%20adpostcode%E2%80%9D%0A%20%20relation[%22boundary%22][%22postal_code%22](49.62316641036844%2C2.6477050781249996%2C50.89263913111063%2C4.36431884765625)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B

**Comment by frodrigo** [comment]
Ops. The right tag is `postal_code`.

**Comment by frodrigo** [comment]
Result are here
http://osmose.openstreetmap.fr/fr/errors/?item=8221

But now half of France have a postal code issue :-/

**Comment by frodrigo** [comment]
We do the right move. All right.
