### ISSUE TITLE
Addresses should be allowed near proposed or under construction streets

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#506]
http://osmose.openstreetmap.fr/en/map/#item=2060&zoom=18&lat=45.323108&lon=-75.586265&level=1%2C2%2C3&tags=&fixable=

Has this error:
```
Tag "addr:street" not matching a street name around
Findlay Creek Drive
node 6410656701 rawedit josm edit
addr:housenumber = 3341
addr:street = Findlay Creek Drive
osm-show osm-edit josm-zone details
Issue reported on: 2019-05-12 
```

Findlay Creek Drive is highway=proposed.  Proposed roads should be allowed to have (proposed) addresses.

![image](https://user-images.githubusercontent.com/26171839/57745380-ed501380-769a-11e9-8ee7-5d1624f479e5.png)

**Comment by frodrigo** [comment]
For efficiency it use common highway table without proposed, construction...
More over construction seam acceptable to me, but proposed highway no.

**Comment by matthewdarwin** [comment]
I think this address check will be less than helpful for me then and I will keep using the one from Geofabik...   Too many false positives with this issue as well as the fact that "near" is not a wide enough boundary.

**Comment by frodrigo** [comment]
Distance setting by country still to be done.

**Comment by frodrigo** [comment]
It's done with 'planned', 'proposed', 'construction'.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=2060&class=19
