### ISSUE TITLE
Item 2060 - Should associatedStreet account square names?

### ISSUE THREAD

**Issue by fansanelli** [osm-fr/osmose-backend#507]
Hello,
I'm experiencing this kind of error:

2788 | 2 | 2060 numero civico | 19 | 1 | E | 7.54 44.38 | n  6131629935    (j) | Piazza Secondo Reggimento Alpini
-- | -- | -- | -- | -- | -- | -- | -- | --

because it doesn't exists a street named "Piazza Secondo Reggimento Alpini", but it does exists a place=square with that name.
I haven't found any reference to squares in this file:
analysers/analyser_osmosis_relation_associatedStreet.py

Could you please check?
Many thanks
Best Regards,
Francesco

**Comment by frodrigo** [comment]
The piazza is not a street but a place, the write way is to use `addr:place` in place of `addr:street`.
https://www.openstreetmap.org/way/211123375

**Comment by Bibi56** [comment]
I confirm, associatedStreet is only for streets, there is no equivalent for places in general, squares in particular. Nominatim wouldn't work in that case either.

**Comment by frodrigo** [comment]
Reopen if required.
