### ISSUE TITLE
Street number test incompatible with Czech addresses

### ISSUE THREAD

**Issue by majkaz** [osm-fr/osmose-backend#508]
The test will fail probably on every address in Czechia. The same might be true for Slovakia as well.

The commonly used [Czech schema](https://wiki.openstreetmap.org/wiki/Cs:WikiProjekt_%C4%8Cesko/Syst%C3%A9m_adres#.C4.8C.C3.ADslo_eviden.C4.8Dn.C3.AD) has to account for several possible ways of numbering houses, including [streetnumber](https://wiki.openstreetmap.org/wiki/Key:addr:streetnumber), [constcriptionnumber](https://wiki.openstreetmap.org/wiki/Key:addr:conscriptionnumber) and [provisionalnumber](https://wiki.openstreetmap.org/wiki/Key:addr:provisionalnumber). The housenumber then contains a combination of streetnumber / conscriptionnumber / provisionalnuber according the official Czech address system.

Would it be possible to disable this test completely for Czech addresses?

**Comment by frodrigo** [comment]
All classes of this analyser are not strictly on street numbers, some are on number, some on street or the relation between them.

The full list of classes is here:
- http://osmose.openstreetmap.fr/en/errors/?country=czech_republic_jihocesky&item=2060&level=1%2C2%2C3

Please can you review it and tell witch ones must be disabled.

**Comment by majkaz** [comment]
Sorry, it seems there is something else wrong than I thought initially. The provisional numbers have to be corrected, there are some with spaces instead of the correct "ev.[number]" variant. If written correctly, there is no error message.
The rest of genuine error messages seems to be a problem of lower/uppercase change or name variant (abbreviation on official address, expanded in OSM). The first one could be corrected either on the street or on the address points. I am not sure, if anybody can do something for the second case - in my town, about half of the street will have a difference - technically correct are the abbreviated names in the address points, OSM "wants" to have them expanded.

But I am not sure, why this shows error: This part of [map](http://osmose.openstreetmap.fr/cs/map/#item=2060&level=2&tags=&fixable=&bbox=14.344368%2C48.8954211%2C14.6255493%2C49.0765647&zoom=17&lat=48.972231&lon=14.509152) all the errors are false positives.

Other cases:
http://osmose.openstreetmap.fr/cs/error/26735425946
http://osmose.openstreetmap.fr/cs/error/26735426163
http://osmose.openstreetmap.fr/cs/error/26735426008
(all addresses on these streets, the same name is written on the address point and street name, as far as I can see)

It is not only local problem, here is [similar case](http://osmose.openstreetmap.fr/cs/error/26734663892) or [this one](http://osmose.openstreetmap.fr/cs/error/26734676962) in Prague.

**Comment by frodrigo** [comment]
- About the "ev.[number]" and with space. It require a dedicated analyser to suggest the add of the dot, of the space should be see as valid/acceptable?

- Case of "nám. Přemysla Otakara II." and "nám. Přemysla Otakara Ⅱ.", not the char "Roman Numeral Two" in the last https://www.compart.com/fr/unicode/U+2161
- Case of "Jiřího z Poděbrad" and "Jiřího z Poděbrad", there is "No-Break Space" in one https://www.compart.com/fr/unicode/U+00A0
- Case of "K Dolíčku", the same, abusive no break space

**Comment by frodrigo** [comment]
Ping

**Comment by frodrigo** [comment]
Reopen if required.
