### ISSUE TITLE
False positive: amenity=bench Street object bench observed around but not associated tags

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#512]
False positive: 
"amenity=bench Street object bench observed around but not associated tags".

Mapillary shows "Street object", but most of them are not "amenity=bench", but:
- gate (mostly: wooden gate as found in the country side)
- shadow of a gate on the grass
- traffic_barrier
- railing ("fence=railing" or "railing" on a building or bus shelter).

I also notice a lot of Mapillary images referred to by Osmose in which I cannot find a "bench" being marked as such by Mapillary. In some of these Images I do see a "bench", but that one is not marked as "bench". Wondering which "bench" is being referred by Osmose.

A "bicycle parking" is not always a "bicycle_parking", but - sometimes - a "barrier=cycle_barrier" or just a "fence".

And yes, some benches are indeed missing on OSM. However, even some of those are "private" (located in front of a private house). Therefore not mapped (by me).

False positives (like "opening_hours"!) on Osmose are not harmless:
- distracting
- covering real errors
- demotivating
- acting on a false positive might result in a real error!
F.i. change "barrier=cycle_barrier" into "amenity=bicycle_parking"
- I prefer benches not on OSM (most likely I won't even notice in real life) to benches on OSM, but not "on the ground". 
- bad for Osmose image and might even result in ignoring Osmose by some OSM-mappers. 

I don't think Mapillary "streets object" are - in this state - useful for Osmose "Error" detection.
Specially since I notice tens of false positives in a small circle.
Location: Woerden, The Netherlands.

**Comment by frodrigo** [comment]
About opening_hours we deploy many fixes just yesterday. The data on Osmose is under update. I was close to remove the opening_hours but @HubMiner fix the code.

**Comment by frodrigo** [comment]
For street objects the main part is about missing traffic light.
I agree, I will disable bench.

**Comment by HubMiner** [comment]
Based on many map corrections I made in the last few days, it looks like opening_hours show style suggestions as errors.  My intention was that if there only if a real error fix needed, suggestions would kick in.  I am new to this code and would need some experienced guidance to address this.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=8360&class=1
