### ISSUE TITLE
admin_level=8 without postcode

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#513]
I'm getting errors that seem to be false positive:

key | value |  comment
-- | --| --
item | 7160  |  code postal, intégration possible
class | 2

Example: http://osmose.openstreetmap.fr/fr/error/26932243546
According to the error message I should add a addr:postcode but there is such a key in the relation.

I get the error message a second time as :

key | value
-- | --
item | 8221
class | 3
subclass | 1822854330

http://osmose.openstreetmap.fr/fr/error/26932415280

So maybe you check for postal_code but ask for addr:postcode

**Comment by frodrigo** [comment]
We fixed the analyser but not the message.
The right tag is `postal_code`.
