### ISSUE TITLE
Adresses should remain valid even if the street is under construction

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osmose-backend#514]
Hi,
Sometimes the streets are under construction.
They are switched from highway=secondary;service;... to construction=secondary;service;... + highway=construction.

I propose that OSMOSE stops reporting false positive errors when it faces this situation.
For example here http://osmose.openstreetmap.fr/fr/error/26950263994 with this street under construction https://www.openstreetmap.org/way/38098705

@frodrigo I think you already agree: you mentioned this problem in an existing issue https://github.com/osm-fr/osmose-backend/issues/506

**Comment by frodrigo** [comment]
Duplicate #506

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=2060&class=19
It's done with 'planned', 'proposed', 'construction'.

**Comment by matthewdarwin** [comment]
Looks good now.  Thank you.
