### ISSUE TITLE
Opening_hours : osmose wrongly suggests replace "," with ";" 

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#515]
Hi everybody,

I saw an osmose alert, suggesting to replace 
  `Mo-Sa 08:30-12:30, Mo-Fr 13:45-19:00, Sa 13:45-18:00`
by 
   `Mo-Sa 08:30-12:30; Mo-Fr 13:45-19:00; Sa 13:45-18:00`.

According to https://openingh.openstreetmap.de/evaluation_tool/, these two values have different meanings, and IMHO, the original value is correct and should not be modified (or should be replaced by `Mo-Fr 08:30-12:30,13:45-19:00; Sa 08:30-12:30,13:45-18:00`).

Osmose error : http://osmose.openstreetmap.fr/en/error/26954510618

key | value 
-- | -- 
source | 411632
item | 3250
class | 32501
subclass | 0
elems | node4331164652
lat lon | 45.5867079 5.2777870
title |  Invalid Opening Hours  |
subtitle |  
timestamp | 2019-05-20 18:08:02

key | value
-- | --
elem_index | 0
type id | N 4331164652
tags |   
amenity | pharmacy |  
dispensing | yes |  
name | Pharmacie Liberté |  
opening_hours | Mo-Sa 08:30-12:30, Mo-Fr 13:45-19:00, Sa 13:45-18:00 |  
ref:FR:FINESS | 380003582 | http://finess.sante.gouv.fr/fininter/jsp/actionDetailEtablissement.do?noFiness=380003582
source | Celtipharm - 10/2014 |  
wheelchair | yes |  
username | lendar

key | value 
-- | --
diff_index | 0
elem_data_type | N
elem_id | 4331164652
tags_create |  
tags_modify | opening_hours : Mo-Sa 08:30-12:30; Mo-Fr 13:45-19:00; Sa 13:45-18:00 |  
tags_delete |

**Comment by frodrigo** [comment]
Ping @HubMiner @rezemika @fgouget

**Comment by frodrigo** [comment]
This item is now hidden on the Osmose Frontend.
Can be accessed via http://osmose.openstreetmap.fr/en/errors/?item=3250&useDevItem=all

**Comment by HubMiner** [comment]
@laurentriffard, all valid points.  I confirmed that both "evaluation_tool" and OsmAnd understand this syntax.

@frodrigo, how would you like to handle this?  The current OH module does not handle the complexity with overlapping days, "evaluation_tool" handles it.  My change with ","->";" made the problem visible.

**Comment by frodrigo** [comment]
Can we start by splinting on `;` and check chunck by chunck?

**Comment by HubMiner** [comment]
Addressed by #522

**Comment by frodrigo** [comment]
It was deployed yesterday lat. Now data are almost up to date on osmose frontend.

**Comment by HubMiner** [comment]
frodrigo, does it make sense to reenable opening_hours/3250 on the frontend?
At least, I would like to see the statistic for the error type.

**Comment by frodrigo** [comment]
The stats are still available. Click on graph from the list page.

We are now back to the level we have before. Can you play with the results,
fix some issues around the world to status on the quality. Then we can
enable. Onpen GitHub issue, even if we do not fix it for now.
