### ISSUE TITLE
Trees also can be on a rooftop

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osmose-backend#516]
Hi,
I think that the test looking for a building overlapping a tree can be more precise.
The level and layer of both elements should be taking into account.
Please see for example an existing tree on a rooftop : http://osmose.openstreetmap.fr/fr/error/26950233062

Merci

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=1070&class=2
