### ISSUE TITLE
ref:mhs test: unexpected issue

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osmose-backend#517]
Hi,
I don't understand why I get this issue:

clé | valeur
-- | --
source | 5150
item | 7080
class | 2
subclass | 0
elems | way62646379
lat lon | 48.8078678 2.3215662
title | enHistorical monument without tag "ref:mhs" or invalid                 frMonument historique sans attribut “ref:mhs” ou incorrect                 nlHistorisch monument zonder tag "ref:mhs" of ongeldig                 ukІсторичний монумент без теґу "ref:mhs" або недійсний | en | Historical monument without tag "ref:mhs" or invalid | fr | Monument historique sans attribut “ref:mhs” ou incorrect | nl | Historisch monument zonder tag "ref:mhs" of ongeldig | uk | Історичний монумент без теґу "ref:mhs" або недійсний
en | Historical monument without tag "ref:mhs" or invalid
fr | Monument historique sans attribut “ref:mhs” ou incorrect
nl | Historisch monument zonder tag "ref:mhs" of ongeldig
uk | Історичний монумент без теґу "ref:mhs" або недійсний
subtitle |  
timestamp | 2019-05-20 19:29:02

I double checked and the ref:mhs = IA94000411 tag should be valid.
Am I missing something here?
Thanks for your help

**Comment by frodrigo** [comment]
This analyser work with the Merimee data base, all the ref start with "PA", it's able ignore Palissy ref "PM". But what is the an "IA" ref ?

**Comment by frodrigo** [comment]
ping

**Comment by frodrigo** [comment]
Reopne if required.

**Comment by overflorian** [comment]
I found the ref number beginning with "IA" on the official website: 

> Référence de la notice
> IA94000411

Please see https://www.pop.culture.gouv.fr/notice/merimee/IA94000411
Is it not the proper ref number to use?
Thanks

**Comment by overflorian** [comment]
PS : I don't know how to re-open this issue :/

**Comment by frodrigo** [comment]
So, It's on "Inventaire général du patrimoine culturel", but not an historical monument.
http://www2.culture.gouv.fr/public/mistral/merimee_fr?ACTION=CHERCHER&FIELD_1=REF&VALUE_1=IA94000411

**Comment by overflorian** [comment]
OK, I didn't know the difference. I do now.
Is there a specific tag I should use to reference this monument even if it's not an "historical monument" according to MERIMEE?

**Comment by frodrigo** [comment]
According to the wiki we can use AI ref.
https://wiki.openstreetmap.org/wiki/Key:ref:mhs
On Osmose we can ignore the AI ref, like we already do for the PM Palissy ref.

The OpenData only contains the historical monument part, not the "Inventaire général du patrimoine culturel". But Open local data base exists on this subject.

**Comment by overflorian** [comment]
>  On Osmose we can ignore the IA ref, like we already do for the PM Palissy ref.

Yes, great!

**Comment by frodrigo** [comment]
It's done.

One less issue in Montrouge.

**Comment by overflorian** [comment]
Merci Fred
