### ISSUE TITLE
False positive : Tag "addr:street" not matching a street name around

### ISSUE THREAD

**Issue by bilboed** [osm-fr/osmose-backend#518]
This issue happens for all addresses on squares/plazas/... which are highways tagged with `area=yes`.

For example this plaza in Montpellier : http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=43.599254&lon=3.897137&item=2060

My understanding is that this false-positive is because anything with `area=yes` gets excluded from the "highways" DB in `Analyser_Osmosis.py` , meaning that the later `Analyser_Osmosis_Relation_AssociatedStreet` can't match the addr:street against anything.

 The problem is that the historical way to mark pedestrian squares was to use `highway=pedestrian, area=yes` ... meaning that all addresses on that square will be marked as false positives.

While excluding "area" highways makes sense, would it make sense to also allow (whether area or not), the highways with `place=square` in the ways DB of `Analyser_Osmosis.py` ? Or would that be too disruptive and instead add that additional check in `Analyser_Osmosis_Relation_AssociatedStreet` ?

**Comment by frodrigo** [comment]
It's done.
