### ISSUE TITLE
amenity=parking capacity:disabled=yes

### ISSUE THREAD

**Issue by vinber** [osm-fr/osmose-backend#519]
for this : http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=44.863219&lon=-0.726598&item=8130&level=1%2C2%2C3&tags=&fixable=

Osmose offers these tags :
amenity = parking
capacity:disabled = yes
source = Bordeaux Métropole - 08/2016

Better these tags ?

amenity = parking
capacity:disabled = 1
source = Bordeaux Métropole - 08/2016

and even better
 
amenity = parking_space
capacity:disabled = 1
parking_space=disabled
source = Bordeaux Métropole - 08/2016

**Comment by frodrigo** [comment]
We are not sure the capacity is 1.

**Comment by frodrigo** [comment]
I think the Osmose way is not wrong. It's an other way to do.

**Comment by frodrigo** [comment]
Reopen if required.
