### ISSUE TITLE
False positive for CRAIG IGN source

### ISSUE THREAD

**Issue by Phyks** [osm-fr/osmose-backend#521]
Hi,

When using the following source, Osmose is raising an issue (probably because of the presence of "IGN" word): 

> CRAIG - IGN - TopoGEODIS - Feder Auvergne-Rhône-Alpes 2016 

This however should be a valid imagery source, available in iD/JOSM (opendata orthophotography).

Best,

**Comment by frodrigo** [comment]
Done. Reopen if required.
