### ISSUE TITLE
Street object, also match amenity=bicycle_parking with ways

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#523]
Osmose: amenity=bicycle_parking Street object bicycle parking observed around but not associated tags 

IMO: associated tags have been set correctly.

Sample: http://osmose.openstreetmap.fr/en/error/27579621715

OSM tags:

- way (15 meters)
- amenity=bicycle_parking
- bicycle_parking=stands
- capacity=20

Perhaps Osmose is expecting a node or an area?
I agree, this would be better. But I'm lazy and 12x (?) node or drawing an uncertain area is too much work (for me).
Or: node (or way) is "Quick and Dirty" and should be updated as an area as soon as possible?

OSM WIKI:

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking
_amenity=bicycle_parking:_

_- may be used on nodes_
**_- may be used on ways_**
_- may be used on areas_

For now, please ignore my other issue (OFF TOPIC):
Mapillary "Street object ****" is responsible for too many false positives.

**Comment by AnkEric** [comment]
I did find two other examples: 

http://osmose.openstreetmap.fr/en/error/27612376518
[amenity=bicycle_parking] as 2x **Node**

http://osmose.openstreetmap.fr/en/error/27612376540
[amenity=bicycle_parking] as **Area**

Both are reported as missing tags...

**Comment by frodrigo** [comment]
The fix is already on the way and deployed soon.
https://github.com/frodrigo/osmose-backend/commit/51404d68ed9551ead860985456cd3986a80bb7d7

**Comment by AnkEric** [comment]
Oké, I will wait and watch...

But also, the fix to be deployed is: "enable ways".
These examples are about Nodes and Areas.

Perhaps distance is also relevant?
As compared to "Tag "addr:street" not matching a street name around"?
"not around" implies a house is 50 meters away from street and no highway is mapped for access, or highway=service does not have a name set...
These are [amenity=bicycle_parking] not connected to any highway... (+ ???)

**Comment by frodrigo** [comment]
> But also, the fix to be deployed is: "enable ways".
> These examples are about Nodes and Areas.
Ways and areas are the the OSM data schema. Here the distance is 30m, can be changed.

> Tag "addr:street" not matching a street name around"
Distance is 2000m (5000m in CA et NZ)

**Comment by AnkEric** [comment]
>  Here the distance is 30m, can be changed.

**Which** distance are you referring to?
The distance between [Mapillary image location] and Area [amenity = bicycle_parking] is a minimum of 6 meters, a maximum of 20 meters.
See virtual way having a length of 10 meters (just to show distance).

**Who** should "change" the distance of 30m ?

Osmose? Osmose should be less restrictive ??

Or should I move  [amenity=bicycle_parking] closer to [highway=cycleway] ???
Would be oké, now I see a "Missing access way to parking" (not applicable to bicycle_parking however).
Connect [amenity=bicycle_parking] and [highway=cycleway] (giving access) ???

Or  should I move  [amenity=bicycle_parking] closer to [Mapillary image] location ????
IMO:  [Mapillary image] location is not relevant. I have seen images showing a bicycle_parking on more than 30 meters distance. Just because image location is not on bicycle_parking location. I must have been cycling too fast; -))

![image](https://i.postimg.cc/xjPB622R/Osmose-distance-to-bicycle-parking-2019-06-05.png)

**Comment by frodrigo** [comment]
Can you confirm it's now OK about the detection of amenity=bicycle_parking on ways ?

**Comment by AnkEric** [comment]
I have verified my three examples:

- amenity=bicycle_parking on **Way** (Woerden, Defensie-eiland) = **OK**
So: confirmed and thanks!
Sorry, I will not verify all bicycle+parking on Mapillary/Osmose; -)

- amenity=bicycle_parking on **Area** (Ameland, Oert Blinkert) = **OK**

- amenity=bicycle_parking on **Node** (Ameland, Johan de Jongpad (end)) = NOT OK
See: http://osmose.openstreetmap.fr/en/error/27705078140

A  bit OT: a way (line) is often NOT Rendered as POI.
NOT on: https://www.openstreetmap.org/#map=19/52.08456/4.88825
NOT on: OpenFietsMap, OsmAnd, my "own" Map
But if OSM-WIKI approves this is a Renderers Error (IMO).
So: Osmose is first to detect a POI tagged as Way! Good! But also: minority view ?!

More OT, this is (IMO) a dilemma:
Yesterday I changed [tourism=artwork] on a Node connected to footway into a Way.
Today I verified this tagging not to be rendered and reverted into 2x node.
https://www.mapillary.com/map/im/UiuW7-l8Wy17gX8sP2UFpw
I'm curious as to your opinion on this Changeset:
https://www.openstreetmap.org/changeset/71018361

Also "on the ground": 20 meters of one picnic_table.
https://www.mapillary.com/map/im/60a2A6AHTt1AATvUNoap2g
1x Way ?
7x Node ??
1x Node + [length=20] ???

Same applies to [barrier=*], except for [barrier=fence, guard_rail, wall].

OSM only (?) acknowledges [natural=tree_row] and [highway=parking_aisle] !

**Comment by frodrigo** [comment]
For the not found amenity=bicycle_parking, I found a bug in the matching computation.

**Comment by frodrigo** [comment]
Now it's OK.

Reopen dedicated issue to other subject if required.
