### ISSUE TITLE
opening_hours: 24

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-backend#526]
Is there a guideline on hour value above 23?
[OH wiki](https://wiki.openstreetmap.org/wiki/Key:opening%20hours?uselang=en-US ) says "HH: An absolute 2-digit hours number (in day, in 24h format, no am/pm) in range 00-23", yet the same page uses example: "Sa-Su 00:00-24:00".  Personally, I find "00:00-24:00" more readable.  Our current implementation proposes to change  "00:00-24:00" to "00:00-00:00" (thus many false positives).

[evaluation_tool](https://openingh.openstreetmap.de/evaluation_tool/#check) allows values over 23 and does not change them.  Should we do the same, or only change values over 24?

**Comment by frodrigo** [comment]
Yes, you are right, converting 24:00 to 00:00 is bad.
But no minute other than 00 should be allowed to 24.

**Comment by HubMiner** [comment]
Please assign this to me.
I'll add handling for H=24 and M=00.

Let me know if you have ideas how to identify that we are looking at second time specifier (hh:mm-hh:mm). I don't want to allow 24 in first time specifier.
