### ISSUE TITLE
opening hours categories

### ISSUE THREAD

**Issue by HubMiner** [osm-fr/osmose-backend#527]
I don't know if this was discussed before - have we explored integrating with 
[evaluation_tool](https://openingh.openstreetmap.de/evaluation_tool/#check)?  It would be great if Osmose would have separate categories for issues from the current module and from evaluation tool.

https://github.com/opening-hours/pyopening_hours

Also, I feel we could use more categories for OH:
- values that can't be parsed (need manual edits)
- values that are wrong but can be parsed (may be tricky to implement - need a way to evaluate what is "wrong")
- valid values with cosmetic cleanup

**Comment by frodrigo** [comment]
This python module require a JS runtime ? If it's the case I think i will be complicated to deployed it.

**Comment by HubMiner** [comment]
I think there is enough benefit here that we should try: that tool handles many cases that we do not.

**Comment by frodrigo** [comment]
Note sure. We have 40 backend servers handled by many people on many OS and deployement technologies (OS package, virtual env, Docker).
cc @jocelynj

**Comment by HubMiner** [comment]
Proposal for additional category for OH:

Consider example: Sa 11:30-01:00; Su 17:00-02:00
If closing time before separator has value past 00:00 (ex: 01:00), then separator should be comma or double pipe "||", so the rules are additive.  This example value is suspicious because rule after separator (Su...) is overriding previous value, losing 00:00-01:00 from "open hours" range.  (Opening hours validation tool does nice job visualizing this difference).  

I assume there are some rare cases when this auto-correction would not be desired, therefore I am proposing a separate category.

**Comment by frodrigo** [comment]
Adding a "category" is done by adding a class issue:
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Opening_Hours.py#L49

**Comment by frodrigo** [comment]
Reopen if required.
