### ISSUE TITLE
detect camp pitchs outside a camp site

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#530]
a camp pitch is a part of a site.
so all pitchs outside a site are : 
- an error : I found a lot of them that were sites
or
- a missing site, i never find this case, but it may happend
detecting those pitchs outside a site 'll help to fix tagging error or add missing site.

3 tags currently exist for a camp pitch :
tourism=camp_pitch
camp_site=camp_pitch
camp_site=pitch
it is useful to test all 3 even if a proposal is being discussed on tagginfo to depreciate the 2 conflicting tags.
2 sites need to be taken to avoid false-positive : tourism=camp_site and tourism=caravan_site

this analysis can be set as "show in dev mode only" to start with, so I can check that there are no false-positive that we would not have thought of

**Comment by frodrigo** [comment]
Can you write the mapcss code for the first case?

**Comment by frodrigo** [comment]
```sql
SELECT
  pitch.id
FROM
  ways AS pitch
  LEFT JOIN ways AS site ON
    site.linestring && pitch.linestring AND
    site.tags != ''::hstore AND
    site.tags?'tourism' AND
    site.tags->'tourism' IN ('camp_site', 'caravan_site')
WHERE
  pitch.tags != ''::hstore AND
  pitch.tags ?| ARRAY['tourism', 'camp_site'] AND
  (pitch.tags->'tourism' = 'camp_pitch' OR pitch.tags->'camp_site' IN ('camp_pitch', 'pitch')) AND
  site.id IS NULL
;
```

**Comment by frodrigo** [comment]
which item ?

**Comment by Marc-marc-marc** [comment]
3032 if you want only one.
and/or 4010 for camp_site=canp_pitch/pitch

**Comment by frodrigo** [comment]
new item 1290

**Comment by frodrigo** [comment]
First result.
http://osmose.openstreetmap.fr/fr/errors/?item=1290&useDevItem=all

Bad analyser name.

**Comment by frodrigo** [comment]
Good name, but now duplicate. Wait for full update before cleaning.

@Marc-marc-marc can you check at the results, please?

**Comment by Marc-marc-marc** [comment]
look good/useful.
but I find (currently only) one false-positive http://osmose.openstreetmap.fr/fr/error/0f88b08f-f447-378c-8d96-0415b5350547 https://www.openstreetmap.org/relation/1359262 https://www.openstreetmap.org/way/508488909

**Comment by frodrigo** [comment]
Ok. Just flag multi polygon as false positive.

**Comment by frodrigo** [comment]
@jocelynj item 1290 to enable

**Comment by frodrigo** [comment]
Enabled
