### ISSUE TITLE
parking without amenity=pub

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#532]
Je ne sais si c'est un problème d'analyse ou d'affichage mais j'ai l'erreur "parking sans amenity=pub"

http://osmose.openstreetmap.fr/fr/byuser/trial?username=trial&source=14264

source | niv | item | cl | scl | pos | élmts | sous-titre 
--        | --  | -- | -- | -- | -- | -- | --
14264 | 3 | 9001             combinaisons | 9001001 | 880056674 | -1.67 52.94 | n          1953495535                    (j) | parking sans amenity=pub

N'est-ce pas plutôt incompatibilité parking et amenity=pub ?
En fait non c'est parking=... sans amenity=parking

**Comment by deuzeffe** [comment]
Il me semble que la plupart des signalements en #9xxx proviennent du validateur (berk, le mot !) de JOSM... Et donc, Freed n'y est pour rien :p

**Comment by frodrigo** [comment]
```css
*[parking][amenity!~/^(parking|parking_space|parking_entrance|motorcycle_parking)$/]
```
It comes from this rule. There is a bug in the message

**Comment by frodrigo** [comment]
The issue is no more available on Osmose to analyse.

**Comment by Bibi56** [comment]
désolé je croyais que tu avais fini. J'ai recréé l'erreur pour vérification ;-)

**Comment by Bibi56** [comment]
Il semble que le message d'erreur reste "parking sans amenity=pub".

**Comment by frodrigo** [comment]
Je n'ai encore encore rien fait.

**Comment by frodrigo** [comment]
attribut manquant parking sans amenity=^(parking|parking_space|parking_entrance|motorcycle_parking)$ 

Done.
