### ISSUE TITLE
Typo in attribute camp_type/lamp_type

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#534]
source | niv | item | cl | scl | E | pos | élmts | sous-titre
-- | -- | -- | -- | -- | -- | -- | -- | --
16412 | 1 | 3150             coquille dans l’attribut | 1 | 0 | E | 146.26 -18.35 | n         [6334509211](https://www.openstreetmap.org/node/6334509211)                    (j) | Coquille dans l’attribut
-- | -- | -- | -- | -- | -- | -- | -- | --

La coquille est dans le vérificateur car [camp_type](https://wiki.openstreetmap.org/wiki/Key:camp_type) est une clé qui va mieux avec un camping que lamp_type ;-)

N. B. : là rien hormis le camp_type n'indique qu'il s'agit d'un camping. Mais rien n'indique qu'il s'agit d'une lampe non plus.

**Comment by frodrigo** [comment]
It's not a typo. It's automatic.
