### ISSUE TITLE
Missing tag exception: information without tourism=information 

### ISSUE THREAD

**Issue by lmagreault** [osm-fr/osmose-backend#539]
Error: http://osmose.openstreetmap.fr/en/map/#item=9001&zoom=18&lat=46.585736&lon=5.696757&level=1%2C2%2C3&tags=&fixable=

Message "missing tag information without tourism=information" but board_type=notice is a listed exception in the wiki for information=board and tourism=information.
Wiki : https://wiki.openstreetmap.org/wiki/Key:board_type

**Comment by frodrigo** [comment]
This rule come from JOSM MapCSS validation:
https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss#L95
@Klumbumbus

**Comment by Klumbumbus** [comment]
I see no reason why tourism=information should be omitted for that one case of board_type=notice while it  should be added for all other board_type values.
Besides information=board requires tourism=information independed from if board_type is set or with which value.
Additional the statement in the wiki "Usually not used with tourism=information" is wrong as 90% of board_type=notice objects have tourism=information too (https://taginfo.openstreetmap.org/tags/board_type=notice#combinations). So the wiki should be corrected.
