### ISSUE TITLE
Broken highway continuity

### ISSUE THREAD

**Issue by Debeet** [osm-fr/osmose-backend#54]
Broken highway continuity should probably ignore ways that connect with `highway=proposed` and `highway=construction`. There are too many false alarms like [these](http://osmose.openstreetmap.fr/en/error/2685958952).

**Comment by frodrigo** [comment]
Can you provide me an other error case ? Since you click on false positive, the link is now invalid.

**Comment by frodrigo** [comment]
http://www.openstreetmap.org/way/138214801
