### ISSUE TITLE
Adjustment for query "Highway intersecting highway without junction"

### ISSUE THREAD

**Issue by sun-geo** [osm-fr/osmose-backend#544]
Please don't warn if a 1-dimentional way (line) highway=* [1] is crossing a 2-dimential area highway=services [2] without a connection node.

I think this is OK, it there is no shared node (connection node) where the outer of the 2D-area is crossing the 1D-(highway)-line.

Example error case:
https://osmose.openstreetmap.fr/de/error/28554182274

Osmone map area of example case:
https://osmose.openstreetmap.fr/de/map/#item=1070&zoom=18&lat=50.298683&lon=8.236597&level=2&tags=&fixable=
https://www.openstreetmap.org/?mlat=50.2985931&mlon=8.2365040#map=18/50.29859/8.23650

So could you please adjust the query and remove the check for 2D highway=services, or even return the logic and start warning if these 1D and 2D objects are connected?

Example-objects:
[1] https://www.openstreetmap.org/way/175404104 (highway=service) 1D
[2] https://www.openstreetmap.org/way/442030860 (highway=services) 2D

**Comment by frodrigo** [comment]
Yes `highway=services` should be ignored.

But I think it's not the general case, eg. linear and polygonal highway=pedestrian.

**Comment by sun-geo** [comment]
Thanks for checking my message.
Yes please ignore `highway=services` for this QA request.

Right, linear and polygonal highway=pedestrian are another interesting case.
So far I know there is still no routing engines available which provides usable results when routing is necessary via area objects. (Or do you know one of such a service?) Because of that, i sometimes add some additional linear highway=pedestrian ways (to support the linear routing engines) over the (inner city square) area of a highway=pedestrian area...

I even thought about if it could be an option to modify these areas 
from `highway=pedestrian`
to `area:highway=pedestrian`

**Comment by frodrigo** [comment]
Done.
