### ISSUE TITLE
railway=construction construction=rail is perfectly fine

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#548]
`railway=construction without construction:railway` complaint is forgetting that `construction=*` tagging is also perfectly fine.

http://osmose.openstreetmap.fr/en/error/28870553085
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.082888&lon=19.892635&item=xxxx&level=1%2C2%2C3&tags=&fixable=

key 	value
source	8420
item	9015
class	9015027
subclass	160705788
elems	way24820897
lat lon	50.0830334 19.8912305
title	
en	{0.key}={0.value} without {0.value}:railway
subtitle	
en	railway=construction without construction:railway
timestamp	2019-07-04 04:09:02

**Comment by matkoniecz** [comment]
And the same with "railway=disused without disused:railway"

http://osmose.openstreetmap.fr/en/error/28870561300
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.081215&lon=19.891793&item=xxxx&level=1%2C2%2C3&tags=&fixable=

key 	value
source	8420
item	9015
class	9015027
subclass	160705788
elems	way233646659
lat lon	50.0810282 19.8910380
title	
en	{0.key}={0.value} without {0.value}:railway
subtitle	
en	railway=disused without disused:railway
timestamp	2019-07-04 04:09:02

**Comment by frodrigo** [comment]
This rules are from MapCSS validator : https://www.openrailwaymap.org/validator/openrailwaymap.validator.mapcss

Please report issue here : https://github.com/OpenRailwayMap/OpenRailwayMap/issues

**Comment by matkoniecz** [comment]
I reported this issues upstream.

**Comment by frodrigo** [comment]
https://github.com/OpenRailwayMap/OpenRailwayMap/issues/659

**Comment by frodrigo** [comment]
If required, we can black list the rules on Osmose side.
