### ISSUE TITLE
"Probably only for bottles, not any type of glass" check and especially autofix is unwanted in Poland

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#549]
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.080537&lon=19.895119&item=xxxx&level=1%2C2%2C3&tags=&fixable=
http://osmose.openstreetmap.fr/en/error/28870534351

Autofix wants to change correct `recycling:glass=yes` to an incorrect and very unusual in Poland `recycling:glass_bottles = yes`

In Poland recycling for bulk collection of glass are typical and ones collecting only bottles are unusual (at least I have never seen one).

See https://duckduckgo.com/?q=szk%C5%82o+kontener+recykling&t=canonical&iax=images&ia=images for typical containers in Poland

related to #362

**Comment by frodrigo** [comment]
This is an error, This check should not run on Poland. It was made for France, where you can only put bottle and assimilated, but no bulk, glasses, cristal...

**Comment by matkoniecz** [comment]
bulb, crystal and similar special are also banned in Poland, but you may but crushed glass, jars etc

**Comment by frodrigo** [comment]
@vinber

**Comment by frodrigo** [comment]
From wiki jars are included in glass_bottles. For crushed glass I think it depends on the origin of the glass.

**Comment by matkoniecz** [comment]
I checked now situation more thoroughly and discovered, to my surprise, that this validator warning is mostly right in Poland.

It turns out that you are supposed to put there only some types of glass - one used to make bottles and jors. Glassware, pyrex, window glass, glass used to make lighting bulbs, glass from grave candles and more all are not supposed to go into glass container.
 
Fundamental problem here is that organizations responsible for recycling mislabel bins - do not label something "glass" if just one type of glass is supposed to go there!
 
See for example
https://www.facebook.com/mpokrakow/photos/a.226855814675361/349419322419009/?type=3&theater
https://ekosystem.wroc.pl/segregacja-odpadow/gdzie-wrzucic/?odpad=szk%C5%82o
