### ISSUE TITLE
Consider adding club=* as a main tag for class 21101

### ISSUE THREAD

**Issue by hgcvm** [osm-fr/osmose-backend#550]
As stated in the wiki: https://wiki.openstreetmap.org/wiki/Key:club 

> club=* can stand on its own just like shop=*/office=*/craft=*.

In 21101, we check if there is a name, and if so, there should also be present a "main tag". 

My own amateur research showed me that in the file "osmose-backend/plugins/TagFix_MultipleTag.py", line 52, the "main tags" are summed up.

Could we add club to that list?

**Comment by frodrigo** [comment]
Even if the tag is not really used. It is an approved tags.

**Comment by frodrigo** [comment]
Done.
