### ISSUE TITLE
support alternative street names for addr:street

### ISSUE THREAD

**Issue by Luzandro** [osm-fr/osmose-backend#551]
When searching for streets matching addr:street you should take alternative names into account like name:left, name:right or alt_name (official_name seems to be already supported)

http://osmose.openstreetmap.fr/de/map/#item=2060&zoom=17&lat=48.029222&lon=16.409872&level=2&tags=&fixable=

https://www.openstreetmap.org/way/86826851#map=18/48.02961/16.40940

**Comment by frodrigo** [comment]
Only name is used for now.

name:left and name:right should be added.

About alt_name and official_name, I'm not sure. At first look, it's look like an issue for me.

**Comment by Luzandro** [comment]
Why is this an issue? Someone has explicitly set that this street is alternatively or officially known under this name. 
I thought that official_name is supported, because in case of the neighboring lake the official address is actually given as "Dürrsee-O" whereas the street is named "Dürrsee Ost". It doesn't raise an issue because the addresses in OSM are set as "Dürrsee Ost" while "Dürrsee-O" is only set as official_name so that tools like Nominatim can easier find it.
https://www.openstreetmap.org/way/29284163
Which brings me to the point that tools like Nominatim or OSMI already support it and don't see it as an issue
https://www.openstreetmap.org/way/41013719
https://tools.geofabrik.de/osmi/?view=addresses&lon=16.40847&lat=48.03069&zoom=18

**Comment by frodrigo** [comment]
To ease the use of the data I think the same name should be used.
Tools like Nominatim are specialized on addresses data and should gather as many data as possible. But I still think it's an issue in the data.

**Comment by frodrigo** [comment]
name:left and name:right Done

**Comment by Luzandro** [comment]
So this alt_name raises an issue, but if you added name:right it would "fix" the issue?
https://www.openstreetmap.org/way/41013719#map=18/48.03138/16.40933
Sorry could not resists, I don't think that people will actually do that, as most won't even be aware of it, but I still think official_name / alt_name should be added as well.

**Comment by frodrigo** [comment]
Reopen if required.
