### ISSUE TITLE
parking=yes/no doesn't need an amenity=parking

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#552]
parking=yes is often used (>3000) to describe that a poi (hotel, restaurant, camp_site, camp_pitch) has its own parking.
and parking=no is used to describe that a poi does not have its own parking.
I think that osmose should not consider as an anomaly the fact of having an amenity/shop/tourism/office=* with parking=yes/no.
on the other hand amenity=parking parking=yes/no is indeed an error and must continue to be reported (455 cases currently)

**Comment by frodrigo** [comment]
Do to have link or item class number?

Le dim. 7 juil. 2019 à 01:04, Marc-marc-marc <notifications@github.com> a
écrit :

**Comment by Marc-marc-marc** [comment]
item | 9001
class | 9001001
subclass | 1572004164

**Comment by frodrigo** [comment]
This check come from JOSM validator 
https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss?rev=13452#L102

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
I don't really like this misuse of parking=yes/no on other objects than amenity=parking as it changes the definition of the parking key. parking=yes/no is not even described in the wiki (except on https://wiki.openstreetmap.org/wiki/Tag:tourism=camp_pitch which might be replaced by camp_pitch:parking https://wiki.openstreetmap.org/wiki/Proposed_features/Key:camp_pitch).

Looking at the objects with this overpass turbo wizard query: `(type:way or type:node) and parking=yes and amenity!=parking global` (That already filtered out the wrong amenity=parking parking=yes/no objects) I still see lots of wrong parking=yes objects e.g. on highway=* or parking=yes as only tag or with area=yes or surface=* only.

**Comment by frodrigo** [comment]
Reopen if required.
