### ISSUE TITLE
amenity=stables + leisure=horse_riding

### ISSUE THREAD

**Issue by Luzandro** [osm-fr/osmose-backend#553]
I've found several cases where this combination raises "Conflict between tags: amenity, leisure", but the wiki actually suggests this

> Tags to use in combination
> leisure=horse_riding
> sport=equestrian

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dstables

**Comment by frodrigo** [comment]
Please suggest more if you have.

**Comment by frodrigo** [comment]
Done.
