### ISSUE TITLE
oneway=yes on airport taxiway

### ISSUE THREAD

**Issue by GiancarloParalovo** [osm-fr/osmose-backend#554]
When I use the tag oneway=yes on a taxiway, osmose report this kind of error :+1:  http://osmose.openstreetmap.fr/en/map/#item=9001&zoom=17&lat=45.193972&lon=7.645234&level=1%2C2%2C3&tags=&fixable= . A taxiway, as a runway is normally bidirectional but some time can be designed for one way only. In this case the airtraffic on taxiway M must go in one direction only. 
Seems that tag "oneway" need to be associate to an highway,aerialway,or railway only.
In other ailfield as Rome Fco with similar taxiways there is the same kind of problem.. 
Thanks for help!

**Comment by frodrigo** [comment]
This rule come from JOSM validator https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss#L214

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
I'll fix it in the next days in JOSM.

**Comment by Klumbumbus** [comment]
Fixed in JOSM with https://josm.openstreetmap.de/changeset/15254

**Comment by frodrigo** [comment]
reopen after auto close by github.

**Comment by frodrigo** [comment]
Done.
