### ISSUE TITLE
500 internal server error on an Osmose error

### ISSUE THREAD

**Issue by Phyks** [osm-fr/osmose-backend#557]
Hi,

Yesterday, I noticed an error which was accessible through

https://osmose.openstreetmap.fr/fr/map/#zoom=17&lat=48.81602&lon=2.319778&item=xxxx&level=1&tags=&fixable=

I sent the link to someone else, but it seems there is an issue at the moment and the link which was working yesterday now returns a 500 internal server error.

Best,

**Comment by frodrigo** [comment]
We have memory issues with the server. But enable to fix it, yet.

**Comment by Phyks** [comment]
Oh, ok, so this is rather a sysadmin issue. Feel free to close this one then, if this is not related to the Osmose codebase specifically :)
