### ISSUE TITLE
Broken highway continuity, part 2

### ISSUE THREAD

**Issue by Debeet** [osm-fr/osmose-backend#56]
Thank you for fixing #54. There's another issue with this detection that I cannot fathom.

Error: http://osmose.openstreetmap.fr/en/error/2787511794
Location: http://www.openstreetmap.org/#map=18/54.21516/21.73803
The way in fault: http://www.openstreetmap.org/way/174463054

What is wrong here? Connection is fine, can't see a problem. Can you fix it so there are no more false-positives like these?

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/map/#zoom=16&lat=53.73523&lon=20.50065&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFT&item=1120&level=1%2C2%2C3&tags=&fixable=
Same problem here

**Comment by jocelynj** [comment]
It seems that one of the way is missing from the .pbf file used by the analysers. I will regenerate this pbf.

**Comment by Debeet** [comment]
Is it possible that after regenerating this pbf file this issue might return at some point in the future?

**Comment by frodrigo** [comment]
No. But please no mark issues as false posititve, need for easy check.

**Comment by Debeet** [comment]
I don't mark these as false positive if I'm not sure it's an error. It must've been someone else.
