### ISSUE TITLE
Propose a quick fix when no addr:street found is due to case

### ISSUE THREAD

**Issue by Phyks** [osm-fr/osmose-backend#561]
Hi,

I've just came across a bunch of errors such as https://osmose.openstreetmap.fr/fr/error/29385417707 with an `addr:street` not matching a nearby street name.

This is because the `addr:street` value is "rue sommeiller" while the street name is "Rue Sommeiller".

What about adding a quick check for case and offer a one-click fix if a match is found?

Thanks!
Best,

**Comment by frodrigo** [comment]
It's too complicated to do. I don't think it's worth it.
