### ISSUE TITLE
Name present but missing main tag (has seamark:* tags)

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#562]
It seems that this should not be an error? It has seamark:* tags which look reasonable.

[i=2110][c=21101][s=1][l=2] (n1611276366) Name present but missing main tag

https://www.openstreetmap.org/node/1611276366#map=13/45.4944/-76.0334

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#zoom=15&lat=45.50007&lon=-76.04958&item=xxxx&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
`seamark:type` will do the job.

**Comment by frodrigo** [comment]
Done.
