### ISSUE TITLE
Improve wording for "Bad topology way level 2"

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#563]
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.296067&lon=-75.925621
https://wiki.openstreetmap.org/wiki/Osmose/issues#1090

The wiki is clear enough what the problem is (however it is not clear how to fix the issue), but the one-line that pops up on osmose UI could be made much more clear to describe the actual problem more like "sudden highway type change type 2"

(this is a general problem where some messages are very clear, while others are much less clear)

![Screenshot_20190717_081612](https://user-images.githubusercontent.com/26171839/61374762-31ae8a00-a86b-11e9-956e-d6bef1ef1bb6.png)

**Comment by frodrigo** [comment]
Done. Update in progress.
