### ISSUE TITLE
Add support for Canadian postal codes

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#565]
Canadian postal codes are in the format A1A 1A1, where A is a letter and 1 is a digit, with a space separating the third and fourth characters. That is: regex ^[A-Z][0-9][A-Z] [0-9][A-Z][0-9]$

https://en.wikipedia.org/wiki/Postal_codes_in_Canada

In OSM, if building an postal code area(boundary), then only the first 3 characters are normally listed.
For addresses all 6 characters should be listed, however if for some reason the full postal code is not fully known, then some people only list the first 3 characters.  However, these kinds of postal codes are not complete and should still flag an error.

The Canadian postal code database is not open data.  However, postal codes are added into OSM based on publicly available information, not using the official postal code database.

**Comment by frodrigo** [comment]
Postal code are check using this list: https://en.wikipedia.org/wiki/List_of_postal_codes

According to you it's not well set on Wikipedia. Please can you fix it?

**Comment by matthewdarwin** [comment]
The wiki is correct, so then OSMOSE should work.. so close this issue.

**Comment by frodrigo** [comment]
But for area it should be ANA in the first column and ANA NAN  in the second, doesn't ?

**Comment by matthewdarwin** [comment]
That's OSM (and some general) convention, not official government practice.  So I'm not sure wiki should be updated.   If second column is blank, then first column applies?

**Comment by frodrigo** [comment]
No there are independent.

First column area is for `postal_code`.

Second, street, is for `addr:postcode`.

(Note I created the two columns myself on Wikipedia)

**Comment by matthewdarwin** [comment]
Ok, I updated wikipedia accordingly.

**Comment by frodrigo** [comment]
Ok. I will be updated on next Osmose cache update. The cache is of 60 days.
