### ISSUE TITLE
False positive: path way endind on river way slipway node gererates 1250 issue

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/osmose-backend#566]
A highway=path ending on a highway=river with their common node tagged leisure=slipway
generates a 1250 item (class 2)
http://osm.org/node/2400660071
http://osmose.openstreetmap.fr/fr/map/#item=1250&zoom=18&lat=3.576621&lon=-53.208526&level=3&tags=&fixable=

**Comment by frodrigo** [comment]
The fix does not solve the issue.

**Comment by frodrigo** [comment]
Done.
