### ISSUE TITLE
Dockerfile python image no longer builds

### ISSUE THREAD

**Issue by devturner** [osm-fr/osmose-backend#567]
Building from the docker directory no longer works as the java-jre cannot be downloaded. 

old, non-working:
> FROM python:3.5

can be made to work (for now) with
> FROM python:3.5-stretch

**Comment by frodrigo** [comment]
I will prefer to update to new Debian. Can you make the upgrade ?

**Comment by frodrigo** [comment]
cc @matthewdarwin maybe your backend issue is linked to this issue (cc @jocelynj )

**Comment by jocelynj** [comment]
On Debian buster, you should be able to use openjdk-11-jre-headless

**Comment by frodrigo** [comment]
I try to make the update.
But the build of the pbf parser does not found boost.

**Comment by jocelynj** [comment]
I think it is because Debian compile boost only for some versions of python:
https://packages.debian.org/buster/amd64/libboost-python1.67-dev/filelist
2.7 and 3.7 on latest stable.

**Comment by frodrigo** [comment]
You are right, switch to py3.7.
Nevertheless the make file does not found it in /usr/lib/x86_64-linux-gnu/libboost_python37.so.1.67.0
