### ISSUE TITLE
Osmose suggests misspelled "sport=billards" (item 8170, class 86)

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#568]
Hi,

When spotted a missing billiard room, Osmose suggests to create an object with "sport=billards" tag. 

However, the correct spelling seems to be "sport=billiards", as in bill-i-ards. See https://wiki.openstreetmap.org/wiki/Tag:sport%3Dbilliards#Spelling_Errors .

Example : https://osmose.openstreetmap.fr/fr/error/29570094842

Marker :

key | value
-- | --
source | 5833
item | 8170
class | 86
subclass | 1994850253
elems |  
lat lon | 45.5841200 5.2756900
title | Pitch not integrated Salle de billard 
subtitle | Salle de billard, Salle de Billard, None
timestamp | 2019-07-16 20:00:02

Fixes :

key | value
-- | --
diff_index | 0
elem_data_type | N
elem_id | 0
tags_create | 
source | Le ministère de la ville, de la jeunesse et des sports - 01/2018 |  
sport | billards |  
tags_modify |  
tags_delete |  

Please, let osmose suggest the correct sport=* tag.

**Comment by frodrigo** [comment]
Done on next update.
