### ISSUE TITLE
not-connected highway/cycleway (1210)

### ISSUE THREAD

**Issue by AdVerburg** [osm-fr/osmose-backend#570]
A highway=* ending on a route=ferry with their common node tagged amenity=ferry_terminal
generates a 1210 item (class 1).
http://osmose.openstreetmap.fr/en/map/#username=AdVerburg&zoom=8&lat=52.108&lon=4.773&item=1210&level=1%2C2%2C3&tags=&fixable=

1210 Also comes when the end node of a way has tourism=viewpoint (https://osmose.openstreetmap.fr/en/error/29709494330) or tagged with noexit=yes (http://osmose.openstreetmap.fr/en/error/29697292962)

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#username=AdVerburg&zoom=16&lat=51.90004&lon=5.60469&item=1210&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
Done.
