### ISSUE TITLE
Maxspeed 100 for hgv

### ISSUE THREAD

**Issue by Michael21011** [osm-fr/osmose-backend#572]
Hi all, 
Could a few new tags be taken into account for speed control checking.
Following tags are ignored:
maxspeed:hgv=100

Details http://osmose.openstreetmap.fr/ru/error/29869642183

item | 8300
class | 14

Mapillary link http://www.mapillary.com/map/im/sTxBPLbbI8VN4ledxUXb4w

All tags for this highway on the map
![image](https://user-images.githubusercontent.com/9266780/61789661-ed4c5c80-ae1d-11e9-8d3a-ba965e0dc85a.png)

Update: previous link already removed, this is new one for the same issue
http://osmose.openstreetmap.fr/en/error/30138918133
https://www.mapillary.com/map/im/SjpqfKvUmlFVUr61f8KjRg

**Comment by Luzandro** [comment]
I'm not sure if this is related, as the link doesn't work anymore and the item is different (9001), but this here raises a missing tag issue, because there is a traffic_sing=maxspeed without a simple unconditional maxspeed, but there is actually a maxspeed:hgv:conditional given:
```
traffic_sign = maxspeed 
maxspeed:hgv:conditional = 80 @ (weight>7.5 AND 22:00-05:00) 
```
http://osmose.openstreetmap.fr/de/map/#item=9001&zoom=17&lat=48.522872&lon=16.626015&level=3&tags=&fixable=

https://wiki.openstreetmap.org/wiki/Conditional_restrictions

**Comment by Michael21011** [comment]
> 
> 
> I'm not sure if this is related, as the link doesn't work anymore 

This is another example of the same issue
http://osmose.openstreetmap.fr/en/error/30138918133
Mappialry phot https://www.mapillary.com/map/im/SjpqfKvUmlFVUr61f8KjRg
![image](https://user-images.githubusercontent.com/9266780/62052755-d1cac280-b21e-11e9-9f4a-4d389ad73ca0.png)

**Comment by frodrigo** [comment]
The mapping is here: https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json

Somme tags are missing. It is wilful to save some query and CPU power.
We can add more if you think there are not too uncommon.

**Comment by Michael21011** [comment]
hi @frodrigo 
Thank you for the link.
Does a possibility exist to select tags with mask like this?


> {
        "highway": null,
        "maxspeed:*": "100{speed_limit_unit}"
      },

if not then could be added
> {
        "highway": null,
        "maxspeed:hgv": "100{speed_limit_unit}"
      },

I see 1745 [usages ](https://taginfo.openstreetmap.org/tags/maxspeed:hgv=100)of such combination

**Comment by frodrigo** [comment]
> I'm not sure if this is related, as the link doesn't work anymore and the item is different (9001), but this here raises a missing tag issue, because there is a traffic_sing=maxspeed without a simple unconditional maxspeed, but there is actually a maxspeed:hgv:conditional given:
> 
> ```
> traffic_sign = maxspeed 
> maxspeed:hgv:conditional = 80 @ (weight>7.5 AND 22:00-05:00) 
> ```
> 
> http://osmose.openstreetmap.fr/de/map/#item=9001&zoom=17&lat=48.522872&lon=16.626015&level=3&tags=&fixable=
> 
> https://wiki.openstreetmap.org/wiki/Conditional_restrictions

This part is from JOSM validator

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
>This part is from JOSM validator

fixed in https://josm.openstreetmap.de/changeset/17218/josm
