### ISSUE TITLE
Typo in tag for static_caravans

### ISSUE THREAD

**Issue by danfos** [osm-fr/osmose-backend#574]
I see that Osmose is reporting a Typo in tag for static_caravan**s** with the suggestion to change it to static_caravan (without an 's')

For an example see http://osmose.openstreetmap.fr/en/map/#item=3150&zoom=16&lat=51.90498&lon=4.17745&level=1&tags=&fixable=

The [camp site page](https://wiki.openstreetmap.org/wiki/Talk:Tag:tourism%3Dcamp_site) indicates static_caravan**s**  just like tents, caravans and cabins. Tag info is shows both values are used but for static_caravan [almost all have the value "plot"](https://taginfo.openstreetmap.org/keys/static_caravan#values), not sure what this means but no good reason to report "Typo in tag" I think.

What is strange is that I do not see a "Typo in tag" problem reported for the [Idéal Camping](https://www.openstreetmap.org/way/91760458) while that has also "static_caravans=yes"

**Comment by frodrigo** [comment]
cc @Marc-marc-marc

**Comment by Marc-marc-marc** [comment]
static_caravan=plot : all from the same user in Holland, without being in a tourism=camp_site nor in a tourism=caravan_site : so no idea of the meaning. perhaps this means that this cadastral parcel is occupied by a static caravan. I asked the contributor the question.
66 of 67 static_caravans are combined with a tourism=*, the last on with a wrong leisure=camp_site.
all other types of tourism=* parcels  (like tents cabins caravans) are words in the plural, so it seems better to not report the plural as an error. this is a point that could be discussed in the current proposal to fine-tune the parcels tags

**Comment by frodrigo** [comment]
TODO
- [ ] white list static_caravans and static_caravan

**Comment by frodrigo** [comment]
Done. Data update on going.
