### ISSUE TITLE
Add Stop sign to list of mapillary street objects

### ISSUE THREAD

**Issue by zzptichka** [osm-fr/osmose-backend#576]
`regulatory--stop-*` ids in mapillary.
Very distinguishable sign, very few false positives. 605 752 nodes tagged with `highway=stop` worldwide. 
Good candidate to add. I would give it "Normal" severity.

**Comment by frodrigo** [comment]
It was not included by choice.
Since there are too many, they overflow the other more interesting objects.
Lot of uninteresting or low priority issues have the effect to discourage fixing or integrating the features.

**Comment by zzptichka** [comment]
Maybe in general you are right. In my city of 1M+ population almost all stop and yield signs are mapped, so I would welcome that.

**Comment by frodrigo** [comment]
We can enable it by Osmose area.
Witch one match your place : http://osmose.openstreetmap.fr/fr/control/update_summary

**Comment by matthewdarwin** [comment]
me and @zzptichka are in canada_ontario_eastern_ontario

**Comment by frodrigo** [comment]
We do not have an area code for eastern_ontario, ony canada_ontario.

There is code for Ontario region? Or do you want the full Ontario (CA-ON)?

https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L821-L828

**Comment by matthewdarwin** [comment]
Full Ontario is fine.  Also canada_quebec (CA-QC).   Ottawa is on the border between Ontario and Quebec and maps we work on cross the boundaries (eg https://maps.bikeottawa.ca/)

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=8300&country=canada_*&class=52

Done.

**Comment by zzptichka** [comment]
Thanks for adding it. Any idea why in Ottawa Ontario[ I can't see any](http://osmose.openstreetmap.fr/en/map/#zoom=12&lat=45.35&lon=-75.7116&item=8300&level=1%2C2%2C3&tags=&fixable=&class=52) (while across the river in Quebec) there are some? Is it because of 100m conflation distance?
Plenty of fresh imagery around here.

**Comment by frodrigo** [comment]
Yes, the conflation distance disable some detection. But the location provided by Mapillary is not good precision.
As speed at a stop is know to be low, maybe the precision is better. We can try with 100m if you want?

**Comment by zzptichka** [comment]
It's 100m right now. Perhaps 50m is worth a try?

**Comment by frodrigo** [comment]
You are right. It's already at 100m, the smallest value configured.
Do you notice too false positives with the 100m config? If not, we can try with 50m.

**Comment by zzptichka** [comment]
OK, let me try to find some undetected ones to understand why it's happening.

**Comment by frodrigo** [comment]
By false positive, I mean stop detected at more than 100m of the actual location.

**Comment by zzptichka** [comment]
My problem is that Osmose doesn't detect any missing stop signs in my area.
For example [this intersection](https://www.openstreetmap.org/#map=17/45.14679/-75.96758), no stop sign mapped.
[Mapillary properly detects Stop sign](https://www.mapillary.com/app/?focus=photo&pKey=vMKK_z3Sc_FASzu9Zuf8gx&lat=45.146659394540194&lng=-75.96897705922156&z=17&signs=true) precisely where it should be.
[Osmose doesn't detect ](http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=45.146993&lon=-75.967702&item=8300&level=1%2C2%2C3&tags=&fixable=&class=52)issue 8300 class 52 here.

**Comment by frodrigo** [comment]
There is also other criteria, like the confidence of the detection, and data range of the photo. There is also a cache for reading from Mapillary of 60 days.

But it's strange that only Central Ontario get results
http://osmose.openstreetmap.fr/fr/errors/?item=8300&country=canada_*&class=52

**Comment by frodrigo** [comment]
All detection from Mapillary are boken: http://osmose.openstreetmap.fr/fr/errors/graph.png?country=canada_ontario_*&item=8300&level=1%2C2%2C3

**Comment by frodrigo** [comment]
I think it's linked to the cache.

@matthewdarwin or @jocelynj . Please, can you clear the Osmose cache on the server ? `/data/work/osmose/cache`

**Comment by matthewdarwin** [comment]
I deleted the cache directory.

**Comment by matthewdarwin** [comment]
Deleting the cache didn't seem to improve anything. I also rebooted the server yesterday to see if that helps.  Nothing  @jocelynj  Canada is not working http://osmose.openstreetmap.fr/en/control/update_matrix

**Comment by frodrigo** [comment]
We force a manual update. We are waiting feedback from @jocelynj.
http://osmose.openstreetmap.fr/en/control/update_matrix?remote=07e9

**Comment by frodrigo** [comment]
Canada is now updated. But the stop detection still does not work.

**Comment by frodrigo** [comment]
I look like a global issue
![image](https://user-images.githubusercontent.com/1785486/64375753-dad15f80-d026-11e9-8214-dc7b492b6a5a.png)

**Comment by frodrigo** [comment]
The gap is linked to the dedup process I am working on.

**Comment by frodrigo** [comment]
Local run `--country=canada_ontario_northeastern_ontario --analyse=merge_traffic_signs` raise missing stops. But not on the server.

**Comment by frodrigo** [comment]
On the server the analyser found no data for all traffic signs: ***Empty bbox, abort***.
http://buildbot2.osmose.openstreetmap.fr/#/builders/15/builds/65/steps/1/logs/stdio
```
2019-09-05 06:18:12   run osmosis all analyser SubAnalyser_Merge_Traffic_Signs_52
2019-09-05 06:18:12   Analyser_Merge.py:867 sql
2019-09-05 06:18:12   Analyser_Merge.py:622 sql
2019-09-05 06:18:12   Convert data to tags
2019-09-05 06:18:12   Analyser_Merge.py:662 sql
2019-09-05 06:18:12   Analyser_Merge.py:663 sql
2019-09-05 06:18:13   Analyser_Merge.py:716 sql
2019-09-05 06:18:13   Analyser_Merge.py:721 sql
2019-09-05 06:18:13   Empty bbox, abort
```

**Comment by frodrigo** [comment]
The next run after @matthewdarwin clear the cache does not refill the cache.

@jocelynj can you check about the cache status on the server, please?

**Comment by matthewdarwin** [comment]
Seems it is working now?  I got these issues in my feed today:

[OSE] [i=8300][c=52][s=1333683827][l=3] () highway=stop Traffic signs for stop observed around but not associated tags: Observed on 2019-07-03
[OSE] [i=8300][c=52][s=1697599796][l=3] () highway=stop Traffic signs for stop observed around but not associated tags: Observed between 2017-04-27 and 2017-09-06
[OSE] [i=8300][c=52][s=338089174][l=3] () highway=stop Traffic signs for stop observed around but not associated tags: Observed on 2019-06-28
[OSE] [i=8300][c=52][s=752506412][l=3] () highway=stop Traffic signs for stop observed around but not associated tags: Observed on 2019-07-03
[OSE] [i=8300][c=52][s=839076742][l=3] () highway=stop Traffic signs for stop observed around but not associated tags: Observed on 2017-09-04

**Comment by frodrigo** [comment]
Yes. It is ok.
Thank all.

**Comment by BalooUriza** [comment]
Would it be possible to get this added to usa_oklahoma or usa_*?

**Comment by frodrigo** [comment]
@BalooUriza should be added here https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json#L1002
I let you make a PR.
