### ISSUE TITLE
"Name present but missing main tag" for guidepost = overhead

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#577]
I'm not sure if there is anything missing from this?  I find a bunch of these kinds of errors locally

http://osmose.openstreetmap.fr/en/error/30192826133
http://osmose.openstreetmap.fr/en/error/30192826222

source | 414832
item | 2110
class | 21101
subclass | 1

**Comment by frodrigo** [comment]
https://wiki.openstreetmap.org/wiki/Key%3Aguidepost

The tag guidepost=* is mostly used in addition to information=guidepost to depict what kind of guidepost it is.

I think there is nothing to fix in Osmose.

**Comment by matthewdarwin** [comment]
ok!

**Comment by matthewdarwin** [comment]
https://www.openstreetmap.org/changeset/72813406

**Comment by matthewdarwin** [comment]
The page https://wiki.openstreetmap.org/wiki/Key:destination says "To indicate the physical location of the signpost itself, use information=guidepost. "   However, this tagging still does not resolve this issue.

http://osmose.openstreetmap.fr/en/map/#zoom=13&lat=45.3458&lon=-75.7952&item=2110

http://osmose.openstreetmap.fr/en/error/31012531292
http://osmose.openstreetmap.fr/en/error/31012530818

**Comment by frodrigo** [comment]
So, `information` should be added as main tag.

**Comment by frodrigo** [comment]
Update in progress. But Canada run are off.

http://osmose.openstreetmap.fr/en/control/update_matrix?remote=07e9
I do not know if it still a problem with the new scheduler.

**Comment by frodrigo** [comment]
Done.
