### ISSUE TITLE
Way with place=island not closed

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#578]
I have a bunch of errors the same:

Way with {0.key}={0.value} not closed.
Way with place=island not closed. 
http://osmose.openstreetmap.fr/en/map/#zoom=13&lat=45.3013&lon=-76.5167

example: http://osmose.openstreetmap.fr/en/error/30221474492

item | 9003
class | 9003010
subclass | 167228643

It is not clear to me what needs to be done to fix these islands.

**Comment by frodrigo** [comment]
It is from JOSM validator.

https://josm.openstreetmap.de/browser/josm/trunk/data/validator/geometry.mapcss#L320

According to the check, the way should be a closed way.

@Klumbumbus

**Comment by Klumbumbus** [comment]
https://www.openstreetmap.org/way/325539325 doesn't produce a warning in JOSM (after reverting it to place=island too) as the way is closed. It seems osmose doesn't correctly interpret the :closed pseudoclass?
