### ISSUE TITLE
Consider adding attraction=* as a main tag for class 21101

### ISSUE THREAD

**Issue by hgcvm** [osm-fr/osmose-backend#579]
This is similar to my request in https://github.com/osm-fr/osmose-backend/issues/550

The tag attraction=*  (https://wiki.openstreetmap.org/wiki/Key:attraction) can be used for example to tag an attraction within an amusement park, for example attraction=roller_coaster. These can have names.

The wiki is not totally clear if the attraction=* tag can exist on itself. But I presume it can, as the wiki doesn't tell differently.

Would "attraction" be something that could be added to "osmose-backend/plugins/TagFix_MultipleTag.py", line 52?

**Comment by frodrigo** [comment]
Done. Update in progress.
