### ISSUE TITLE
For error "Initial stuck to the name" it should tell you the name

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#580]
For "Name with uppercase" you get the name,  But for "Initial stuck to the name", you don't.  This message could be improved by giving you the name.

A few examples:

[i=5010][c=803][s=0][l=1] (n3243533450) Name with uppercase: LASIK MD
[i=5010][c=803][s=0][l=1] (n3358563838) Name with uppercase: OPTODENT Centre
[i=5010][c=803][s=0][l=1] (n2434574988) Name with uppercase: W.E. TRAVEL
[i=5010][c=803][s=0][l=1] (n2242277176) Name with uppercase: BOBITES Best Organic Bites
[i=5010][c=902][s=0][l=3] (w681174672) Initial stuck to the name
[i=5010][c=902][s=0][l=3] (w477490707) Initial stuck to the name
[i=5010][c=902][s=0][l=3] (n6202432693) Initial stuck to the name

**Comment by frodrigo** [comment]
Done. Data update on going.
