### ISSUE TITLE
Don't sugest to replace lock_ref with loc_ref on a lock

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#581]
Similar to https://github.com/osm-fr/osmose-backend/issues/349, now `loc_ref` is suggested instead of `lock_ref`.  

example: way 42808218

http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.371285&lon=-75.697708&level=1%2C2&tags=&fixable=&item=3xxx

**Comment by frodrigo** [comment]
Done. Data update on going.
