### ISSUE TITLE
Add more description to class 30923 "Missing international prefix"

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#583]
Would it be possible to reference the word "phone" somewhere in the description of 30923?  For 30925 it says "Unallowed char in phone number: Not allowed char "xxxx" in phone number", which is great.  But for 30923 it doesn't reference the word phone anywhere, just says "Missing international prefix".

I'm not sure if the "phone" refers to the actual tag (vs "fax", "contact:phone", etc) or is just a term hard-coded in the message.

I am reviewing errors from the RSS feed so a bit more hints about what the error refers to in the title is helpful.

[i=3092][c=30923][s=1654375820][l=3] (w470442714) Missing international prefix
[i=3092][c=30923][s=1654375820][l=3] (w253267831) Missing international prefix
[i=3092][c=30923][s=1654375820][l=3] (w68609059) Missing international prefix
[i=3092][c=30923][s=1654375820][l=3] (w68609034) Missing international prefix
[i=3092][c=30925][s=1654375820][l=3] (w68661214) Unallowed char in phone number
[i=3092][c=30925][s=1654375820][l=3] (n4496341889) Unallowed char in phone number
[i=3092][c=30925][s=411668680][l=3] (n975439580) Unallowed char in phone number

**Comment by frodrigo** [comment]
Done. Update in progress.
