### ISSUE TITLE
integration opendata hosting campsite does not detect the existing

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#584]
Osmose propose d'ajouter un camping à l'endroit oü celui-ci existe déjà dans osm avec le bon nom et le bon tag principal. exemple :
https://www.openstreetmap.org/way/471793173
name=Camping Le Paradou
tourism=camp_site
source | 79899
item | 8140
class | 11
lat lon | 45.1903590 0.0263903

**Comment by frodrigo** [comment]
http://opendata.osmose.openstreetmap.fr/fr/errors/graph.png?item=8140&class=11

**Comment by frodrigo** [comment]
Use osmose.osm.fr not opendata.osmose.osm.fr
