### ISSUE TITLE
Testing ref:FR:FINESS seems to provide many false positives

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osmose-backend#587]
Hello,
I get the message "Hôpital sans attribut ref:FR:FINESS ou incorrect", while the tag ref:FR:FINESS is present and correct.
exemples : https://www.openstreetmap.org/way/559279569
ou https://www.openstreetmap.org/way/31150223
Thanks.

**Comment by williamdes** [comment]
I agree, many many false positives.
Opened #591 for MHS

**Comment by zorglubu** [comment]
> Did you mark it as false positive? I can see it.

No, I didn't mark anything. Do you want me to mark some of the false positives ?

**Comment by frodrigo** [comment]
No, keep marker as open issue.

OK, It is a purple marker.

http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=48.756954&lon=2.302899&item=7220&level=1%2C2%2C3&tags=&fixable=

It is a know issue. The is two levels of FINESS, one administrative for large entity, one for medical sub part. To be confirmed, but the only the sub parts are in OpenData.

cc @vinber

**Comment by zorglubu** [comment]
Bonjour,
Sauf erreur, le fichier https://static.data.gouv.fr/resources/finess-extraction-du-fichier-des-etablissements/20190906-110342/etalab-cs1100507-stock-20190906-0450.csv me semble fournir les seules structures géographiques (ET) et pas les structures juridiques (EJ). La colonne 2 "Numéro FINESS ET" fournit le bon FINESS.
Je suis à disposition au besoin. Cordialement.

**Comment by frodrigo** [comment]
C'est déjà les structures géographiques et que celles-ci qui sont utilisées.
Il faut essayer d’avoir les structures juridiques en OpenData.
Si pas disponible, on peut désactiver cet item d'osmose pour ne plus avoir les faux-positifs.

**Comment by zorglubu** [comment]
Pourquoi avoir les structures juridiques ? Une société comme Korian qui possède 800 établissements dans une demi douzaine de pays, y-a-t-il un intérêt à s'en occuper ?
Par contre ce qui serait intéressant c'est effectivement de vérifier qu'un FINESS "ET" est bien présent sur OSM.

**Comment by frodrigo** [comment]
C'est déjà ce qui est fait.

**Comment by zorglubu** [comment]
Désolé, je n'ai pas dû comprendre le problème "To be confirmed, but the only the sub parts are in OpenData."
Je connais plutôt bien la gestion des FINESS, mais pas trop Osmose :-)

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_healthcare_FR_finess.py

Ces données sont utilisées : https://www.data.gouv.fr/fr/datasets/finess-extraction-du-fichier-des-etablissements/

Ce sont les structures géographiques. Osmose essaye de les rapprocher d'OSM. Mais comme des contributeurs renseignent parfois les référencer des structures juridiques, et qu'elles ne sont pas dans l'OpenData, Osmose les signale comme invalide.

Soit on a accès aux structures juridiques pour valider les ref. Soit on ne valide pas que les ref existent.

**Comment by zorglubu** [comment]
On aura quelques faux positifs pour des FINESS juridiques, c'est vrai. Mais pourquoi pas, je crois qu'ils ne seront pas nombreux.
Par contre l'exemple donné https://www.openstreetmap.org/way/559279569 correspond au FINESS 920300043 qui est bien un FINESS géographique. Il faudrait identifier pourquoi on a cette erreur osmose. Est-ce un problème de coordonnées ?

**Comment by frodrigo** [comment]
Effectivement 920300043 est bine dans le fichier.

**Comment by deuzeffe** [comment]
@zorglubu puisque tu connais bien la gestion FINESS, quelle est le "bon" code à utiliser ? Le géographique, certes... mais plus précisément ? Moi non plus, je ne comprends pas pourquoi les codes géographiques sont marqués en erreur :/ "Normalement" @vinber avait en projet de remettre tout ça au carré. Si tu veux nous donner un coup de main. Discussion ailleurs, si besoin ^^

**Comment by vinber** [comment]
ok, partant si en plus on a quelqu'un qui connait bien finess :). Discussions ailleurs, tu penses à quoi @deuzeffe

**Comment by zorglubu** [comment]
Si je peux aider, ce sera avec plaisir. Pouvez-vous me mettre quelques liens vers la source utilisée et les bouts de code concernés ?

**Comment by vinber** [comment]
les données FINESS : https://www.data.gouv.fr/fr/datasets/finess-extraction-du-fichier-des-etablissements/

le rapprochement entre les 2 bases : https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.csv

Qui est la traduction de : 
# sur la base de et_categ_niv3 et de la nomenclature catégorie d'établissement FINESS http://finess.sante.gouv.fr/fininter/jsp/nomenclatures.do

Valeur fichier FINESS,item osmose,?,importance ?,Nom descriptif, tag osm, tag osm, ...

1101|1102|1106|,,,,Hôpital,amenity=hospital
2201|2202|2204|2205|2206,,,Établissements de soins autres que les hopitaux,healthcare=yes
3101,,,Laboratoire de Biologie Médicale,healthcare=laboratory,healthcare:speciality=biology
3201,8210|7150,0,3,Pharmacie,amenity=pharmacy,dispensing=yes
4301,,,Établissement et services d'hébergement pour adultes handicapés,amenity=social_facility,social_facility=group_home,social_facility:for=disabled
4302,,,Établissements et services de travail protégé pour adultes handicapés,amenity=social_facility,social_facility=workshop,social_facility:for=disabled
4401,,,Etablissements d'Hébergement pour Personnes Âgées,amenity=social_facility,social_facility=group_home,social_facility:for=senior
4501,,,Etablissements de l'Aide Sociale à l'Enfance,amenity=social_facility,social_facility=group_home,social_facility:for=child
5101,,,Crèches, mutliaccueil enfants de - de 6 ans,amenity=kindergarten


Ce mapping est trés certainement perfectible

**Comment by zorglubu** [comment]
En regardant rapidement je ne détecte aucune entité juridique (EJ) dans ce fichier -> on peut donc à mon avis les ignorer. On doit aussi ignorer la colonne 3 (Numéro FINESS EJ) qui indique à quelle EJ est rattaché l'établissement (ET), c'est sans intérêt pour l'instant.
Concernant les filtres il faudrait certainement ajouter au moins les catégories 1103(CHS), 1104(CLCC), mais c'est un autre sujet ;-)
Sinon, concernant le FINESS 920300043 (way 559279569), peut-on savoir exactement d'où provient cette erreur ? J'ai juste repéré un positionnement géographique approximatif de l'open data (décalage >100m), le reste semble bon ...

**Comment by vinber** [comment]
> Concernant les filtres il faudrait certainement ajouter au moins les catégories 1103(CHS), 1104(CLCC), mais c'est un autre sujet ;-)
alors faisons un autre sujet pour cela  #666

**Comment by vinber** [comment]
Je dirai que l'erreur est un faux positif car :
- la ref finess est bien renseignée
- cette ref renvoie à la page descriptive de cet hopital

donc je dirai faux positif une deuxième (je l'ai écris au dessus !!!)

**Comment by zorglubu** [comment]
J'avais dans l'idée de balayer toutes les amenity:hospital ou clinic pour y ajouter le FINESS s'il n'est pas dans OSM. Que penseriez-vous de dissocier les tests (on aurait sans doute moins de faux positifs) : 
1) détecter les amenity: hospital|clinic qui n'ont pas de ref:FR:FINESS
2) détecter les FINESS open data qu'on ne retrouve pas dans OSM et les localiser avec les coordonnées open data
3) proposer des infos open data pour les amenity: hospital|clinic qui ont un ref:FR:FINESS
4) détecter les géolocalisations qui diffèrent de plus de X km (2 km ?) entre OSM et opendata

**Comment by vinber** [comment]
Ce qui n'est pas évident c'est que :
- https://osm.org/go/0BOZH5~6k--?m= est aussi un hopital avec le même nom Hôpital Privé d'Antony (https://www.openstreetmap.org/way/80875417#map=18/48.75647/2.30534&layers=D)
- FINESS 920300043 https://www.openstreetmap.org/way/559279569

peut-être que ce n'était pas un faux positif :( mais 2 sites hopital, avec le même nom, et donc une alerte au milieu ?

**Comment by deuzeffe** [comment]
@vinber Ma première idée était de démêler les erreur osmose (ET, EJ, par ex.)
L'approche de @zorglubu semble intéressante (s'il veut bien la coder :p) : le point 1 me semble indispensable en premier lieu.

**Comment by zorglubu** [comment]
Je crois avoir détecté un truc. La totalité ou presque des erreurs osmose "Hôpital sans attribut ref:FR:FINESS ou incorrect" concerne soit des ET sans FINESS (erreur normale), soit des ET dont la catégorie "agrégée" est 1103 ,04, 06, 07, 09, 10, 11
Je propose donc de commencer par traiter le ticket https://github.com/osm-fr/osmose-backend/issues/666

**Comment by zorglubu** [comment]
Pour info, j'ai remplacé l'Hôpital Privé d'Antony par un multipolygone afin de ne conserver qu'une seule entité FINESS 920300043. (Je connais le coin, il s'agit bien de la même structure)
