### ISSUE TITLE
How to tag a path on top of a building so avoid message "Long Highway above ground and no bridge"

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#589]
How to tag a path on top of a building so avoid message "Long Highway above ground and no bridge"

http://osmose.openstreetmap.fr/en/error/31012551031

source | 414832
item | 4110
class | 41106
subclass | 0

http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.422892&lon=-75.692148&item=4110

**Comment by frodrigo** [comment]
Simple mark it as false positive.

**Comment by matthewdarwin** [comment]
If this is the only solution, then I will do that.

**Comment by frodrigo** [comment]
I see no solution, and it should happen rarely.
