### ISSUE TITLE
highway with lanes and railway=abandoned is OK

### ISSUE THREAD

**Issue by zzptichka** [osm-fr/osmose-backend#593]
Right now the following object generates error 9015024 (lanes=* is used for highways, not railways)
```
highway=motorway
lanes=3
railway=abandoned
```

link: https://www.openstreetmap.org/way/467076762
osmose link: http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.35186&lon=-75.784995&item=xxxx&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
Issue com from openrailwaymap.validator.mapcss

https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/validator/openrailwaymap.validator.mapcss#L637

Please report on OpenRailwayMap project.

(cc @Klumbumbus)

**Comment by frodrigo** [comment]
https://github.com/OpenRailwayMap/OpenRailwayMap/issues/660
