### ISSUE TITLE
Add "destination" on one-way-exit way of a roundabout 

### ISSUE THREAD

**Issue by Crochetdavid** [osm-fr/osmose-backend#594]
==French, native language==
Sur les sorties de giratoire (chemin avec "oneway=yes" et dont son origine est un point d'un chemin avec "junction=roundabout") si la destination n'y est pas indiqué (destination=* n'existe pas) alors proposer l'ajout de l'information destination (destination=??).
==English==
On a roundabout exit(way with "oneway=yes" and its begin is a node from a way within "junction=roundabout", if "destination" is not indicated (destination=* do not exist), then propose the addition of the destination information (destination=??).

**Comment by frodrigo** [comment]
This is not about error on the data, it is about improvement. It is out of scope.
