### ISSUE TITLE
False positive: Small highway group apart from the main network on islands with only air access

### ISSUE THREAD

**Issue by rivermont** [osm-fr/osmose-backend#597]
There are many islands around the world with roads on them, that are only accessible by plane, and thus not routable on the ground. [Rota Island in the Marianas](https://en.wikipedia.org/wiki/Rota_(island)#Transportation), for example.  

This is nearly a duplicate of #339, but concerns situations where a ferry does not exist to connect to the main road network.

I'm not sure how this should be addressed, but all of these errors are currently not fixable, though valid problems.

![image](https://user-images.githubusercontent.com/25139386/63909111-8a874b80-c9ef-11e9-980e-b4cd0d299394.png)

**Comment by matkoniecz** [comment]
Maybe create list of starting points of independent road networks, not connected by ferries? Or add this island to such list if it exists already.

**Comment by frodrigo** [comment]
Start point can also be connected airport
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_floating_islands.py#L37-L46

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/138313727#map=17/14.17236/145.24299 seems mapped correctly from the first look

>     (tags?'aeroway' AND tags->'aeroway' IN ('taxiway', 'runway', 'apron')) OR

I am not convinced that `aeroway=runway` attached to road makes sense to tag this (it happens in Gibraltar, but even there it is about crossing rather than transit connectivity).

And roads attached to `aeroway=apron` would be at best private service roads.

**Comment by frodrigo** [comment]
I think there is physical junction between service way and apron in Rota airport. 
I think it is the main case. It is why the analyser check for airport.
We may add some other seed manually in the analyser. But here I think is not necessary.

**Comment by frodrigo** [comment]
Please, reopen if required, or not agree with the current state.

**Comment by EwenH** [comment]
I have the same issue with multiple islands including Elcho Island at the top of Australia 
![image](https://user-images.githubusercontent.com/4280493/66248260-5cbcc180-e768-11e9-8b94-1eac053a2c88.png) There are no ferry services although barges run on an infrequent or ad-hoc service and you may need to hire the barge (bac) for 10 days to get to some of these places.  Flights are the only real way to get here. I don't like setting these to false positives in case further edit mistakes are missed. Is there away to check if the road is on an area marked "place=island" and the island is < 100sqkm perhaps?

**Comment by frodrigo** [comment]
Computing this check will be very expensive. But I think in your case it should be ok, since you already have a taxiway connected to highway.
