### ISSUE TITLE
Split Canada/Québec into sub regions for faster processing

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#600]
http://www.toponymie.gouv.qc.ca/ct/normes-procedures/regles-ecriture/comment-ecrire-region-administrative-touristique.html

canada_quebec_region('abitibi_témiscamingue', 8107213)
canada_quebec_region('bas_saint_laurent', 8137316)
canada_quebec_region('capitale_nationale', 8114679)
canada_quebec_region('centre_du_québec', 8100165)
canada_quebec_region('chaudière_appalaches', 8138409)
canada_quebec_region('côte_nord', 8126390)
canada_quebec_region('estrie', 8098121)
canada_quebec_region('gaspésie_îles_de_la_madeleine', 7485821)
canada_quebec_region('lanaudière', 8098959)
canada_quebec_region('laurentides', 8098885)
canada_quebec_region('laval', 3532125)
canada_quebec_region('mauricie', 8098985)
canada_quebec_region('montérégie', 8093332)
canada_quebec_region('montréal', 1571328)
canada_quebec_region('nord_du_québec', 8118159)
canada_quebec_region('outaouais', 8100164)
canada_quebec_region('saguenay_lac_saint_jean', 8120111)

**Comment by matthewdarwin** [comment]
this is admin_level=5 boundaries

**Comment by jocelynj** [comment]
Split of Quebec is now on master, and configured on http://buildbot2.osmose.openstreetmap.fr/#/builders

**Comment by matthewdarwin** [comment]
So far all the builds have failed.

**Comment by jocelynj** [comment]
I had forgotten to add the new subdivisions to opendata.osmose.openstreetmap.fr. It should work fine on next run.

**Comment by matthewdarwin** [comment]
Builds seem to be completing successfully now.

**Comment by matthewdarwin** [comment]
Old canada_quebec needs to be removed: http://osmose.openstreetmap.fr/en/control/update_matrix?remote=07e9

**Comment by jocelynj** [comment]
Thanks for the notification. I've removed old canada_quebec from server.

**Comment by matthewdarwin** [comment]
Thanks!
