### ISSUE TITLE
False positive: "Possible missing direction tag on stop or a give way" when using cardinal direction=*

### ISSUE THREAD

**Issue by camelCaseSucks** [osm-fr/osmose-backend#602]
https://osmose.openstreetmap.fr/en/map/#zoom=16&lat=45.5275&lon=-122.68093&item=2090&level=1%2C2&tags=&fixable=

Here you can see a lot of issues regarding the direction of stop signs. Most of them are tagged with cardinal directions (N,E,S,W). If these are being ignored intentionally because the direction may be invalid, I'd think it would be possible to verify by checking each highway connected to the node and comparing the angle to the direction tag.

**Comment by matthewdarwin** [comment]
In the case of a 4-way stop, the convention is to put the stop sign on the junction, then direction is not needed.

Else direction is meant to be according to the direction of the way (highway) that contains the stop:  either 'forward' or 'backward'

**Comment by matthewdarwin** [comment]
If your ways terminate at the intersection with the stop sign, the following script can add the forward/backward direction for you: https://github.com/osmottawa/data-research/tree/master/StopYieldDirections  

Instructions: 
1) use the Export to JOSM feature from OSMOSE to get the list of errors, save to file roadsWithSigns.osm
2) run the script and it exports roadsWithSignsAndDirections.osm
3) open that in JOSM, review and upload to OSM

**Comment by frodrigo** [comment]
Yes. Its a misusage of the `direction` tag.
https://wiki.openstreetmap.org/wiki/Key:direction
