### ISSUE TITLE
duration syntax checker

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#603]
source | niv | item | cl | scl | E | pos | élmts | sous-titre | ✘/✔
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
407663 | 2 | 9014             transport en commun | 9014022 | 1468186952 | E | -4.50 48.39 | r          6674962                    (j) | La durée est invalide (essayer un nombre en minutes) | ✘/       ✔

On https://www.openstreetmap.org/relation/6674962, the duration is PT2M, this is a possible value according to the wiki https://wiki.openstreetmap.org/wiki/Key:duration

Of course I can change to 00:02, as this format is preferred, but a least the error message (and the level of error) is wrong.

**Comment by frodrigo** [comment]
cc @nlehuby

**Comment by frodrigo** [comment]
The issue should be reported to https://github.com/Jungle-Bus/transport_mapcss
But keep it here.

**Comment by frodrigo** [comment]
@nlehuby it is feasible with mapcss/regex or not ?

**Comment by nlehuby** [comment]
I won't have time to properly dig into the ISO 8601 spec before a few weeks, but I guess it's feasible with a regexp if anyone want to give it a try.

However, I'm still to sure if it is worth it as the usage is very low and this format is not supported by any known OSM data users 🤔

**Comment by frodrigo** [comment]
So we remove this rule?

**Comment by Bibi56** [comment]
@nlehuby, something like 
`^P(?!$)((\d+Y)|(\d+\.\d+Y$))?((\d+M)|(\d+\.\d+M$))?((\d+W)|(\d+\.\d+W$))?((\d+D)|(\d+\.\d+D$))?(T(?=\d)((\d+H)|(\d+\.\d+H$))?((\d+M)|(\d+\.\d+M$))?(\d+(\.\d+)?S)?)??$`
?
Found on [StackOverflow](https://stackoverflow.com/questions/32044846/regex-for-iso-8601-durations).

**Comment by nlehuby** [comment]
The support of the ISO 8601 format for duration has been removed from the wiki a few month ago and the usage in the data is still very low.
I think we can remove the regexp added on last october.
Does it sound ok for you ?

**Comment by frodrigo** [comment]
Remove sound very good to me!

**Comment by frodrigo** [comment]
ISO format support removed.
