### ISSUE TITLE
potential "false positive" for rule "Almost junction, join or use noexit tag"

### ISSUE THREAD

**Issue by my-na-me** [osm-fr/osmose-backend#606]
node: https://www.openstreetmap.org/node/250048648
The item and class number:
http://osmose.openstreetmap.fr/en/error/31911891258
Or at least a permalink to the Osmose map.
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.656347&lon=11.984962&item=xxxx&level=1&tags=&fixable=

The message says: "Almost junction, join or use noexit tag" but it seems there is no gap between the nodes.
Is this a false positive? If so, could you check the relevant validation rule, maybe this rule could be modified/improved to don't show this kind of false positives anymore.

Thanks a lot

**Comment by frodrigo** [comment]
Yes something is not working in this case.

**Comment by my-na-me** [comment]
OK, thanks for checking :-)

**Comment by frodrigo** [comment]
There is no more the osmose issue and no idea what it could be.

I close, but feel free to add more details or reopen.
