### ISSUE TITLE
Roundabout suggested but only footway connected	

### ISSUE THREAD

**Issue by boothym** [osm-fr/osmose-backend#607]
http://osmose.openstreetmap.fr/en/error/31991946544

Osmose suggests adding junction=roundabout here - however, other than the footway there is only one road connected to the circular road. 

Of course a roundabout needs two roads connecting to it - therefore footways, cycleways, bridleways, and paths should be excluded from the highway count.

**Comment by frodrigo** [comment]
It should be fixed. But do you have a permalink to your original issue?

**Comment by boothym** [comment]
Sorry for the delay. I don't have a permanlink, but I can't find examples on Osmose in the area I was looking at previously so I assume it is now fixed.

**Comment by frodrigo** [comment]
Yes. It should be fixed. The ask of the permalink was just to be sure.
