### ISSUE TITLE
GeoJSON source fail because of polymorphic source

### ISSUE THREAD

**Issue by wadouk** [osm-fr/osmose-backend#608]
In case of the "properties" are not the same for all items, it fails to import because [only the first item](https://github.com/osm-fr/osmose-backend/blob/a3de6d54ebf02dd1241c35a694e498409f8176cb/analysers/Analyser_Merge.py#L498) is analyzed.
`
psycopg2.errors.UndefinedColumn: column "horaires" of relation "defibrillateurs_fr_issylesmoulineaux"
` on this [source](https://data.issy.com/explore/dataset/defibrillateurs-issy-les-moulineaux/information/)
```json

    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          2.261550262,
          48.82544425
        ]
      },
      "properties": {
        "localisation": "4 boulevard Garibaldi",
        "acces": "Intérieur du bâtiment",
        "titre": "Défibrillateur Centre Technique Municipal",
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          2.269434522,
          48.82248028
        ]
      },
      "properties": {
        "horaires": "Du lundi au vendredi de 8h30 à 18h30, du mardi au jeudi de 8h30 à 12h et de 14h30 à 18h30. Fermé au mois d'août.",
        "localisation": "Entrée 27 bis avenue Victor Cresson. Marcher 40 mètres jusqu'au bâtiment.",
        "acces": "Intérieur du bâtiment",
        "titre": "Défibrillateur Centre Municipal de Santé",
      }
    },
```
What would be the easier fix ?
Look for all features to merge all properties ?
Ignore a property if not like the first item ?

**Comment by wadouk** [comment]
I will try to use the CSV version by splitting the "Coordonnées géographiques" like in [this analyser](https://github.com/osm-fr/osmose-backend/blob/a3de6d54ebf02dd1241c35a694e498409f8176cb/analysers/analyser_merge_public_transport_FR_star.py#L38)

**Comment by frodrigo** [comment]
Would be nice, but not required for now.
