### ISSUE TITLE
Add checks against the name suggestion index

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#609]
This is an enhancement request to import data from the http://osmlab.github.io/name-suggestion-index/ and then if a "node" or "way" or "relation" matches the "brand:wikidata" tag in OSM, then check that the other tags contained within the name-suggestion-index (NSI) are consistent.

**Comment by matthewdarwin** [comment]
The Name Suggestion Index en discussed at the State-of-the-Map US conference this weekend, and the talk will be available on Youtube soon.

**Comment by frodrigo** [comment]
Already done #874
http://osmose.openstreetmap.fr/en/errors/?item=3130
