### ISSUE TITLE
Feature request: check "name:es" without "name:ca"

### ISSUE THREAD

**Issue by jmontane** [osm-fr/osmose-backend#61]
Hi,

I request a custom local rule to check objects (nodes, ways, and relations) with "name:es" but lacking "name:ca".

This rule can be applied to Catalonia, Comunitat Valenciana, Illes Balears (Spanish regions), and Andorra, where Catalan is preferred language for "name"

**Comment by frodrigo** [comment]
There is already a rule in Osmose QA for that. But it is not applied because here, because there is no unique language defined in setting for such areas. Check the configuration:
https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L845

**Comment by frodrigo** [comment]
Btw, it you insterested you can provite "translation" for plugin languge or country based. Look at *_FR, *_fr, *_es and so on here :
https://github.com/osm-fr/osmose-backend/tree/master/plugins

**Comment by jmontane** [comment]
Great,

Let me explain to verify I understand correctly your messagges

If I change 
https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L845
to
es_comm("catalunya", 349053, proj=32630, analyser_options={"language": ["ca"]})
then, an issue will be created if missing "name:ca", right? Is there any counter-effect?

Following 2n comment,
Are *_es plugins applyed only if Spanish language is selected in Osmose front-end? or are they applyed always to "name:es" tags?

Thanks!

**Comment by frodrigo** [comment]
Where there is multiple language is almost the same thing as no language. Language specific analyses are disabled.

*_es are apply mainly on default name when language is ["es"].
