### ISSUE TITLE
Feature request: detect way "name" tag with selected words

### ISSUE THREAD

**Issue by jmontane** [osm-fr/osmose-backend#62]
Hi,

I request a rule to detect ways with "name" tag starting with words: Calle, Camino, Avenida, Plaza, or Pasaje. These are Spanish words for type of way.

Such rule should be applied to Catalonia, Illes Balears (Spanish regions), and Andorra, where Catalan languages is preferred.

Some mappers use Spanish names for ways, but Catalan community use Catalan names for "name" and "name:ca" tags and Spanish names for "name:es" tag.
See this Overpass-turbo query
http://overpass-turbo.eu/s/at7

There are two Spanish regions, Comunitat Valenciana and Aragon, where language preference is city based. So, I don't know if it's possible to develop such rule for Valencian and Aragon regions.

**Comment by frodrigo** [comment]
Still needed ?

**Comment by frodrigo** [comment]
I close, complain if needed.
