### ISSUE TITLE
seamark object not rendered

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#620]
Hi,

Seamark objects aren't rendered if they don't have a `seamark:type` key.

For example, node [2179941346](https://www.openstreetmap.org/node/2179941346) has only `seamark:landmark:category=flare_stack`
It need `seamark:type=landmark`.

Here is an Overpass query that find all theses objects in the earth:
[`~"seamark"~".*" and "seamark:type"!=* global`](https://overpass-turbo.eu/s/MsK)

Founded:

- 5 139 nodes
- 372 ways
- 25 relations
- 96 keys

Probably some other checks could be done for seamarks…

Keys:

- seamark
- seamark:buoy_cardinal:colour_pattern
- seamark:buoy_cardinal:shape
- seamark:buoy_isolated_danger:colour
- seamark:buoy_isolated_danger:shape
- seamark:buoy_lateral:category
- seamark:buoy_lateral:colour
- seamark:buoy_lateral:shape
- seamark:buoy_lateral:system
- seamark:buoy_special_purpose:category
- seamark:buoy_special_purpose:colour
- seamark:buoy_special_purpose:colour_pattern
- seamark:buoy_special_purpose:shape
- seamark:crane:category
- seamark:daymark:colour
- seamark:distance_mark:distance
- seamark:distance_mark:units
- seamark:fixme
- seamark:fog_signal:category
- seamark:gate:category
- seamark:harbour:category
- seamark:information
- seamark:landmark:category
- seamark:landmark:colour
- seamark:landmark:conspicuity
- seamark:landmark:function
- seamark:landmark:height
- seamark:landmark:name
- seamark:light_float:colour
- seamark:light:1:category
- seamark:light:1:character
- seamark:light:1:colour
- seamark:light:1:group
- seamark:light:1:height
- seamark:light:1:orientation
- seamark:light:1:period
- seamark:light:1:range
- seamark:light:1:sector_end
- seamark:light:1:sector_start
- seamark:light:1:sequence
- seamark:light:1:visibility
- seamark:light:2:character
- seamark:light:2:colour
- seamark:light:2:height
- seamark:light:2:period
- seamark:light:2:range
- seamark:light:2:sector_end
- seamark:light:2:sector_start
- seamark:light:2:sequence
- seamark:light:category
- seamark:light:character
- seamark:light:colour
- seamark:light:exhibition
- seamark:light:group
- seamark:light:height
- seamark:light:multiple
- seamark:light:period
- seamark:light:range
- seamark:light:reference
- seamark:light:sequence
- seamark:marine_farm:category
- seamark:mooring:category
- seamark:mooring:colour
- seamark:mooring:shape
- seamark:name
- seamark:notice:1:category
- seamark:notice:1:function
- seamark:notice:1:orientation
- seamark:notice:1:system
- seamark:notice:2:category
- seamark:notice:2:function
- seamark:notice:2:orientation
- seamark:notice:2:system
- seamark:notice:category
- seamark:notice:function
- seamark:notice:information
- seamark:notice:orientation
- seamark:obstruction:category
- seamark:pile:category
- seamark:pylon:category
- seamark:radar_reflector
- seamark:radio_station:callsign
- seamark:radio_station:category
- seamark:radio_station:channel
- seamark:rock:water_level
- seamark:sea_area:category
- seamark:seabed_area:surface
- seamark:shoreline_construction:category
- seamark:signal_station_traffic:category
- seamark:small_craft_facility:category
- seamark:source
- seamark:status
- seamark:topmark:colour
- seamark:topmark:shape
- seamark:wreck:category
- seamark:wreck:water_level

**Comment by frodrigo** [comment]
Please, can you link a wiki page about the mandatory of `seamark:type=landmark` tag.

**Comment by pyrog** [comment]
`seamark:type=*` is mandatory.
The **value** must be one of the column **object key** in [Seamarks/Seamark Objects](https://wiki.openstreetmap.org/wiki/Seamarks/Seamark_Objects).

Sources:
https://github.com/OpenNauticalChart/renderer/issues/2#issuecomment-533446256
> Objects without a "seamark:type" tag do not get rendered.

[Seamarks/Landmarks](https://wiki.openstreetmap.org/wiki/Seamarks/Landmarks#Landmarks)
> This page defines values […] for objects tagged as "seamark:type=landmark".

**Comment by frodrigo** [comment]
For all `seamark:YYY:category` of an object. `YYY` must be unique and `seamark:type=YYY`, must not?

**Comment by pyrog** [comment]
`seamark:type=X`
`seamark:X:Z=V`
`seamark:X:1:Z=V`
`seamark:X:2:Z=V
…

`seamark:Y:Z=V`
`seamark:Y:1:Z=V`
`seamark:Y:2:Z=V
…

Where `X` and 'Y' are **[objects](https://wiki.openstreetmap.org/wiki/Seamarks/Seamark_Objects)**, `Z` are **[attributes](https://wiki.openstreetmap.org/wiki/Seamarks/Seamark_Attributes)**and `V` are **values**.
(Came from [IHO standards](https://www.iho.int/srv1/index.php?option=com_content&view=article&id=448&Itemid=345&lang=fr) : [S-57](http://www.s-57.com/) and [S-100](http://s100.iho.int/S100/))

See [Seamark tagging schema](https://wiki.openstreetmap.org/wiki/Seamark_tagging_schema).

Example:

[Gellen lighthouse
<img width="486" alt="Gellen lighthouse" src="https://user-images.githubusercontent.com/2158081/65339940-6ae9da00-dbcd-11e9-8ac6-9ae4e612be5f.png">
](https://www.openstreetmap.org/way/233359892)

This is a **[landmark](https://wiki.openstreetmap.org/wiki/Seamarks/Landmarks)**:
`seamark:type=landmark`
`seamark:landmark:*=*`

But also a **[light](https://wiki.openstreetmap.org/wiki/Seamarks/Lights)** with 7 [sectors](https://wiki.openstreetmap.org/wiki/Seamarks/Sectored_and_Directional_Lights):
`seamark:light:1:*=*`
`seamark:light:2:*=*`
…
`seamark:light:7:*=*`

Another lighthouse, buoy… could have [fog signals](https://wiki.openstreetmap.org/wiki/Seamarks/Fog_Signals), [radio stations](https://wiki.openstreetmap.org/wiki/Seamarks/Radio_Stations) (radar, AIS…) and so on.

**Comment by frodrigo** [comment]
So what do you want to be checked?

Le ven. 20 sept. 2019 à 18:09, Yves Pratter <notifications@github.com> a
écrit :

**Comment by pyrog** [comment]
Just object with keys starting with `seamark`: without key `seamark:type`.

**Comment by pyrog** [comment]
Key `seamark:type` must be proposed, but the value is tricky.

For `seamark:landmark:*` the value is obvious.

For lights, the value, could be `light_major`, `light_minor`, `light_vessel`, `light_float`…
…but also `landmark`, `beacon_cardinal`…, `buoy_lateral`… and many more.

For example, what is the type for node [4458225614](https://www.openstreetmap.org/node/4458225614) with only the following tags?
- `name=R`
- `seamark:topmark:colour=red`
- `seamark:topmark:shape=cylinder`

`seamark:type=`[`mooring`](https://wiki.openstreetmap.org/wiki/Seamarks/Moorings), [`beacon_lateral`](https://wiki.openstreetmap.org/wiki/Seamarks/Beacons), [`buoy_cardinal`](https://wiki.openstreetmap.org/wiki/Seamarks/Buoys)…

**Comment by frodrigo** [comment]
Ok. We should add a new MapCSS rule about this.

**Comment by pyrog** [comment]
I see http://github.com/osm-fr/osmose-backend/blob/master/plugins/Josm_Seamark.py that seemed to be generated from mapcss rules.

Where are the rules ?
In https://josm.openstreetmap.de/browser/josm/trunk/data/validator?order=name ?

**Comment by frodrigo** [comment]
The MapCSS are from https://github.com/OpenNauticalChart/josm
