### ISSUE TITLE
fuel:e10 = no   	8202 Service station, to be updated

### ISSUE THREAD

**Issue by Bernard59118** [osm-fr/osmose-backend#624]
Hello,
You report an error for
fuel: e10 = no
This possibility is given by the JOSM preset.
I agree that this is not helpful, but generates errors in Osmose
cordially
Bernard59118

**Comment by frodrigo** [comment]
Please can you add a perma link to see witch analysis provide this issue.

Le lun. 23 sept. 2019 à 12:14, Bernard59118 <notifications@github.com> a
écrit :

**Comment by frodrigo** [comment]
ping

**Comment by frodrigo** [comment]
Please, reopen with more details.
