### ISSUE TITLE
"Unconnected waterway or wrong way flow" false positive

### ISSUE THREAD

**Issue by Veverica10** [osm-fr/osmose-backend#625]
Hi,
a waterway=stream flows into waterway=ditch (https://www.openstreetmap.org/way/718167524). It gives a low osmose issue "Unconnected waterway or wrong way flow" and this is a false positive check. There shoud be no issue in such situation.

Thank you for the patch,

Greetings, Peter

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#item=1220&zoom=17&lat=46.146105&lon=14.489534&level=1%2C2%2C3&tags=&fixable=

analyser_osmosis_waterway.py

**Comment by mephinet** [comment]
I think this rule also needs to be extended to account for a stream flowing into a lake (technically, into a way that has a relation to a lake of type "outer"). Example of false positives: https://osmose.openstreetmap.fr/de/map/#way=95868598

**Comment by frodrigo** [comment]
@mephinet the graph mus also be present in lake, like the there is no lake
https://www.openstreetmap.org/#map=16/42.6425/2.1224&layers=D

**Comment by klenje** [comment]
@frodrigo I was looking into this, any reason why analyser_osmosis_waterway.py doesn't have some tests like https://github.com/osm-fr/osmose-backend/blob/0a3308894844b1a16e7808308c5d14c8a61289b9/analysers/analyser_osmosis_roundabout_reverse.py#L76 ? Can I add them?

**Comment by frodrigo** [comment]
Most of the Osmosis Analyser does not have test. I think they was introduced later.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=1220&class=2

**Comment by mephinet** [comment]
@frodrigo Ah, thanks for the clarification! I wan't aware that the river is supposed to continue through the lake.
