### ISSUE TITLE
Do not report 1210 not-connected cycleway if it ends on amenity=bicycle_parking

### ISSUE THREAD

**Issue by danfos** [osm-fr/osmose-backend#627]
I see that osmose is reporting a 1210 not-connected highway/cycleway if a cycleways ends on an amenity=bicycle_parking while I think that makes perfectly sense.

Examples:
- http://osmose.openstreetmap.fr/en/map/#item=1210&zoom=17&lat=51.922322&lon=4.574212&level=1
- http://osmose.openstreetmap.fr/map/#&item=1210&zoom=17&lat=51.9122093&lon=4.5662169&level=1

Can the checker be extended to ignore this?

**Comment by danfos** [comment]
Would be also good to ignore if the way ends on a node with "noexit=yes", sometimes cycleways does really end, see for example:

http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=51.809974&lon=4.435729&item=1210&level=1

**Comment by danfos** [comment]
Had a look on how to fix this and I think the responsible code is:

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_deadend.py#L25-L64

While I am no fluent on SQL I see:
```
    JOIN nodes ON
        nodes.id = way_ends.nid AND
        (NOT nodes.tags?'highway' OR nodes.tags->'highway' != 'turning_circle') AND
        (NOT nodes.tags?'entrance' OR nodes.tags->'entrance' != 'no') AND
        (NOT nodes.tags?'noexit' OR nodes.tags->'noexit' != 'no')
```

So should that no already take care of ways ending on a node with "noexit=yes?

Is the code not doing what it is supposed to do?

**Comment by frodrigo** [comment]
A fix done in June, but only for parking on node.
http://osmose.openstreetmap.fr/en/errors/graph.png?item=1210&class=1&start_date=2020-05

**Comment by frodrigo** [comment]
Note to myself:
http://osmose.openstreetmap.fr/en/errors/?source=5069&item=1210&class=1
http://osmose.openstreetmap.fr/fr/map/#item=1210&zoom=18&lat=52.136021&lon=5.033996&level=1&tags=&fixable=&class=1

**Comment by danfos** [comment]
FYI, I had a look at http://osmose.openstreetmap.fr/en/errors/?source=4709&item=1210&class=1 and checked about 100 of this warnings. I solved the ones I could but did leave open the ones that I think should be ignored.

The majority is a cycleway ending on a way tagged with amenity=bicycle_parking (14) and with highway=construction (13) and I found one ending on a way tagged with highway=pedestrian + area=yes.

_way amenity=bicycle_parking_
https://www.openstreetmap.org/node/7830481936
https://www.openstreetmap.org/node/7667968200
https://www.openstreetmap.org/node/7512379600
https://www.openstreetmap.org/node/7511564346
https://www.openstreetmap.org/node/6794207285
https://www.openstreetmap.org/node/7218240023
https://www.openstreetmap.org/node/7194236579
https://www.openstreetmap.org/node/7152340772
https://www.openstreetmap.org/node/7100225620
https://www.openstreetmap.org/node/6563413804
https://www.openstreetmap.org/node/6518217622
https://www.openstreetmap.org/node/6153835745
https://www.openstreetmap.org/node/6153835743
https://www.openstreetmap.org/node/6153835740

_way highway=construction_
https://www.openstreetmap.org/node/5207957542
https://www.openstreetmap.org/node/7109186818
https://www.openstreetmap.org/node/7569684742
https://www.openstreetmap.org/node/7638249758
https://www.openstreetmap.org/node/7463929595
https://www.openstreetmap.org/node/6316706738
https://www.openstreetmap.org/node/7480058568
https://www.openstreetmap.org/node/7479949986
https://www.openstreetmap.org/node/7477048420
https://www.openstreetmap.org/node/6811586752
https://www.openstreetmap.org/node/6624823147
https://www.openstreetmap.org/node/6553383117
https://www.openstreetmap.org/node/6553371927

_way highway=pedestrain + area=yes_
https://www.openstreetmap.org/node/7419194112

**Comment by frodrigo** [comment]
Thank you. I made a fix yesterday, but still need check before publishing it.
