### ISSUE TITLE
Check wikimedia_commons values

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#628]
According to the wiki, `wikimedia_commons` values must start with `File:` or `Category:`

* [File:Bicycle crossing, Poland, Kraków, Josepha Conrada.JPG](http://en.wikipedia.org/wiki/commons:File:Bicycle_crossing,_Poland,_Krak%C3%B3w,_Josepha_Conrada.JPG)
* [Category:St Paul, Birmingham](http://en.wikipedia.org/wiki/commons:Category:St_Paul,_Birmingham)

Unfortunately, some users use bad values:

1. `File:` or `Category:` prefixes are missing
1. Full URL<br/>http://en.wikipedia.org/wiki/commons:Category:St_Paul,_Birmingham
2. URL to one version of the image<br/>https://upload.wikimedia.org/wikipedia/commons/1/11/Sottopasso_San_Candido_.jpg
3. URL to other websites<br>https://www.tuepedia.de/images/9/94/Käppele_in_Derendingen.JPG
1. Broken values
1. Deleted files or categories<br/>[File:Plaque "ici vécu Léon Vallas", rue Vendôme à Lyon.jpg](https://commons.wikimedia.org/wiki/File:Plaque_%22ici_vécu_Léon_Vallas%22,_rue_Vendôme_à_Lyon.jpg)

The first 3 issues could be corrected automatically.
The 4th too, replace `wikimedia_commons` key by `image`.

PS: There is **1410** values contains `http`

**Comment by frodrigo** [comment]
Can you try to make the corresponding MapCSS code, please?

**Comment by pyrog** [comment]
Is it here?
https://josm.openstreetmap.de/browser/josm/trunk/data/validator/wikipedia.mapcss

**Comment by frodrigo** [comment]
Yes, you can improve this one.

**Comment by frodrigo** [comment]
Ping @pyrog
