### ISSUE TITLE
don't count disused:boundary as a missing tag on boundarys

### ISSUE THREAD

**Issue by ferdinand0101** [osm-fr/osmose-backend#631]
I have no Idea on how to implement this but this seem like a thing which should be done

**Comment by frodrigo** [comment]
Please, can you give a permalink to the map or the item/class id of the Osmose issue.

**Comment by ferdinand0101** [comment]
Osmose issue item=9007, class=9007001
https://www.openstreetmap.org/relation/2362246#map=12/43.3468/-1.7132

**Comment by frodrigo** [comment]
It is coming from the JOSM MapCSS rules validation
https://josm.openstreetmap.de/browser/josm/trunk/data/validator/relation.mapcss#L14

cc @Klumbumbus

**Comment by ferdinand0101** [comment]
thank you I have forewarded it to the JOSM team

**Comment by ferdinand0101** [comment]
should I close it now ?

**Comment by frodrigo** [comment]
No.

I am still not sure it is an issue.

**Comment by Klumbumbus** [comment]
Lifecycle tags are not yet really supported in JOSM. A more universal solution is preffered but not yet invented, see https://josm.openstreetmap.de/ticket/16093. Not sure if this particular case is important enough to create a special fix.

**Comment by frodrigo** [comment]
Reopen if required.
