### ISSUE TITLE
Conflict between tags: leisure, natural for nature_reserve and scrub

### ISSUE THREAD

**Issue by EwenH** [osm-fr/osmose-backend#633]
I believe there maybe a false positive regarding "Conflict between tags: leisure, natural"

Example: relation 6742680
http://osmose.openstreetmap.fr/en/map/#zoom=16&lat=-34.37085&lon=141.17088&item=xxxx&level=1&tags=&fixable=

Some of the key tags are:
- boundary = protected_area 
- **leisure = nature_reserve** 
- name = Morkala Bushland Reserve 
- **natural = scrub** 
- protect_class = 4 
- type = boundary 

Is there a valid reason why these are not permitted or should they be allowed to co-exist?

Thanks for the excellent resource.

**Comment by frodrigo** [comment]
Done.

**Comment by EwenH** [comment]
Thank you so much @frodrigo
