### ISSUE TITLE
Sudden highway change for secondary_link connected to unclassified/residential

### ISSUE THREAD

**Issue by YaroShkvorets** [osm-fr/osmose-backend#635]
Is there any reason why `highway=secondary_link` connected to `highway=residential` or `highway=unclassified` produces this warning? [Example](http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.350835&lon=-75.845404&item=xxxx&level=1%2C2&tags=&fixable=).
As far as I can see in the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dsecondary_link), it's acceptable, specifically: 
`Therefore, highway=secondary_link should be used on a slip road/ramp which connects a highway=secondary to a tertiary, unclassified or other minor highway.`

**Comment by frodrigo** [comment]
Theoretically, the road network should be consistent by level and connected next lower level.

But it depend of country and local community.

cc @matthewdarwin

**Comment by zzptichka** [comment]
Aha I see. In Canada and US our planners liked to build these deadly `secondary_link` slip lanes everywhere instead of building regular perpendicular intersections. I guess in Europe they are not that common and as far as I know we are moving away from them as well.
 
IMO connecting `secondary_link` to `unclassified` should be allowed. At least in Canada/US.

**Comment by matthewdarwin** [comment]
agree we get secondary_link connected to lower class roads here in North America.  Maybe just start with exception in Ontario and expand as other people see the issue as well.

**Comment by sannius** [comment]
In Israel it's a common pattern, almost every interchange with traffic signal have such lanes that allows right turn avoiding signal. Now the error spams issue landscape greatly. Please add exception for us too.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=1090&class=2
I think the *_link should be allow to connect to anything.

**Comment by matthewdarwin** [comment]
Not sure what you mean by "anything".   Really it should be anything of equal or lower rank.

You can't have a tertiary road connect to a residential road via a secondary_link.  The link should probably (?) be always the highest class of road?

**Comment by frodrigo** [comment]
Yes, sure, respecting this rule.

**Comment by zzptichka** [comment]
Agreed.
motorway_link  is a bit different though. These interchanges are rare and expensive to build and I've never seen one connected to a minor road.

**Comment by sannius** [comment]
motorway_link really depends on terrain - in mountain areas you may have an isolated farm that have no other road, so slipway is constructed that leads to service road, at best.

**Comment by frodrigo** [comment]
Fix it by one more level to tolerance when checking `*_link`. Allow end of `seondary_link` to residential, but not end of `secondary`.

http://osmose.openstreetmap.fr/en/errors/?item=1090&class=2
http://osmose.openstreetmap.fr/en/errors/graph.png?item=1090&class=2
