### ISSUE TITLE
Umbalanced (( are wrong for right-to-left languages

### ISSUE THREAD

**Issue by sannius** [osm-fr/osmose-backend#642]
The rule for right-to-left languages (like Hebrew) should be reversed.
Not it flags perfectly fine strings

source | 16090
item | 5070
class | 50704
subclass | 1

http://osmose.openstreetmap.fr/en/error/33247092172

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#item=5070&zoom=17&lat=31.968273&lon=34.841873&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
Osmose is right.

"120 - (בי"ס אסיף (התפתחות הילד " contains twice `)`, but not written in the direction.
