### ISSUE TITLE
How to specify the projection in analyser ?

### ISSUE THREAD

**Issue by wadouk** [osm-fr/osmose-backend#655]
I have to manage a data source with Lambert 93 projection ? 
Does it exist a sample to manage it ?

https://www.data.gouv.fr/fr/datasets/defibrillateurs-1/
I have to use the csv because I can't guess the encoding for the shape file.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_public_transport_FR_stif.py#L37

**Comment by wadouk** [comment]
srid ?

**Comment by frodrigo** [comment]
https://fr.wikipedia.org/wiki/Syst%C3%A8me_de_coordonn%C3%A9es_(cartographie)
