### ISSUE TITLE
How to merge multiple files before loading analysis ?

### ISSUE THREAD

**Issue by wadouk** [osm-fr/osmose-backend#656]
On this data set there is multiple files and there will be great to load a script for download them all, and merge before running the analyser. 

https://www.data.gouv.fr/fr/datasets/defibrillateurs-publics/

Any sample ?

**Comment by frodrigo** [comment]
You can build a custom source to merge the data.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge_Geocode_Addok_CSV.py

No need to build an external py file, as it will not be reusable.
