### ISSUE TITLE
Bicycle not drive side deps.

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#657]
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Bicycle.validator.mapcss#L89-L99

The side should deps on drive side.

This rule is realy valid?

**Comment by danfos** [comment]
Is this about:

```
way[cycleway=~/opposite|opposite_lane/][!oneway],
way[cycleway=~/opposite|opposite_lane/][oneway=no]
```

If so, I think this is correct, see https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dopposite

> Use cycleway=opposite for situations where cyclists are permitted to travel in both directions **on a road which is one-way for normal traffic**

and from https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dopposite_lane

> **Used on a one-way street** that has a cycling lane going in the opposite direction to normal traffic flow (a "contraflow" lane)

**Comment by frodrigo** [comment]
The question is about this version of file https://github.com/osm-fr/osmose-backend/blob/3ca43550e2594953c88d08c96480332e435be944/plugins/Bicycle.validator.mapcss#L89-L99

**Comment by frodrigo** [comment]
https://overpass-turbo.eu/s/Z3T

```
[out:json][timeout:25];
{{geocodeArea:france}}->.searchArea;
(
way["cycleway:right"="opposite"][oneway=yes](area.searchArea);
way["cycleway:right"="opposite_lane"][oneway=yes](area.searchArea);
);
out body;
>;
out skel qt;
```

**Comment by frodrigo** [comment]
opposite is not marked, so cannot be right or left. OK to keep this rule.

**Comment by frodrigo** [comment]
https://wiki.openstreetmap.org/wiki/Key:cycleway:left#Invalid_values
https://wiki.openstreetmap.org/wiki/Key:cycleway:right:oneway

**Comment by danfos** [comment]
Yes, I would be better to slowly get rid of cycleway;[left/right]=opposite_lane and replace it by cycleway;[left/right]=lane + oneway:bicycle=no
