### ISSUE TITLE
SP95 versus SP95-E10

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#658]
"Does this station still sell SP95, or has it been replaced by the SP95-E10?" is a question I get [here](http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=47.785786&lon=-3.49039&item=xxxx&level=1%2C2%2C3&tags=&fixable=).
I don't get why the question is raised as in
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_fuel_FR.py you're using a source that make the distinction between both and they correctly state SP95.
If possible, don't raise false positive or give a link to the source (or the more user friendly [OpenFuelMap](https://openfuelmap.net/#18/47.78616/-3.49067)).

Note: initially I thought it was a backend issue, it may be a front end issue.

https://osmose.openstreetmap.fr/fr/error/33639047105
https://osmose.openstreetmap.fr/fr/map/#item=4061&zoom=17&lat=47.785833&lon=-3.491244&level=1%2C2%2C3&tags=&fixable=

clé | valeur
-- | --
source | 407718
item | 4061
class | 40612
subclass | 0
elems | node323161771
lat lon | 47.7858308 -3.4912398
title | enDoes this station still sell SP95, or has it been replaced by the SP95-E10? | en | Does this station still sell SP95, or has it been replaced by the SP95-E10?
en | Does this station still sell SP95, or has it been replaced by the SP95-E10?
subtitle | enDoes this station still sell SP95, or has it been replaced by the SP95-E10? | en | Does this station still sell SP95, or has it been replaced by the SP95-E10?
en | Does this station still sell SP95, or has it been replaced by the SP95-E10?
timestamp | 2019-10-09 03:09:02

**Comment by frodrigo** [comment]
cc @PanierAvide

**Comment by frodrigo** [comment]
It comes from this rule https://github.com/osm-fr/osmose-backend/blob/4428382621b8119ba2437b40892c01b7ef8a3276/plugins/Josm_FranceSpecificRules.py#L149

**Comment by PanierAvide** [comment]
I added this rule because many fuel stations are not up-to-date on OSM in France regarding this topic. Most of them were selling SP95 in the past, but only sell SP95-E10 as now. The tags are not updated, so this warning is to alert user and make them check. Warning is not thrown if you have a `fuel:e10=*` tag, meaning that the distinction was made.

**Comment by frodrigo** [comment]
It is not the first time, someone ask for this. Maybe the message should be improved?

**Comment by Bibi56** [comment]
In this case the source says that SP95, not SP95-E10. Some fuel stations, like this [one](http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=47.76442&lon=-3.39521&item=xxxx&level=1%2C2%2C3&tags=&fixable=) deliver both.
Yes @frodrigo, informing that we can check with OpenFuel and mark as false positive would be better than the current message.
But it could be more generic: we know what is delivered and what is not. So proposing to add the missing tags and to remove the outdated tags (as you do with other data) would be even better.

**Comment by PanierAvide** [comment]
Note that official source used in OpenFuelMap has wrong information. I have at least two stations around my city which are incorrectly set as selling SP95 when they really sell only SP95-E10. This information should be changed in OSM only by going there or using recent street pictures.

And we can change message, but we should make clear that people should check if station is still really selling SP95 and not only SP95-E10.
