### ISSUE TITLE
Which categories of establishments are reconciled using the FINESS database

### ISSUE THREAD

**Issue by vinber** [osm-fr/osmose-backend#666]
Actuellement :
Valeur fichier FINESS,item osmose,?,importance ?,Nom descriptif, tag osm, tag osm, ...

1101|1102|1106|,,,,Hôpital,amenity=hospital
2201|2202|2204|2205|2206,,,Établissements de soins autres que les hopitaux,healthcare=yes
3101,,,Laboratoire de Biologie Médicale,healthcare=laboratory,healthcare:speciality=biology
3201,8210|7150,0,3,Pharmacie,amenity=pharmacy,dispensing=yes
4301,,,Établissement et services d'hébergement pour adultes handicapés,amenity=social_facility,social_facility=group_home,social_facility:for=disabled
4302,,,Établissements et services de travail protégé pour adultes handicapés,amenity=social_facility,social_facility=workshop,social_facility:for=disabled
4401,,,Etablissements d'Hébergement pour Personnes Âgées,amenity=social_facility,social_facility=group_home,social_facility:for=senior
4501,,,Etablissements de l'Aide Sociale à l'Enfance,amenity=social_facility,social_facility=group_home,social_facility:for=child
5101,,,Crèches, mutliaccueil enfants de - de 6 ans,amenity=kindergarten

@zorglubu :  

> il faudrait certainement ajouter au moins les catégories 1103(CHS), 1104(CLCC),

**Comment by frodrigo** [comment]
Vous pouvez proposer la modif du fichier de conf svp? https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.csv

**Comment by frodrigo** [comment]
cc @zorglubu

**Comment by zorglubu** [comment]
Ajouter en première ligne les catégories 1103 ,04, 06, 07, 09, 10, 11 qui sont des structures "hospital" largement présentes sur OSM.
Avec la remarque qu'on pourrait aussi indiquer la healthcare:speciality en fonction de cette catégorie.

**Comment by frodrigo** [comment]
Désolé, je ne sais pas ce qu tu veux dire. Tu peux modifer le fichier, stp ?

**Comment by zorglubu** [comment]
Je suis totalement novice sur osmose et github, je n'ose pas trop toucher quoi que ce soit, sauf à être un peu guidé :-)
Je propose une ligne comme :
1101|1102|1103|1104|1106|1107|1109|1110|1111|,,,,Hôpital,amenity=hospital

**Comment by frodrigo** [comment]
https://github.com/frodrigo/osmose-backend/commit/9dfea0a9cc2df11968bbd0859f4ddcd6c5f33c99

**Comment by vinber** [comment]
Merci @zorglubu 

Première étape, les amenity=hospital
Deuxième étape on ajoute les healthcare:speciality

Si je comprends bien ce que tu dis, alors ici on peut faire mieux sur le wiki osm : https://wiki.openstreetmap.org/wiki/FR:Tag:amenity=hospital#Pour_la_France

**Comment by zorglubu** [comment]
Oue est le meilleur endroit pour discuter de tout ça ? C'est ici ? 😊

**Comment by vinber** [comment]
ici cela me va, je découvre que je peux commenter ici : https://github.com/frodrigo/osmose-backend/commit/9dfea0a9cc2df11968bbd0859f4ddcd6c5f33c99

mais je ne sais pas si c'est vraiment comme cela qu'il faut utiliser tout cela :)

@frodrigo ton avis  pour les newbee que nous sommes ? l'annotation dansle commit comme ce que j'ai fait est-il oppportun, pas du tout ?

**Comment by frodrigo** [comment]
Ici. Dans le commit il n'y a que moi qui reçoit la notif.

**Comment by vinber** [comment]
ok, mais comment puis sinon faire des modifs sur ce fichier : https://github.com/frodrigo/osmose-backend/blob/9dfea0a9cc2df11968bbd0859f4ddcd6c5f33c99/merge_data/healthcare_FR_finess.mapping.json

ou en avoir une version que nous pourrions commenter comme ce que j'ai fait sur ton commit ? Si c'est possible ?

**Comment by frodrigo** [comment]
https://github.com/frodrigo/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json
Depuis là tu utilise le crayon pour proposer une modif, ça va crééer un pull request (proposition de changement), et c'est possible de discuter dessus.

**Comment by vinber** [comment]
mais par exemple ce fichier https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.csv
ne correspond pas au fichier https://github.com/frodrigo/osmose-backend/blob/9dfea0a9cc2df11968bbd0859f4ddcd6c5f33c99/merge_data/healthcare_FR_finess.mapping.json

et c'est plutôt le json que j'aimerai commenter car plus avancé mais lui je ne peux pas le faire car "you must be on a branch to make or propose changes to this file" ?

**Comment by vinber** [comment]
ou alors je reprends le json, je remplace dans le master et là je commence à me perdre entre les diverses branches, trucs, :) :)

**Comment by frodrigo** [comment]
Le bon lien :
https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.csv

Attention, on ne peut pas mettre de commentaires dans json lui même. Juste des modif, Mais on peut discuter sur le Pull Request (PR).

**Comment by vinber** [comment]
ok, j'ai tenté cela : https://github.com/osm-fr/osmose-backend/compare/master...vinber:patch-2
 que l'on peut vraisemblablement commenter

**Comment by frodrigo** [comment]
Vas jusqu'a créeer le PR.

**Comment by vinber** [comment]
ok, je crois que je l'ai fait, désolé si je fais n'importe quoi, je suis un peu perdu entre le fichier csv et le json qui était plus à jour !
mais on va y arriver :) Merci @frodrigo

**Comment by zorglubu** [comment]
@vinber Je vais détailler le [wiki](https://wiki.openstreetmap.org/wiki/FR:Tag:amenity=hospital#Pour_la_France) : à affiner avec vos remarques si possible ;-)
Et effectivement, l'agrégat 1111, bien que faisant partie des "Etablissements Hospitaliers" pose question quant à son statut "hospital". On devrait pour l'instant le supprimer de la liste que j'ai faite et des tests Osmose.
Par contre pour le 1110, ça devient difficile car certains s'appellent "hôpital". Mais d'autres sont clairement des "cliniques" pour un francophone. La limite est floue sur la taille. Peut-être faudrait-il tolérer les deux amenity=hospital|clinic pour ceux-là ?
exemples : 
hôpital : http://finess.sante.gouv.fr/fininter/jsp/actionDetailEtablissement.do?noFiness=940300551
clinique : http://finess.sante.gouv.fr/fininter/jsp/actionDetailEtablissement.do?noFiness=410004998

**Comment by vinber** [comment]
ok, j'ai donc :
 - mis le 1110 en clinic mais cela n'est pas évident effectivement
- mis le 1111 avec healtcare=yes 

la distinction hospital/clinic est complexe effectivement.

Si j'ai bien compris, nous pouvons commenter ici : https://github.com/osm-fr/osmose-backend/pull/668/files

**Comment by deuzeffe** [comment]
@vinber clinique/hôpitaux : tu as raison 2 fois ;) Une clinique sans pub lucratif des dirigeants est dite "hôpital privé" 
(le patch m'a effectivement viré des faux positifs, mais j'en ai encore 2 qui me sont incompréhensibles et mon FF fait la grève sur le répertoire FINESS en ligne :/)

**Comment by frodrigo** [comment]
@deuzeffe aucun patch n'a encore été appliqué: patch en cours d'écriture https://github.com/osm-fr/osmose-backend/pull/668

**Comment by zorglubu** [comment]
OK avec les commentaires précédents sur catégories 1110 et 1111.
Je viens de passer un bon moment sur les structures SLD (1109), il me semble que ce sont en grande majorité des sous-structures à l'intérieur d'un établissement. Il ne faudra pas tenter de les ajouter à OSM, c'est peu intéressant.

**Comment by vinber** [comment]
et du coup c'est ici que l'on continue à améliorer par exemple les maisons de rertaite et les ehpad @zorglubu
4401
le 202 c'est maison de retraite = social_facility=groupe_home
dans l'autre le 500 c'est plutôt assisted_living ou nursing_home ?

**Comment by frodrigo** [comment]
4401 on à déjà ça, non ? https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json#L136-L157

**Comment by vinber** [comment]
Mais je suis définitivement perdu :( si je regarde ceci https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json
ce n'est pas le dernier mapping que nous avons discuté.

**Comment by vinber** [comment]
> 4401 on à déjà ça, non ? https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json#L136-L157

oui on va rester sur ce fichier et les divers items.
Je pense que l'on peut cependant distinguer les ephad (nursing_home ou assisted-living) et les maisons de retraites (hroup_home)
@zorglubu je n'ai pas repris tes commentaires sur la pull request, on continue ici la discussion :D

**Comment by frodrigo** [comment]
@vinber oui, j'ai dû corriger le problème de conflit à la main. C'est donc sur mon fork et pas encore intégré ici https://github.com/frodrigo/osmose-backend/commit/436badda6458decd8b335bd761e2d8d927a8ee7e . Ça n’empêche pas de corriger d'autres choses et de faire de nouveaux PR en //. Git c'est fait pour.

**Comment by vinber** [comment]
que Git soit fait pour j'en suis sur, que mon cerveau soit fait pour git, c'est moins sur :dancer:

**Comment by zorglubu** [comment]
Je viens de comprendre que les "items" dans le json correspondent à des rubriques dans le menu de gauche d'Osmose :-)
@frodrigo  serait-il difficile de séparer les "structures de santé" (catégories 11xx) des "Autres Etablissements de Soins et Prévention", bref de ne pas les mettre dans le même item 8330 ou 7220 ?
Parce que les premiers (par leur taille) seraient pour moi prioritaires à corriger, et actuellement ils sont un peu noyés dans le nombre. Merci pour ta réponse.

Le deuxième truc, c'est qu'il y a un item 8331 "hôpital, proposition d'intégration" dans Osmose qui n'est pas dans le JSON. Il vient d'une autre source ?

**Comment by frodrigo** [comment]
Il y a un "8xx1" pour tous, c'est automatique : https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_healthcare_FR_finess.py#L68
On peut découper en plusieurs items si vous vouluez. Proposez une modif du fichier de configuration json.

**Comment by zorglubu** [comment]
Il faudrait un numéro d'item pour dédoubler le 8330. Il faut juste le mettre dans le json ? Comment savoir quel numéro est libre ?

**Comment by frodrigo** [comment]
7250, 8400

**Comment by zorglubu** [comment]
Pour répondre à @vinber , si on veut distinguer les ephad (nursing_home ou assisted-living) et les maisons de retraites (hroup_home), ce qui peut être une bonne idée, il faudrait dans le code tester les categetab et pas uniquement les categagretab.
Je ne peux pas m'amuser proposer quelque chose, je ne connais pas python  :-(

**Comment by vinber** [comment]
ou alors faire 2 propositions de tag, en demandant aux humains de choisir en fonction du texte descriptif, exemple de 2 textes que l'on peut trouver :
![Capture d’écran de 2019-10-22 15-25-04](https://user-images.githubusercontent.com/890869/67290312-39bc3c80-f4e0-11e9-81d6-89c8a46e5ee2.png)
![Capture d’écran de 2019-10-22 15-24-48](https://user-images.githubusercontent.com/890869/67290314-39bc3c80-f4e0-11e9-9f50-cc530a303a42.png)

**Comment by frodrigo** [comment]
Les choix multiples pour l'opendata ne sont pas implémentés.

**Comment by vinber** [comment]
ok, je pensais que c'était cela     "tags_generate2": {} mais à réfléchir donc :)

**Comment by frodrigo** [comment]
tags_generate2 sont des tags secondaires qui ne demandent pas à mettre l'objet à jour même s'il sont différents.

**Comment by gendy54** [comment]
J'arrive un peu comme un cheveu sur la soupe dans cette discussion.
J'avais justement précisé sur le wiki les différences sur les structures pour personnes âgées.

- EHPAD, maison de retraite: group_home (type:FR:FINESS=500)
- Résidence service, senior, résidence autonomie: assisted_living (type:FR:FINESS=202)

**Comment by gendy54** [comment]
Pour ce qui est des hôpitaux, les établissements de santé sont regroupés sous 3 statuts:

- public: hôpitaux publics, AP-HP, AP-HM, HCL,...
- privé non-lucratif: gérés par des associations, fondations. Issus soit des congrégations religieuses, soit de philanthropes du XXe siècle
- privé lucratif: groupes privés: Ramsay Générale de Santé, Elsan, Médipôle-Partenaires, Vivalto Santé et Capio,...

**Comment by gendy54** [comment]
Pour tout ce qui concerne les personnes handicapées, adultes et enfants, je serais très mesuré à une intégration via Osmose, dans la mesure où il est très fréquent, que plusieurs structures (avec un Finess différent (ref et type)) soient dans le même bâtiment ou la même zone. Il est donc très difficile de les cartographier, même si on est sur le terrain, sauf à multiplier les POI sur un même bâtiment ou zone. C'est la même problématique que les groupes scolaires allant de la maternelle au lycée, mais en pire ):
Quand je cartographie des structures comme ca, je mets souvent ni la ref:FR:FINESS ni le type::FR:FINESS, et je rajoute le tag de la structure la plus grosse

**Comment by gendy54** [comment]
Ah je n'ai pas parlé des cliniques. Selon mon opinion et comme le dit le wiki (c'est pas moi qui l'ai écrit), il ne devrait pas y avoir de "clinic" en France.
Les cliniques font le même travail que les hôpitaux, c'est juste qu'elles sont privées. Elles sont juste en général plus petites et sont en général très spécialisées (psy, chir ortho, cancer,...).
En fait, il devrait y avoir en France 3 niveaux:

- amenity=hôpital (à basculer en healthcare=hôpital): soins lourds, hospitalisation, hôpital de jour
- healthcare=centre: maison médicale, cabinet de groupe, centre de consultations (PMI, travail,...)
- amenity=doctor (à basculer en  healthcare=doctor): médecin seul ou à 2

**Comment by vinber** [comment]
On ferme cette issue et on en ouvre d'autres si besoin ?
