### ISSUE TITLE
historic:railway=station (or station_site) appears as an error 2110 -Name present but missing main tag

### ISSUE THREAD

**Issue by EwenH** [osm-fr/osmose-backend#667]
Hi,
  Osmose is reporting an error 2110/21101 error for an historic railway station returning "Name present but missing main tag"...
http://osmose.openstreetmap.fr/en/error/34163773364 for node https://www.openstreetmap.org/node/6679525691
http://osmose.openstreetmap.fr/en/map/#item=2110&zoom=17&lat=-17.650837&lon=141.06802&level=1%2C2%2C3&tags=&fixable=

historic:railway | station |  
-- | -- | --
name | Margaret and Jane landing |
note | position approx |  
train | yes

There are a large number of these entries and I thought historic* was ok to use. What do I need to add/fix or is this a false positive please?

**Comment by frodrigo** [comment]
Ok for support `historic:*` name space.
