### ISSUE TITLE
False positive: Public transport relation route not in route_master relation

### ISSUE THREAD

**Issue by camelCaseSucks** [osm-fr/osmose-backend#669]
https://osmose.openstreetmap.fr/en/map/#item=1260&zoom=11&lat=45.4121&lon=-122.6566&level=1%2C2&tags=&fixable=

Most of these issues are false positives - 10 light rail routes, 4 tram routes, & 2 train routes are already in route_master relations.

**Comment by frodrigo** [comment]
https://osmose.openstreetmap.fr/en/errors/?item=1260&class=4
