### ISSUE TITLE
Mapillary False positive keeps reappearing

### ISSUE THREAD

**Issue by camelCaseSucks** [osm-fr/osmose-backend#670]
https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.517626&lon=-122.691652&item=8360&level=1%2C2&tags=&fixable=

I have marked this issue as a false positive about 5 times (it is detecting the traffic signals a block down the street, which are already mapped) but the issue keeps reappearing.

**Comment by frodrigo** [comment]
There is a bug with all Mapillary false-positive. We are working on.

**Comment by frodrigo** [comment]
Linked to #560

**Comment by frodrigo** [comment]
It should be OK. Please can you check on your side.

Note the check Merge_Street_Objects and Merge_Traffic_Signs are not always update on some area : http://osmose.openstreetmap.fr/fr/control/update_matrix
