### ISSUE TITLE
Close similar names are the same

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#678]
item=5080
class=1

http://osmose.openstreetmap.fr/fr/byuser/trial?username=trial&item=5080

the names are more than similar, they are the same.
Should I just close as false positive? 
Can it be a reason for that?

N.B.: equality checked with CTRL+C/CTRL-F/CTRL+V using FireFox.

**Comment by frodrigo** [comment]
```
 590840039 Rond-Point de Keryado (dash)
  23152229 Rond Point de	Keryado (no dash, and tab)
```
The names on OSM are not the same. But the Osmose message look wrong. But I does not see why.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_name_close.py

**Comment by Bibi56** [comment]
It was the tab, not the dash (I was adding the dash due to another Osmose message).
Maybe it's the popup that convert the tab into space?

**Comment by frodrigo** [comment]
Ok. probably the web brother.
