### ISSUE TITLE
traffic_calming=island + area=yes gives confusing report

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#679]
It complaints about area without kind.

Maybe this tagging is wrong but error message makes no sense.

Spotted for https://www.openstreetmap.org/way/309639281/history#map=19/50.02905/19.93684

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.028752&lon=19.937216&item=xxxx&level=1%2C2%2C3&tags=&fixable=


key | value
-- | --
source | 8420
item | 3200
class | 32002
subclass | 1
elems | way309639281
lat lon | 50.0290587 19.9367915



key | value
-- | --
elem_index | 0
type id | W 309639281
tags | traffic_calming=island area=yes
username | Władysław Komorek

**Comment by matthewdarwin** [comment]
Why not remove area=yes?

https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland

**Comment by matkoniecz** [comment]
In such case "not needed area=yes" error should be raised.

**Comment by frodrigo** [comment]
It comes from here: https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Area.py#L30
Feel free to make a Pull Request to improve it.

**Comment by matkoniecz** [comment]
I am a bit confused by this code, especially by `area_yes_good` with listed `amenity`.

What kind of `amenity` tags can have valid `area=yes`?

**Comment by frodrigo** [comment]
To be checked. Maybe other parts need to be improved.
