### ISSUE TITLE
New analyzer: very small polygons.

### ISSUE THREAD

**Issue by StyXman** [osm-fr/osmose-backend#684]
The OSM database is full of very small polygons; case in point:

https://www.openstreetmap.org/way/392478178

I counted more than 800k instances in a many months old Europe import. Many of them seem to be part of the cadastre import in France. It seems that a good threshold could be 5 or 10 `way_areas` (as calculated in an OSM import), but maybe there's a way to calculate their real size.

**Comment by grischard** [comment]
A few other examples from chatting with @StyXman on irc:

https://www.openstreetmap.org/way/159270921
https://www.openstreetmap.org/way/590796476
https://www.openstreetmap.org/way/93883538
~5wa: https://www.openstreetmap.org/way/154311611
1wa: https://www.openstreetmap.org/way/168439247
2wa: https://www.openstreetmap.org/way/159362517

Valid small areas:

https://www.openstreetmap.org/#map=19/52.51390/13.37908
https://www.openstreetmap.org/way/288639986

**Comment by frodrigo** [comment]
Osmose deals with geom on local metric projection. Area are in m².

Maybe whitelist some tags?

**Comment by vinber** [comment]
>  ~5wa: https://www.openstreetmap.org/way/154311611

an eaves at the entrance of the building, i know it

> https://www.openstreetmap.org/way/159362517

l think (but i'm not sure) also an eaves at the entrance of the home

**Comment by StyXman** [comment]
Yes, this will need a lot of on premises validation.

**Comment by frodrigo** [comment]
Yes. Please add more rules about what should be or should not be reported.

**Comment by Bibi56** [comment]
I don't see what is wrong here. It's very detailed, yes, not strictly needed for most usage, true.
I see individual tombs. That's correct.
Roof overhangs protecting the entrance. That's correct.

If you don't need such detail, remove it during the import process (no mapping for tombs for instance) or at some later step.

Exceptions:
https://www.openstreetmap.org/way/168439247#map=19/49.42162/1.12305
Correct, the smalls bricks could be merged to the church (not something Osmose propose right now) but removing the m would be an error. And for 3D modeling having that as a separate object makes further work easier.

https://www.openstreetmap.org/way/392478178#map=19/47.55725/9.65839
Right, but it was including a `fixme=shape`, I fixed it using the Bavarian imagery.

**Comment by frodrigo** [comment]
We may check only landuse ?

**Comment by Famlam** [comment]
An analyser for several types of polygons is now live:
http://osmose.openstreetmap.fr/en/issues/open?item=3100

I guess that completes this issue for now? (More types of polygons can of course be added in the future)
