### ISSUE TITLE
Error 5030 - two names

### ISSUE THREAD

**Issue by Lesko987** [osm-fr/osmose-backend#69]
Hi,

With error 5030, there is a problem in bilingual areas. There all street names, street signs, oficial building names,... must be written in both languages. Common practice is to write in name field in both languages separated with / and also in both local languages.

Example:
way 277453150
name	Razbremenilnik / Canale di scolo
name:it	Canale di scolo
name:sl	Razbremenilnik

So my suggestion is, that in case of / you check for both sides if they exists in name:xx tag and in such case don't report this as an error.

Same problem applies to error 5060 

BTW: Can you add default language for Slovenia.

File osmose-backend/osmose_config.py Line 384

default_country("europe", "slovenia", 218657, {"country": "SI", "language": "sl", "proj": 32633}, download_repo=GEOFABRIK)

**Comment by frodrigo** [comment]
We can disable "/" for the country / area, witch one ?

Bu it's no so simple. There is many other multilingual area and the way to do is not always the same, with "-" in Brussels, with nothing in Morocco, with "()" in Asian countries... First time I hear usage of "/". Maybe we can setup you area for multilingual.

About setting a language for Slovenia, "sl" is the only default language for all the country ? Nevertheless, it's will change nothing while there is no Slovenian specific analysis.

**Comment by Lesko987** [comment]
This are bilingual regions in the area and all of them are mostly using 
name=Local name / Minority name
name:xx=Local name
name:yy=Minority name

Italiy - Slovenian minority (Error no translation)
http://osmose.openstreetmap.fr/en/map/#layer=Mapnik&zoom=11&lat=45.7871&lon=13.8098&item=5060&level=1%252C2%252C3&tags=&fixable=

Austria - Slovenian minority (Error no translation)
http://osmose.openstreetmap.fr/en/map/#layer=Mapnik&zoom=11&lat=46.5352&lon=14.4374&item=5060&level=1%252C2%252C3&tags=&fixable=

Slovenia - Italian minority (Error two names)
http://osmose.openstreetmap.fr/en/map/#layer=Mapnik&zoom=12&lat=45.5222&lon=13.6755&item=5030&level=&tags=&fixable=

Same notation is also used in Sardegnia,  New zeeland and for border features, http://wiki.openstreetmap.org/wiki/Multilingual_names#Shared_boundary_features

I will raise the question of bilingual names in slovenian forum, and let you know what the community decided.



> About setting a language for Slovenia, "sl" is the only default language for all the country ? 
Yes. "sl" is official language in whole country. We have also Italian and Hungarian minorities and there are official bilingual areas and all street signs are in both languages.

> Nevertheless, it's will change nothing while there is no Slovenian specific analysis.
I thought local language analyses depends on this. In file osmose-backend/osmose_config.py language field is set for most countries, but not for Slovenia.

**Comment by frodrigo** [comment]
The multilingual areas are delimited and the border are in OSM ?
We have no generic analysis for monolingual areas. But we have some for bilingual.

Look at https://github.com/osm-fr/osmose-backend/tree/master/plugins for file ends with _xx are country (upper case) or language (lower case) specific.

There is also this for bilingual areas :
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_Multilingual.py

**Comment by frodrigo** [comment]
ping

**Comment by Lesko987** [comment]
There are no specific borders in OSM and also areas are not exactly defined. 

There is no response from our community, so you can leave it as it is for now.

**Comment by stefanb** [comment]
@Lesko987 for some reason https://forum.openstreetmap.org/viewtopic.php?id=40271 didn't get my attention, but i noticed the same discrepancy now that we're preparing the country-wide address import.

Should we reopen this to address it properly?

My generic solution would be for osmose to allow such bilingual `name` tags IF they are both also written individually in the separate `name:xx` and `name:yy` tags.
