### ISSUE TITLE
Allow addr:postcode instead of postal_code

### ISSUE THREAD

**Issue by danfos** [osm-fr/osmose-backend#690]
Saw a admin_level 8 without tag "postal_code" message popping up for the objects I last edited so had a look what was wrong.

For an example, see:

http://osmose.openstreetmap.fr/en/error/34959149337

Or click some of the problems you can see on http://osmose.openstreetmap.fr/en/map/#item=7160&zoom=11&lat=47&lon=4&level=3

The problem seems to me that an [postal_code=*](https://wiki.openstreetmap.org/wiki/Key:postal_code) is missing, but there is an addr:postcode

Looking in the source I see that analysers/analyser_merge_postal_code_FR.py is only testing for postal_code while I see most relation using addr:postcode.

Changing the source to check for addr:postcode is simple but the code should be changed I think so that either addr:postcode or postal_code is fine

**Comment by frodrigo** [comment]
On area, the wiki is clear the tag is `postal_code`. On addresse it is `addr:postcode`.

**Comment by danfos** [comment]
Did download 5733 boundaries with admin_level=8 from the middle of France using Overpass:

```
[out:xml][timeout:90][bbox:{{bbox}}];
(
  relation["admin_level"="8"];
);
out meta;
```

And I see "addr:postcode" set 844 times and "postal_code" being set only 131 times.

So only about 17% of the boundaries have "addr:postcode" _or_ "postal_code" set, but "addr:postcode" is used at least 6 times more than "postal_code"

So most mapper at least in France use "addr:postcode".

[Key:postal_code](https://wiki.openstreetmap.org/wiki/Key:postal_code) is not really clear on it:

> For **boundaries** of a postcode area...
>
> This **postal_code**=* is still valid and widely used, but you can also use... 

That text was added Jan 2014 (and not updated) and it looks like since then the [Karlsruhe Schema](https://wiki.openstreetmap.org/wiki/Proposed_features/House_numbers/Karlsruhe_Schema) more and more became the default .

**Comment by danfos** [comment]
Also world-wide the numbers are clear, have a look at https://taginfo.openstreetmap.org/tags/admin_level=8#combinations and filter on "post"

**Comment by frodrigo** [comment]
The worldwide result give this because of France: https://taginfo.openstreetmap.fr/tags/admin_level=8#combinations
Having postcode on admin_level 8 should not be generalized worldwide.

**Comment by danfos** [comment]
Yes, agreed the world-wide results are largely because of France

So from both sources it is clear that France prefers clearly "addr:postcode" over "postal_code"

**Comment by frodrigo** [comment]
So data should be fixed in France.
