### ISSUE TITLE
Ignore river deviation when river is inside a lake

### ISSUE THREAD

**Issue by ghost** [osm-fr/osmose-backend#695]
Due to the nature of lake the rivers flowing through them are only mapped with a few nodes and as such create false positives
Ignoring river deviation quest when inside lakes would fix that

**Comment by ferdinand0101** [comment]
![Unbenannt](https://user-images.githubusercontent.com/24229481/68552629-4108a300-0419-11ea-97cd-6ebf4770d6f4.PNG)
This is an example of a river going through a lake in russia

**Comment by frodrigo** [comment]
analyser_osmosis_way_approximate.py

Lake may be multipolygon

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=1190&class=20
