### ISSUE TITLE
"tunnel on suspicious object" for tunnel=culvert

### ISSUE THREAD

**Issue by danfos** [osm-fr/osmose-backend#696]
I see that Osmose is reporting "tunnel on suspicious object" for tunnel=culvert, for example:

![Screenshot_20191111_150831](https://user-images.githubusercontent.com/8472097/68593207-ca0cf200-048c-11ea-8170-021e6c7615b1.png)

http://osmose.openstreetmap.fr/en/map/#item=9001&class=9001002&zoom=15&lat=51.8384&lon=4.29955&level=3&tags=&fixable=

I think I could fix this myself but I need some guidance on how. 

I see the message is triggered by code in plugins/Josm_combinations.py and that looks like code generated based on mapcss but I do not see which file this was based on.

There is also a comment

        # way[waterway][layer][layer=~/^(-1|-2|-3|-4|-5)$/][!tunnel][culvert!=yes][covered!=yes][pipeline!=yes][location!=underground][eval(waylength())>400]
        # Part of rule not implemented

and that is likely covering this issue.

Any guidance on how to get this fixed?

**Comment by ferdinand0101** [comment]
I believe the problem here is that you're missing the
`waterway=XYZ`
Tag

**Comment by danfos** [comment]
I agree that "tunnel=culvert" is most used in combination with waterway=*, water is here mapped as an area with natural=water. Mapping an area of water is not possible with the waterway tags.

If the surrounding water is mapped as natural=water (as is here the case) It makes sense to me to map the water (if it is reasonable wide) in the culvert also as natural=water

**Comment by frodrigo** [comment]
The source code is from JOSM MapCSS https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss
If any issue report to JOSM

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
To me the warning is correct. Similar to bridge=yes also tunnel=yes is meant as property of a linear feature like highways or railways. If you want to map the outline you may use man_made=bridge or man_made=tunnel (proposed, see https://wiki.openstreetmap.org/wiki/Proposed_features/man_made%3Dtunnel)

**Comment by frodrigo** [comment]
Please, reopen if required.

**Comment by danfos** [comment]
Good suggestion to use "man_made=tunnel" but I think doing so it is still good to indicate the type of tunnel, just the Wiki says tunnel=building_passage/avalanche_protector

That would mean adding "man_made=tunnel" but keeping "tunnel=culvert"

**Comment by Klumbumbus** [comment]
OK, after https://josm.openstreetmap.de/changeset/15595/josmit it no longer warns about tunnel=* on man_made=tunnel however it warns about the special cases tunnel=yes on man_made=tunnel and also bridge=yes on man_made=bridge as these are not useful combinations.

**Comment by Klumbumbus** [comment]
(it seems reopening this issue is not allowed)

**Comment by danfos** [comment]
Thanks for the rapid fix, good to have.

I guess Osmose merges these changes in JOSM periodically, having this issue open would be a good reminder for that I think.

**Comment by frodrigo** [comment]
Manually update.

I prefer do not track issues on remote fixed code here.

**Comment by danfos** [comment]
Is updating Osmose a matter of getting the latest version of josm/trunk/data/validator/combinations.mapcss through mapcss2osmose.py?

If so, I could make a PR for it.

**Comment by frodrigo** [comment]
Yes. But its undocumented.

**Comment by danfos** [comment]
I did that before for #680, can do it for this.

**Comment by frodrigo** [comment]
I made the update. It is in the pipe line.
