### ISSUE TITLE
«Apply of charte de toponymie de l'IGN»Should botanique be Capitalized?

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osmose-backend#699]
Saluton, hola, bonjour, hi! :)

item=5040
https://osmose.openstreetmap.fr/en/error/35878486151
https://wiki.openstreetmap.org/wiki/Osmose/issues#5040
http://education.ign.fr/sites/all/files/charte_toponymie_ign.pdf

I can't find a reference to "botanique" in the document. Did I miss something?

**Comment by frodrigo** [comment]
There is no specificity for "botanique" §4.9.2.

**Comment by tuxayo** [comment]
Oh I see, thanks for the clarification :)
