### ISSUE TITLE
service=slipway is not a deprecated tag nor is it uncommon

### ISSUE THREAD

**Issue by Identitaet** [osm-fr/osmose-backend#700]
Item: 9002 Class: 9002017

**Comment by frodrigo** [comment]
It from JOSM validator

https://josm.openstreetmap.de/browser/trunk/data/validator/deprecated.mapcss#L1088

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
fixed in JOSM in https://josm.openstreetmap.de/changeset/15548/josm

**Comment by Klumbumbus** [comment]
For such cases when I fix it in JOSM do you need to sync something in Osmose or is it adopted automatically? If automatically I could close these issues in the future too.

**Comment by frodrigo** [comment]
No, update is manually.

**Comment by Klumbumbus** [comment]
Ok, then I'll leave the issue open.

**Comment by Identitaet** [comment]
Thank you

**Comment by frodrigo** [comment]
Updated.
