### ISSUE TITLE
Add tests for motorway_junctions

### ISSUE THREAD

**Issue by Lispach** [osm-fr/osmose-backend#701]
Hello, there.

Accustomed to correcting motorway junctions (`highway=motorway_junction` nodes and connected ways), I would like to suggest some common errors Osmose could warn about:

- using `name=*` on the `highway=motorway_junction` node to indicate the destination of the exit, instead of using `destination=*` on the link exiting from the motorway; here, we have a classical _Tagging for the renderer_;
- using `ref=*` ([edit]: or `name=*`) on the `highway=motorway_junction` to indicate the reference of the road connected to the exit, instead of using `destination:ref=*` on the link exiting from the motorway; again tagging for the rendering;
- using the deprecated `exit_to=*` on the `highway=motorway_junction` node to indicate the destination of the exit, instead of using `destination=*` on the link exiting from the motorway.

As a first guess (French mapper), I would say that:
- for `name=*`, it is not supposed to be used on `highway=motorway_junction` nodes, as named junctions are unlikely; they do exist ([here](https://www.mapillary.com/map/im/80MYtnjU2wJbV6VoF5p1yQ), the exit is named _Batilly_) but one could simply discard the Osmose warning if needed;
- for `ref=*`, a junction ref is supposed to start with a number (1, 5b…), so any value starting with something else, especially a letter (D 453, A 5) should be treated as an error;
- for `exit_to=*`, always warn as deprecated.

Feel free to ask additional data if needed, I would be happy to help implementing this!

Regards.

**Comment by frodrigo** [comment]
I think you can write MapCSS check for all this rules. It is supported in JOSM and Osmose.

https://josm.openstreetmap.de/wiki/Help/Validator/MapCSSTagChecker

**Comment by Lispach** [comment]
I just tested these rules under JOSM and they seem OK:
```css
node[highway=motorway_junction][name] {
    throwWarning: "Unusually named motorway_junction; use of 'name=*' for the exit destination?";
    fixRemove: "name";
    suggestAlternative: "'destination=*' tag on the exiting 'highway=*_link'";
    assertMatch: "node highway=motorway_junction name=Trifouilly-lès-Oies";
}

node[highway=motorway_junction][ref=~/^\D/] {
    throwWarning: "Unusual ref for motorway_junction; use of 'ref=*' for the exit destination ref?";
    fixRemove: "ref";
    suggestAlternative: "'destination:ref=*' tag on the exiting 'highway=*_link'";
    assertMatch: "node highway=motorway_junction ref=N7";
}

node[highway=motorway_junction][exit_to] {
    throwWarning: "Deprecated 'exit_to=*' for motorway_junction";
    fixRemove: "exit_to";
    suggestAlternative: "'destination=*' tag on the exiting 'highway=*_link'";
    assertMatch: "node highway=motorway_junction exit_to=Trifouilly-lès-Oies";
}
```

Does this look OK to you too?

**Comment by frodrigo** [comment]
Suggest to move the value to the new tag, not just delete it with `fixAdd`?

@Klumbumbus interested to have this in JOSM MapCSS?

**Comment by Klumbumbus** [comment]
> @Klumbumbus interested to have this in JOSM MapCSS?

yes, however:

rule1: At least in germany motorway junctions do have names. And it seems in other countries too as 56000 motorway junctions (=32%) worldwide have names. And the wiki says the same. So I don't agree with this rule. Specific rules for specific countries can be added to https://josm.openstreetmap.de/wiki/Rules.

rule2: does this apply worldwide?

rule3: OK, but without the fixRemove as the tag should be transfered to another object.

**Comment by Klumbumbus** [comment]
Rule 3 added to JOSM in https://josm.openstreetmap.de/changeset/15966/josm

Rule 2: https://overpass-turbo.eu/s/Rby Only 81 Nodes worldwide and 50 of those on one motorway in France, so not really a big problem worldwide. I don't think it is worth a rule.

**Comment by frodrigo** [comment]
Thank you.
