### ISSUE TITLE
Clarify which attribute is refered in message "Typo in tag"

### ISSUE THREAD

**Issue by bmillemathias-1a** [osm-fr/osmose-backend#703]
example http://osmose.openstreetmap.fr/fr/error/8d1ccbb3-b53d-74e7-b734-f74f010fb697
Which tag is scoped by the error ?

source | 14287
-- | --
item | 3150
class | 1
subclass | 4609547083374440105
elems | node5420738256
lat lon | 52.9532799 -1.1757155

**Comment by frodrigo** [comment]
A proposed fix should be present, but is missing.

**Comment by frodrigo** [comment]
The fix proposed is to rename one tag by an other already present. By safety the fix is pruned.

So, make a better message in all case.

**Comment by bmillemathias-1a** [comment]
thanks !
