### ISSUE TITLE
Problems with Condado de Treviño

### ISSUE THREAD

**Issue by JorgeSanzS** [osm-fr/osmose-backend#704]
In Treviño County we have quite a few false positives in all the errors that have to do with road junctions. It is an area that is separated from the rest of Castile and León and therefore when analyzed everything comes out as disconnected although it is not real.

Example of incorrect error:
http://osmose.openstreetmap.fr/es/error/09ac25d5-b39e-99ae-2825-c54770e94c00

The area in question:
https://www.openstreetmap.org/relation/342195

Osmose area analyzed:
https://www.openstreetmap.org/relation/349041#map=8/41.680/-4.426

**Comment by frodrigo** [comment]
Relations are well configured in Osmose.

Extract need to be checked: http://download.openstreetmap.fr/extracts/europe/spain/

**Comment by frodrigo** [comment]
The PBF extract is broken.

cc @jocelynj 

![image](https://user-images.githubusercontent.com/1785486/70356363-82ec0400-1874-11ea-84a4-2c3ca2c635f7.png)

**Comment by jocelynj** [comment]
There was an issue with diff generation, where portion of a country that was in an outer, and placed after an inner in the .poly file, was ignored on position check.

It is fixed by https://github.com/jocelynj/osm/commit/23a0f152cc235ab0799352dbf83cf70f1c39dc92

I will regenerate the extracts tomorrow.

**Comment by jocelynj** [comment]
I've regenerated all European extracts, and will regenerate other extracts too.
I will check if the new extract is correct, then will make sure that osmose backends are using the latest extract.

**Comment by frodrigo** [comment]
@JorgeSanzS can you check ? For me it is ok now on Condado de Treviño

**Comment by JorgeSanzS** [comment]
If it seems correct. Thank you

**Comment by frodrigo** [comment]
@jocelynj have you updated all impacted extracts ?

**Comment by frodrigo** [comment]
Ok. Done.
