### ISSUE TITLE
route access mismatch includes other places like churches

### ISSUE THREAD

**Issue by ferdinand0101** [osm-fr/osmose-backend#705]
Class 3240 route access mismatch Item 1
one example for it would be the [church route in Essen](https://www.openstreetmap.org/relation/934536#map=16/51.3890/7.0049) which includes chures in the relation.
Now it colplains that those chures aren't accesable for bikes
I'd suggest that those checks should only be done for things tagged highway

**Comment by frodrigo** [comment]
But church are ways. We should find a better criteria.

Can you look at the wiki please.

**Comment by ferdinand0101** [comment]
Okay so after looking it seems like the building=* tag seems to be a good criteria

**Comment by ferdinand0101** [comment]
also amenity

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=3240
