### ISSUE TITLE
Item 8031 - Added operator:type tag in the integration proposal

### ISSUE THREAD

**Issue by thibdrev** [osm-fr/osmose-backend#71]
Is it possible to include in the tags proposed by the tag operator:type ?

Information must be taken from the name of the institution:
* Contains "public" -> operator:type=public
* Contains "privé", "privée", "saint", "sainte" -> operator:ype=private

**Comment by frodrigo** [comment]
operator:type was already detected.
Now, new file version contain a column for this.

**Comment by thibdrev** [comment]
The current file from the Education Nationale (https://www.data.gouv.fr/s/resources/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres/community/20150116-105239/depp-etablissements-premier-et-second-degres-structures-administratives-education-avril-2014.txt) includes a column called "secteur_public_prive" which contains "PU" for public and "PR" for private.
