### ISSUE TITLE
French Isère telecom exchange fibre points in open-data

### ISSUE THREAD

**Issue by flacombe** [osm-fr/osmose-backend#710]
Hi,

French telecom exchange nodes slowly appear in opendata records.
Isere county had actually published a dataset with more than 100 nodes that could be analyzed by Osmose

https://opendata.isere.fr/explore/dataset/nro/table/

Tagging is simple and the same for all records :
telecom=exchange
telecom:medium=fibre
operator=SFR
ref=$NOM

Is it possible to add them to opendata analysis please?

**Comment by frodrigo** [comment]
It is possible. But 100 node is not so much.

Please make a pull request.

**Comment by flacombe** [comment]
I think I'll integrate them manually for Isère county, and wait that a standard raise for all that exchange points possibly next year

You can close this issue
