### ISSUE TITLE
Invalid addr:housenumber value, false positives in The Netherlands

### ISSUE THREAD

**Issue by AdVerburg** [osm-fr/osmose-backend#711]
item | 2060, class | 10
Recently I noticed a great number of this issues on the map.
As an example: http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=51.402247&lon=3.538166&item=2060&level=1%2C2%2C3&tags=&fixable=
In The Netherlands the street-names, house-numbers and postcode are established by the municipality.
These house-numbers are not just **numbers**, but *can* include hyphen and characters (both upper- and/or lowercase).
Examples of **valid** identifiers are "44-bis", "1-TRAF", "19p-8", "44d-G", "48A", "49a", "3-0072", "450-482".

Many (but not all) of these 'odd' numbers are given to a block of garages, chalets, apartments, service-buildings etc. and there are nearby more addresses according that pattern.

**Comment by frodrigo** [comment]
Please look at https://github.com/osm-fr/osmose-backend/pull/709

**Comment by frodrigo** [comment]
Can we improve or we need to remove the check?

**Comment by AdVerburg** [comment]
The question what to do: improve or remove is on Dutch forum now:
https://forum.openstreetmap.org/viewtopic.php?id=68257

**Comment by jdhoek** [comment]
I think @danfos overlooked quite a few valid possibilities. The BAG supplies the bulk of the addresses in the Netherlands, but not all of them. Osmose probably shouldn't ban house numbers that are perfectly valid, just not used in the BAG.

[Wikipedia](https://nl.wikipedia.org/wiki/Huisnummer) lists a few examples, some of which (Pekela?) we may even consider fixing in OpenStreetMap at some point:

* Starts with a letter (Pekela)
* `19601U` (Graan voor Visch, Hoofddorp)
* `t/o 56` (woonboot)

Further examples from OSM:

* `73-412` (dashes!)
* `10t-13`

I have added a few test cases to a PR and fixed the regex, tentatively. Please have a look.

@AdVerburg Any test cases to add?

**Comment by danfos** [comment]
Thanks @jdhoek for taking this up, like written in #709 I did not time for me to look at it earlier.

The Wikipedia link is nice, did not know that, but what I am wondering is if it is also covered by some formal BAG specification.

Good to make the checking right now less strict.

**Comment by jdhoek** [comment]
You're welcome.

The BAG is just one of possible sources of addresses. For us in the Netherlands it contributes perhaps 99,9%, but it is not exhaustive. Some addresses simply don't exist in the BAG, even though they are valid addresses.

OSM isn't a copy of the BAG, so in my opinion what constitutes a valid `addr:housenumber` is anything that is valid in the Netherlands. The Wikipedia-link does list a few nice exceptions, and I think the Dutch community can help flesh out any remaining edge cases.

**Comment by danfos** [comment]
Reading [Afwijkende adresseringen](https://nl.wikipedia.org/wiki/Huisnummer#Afwijkende_adresseringen) I wonder if it is not better to revert the change completely. 

My assumption that house numbers were covered by the BAG specification was not correct.

As @frodrigo indicated, would have been better to first ping the Dutch forum.

**Comment by danfos** [comment]
Thanks once more @jdhoek for taking this up and good that it is now merged.

Let's see how much problems remain when this code is in place.

**Comment by frodrigo** [comment]
Update is in progress
http://osmose.openstreetmap.fr/en/errors/?country=netherlands_*&item=2060&class=10

**Comment by jdhoek** [comment]
@frodrigo Nice. It looks good for the provinces that have been updated. I'll monitor the updates and see if there are any false positives remaining.

**Comment by jdhoek** [comment]
I'm preparing a fix for the remaining issues in #720.

**Comment by jdhoek** [comment]
It looks like most of the remaining warnings are those that have multiple housenumbers enumerated on one node. As the Dutch convention is to use a separate node for each distinct address, this is fine.

Other interesting warnings include this curious example of tag-misuse:

https://osmose.openstreetmap.fr/en/map/#source=4682&item=2060&class=10&zoom=18&lat=51.814125&lon=4.661059&level=3&tags=&fixable=

Again, this is what the check should warn us about, so all good there.
