### ISSUE TITLE
False Positive? Entrance marked Highway intersecting building

### ISSUE THREAD

**Issue by hungerburg** [osm-fr/osmose-backend#715]
As far as I can tell, there is only one point where these ways overlap, and that is tagged entrance

http://osmose.openstreetmap.fr/en/error/79493e25-d2ad-2254-a249-2829891fcc2e

**Comment by frodrigo** [comment]
The check is made with `ST_Crosses` https://postgis.net/docs/ST_Crosses.html

It does not manage this case.

**Comment by hungerburg** [comment]
Hello @frodrigo - I can't read the symbols at the page, do they say, the test cannot reliably handle concave shapes?

**Comment by frodrigo** [comment]
No, the interior is all part except the boundary. The for linestring the boundaries are only the start and the end. Here it fails because the intersection is in the middle of the linestring.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=1070&class=1

**Comment by hungerburg** [comment]
At the moment, the error does not show up in the map.
