### ISSUE TITLE
Funicular railway=station without name

### ISSUE THREAD

**Issue by fansanelli** [osm-fr/osmose-backend#716]
Hello,

I experienced this error:

2776 | 3 | 9015openrailwaymap | 9015044 | 1983319850 | E | 7.55 44.39 | n 3023921374    (j) | railway=station without name
-- | -- | -- | -- | -- | -- | -- | -- | --

With a funicular station:
https://wiki.openstreetmap.org/wiki/Tag:station=funicular

Does the train station rule still apply?
Many thanks,
Best regards
Francesco

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr//error/786230ef-be4e-42a2-c5b0-23d45020a008

If come from OpenRailMap rules
```css
         node[railway=station][!name]                                                                                
         node[railway=halt][!name]                                                                                   
         node[railway=junction][!name]                                                                               
         node[railway=spur_junction][!name]                                                                          
         node[railway=service_station][!name]                                                                        
         node[railway=site][!name]                                                                                   
         node[railway=tram_stop][!name]                                                                              
         node[railway=yard][!name]                                                                                   
         node[railway=crossover][!name]   
```

https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/validator/openrailwaymap.validator.mapcss#L709-L738

Please report to the OpenRailwayMap project.

**Comment by fansanelli** [comment]
> http://osmose.openstreetmap.fr//error/786230ef-be4e-42a2-c5b0-23d45020a008
> 
> If come from OpenRailMap rules
> 
> ```css
>          node[railway=station][!name]                                                                                
>          node[railway=halt][!name]                                                                                   
>          node[railway=junction][!name]                                                                               
>          node[railway=spur_junction][!name]                                                                          
>          node[railway=service_station][!name]                                                                        
>          node[railway=site][!name]                                                                                   
>          node[railway=tram_stop][!name]                                                                              
>          node[railway=yard][!name]                                                                                   
>          node[railway=crossover][!name]   
> ```
> 
> https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/validator/openrailwaymap.validator.mapcss#L709-L738
> 
> Please report to the OpenRailwayMap project.

Hi @frodrigo 
they suggested to do change their validator:

https://github.com/OpenRailwayMap/OpenRailwayMap/pull/676

I think you can close this issue as soon as it's merged and pulled in Osmose.
Thanks
Francesco

**Comment by frodrigo** [comment]
Let me close it here.

**Comment by fansanelli** [comment]
The fix have been merged.
Cheers
Francesco
