### ISSUE TITLE
Extend French/France alphabet to support oversea territories

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#718]
French Guyana and Polynesia use more local characters reported as issues.

**Comment by adrienandrem** [comment]
Some related info:
* [Langues de Guyane](https://wiki.openstreetmap.org/wiki/Guyane_fran%C3%A7aise/Contributeurs#.C3.89l.C3.A9ments_sp.C3.A9cifiques)
* [Caractères Teko](https://wiki.openstreetmap.org/wiki/Teko_-_Emerillion)
* BDCarthage stream names

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?country=france_guyane&item=5070&level=1%2C2%2C3
http://osmose.openstreetmap.fr/fr/errors/?country=france_polynesie&item=5070&level=1%2C2%2C3

**Comment by frodrigo** [comment]
Done, and data update. Ask for more of for fix.
