### ISSUE TITLE
French distribution power grid update

### ISSUE THREAD

**Issue by flacombe** [osm-fr/osmose-backend#719]
Hi

Last week, Enedis made an update on its datasets and now provide undeground network data.
It implies that two datasets were modified :
https://data.enedis.fr/explore/dataset/poste-source/information/
https://data.enedis.fr/explore/dataset/poste-electrique/information/

Is it possible to update osmose (item 8280) as well please?

Available for any additional information

**Comment by frodrigo** [comment]
There is no additional information. Only location.

**Comment by flacombe** [comment]
Indeed

But I thought the URL changed
If not, Osmose will be automatically updated right?

**Comment by frodrigo** [comment]
* https://data.enedis.fr/explore/dataset/poste-electrique/information/ : URL not changed
* https://data.enedis.fr/explore/dataset/poste-source/information/ : which is the current analayser on Osmose ?

**Comment by frodrigo** [comment]
Reopen if required.
