### ISSUE TITLE
Item 8031 - Update French Education Nationale files

### ISSUE THREAD

**Issue by thibdrev** [osm-fr/osmose-backend#72]
New schools to integrate geocoding is it possible? (with BANO / ADDOK)

This will allow both to school integration and validates the address.

**Comment by frodrigo** [comment]
Schools are geocoded in opendata file. Nevertheless you can try to regeocode with ban/addok or bano/addok. Please fell free to try and report if it's really interesting to regeocode.

**Comment by thibdrev** [comment]
The latest Education Nationale files are dated April 2014 and available here : 
https://www.data.gouv.fr/fr/datasets/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres/

2 files are available:
[1] Données de géolocalisation des établissements
    > includes lat/lon but not address
[2] Adresses des établissements d'enseignement des premier et second degrés avril 2014  
    > includes lat/lon and the address (address ; city/village ; postal code }

I've tried to regeocode [2] with addok but got an error. I'll try again later.

**Comment by frodrigo** [comment]
Please can you check and fix this to make the update to 2014 file:
https://framacalc.org/48Q4ELRXhm

**Comment by thibdrev** [comment]
Unforntunately, I wasn't able to modify much. I've opened the file from Education Nationale (https://www.data.gouv.fr/s/resources/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres/community/20150116-105239/depp-etablissements-premier-et-second-degres-structures-administratives-education-avril-2014.txt) in LibreOffice Calc to check the nature_uai codes I didn't know. 

I've filtered on the nature_uai column and found 2 things:
* 290 lines with an undocumented nature_uai=1
* 61 lines with cells shifted to the right (e.g. 0560620V), resulting with other values in the nature_uai column (might worth it to clean these 61 lines)

Regarding the lines where nature_uai=1, the nature_uai code is in fact in the lib_nature column.

Based on this file, I've updated the framacalc file as follow:

nature_uai | school:FR
-------------- | --------------
101, 102, 103 and 111 | maternelle
315 | lycée
336 | nothing

We could also include sections of collèges and lycées, but if this wasn't done in the past there might be a reason.

nature_uai | school:FR
-------------- | --------------
334 | lycée
335 | lycée
390 | collège

For the rest, I'm guessing these were also not taken into account for a reason (only a few, or types too specific):

nature_uai | lib_nature | comment | lines concerned
-------------- | ----------- | ------------- | -------------------
160 | ECOLE DE PLEIN AIR | I don't know | 3
161 | ECOLE AUTONOME DE PERFECTIONNEMENT | - | none
170 | ECOLE SANS EFFECTIFS PERMANENTS | it's a mix | 8
332 | ECOLE PROFESSIONNELLE SPECIALISEE | it's a mix | 3
336 | SECTION ENSEIGNT TECHNO (1ER CYCLE) | - | none
349 | ETABLISSEMENT DE REINSERTION SCOLAIRE | I don't know | 3
370 | ETABLISSEMENT REGIONAL D'ENSEIGNT ADAPTE | I don't know | 81
380 | CTR FORMATION PROF.AGRICOLE (MAIS.RURAL) | - | none
>800 | mix | these are not schools but administrative centres (rectorat, etc.) | -

**Comment by frodrigo** [comment]
I try to setup the new file, but there is many shit in rows. Please, can you deals with that and provide my a fixed files ?

**Comment by thibdrev** [comment]
I did not see at first, but we can reuse the already cleaned file made by "Les Décodeurs (Le Monde)", available here: https://www.data.gouv.fr/s/resources/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres/community/20150420-102433/Noms_des_etablissements_du_premier_et_second_degre.csv

They've fixed the shifted cells, some typos and added a new ID column titled "identifiant". Otherwise, same number of rows and same columns. There are still some addresses sometimes in the lieu_dit_uai column, but if we don't regeocode it doesn't matters.

**Comment by frodrigo** [comment]
This one and #70 are available on Osmose. Please, can you check the result ?

**Comment by thibdrev** [comment]
From what I'm seeing on the Cher (18) departement, it's better than what we had before.
Also the tag amenity=kindergarten is correctly proposed for the écoles maternelles.
Tks!
