### ISSUE TITLE
Clarification of a multi polygon error

### ISSUE THREAD

**Issue by bmillemathias** [osm-fr/osmose-backend#722]
I get this set of errors http://osmose.openstreetmap.fr/fr/byuser/baptistemm?username=baptistemm&item=1170 for https://www.openstreetmap.org/relation/9104912
the message is "building=(yes,office)" so I don't understand what the problem is.

![image](https://user-images.githubusercontent.com/8579/71546059-f922e880-2992-11ea-98ad-4e6af9430980.png)

Could it be clarified ?

thanks

**Comment by frodrigo** [comment]
The buildings have the `building=office`, but the relation have the `building=yes`. Since the relation is a `type=site`, the relation should not have `building` tag.
