### ISSUE TITLE
#Class 9001.003: false positive for parking=yes

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#723]
Hello,

Error #9001.003 "{0.key} on a relation without {1.key}={1.value}" is sometimes a false positive where 0.key=parking and 1.key=amenity (e.g. an shop=bakery with parking=yes).

I don't no if it's easy to resolve...

Thx for your answer whatever it is.

**Comment by frodrigo** [comment]
Do you have a link to an issue?

**Comment by deuzeffe** [comment]
This (whithout amenity= but with building=) https://osmose.openstreetmap.fr/fr/error/98b35627-1390-646e-042e-8b3e8f389d6b
That https://osmose.openstreetmap.fr/fr/error/d17eed76-b0bf-08d6-c890-01f4b28b3467 (with tourism=)
Or this https://osmose.openstreetmap.fr/fr/error/98b1a3a9-3aa5-a407-95a9-a1318005b7f6 (with amenity)

**Comment by frodrigo** [comment]
cc @Klumbumbus

**Comment by Klumbumbus** [comment]
Fix and my comment see https://josm.openstreetmap.de/changeset/15624/josm

**Comment by deuzeffe** [comment]
@Klumbumbus thx for the fix!
(at least I'm lucky sometimes or somewhere ^^)
