### ISSUE TITLE
Question (for my education): analysis lag for France?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#724]
Hello,

- 2019-12-30 This error : https://osmose.openstreetmap.fr/fr/error/5d466ded-49ab-a5e5-0c33-62df7a8b07a7 

source | 409655
-- | --
item | 2060
class | 12

- was resume on 2019-12-26 (4 days ago) and it's still shown.

Extract pb, some backends KO, other ?

Thx for your answer whatever it is.

**Comment by frodrigo** [comment]
The date "2019-12-30 13:34:02" is the date of the extract used.

Yes. The content does not match with the last version of the object.

cc @jocelynj

**Comment by frodrigo** [comment]
Also see https://github.com/osm-fr/osmose-frontend/issues/192

**Comment by jocelynj** [comment]
I'm not sure if I've removed extracts on osm211 and osm212, as I cannot access these at the current time. I will check with Paulla for the access.

**Comment by jocelynj** [comment]
I've cleaned all files on Paulla cluster.

**Comment by frodrigo** [comment]
It has not changed, maybe the source extract is corrupted?

**Comment by frodrigo** [comment]
Still not ok.

**Comment by deuzeffe** [comment]
Still...

**Comment by vinber** [comment]
oups sorry for duplicate

**Comment by frodrigo** [comment]
Maybe the same as https://github.com/osm-fr/osmose-frontend/issues/201
The issue update date may be wrong.

Waiting for the next update.

**Comment by deuzeffe** [comment]
@frodrigo Wrong alert still seems to be there despite your fix.

**Comment by deuzeffe** [comment]
Is the update OK? 'Cause I can still see the false positive. @frodrigo can you check from your side (if you have a little bit of unemployed time - hum)?
