### ISSUE TITLE
False positive: Way with {tag}={value} not closed

### ISSUE THREAD

**Issue by SilentSpike** [osm-fr/osmose-backend#725]
Item: 9003
Class: 9003010
Example: https://osmose.openstreetmap.fr/en/error/e75c3b47-acd1-cf49-66a6-c8a335090f76

If you look at the way in question, it was last edited over 5 years ago and starts/ends with the same node (is closed). Yet this issue is timestamped `2019-12-29 21:59:02`.

**Comment by frodrigo** [comment]
You are right, something wrong with this check.

**Comment by SilentSpike** [comment]
Looks like the issue is just a `==` that should be a `!=` (`nds[0] != nds[-1]`) here 

https://github.com/osm-fr/osmose-backend/blob/893a658b055477b9000861cc8a0ef8a8976c132e/plugins/Josm_geometry.py#L644

**Comment by frodrigo** [comment]
Thank you. Fixed a mapcss compiler bug.

**Comment by SilentSpike** [comment]
Looks like this also closes #578
