### ISSUE TITLE
Item 2060 - Should associatedStreet relations take into account roundabouts?

### ISSUE THREAD

**Issue by thibdrev** [osm-fr/osmose-backend#73]
Osmose rises a class 7 issue when an associatedStreet relation includes different names.

However, in this example (http://osmose.openstreetmap.fr/fr/error/3880380933), the relation "Route de Nevers" encompasses several streets named "Route de Nevers" and 2 roundabouts named "Porte de Nevers".

Maybe the relation should not include the roundabouts or the Osmose test should be modified. I haven't found info on the wiki (http://wiki.openstreetmap.org/wiki/Relation:associatedStreet).

**Comment by frodrigo** [comment]
I see classical roundabouts as junctions. So I think there are no place for there in associatedStreet relations.
