### ISSUE TITLE
item 4090 and aeroway = parking_position 

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#739]
the way is an area and the node ref 
false positive ?

http://osmose.openstreetmap.fr/fr/map/#source=22424&item=4090&class=1&zoom=15&lat=35.76545&lon=140.38943&level=1&tags=&fixable=

**Comment by frodrigo** [comment]
No more issue on Osmose. Which way?

**Comment by didier2020** [comment]
like this http://osmose.openstreetmap.fr/fr/error/77f64294-a280-315a-63ca-a2a410a1e10f

**Comment by frodrigo** [comment]
I do not know if it is a false positive or not.
