### ISSUE TITLE
Error 3030, Class 737787355 "shop" 

### ISSUE THREAD

**Issue by Lesko987** [osm-fr/osmose-backend#74]
Hi, 

shop=fishing is good tag for shop with fishing equipment. http://wiki.openstreetmap.org/wiki/Tag:shop=fishing
and should not be reported as error.

Can I correct (remove) it on http://wiki.openstreetmap.org/wiki/User:FrViPofm/TagwatchCleaner#s_2 or should you make changes there?

**Comment by frodrigo** [comment]
Good spot. I removed it. Wait a few days before the change appear in osmose's issues.
