### ISSUE TITLE
Combined foot- or cyclelways

### ISSUE THREAD

**Issue by MicDK** [osm-fr/osmose-backend#741]
Hello,

Corrections made in OpenStreetMap does not disappear in Osmose (JOSM validator + Combinations + Missing tag).

It seems as if Osmose sticks to what was detected 2020-01-08.  Please see screenshot. The cycleway shown on the map hase been redrawn and marked as segregated. Way no. 679508775.

I'll be very thankful if someone can solve this problem.

![billede](https://user-images.githubusercontent.com/60147959/72823407-f0f95880-3c73-11ea-8bd5-b2c11061ae9c.png)

Yours
Michael (MicDK) from Denmark

**Comment by frodrigo** [comment]
We are expecting some trouble with backend servers as we are migrating some of them.

http://osmose.openstreetmap.fr/en/control/update_summary

http://osmose.openstreetmap.fr/en/control/update_summary

**Comment by MicDK** [comment]
Thank You, Frédéric  :-)
