### ISSUE TITLE
Tag conflict aeroway=airstrip & leisure=sports_centre: false positive or mistagging?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#743]
Hello,

This object https://www.openstreetmap.org/node/3702778707 is flagged as a #4030 error: https://osmose.openstreetmap.fr/fr/map/#item=4030&zoom=18&lat=49.204217&lon=3.733828&level=1&tags=&fixable=

Is a really mistagging flagged or a false positive?
(I RTFW to answer myself. Unlucky I was :/)

Thx for your answer, whatever it is.

**Comment by frodrigo** [comment]
It not a `leisure=sports_centre` for me.
