### ISSUE TITLE
'In France all pharmacies deliver drugs under prescription', Belgium as well

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-backend#744]
I noticed this osmose error also actually applies to Belgium
https://github.com/osm-fr/osmose-backend/blob/e6f637c09a64535181bb43f6d48c282535fa7866/plugins/TagFix_MultipleTag_FR.py#L45-L54

**Comment by frodrigo** [comment]
It is not set for BE, please can you point at one

https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag_FR.py

**Comment by frodrigo** [comment]
You want it also for Belgium?

**Comment by thibaultmol** [comment]
Sorry, bad phrasing on my part.
What I meant to say was that this rule should also be applied to Belgium, as all Belgium pharmacies are forced to sell prescription drugs. (excluding parapharmacies)

**Comment by klenje** [comment]
@frodrigo should we extract the pharmacy part in a dedicated file and add it also BE there? Since the current file covers lots of other tags

**Comment by frodrigo** [comment]
Yes

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=2100&class=30326
Deployed and we have results.
