### ISSUE TITLE
Fuel station to update: bad fix proposal

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#747]
Hello,

For this way https://www.openstreetmap.org/way/298394506 the fix proposal is: 

clé |	valeur
-- | -- 
create | fuel:octane_95 yes	
shop | gas	
delete | fuel:e10

Ok to add shop=gas but replace fuel:e10 by fuel:octane_95 is not ok imho.
(the osmose alert: https://osmose.openstreetmap.fr/fr/map/#item=8202&zoom=17&lat=45.800555&lon=1.118094&level=3&tags=&fixable= )

What's wrong with my understanding? :/

Thx for your answer whatever it is.

**Comment by frodrigo** [comment]
Also see #658

**Comment by deuzeffe** [comment]
@frodrigo I'm afraid I'm unable to know/understand if the both alert are similar, sorry :(
(2 different items, one comes from josmspecific rules, the other from osmose analysis ?)

**Comment by frodrigo** [comment]
cc @Bibi56 @PanierAvide

**Comment by Bibi56** [comment]
Yes, it's a bit strange, fuel:e10=yes sounds correct to me: it's a mix using octane 95: SP95-E10 in France. Just adding it on https://www.openstreetmap.org/node/323161771.

**Comment by Bibi56** [comment]
Indeed, I added fuel:e10=yes on https://www.openstreetmap.org/node/323161771 (which is correct) and got the proposal of Osmose to remove it :-(. @PanierAvide?

**Comment by PanierAvide** [comment]
Something I don't understand is why the ressource associated to this issue is an Italian fuel prices dataset : http://osmose.openstreetmap.fr/fr/error/bac373f8-bd5c-9ec9-bfcf-166b4b50b456

**Comment by frodrigo** [comment]
We now have the same merge for Italy. The class number is wrong (the same) and the documentation is overwrited. To be fixed.

**Comment by PanierAvide** [comment]
And the datasource in France is correct : https://donnees.roulez-eco.fr/opendata/instantane (search `GUIDEL`, station Super U has E10).

But the merge analysis doesn't use the online version, it uses a file named `fuel_FR.csv.bz2` : https://github.com/osm-fr/osmose-backend/blob/ddb9fbab3d975dcd76144eff689a6a0000b8214c/analysers/analyser_merge_fuel_FR.py#L40

@frodrigo where is it extracted from ? Can't we use the latest version online ?

**Comment by frodrigo** [comment]
The online file was probably not usable last time I check. To be rechecked.

**Comment by PanierAvide** [comment]
Otherwise, I already process this file and put it as a daily-updated GeoJSON file here if it's more convenient : https://files.pavie.info/depot/remote/carburants_gouv.geojson

**Comment by frodrigo** [comment]
Please, make a PR if you wish a quick update of Osmose.

**Comment by frodrigo** [comment]
IT class id fixed.
