### ISSUE TITLE
Establishing translation string standards

### ISSUE THREAD

**Issue by SilentSpike** [osm-fr/osmose-backend#749]
Osmose translation strings are now being used in the iD Osmose layer (preview at bottom of this post).

I thought it might be worth starting a discussion on establishing translation/formatting/grammar standards which would benefit the end users of both Osmose and iD (by creating a more consistent UX).

The immediate ones that come to mind for me would be along the lines of:
- All issue classes should have a `title` string which describes the issue
- All issue classes should have a `detail` string which explains the issue
- Title strings should not contain OSM keys/values (looks bad and can now be moved to detail string)
- Subtitle strings should be a valid sentence, for example
```
"\"{0}\" unexpected non printable char ({1}, 0x{2:04x}) in key at position {3}"
```
would become 
```
"A non-printable character, {1}, with Unicode value `0x{2:04x}` was found at position {3} in `{0}`."
```
- Perhaps any OSM element ID (n1, w1, r1) should be given a special markdown - I suggest the form \[\[n1234\]\] as it's similar to internal links on wikimedia sites (this would only be relevant for dynamic subtitle strings if any include elements)
- That any sort of OSM `key`, `key=value`, `value`, `namespace:` should be enclosed in code markdown (that's \`key=value\`) as is already done in a few strings (see preview image).
- Markdown should be used for URLs as already done in a few strings (that's \[text\]\(url\)) - no raw URLs in strings

Here's the iD UI preview:
![image](https://user-images.githubusercontent.com/5459452/73793008-66e5df80-479d-11ea-99d7-618da8584b67.png)

**Comment by SilentSpike** [comment]
Part of the motivation for this would be to document such standards somewhere that iD can direct users (currently links to Transifex) along with general guidelines on how to contribute translations (and how they get deployed). 

Perhaps a wiki page on this repository?

**Comment by frodrigo** [comment]
Yes good point. I have similar goal to add how to write issue doc in the wiki.

cc @deuzeffe

**Comment by frodrigo** [comment]
Markdown is only available for new fields detail, fix, trap and example. Source and Resource are URL field, not free text.

Subtitle are not part of the item/class documentation, and not markdown. It should require to review all subtitle first.

I added some of this advice to the wiki https://wiki.openstreetmap.org/wiki/Osmose

**Comment by frodrigo** [comment]
Fell free to make any PR to improve the wording.
