### ISSUE TITLE
indention behind 3161 parking lane 'missing access to parking'?

### ISSUE THREAD

**Issue by it4workflow** [osm-fr/osmose-backend#75]
Now that I've gotten some warnings about [3161 parking lane](http://wiki.openstreetmap.org/wiki/DE:Osmose/issues#3161) 'missing access to parking' and nothing is documented in the wiki, i want to ask you: what is your indention behind this issue?

Just an example: [273144424](http://www.openstreetmap.org/way/273144424) and related [bing maps](http://binged.it/1GccLu8). How should i tag/map this parking area?

If you prefer parking:lane, where should i tag operator, surface, and so on? There's nothing mentioned about it in wiki for parking:lane.

Another opportunity could be to share the two corner-nodes with the highway, but this isn't best practice.

**Comment by frodrigo** [comment]
> If you prefer parking:lane, where should i tag operator, surface, and so on? There's nothing mentioned about it in wiki for parking:lane.

The idea here is to use parking:lane here, but you are right, there is no sub tag for surface and others.

> Another opportunity could be to share the two corner-nodes with the highway, but this isn't best practice

Here the street touch the parking, not the same case with a park, a building or a landuse. E.g. no side walk separate the street and the parking.

This analysis was primary created to access to large parking (eg park and ride) and extended to all parkings. Maybe was a bad idea.
