### ISSUE TITLE
numeric rule - direction value contains special character (semicolon  ";")

### ISSUE THREAD

**Issue by sun-geo** [osm-fr/osmose-backend#751]
Hi together,

i'm wondering if a node object which has a direction information like `direction=90;270` 
( example osm ojbect: https://www.openstreetmap.org/node/6758704280 )
is wrong like there is a rule
(the item and class number, http://osmose.openstreetmap.fr/en/errors/?item=9006 )
which is saying that _"unusual value of direction"_.

https://osmose.openstreetmap.fr/en/error/2f715950-3b8f-f17c-6008-c3a9d9d3c0dc
https://osmose.openstreetmap.fr/de/map/#item=9006&zoom=17&lat=34.641377&lon=-102.741073&level=1%2C2%2C3&tags=&fixable=

Even the iD-Editor supports these semicolon separated direction values by drawing/rendering cones to the object, see here:
https://www.openstreetmap.org/edit?node=6758704280
![cones](https://user-images.githubusercontent.com/47290585/73983942-dabbef80-4937-11ea-911f-6276633c734f.png)

Please consider to don't warn about these situations.

**Comment by frodrigo** [comment]
This check come from JOSM validator "numeric".

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
The rule in general supports semicolons, but not with two single values. I'll have a look if I can adjust the regexp accordingly: https://josm.openstreetmap.de/browser/josm/trunk/data/validator/numeric.mapcss#L278

**Comment by sun-geo** [comment]
Thank you both, for checking this.

**Comment by frodrigo** [comment]
@Klumbumbus can I close this issue?

**Comment by Klumbumbus** [comment]
Yes, you can close it. I didn't have time/motivation to look at this, however I moved the issue here: https://josm.openstreetmap.de/ticket/18765

**Comment by Klumbumbus** [comment]
Fixed in JOSM in https://josm.openstreetmap.de/changeset/15965

**Comment by sun-geo** [comment]
@Klumbumbus
Thanks a lot.

@frodrigo
This JOSM change will also modify the corresponding osmose rule?

**Comment by frodrigo** [comment]
MapCass updated on Osmose side.
