### ISSUE TITLE
Check for pipes in destination tags

### ISSUE THREAD

**Issue by Discostu36** [osm-fr/osmose-backend#752]
The following tags should be checked if the value contains a pipe (`|`):

- `destination`
- `destination:forward`
- `destination:backward`
- `destination:ref`
- `destination:ref:forward`
- `destination:ref:backward`
- `destination:symbol`
- `destination:symbol:forward`
- `destination:symbol:backward`
- `destination:ref:to`
- `destination:ref:to:forward`
- `destination:ref:to:backward`
- `destination:int_ref`
- `destination:int_ref:forward`
- `destination:int_ref:backward`
- `destination:country`
- `destination:country:forward`
- `destination:country:backward`
- `destination:street`
- `destination:street:forward`
- `destination:street:backward`

Pipes should only be used for destination lanes, not for destination.

**Example:**

Wrong:
`destination=Paris|Bordeaux`

Correct 1:
`destination:lanes=Paris|Bordeaux`

Correct 2:
`destination=Paris;Bordeaux`

**Comment by klenje** [comment]
Fixed with https://github.com/osm-fr/osmose-backend/pull/855

**Comment by klenje** [comment]
http://osmose.openstreetmap.fr/fr/errors/?source=24767&item=3160&class=316010
I see quite some false positives like:

destination:symbol:lanes
destination:ref:lanes
destination:colour:lanes

We should probably exclude any key containing lanes

**Comment by frodrigo** [comment]
Full result at
http://osmose.openstreetmap.fr/en/errors/?item=3160&class=316010

@klenje, thank you, please make a new PR

**Comment by klenje** [comment]
@frodrigo deployment is done automaticaly? how can I check the version? Because I don't see the changes yet

**Comment by frodrigo** [comment]
No is manual. And it is not yet deployed.
cc @jocelynj

**Comment by klenje** [comment]
All right, thanks! No pressure :)

**Comment by frodrigo** [comment]
Deployed, update in progress.

**Comment by klenje** [comment]
Looks better, but I think the proposed fix is wrong, I will do another PR later

**Comment by frodrigo** [comment]
Deployed, update in progress.

**Comment by klenje** [comment]
looks good to me. No false positives and correct fix suggested

**Comment by frodrigo** [comment]
Thank you.
