### ISSUE TITLE
turn restriction into an oneway:X=no way reports incorrect restriction

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#755]
http://osmose.openstreetmap.fr/nl/error/44baeeb6-9b8d-e209-d730-7d26a2f4a813

This error reports an incorrect turn restriction relation (3180, class 4). The situation is
`from` is a oneway cycleway towards the `to` way
`via` is just a node
`to` is a oneway road with `oneway:cycleway = no`

Probably, oneway:bicycle (or any other oneway:*=no exceptions) is not considered in the error evaluation?

**Comment by frodrigo** [comment]
Please can you try to spot the issue here: https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_restriction.py

**Comment by Famlam** [comment]
Hmm, spotting the error isn't difficult (https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_restriction.py#L265 doesn't evaluate `oneway:X`, where X can be bicycle, psv, moped, ...[any transport type]). 

However, I'm not familiar enough with the (SQL?) syntax to think of a good fix. (There's ~324 possible combinations of oneway(from-way), oneway(to-way), oneway:X(from-way) oneway:X(to-way), direction(from-way), direction(to-way) and I cannot figure out what is dealt with already; requiring any oneway:X tag present to be the same on both roads is probably too harsh)

**Comment by frodrigo** [comment]
But the restriction concern only bicycle I guess. This should be `restriction:bicycle=only_straight_on`

https://wiki.openstreetmap.org/w/index.php?title=Relation:restriction&uselang=fr

**Comment by Famlam** [comment]
It applies to `bicycle`, `mofa` and `moped`, as is set (or the default) for the cycleway. However, that means it applies to all vehicles coming from the `from` road, so such a "restriction" to the restriction relation (i.e., making it `restriction:bicycle` and others) isn't needed and would hence only be tagging for the validator

**Comment by frodrigo** [comment]
It is complicated to detect implicit access of the from way, could also be oneway:X. 

Please just mark this as false positive.

**Comment by Famlam** [comment]
And regarding _explicit_ oneway access, like http://osmose.openstreetmap.fr/nl/error/56b92810-6e7c-2add-e549-32f11a3a1937 (which, indeed, could be moped-only too, although unnecessary)?

**Comment by frodrigo** [comment]
As the default is for car. This one is also useless as is I think.

**Comment by gileri** [comment]
>It applies to bicycle, mofa and moped, as is set (or the default) for the cycleway. However, that means it applies to all vehicles coming from the from road, so such a "restriction" to the restriction relation (i.e., making it restriction:bicycle and others) isn't needed and would hence only be tagging for the validator

I agree with that. It seems easily doable to add a `NOT 'oneway:*'='yes'` [here](https://github.com/osm-fr/osmose-backend/blob/577be61/analysers/analyser_osmosis_relation_restriction.py#L231-L232) to avoid this false positive.

In [this case](http://osmose.openstreetmap.fr/fr/error/50471d69-52b2-dade-e0da-e6e94d0a509d), the restriction applies to all vehicles (French "ligne blanche"), even if only `bicycle` should be coming from the `from` way.

Would you would accept such a PR ?

**Comment by frodrigo** [comment]
Yes, please make à PR.
