### ISSUE TITLE
Missing tags in Mapillary issue descriptions 

### ISSUE THREAD

**Issue by SilentSpike** [osm-fr/osmose-backend#762]
Example: https://osmose.openstreetmap.fr/en/error/e9c1fafe-2e55-635a-0cc9-259a95be778d

>Traffic sign (max height limit) detected by Mapillary, but no nearby "" tagging.

This only applies to the traffic sign issues, basically it's because there aren't entries in the `generate_tags` key of

https://github.com/osm-fr/osmose-backend/blob/2d899d2ea4aac90e4da90ac954d8a0058e392cd6/merge_data/mapillary-traffic-signs.mapping.json#L770

Which is used to populate this string here

https://github.com/osm-fr/osmose-backend/blob/2d899d2ea4aac90e4da90ac954d8a0058e392cd6/analysers/analyser_merge_traffic_signs.py#L77

Quick glance at the code makes me think it's fine to simply add `maxheight: null` (etc.) into the json since `generate_tags` is filtered by the values before being used here

https://github.com/osm-fr/osmose-backend/blob/2d899d2ea4aac90e4da90ac954d8a0058e392cd6/analysers/analyser_merge_traffic_signs.py#L92

**Comment by frodrigo** [comment]
The detail message should be building using `select_tags` not `generate_tags`.
