### ISSUE TITLE
Osmose not working in San Marino

### ISSUE THREAD

**Issue by syntex1** [osm-fr/osmose-backend#763]
Recently I've made some edits in the country of San Marino and I wanted to check, if there were any errors in the country and surprisingly the Osmose map is empty. The only objects that have an error node are those that are also a part or go through the Italy. My question is: Why osmose is not working in San Marino and is it easily fixable? Thanks

**Comment by frodrigo** [comment]
We supposed cover all the world, but it appear we never have support of San Marino!

**Comment by frodrigo** [comment]
Related #87

**Comment by syntex1** [comment]
I think the same problem is also with the Vatican City

**Comment by frodrigo** [comment]
Config added, waiting for extract to be generated.

**Comment by frodrigo** [comment]
@jocelynj the diffs are here but no the extracts, something is wrong, or we just have to wait more?
