### ISSUE TITLE
non-working defibrillators analysers

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#767]
Some of defibrillators analysers are not working any more (http 404).
* analyser_merge_defibrillators_FR_gers.py
* analyser_merge_defibrillators_FR_hautesalpes.py
* analyser_merge_defibrillators_FR_hautevienne.py 
* analyser_merge_defibrillators_FR_toulouse.py

cc @wadouk

**Comment by wadouk** [comment]
Thought that all was removed because of the new national project about DAE but seems that just the links changed. Maybe just the links to change.

**Comment by jocelynj** [comment]
For information, there is a travis test that can find this kind of issues: https://travis-ci.com/osm-fr/osmose-backend/jobs/288140624

It is not enabled to mark a commit as failing for the moment.

**Comment by wadouk** [comment]
- [x] analyser_merge_defibrillators_FR_gers.py 200 but format change
 - [x] analyser_merge_defibrillators_FR_hautesalpes.py 404
 - [x] analyser_merge_defibrillators_FR_hautevienne.py DEAD
 - [x] analyser_merge_defibrillators_FR_toulouse.py 200
