### ISSUE TITLE
new analyse to detect duplicated import of nodes

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#77]
it's about detect duplicated nodes.
this 2 changest are from the same user who upload 2 times the same data
https://www.openstreetmap.org/changeset/34273139
https://www.openstreetmap.org/changeset/34273083

i try this

sql10 = """
-- node which is not in way and relation
CREATE TEMP TABLE {0}onlynodes AS
SELECT
    id,tags,geom
FROM
    nodes
LEFT JOIN way_nodes ON
    nodes.id = way_nodes.node_id
LEFT JOIN relation_members ON
    nodes.id = relation_members.member_id and
    relation_members.member_type = 'N'
WHERE
     way_nodes.node_id IS NULL AND
     relation_members.member_id IS NULL
 ;
"""

sql11 = """
CREATE INDEX {0}onlynodes_idx ON {0}onlynodes USING gist(geom);
"""

sql12 = """
SELECT
    b1.id AS id1,
--    b2.id AS id2,
    ST_AsText(b1.geom)
FROM
    {0}onlynodes AS b1,
    {1}onlynodes AS b2
WHERE
    b1.id > b2.id AND
    b1.geom && b2.geom AND 
    ST_Equals(b1.geom, b2.geom) AND
    ((b1.tags @> b2.tags ) and (b2.tags @> b1.tags ))
;
"""

**Comment by didier2020** [comment]
issues can be see there :
http://dev.osmose.frontend.dirif.info/fr/errors/?item=1230&class=3

**Comment by frodrigo** [comment]
Ok, I will integrate this. How long it's take ?

**Comment by frodrigo** [comment]
What about remove this :
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_duplicated_geotag.py#L40
As the description say:
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_duplicated_geotag.py#L113

**Comment by didier2020** [comment]
"cela n'est pas chronophage"
j'ai optimisé la detection depuis :
(cela ne genere des faux positifs que pour le tagging indoor)

sqln10full = """
CREATE TEMP TABLE {0}onlynodesfull AS
SELECT
    id,tags,geom
FROM
    nodes
WHERE
array_length(akeys(delete(delete(delete(delete(nodes.tags,'source'),'created_by'),'converted_by'),'attribution')),1) >0 AND
     not (nodes.tags ? 'man_made' and nodes.tags->'man_made' = 'survey_point')
 ;
"""

sqln11full = """
CREATE INDEX {0}onlynodesfull_idx ON {0}onlynodesfull USING gist(geom);
"""

sqln12full = """
SELECT
    b1.id AS id1,
    b2.id AS id2,
    ST_AsText(b1.geom)
FROM
    {0}onlynodesfull AS b1,
    {1}onlynodesfull AS b2
WHERE
    b1.id > b2.id AND
    b1.geom && b2.geom AND 
    ST_Equals(b1.geom, b2.geom) AND
--    ((b1.tags @> b2.tags ) and (b2.tags @> b1.tags ))
    b1.tags = b2.tags
;
"""

**Comment by didier2020** [comment]
pour les duplicated way j'ai aussi ajouté

leisure
barrier
railway
addr:interpolation
man_made
power
dans les lignes 74 and 98

**Comment by didier2020** [comment]
to detect duplicated nodes : this return True ! 
SELECT
 ST_PointFromText('POINT(-122.16144561767 37.44493865966)', 4326) &&
 ST_PointFromText('POINT(-122.161445617676 37.444938659668)', 4326);
=> 
b1.geom && b2.geom AND ST_Equals(b1.geom, b2.geom)
is necessary

**Comment by didier2020** [comment]
last code to detect duplicated nodes (like for way with exactly duplicated/not all tags egals)

sqln10full = """
CREATE TEMP TABLE {0}onlynodesfull AS
SELECT
    id,
    nodes.tags - ARRAY['source', 'created_by', 'converted_by', 'attribution'] AS tags,
    geom
FROM
    nodes
WHERE
    nodes.tags - ARRAY['source', 'created_by', 'converted_by', 'attribution'] != ''::hstore AND
     not (nodes.tags ? 'man_made' and nodes.tags->'man_made' = 'survey_point')
 ;
"""

sqln11full = """
CREATE INDEX {0}onlynodesfull_idx ON {0}onlynodesfull USING gist(geom);
"""

sqln12full = """
SELECT
    b1.id AS id1,
    b2.id AS id2,
    ST_AsText(b1.geom),
    b1.tags = b2.tags
FROM
    {0}onlynodesfull AS b1,
    {1}onlynodesfull AS b2
WHERE
    b1.id > b2.id AND
    b1.geom && b2.geom and
    ST_Equals(b1.geom, b2.geom)
    -- fix false positive in denmark
    and not (
    (b1.tags ? 'osak:identifier' and b2.tags ? 'osak:identifier') and not (b1.tags->'osak:identifier' = b2.tags->'osak:identifier'))
 AND
    ((b1.tags @> b2.tags ) or (b2.tags @> b1.tags ))
    AND
    (NOT b1.tags?'layer' AND NOT b2.tags?'layer' OR b1.tags->'layer' = b2.tags->'layer') AND
    (NOT b1.tags?'level' AND NOT b2.tags?'level' OR b1.tags->'level' = b2.tags->'level')

;
"""

**Comment by frodrigo** [comment]
> b1.geom && b2.geom AND ST_Equals(b1.geom, b2.geom)

OK

**Comment by frodrigo** [comment]
Why
> ((b1.tags @> b2.tags ) OR (b2.tags @> b1.tags ))

And not just
`b1.tags = b2.tags`

**Comment by frodrigo** [comment]
commit updated
