### ISSUE TITLE
Question about strings

### ISSUE THREAD

**Issue by SilentSpike** [osm-fr/osmose-backend#771]
Obviously I've been updating a lot of strings here lately and wondered:

If we were to use implicit string concatenation

```python
detail = T_f(
    'This first line '
    'implicitly concatenates with this line'
    " and there's no newline characters to worry about"
    ' - plus indentation is cleaner'
)
```

Would this work fine for the process of updating the translation string files? I personally prefer this style for the benefits listed above. That same string using triple-quotes:

```python
detail = T_f(
'''This first line \
implicitly concatenates with this line\
 and there's no newline characters to worry about\
 - plus indentation is cleaner'''
)
```

Inspired to ask this after I realised my recent PRs forgot to escape the newline characters in triple-quoted strings.

**Comment by frodrigo** [comment]
Neither. The convention is to use triple-quotes, except for title. Start a column 0, cut at 80 (78?). Does not escape new lines, because it is markdown and want to keep it simple for other to contribute.

Never the less the strings to translate contain the \n.

**Comment by SilentSpike** [comment]
@frodrigo That's what I mean, in Python triple quotes you have to escape the EOL to prevent the `\n` character

**Comment by frodrigo** [comment]
Yes you can prevent `\n`, but not on all line. Since markdown require it for formatting.

I agree `\n` are bad in translation tool. I try may code layout for documentation and choose to keep it simple in the code, and make contribution simple.
