### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#772]
Hello,
I've found a lot of strings which are in English, but they aren't on Transifex, so it's not possible to translate them.

- buttons in the top left corner: Zoom in, Zoom out, Menu, Location, Search...
- "Report base on data from date" - it's a tooltip when we hover a pointer over "Issue reported on: 2020-02-17"
- "Issue details"
- "Missing tag gauge on rail"
- "Suspicious tag association - possible confusion between swimming_pool and sports_centre"
- "If this is a facility containing one or more swimming pools it should be tagged leisure=sports_centre + sport=swimming."
- "incorrect "lanes""
- "Pharmacie not integrated"
- "Pharmacie, integration suggestion"
- "Laboratoire de Biologie Médicale not integrated"
- "Laboratoire de Biologie Médicale, integration suggestion"
- "Observed on 2018-10-14"
- "Observed between 2016-12-31 and 2019-05-21"
- "addr:housenumber without number"
- "lanes=* is used for highways, not railways"
- "Combined foot- and cycleway without segregated"
- "building=razed is not a building type."
- "supervised=* is deprecated"

Would it be possible to make them translatable?

**Comment by frodrigo** [comment]
There is multiple sources for strings. The frontend, the backend and external MapCSS rules.
External MapCSS mainly come from JOSM with their own translations. For Osmose strings most of the one you show contain place holder. Maybe there are not translated yet. Witch language do you looking for?

**Comment by maro-21** [comment]
So where can I translate these strings?

**Comment by frodrigo** [comment]
Most on transifex osmose banckend or osmose frontend, but search for part of the string.

**Comment by maro-21** [comment]
None of them are there, so that's why I asked here.

**Comment by frodrigo** [comment]
Eg 

* "Pharmacie, integration suggestion" -> "{0}, integration suggestion"
* "Suspicious tag association...": come from JSOM contrib SuspiciousSwimming_Pool, translatable, but no easily

**Comment by maro-21** [comment]
- "pharmacie" is in French and it's not translatable
- where is the place to translate strings from JOSM?

**Comment by frodrigo** [comment]
*  "pharmacie" comme from data, and apply only to a french dataset, yes this part is not on translation
* JOSM https://josm.openstreetmap.de/wiki/Translations

 But note we also use contrib to JOSM and there are not under JOSM translation https://josm.openstreetmap.de/wiki/Rules . We ask to JOSM to support translation on this, it was done, but it is no easy. Look at https://github.com/Jungle-Bus/transport_mapcss . It is on Osmose transifex project. It require building a zip https://github.com/Jungle-Bus/transport_mapcss/tree/gh-pages

**Comment by maro-21** [comment]
I searched
https://www.transifex.com/josm/josm/translate
and
https://translations.launchpad.net/josm/trunk/+pots/josm/pl
but I couldn't find any of these strings.

I think not all of these strings come from JOSM.

The issue is not solved so it shouldn't be closed.

**Comment by frodrigo** [comment]
Some come from JOSM MapCSS contrib, external project to JOSM, ant there are not translatable easly, unless doing like on https://github.com/Jungle-Bus/transport_mapcss with a zip file.

**Comment by maro-21** [comment]
Ok... But what about the others? For example "Issue details" doesn't come from an external source.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-frontend/blob/master/views/map/popup.tpl#L97
It look like it have `_()` but not taken for translation.
cc @jocelynj
