### ISSUE TITLE
camp_pitch outside camping

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#775]
item | 1290
-- | --
class | 1

Example: 
https://osmose.openstreetmap.fr/fr/error/cf35cbaf-f4ad-ed30-6e89-db5f26e6f024

The camp_pitch is inside a camp_site (https://www.openstreetmap.org/way/91758971#map=17/45.58242/-0.98471) but is seen as outside.

**Comment by frodrigo** [comment]
Nothing reported for Analyser_Osmosis_Camp_Pitch_Out_Of_Camp_Site-france_poitou_charentes_charente_maritime when running locally.

http://osmose.openstreetmap.fr/en/errors/graph.png?source=416260&item=1290&class=1

@jocelynj the extract may be corrupted (on may backend?)

**Comment by Bibi56** [comment]
heads up: "my" issue list on Osmose is unusable as I changed many camp_pith: the error list is full of false positive. I won't want to declare each of them false positive as the issue seems to be a db corruption.

**Comment by frodrigo** [comment]
We purge the extracts cache, but the problem is still here. We need to rebuild the extracts.
cc @jocelynj

**Comment by jocelynj** [comment]
Could it be linked to https://github.com/osm-fr/osmose-frontend/issues/225 ?

**Comment by frodrigo** [comment]
Yes. I already done the fix, please review https://github.com/osm-fr/osmose-frontend/pull/226

**Comment by frodrigo** [comment]
Solved. The frontend was keeping delete issues.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-frontend/issues/225
