### ISSUE TITLE
The self-intersecting polygon rule is faulty

### ISSUE THREAD

**Issue by MaestroGlanz** [osm-fr/osmose-backend#776]
If a polygon reuses it's own nodes like this

![Unbenannt](https://user-images.githubusercontent.com/27563281/74975941-26869280-5428-11ea-9d02-3ef9e52dec5f.png)

it is not faulty. It is valid and rendering absolute correctly. If mapping like this is depreciated, then it can be marked as depreciated, but it is not invalid. In several cases I created wholes in polylines like this. I use multipols more, if they have more then one hole in it or the hole is far from the polyline around it.

**Comment by frodrigo** [comment]
No is not a topologically valide polygone. You must use a multipolygon even
in this case.

Le jeu. 20 févr. 2020 à 21:32, MaestroGlanz <notifications@github.com> a
écrit :

**Comment by MaestroGlanz** [comment]
Disagree. It is not a valid polygon, because?

**Comment by frodrigo** [comment]
https://postgis.net/docs/using_postgis_dbmanagement.html#OGC_Validity

The check is based on common validation.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_polygon.py#L38

There is no way to alter the validation made by Posgis/GEOS, and I comply with it.

**Comment by MaestroGlanz** [comment]
Okay, agree. You convinced me, because it makes sense. But this should be added to the wiki, before this is closed here. Otherwise it will be forgotten.
