### ISSUE TITLE
Remove "Duplicated similar values"

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#779]
Can we remove item 3060 Duplicated similar values?

Looks like there are more false positives than something that needs to be corrected.
In fact, I didn't find any error that needed improvement.

In my region there are thousands of errors like this:
- [x] railway:signal:shunting:states = PL-PKP:ms1;PL-PKP:ms2
- [x] railway:signal:combined:states=PL-PKP:s1;PL-PKP:s2;PL-PKP:s3;PL-PKP:s4;PL-PKP:s5;PL-PKP:s10a;PL-PKP:s11a;PL-PKP:s12a;PL-PKP:s13a;PL-PKP:s10;PL-PKP:s11;PL-PKP:s12;PL-PKP:s13

I also don't see what's wrong with these ones:
- [ ] sport=snowboard;ski;windsurfing;kitesurfing
- [ ] old_name:de = Märzdorf;Merzdorf
- [ ] destination=Milicz;Żmigród;Żmigródek;Garbce
- [ ] turn:lanes=left|through;left|through
- [x] service_times=Sa 17:00; Fr 09:00; Su 09:00; We 17:00
- [x] healthcare:speciality=cardiology;gynaecology;stomatology;dermatology
- [x] the same with phones and faxes.

Subitem "duplicated values" looks ok. It finds errors like:
- [ ] Duplicated values source=Bing;Bing;GPS;Bing

But for "Duplicated similar values" I don't see any issues that need to be corrected.

http://osmose.openstreetmap.fr/pl/errors/?item=3060

**Comment by frodrigo** [comment]
Let's try first to improve it https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_DuplicateValue.py

**Comment by frodrigo** [comment]
With the first fix we already loose a large part of false positives.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=3060&class=30601
http://osmose.openstreetmap.fr/en/errors/graph.png?item=3060&class=30601&start_date=2020-02

**Comment by maro-21** [comment]
The graph looks great :)
Thank you, good job!

Can we also add `phone`, `fax`, `contact:phone` and `contact:fax`, to the blacklist?
And `alt_name`?

**Comment by frodrigo** [comment]
Ok for phone* and fax*.

But not sure about alt_name, wiki say to avoid multiple values in it.

**Comment by maro-21** [comment]
Didn't know about it. Strange. What if there are more than one alternative names?

Looks like `alt_name` together with `old_name` dominates here
Examples:
Duplicated similar values alt_name=Chaykendy;Chaykhaneh;Chaikhana
Duplicated similar values alt_name:be=Юзафоўка;Юзіфоўка;Юзяфаўка;Язэпоўка
Duplicated similar values alt_name=Geydarabad;Haiderabad;Haidarabad;Hedarabad
Duplicated similar values alt_name:en=Aghajaglil;Aghaj Owghlu;Aghaj Uqli;Aqajoli;Agadzhagly;Aghaj Oghlu

If the Wiki suggests to avoid such, what it suggests to do instead? If `alt_name:en=Aghajaglil;Aghaj Owghlu;Aghaj Uqli;Aqajoli;Agadzhagly;Aghaj Oghlu` is incorrect, how to correct it?

We should also blacklist these ones:
- `healthcare:speciality` - becasue many of them ends with "-ology"
- `passenger=national;regional` - many such errors in Ireland
- `tiger:cfcc=B11:B11; B21; B21:B13` - many such errors in the US
- `statscan:rbuid=2309967;2309988;2309990;2310012;2310067;3462931;3542465;3542481;3759162;3836755` - many such errors in Ontario
- `destination` - example: `destination=US 54 West; US 400 West; Kingman`
- `addr:unit=120-101;120-102;120-103;120-104;120-201;120-202;120-203;120-204;120-301;120-302;120-303;120-304;120-B1;120-B2;130-101;130-102;130-103;130-104;130-201;130-202;130-203;130-204;130-301;130-302;130-303;130-304;130-B1;130-B2`

**Comment by maro-21** [comment]
We should also exclude:
- `description`:
description=obejmuje 100 m linii brzegowej; N 54°05'53.95" E 15°04'56.48"; N 54°05'54.86" E 15°05'01.78"; N 54°05'54.28" E 15°05'01.90"; N 54°05'53.67" E 15°05'02.34"; N 54°05'52.74" E 15°04'57.05"; N 54°05'53.35" E 15°04'56.75"
- `inscription`:
inscription=Bogatynia; Hrádek n.N.; Zittau; Tutaj rozwija się wspólnie Europa.; Zde vyrůstá Evropa společně.; Hier wächst Europa zusammen.; 01.05.2004; Na pamiatke; Na památku; Zur Erinnerung
- `email` and `contact:email`
- `turn:lanes`:
turn:lanes=left|through;left|through - there are three values here, because lanes are separated by "|"
- `cuisine`:
cuisine=italian;sicilian;fish;pasta
cuisine=kurdish;turkish;arabic
cuisine=mexican;american
- `opening_hours:kitchen`:
opening_hours:kitchen=Mo 12:00-21:30; Tu-Fr 12:00-21:30; Sa 13:00-21:30; Su 13:00-21:30
- `traffic_sign`:
There could be multiple traffic signs on one pole: traffic_sign=DE:262:3.5;DE:1026-36;DE:1020-30
- `sport`:
sport=basketball;football;netball

**Comment by frodrigo** [comment]
Updated, but low impact.

More to disable can be found here: http://osmose.openstreetmap.fr/en/errors/?item=3060&class=30601

**Comment by frodrigo** [comment]
Open new issue if required.
