### ISSUE TITLE
"lanes=* is used for highways, not railways"

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#780]
"lanes=* is used for highways, not railways" - it suggests an error for a way tagged:
```
disused:railway = tram
highway = tertiary
railway = disused
lanes=2
```

There is a "highway=*" tag so it shouldn't suggest an error.

**Comment by frodrigo** [comment]
* item=9015
* class=9015024

It come from openrailwaymap validator. Please report to this project https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/validator/openrailwaymap.validator.mapcss

**Comment by frodrigo** [comment]
Reported to OpenRailwayMap project https://github.com/OpenRailwayMap/OpenRailwayMap/issues/682

**Comment by DerDakon** [comment]
Are you sure you are on the latest version of the OpenRailwayMap rules? This has [already been reported](https://github.com/OpenRailwayMap/OpenRailwayMap/issues/660) and is fixed since November in our rules.

**Comment by frodrigo** [comment]
Sure we are not on the last version! Sorry for annoying you.

**Comment by ferdinand0101** [comment]
The problem is that the validator only accepts abandoned and razed but not disused.

**Comment by maro-21** [comment]
The example from my first post here
```
disused:railway = tram
highway = tertiary
railway = disused
```

is often used in my city for roads where used to be a tramway, but there isn't anymore. Such tagging is used to probably not draw another line for railway, so it's the same feature. Would it be ok if I change it to 
```
abandoned:railway = tram
railway = abandoned
```
?
These tram railways are indeed abandoned, without overhead line.

**Comment by ferdinand0101** [comment]
then I'd say it's ok.
