### ISSUE TITLE
Duplicated values - blacklist couplings:diameters

### ISSUE THREAD

**Issue by kudlav** [osm-fr/osmose-backend#784]
Problem: http://osmose.openstreetmap.fr/cs/error/9bd633b7-5e12-cd80-6d49-e46e6ad60f8e
item | 3060
class | 3060

Actual value is: couplings:diameters = 75 mm;75 mm;110 mm
According to [wiki](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant), the format is #;#;# (numeric values), for example couplings:diameters=45 mm;45 mm;110 mm.

So it's probably safe to add couplings:diameters to the following blacklist:

https://github.com/osm-fr/osmose-backend/blob/bcc4cc69bb9622c7172ea462daa7c02d966dd1d4/plugins/TagFix_DuplicateValue.py#L48

**Comment by frodrigo** [comment]
cc @flacombe any comment on this?

**Comment by flacombe** [comment]
Hi

I agree with @kudlav, couplings:diameters = 75 mm;75 mm;110 mm is correct
The amount of values should be consistent with couplings=* value (here couplings=3) is defined.

All the best
