### ISSUE TITLE
Wrong update proposition on analyser_merge_recycling_FR_csma.py

### ISSUE THREAD

**Issue by Stefal** [osm-fr/osmose-backend#788]
Hi!

If you look at these 2 corrections:
http://osmose.openstreetmap.fr/fr/error/9997c63e-58a3-2e3b-a3fc-e83e814fa03a
http://osmose.openstreetmap.fr/fr/error/b8fb3509-3671-3aa0-1e89-1f020ff43780

One want to switch the paper container to a glass_bottle container, and the other one propose to do the opposite correction on the other container (glass_bottle to paper).

Is there a way to remove these wrong "update" with some code in the analyser ?

**Comment by frodrigo** [comment]
This is not a switch, but only the add of a new attribute.

I see nothing wrong here.

**Comment by Stefal** [comment]
Yes, you're right, "switch" is a wrong word.
But still, the analyser want to add recycling:paper=yes altough the correct container with recycling:paper is already here, next to it.

**Comment by frodrigo** [comment]
Since there is no ref, the update is not possible
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_recycling_FR_csma.py#L33
This line should be removed.

**Comment by frodrigo** [comment]
Item 8122 to be removed from frontend.
