### ISSUE TITLE
Edit #21412: Missing legacy tag on a public transport stop

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#789]
Osmose suggests missing `railway=tram_stop` for:
```
public_transport = platform
tram = yes
```
on standalone points [they are not a vertex on `railway=tram`].
But this is a correct tram stop. There is even such preset in iD called "Tram Stop / Platform".
In public transport version 2 correct tagging is:
```
public_transport = stop_position
railway = tram_stop
tram = yes
````
as a vertex on `railway=tram`
plus
```
public_transport = platform
tram = yes
```
as a point.

So `railway=tram_stop` is already on a `railway` feature.

Correct me if I'm wrong.

https://wiki.openstreetmap.org/wiki/Tag:railway%3Dtram_stop
"This tag is one way to mark a tram stop. It is used on tram tracks (railway=tram) and also on light rail tracks (railway=light_rail)"

**Comment by frodrigo** [comment]
Please give a link to point to an issue. Give Item and class eg. There is a lot of rules in Osmose.

cc @nlehuby

**Comment by maro-21** [comment]
http://osmose.openstreetmap.fr/en/map/?#zoom=13&lat=51.115&lon=17.0514&item=2140&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
key | value
-- | --
source | 8235
item | 2140
class | 21412
lat lon | 51.1175198 17.0255182


name | mosty Mieszczańskie |
-- | -- | 
network | Wrocław |  
operator | ZDiUM Wrocław |  
public_transport | platform |  
ref | 10649 |  
tram | yes |

**Comment by frodrigo** [comment]
key | value
-- | --
source | 8235
item | 2140
class | 21412
lat lon | 51.1175198 17.0255182


name | mosty Mieszczańskie |
-- | -- | 
network | Wrocław |  
operator | ZDiUM Wrocław |  
public_transport | platform |  
ref | 10649 |  
tram | yes |

**Comment by maro-21** [comment]
So I think for standalone points tagged
`public_transport=platform` [and no other tags]
it shouldn't suggest 

> The legacy tag is missing, add the tag highway=bus_stop / railway=tram_stop

But rather something like "... add the tag highway=bus_stop / tram=yes"
Because `railway=tram_stop` should be used on `railway=tram` ways

and for 
`public_transport=platform` + `tram=yes` there shouldn't be an issue.

**Comment by frodrigo** [comment]
https://github.com/Jungle-Bus/transport_mapcss/blob/master/transport.validator.mapcss

**Comment by maro-21** [comment]
So would changing this 
`node[public_transport=platform][!highway][!railway][!bus]`
https://github.com/Jungle-Bus/transport_mapcss/blob/98bf41d8887f609c5196332176feeec8bc1a5da6/transport.validator.mapcss#L233
to
`node[public_transport=platform][!highway][!railway][!bus][!tram]`
solve the issue?

**Comment by frodrigo** [comment]
Please report to the https://github.com/Jungle-Bus/transport_mapcss/ project.

**Comment by maro-21** [comment]
The issue was fixed there. Would it be automatically fixed on Osmose or should we update it here as well?

**Comment by frodrigo** [comment]
It require a manual update.

**Comment by maro-21** [comment]
Can you do the update?
Should open a new issue for it?

**Comment by frodrigo** [comment]
I plan an update soon.
