### ISSUE TITLE
Reappearing issues which are already fixed in the analyser

### ISSUE THREAD

**Issue by ghost** [osm-fr/osmose-backend#791]
http://osmose.openstreetmap.fr/de/error/56095b50-c172-2ec1-8fac-6c94531f0e37

this is a "bad key" issue

it has a problem with the `strassen-nrw:abs` key.

This key should already be ignored.
Why does it keep reappearing

item | 3050
class | 3050

**Comment by frodrigo** [comment]
Look like the analyser is not up to date.
cc @jocelynj

**Comment by frodrigo** [comment]
Server is up to date.
Found a bug with key with ':'.
