### ISSUE TITLE
False positives with connection between different voltages analysis

### ISSUE THREAD

**Issue by flacombe** [osm-fr/osmose-backend#793]
Some false positives are currently shown for item 7040, class 3
Connection between different voltages

Example :
http://osmose.openstreetmap.fr/fr/error/67772eed-931b-a0f8-8c66-32233eb76049
Seen in place : http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=45.66146&lon=6.416879&item=xxxx&level=1%2C2%2C3&tags=power&fixable=

As far as I know OSM data in this area, lines are all described with voltage=400000 only.

All the best

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=7040&class=3

Bug fixed, now usable.

**Comment by flacombe** [comment]
Thank you Frédéric !
