### ISSUE TITLE
Edit 1270 almost junction: without proposed highways

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#796]
Exclude `highway=proposed`.

Proposed roads don't have to be connected to existing roads.

The same with `highway=construction`.

**Comment by frodrigo** [comment]
Was removed here e3124e642298a2659888c2a67a5c67ee4177e1d5

**Comment by maro-21** [comment]
So why doesn't it work?

**Comment by frodrigo** [comment]
Not added, removed. Need to look further why.

**Comment by Bibi56** [comment]
IMHO, I believe at some point `highway=proposed` and `highway=construction` should be connected to the network. At least if you have a construction, the connection to the existing network should be proposed or planned. If for a specific case it doesn't make sense, mark it as false positive.
