### ISSUE TITLE
Edit 2110 missing object kind and include lifecycle prefix

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#797]
"Name present but missing main tag"

Osmose should take into account lifecycle prefix (disused, construction etc.)
Because features like
```
construction:amenity=restaurant
name=XYZ
```
or 
```
disused:shop=supermarket
name=ZYX
```
are correct.

Lifecycle prefixes to include:
```
proposed:
planned:
construction:
disused:
abandoned:
demolished:
removed:
razed:
was:
```

**Comment by frodrigo** [comment]
Please, give item + class id and or links to a issue... there thousand of issues kinds.

**Comment by frodrigo** [comment]
item 2110
class 21101

**Comment by maro-21** [comment]
It's in the title: Edit "2110 missing object kind"

**Comment by frodrigo** [comment]
You can get the class id with the detail link.

**Comment by frodrigo** [comment]
Need more values here
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag.py#L124-L127
