### ISSUE TITLE
check for old landuse=construction

### ISSUE THREAD

**Issue by simonpoole** [osm-fr/osmose-backend#80]
It seems to me as if there is a tendency to map landuse=construction and then forget to revisit and remap when construction is complete. A check for "old" construction areas would be nice. What would be  considered old could be scaled by size of the area (example 1000m^2 a year is probably the latest you would want to recheck, 100'000m^2 5 years might be better).

Something similar could be done for highway=construction

**Comment by frodrigo** [comment]
This feature is already in Osmose:
http://osmose.openstreetmap.fr/en/map/#zoom=9&lat=46.762&lon=7.531&item=4070&level=1%2C2%2C3
http://osmose.openstreetmap.fr/en/errors/?item=4070
But it no depends on area, only tag for planned end of construction and last edition date on object.
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Construction.py

**Comment by simonpoole** [comment]
I was thinking more of typical non-road construction where there is, in general, no publicly known end date (which is slightly different from short term road works).

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?country=&item=4070
http://osmose.openstreetmap.fr/fr/errors/graph.png?country=&item=4070

The change doesn't detect more items.
