### ISSUE TITLE
#303210: barrier=fence and material

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#803]
I don't think using `material` with `barrier=fence` is incorrect. The preset in iD for fence has both tags: `fence_type` and `material`.

For me, `fence_type` is rather a shape of a fence, so not "wood" or "metal". There could be for example two fences with the same shape but one made of metal and one made of wood.
[Wiki says](https://wiki.openstreetmap.org/wiki/Key:fence_type) "Currently, this tag mixes function, construction type and material of fences."

Also it is very often used
`barrier=fence`: 3,908,705 features
`barrier=fence` + `material`: 22,387 features
https://taginfo.openstreetmap.org/tags/barrier=fence#combinations

Issue 303210: http://osmose.openstreetmap.fr/en/errors/?item=3032&class=303210

I understand the code: it lists fences with "material" tag but without "fence_type". But I don't think it's an issue and should be removed. Because currently there is a contradiction between Osmose and iD preset.
What do you think?
https://github.com/osm-fr/osmose-backend/blob/ffed9fa9b89c52a1854ce3ffdbca4ec4561a5b2f/plugins/TagFix_MultipleTag.py#L150-L151

**Comment by frodrigo** [comment]
Check added after query in #447

Maybe we can raise issue when there is only `material` but no `fence_type`?

**Comment by maro-21** [comment]
Currently there is a contradiction between Osmose and iD preset. People have two field to fill in: fence_type and material. And I think it's correct not to mix the values like "chain_link" and "metal" in one tag.
Typing `fence_type=wood` doesn't say if it's 
https://wiki.openstreetmap.org/wiki/File:Zaun_Freilichtmuseum_Salzburg_02.JPG
https://wiki.openstreetmap.org/wiki/File:Wooden_Fence_-_geograph.org.uk_-_1499882.jpg
or https://wiki.openstreetmap.org/wiki/File:J%C3%A4gerzaun.jpg

But let's wait with this issue, I'll start a discussion on Wiki and ask about it.

**Comment by maro-21** [comment]
> I'll start a discussion on Wiki and ask about it.

I forgot what I was going to ask ;)
But such issue is already at https://wiki.openstreetmap.org/wiki/Talk:Key:fence_type#Material_vs_type

**Comment by hungerburg** [comment]
I second that and the reasoning in #1116 - Steel/Metal/Wood are materials; Barbed_wire/Chain_link/&c are types.

The wiki even proposes "Consider using [material](https://wiki.openstreetmap.org/wiki/Key:material)=metal instead." in the valuses section of [fence_type](https://wiki.openstreetmap.org/wiki/Key:fence_type#Values)=metal.
