### ISSUE TITLE
Home Oxygen Dispensing Structure for Medical Use is not a Pharmacy

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#805]
Voir intégration [b39b3761-d70a-5cfb-837f-9734a3e90671](https://osmose.openstreetmap.fr/fr/error/b39b3761-d70a-5cfb-837f-9734a3e90671) [`ref:FR:FINESS=740016225`](http://finess.sante.gouv.fr/fininter/jsp/actionDetailEtablissement.do?noFiness=740016225)

A taguer comme une société avec un numéro FINESS ?
[`office=company`](https://wiki.openstreetmap.org/wiki/Key:office)

**Comment by frodrigo** [comment]
Please propose an add for
https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json

**Comment by gendy54** [comment]
Je les tagguerai comme shop=medical_supply avec le type:FR:FINESS=632

**Comment by pyrog** [comment]
> Je les tagguerai comme [`shop=medical_supply`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dmedical_supply) avec le type:FR:FINESS=632

Bien vu 😄 
Et aussi avec [`medical_supply=respiratory`](https://wiki.openstreetmap.org/wiki/Key:medical_supply) ?

**Comment by frodrigo** [comment]
Please, make a pull request.

**Comment by pyrog** [comment]
> Please, make a pull request.

Pour distinguer les **Pharmacie d'Officine** et les **Structure Dispensatrice à domicile d'Oxygène à usage médical**, il ne faut plus utiliser `categagretab` mais `categetab`.

Dans [healthcare_FR_finess.mapping.json](https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json), il faut :

- soit remplacer tous les codes `categagretab` par `categetab` dans `categories`
- soit ajouter  `sous-categories` avec les codes `categetab` et modifier le select dans l'analyseur [analyser_merge_healthcare_FR_finess.py#L80](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_healthcare_FR_finess.py#L80)

Je sais faire la première solution (long : il faut vérifier toutes les catégories) mais pas la seconde 😉 


categetab | libcategetab | categagretab | libcategagretab
-- | -- | -- | --
620 | Pharmacie d'Officine | 3201 | Commerce de Biens à Usage Médicaux
624 | Laboratoire pharmaceutique préparant délivrant allergènes | 3201 | Commerce de Biens à Usage Médicaux
627 | Propharmacie | 3201 | Commerce de Biens à Usage Médicaux
628 | Pharmacie Minière | 3201 | Commerce de Biens à Usage Médicaux
629 | Pharmacie Mutualiste | 3201 | Commerce de Biens à Usage Médicaux
632 | Structure Dispensatrice à domicile d'Oxygène à usage médical | 3201 | Commerce de Biens à Usage Médicaux

**Comment by gendy54** [comment]
Je sais pas faire de PR... ):

**Comment by frodrigo** [comment]
Go to this page https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json
and use the pencil to make a PR online, easy.

**Comment by vinber** [comment]
in some case could we use an other columm for the mapping, as suggest @pyrog.
Actually categories is "categagretab" but it's not enough precise in some case.

So 
1. we can use "categagretab" in some cases in actual analysis 
2. we make an other "mapping" using only "categagretab"
3. we make an other analyse : in the first one we erase 3201 et in the new one we based analyse on categagretab

**Comment by frodrigo** [comment]
I seem not so much work to switch to `categagretab`, at least in Osmose.

You can done it your self on this pad
 https://pad.april.org/p/9fpk-tf3g4n9w5y?lang=fr

There a chat on the pad.

**Comment by vinber** [comment]
OK, i changed and "simplified", based on categetab, following this http://finess.sante.gouv.fr/fininter/jsp/nomenclatures.do
i don't know where to change the fact that it's not the same column, it's colum 1 now and not 4.

**Comment by pyrog** [comment]
> OK, i changed and "simplified", based on categetab, following this
> http://finess.sante.gouv.fr/fininter/jsp/nomenclatures.do
>
Seem that you have done everything 😀

>
> i don't know where to change the fact that it's not the same column, it's
> colum 1 now and not 4.
>
I know but I am at work. I'll do that this evening

I updated the wiki yesterday (ref:FR:FINESS).
You could try to find the appropriate tags if you have time.

Yves

>

**Comment by frodrigo** [comment]
Once it is ok for you I will do the integration.

**Comment by vinber** [comment]
> I seem not so much work to switch to `categagretab`, at least in Osmose.

we used categagretab  (Catégorie d’agrégat d’établissement)
in the pad, now it's categetab (Catégorie d’établissement)
and perhaps we can add type:FR:FINESS=categetab

**Comment by frodrigo** [comment]
We lost :
* 70 Clinique
* 20 Établissements de soins autres que les hôpitaux

We add :
* Structure dispensatrice d'oxygène à usage médical
* Résidence autonomie
* EHPAD

It's of for you ?

**Comment by frodrigo** [comment]
Only one type get `"type:FR:FINESS": "632"` ?

**Comment by gendy54** [comment]
Je viens de jeter un œil sur le pad April et de faire quelques modifications.
En revanche, ne sachant pas à quoi correspondent les classes et les level, je n'ai rien bouger de côté là.
Mon idéal serait de faire un tableur avec tous les type:FR:FINESS et de décider quel tag on leur affecte, mais là on sort un peu du sujet.

**Comment by frodrigo** [comment]
Please review the PR https://github.com/osm-fr/osmose-backend/pull/810/files

No more changes on the pad.

**Comment by vinber** [comment]
@gendy54 oui pour le français ! et deeplL quand tu ne comprends pas.

> Only one type get `"type:FR:FINESS": "632"` ?

yes, it's "Structure dispensatrice d'oxygène à usage médical"
c'est pourquoi je propose type:FR:FINESS=categetab

**Comment by vinber** [comment]
@gendy54 pourquoi as-tu repassé 500 en group_home, les gens sont dépendants c'est du nursing_home https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dnursing_home il y a des soins tout le temps non ?
group_home c'est une maisson de retraite et assisted_living plutôt les résidences pour personnes agées.

**Comment by vinber** [comment]
les 437 et 448 je pense sont aussi des nursing_home je pense / des maisons d'accueils médicalisées

**Comment by vinber** [comment]
> We lost :
> 
>     * 70 Clinique
> 
>     * 20 Établissements de soins autres que les hôpitaux

yes amenity=clinic seems to have a other sens in French


> 
> We add :
> 
>     * Structure dispensatrice d'oxygène à usage médical
> 
>     * Résidence autonomie
> 
>     * EHPAD
> 
> 
> It's of for you ?

except tagging schema for EHPAD, but it's not so important !

**Comment by vinber** [comment]
j'ai des doutes également sur operator:type  @gendy54 , on peut vraiment séparer aussi "simplement" les catégories ?

**Comment by pyrog** [comment]
@gendy54 Tu peux jeter un oeil à la PR #810 ?

**Comment by frodrigo** [comment]
Maintenant que `categetab` est dans le code source. Il faut proposer des modifications du json. Il faut faire un fichier json (ici en PJ) ou PR (je peux faire les PR) par modification. Donc un json modifié par proposition :
- l’oxygène
- les EPAD
- …

**Comment by pyrog** [comment]
Je m'en occupe en rentrant du boulot ce soir. Je ne travaille pas demain
matin.

__
Yves

Le mer. 25 mars 2020 à 10:51, Frédéric Rodrigo <notifications@github.com> a
écrit :

**Comment by vinber** [comment]
Super, merci @frodrigo 

Je peux regarder demain également !

Pour être sur de bien comprendre :

- on retire 1 catégorie de la liste de catégories (anciennement catégories aggrégées)
- on "duplique" la partie item et le code, en précisant les tags
