### ISSUE TITLE
FINESS : Raisons sociales manquantes dans le sous-titre de l'erreur

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#807]
Certains établissements n'ont pas de valeurs dans le champ `rs`, mais dans `rslongue`.

Exemple: https://osmose.openstreetmap.fr/fr/error/4ee461f1-5977-2072-ded0-988318e21f06

clé | valeur
-- | --
source | 32609
item | 8340
class | 61
lat lon | 47.8418340 -0.3451070
title | fr - Etablissement de l'Aide Sociale à l'Enfance non intégré 
subtitle | en - 39, BD, DE LA PETITE VITESSE, 72300 SABLE SUR SARTHE, Maison d'Enfants à Caractère Social | en | 39, BD, DE LA PETITE VITESSE, 72300 SABLE SUR SARTHE, Maison d'Enfants à Caractère Social
timestamp | 2020-03-22 00:09:02
source code | https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_healthcare_FR_finess.py#L67
resource | https://www.data.gouv.fr/fr/datasets/finess-extraction-du-fichier-des-etablissements/

. | nofinesset | nofinessej | rs | rslongue | complrs | compldistrib | numvoie | typvoie | voie | compvoie | lieuditbp | commune | departement | libdepartement | ligneacheminement | telephone | telecopie | categetab | libcategetab | categagretab | libcategagretab | siret | codeape | codemft | libmft | codesph | libsph | dateouv | dateautor | datemaj | numuai
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
structureet | 720006105 | 720001445 | MAISON D ENFANTS LES PLEIADES |   |   |   | 39 | BD | DE LA PETITE VITESSE |   |   | 264 | 72 | SARTHE | 72300 SABLE SUR SARTHE | 0243620210 | 0243620219 | 177 | Maison d'Enfants à Caractère Social | 4501 | Etablissements de l'Aide Sociale à l'Enfance | 78630956700059 | 8790A | 08 | Président du Conseil Départemental |   |   | 1998-10-01 | 2018-01-01 | 2018-09-07

**Comment by frodrigo** [comment]
And so. What do you suggest?

**Comment by pyrog** [comment]
> And so. What do you suggest?

J'espère que la PR est claire ?

PS: J'avais envoyé un mél sur la liste discussion, il a du être noyé dans le flot 😉 
_Rép : [OSM-talk-fr] Carto Maisons de retraites, EHPAD, etc… (était : Fwd: [CrisisMappers] Re: COVID-19 Response)_

**Comment by frodrigo** [comment]
OK
