### ISSUE TITLE
FINESS : integration of telephone and fax numbers...

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#809]
On pourrait rajouter ces informations utiles. 😄 
Eventuellement le SIRET et le code APE ?

Cf. [analyser_merge_tourism_FR_aquitaine_information.py#L57](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_tourism_FR_aquitaine_information.py#L57)

On rajoute ça dans `mapping1` ou `mapping2` ?
```python
"phone": "telephone",
"fax": "telecopie",
```

**Comment by frodrigo** [comment]
`mapping2` is for secondary tags.

When value of tags from `mapping2` change in source, Osmose does not raise an issue.

**Comment by vinber** [comment]
so it's better to add it in mapping1 ?

**Comment by frodrigo** [comment]
I personally think phone and more over fax number are no primary citizen in OSM. Use yellow pages if you want to make a phone call.

**Comment by pyrog** [comment]
Je pense qu'il faut intégrer ces n° dans OSM 😄 
Tant qu'il manquera ces infos de bases, les "citoyens" continueront d'utiliser Google Map… 😞 

En tant que professionnel de santé, j'ai besoin du fax et de l'adresse mél, et bien sur d'une géolocalisation précise.

**Question :** comment mettre une seule fois pour toute les numéros de tél (mais aussi les catégories FINESS) dans tous les objets intégré à partir du fichier FINESS ?
Ça se fait dans[ analyser_merge_healthcare_FR_finess.py](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_healthcare_FR_finess.py) ou plutôt dans [healthcare_FR_finess.mapping.json](https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json) ?

**Comment by frodrigo** [comment]
Dans le fichier python.

Le jeu. 2 avr. 2020 à 09:19, Yves Pratter <notifications@github.com> a
écrit :

**Comment by adrienandrem** [comment]
I think discussions about whether or not any type of information should be put in OSM database should be initiated on mailing lists.
Using GitHub in the first place scatters discussions, reduces community access to arguments and shortcuts the consultation process.

**Comment by adrienandrem** [comment]
As a OSMAnd user I am happy to see photos and read Wikipedia articles from the map.
Being able to access information doesn't mean it has to be stored in the OSM database.

**Comment by vinber** [comment]
for me :
+1 for discussion on mailing list talk-fr (opportunities of phone, fax, ...)
+1 for discussion in french if discussion concern french community (in this case, FINESS is french opendatabase and i think if we want to associate french people and not only informaticians, we can have discussions in french).
+1 for discussion in english for international discussion on others issues

**Comment by pyrog** [comment]
@adrienandrem tu es francophone (même français qui sait 😉 )
On va discuter en FRANÇAIS  stp pour un sujet qui ne concerne que les français, ok ? 😄

**Comment by frodrigo** [comment]
The discussion was more about setting the tags as primary or not in the osmose analyser (mapping1 or mapping2).

**Comment by pyrog** [comment]
Merci Fred 😃
