### ISSUE TITLE
Error id different for different languages?

### ISSUE THREAD

**Issue by simonpoole** [osm-fr/osmose-backend#81]
WHile not a serious issue, it is slightly irritating. Can you confirm that the API returns different ids depending on the language?

**Comment by frodrigo** [comment]
No, it's not the case.
http://osmose.openstreetmap.fr/fr/error/4604364748
All language are here.

**Comment by simonpoole** [comment]
Hmm then I can't quite explain what I've been seeing here. naturally the language aspect could simply be coincidence and what I saw was the same issue simply with two different ids, unluckily I actually fixed the issue and closed both errors. So for now I'll just keep my exes open.
