### ISSUE TITLE
Verifiy tag nat_ref in france 

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#819]
Hello,
as i explain at https://wiki.openstreetmap.org/wiki/User:Didier2020#Riu
I want to integrate the nat_ref tag in France for entries, exits and exchange.
"i do the job" for "ile de france" (ex https://www.openstreetmap.org/way/332301377)
and now i want to verify on way (only in france) : 
- the values ​​entered ; nat_ref regex python
^([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])$
- tag nat_ref without tag highway "link"
- tag nat_ref without tag operator
- others i don't think yet ?

i had to do as a plugins, an analyse or ...
merci d'avance
didier

**Comment by frodrigo** [comment]
When checking only one object, without dealing with geometry, use a plugin.

You can generate the plugin from a mapcss source code. The MapCSS can also be used in JOSM.

**Comment by didier2020** [comment]
thanks,

**Comment by didier2020** [comment]
way[highway=~/^(motorway|trunk|primary|secondary|tertiary)$/] {
  set major_road;
}
way[highway=~/^.*_link$/] {
  set link_road;
}
way.major_road[nat_ref][operator][inside("FR")] {
    throwWarning: tr("{1} is not link ", "{1.tag}");
}
way.major_road[nat_ref:backward][operator][inside("FR")] {
    throwWarning: tr("{1} is not link ", "{1.tag}");
}
way.major_road[nat_ref:forward][operator][inside("FR")] {
    throwWarning: tr("{1} is not link ", "{1.tag}");
}
way.link_road[nat_ref][nat_ref!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])/][inside("FR")] {
    throwWarning: tr("{1} is invalid", "{1.tag}");
}
way.link_road[nat_ref:forward][nat_ref:forward!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])/][inside("FR")] {
    throwWarning: tr("{1} is invalid", "{1.tag}");
}
way.link_road[nat_ref:backward][nat_ref:backward!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])/][inside("FR")] {
    throwWarning: tr("{1} is invalid", "{1.tag}");
}
way[highway][nat_ref][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
}
way[highway][nat_ref:forward][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
}
way[highway][nat_ref:backward][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
}

**Comment by frodrigo** [comment]
Please, add some asserts.

**Comment by frodrigo** [comment]
Maybe add it to https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules

**Comment by didier2020** [comment]
my poor english ... asserts ?

**Comment by frodrigo** [comment]
```css
    -osmoseAssertMatchWithContext: list("way railway=rail", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way railway=rail gauge=1435", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way railway=disused", "inside=FR");
```

**Comment by didier2020** [comment]
thanks, i can now find issue with josm (i've update the mapcss)

**Comment by frodrigo** [comment]
Do you whant to add it to https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules or not?

**Comment by didier2020** [comment]
it's now added, i hope there is no issue

**Comment by frodrigo** [comment]
One assert is failing

```css
-osmoseAssertMatchWithContext: list("node highway=milestone ref='A 4' nat_ref='77PR38DC' operator='SANEF'","inside=FR");
```

**Comment by didier2020** [comment]
i have no error with josm using rule https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules
so ...?

**Comment by frodrigo** [comment]
`-osmoseAssertMatchWithContext` is not run by JOSM, it's Osmose only, JOSM assert does not support context. I hve no more info than it fail.

**Comment by didier2020** [comment]
may be a wrong copier-coller ...
`
/* #xxxxx add validation rules for French RIU (Referentiel Inter Urbain) at https://www.data.gouv.fr/fr/datasets/bornage-du-reseau-routier-national/*
/* # nat_ref is well formed on node (milestone) */
node[highway=milestone][nat_ref][nat_ref!~/([1-9][0-9]|0[1-9])PR([0-9]|[1-9][0-9]|[1-9][0-9][0-9])[DGU](|C)/][inside("FR")] {
    throwWarning: tr("{1} is not a node valid reference RIU", "{1.tag}");
    group: tr("validation rules nat_ref in france");
    -osmoseAssertMatchWithContext: list("node highway=milestone nat_ref=77PR38DC operator=SANEF", "inside=FR");
}
/* # Select major roads */
way[highway=~/^(motorway|trunk|primary|secondary|tertiary)$/] {
  set major_road;
}
/* # Select links roads */
way[highway=~/^.*_link$/] {
  set link_road;
}
/* # tag nat_ref is for links roads, ref is on major roads */
way.major_road[nat_ref][operator][inside("FR")] {
    throwWarning: tr("{1} must be a link road", "{1.tag}");
    group: tr("validation rules nat_ref in france");
    -osmoseAssertMatchWithContext: list("way highway=primary_link nat_ref='62A901609CD_2' operator='SANEF'", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=primary nat_ref='62A901609CD_2' operator='SANEF'", "inside=FR");   
}
way.major_road[nat_ref:backward][operator][inside("FR")] {
    throwWarning: tr("{1} must be a link road", "{1.tag}");
    group: tr("validation rules nat_ref in france");
    -osmoseAssertMatchWithContext: list("way highway=motorway_link nat_ref:forward='62A902615CD_1' nat_ref:backward='62A902615CD_2' operator='SANEF'", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=motorway nat_ref:forward='62A902615CD_1' nat_ref:backward='62A902615CD_2' operator='SANEF'", "inside=FR");
}
way.major_road[nat_ref:forward][operator][inside("FR")] {
    throwWarning: tr("{1} must be a link road", "{1.tag}");
    group: tr("validation rules nat_ref in france");
}
/* # tag nat_ref is well formed */
way.link_road[nat_ref][operator!="VILLE DE PARIS"][nat_ref!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])/][inside("FR")] {
    throwWarning: tr("{1} is not a valid reference", "{1.tag}");
    group: tr("validation rules nat_ref in france");
    -osmoseAssertMatchWithContext: list("way highway=motorway_link nat_ref='94A900402_1' operator='DIRIF'", "inside=FR");
    -osmoseAssertMatchWithContext: list("way highway=motorway_link nat_ref='80A901645CD_6' operator='SANEF'", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=primary nat_ref='62A901609CD_2' operator='SANEF'", "inside=FR");
}
/* # tag nat_ref is well formed specific Paris*/
way.link_road[nat_ref][operator="VILLE DE PARIS"][nat_ref!~/75Periph_Paris_[0-9]{2}_(1[0-9]|[1-9])/][inside("FR")] {
    throwWarning: tr("{1} is not a valid reference (Paris)", "{1.tag}");
    group: tr("validation rules nat_ref in france");
    -osmoseAssertMatchWithContext: list("way highway=trunk_link nat_ref='75Periph_Paris_05_3' operator='VILLE DE PARIS'", "inside=FR");
}

way.link_road[nat_ref:forward][nat_ref:forward!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])/][inside("FR")][one_way!=yes] {
    throwWarning: tr("{1} is not a valid reference", "{1.tag}");
    group: tr("validation rules nat_ref in france");
    -osmoseAssertMatchWithContext: list("way highway=motorway_link nat_ref:forward='62A902615CD_1' nat_ref:backward='62A902615CD_2' operator=SANEF", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=motorway_link nat_ref:forward='62A902615CD_1' one_way='yes' operator='SANEF'", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=motorway nat_ref:forward='62A902615CD_1' one_way='no' operator='SANEF'", "inside=FR");
}
way.link_road[nat_ref:backward][nat_ref:backward!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])/][inside("FR")][one_way!=yes] {
    throwWarning: tr("{1} is not a valid reference", "{1.tag}");
    group: tr("validation rules nat_ref in france");
}
/* # nat_ref reference without operator */
way[highway][nat_ref][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
    group: tr("validation rules nat_ref in france");
}
way[highway][nat_ref:forward][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
    group: tr("validation rules nat_ref in france");
}
way[highway][nat_ref:backward][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
    group: tr("validation rules nat_ref in france");
}

`

**Comment by frodrigo** [comment]
Ok. But sill issues with messages, place holder en tags replacement start 0 not 1.
```css
tr("{1} must be a link road", "{1.tag}");
```

**Comment by didier2020** [comment]
sorry, it's fixed

**Comment by frodrigo** [comment]
This assert is false
```css
-osmoseAssertMatchWithContext: list("node highway=milestone nat_ref=77PR38DC operator=SANEF","inside=FR");
```

You can test in JOSM by removing the context `[inside("FR")]` and using `assertMatch` and `assertNoMatch`.

**Comment by didier2020** [comment]
there was also a missing $ in nat_ref regex

```
/* #xxxxx add validation rules for French RIU (Referentiel Inter Urbain) at https://www.data.gouv.fr/fr/datasets/bornage-du-reseau-routier-national/*
/* # nat_ref is well formed on node (milestone) */
node[highway=milestone][nat_ref][nat_ref!~/([1-9][0-9]|0[1-9])PR([0-9]|[1-9][0-9]|[1-9][0-9][0-9])[DGU](|C)$/] {
    throwWarning: tr("{0} is not a node valid reference RIU", "{1.tag}");
    group: tr("validation rules nat_ref in France");
    -osmoseAssertMatch: list("node highway=milestone distance=38 ref='A 4' nat_ref=77PR38DC operator=SANEF");
    -osmoseAssertNoMatch: list("node highway=milestone ref='A 4' distance=38");
    -osmoseAssertNoMatch: list("node highway=milestone distance=38");
}
/* # Select major roads */
way[highway=~/^(motorway|trunk|primary|secondary|tertiary)$/] {
  set major_road;
}
/* # Select links roads */
way[highway=~/^.*_link$/] {
  set link_road;
}
/* # tag nat_ref is for links roads, ref is on major roads */
way.major_road[nat_ref][operator][inside("FR")] {
    throwWarning: tr("{0} must be a link road", "{1.tag}");
    group: tr("validation rules nat_ref in France");
    -osmoseAssertMatchWithContext: list("way highway=primary_link nat_ref='62A901609CD_2' operator='SANEF'", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=primary nat_ref='62A901609CD_2' operator='SANEF'", "inside=FR");   
}
way.major_road[nat_ref:backward][operator][inside("FR")] {
    throwWarning: tr("{0} must be a link road ", "{1.tag}");
    group: tr("validation rules nat_ref in France");
    -osmoseAssertMatchWithContext: list("way highway=motorway_link nat_ref:forward='62A902615CD_1' nat_ref:backward='62A902615CD_2' operator='SANEF'", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=motorway nat_ref:forward='62A902615CD_1' nat_ref:backward='62A902615CD_2' operator='SANEF'", "inside=FR");
}
way.major_road[nat_ref:forward][operator][inside("FR")] {
    throwWarning: tr("{0} must be a link road", "{1.tag}");
    group: tr("validation rules nat_ref in France");
}
/* # tag nat_ref is well formed */
way.link_road[nat_ref][operator!="VILLE DE PARIS"][nat_ref!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])$/][inside("FR")] {
    throwWarning: tr("{0} is not a valid reference", "{1.tag}");
    group: tr("validation rules nat_ref in France");
    -osmoseAssertMatchWithContext: list("way highway=motorway_link nat_ref='94A900402_1' operator='DIRIF'", "inside=FR");
    -osmoseAssertMatchWithContext: list("way highway=motorway_link nat_ref='80A901645CD_6' operator='SANEF'", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=primary nat_ref='62A901609CD_2' operator='SANEF'", "inside=FR");
}
/* # tag nat_ref is well formed specific Paris*/
way.link_road[nat_ref][operator="VILLE DE PARIS"][nat_ref!~/75Periph_Paris_[0-9]{2}_(1[0-9]|[1-9])$/][inside("FR")] {
    throwWarning: tr("{0} is not a valid reference (Paris)", "{1.tag}");
    group: tr("validation rules nat_ref in France");
    -osmoseAssertMatchWithContext: list("way highway=trunk_link nat_ref='75Periph_Paris_05_3' operator='VILLE DE PARIS'", "inside=FR");
}
way.link_road[nat_ref:forward][nat_ref:forward!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])$/][inside("FR")][one_way!=yes] {
    throwWarning: tr("{0} is not a valid reference", "{1.tag}");
    group: tr("validation rules nat_ref in France");
    -osmoseAssertMatchWithContext: list("way highway=motorway_link nat_ref:forward='62A902615CD_1' nat_ref:backward='62A902615CD_2' operator=SANEF", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=motorway_link nat_ref:forward='62A902615CD_1' one_way='yes' operator='SANEF'", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("way highway=motorway nat_ref:forward='62A902615CD_1' one_way='no' operator='SANEF'", "inside=FR");
}
way.link_road[nat_ref:backward][nat_ref:backward!~/([1-9][0-9]|0[1-9])[ANP]9[0-9]{3}[0-9]{2}[a-z]*(|CD)_(1[0-9]|[1-9])$/][inside("FR")][one_way!=yes] {
    throwWarning: tr("{0} is not a valid reference", "{1.tag}");
    group: tr("validation rules nat_ref in France");
}
/* # nat_ref reference without operator */
way[highway][nat_ref][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
    group: tr("validation rules nat_ref in France");
}
way[highway][nat_ref:forward][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
    group: tr("validation rules nat_ref in France");
}
way[highway][nat_ref:backward][!operator][inside("FR")] {
    throwWarning: tr("Missing tag operator with nat_ref");
    group: tr("validation rules nat_ref in France");
}

```

**Comment by frodrigo** [comment]
No need to copy here, I get the one from the JOSM wiki.
I add a fix to the mapccs code. But still not ok.

- `{1.tag}` should also start at 0
- `-osmoseAssertMatch: list("node highway=milestone distance=38 ref='A 4' nat_ref=77PR38DC operator=SANEF", "inside=FR");` Still failing. The regex match. The test should not be `-osmoseAssertNoMatch` ?

**Comment by didier2020** [comment]
no : {0.tag} is for highway=milestone.
you add "inside=FR" but no change for -osmoseAssertMatch => -osmoseAssertMatchWithContext ?

**Comment by didier2020** [comment]
i found https://josm.openstreetmap.de/wiki/Help/Validator/MapCSSTagChecker
/* assertions with spaces, use \"...\" around the value */
   assertNoMatch: "node amenity=recycling collection_times=\"Mo-Fr 15:00\"";

=> error is space  in ref ?

**Comment by frodrigo** [comment]
> Failed process seem to be still here, doing some thing.

Right !

>  -osmoseAssertMatch => -osmoseAssertMatchWithContext ?

Right !

> error is space in ref ?

No. The "error" is the fact that the `-osmoseAssertMatch: list("node highway=milestone distance=38 ref='A 4' nat_ref=77PR38DC operator=SANEF", "inside=FR");` was not meet.
The tags provided to `osmoseAssertMatch` (`-osmoseAssertMatchWithContext`)  does not match the rule, as expected.

**Comment by didier2020** [comment]
je suis désolé car je ne comprends pas (pas a grand chose a l'anglais et a osmoseassertmatch....)

**Comment by frodrigo** [comment]
Est-qu'il ne faut pas juste mettre `-osmoseAssertNotMatchWithContext` à la place de `-osmoseAssertMatchWithContext` ?

**Comment by didier2020** [comment]
s'il y a highway=milestone, distance, ref, operator et nat_ref(valide) c'est "bien tagué".

**Comment by frodrigo** [comment]
Si c'est bien tagué, alors la règle ne match pas.

Assert = "s'assurer que"

**Comment by didier2020** [comment]
nomatch= c'est bien tagué
match=mal tagué ?
dans ce cas tous ce qu'e j'ai écrit est fau

**Comment by frodrigo** [comment]
Oui c'est ça.

On détecte les erreurs, donc quand la règle match, c'est que c'est mal taggé.

**Comment by didier2020** [comment]
ouf ;-),
je fais les corrections.
thanks a lot

**Comment by frodrigo** [comment]
It is ok for me.
Will be integrated in the next deploy.

**Comment by didier2020** [comment]
thanks

**Comment by frodrigo** [comment]
Can you check at the results please:
http://osmose.openstreetmap.fr/fr/errors/?item=9019&useDevItem=true

For now it is an idem item into Osmose.

**Comment by didier2020** [comment]
this is not an error  :
http://osmose.openstreetmap.fr/fr/error/1e3585b5-ca5c-0b72-3d45-b1bd3b8ac361
(operator ?)

**Comment by didier2020** [comment]
i've fixed an error in josm rules (in v36)
https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules?sfp_email=&sfph_mail=&action=diff&version=36&old_version=35.

**Comment by didier2020** [comment]
i add a rule for roundabout :
https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules?sfp_email=&sfph_mail=&action=diff&version=33&old_version=32
but this issue :
http://osmose.openstreetmap.fr/fr/error/88ae06f4-c95a-9ef1-fdd9-1122bfcebcc3

**Comment by frodrigo** [comment]
> this is not an error : http://osmose.openstreetmap.fr/fr/error/1e3585b5-ca5c-0b72-3d45-b1bd3b8ac361

Play with assert to check it the rule is working.

**Comment by didier2020** [comment]
subtitle is  'en | operator=VILLE DE PARIS is not a valid reference'
but the tag operator of the way is "operator | DIRIF" ...

**Comment by frodrigo** [comment]
About the message I create #828.

I think we are OK here. repone if is not the case.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/map/#zoom=10&lat=45.8216&lon=3.255&item=9019&level=1%2C2%2C3&tags=&fixable=

**Comment by didier2020** [comment]
? there is no tag nat_ref in this errors !
rule is node[highway=milestone][nat_ref][!ref][inside("FR")]

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=9019&class=9019002

**Comment by didier2020** [comment]
I checked all the rules , it's ok in josm.
(I miss to use osmose's mapcss code)
