### ISSUE TITLE
check addr:unit before reporting duplicate addr:housenumber

### ISSUE THREAD

**Issue by dobratzp** [osm-fr/osmose-backend#82]
item=2060, class=6
There are many situations in the United States where there are multiple buildings with the same addr:housenumber on the same addr:street.  The addr:unit tag is used to specify another number or letter to differentiate these addresses.

**Comment by jocelynj** [comment]
Fix pushed to master 6c06046745840505e38b7c92bbf296c9588b5e17.

**Comment by dobratzp** [comment]
There's an error with the output text now for all the "Number twice in the street" messages:
> Multiple numbers "(<function <lambda> at 0xb57d9d4c>, [u'3323', None, None])" in way

**Comment by frodrigo** [comment]
see #84 
Does the original problem solved ?

**Comment by dobratzp** [comment]
Yes, the original issue is solved.

The ways [289684233](http://www.openstreetmap.org/way/289684233), [289684348](http://www.openstreetmap.org/way/289684348), [289684238](http://www.openstreetmap.org/way/289684238), and [289684234](http://www.openstreetmap.org/way/289684234) were previously flagged as duplicate addresses, but now they are not.
