### ISSUE TITLE
River Deviation where it is drawn through a reservoir.

### ISSUE THREAD

**Issue by HikerDan** [osm-fr/osmose-backend#822]
Osmose reports a river deviation error because it was roughly drawn through a lake.

37806 | 3 | 1190 approximate way | 20 | E | -121.08 38.82 | w  26189793    (j) | river deviation of 51m

The waterway 26189793 (North Fork American River) is drawn through the center of Folsom Reservoir  (25354212)  is reported as a deviation error when it should not be.  It's just there to show the flow of the water through the reservoir. 

[http://osmose.openstreetmap.fr/en/error/f3ead811-be16-0fad-1727-da3e6fd2a181](url) 

Dan.

**Comment by frodrigo** [comment]
Duplicate #695
