### ISSUE TITLE
junction + area:highway

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#823]
I would like to ask you if tagging `area:highway`+`junction` really incorrect is?
Because Wiki doesn't mention anything if it can be used or not with `area:highway`.
https://wiki.openstreetmap.org/wiki/Key:junction

I would like to know if it's wrong tagging and I should correct it somehow or is it false positive.

`junction=*` is used 702,777 times and in combination with `area:highway=*` 32,090 times.
https://taginfo.openstreetmap.org/keys/?key=junction#values

Item and class number:
- [x] 20800 "Tag highway missing on junction" and
- [x] 9001001 "junction without highway".

Edit:
- [ ] update MapCSS for 9001001

**Comment by frodrigo** [comment]
This rule come from JOSM validator combinations.mapcss

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
>junction=* is used 702,777 times and in combination with area:highway=* 32,090 times.

The number of concerned objects is not so high, because junction=yes is already excluded from the test. These around 1100 ways are concerned: https://overpass-turbo.eu/s/S9t so aside from some single cases it only affects poland and one part in germany. Most of these objects are tagged junction=y_junction which is not even documented in the wiki.

However I think we can exclude area:highway=* from the test anyway.

**Comment by Klumbumbus** [comment]
Fixed in JOSM in https://josm.openstreetmap.de/changeset/16233.

**Comment by frodrigo** [comment]
Thank you.
Will be available in next MapCSS update.

**Comment by maro-21** [comment]
I would like to point out that one feature with
```
area:highway = tertiary
junction = y_junction
```
generates two issues:
- `2080, 20800: Tag highway missing on junction` and it's on level=1
- and  `9001, 9001001: junction without highway` and it's on level=3

I assume it has been corrected only for 9001001.

**Comment by maro-21** [comment]
Could you reopen this issue? Because it hasn't been resolved.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=2080&class=20800

**Comment by maro-21** [comment]
Was there already "MapCSS update"? Because I still can see that error from JOSM 9001001.

**Comment by frodrigo** [comment]
The last MapCSS was update on 2020-03-30 , so no yet.

But the Osmose plugin part of this issue is fixed.

**Comment by frodrigo** [comment]
MapCSS update in progress

**Comment by maro-21** [comment]
> MapCSS update in progress

Looks like new issues appeared today :) So this update took a lot of time
