### ISSUE TITLE
Only some of item=5010 & class=50109001 have fix suggestion

### ISSUE THREAD

**Issue by iriman** [osm-fr/osmose-backend#824]
For example this one has a fix suggestion (fix-edit button):
http://osmose.openstreetmap.fr/en/error/2d446805-3dcd-4d6b-ee5b-b19e7062b9ff
that makes it easier to fix.

but this one hasn't fix suggestion:
http://osmose.openstreetmap.fr/en/error/1f41fb3c-db3d-6e88-e478-d9b2cb85dda6

url to some issues:
http://osmose.openstreetmap.fr/en/map/#zoom=10&lat=35.709&lon=51.6&item=5010&class=50109001&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
It is already implemented.
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_MisspelledWordByRegex_Lang_fa.validator.mapcss#L39

But is should not work. To be investigated.

**Comment by frodrigo** [comment]
I need help to fix this.

We are looking for "ي" (or "ك').

Eg. "خانه فرهنگ رايزان" this string match, but no fix proposed. I do not event see where is the match in the string.

Can you explain me more how it works? And what should be done?

Should we also match:
يـ
ـيـ
ـي

And do something ?

**Comment by iriman** [comment]
In brief, no, we should not check for each form, just one unicode letter "ي". (I'll try to explain at the end)

Also may it's worth to mention that by the url you provided to the code, I digged a bit more at code. 
Could it be some sort of issue with the the way replace function works with unicode? I saw in some other parts of the code strings like u'ي'. But here it's bare 'ي'.

Explanation:

Because the Persian/Arabic script is cursive, most of the letters could have these different shapes based on their position in a word:

isolated, initial (joined on the left), medial (joined on both sides) and final (joined on the right).

However, these are all just one unicode letter that behaves this way based on its possition.
In unicode there are some dedicated codes for each form, but they never should be used explicitly in a normal text and this issue is not about that unicode dedicated forms, but about a single general letter that could appear in different forms.

For example the letter yeh "ي" may be placed in one of those positions (same unicode character in different positions):

خانه فرهنگ "**رايزان**" >> ر ا **ي** ز ا ن
 middle or 3rd letter (read from right)

خانه فرهنگ "**ساعي**" >> س ا ع **ي** 
final or last letter

خانه فرهنگ "**يار**" >> **ي** ا ر 
initial or first letter

خانه فرهنگ "**ري**" >> ر **ي** 
isolated or not joint

As you see by putting spaces between letters, all "ي"s are same. Also their unicode code is same. 

So, no, we should not check for each form, just one unicode letter "ي"

**Comment by frodrigo** [comment]
u'' string was for python2, but we are now only in python3. In python3 u'' and '' are the same.

Ok thank. better understanding. But still not explain why there is no replacement.

**Comment by frodrigo** [comment]
print(n.node(data, {u'name': u'ي'}))  -->  'ی'
            print(n.node(data, {u'name': u'رايزان'}))  -->  'رایزان'  Not working
            print(n.node(data, {u'name': u'ساعي'}))  -->  'ساعی'
            print(n.node(data, {u'name': u'يار'}))  -->  'یار'  Not working
            print(n.node(data, {u'name': u'ري'}))  -->  'ری'

I look at http://osmose.openstreetmap.fr/en/map/#source=22034&item=5010&class=50109001&zoom=13&lat=35.6929&lon=51.3553&level=1%2C2%2C3&tags=&fixable=
but found no pattern on why there is replacement or not.

**Comment by iriman** [comment]
> خانه فرهنگ "**رايزان**" >> ر ا **ي** ز ا ن
> middle or 3rd letter (read from right)
> 
> خانه فرهنگ "**ساعي**" >> س ا ع **ي**
> final or last letter
> 
> خانه فرهنگ "**يار**" >> **ي** ا ر
> initial or first letter
> 
> خانه فرهنگ "**ري**" >> ر **ي**
> isolated or not joint

Sorry, I made a mistake here.  In example 1 and 3 we have initial form of yeh. In 1, although yeh appeared middle, but it hasn't joined to the previous letter. So both 1 and 3 are examples of initial form.
A correct example for medial form:

خانه فرهنگ "**شيراز"** >> ش **ي** ر ا ز
medial form (second letter from right)

> I look at http://osmose.openstreetmap.fr/en/map/#source=22034&item=5010&class=50109001&zoom=13&lat=35.6929&lon=51.3553&level=1%2C2%2C3&tags=&fixable=
> but found no pattern on why there is replacement or not.

I will check it

**Comment by frodrigo** [comment]
print(n.node(data, {u'name': u' ي '}))  -->  ی
            print(n.node(data, {u'name': u' رايزان '}))  -->   رایزان 
            print(n.node(data, {u'name': u' يار '}))  -->   یار 
            print(n.node(data, {u'name': u' ساعي '}))  -->   ساعی 
            print(n.node(data, {u'name': u' ري '}))  -->   ری 
            print(n.node(data, {u'name': u' شيراز '}))  -->   شیراز 

So, can you check if it works only for isolated and last form?

**Comment by iriman** [comment]
The results on the right side all use Persian yeh "ی".
I mean for each form, the replacement of arabic yeh "ي" with persian yeh "ی" is done.

**Comment by frodrigo** [comment]
I finally got it! There a fix only for ways and not for nodes and relations. A bug Osmose engine.

**Comment by iriman** [comment]
Ah, thanks! I checked some of them but didn't noticed what type of element they are!

**Comment by frodrigo** [comment]
After solving an other bug on pushing result that only change the suggested fix, the result are now available on the web frontend.
Nevertheless, there is still a new bug, some popup are not updated, while the data are here.

**Comment by frodrigo** [comment]
Now OK, probably just a cache issue.
