### ISSUE TITLE
50601: international routes

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#825]
Item 50601, class 50601: Default and local language name not the same.

Could we ignore this for international bus routes? And other internation routes as well of course. The names are indeed not the same and won't be, because what is "local langauge" for a bus route that goes through three countries?
For one such relation that crosses through 3 countries, there are 4 issues in Osmose.

**Comment by frodrigo** [comment]
Only few, please just mark as false positive.
