### ISSUE TITLE
switzerland extract daily@geofabrik -> hourly@osm.ch

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#826]
osmose is using geofabrik daily extract at https://download.geofabrik.de/europe/switzerland-latest.osm.pbf and daily update at https://download.geofabrik.de/europe/switzerland-updates/
the Swiss local chapter association provides an update every hour https://planet.osm.ch
Is it conceivable to use it in order to gain reactivity ?

**Comment by frodrigo** [comment]
Yes. A new provider should be setup in https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py

**Comment by Marc-marc-marc** [comment]
at https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L33
add OSMCH=https://planet.osm.ch/

at https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L608
add download_repo=OSMCH

and the logic for the url at https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L199

it's something like that ?

**Comment by jocelynj** [comment]
There is one issue: the state.txt for the switzerland.pbf file is not provided.

Can you ask the Swiss local chapter if they can provide it?

**Comment by frodrigo** [comment]
Here https://planet.osm.ch/replication/hour/

**Comment by jocelynj** [comment]
That should be fine. Let's hope that the pbf file is generated before the state.txt file is updated.

**Comment by frodrigo** [comment]
@Marc-marc-marc do you have tested it?
