### ISSUE TITLE
Change translations for "Approximate *way" and "river deviation"

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#827]
I can't translate "Approximate {0}" into my language without translating the other part of the phrase.
There are only 3:
Approximate highway
Approximate railway
Approximate waterway

Could we split them into separate strings, please?

Similar with "{0} deviation of {1}m"

{1} is the number of meters, but {0} is a value of key "highway", "waterway" or "railway". Values can be: "river", "secondary", "tertiary" etc.
If I translate it into my language it would be "odchylenie river {1} m". Could we do something with it too? There aren't many possible values here.

A typical issue from this category looks like this:
```
Approximate waterway
river deviation of 106 m
```

**Comment by frodrigo** [comment]
There a way to reformulate the English string has we can keep the place holder while make it translatable for you?

We try to factorize strings, avoiding works to translators.

**Comment by maro-21** [comment]
Ok, forget about the second one. I translated it omitting the first parameter.
But for the first one we should split it into 3 strings.

**Comment by jocelynj** [comment]
@maro-21: can you provide examples to better understand the difference in translations between these three strings?

**Comment by frodrigo** [comment]
There many more other strings like this one. It is the only one raising problem for you?

**Comment by maro-21** [comment]
highway, railway and waterway are tag names but also English words, so 
Approximate highway
Approximate railway
Approximate waterway
looks ok in English.
But for other languages we can translate only "Approximate".
I can translate it into Polish like "Przybliżone", so the translations will look like this:
Przybliżone highway
Przybliżone railway
Przybliżone waterway but it doesn't make sense and it's confusing.
I bypassed the problem translating it into Polish as
"Przybliżona geometria linii {0}" which means "Approximate line geometry of"

What I wanted to do before was to have translations more natural, not using names of OSM tags:
Przybliżona geometria drogi = Approximate road geometry
Przybliżona geometria toru kolejowego = Approximate geometry of the railway track
Przybliżona geometria cieku = Approximate waterway geometry

So there are 2 options:
- Change the string to "Approximate geometry of {0}", so it will be more understandable and similar to the Polish one.
- Split it into three strings, so the translations into other language can be more natural, i.e. not using OSM tags but more natural words like "road".
