### ISSUE TITLE
Bad MapCSS tag value capture

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#828]
```css
[operator!="VILLE DE PARIS"]
```

Capture `VILLE DE PARIS` and not the `operator` value.

**Comment by didier2020** [comment]
the file's date plugins/Josm_FranceSpecificRules.py (01/04)  is older than 
the last version of osmose (12/04)
the version at josm FranceSpecificRules

this code is not "refresh" ?

**Comment by frodrigo** [comment]
No. It is manual update.

**Comment by frodrigo** [comment]
Capturing the not equal value was made after #532 in d45cc6427556c4014d7d92695f5f6f6e333d1605

Should we capture the actual value of the tag, or the one from the rule?

**Comment by frodrigo** [comment]
I check how JOSM report message and it report the value from the rule, not the one from the tag, like Osmose

So I think the current implementation is right.

**Comment by didier2020** [comment]
I did not fully understand 
(compris entièrement le  fonctionnement)
the operation of the osmosis and josm report message but after tests on both, it seems ok

**Comment by frodrigo** [comment]
OK.

Anyway check if you have to fix the messages in the mapcss.
