### ISSUE TITLE
Check for overlapping buildings Brandenburg is wrong/missing

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-backend#83]
Osmose gives no errors for overlapping buildings in Brandenburg.

for example:
http://osmose.openstreetmap.fr/de/map/#zoom=18&lat=52.271388&lon=13.354482&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFT&item=&level=1%2C2%2C3&tags=&fixable=
(number 11 in trebbiner Strasse)
http://osmose.openstreetmap.fr/de/map/#zoom=18&lat=52.283636&lon=13.168546&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFTT&item=0&level=1%2C2%2C3&tags=&fixable=
(gasthof Naase) in same village

or:
http://osmose.openstreetmap.fr/de/map/#zoom=18&lat=51.915519&lon=14.680593&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFT&item=&level=1%2C2%2C3&tags=&fixable=
(11/13 on the left)

see heatmap too for that:
http://osmose.openstreetmap.fr/de/map/#zoom=7&lat=52.629&lon=14.15&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFTF&item=0&level=1%2C2%2C3&tags=&fixable=

(note: thuringia isnt wrong its all fixed there)

**Comment by frodrigo** [comment]
For some reason there is a problem on some areas. The problem is a new one :
http://osmose.openstreetmap.fr/fr/errors/graph.png?source=8944&item=0&class=1

**Comment by jocelynj** [comment]
It might be linked to issue reported on https://lists.openstreetmap.org/pipermail/dev/2015-December/028961.html

Some Geofabrik extracts were incorrect yesterday, and this could explain why we lost so many errors. I have removed all erroneous extracts used by Osmose, and next results should be correct.

**Comment by frodrigo** [comment]
still not back

**Comment by dex2000** [comment]
any news?

**Comment by frodrigo** [comment]
@jocelynj many other report are missing too
http://osmose.openstreetmap.fr/fr/errors/graph.png?country=germany_brandenburg&item=xxxx

**Comment by jocelynj** [comment]
Sorry, I didn't have time to look at his yet. Will look at this in the next following days.

**Comment by dex2000** [comment]
Brandenburg is back, thx!
