### ISSUE TITLE
ref:FR:gdo "[insee_code]EEM[serial]" false negative

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/osmose-backend#830]
Hi,

Osmose raised a warning "ref:FR:gdo=38193EEM01 is invalid" here : https://osmose.openstreetmap.fr/fr/error/ad359354-6f8a-9466-a9c6-9512b1b6c7ff

However, these values are documented here : https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:gdo#Les_remont.C3.A9es_a.C3.A9ro-souterraines

Can you adjust the the filter rules to allow these values ?

Cheers
~~
laurent

**Comment by frodrigo** [comment]
Source code on JOSM wiki https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules
You can fix it your self.
cc @flacombe

**Comment by laurentriffard** [comment]
Done : https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules?action=diff&version=43
First update in JOSM mapcss filter, hope it's good.
cc @flacombe

**Comment by frodrigo** [comment]
You can add the rule in JOSM and check it on objects

**Comment by laurentriffard** [comment]
yes, I did the following :
- downloaded Rules_FranceSpecificRules.validator.mapcss on my desktop
- read the mapcss doc :-p , and made changes in the file
- loaded this file into JOM
- checked on a few objects
- then updated JOSM wiki.

**Comment by frodrigo** [comment]
Ok. Thank.

**Comment by flacombe** [comment]
That's a great point, indeed I forget about the EEM pattern when proposing validation rules in https://josm.openstreetmap.de/ticket/18640

Thank you
