### ISSUE TITLE
water=pond + leisure=fishing is conflicting

### ISSUE THREAD

**Issue by fansanelli** [osm-fr/osmose-backend#831]
Hello,

I have a doubt about this warning:

2776 | 1 | 4030 tag incompatibili | 900 | E | 6.82 45.04 | w  521147261    (j) | Conflitto tra etichette: leisure, natural

water=pond + leisure=fishing

seems like a valid exception. See also the wiki:

https://wiki.openstreetmap.org/wiki/Key:water

in particular:
water=fishpond should possibly be water=pond and/or landuse=aquaculture and/or leisure=fishing

Thanks
Francesco

**Comment by fansanelli** [comment]
Hello,

This issue regressed.

Can you please check?


2776 | 1 | 4030 incompatible tags | 900 | E | 6.82 45.04 | w  521147261    (j) | Conflict between tags: leisure, natural
-- | -- | -- | -- | -- | -- | -- | --

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/error/a631b4f0-b9ff-2e82-17c3-d8a0ffe97716

**Comment by frodrigo** [comment]
This time is
* leisure = fishing
* natural = water 

https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Incompatibles.py#L51

**Comment by fansanelli** [comment]
Oops.. right!

**Comment by matkoniecz** [comment]
@frodrigo It seems that it is also flaggable as ready (or maybe even supposed to be deployed?)
