### ISSUE TITLE
FINESS - social facility nursing_home for an EHPAD

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osmose-backend#840]
Hello,
The proposed tag social_facility should be nursing_home for an EHPAD (type:FR:FINESS=500)
But for many EHPAD, the tag is wrongly suggested : "social_facility = group_home"
Example :
http://osmose.openstreetmap.fr/fr/error/43298723-b0b8-622a-8fec-5ebe3b2549dc
or
http://osmose.openstreetmap.fr/fr/error/a15504ed-a8e3-ea86-caa6-eafd999eb658

**Comment by frodrigo** [comment]
It is already configured like this, rightly deployed on the server
https://github.com/osm-fr/osmose-backend/blob/master/merge_data/healthcare_FR_finess.mapping.json#L257-L272
But there is a bug some where, maybe be there is issue with the update of the frontend. Any help welcome.

cc @pyrog @vinber

**Comment by vinber** [comment]
this is ok EHPAD and nursing_home : http://osmose.openstreetmap.fr/fr/map/#item=8340&zoom=18&lat=44.823606&lon=-0.591787&level=1%2C2%2C3&tags=&fixable=


and here, there is a mix (http://osmose.openstreetmap.fr/fr/map/#item=8340&zoom=18&lat=44.826681&lon=-0.590199&level=1%2C2%2C3&tags=&fixable=)

text is "Etablissement d'hébergement pour personnes âgées (EHPA) non intégré" et not EHPAD, but normally texte should be "Etablissement d'hébergement pour personnes âgées dépendantes (EHPAD) non intégré" because it's a ref=500 et it's really an EHPAD

**Comment by frodrigo** [comment]
So, is it OK ?

**Comment by zorglubu** [comment]
No. The first exemple from @vinber is ok, but the second one is an error : 
detected by osmose as EHPA, but it is an EHPAD

**Comment by frodrigo** [comment]
While it is also 500. OK, got the issue. Need check arround if already integrated.

**Comment by zorglubu** [comment]
Or a problem with a cache ?

**Comment by pyrog** [comment]
I can't open the 2 examples 😞

**Comment by frodrigo** [comment]
Please check the data send to the frontend https://partage.informatique-libre.org/dl/763006

**Comment by pyrog** [comment]
Bad
* [Catégorie de l'établissement :	[500] Etablissement d'hébergement pour personnes âgées dépendantes](http://finess.sante.gouv.fr/fininter/jsp/actionDetailEtablissement.do?noFiness=780701637)
* `social_facility=group_home` should be `social_facility=nursing_home`
* Bad charset resulting in missing accentuated chars : _"personnes ges dpendantes"_

```xml
<error class="51" subclass="8356858858190006932">
	<location lat="48.8958881147627" lon="2.10270407631713" />
	<text lang="en" value="EHPAD NOTRE DAME LE PECQ, 53, R, DE PARIS, 78230 LE PECQ, Etablissement d'hbergement pour personnes ges dpendantes" />
	<fixes>
		<fix>
			<node id="0">
				<tag action="create" k="source" v="Le ministère des solidarités et de la santé - 03/2019" />
				<tag action="create" k="amenity" v="social_facility" />
				<tag action="create" k="ref:FR:FINESS" v="780701637" />
				<tag action="create" k="social_facility" v="group_home" />
				<tag action="create" k="social_facility:for" v="senior" />
			</node>
		</fix>
	</fixes>
</error>
```

**Comment by frodrigo** [comment]
Can you check the status of thus in the finess file in use https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_healthcare_FR_finess.py#L78
On old one.

**Comment by zorglubu** [comment]
I have checked the file https://static.data.gouv.fr/resources/finess-extraction-du-fichier-des-etablissements/20190307-093304/etalab-cs1100507-stock-20190307-0422.csv,
with FINESS 780701637
It's type 500.

**Comment by frodrigo** [comment]
The analyser produce twice result one in each class, while the subclass is the same:
```
<error class="111" subclass="8356858858190006932">
<location lat="48.8958881147627" lon="2.10270407631713" />
<text lang="en" value="EHPAD NOTRE DAME LE PECQ, 53, R, DE PARIS, 78230 LE PECQ, Etablissement d'hbergement pour personnes ges dpendantes" />
```
```
<error class="51" subclass="8356858858190006932">
<location lat="48.8958881147627" lon="2.10270407631713" />
<text lang="en" value="EHPAD NOTRE DAME LE PECQ, 53, R, DE PARIS, 78230 LE PECQ, Etablissement d'hbergement pour personnes ges dpendantes" />
```

**Comment by frodrigo** [comment]
No issue on local run, only on server. I try to clean the cache. Wait & see.

**Comment by zorglubu** [comment]
Having checked ~ 20 EHPAD, it gives a feeling of perfection :-)
Let me work one or two days on integration before closing the ticket.

**Comment by zorglubu** [comment]
Checked few dozens OK. I close this issue.
Thank you @frodrigo
