### ISSUE TITLE
Accept parking:lane:right AND parking:lane:left instead of parking:lane:both

### ISSUE THREAD

**Issue by DerDings** [osm-fr/osmose-backend#841]
item | 3161
-- | --
class | 31616

### Actual behavior
This plugin checks whether for each `parking:condition:[side]` if tfere is an `parking:lane:[side]` key with the same Value for `[side]`
### Expected behaviour
It should check if for every side of the street where a parking:condition is given if there also is parking:lane for this side of the street. The side may be explicitly given as `right `or `left `or implicitely as a part of `both`
So instead of only checking if both values for `[side]` are the same, it should also be checked if one pair of `right` and `left` in one key matches `both` in the other key.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=3161&class=31611
