### ISSUE TITLE
In France all pharmacies deliver drugs under prescription

### ISSUE THREAD

**Issue by pyrog** [osm-fr/osmose-backend#843]
`amenity=pharmacy` without `dispensing=yes` but with `ref:FR:FINESS=*` are pharmacies.

Osmose must suggest to add only `dispensing=yes`

Could be the same if name start with "Pharmacie".

**Comment by frodrigo** [comment]
What is the issue?
Osmose already suggest `dispensing=yes` for all `amenity=pharmacy` in France.

**Comment by pyrog** [comment]
Not an issue, a feature 😉 

Osmose suggest to:
* add `dispensing=yes`
or 
* add `shop=chemist`
* remove `amenity=pharmacie`

But with a FINESS number (or name starting with pharmacie) there is no doubt 😃

**Comment by frodrigo** [comment]
So the pharmacy merge already do the job.
