### ISSUE TITLE
1070: Highway overlaps - exclude areas

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#844]
item: 1070, class: 9 "Highway overlaps"

There should be an exception for [highway=elevator](https://wiki.openstreetmap.org/wiki/Tag:highway%3Delevator) and [highway=pedestrian](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpedestrian)
when they are closed lines (areas), because they can be drawn as an area and areas may have a common edge.

**Comment by frodrigo** [comment]
Can you give more detail about want you are asking for?

**Comment by maro-21** [comment]
Examples:
https://www.openstreetmap.org/way/442594100
https://www.openstreetmap.org/way/442594102
Osmose thinks that they are highways like for example highway=residential. But these are just two elevators close to each other, so they do share an edge. We have such tagging that elevator is "highway".
The same with highway=pedestrian because they also can be drawn as areas.

**Comment by frodrigo** [comment]
Only exclude elevator.

**Comment by maro-21** [comment]
An example with `highway=pedestrian` + `area=yes` (or other areal tag, in this case `area=yes` is redundant because of `building=yes`):

https://www.openstreetmap.org/way/101423788
https://www.openstreetmap.org/way/101428539

Or maybe I should add `area=yes to` to them to remove the Osmose issue? Looking and this line
https://github.com/osm-fr/osmose-backend/blob/25ef1466923c828d2d41a57ddb2a8e980eaf9b3d/analysers/analyser_osmosis_highway_vs_building.py#L53
it omits highways with `area=yes` tag, right?

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=51.113731&lon=17.062469&item=xxxx&level=1%2C2%2C3&tags=&fixable=
