### ISSUE TITLE
3092 phone number - add Poland

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#845]
"[3092 phone number](http://osmose.openstreetmap.fr/en/errors/?item=3092)" works only for some countries:
Argentina, Belgium, Benin, Canada, Cuba, Denmark, France, Germany, Italy, Monaco, Philippines, Spain and Switzerland.
Why only these countries and would it be possible to add Poland to the list?

**Comment by frodrigo** [comment]
Yes. Any contry can be enable. There is setting to do https://lite.framacalc.org/j53QhVFxas https://github.com/osm-fr/osmose-backend/blob/master/plugins/Phone.py#L33-L46
Look at the end for example.

**Comment by maro-21** [comment]
Polish phone numbers format:
prefix `+48` and 9 digits.
Example `+48 888 000 000`

link: https://en.wikipedia.org/wiki/Telephone_numbers_in_Poland

**Comment by frodrigo** [comment]
Please, can fill a row in the calc?

**Comment by frodrigo** [comment]
Waiting for results
http://osmose.openstreetmap.fr/en/errors/?country=poland_*&item=3092

**Comment by frodrigo** [comment]
@maro-21 The results s are available, please can you check it.

**Comment by maro-21** [comment]
Yeah, it works, thanks! :)

Small question: there is "Bad separator for multiple values" - does it mean that the correct separator is only ";" without space, right?
