### ISSUE TITLE
3250 opening hours - add Poland - missing lib on backend

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#846]
[It looks like](http://osmose.openstreetmap.fr/en/map/?#zoom=7&lat=49.628&lon=12.722&item=3250&level=1%2C2%2C3) Poland is one of the few missed European countries without validation for opening hours (3250). Would it be possible to add it to the list?

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?country=poland*&item=3250

It looks like some part are not working. 

It is not country specific.

**Comment by frodrigo** [comment]
Poland si run on a contrib server, and we have not the hand on it to check. But it look like the sever miss a library required to parse the opening hours.

cc @jocelynj

**Comment by frodrigo** [comment]
Remove of lark to use PyKOpeningHours.

**Comment by maro-21** [comment]
It started working today.
