### ISSUE TITLE
Edit 21101 Untagged named object: note & advertising

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#851]
21101: Untagged named object

- Make an exception for nodes with only `note` tag or with `name`+`note` because such nodes can be drawn to give information for other mappers.
iD already accepts such features as correct.
- add advertising=* to basic tags

**Comment by frodrigo** [comment]
There is a doc on a wiki about this ?

**Comment by maro-21** [comment]
I don't think so.

**Comment by maro-21** [comment]
And add advertising=* to basic tags.

**Comment by frodrigo** [comment]
Ok for `advertising`.
For `note` I still need to be convinced.
