### ISSUE TITLE
Clean name in SIRENE shop analyser

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/osmose-backend#858]
Concerns : `analyser_merge_shop_FR.py`

It seems that most of names suggested when integrating SIRENE data are fully uppercase, without any accents. To make contribution easier, could it be interesting to use [`reaccentue` module](https://github.com/cquest/reaccentue) which clean-up string to title case + add backs accents ?

**Comment by frodrigo** [comment]
Yes you can try at this.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=8310

It is update. Thank you.
