### ISSUE TITLE
Osmose Jupyter

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#859]

**Comment by Marc-marc-marc** [comment]
small description https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2020/Project_ideas#Osmose-QA

**Comment by frodrigo** [comment]
![imagen](https://user-images.githubusercontent.com/1785486/81209172-74934700-8fd0-11ea-8abc-b1298f7e67d8.png)

**Comment by frodrigo** [comment]
It is online (as beta service) : https://osmose-jupyter.openstreetmap.fr
aeje9ahmaiNg

**Comment by deuzeffe** [comment]
502 bad gateway right now. IPv6 only?

**Comment by frodrigo** [comment]
No, it works in ipv[46].
The service was stop. But I see there is a button to stop it from the web :/
Restarted.

**Comment by frodrigo** [comment]
> But I see there is a button to stop it from the web
Removed

**Comment by deuzeffe** [comment]
Indeed, it works \o/ (now, to understand the beast...)
(stop buttons are still visible on the web page - maybe disabled?)
![Screenshot_2020-11-08 Home Page - Select or create a notebook](https://user-images.githubusercontent.com/36087963/98465623-7b428700-21ca-11eb-84e6-7d6a64698d14.png)

**Comment by frodrigo** [comment]
It is only for the running job (aka kernel) for pages, does not matter.
