### ISSUE TITLE
"Élément de voie ou noeud barrier isolé" improper

### ISSUE THREAD

**Issue by bmallet** [osm-fr/osmose-backend#86]
A node barrier not linked to an highway will cause an error : http://www.openstreetmap.org/node/3403400165

I think it's improper considered a gate can be linked only to a linear barrier as fence : 
"Simply add the tag barrier=gate to the node or way where the gate is. This can be placed on a linear barrier, (...)"
http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate

**Comment by frodrigo** [comment]
"This can be placed on a linear barrier, in the intersection node of a linear barrier and a highway way, or at a highway way node."

May we check node is on highway or barrier ?

**Comment by frodrigo** [comment]
No more report barrier
