### ISSUE TITLE
multiple inscription dates for french heritage sites

### ISSUE THREAD

**Issue by treinen** [osm-fr/osmose-backend#867]
item=8012;class=4

Heritage inscription records of the Merimee base sometimes have several dates for the inscription, even sometimes several dates for the same level of classification. In absence of a specified rule which date to chose in that case (there is no such rule on the OSM wiki) I suggest to put all the dates, separated  as usual by ";".

I can try to produce a PR if you give me a green light. -Ralf.

**Comment by frodrigo** [comment]
Different date are for different parts of the heritage. But In OSM we does not tag such detail. So the older do the job (at least for me).

But you can anyway add all dates. Go ahead if you want to add this support on Osmose.
