### ISSUE TITLE
Mapillary objects not appearing for Canada->Ontario->Central Ontario

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#869]
http://osmose.openstreetmap.fr/en/map/#zoom=10&lat=44.3297&lon=282.38&item=8xxx&level=1%2C2%2C3&tags=&fixable=

Mapillary objects checks are visible for Eastern Ontario, and then disappear at the boundary to Central Ontario.

![Screenshot_20200509_123057](https://user-images.githubusercontent.com/26171839/81479419-06799a80-91f1-11ea-9620-8f58afa2ef4f.png)

**Comment by frodrigo** [comment]
The stats are weird
http://osmose.openstreetmap.fr/en/errors/graph.png?country=canada_ontario_central_ontario&item=8300&level=1%2C2%2C3
![imagen](https://user-images.githubusercontent.com/1785486/81484427-a52fe680-9245-11ea-9071-cb84512f900e.png)

**Comment by frodrigo** [comment]
The stats are weird
http://osmose.openstreetmap.fr/en/errors/graph.png?country=canada_ontario_central_ontario&item=8300&level=1%2C2%2C3
![imagen](https://user-images.githubusercontent.com/1785486/81484427-a52fe680-9245-11ea-9071-cb84512f900e.png)

Maybe linked to the cache on one of the backend.

cc @jocelynj  cc @Marc-marc-marc

**Comment by frodrigo** [comment]
Found a bug in the cache key of mapillary download.

**Comment by frodrigo** [comment]
The data is back.

Keep this open to monitor for a while
