### ISSUE TITLE
Basin

### ISSUE THREAD

**Issue by jjiglesiasg** [osm-fr/osmose-backend#871]
Can a feature be added so it could be fixable water=basin, landuse=basin and man_made=basin to the preferred Taggid water=basin?

In Bolivia we have thousand of this water features tagged randomly, and fix each one on-line is quite slow the process.

Thanks and Best regards

JJIglesias

**Comment by frodrigo** [comment]
Can you explain more in detail what you request.

Do you want an existing check to be amended? Witch one (item/class number)? To provide more fix suggestion?

A new check?

**Comment by Bibi56** [comment]
Why not using JOSM with todolist plugin in conjunction to overpass?
[Overpass](http://overpass-turbo.eu/s/UdM) returns 8834 polygons.

**Comment by frodrigo** [comment]
I close. Please reopen with more details.
