### ISSUE TITLE
Bad turn lanes order

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#873]
Osmose points out that `turn:lanes=reverse;left|left|through|through|through;right` is "Bad turn lanes order". Why?

**Comment by frodrigo** [comment]
Do you have a link?
Issue item/class id, please ?

**Comment by maro-21** [comment]
item: 3160
class: 31607

**Comment by frodrigo** [comment]
It is form here
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Lanes.py#L131

I re-read quickly the code and see no issue, yet.

**Comment by maro-21** [comment]
Maybe `reverse`?
Where is the order in the code? Here?
https://github.com/osm-fr/osmose-backend/blob/c3cbc59cc61c76b9c96398a63ff7930d0139611e/plugins/Highway_Lanes.py#L112-L118
If so, `reverse` is in the middle.

**Comment by frodrigo** [comment]
No this part is only translation.

Then reverse is ignored.
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Lanes.py#L120

Order check is here
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Highway_Lanes.py#L121-L131

**Comment by maro-21** [comment]
Another examples:
- [`turn:lanes=none|left|left;right`](http://osmose.openstreetmap.fr/pl/error/faa38f29-fd19-756c-a806-18abd7ba08e3)
Here we have `turn:lanes=none|left|left;right` which looks ok.
- [`turn:lanes=left;through|right|right|none`](http://osmose.openstreetmap.fr/pl/error/17de631d-a6c2-f8ca-1aa5-20fca58b57ff)

**Comment by frodrigo** [comment]
Both seem wrong to me. The none turn cannot be cross by other.

**Comment by maro-21** [comment]
> Both seem wrong to me. The none turn cannot be cross by other.

What do you mean? None is a correct value.

**Comment by frodrigo** [comment]
`left|none` is ok, but not `none|left`

**Comment by maro-21** [comment]
> `left|none` is ok, but not `none|left`

On Wiki you have an example with `turn:lanes=none|none|none|merge_to_left`
https://wiki.openstreetmap.org/wiki/Key:turn#Motorway_with_links_and_destinations

**Comment by frodrigo** [comment]
merge_to_left is not turn left.

**Comment by dex2000** [comment]
> Both seem wrong to me. The none turn cannot be cross by other.

turns are not crossing-restrictions. Of course you can cross it (not all time, but most)

Problem in the examples are the bus:lanes. A bus:lane can has no turns but be the leftest lane. 
none|left|something is right there. 
without bus:lanes (or psv whatever) its maybe wrong.

**Comment by frodrigo** [comment]
Ok, so non general traffic lanes have to be excluded from the check.

**Comment by Famlam** [comment]
A similar case is probably http://osmose.openstreetmap.fr/nl/error/04dce2a1-789f-cd05-b4fd-8580d563043f
key | value 
-- | -- 
access:lanes | \|\|no 
bicycle | use_sidepath 
bus:lanes | \|\|designated 
highway | secondary  
lanes | 3 
lit | yes 
maxspeed | 50 
name | Nieuwe Dukenburgseweg
oneway | yes 
surface | asphalt 
turn:lanes | left\|right\|

**Comment by kudlav** [comment]
Hi, this check also doesn't work with trams. I [have](http://osmose.openstreetmap.fr/cs/error/800658ad-781c-d832-5e38-daab6ab42ebe)

```
turn:lanes:backward = none|left|through;right 
psv:lanes:backward = yes|no|no 
railway:lanes:backward = tram|no|no
```
which is quite common in our city and I see nothing wrong with that.
