### ISSUE TITLE
FR, merge datatourisme

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#875]
cc @nlehuby @vinber 
Issue to improve datatourisme merge

First results with tourism_office
http://osmose.openstreetmap.fr/en/errors/?item=8420&useDevItem=all

**Comment by frodrigo** [comment]
We should add the postal address in the subtitle.

**Comment by nlehuby** [comment]
I've started a branch: https://github.com/osm-fr/osmose-backend/compare/tourism_office

**Comment by frodrigo** [comment]
From place from data.gouv, 202062 lines
Categories stats: https://pastebin.com/QtWqu7D0

All have PlaceOfInterest and PointOfInterest.

I think we can ignore all generic Accommodation and Lodging.

Low frequency contains interesting thing... but there have low frequency.

Camping or Church can be the next step as they can be found on imagery.

**Comment by frodrigo** [comment]
I make the analyser generic.
https://github.com/osm-fr/osmose-backend/pull/883

**Comment by nlehuby** [comment]
Can we have something like [this](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_building_shapes.py#L75) and let the user choose the kind of amenity/shop when we have several ones in the source dataset ?

![image](https://user-images.githubusercontent.com/919962/82749260-3e174380-9da8-11ea-90dd-963ba63d1581.png)

**Comment by frodrigo** [comment]
Multiple fixes are not implemented in merge analyser. Should require to have multiple `Generate` parts. On Sirene is just done like this https://github.com/osm-fr/osmose-backend/blob/master/merge_data/shop_FR.mapping.json#L17-L18

**Comment by frodrigo** [comment]
Merge Restaurant, Camping and Church.
Remove pervious Restaurant for Aquitaine and Saône-et-Loire

**Comment by frodrigo** [comment]
Also disable merge_tourism_FR_aquitaine_information.

We have analyser_merge_tourism_FR_aquitaine_camp_caravan.py but with:
- tourism": "caravan_site
- tourism": "camp_site

Can we have both from Datatourisme?

**Comment by frodrigo** [comment]
Camping
http://osmose.openstreetmap.fr/fr/errors/?item=8140&class=330

Church, few, probably only touristic ones (hidden item)
http://osmose.openstreetmap.fr/fr/errors/?item=8101&class=320&useDevItem=all

Restaurant
http://osmose.openstreetmap.fr/fr/errors/?item=8240&class=340

We have a static conflation distance, we should move it into the json file.

**Comment by frodrigo** [comment]
I have setup a configurable conflation distance.

@vinber please, can you look about the ref? The in Datatourisme seam to be just the same as from local producer.

**Comment by frodrigo** [comment]
Camping have a wide range of application from farm camping to tourism=hotel.

**Comment by vinber** [comment]
yes, i think in case of TourinFrance (tourinsoft, sirtaqui for exemple ?) /  the ref seems to be same than the local producer ([rdfs:isDefinedBy])

page 13 https://framagit.org/datatourisme/ontology/-/blob/master/Documentation/Ontologie%20DATAtourisme%20v2.4_Documentation.pdf

**Comment by vinber** [comment]
once again i'm lost :)
where can i see datatourism data than you merge with osm ?

**Comment by frodrigo** [comment]
So what `ref` tag to use?


@vinber it is generated from a query
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_tourism_FR.py#L47
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_tourism_FR.py#L70

**Comment by vinber** [comment]
good question, when we use it in Aquitaine, it was ref:FR:CRTA, but now with data tourism i don't know. I ask on mailing list ? 
ref:FR:tourism ?

**Comment by frodrigo** [comment]
But it is not a datatourisme ref. If it is just a copy of the local ref we may need to use the local ref key?

**Comment by frodrigo** [comment]
The adjustment of conflation distance double the number of Restaurant and Church.

**Comment by vinber** [comment]
> But it is not a datatourisme ref. If it is just a copy of the local ref we may need to use the local ref key?

yes you're right

**Comment by vinber** [comment]
In datatourism, SIT (Système d'information touristique : local source) is define by hasBeenCreatedBy or hasBeenPublishedBy
And ref is : isDefinedBy

**Comment by vinber** [comment]
and if there's no "possible_merge" but "only" missing_official it's because you have not time to do or for an other reason ?

**Comment by frodrigo** [comment]
> and if there's no "possible_merge" but "only" missing_official it's because you have not time to do or for an other reason ?

We need a ref

**Comment by vinber** [comment]
I thought it was just for update_official

**Comment by frodrigo** [comment]
> hasBeenCreatedBy

https://data.datatourisme.gouv.fr/864cf6ad-2809-39bf-a1aa-fbf3478cdf29

> hasBeenPublishedBy

https://data.datatourisme.gouv.fr/7def446d-ec1e-327f-ba4e-262070d9785e

> And ref is : isDefinedBy

For me the ref is under `dc:identifier`, `isDefinedBy` is aproperty of what?

Update query with ?creator_name and ?identifier
https://annuel.framapad.org/p/dataljfjFKJQLKQLQ

**Comment by vinber** [comment]
page 9 https://framagit.org/datatourisme/ontology/-/blob/master/Documentation/Ontologie%20DATAtourisme%20v2.4_Documentation.pdf
isDefinedBy : lorsque le concept est issu d’un thésaurus déjà existant.
Renseigner ici l’identifiant unique du terme concerné.

But i'm not sure to understand what i read.

**Comment by vinber** [comment]
I suppose you're right : 
"La référence du POI dans le SIT source est dans la propriété dublin core identifier
La référence unique du POI dans DATAtourisme est son URI"

https://support.datatourisme.gouv.fr/t/ref-du-sit-regional/1086/2

**Comment by frodrigo** [comment]
"concept" are the meta model, not the data, hasBeenCreatedBy or hasBeenPublishedBy are concept.

**Comment by frodrigo** [comment]
The issue is now that Osmose merge framework does not support variable tags key (but only variable value). We can filter data and run only on data from a source by area, or try to make support of variable key in the framework.

**Comment by frodrigo** [comment]
I change query to use ref (@nlehuby I switch the query to my own datatourism account)
I map the ref from SIRTAQUI Nouvelle-Aquitaine" to ref:FR:CRTA, like disabled tourism query.
@vinber I list the available provider at the end of https://annuel.framapad.org/p/dataljfjFKJQLKQLQ

**Comment by frodrigo** [comment]
### Nouveaux

Museum (TODO Aquitaine à supprimer)
http://osmose.openstreetmap.fr/fr/errors/?item=8010&class=350&useDevItem=all


Winery (TODO Aquitaine à supprimer)
http://osmose.openstreetmap.fr/fr/errors/?item=8250&class=360&useDevItem=all

Viewpoint
http://osmose.openstreetmap.fr/fr/errors/?item=8450&class=370&useDevItem=all

Picnic site
http://osmose.openstreetmap.fr/fr/errors/?item=8460&class=380&useDevItem=all

### Déjà présent
Camping
http://osmose.openstreetmap.fr/fr/errors/?item=8140&class=330

Church, few, probably only touristic ones (hidden item)
http://osmose.openstreetmap.fr/fr/errors/?item=8101&class=320&useDevItem=all

Restaurant
http://osmose.openstreetmap.fr/fr/errors/?item=8240&class=340

**Comment by frodrigo** [comment]
Major classes integrated and activated on frontend. Thank all.
