### ISSUE TITLE
Possible missing direction tag on stop or a give way

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#876]
source | 407746
-- | --
item | 2090
class | 4
lat lon | 47.7956004 -3.4969154
title | en Possible missing direction tag on stop or a give way 
detail | en An other node very close have already the tag `crossing=traffic_signals`. 
en | It is very likely that the traffic signals on the junction are inconsistent with each other, see also [highway=traffic_signals](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals).
source code | https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_traffic_signals.py#L179

I guess I made a mistake [here](http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=47.794985&lon=-3.49582&item=xxxx&level=1%2C2%2C3&tags=&fixable=) that I don't understand (well probably `direction`=`forward` or `backward`), but an [Overpass request](http://overpass-turbo.eu/s/UdX) confirms there is no such `crossing`=`traffic_signals` or `highway`=`traffic_signals`.

At least the error message doesn't match the case.

**Comment by frodrigo** [comment]
Update in progress

**Comment by Bibi56** [comment]
"Attribut “direction” peut-être manquant sur un stop ou laissez-le-passage" is still incorrect (in this case direction is not missing but the value is neither forward nor backward).
[6 stops here](http://osmose.openstreetmap.fr/fr/map/#zoom=17&lat=47.795557&lon=-3.496126&item=xxxx&level=1%2C2%2C3&tags=&fixable=).
