### ISSUE TITLE
Fake names

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#877]
I haven't been able to find the analyzer that wants to remove Cimetière from `landuse`=`cemetery`, but likewise Bibliothèque should be a forbidden name for `amenity`=`library`.

**Comment by frodrigo** [comment]
From the popup. Click on [i] or details to have a link to source code.

**Comment by Bibi56** [comment]
Thanks, I forgot I could use Nominatim to find "Cimetière" (I had no such error anymore). So the answer is https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/unnecessary.mapcss and I can add a ticket in JOSM.
