### ISSUE TITLE
Floating Islands Reported for Roads on One Side of an Admin Boundary

### ISSUE THREAD

**Issue by gecho111** [osm-fr/osmose-backend#879]
I'm getting false positives of error type 1210 (Small highway group apart from the main network or with insufficient access upstream), for a small area where all the roads in that area only connect to the rest of the map by crossing a provincial border (admin_level=4).

Beside the border the only other difference I've noticed is that the roads on the left side of the border all contain is_in tags

http://osmose.openstreetmap.fr/en/map/#item=1210&zoom=13&lat=50.932&lon=-109.943&level=1&tags=&fixable=

**Comment by frodrigo** [comment]
You must flag this as false positive.
Validation are done by area.
