### ISSUE TITLE
Marks/Issues not showing for users with space in name

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-backend#88]
Opening [this URL](http://osmose.openstreetmap.fr/fr/map/#username=Gautier%20PP), 178 markers should be shown but it seems that the space in username break something leading to no marker being shown.

**Comment by frodrigo** [comment]
Yes, there is a bug.http://osmose.openstreetmap.fr/fr/map/markers?username=Gautier%2520PP

**Comment by bagage** [comment]
Please let me know when this issue is fixed so that I can fix my numerous errors :)

**Comment by jocelynj** [comment]
You can use http://osmose.openstreetmap.fr/fr/byuser/?username=Gautier%20PP in the meantime.

**Comment by bagage** [comment]
Yes, but the issue is with http://osmose.openstreetmap.fr/fr/map/#username=Gautier%20PP which is automatically converted to http://osmose.openstreetmap.fr/fr/map/#username=Gautier PP leading to no markers on the map. I did not find a workaround yet for map.

**Comment by frodrigo** [comment]
Duplicate issue of https://github.com/osm-fr/osmose-frontend/issues/24

**Comment by bagage** [comment]
However this issue is *not* a duplicate of osm-fr/osmose-frontend#24 (which I reported also).

It looks to me a specific issue for names with space in it. Does [this](http://osmose.openstreetmap.fr/fr/map/#username=Gautier%20PP) work for you? It does not for me.

**Comment by frodrigo** [comment]
Fixed
