### ISSUE TITLE
Unresolved git merge in Docker instructions

### ISSUE THREAD

**Issue by wetneb** [osm-fr/osmose-backend#880]
See 
https://github.com/osm-fr/osmose-backend/blob/master/docker/README.md

which contains the following leftover git merge lines:
```
From docker container you can test analysers:
>>>>>>> 0e583394... Add Jupyter support and Plugin notebook #859
```

This should be cleaned up but it's not obvious to me how!

**Comment by frodrigo** [comment]
Thank for report fixed.
