### ISSUE TITLE
building=yurt can be round, but is not a building=hut

### ISSUE THREAD

**Issue by habi** [osm-fr/osmose-backend#885]
I've added two `building=yurt` as round ways [671218120](https://www.openstreetmap.org/way/671218120) and [195565821](https://www.openstreetmap.org/way/195565821) to OSM.
Osmose complains (somewhere [here](https://github.com/osm-fr/osmose-backend/blob/1d3f3d3393602efc4442ddcd4227219727329bbe/analysers/analyser_osmosis_building_shapes.py#L81)) that this is wrong.
I corrected the value to `building=ger` in the hope to 'please' Osmose :)

If I'm correct, this is item 7011 and class 1.
I think either a `yurt` or `ger` should be allowed (or suggested by Osmose) to be round.

**Comment by habi** [comment]
The error still pops up.
I've changed some buildings [here](http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=47.387351&lon=8.574386&item=7011&level=3&tags=&fixable=&issue_uuid=bcdc9673-ace5-5d1a-ee07-0b634ca92489) to `building=ger`, but Osmose still complains.
Or is the change from May 2020 not propagated to osmose.openstreetmap.fr yet?

**Comment by frodrigo** [comment]
Its deployed so far.
But it is not updated here
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_building_shapes.py#L40

**Comment by frodrigo** [comment]
#1234
