### ISSUE TITLE
Massage shops shouldn't create a warning

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osmose-backend#886]
### Issue
I've got an issue with a shop=massage node (https://www.openstreetmap.org/node/6470576882).
The Osmose warning suggests to correct "massage" to "message" https://osmose.openstreetmap.fr/fr/map/#item=3150&zoom=17&lat=48.815726&lon=2.310395&level=1&tags=&fixable=

I understand why I've got this warning: it's based on statistics.

### Proposal
As the shop=massage tag is approved and in use (cf. https://wiki.openstreetmap.org/wiki/Tag:shop=massage), we should make an exception in order not to have this specific warning again, shouldn't we?

**Comment by frodrigo** [comment]
To be added here
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_tag_typo.py#L80

**Comment by overflorian** [comment]
Merci !
