### ISSUE TITLE
Manage different alphabets in some countries

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osmose-backend#887]
This isn't really an issue, it's more a question:

### Issue
The message "Default and local language name not the same" is displayed for place where 2 alphabets are in use:
-Russia https://www.openstreetmap.org/way/28966446
-Myanmar https://www.openstreetmap.org/node/2608583949

It's unclear for me if the local communities already decided to use both tags: "name" and "name:ru" for Russia / "name" and "name:my" for Myanmar.
As you can see in Saint-Petersbourg, it seems that it's the case in Russia https://osmose.openstreetmap.fr/fr/map/#item=5060&zoom=14&lat=59.93306&lon=30.34119&level=1&tags=&fixable=

### Solution
How should I interpret these Osmose warnings?
Do you think I should change the data or that you should create exceptions for these countries where several alphabets are in use at the same time?
If so, I can help to identify these countries if needed.

**Comment by frodrigo** [comment]
Each country, or sub area have one or more languages.
https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L987
It is based on usage in OSM, not official country languages.
We can fix languages for an area.

**Comment by overflorian** [comment]
OK, great.

But I am not sure to understand.
Is this setup supposed to stop Osmose from creating the warning for the examples I gave before? Or would it be a behavior we would like to change?

**Comment by frodrigo** [comment]
1. The Osmose configuration for the area is correct, and data should be fixed
2. Or, contributor are locally are on using other langue and Osmose config should be fixed.

By default the `name` should be in local language and so the same value as `name:[local]`.

**Comment by matthewdarwin** [comment]
Just as an example, in Canada, we have:

```
name=English Name
name:en=English Name
name:fr=French Name
```

or

```
name=Franch Name
name:en=English Name
name:fr=French Name
```

**Comment by overflorian** [comment]
Thank you @matthewdarwin 

So if we want to fix properly this issue I believe that have 2 solutions:


1. We define country-per-country the different sets of languages.
For example in Canade there is 2 different "sets" or "setup".

Therefore we would have:
### In Myanmar country :

**Setup 1** (by default)
```
name=Burmese name (burmese alphabet)
name:my=Burmese name (latin alphabet) and/or
name:ဗမာ=Burmese name (burmese alphabet)
```

_Example: https://www.openstreetmap.org/relation/50371_ 
```
name=မြန်မာ
name:my=မြန်မာ
```

**Setup 2**
```
name=Burmese name (latin alphabet)
name:my=Burmese name (burmese alphabet) and/or
name:ဗမာ=Burmese name (burmese alphabet)
```

_Example: https://www.openstreetmap.org/relation/6004094_
```
name=Yangon
name:my=ရန်ကုန်
name:ဗမာ=ရန်ကုန်
```

**Setup 3**
```
name=Burmese name (burmese alphabet) + Burmese name (latin alphabet) in bracket
name:my=Burmese name (burmese alphabet) and/or
name:ဗမာ=Burmese name (burmese alphabet)
```

_Example: https://www.openstreetmap.org/relation/5996478_ 
```
name=ကရင်ပြည်နယ် (Kayin)
name:my=ကရင်ပြည်နယ်
```

2. The second option would be that the local community should make a choice over one single setup.
In this case, I think that we should think about a dashboard listing the official decisions (made via a vote in the wiki or just from the _de facto_ data) of such choices. It could help the community to map the proper way while editing a country abroad (such as Myanmar for my, for example). I believe a simple wiki page would solve this problem.

What do you guys think?

**Comment by frodrigo** [comment]
I think you mix two concepts, language and script ("alphabet").

Osmose configure languages per country.
There is already an other setup to match languages and scripts. But I think it out of scope here.
https://github.com/osm-fr/osmose-backend/blob/master/modules/languages.py

>     1. We define country-per-country the different sets of languages.

Osmose already do this in the config.

>        For example in Canada there is 2 different "sets" or "setup".

The config is not the same for all provinces. Default to 'en', but not for Quebec 'fr'.


> Therefore we would have:
> ### In Myanmar country :
> 
> **Setup 1** (by default)
> 
> name=Burmese name (burmese alphabet)
> name:my=Burmese name (latin alphabet) and/or
> name:ဗမာ=Burmese name (burmese alphabet)

There is no such `name:ဗမာ`. Lang should be an iso code.


>     1. The second option would be that the local community should make a choice over one single setup.
>        In this case, I think that we should think about a dashboard listing the official decisions (made via a vote in the wiki or just from the _de facto_ data) of such choices. It could help the community to map the proper way while editing a country abroad (such as Myanmar for my, for example). I believe a simple wiki page would solve this problem.

We already based on de facto. But can fix.


There is also multilingual areas, like Bruxelles, Morocco, Kosovo with dedicated rules.

**Comment by overflorian** [comment]
OK thanks, I understand all the process much more precisely now.
I think there's a need to work on the data itself and not to improve Osmose for now.
Thanks!
