### ISSUE TITLE
Detect full uppercase ways? 

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-backend#89]
I think that way where name is totally in uppercase should be invalid and detected as error by osmose (see [this way](http://www.openstreetmap.org/way/40010954) for instance).

Osmose, at least for France, already detect:
- names' contraction (`St` should be `Saint`)
- missing hypen (`Saint Jean` should be `Saint-Jean`)
- missing first letter uppercase (`rue du moulin` should be `Rue du Moulin`)

Would it make sense to correct `Rue des MOULINS` to `Rue des Moulins` as well?

**Comment by jocelynj** [comment]
We have something that detects if a name is all in uppercase for natural=peak and mountain_pass=yes, or if name contains N°[0-9]. It makes sense to detect if a word is all in uppercase for other cases.

**Comment by bagage** [comment]
I checked a few highways (in a small subset of France only) with overpass turbo using this:
```
<osm-script>
  <query type="way">
    <bbox-query n="51.577" w="0.581" e="3.020" s="50.179" />
        <has-kv k="highway"/>
    <has-kv k="name" regv="\b[A-Z]+\b"/>
  </query>
  <print/>
</osm-script>
```
[Here](http://pastebin.com/MYa3Pmk6) are the results: in my opinion, none of them make sense. There are all either contractions of correct word (ZA instead of Zone Artisanale) or unneeded uppercase (Rue de L'Église instead of Rue de l'Église).
Do you have anything in mind to not use this for `highways`?

**Comment by jocelynj** [comment]
I think your query would be better if it matched 2 or more uppercase characters. Something like: "\b[A-Z]{2,}\b"

**Comment by bagage** [comment]
Indeed, running on a rough bounding box of France using:
```
<osm-script>
  <query type="way">
    <bbox-query n="51.577" w="-5.581" e="10.020" s="41.179" />
        <has-kv k="highway"/>
        <has-kv k="name" regv="\b[A-Z]{3,}\b"/>
  </query>
  <print/>
</osm-script>
```

I get [3224 results](http://pastebin.com/WE4SVbW4).

**Comment by frodrigo** [comment]
OK. To avoid false positives we also need a blacklist : like SNCF, EDF, VTT, USA and detect roman number and/or detect at least four uppercase consecutive letters.

**Comment by frodrigo** [comment]
```
node
  ["name"~"[A-Z]{5,}"]
  ["name"!~"[IVXCDLM]{5,}"]
  ({{bbox}});
out;
```

**Comment by frodrigo** [comment]
So, the result with numerous issues reported :
http://osmose.openstreetmap.fr/fr/errors/?item=5010&class=803

**Comment by bagage** [comment]
Thanks a lot @frodrigo, great work! I'll fix my area and check for any false-positive (maybe here?).

**Comment by bagage** [comment]
Quelques remarques : 

* les bureaux de postes sont quasiment tous systématiquement en MAJUSCULES. Je n'ai pas encore creusé s'il il y a une raison derrière ou si ça a simplement été importé depuis les fichiers de la Poste. En tout cas, ça fait un paquet d'erreurs Osmose
* La vérification est faite pour l'attribut name de tous les objets ; certains bâtiments sont nommés en fonction de l'entité hébergée.. ne risque t-il pas d'y avoir trop de faux positifs ?
* À la manière de l'erreur Toponymie "Majuscule manquante à", serait-il possible à terme de rajouter un bouton fix-edit pour éditer directement depuis Osmose?

Sur ce je continue de tester !

**Comment by frodrigo** [comment]
> les bureaux de postes sont quasiment tous systématiquement en MAJUSCULES. Je n'ai pas encore creusé s'il il y a une raison derrière ou si ça a simplement été importé depuis les fichiers de la Poste. En tout cas, ça fait un paquet d'erreurs Osmose

Yes they come from import

> À la manière de l'erreur Toponymie "Majuscule manquante à", serait-il possible à terme de rajouter un bouton fix-edit pour éditer directement depuis Osmose?

There is "edit"

**Comment by bagage** [comment]
> Yes they come from import

Should they be fixed or left as it?

> There is "edit"

Oh yes! But auto-fix would be valuable since most of the time, fix should be first letter upper-cased + everything else lower-cased, should not it be?

**Comment by frodrigo** [comment]
>> Yes they come from import

> Should they be fixed or left as it?

Yes

>> There is "edit"

> Oh yes! But auto-fix would be valuable since most of the time, fix should be first letter upper-cased + everything else lower-cased, should not it be?

In case we are really almose sure of the fix

**Comment by imagoiq** [comment]
Hi, 

I don't have the full historic and enough knowledge probably to understand the choice of this rule, but I'm wondering if this wouldn't be better to detect only name fully in uppercase with `^[A-Z]{5,}$` regex?

I have some examples where name are constituted with abbreviations but not only: https://www.openstreetmap.org/node/5000671256 (see https://fr.wikipedia.org/wiki/Association_suisse_des_locataires)
https://www.openstreetmap.org/node/8204828804
https://www.openstreetmap.org/node/5019777080
https://www.openstreetmap.org/node/7788408031 (maybe for this one the abbreviation should be an alternative name).

**Comment by frodrigo** [comment]
Look here are typical errors
http://osmose.openstreetmap.fr/en/errors/?country=france*&item=5010&class=803

**Comment by imagoiq** [comment]
I see possibilities are endless and it's better to encompass most errors ! Ok, thanks for your reply. I've read the name page on the wiki and it's seems that for my examples `short_name` will fit the usage.
