### ISSUE TITLE
Way access mismatch relation route=bicycle / cycleway=lane & route=foot / sidewalk=both

### ISSUE THREAD

**Issue by AndrewHain** [osm-fr/osmose-backend#890]
Osmose warns of route access mismatches [between a bicycle route and a road tagged cycleway=lane](http://osmose.openstreetmap.fr/en/error/172ff908-25b8-081a-7bd1-60af689bb2c5) and [between a foot route and a road tagged sidewalk=both](http://osmose.openstreetmap.fr/en/error/2c525c1b-80e9-041e-17ca-17c31c7d3a5b). Both roads have specific spaces for the modes routed.

**Comment by frodrigo** [comment]
source | 30621
-- | --
item | 3240
class | 1


source | 30621
-- | --
item | 3240
class | 2

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_route_access.py#L76-L94

**Comment by frodrigo** [comment]
Update in progress
http://osmose.openstreetmap.fr/en/errors/?item=3240&class=1
