### ISSUE TITLE
France - École non intégrée - Ajouter operator:type en fonction du secteur

### ISSUE THREAD

**Issue by Codain** [osm-fr/osmose-backend#897]
source : 1156
item : 8030
class : 1

Lors de la proposition de création d'une école depuis la base data.gouv.fr il serait bon de préremplir le tag `operator:type` (https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dschool#Op.C3.A9rateur) avec la valeur `public` ou `private` selon le champ `secteur_public_prive` du fichier.

Exemple de proposition de création n'incluant pas ce tag : http://osmose.openstreetmap.fr/fr/error/352bea82-9a4a-e6d9-a4da-e8aa35b01c5e

De même, s'il existe une moulinette qui compare les écoles OSM avec celles du fichier il serait bon de proposer d'ajouter ce champ quand il manque.

**Comment by frodrigo** [comment]
Already the case, only for private
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_school_FR.py#L92

**Comment by Codain** [comment]
Thanks for your answer. Is there a reason why it is not provided for public schools also? Explicite values are of great interest in this case. I can submit a pull request if you provide green light.

**Comment by frodrigo** [comment]
Ok, if public is explicit on the source file.
