### ISSUE TITLE
Inconsistent motor_vehicle values?

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#899]
item: 2130
"Inconsistent motor_vehicle values ('no'!='')"

On one side I have `highway=pedestrian` and on the other side, on the end node I have `barrier=bollard` with `motor_vehicle=no`. I don't know what's "inconsistent" with it.

`highway=pedestrian` has `motor_vehicle=no` by default.

**Comment by frodrigo** [comment]
Do you have a link or ways id?

**Comment by maro-21** [comment]
I marked them as false positives. But I think I explained in detail.

**Comment by frodrigo** [comment]
Do you have the location or the way id? I need more data to help on debug.

**Comment by maro-21** [comment]
It was here:
between [this pedestrian street](https://www.openstreetmap.org/way/21587270) and [this bollard](https://www.openstreetmap.org/node/6184448553).
The tagging is correct because `highway=pedestrian` has `foot=yes` + `motor_vehicle=no` by default.

**Comment by frodrigo** [comment]
The check look for the same `motor_vehicle` value on the pedestrian and the bollard.
`highway=pedestrian` does not mean `motor_vehicle=no` by default, Access with `no` is very restrictive, in most case you can enter at some hours, if your live here, your are deliver men...
