### ISSUE TITLE
proposal analysis on public_transport=stop_position

### ISSUE THREAD

**Issue by Percherie** [osm-fr/osmose-backend#900]
Good morning, sir,

The creation of a public transit system is long and tedious. In my spare time, I have been slowly progressing on the Narbonne network for 3 years now.
I had put a lot of place where the bus stops as an isolated node when they must be placed on the way. I take care of the correction but maybe this kind of mistake is frequent elsewhere?

Osmose does raise an anomaly if highway=bus_stop is on an isolated node (nickel) but as soon as the tag public_transport=stop_position exists, there is no more error. Yet this should be specified. Passenger waiting places can be on an isolated node but not the location where the bus stops: https://wiki.openstreetmap.org/wiki/FR:Key:public_transport

For the stop "Cave Cooperative", the node https://www.openstreetmap.org/node/2466864152 is well on the way and it has the tag "highway=bus_stop". I was expecting to get the fix-edit from Osmose proposes the tag "public_transport=stop_position" instead of "public_transport=platform". 
Ideally osmosis should say "this belongs to the road,
so fix with stop_postion or disconnect from the road for a platform."

For the "La Ricarde" stop, the https://www.openstreetmap.org/node/4498238410 node is isolated but carries tags that need to be attached to the path (stop_position and bus_stop). I was expecting Osmose to ask for it to be reattached OR for the tags to be modified (platform) so that it corresponds to an isolated node. For the moment Osmose doesn't report any error on "public_transport=stop_position" on isolated nodes.
ideally osmose should say "attach the stop_position to the
if it is the location of the vehicle or correct in the platform.
if that's where the vehicle's waiting.

This is a summary of several exchanges on the openstreetmap talk-fr list

Sincerely

**Comment by frodrigo** [comment]
cc @nlehuby

**Comment by nlehuby** [comment]
note to self: https://github.com/Jungle-Bus/transport_mapcss/issues/2

**Comment by nlehuby** [comment]
Thanks @Percherie for these suggestions.

I've started a fix for the first one in MapCSS: https://github.com/Jungle-Bus/transport_mapcss/commit/9f5e7f455538e2595ef234fa607ece83368bfd8f
But I think this kind of rules is not supported by Osmose right @frodrigo  ?

The second one is already handled by both PT Assistant plugin and geometry.mapcss from standard JOSM validation, so it needs to be handled here in Osmose.

**Comment by frodrigo** [comment]
Right, multi-objects operator is not supported is Osmose (`>`).

**Comment by Percherie** [comment]
Thank you for taking into account

@frodigo, does that mean that implementation is not possible?

**Comment by frodrigo** [comment]
It is possible and would be nice to have it. But it requires to implement an other output format of the mapcss compiler to generate SQL in place of python code.

**Comment by frodrigo** [comment]
The other way to have it is to implement it direcly in SQL, duplicating the MapCSS code for Osmose.

**Comment by Percherie** [comment]
Oh, yeah, that's not a harmless modification.

**Comment by frodrigo** [comment]
MapCSS will be fetched on next update. But the rules will be ignored. Cannot do better unless manual dev or major improving mapcss support.
