### ISSUE TITLE
Facebook URLs structure has changed: create a dedicated alert

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osmose-backend#901]
Facebook's pages structure has evolved and that's easy to change it.
Let's suggest to the user to replace "https://fr-fr.facebook.com/" by "https://www.facebook.com/"
Let's replace too "http://fr-fr.facebook.com/" (without the "s") by "https://www.facebook.com/"

For example:
- old URL: https://fr-fr.facebook.com/pages/category/Movie-Theater/DOMONT-CINEMA-122845887790907
- new URL: https://www.facebook.com/pages/category/Movie-Theater/DOMONT-CINEMA-122845887790907

For this example, Facebook achieves the redirection automatically but _sometimes_ it's a blocking 404 so that's an important task.

I guess it would apply to all languages... most common tags using these URLs are "contact:facebook" and "facebook".

**Comment by frodrigo** [comment]
Maybe better to try to do an automated edition than report it on Osmose. Because new contribution will be in new format.

Maybe cc @Marc-marc-marc could be interested.

**Comment by overflorian** [comment]
@PanierAvide maybe ? ;)

**Comment by PanierAvide** [comment]
Is it really necessary to change those URLs, as they are correctly redirect by Facebook even if they have changed ?

**Comment by overflorian** [comment]
yes maybe. from my own experience: I found some URLs correctly redirected and others failing so you might be right.

How should we proceed?
My suggestion: gather all facebook.com URLs in France, automatically find 404's and try to find a reason why these are failing and the others not. Also it could be nice to have a % of the URLs failings to answer your question.
Would you be up for the challenge? Thanks Adrien
