### ISSUE TITLE
Add footway=access_aisle

### ISSUE THREAD

**Issue by blef00fr** [osm-fr/osmose-backend#906]
Hello.
The key [footway=access_aisle](https://wiki.openstreetmap.org/wiki/Tag:footway%3Daccess_aisle) has now the status approved, but it is still considered as an error [(détail link)](https://osmose.openstreetmap.fr/fr/error/73ce5478-fd93-c6fe-74ba-5f30db2df4cb).

**Comment by frodrigo** [comment]
It is from JOSM validator
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/highway.mapcss#L138

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
fixed in JOSM, see https://josm.openstreetmap.de/ticket/19389

**Comment by frodrigo** [comment]
Thank.
Will get in Osmose in next MapCSS update.
