### ISSUE TITLE
code INSEE on admin level 4

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#91]
false positive on insee code, not found in INSEE list
http://osmose.openstreetmap.fr/en/error/5341014364

For Departements, insee code is not checked from
http://www.insee.fr/fr/methodes/nomenclatures/cog/
but
http://www.insee.fr/fr/methodes/default.asp?page=nomenclatures/cog/codes_regions_2016.htm

**Comment by frodrigo** [comment]
Not sure what your are talking about. I have update the INSEE code liste.
