### ISSUE TITLE
Odd behaviour when using Jupyter Notebooks for testing Analyser_Merge Classes

### ISSUE THREAD

**Issue by DavidMoraisFerreira** [osm-fr/osmose-backend#912]
When creating an analyser_merge using the new Jupyter-Feature, changes to a class after it has been created are not taken into account. It seems like whatever class is first defined gets cached somewhere, and updates to this same class are not taken into account.

1. Open the .ipynb file I uploaded here: [analyser_merge_emergency_points_LU.zip](https://github.com/osm-fr/osmose-backend/files/4806515/analyser_merge_emergency_points_LU.zip)

2. Run the cells from top to bottom
3. In the fix-column, you should see an addition for the key "ref".
`{'+': {'ref': 'BB-001', 'highway': 'emergency_..`
4. Now go back into the class definition, and change "ref" to "refX" in static1.
5. Execute the changed class
5. Rerun the analysis
6. - _Expected result:_ instead of "ref" in the result set, we should be seeing "refX".
    `{'+': {'refX': 'BB-001', 'highway': 'emergency_..`
    - _Actual Result:_ The old class definition is still being used. By changing the class name to something else and rerunning the analysis, the "new" refX is added into the result set.
    `{'+': {'ref': 'BB-001', 'highway': 'emergency_..`

Edit: Improved expected/actual result section.

**Comment by frodrigo** [comment]
The mapping of OpenData to OSM tags is cached in database using the class name.

Fix: use the class hash to save the version of the source code in the  database cache.

**Comment by frodrigo** [comment]
Was already using hash version, but ignoring class outside of python source file.
