### ISSUE TITLE
Incomplete string for translation

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#913]
Item 40102.

_Tag landcover=water powinien być zastąpiony tagiem `natural=water` or `waterway=riverbank` or `landuse=reservoir`_

The string for translation on Transifex is only
_The tag `{0}` is deprecated in favour of {1}_
without possibility to translate "or".

**Comment by frodrigo** [comment]
The replaced text come from  https://wiki.openstreetmap.org/wiki/Template:Deprecated_features

Maybe we can just do basic text replacement.

item=4010 plugins/TagFix_Deprecated.py

**Comment by frodrigo** [comment]
No good solution.
Please, reopen if required, with solution.

**Comment by maro-21** [comment]
The solution is to add "or" as a string to translate. Or rephrase the sentence to not use "or".

I'm not able to reopen issues.

This issue is not resolved so it should be open.

**Comment by frodrigo** [comment]
If you want to rephrase do it on the wiki.
