### ISSUE TITLE
New analysis: name together with noname

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#916]
Find features which have conflicting tags: `name` and `noname=yes`.

It can be added to item 4030 incompatible tags.

**Comment by frodrigo** [comment]
Could be done in mapcss.

**Comment by Famlam** [comment]
Doesn't this already exist? I.e.: 
http://osmose.openstreetmap.fr/nl/error/4e14528e-74bd-1d93-002e-8045c3d2b240

**Comment by frodrigo** [comment]
Yes are you right.
