### ISSUE TITLE
New analysis: phone and contact:phone

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#917]
Find features which have both tags: `phone` and `contact:phone`.

The same with other tags `contact:*=*` tags:
- `website` and `contact:website`
- `email` and `contact:email`
- `fax` and `contact:fax`
- or maybe a general rule: `$1` and `contact:$1` because there are many of them: https://wiki.openstreetmap.org/wiki/Key:contact

If the values are the same:
- display message "The same phone value twice. Remove one of the tags."

If the values are different:
- display message "Conflicting values in phone and contact:phone".

It can be added to item 4030 incompatible tags.

**Comment by frodrigo** [comment]
Could be done in mapcss.

**Comment by matthewdarwin** [comment]
I also wonder if there is some country specific behaviour that might be interesting.
In Canada, phone is preferred over contact:phone because that is what ID editor uses. (same for fax, website, etc..)

**Comment by maro-21** [comment]
> I also wonder if there is some country specific behaviour that might be interesting.

There is no consensus as to which tag should be used, so Osmose shouldn't suggest which tag should be left and which removed and should let user decide.

**Comment by frodrigo** [comment]
Only check for different values. Same values are not really an issue.

**Comment by frodrigo** [comment]
Done. Update in progress.

Typo and placeholder message error already fixed.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=3092&class=3097
