### ISSUE TITLE
Simpler messages for 31608

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#918]
Look at the title issues on http://osmose.openstreetmap.fr/pl/errors/?item=3160&class=31608
Could we make them simpler and more understandable for users?
For example _Conflict between lanes number of same sufix ("", forward, backward or both_ways)_ is OK, but something like _(lanes(lanes:*)=2) - (non fullwidth=0) != (lanes(bicycle:lanes)=4) - (non fullwidth=1)_ isn't OK.

I don't know how to fix http://osmose.openstreetmap.fr/pl/error/31824c0e-c8b3-059e-506f-c2d0cb7d1020
Could you help me?

**Comment by frodrigo** [comment]
The subtitle with the value help to figure where the issue should be. The title is already the more generic par.

About 31824c0e-c8b3-059e-506f-c2d0cb7d1020 maybe look at #573

**Comment by frodrigo** [comment]
Please reopen if required.
