### ISSUE TITLE
item=8032, class=4 : confusion entre primaire et élémentaire (school:FR) ainsi qu'entre école maternelle et crèches/haltes-garderies (amenity=kindergarten)

### ISSUE THREAD

**Issue by lagiraudiere** [osm-fr/osmose-backend#919]
osmose propose l'attribut `school:FR=primaire` au lieu de `school:FR=élémentaire` pour les écoles sans maternelle ou avec une maternelle distinct.

Ainsi l'attribut `school:FR=primaire` devrait être réservé aux établissements où l'école élémentaire et l'école maternelle partage la même référence (`ref:UAI`)

De plus les écoles maternelles devraient porter l'attribut `amenity=school` et pas `amenity=kindergarten`. Ce dernier étant à réserver aux crèches, haltes-garderies et jardins d'enfants.

cf. https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dschool

**Comment by frodrigo** [comment]
Please see this https://github.com/osm-fr/osmose-backend/issues/314

cc @deuzeffe @vinber @Bibi56

**Comment by deuzeffe** [comment]
@lagiraudiere Alors, la section https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dschool#Type_d.27.C3.A9cole est certes à jour. Mais, il me semble que la base OD utilisée aussi bien pour le contrôle qualité que pour l'intégration ou la mise à jour des données a encore beaucoup de mal avec cette distinction primaire/maternelle/élémentaire. Et s'il y a 2 types d'école dans un même périmètre, il faut bien y faire figurer les deux... Un exemple de ce tu as observé pour primaire/élémentaire ?

D'autre part, le remplacement de amenity=kindergarten par amenity=school, school:FR=maternelle n'a toujours pas été tranché *huge sight* 

Je ne sais pas si ça répond à ta question.

**Comment by lagiraudiere** [comment]
désolé pou le délai

Dans la mesure où, les maternelles se voient attribuées une référence UAI, il n'y a plus d'établissements strictement "primaires" (même si la dénomination historique reste). D'un point de vue administratif, anciennes écoles primaires sont maintenant des groupes scolaires.
Le problème, est qu'en laissant une école comme "primaire" et en ajoutant, à coté, "son" l'école maternelle, on suggère qu'il y a, non pas 1 mais 2 établissements susceptibles d'accueillir des 3-6 ans.

Dans le fichier https://www.data.gouv.fr/fr/datasets/r/e17a0a8e-54e6-4a53-9262-e087401c0046 l'ID du type d'établissement me semble infiniment plus fiable que le nom. Ainsi, en proposant une valeur conforme au contenu du fichier, on diminuerais fortement le nombre de faux positif.

Aussi je propose :
- que les établissements de type 151 (ELEMENTAIRE) avec mot "maternelle" dans le nom soient étiquetés `school:FR=maternelle`
- que les autres établissements de type 151, 152, 153 et 163  soient étiquetés `school:FR=élémentaire` conformément au type

- que les établissements de type 101 (MATERNELLE) avec mot "élémentaire" dans le nom soient étiquetés `school:FR=élémentaire`
- et enfin que les autres établissements de type 101, 102 et 103  soient étiquetés `school:FR=maternelle`

En tout état de cause, lors de la vérification des valeurs, il ne faudrait pas suggérer la correction "primaire" à la place d'"élémentaire", mais il faudrait accepter les 2 valeurs.

@deuzeffe 
je ne partage pas ton pessimisme sur la qualité des fichiers quant à la distinction primaire/maternelle/élémentaire. En revanche, pour le nom des établissements, c'est le flou artistique : hormis l'appellation "historique" "primaire", le nom contient parfois un descriptif long comme un vrai roman plutôt que le nom réél...(cf. les lycées qui mélangent enseignement général et technique)

@deuzeffe 
>"s'il y a 2 types d'école dans un même périmètre, il faut bien y faire figurer les deux..."

C'est pour ça qu'il faut utiliser "maternelle"+"élémentaire" et pas "maternelle"+"primaire"

**Comment by lagiraudiere** [comment]
@deuzeffe
concernant le remplacement de 
	`amenity=kindergarten` + `school:FR=maternelle`
par 
	`amenity=school` + `school:FR=maternelle`
le wiki est pourtant clair.
Sur la page 
	[https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dschool](https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dschool) au chapitre "Type d'école"
mais aussi
	https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dkindergarten
il est indiqué que 
	"les établissements proposant une éducation formelle (à partir de l'école maternelle en France), utilisez l'attribut amenity=school."
De plus la page https://wiki.openstreetmap.org/wiki/FR:Key:kindergarten:FR recensant les types d'établissements, ne fais pas référence aux écoles maternelles.

Il est dommage de les contrôles mis en place ne soient pas conformes au wiki.

**Comment by frodrigo** [comment]
On peut donc checher à signamer qu'il ne faut pas de school:FR=maternelle avec une ref UAI ?

**Comment by frodrigo** [comment]
> Il est dommage de les contrôles mis en place ne soient pas conformes au wiki.

Donner une liste claire de ce qu'il faut changer. Une nouvelle issue par changement.

**Comment by lagiraudiere** [comment]
> On peut donc checher à signamer qu'il ne faut pas de school:FR=maternelle avec une ref UAI ?

bien sûr que si ! 
le problème n'est pas que les maternelles portent leur propre référence UAI, le problème est que, lorsqu'elle en ont une, l'école du CP au CM2 à laquelle elle est jumelée n'est pas une école "primaire", mais une école "élémentaire".

**Comment by frodrigo** [comment]
Je me suis trompé, je voulais signaler school:FR=primaire avec une ref UAI , c'est bien à signaler ?

**Comment by lagiraudiere** [comment]
> > Il est dommage de les contrôles mis en place ne soient pas conformes au wiki.
> 
> Donner une liste claire de ce qu'il faut changer. Une nouvelle issue par changement.

pour les écoles maternelle (qui portent l'étiquette `school:FR=maternelle` ), il faudrait remplacer `kindergarten` par `school` pour la valeur de l'étiquette `amenity`

**Comment by lagiraudiere** [comment]
> Je me suis trompé, je voulais signaler school:FR=primaire avec une ref UAI , c'est bien à signaler ?

Je ne suis pas certain de ce que tu entends par là...
les écoles maternelles et élémentaires étant quasiment toutes distinctes, on ne devrait plus trouver d'écoles "primaires" (ou seulement à la marge) 
mais school:FR=primaire n'est pas incompatible avec une ref UAI
un établissement `school:FR=primaire` est incompatible avec un autre etablissement 'school:FR=maternelle' ou `school:FR=élémentaire` dans un même `landuse=school`

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/issues/941

**Comment by Stefal** [comment]
Coucou,
Je vois toujours des suggestions de la part d'Osmose pour basculer des écoles élémentaires de `school:FR=élémentaire` à `school:FR=primaire`. Ca ne devrait pas être le cas.
Exemple : http://osmose.openstreetmap.fr/fr/error/814032f2-f433-b042-d3d4-1de8cf18dffe

![image](https://user-images.githubusercontent.com/8255984/103284293-1f7ec800-49db-11eb-8a57-9c850cca4937.png)
