### ISSUE TITLE
 Test Soundex too violent?

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-backend#92]
It seems that Test Soundex is triggering errors whenever it does not know a word. See [Impasse des Balmas](http://osmose.openstreetmap.fr/fr/map/#layer=Mapnik&zoom=18&lat=45.070792&lon=5.133243) or [Chemin de Belle Vue](http://osmose.openstreetmap.fr/fr/map/#layer=Mapnik&zoom=18&lat=45.13901&lon=5.128002) where both times, exact name is used but osmose invalidly suggests a "real"/"correct" name instead.
These invalid suggestions make me wonder if I should trust osmose much. Could it check if the name matches with BANO and/or cadastre first before suggesting another name?

**Comment by frodrigo** [comment]
Soundex test is build as an autonomous test. It checks for similar names in the area (country as definited in osmose).

The soundex test have no white-list, but you can make a pull resquest with improvement. Look at `analyser_osmosis_soundex.py`.
