### ISSUE TITLE
Mapillary street signs: recognise junction=circular

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#920]
junction=circular can (should) be used on roundabouts where the traffic on the roundabout doesn't have the right of way. In (at least the Netherlands) such `junction=circular` structures have the same traffic signs as `junction=roundabout` "circular roads".

Famous example in The Netherlands is the [Keizer Karelplein](https://www.mapillary.com/app/?lat=51.842060375&lng=5.860718020833334&z=17&focus=photo&dateFrom=2019-08-01&pKey=1mhVlTvr4e9HdkLetyhiPg), but that same city contains more of these ([example](https://www.mapillary.com/app/?lat=51.824649621035924&lng=5.789259823252415&z=17&dateFrom=2019-08-01&x=0.4974370020752761&y=0.7802798025835962&zoom=1.9145312199692242&pKey=NkdpYb7xn6ga8_4G1oXU5w&focus=photo)).

Example false positive issue detected by Osmose: http://osmose.openstreetmap.fr/nl/error/523319e1-46aa-62e4-a84f-48dac81e109e
(On this way, once the traffic signals go green, the traffic on the roundabout must stop)

Solution: add [to the detected objects]( https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json#L815 )
```
      {
        "highway": null,
        "junction": "circular"
      },
```

**Comment by frodrigo** [comment]
Sound good, please make a pull request to add this.
