### ISSUE TITLE
False positive: Invalid Opening Hours

### ISSUE THREAD

**Issue by AnkEric** [osm-fr/osmose-backend#925]
Invalid Opening Hours:
Osmose does not accept Date format in opening_hours: "mmm dd".
Osmose will interpreted "mmm dd" as: "mmm hh:mm".
Evaluation_tool and JOSM will accept both formats: "mmm d" and "mmm dd".
Evaluation_tool is suggesting by "Warnings solved": "mmm dd" as "best practice".

Examples:

Me: opening_hours = "Jul 01-Mar 14"
Osmose: opening_hours = "Jul 1-Mar 14:00"

Me: opening_hours = "Jan 01 off"
Osmose: opening_hours = "Jan 01:00 off"

https://openingh.openstreetmap.de/evaluation_tool/

Me: opening_hours = "Jan 1 off"
Warnings solved: opening_hours = "Jan 01 off"

**Comment by dfaure-kdab** [comment]
Same as https://github.com/osm-fr/osmose-backend/issues/555
