### ISSUE TITLE
'Name with uppercase' is mostly fasle positive in Japan

### ISSUE THREAD

**Issue by higa4** [osm-fr/osmose-backend#927]
'Name with uppercase' is commonly seen in Japan. Is it possible to exclude 'Name with uppercase' check in Japan? Most of the red marker below shows this issue and they are all false positive. 
![](https://i.imgur.com/iUvqLy1.png)
http://osmose.openstreetmap.fr/ja/map/#zoom=16&lat=35.70785&lon=139.77729&item=xxxx&level=1&tags=&fixable=

**Comment by frodrigo** [comment]
We can disable it for Japan.
We can also change the limit of Upper case number before raising issue for JP.
You does not use latin lower case for name in JP ?
There is sone rule on the wiki or else where ?

**Comment by higa4** [comment]
Although there's not a clear rule, but there's a naming sample of franchise shops. Please see the 'name:en' column below:
https://wiki.openstreetmap.org/wiki/JA:Naming_sample

**Comment by higa4** [comment]
There is not a clear rule for using Upper case in Japan. So I think only disabling this check is enough for us Japanese. We see Upper case something free decorative expression.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?country=japan*&item=5010&class=803
