### ISSUE TITLE
addr:housenumber may start with a number

### ISSUE THREAD

**Issue by pl71** [osm-fr/osmose-backend#93]
street numbers "2060" Class 10 "addr:housenumber does not start by a number"

Actually this is permitted for many countries - Russia and some in Eastern Europe.
wiki - http://wiki.openstreetmap.org/wiki/Addresses

**Comment by frodrigo** [comment]
Yes, we already seen some trouble with that. Please can you set up a list of country where we need to disable this test ?

**Comment by frodrigo** [comment]
Setup for Russia only (but today is not in Osmose coverage), please provide a list of countries.

**Comment by pl71** [comment]
Add Bulgaria to this list.
