### ISSUE TITLE
False positive highway=junction, junction=*

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#930]
item | 2080 
-- | --
class | 20800

https://www.openstreetmap.org/way/156963722 has 

highway | primary
-- | --
junction | roundabout

It seems to need now `highway=junction` but it doesn't match the wiki saying `highway=*`

**Comment by gileri** [comment]
I addressed this issue in #928

**Comment by Bibi56** [comment]
Thanks but:
https://github.com/osm-fr/osmose-backend/pull/928/checks?check_run_id=889815120 :-(

**Comment by gileri** [comment]
It's is a [pre-existing error](https://travis-ci.com/github/osm-fr/osmose-backend/jobs/362567175) unrelated to #928. I don't think that will be preventing its merge.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=2080&class=20800
