### ISSUE TITLE
Speed-up correction for "descriptive name"

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#932]
item | class
-- | --
9010             inutile | 9010003

"descriptive name" suggests to remove the name=*.
Fine but usually we just need to say "OK, do it".
In lists like http://osmose.openstreetmap.fr/fr/errors/?source=407718&item=9010&class=9010003
We could have a button ❎ to just delete the name tag in the given object, without the need to just to an editor.

 ✘  | ✔  |  ❎
-- | -- | --

Other optimization: enable the multiple selection (in 2 clicks with shift) to be able to apply to a bunch of items. As we can sort by names, some are obviously descriptive names, some may require more attention.

**Comment by frodrigo** [comment]
It comes from JOSM validator.

Unlike this rule https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/unnecessary.mapcss#L130
This rule does not suggest to remove the `name` tag https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/unnecessary.mapcss#L160

cc @Klumbumbus

**Comment by Klumbumbus** [comment]
For cases with possible information loss there is no autofix.
E.g. for a object with amenity=school + name=school + building=yes, you should manually check if it should be building=school.

**Comment by Bibi56** [comment]
@Klumbumbus, I see no possible information loss in your case. `name=school` means `amenity=school`. If the school looks like a school, yes it's a possibility. But `name=school`doesn't imply it.
`amenity=school` may suggest to add `building=school` but IMHO it's a completely different topic.

**Comment by Klumbumbus** [comment]
Yes, my example was wrong.
For name=school _with_ amenity=school the autofix should be available.
For name=school _without_ amenity=school the autofix should _not_ be available.

I just noticed possible problems with the JOSM validator rules. I'll look into that.

**Comment by Klumbumbus** [comment]
I fine tuned the rules a bit in https://josm.openstreetmap.de/changeset/16858. However that means there are now more cases witout autofix.
But anyway I think thats not related as what was asked in the issue ("We could have a button ❎ to just delete the name tag") would need to be handled by osmose. E.g. https://www.openstreetmap.org/node/6325595727 which is in the linked list has an autofix in JOSM.

**Comment by frodrigo** [comment]
The auto-fix in Osmose is linked to the mapcss `fixRemove`.

**Comment by Bibi56** [comment]
@frodrigo the idea was (and is) to speed-up the correction. On the [given example](https://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=47.976986&lon=-3.281109&item=xxxx&level=1%2C2%2C3&tags=&fixable=). I can select the item, click on "fix-edit" then "Done". 3 clicks.
As I see what will be done (removal of `name` tag) I can save a click here (adding a "fix it" link or a ❎ button). Just 2 clicks. Could even be a 1 click in a list view.

**Comment by frodrigo** [comment]
Ok. I miss read the initial issue.
Please can you re-open on the github osmose frontend.

**Comment by Bibi56** [comment]
Sure. My bad, of course it's a front end issue.
