### ISSUE TITLE
Problem with School without ref:UAI

### ISSUE THREAD

**Issue by gnafron** [osm-fr/osmose-backend#933]
Hello,

Several analyses seem to be broken and return false positives, all related with data integration.
For example :
- [School without ref:UAI](https://osmose.openstreetmap.fr/fr/error/8ca5ea67-92ad-b526-8a34-c8f253df6728) although the ref is [here](https://www.openstreetmap.org/way/288699187) and [correct](https://www.education.gouv.fr/annuaire/35-ille-et-vilaine/pleurtuit/etab/ecole-maternelle-publique-joseph-launay.html) (see the ref in the email address)
- [Non-integrated shop](https://osmose.openstreetmap.fr/fr/error/982b6e94-846a-66ab-e159-38a46542399c) although it is [here](https://www.openstreetmap.org/node/1306555571)

I don’t know if other analyses are impacted.

**Comment by frodrigo** [comment]
If it is OK in OSM, just mark Osmose issues as false positive. OpenData are not perfect.

**Comment by gnafron** [comment]
I meant there was an abnormal amount of false positives.
On [this zone](http://osmose.openstreetmap.fr/fr/map/#zoom=13&lat=48.6031&lon=-2.0904&item=7070&level=1%2C2%2C3&tags=&fixable=), which is my usual mapping zone, all schools have a ref:UAI which is correct, and these reports did not appear before. That is why I suppose that there is something broken in the analysis, and not in the open data.

**Comment by frodrigo** [comment]
Ok, something is broken with school: https://osmose.openstreetmap.fr/en/errors/graph.png?item=7070&class=2

The shop look ok.
https://osmose.openstreetmap.fr/en/errors/graph.png?item=8310&class=4702226

**Comment by laurentriffard** [comment]
Same problem with french pharmacies and ref:FR:FINESS ? 
Example : http://osmose.openstreetmap.fr/fr/error/75c2ba70-418e-58bd-cabf-68de438051eb
graph : https://osmose.openstreetmap.fr/en/errors/graph.png?item=7150&class=2

**Comment by frodrigo** [comment]
Not the same issue, the graph have not the same pattern. ref:FR:FINESS look like issue when the server for french opendata reboot. Still not found the issue with this server.

**Comment by frodrigo** [comment]
Same thing as finess, but was blocked by an other issue.
https://osmose.openstreetmap.fr/en/errors/?item=7070&class=2
