### ISSUE TITLE
Culverts falsely marked

### ISSUE THREAD

**Issue by 501Ghost** [osm-fr/osmose-backend#934]
Hello Osmose developers,

Today I noticed a small issue in Osmose. I looked at a culvert with the tags tunnel=culvert, waterway=ditch, layer=-1. Osmose said that waterways are not supposed to have a layer tag, but according to [the wiki page on culverts](https://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dculvert) a layer tag should be correct in this case. 

Kind regards,

Casper

P.s. My apologies if I've overlooked some information that could be useful to you. I'm new around here ;)

**Comment by frodrigo** [comment]
Please can you point at the issues, a link or an item, class ids. There is throusand of issue kinds in Osmose.

**Comment by 501Ghost** [comment]
Of course. Let me find that for you.

http://osmose.openstreetmap.fr/en/error/62d7b15a-b522-64b8-88f5-fe246648d0f6
class 30327

https://www.openstreetmap.org/way/808554202

Is this information useful?

**Comment by danfos** [comment]
@501Ghost: The problem with https://www.openstreetmap.org/way/808554202 is that it not have layer=-1, but level=-1.

That is not correct, level is used for buildings, the fix should be that change level into layer.

**Comment by 501Ghost** [comment]
> @501Ghost: The problem with https://www.openstreetmap.org/way/808554202 is that it not have layer=-1, but level=-1.
> 
> That is not correct, level is used for buildings, the fix should be that change level into layer.

I see. Hadn't even noticed that, so thank you for pointing it out. I'll get it fixed.
