### ISSUE TITLE
Untranslatable strings for 8300 and 8360

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#935]
- Unmapped bicycle parking
- Unmapped surveillance camera
- Unmapped fire hydrant
- Unmapped traffic light
- Unmapped phone booth
- Unmapped drinking water
- ... and a lot from 8300

There is only one string, `Unmapped {0}`, for all of them.

**Comment by frodrigo** [comment]
The parameter of `Unmapped {0}` will still be in english after translation, if come from configuration file.

I does not see the issue with `Observed between {0} and {1}` (and `Observed on {0}`). Please can you explain or suggest something?

**Comment by maro-21** [comment]
These ones come from Mappilary issues.

**Comment by frodrigo** [comment]
Yes, I know. But what do you suggest?

**Comment by maro-21** [comment]
Add strings for translation.

**Comment by frodrigo** [comment]
I ask you suggestion of an english replacement string for `Observed between 2018-10-14 and 2019-08-30`.

**Comment by maro-21** [comment]
The one you wrote before, "Observed between {0} and {1}" looks ok :)

**Comment by frodrigo** [comment]
Ok, so nothing to change.

**Comment by maro-21** [comment]
So why are you closing an unresolved issue again?
If you allow your software to be available in many languages in should be fully available.

Translating only part of a sentence doesn't make sense. If I translate "unmapped" to "niezmapowane" there will be "niezmapowane traffic light" which doesn't make sense! And it won't help someone who doesn't understand English. What's the problem with adding a few more strings to translate?

**Comment by frodrigo** [comment]
`Unmapped {0}`, the `{0}` part is not translatable and you have no issue with `Observed between {0} and {1}`. So nothing left.

**Comment by bagage** [comment]
`{0}` is a dynamic value that cannot be translated easily (you would need to extract all possible values from `merge_data/mapillary-traffic-signs.mapping.json` and related files).

To me there is only 2 solutions:

1. Leave the whole string untranslated. Always use English.
2. Slightly change the translation to `Unmapped *{0}*` (notice the italic for the untranslated term), so for instance it would be `niezmapowane *traffic light*`. Would it sound better to you @maro-21?

**Comment by maro-21** [comment]
> the {0} part is not translatable

Yes, it is. That's what I made this issue for!

> you would need to extract all possible values from merge_data/mapillary-traffic-signs.mapping.json

So let's extract them.

They should be extracted together with "Unmapped" because in my language translating this word depends on what is the gender of the next word. So
`Unmapped bicycle parking` would be `Niezmapowany parking dla rowerów`
but `Unampped surveillance camera` would be `Niezmapowana kamera monitoringu`.

>     1. Leave the whole string untranslated. Always use English.

This isn't a solution becasue if the software is possible to translate into another language it should be possible to translate it in full.
If someone doesn't know how to fix the issue, or if it's boring or something, the issue should remain open until someone takes care of it.
Would you like to read un livre which is seulement parly translated into français?

>     2. Slightly change the translation to **Unmapped _{0}_** (notice the italic for the untranslated term)

It's not possible to use italic in either Osmose and iD.
iD users could think that translators didn't know how to translate "traffic light".

![Osmose_iD](https://user-images.githubusercontent.com/57260466/90011659-43e33d80-dca2-11ea-993f-f71e16ece475.png)

**Comment by SilentSpike** [comment]
@maro-21 Osmose strings support markdown so italics are possible (generally I would recommend to keep formatting symbols out of the strings for translation by inserting them in the code). However, yes, it may be better to just have strings for each case. Updating the original (English) strings needs to be done in the code.

**Comment by frodrigo** [comment]
String for some json (mapillary) are now translatable.

**Comment by maro-21** [comment]
Thanks Frédéric! :)

Are there any missing?
Looks like almost all have been added except "bench"
![Osmose8360](https://user-images.githubusercontent.com/57260466/91903857-3c60f400-eca4-11ea-8de9-76d016ce1f43.png)

**Comment by frodrigo** [comment]
The bench are no more proposed, it is a removed part. Should be delete from frontend database.

**Comment by frodrigo** [comment]
8360/1 deleted

**Comment by maro-21** [comment]
There are still two untranslatable :P
30: `highway=give_way Traffic signs for yield observed around but not associated tags`
31: `highway=stop Traffic signs for stop observed around but not associated tags`

![Osmose](https://user-images.githubusercontent.com/57260466/92417891-fd7be400-f164-11ea-9e26-37144cea3d51.png)

**Comment by frodrigo** [comment]
Also deleted.
