### ISSUE TITLE
8370/120 GeoDAE tag name is no a name

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#936]
The name tag of the merge are not name, at best local ref, but mostly description.

cc @PanierAvide

**Comment by cquest** [comment]
ref:FR:SIREN est ambigu, car ça décrit une personne morale à la source de l'info

source:FR:SIREN serait plus cohérent.

**Comment by frodrigo** [comment]
Je pense que level=0 peut vouloir dire non rensigné.

**Comment by PanierAvide** [comment]
J'aurais plutôt indiqué `operator:ref:FR:SIREN` puisqu'il s'agit bien du code SIREN du gestionnaire de l'ERP (et fait le lien avec le tag `operator` également renseigné).

Pour name/ref/description, le tag `name` est plus fréquemment associé que `ref`, même si on est d'accord que le nom est ici très descriptif (mais c'est le cas aussi pour les DAE déjà dans OSM). Après pas de soucis pour le changer, mais ce ne sera pas raccord avec les autres pays. À discuter au-delà peut-être de GitHub et avec la communauté internationale ?

Je ne pense pas qu'il faille modifier `level`, les données à priori et le code font bien la distinction entre valeur "0" et pas de valeur renseignée.

**Comment by frodrigo** [comment]
Comme je m'en doutais, je suis allée voir (un seul) level=0, pour une salle de sport que je savais à l'étage, et le DAE, n'était bien pas dans le hall au rez-de-chaussé.

**Comment by PanierAvide** [comment]
Donc toutes les valeurs différentes de "0" peuvent être conservées, et on ignore "0" ? Ou marquer dans la doc `trap` de bien vérifier l'étage ?

**Comment by PanierAvide** [comment]
Fixed by #940, can be closed too.
