### ISSUE TITLE
item=8032, class=4 kindergarten -> school

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#941]
Report from https://github.com/osm-fr/osmose-backend/issues/919#issuecomment-669115922

pour les écoles maternelle (qui portent l'étiquette school:FR=maternelle ), il faudrait remplacer kindergarten par school pour la valeur de l'étiquette amenity

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_school_FR.py#L89

cc @lagiraudiere @deuzeffe

**Comment by vinber** [comment]
pour moi il y a 2 choses :
- un changement de tag et donc une nouvelle analyse "mauvais tag" ou une modification en masse #982 ?
- un rapprochement de la base de l'éducation nationale qui doit également prendre en compte ce changement
