### ISSUE TITLE
Rule josm for aeroway hangar vs building barn

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#942]
Hi,
we can add an osmose class to this new rule :
https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules?action=diff&version=53

but i don't know which one

Regards.

**Comment by frodrigo** [comment]
It does not matter, this expression (`⊉`) is not supported by Osmose
```css
area:closed2[aeroway] ⊉ way[building=hangar][!aeroway][inside("FR")]
```
