### ISSUE TITLE
Allow maxspeed=implicit

### ISSUE THREAD

**Issue by FF-11** [osm-fr/osmose-backend#944]
Item:

source | 24931
-- | --
item | 3091
class | 3091
lat lon | 49.9999542 9.0447691
link | https://osmose.openstreetmap.fr/en/error/1366c953-064f-deba-dc11-9c3109e4770b

This is reported because a sign has the tag `maxspeed=implicit`. However, this is allowed according to https://wiki.openstreetmap.org/wiki/Tag:maxspeed=implicit.

**Comment by frodrigo** [comment]
This wiki page look suspicious for me.

Look at https://wiki.openstreetmap.org/wiki/Key:maxspeed "implicit"
