### ISSUE TITLE
Broken highway level continuity for highway=tertiary ending on highway=residential

### ISSUE THREAD

**Issue by danfos** [osm-fr/osmose-backend#945]
I had a look at http://osmose.openstreetmap.fr/en/errors/?source=4696&item=1120&class=3 and I see that quite some Warnings are generated for highway=tertiary with the node being the end of that highway=tertiary connected to one or multiple ways marked as highway=residential

For an example, see http://osmose.openstreetmap.fr/en/error/5f1f0825-1083-cc1a-67e3-9fdb8f84da40

As far as I know this is not wrong, so is the code making an error for this?

**Comment by frodrigo** [comment]
It is because Osmose query found an other "unconnected" tertiary close, as explained in the help panel.

http://osmose.openstreetmap.fr/en/map/#item=1120&zoom=16&lat=51.85576&lon=4.52679&level=1%2C2%2C3&tags=&fixable=

It can be false positive, especially in such suburb.

**Comment by danfos** [comment]
I had a good look but I do not see what is meant with _**an other "unconnected" tertiary close**_

As for the Help panel:

![Screenshot_20200815_140430](https://user-images.githubusercontent.com/8472097/90311914-493dc380-df00-11ea-8452-77b55fb27d2b.png)

The picture is for a highway=secondary becoming residential for which the warning makes sense, the text is for higway=tertiary but it does not explain me what is the problem.

**Comment by frodrigo** [comment]
On my last link. You can see the two markers. You have tertiary, but it the same same.
Here it is a false positive as the two are not connected.

**Comment by danfos** [comment]
Okay, understood, I am not a native English speaker and I guess you also not but I should have read:

_an other "unconnected" tertiary close **by**._

Let me mark these problem as False positive.

Thanks!
