### ISSUE TITLE
item=3050 class=30501 allow dot char '.' in tag name

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-backend#948]
The `.` char is sometimes used for the `ref` key to reference a website source. 

For instance French churches may use https://clochers.org website and use `ref:clochers.org=xxx` tag to link with it. 

It should be OK to allow that character or at least decrease the severity of such issues.

**Comment by frodrigo** [comment]
The solution is the decrease the level for some chars.

**Comment by 1ec5** [comment]
The [`hazmat`](https://wiki.openstreetmap.org/wiki/Key:hazmat) tagging scheme is also affected. `hazmat:*` subkeys identify hazmat classes by their standard alphanumerics. In the United States, which restricts vehicles based on [GHS placards](https://en.wikipedia.org/wiki/GHS_hazard_pictograms#Transport_pictograms), several of the classes have divisions containing periods, hence [`hazmat:4.3`](https://wiki.openstreetmap.org/wiki/Item:Q21442).

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=3050

Split class 3050 in 3050 and 30502.

**Comment by frodrigo** [comment]
Actually we do it.
