### ISSUE TITLE
Comprare with alt_name too?

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#949]
type | value
-- | --
item | 2060             
class  |  9

[Here](https://osmose.openstreetmap.fr/fr/error/563e930c-fd19-cceb-9a0d-60781794f3f1), _Pavé Jean-Marie Leblanc_ is the alt_name of _Carrefour de l’Arbre_, so IMHO `addr:street=Pavé Jean-Marie Leblanc` should be valid.

Or should we consider it on individual basis as false positive?

BTW, https://www.openstreetmap.org/node/766682466 is a POA and a POI at the same time.

**Comment by frodrigo** [comment]
Already asked in an other issue.
The global idea is to facilitate reuse when relation is not used, the name should be easy to match, same name, same tag...
