### ISSUE TITLE
Roundabouts in the UK tagged direction=clockwise should not be considered in error.

### ISSUE THREAD

**Issue by Yorkshire-Jack** [osm-fr/osmose-backend#95]
Many road junctions in the UK are tagged:

`direction = clockwise`
`highway = mini_roundabout`

Osmose marks this as an error, with the following description:

> Reverse roundabout
> Mini roundabout direction in this country is "clockwise" by default, useless direction tag

However, the OSM wiki [states](http://wiki.openstreetmap.org/wiki/Road_signs_in_the_United_Kingdom):

> Add highway=mini_roundabout to the intersection node where the mini roundabout is located. Also add direction=clockwise.

And in response to a [question on osm help](https://help.openstreetmap.org/questions/47988/mini-roundabout-direction-needed-or-not-osmose-vs-wiki) the consensus seems to be that the direction tag should be present, or at least it is not an error if it is.

**Comment by frodrigo** [comment]
You are right, we should not ask to remove explicit direction tag.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=1050&class=1050&subclass=10001
Osmose-QA Issues removed
