### ISSUE TITLE
Add https checker

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-backend#950]
Hi,

I found this tool which automatically checks osm website tags to see if they can be converted to https ones if they haven't already.
https://gitlab.com/b-jazz/https_all_the_things
Something like this seems useful for Osmose as well

Cheers

**Comment by frodrigo** [comment]
Can be done, with a cache in from of it.

**Comment by matkoniecz** [comment]
It can be done with bot (and there is/was an active one with edit permission) - and even there it was barely worth spending time on it.

Wasting time of human editors on that seems pointless, if implemented it should be disabled by default.

**Comment by matkoniecz** [comment]
Is there a point in duplicating https bot that is already checking everything anyway? And asking humans to do something that will be soon done by a bot anyway?

**Comment by thibaultmol** [comment]
I guess I just saw it from the view that b-jazz bot is going trough some random order. And it's manual supposedly.
I looked on osmcha and can't find a single edit by it in Belgium. I went trough a lot urls at some point and they all could have been converted if the bot had actually gone over them there. 
So guess it's just a question of having that bot be run over more areas

**Comment by matkoniecz** [comment]
If there are missing edits in Belgium then I would start from contacting bot operator. Fixing bug in bot (if present) can save thousands of manual edits.
