### ISSUE TITLE
Name suggestion index takes a while to update?

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-backend#952]
Hi,

For some reason I thought that the NSI in osmose got updated every day or atleast every time it ran.
But it seems like my adjustment of the Bristol shoe store that got accepted 3 days ago, still doesn't show up in osmose for some reason:

https://github.com/osmlab/name-suggestion-index/pull/4068

![Screenshot_20200816_203609](https://user-images.githubusercontent.com/1010226/90341458-20045c80-e000-11ea-953b-709c3d993a19.png)

http://osmose.openstreetmap.fr/en/error/1d4ccf01-996e-140c-6b7d-114662501e7a

Am I being impatient, or is it having troubling updating to the latest nsi export?

**Comment by frodrigo** [comment]
Osmose analyzers run every day. But external data is cached and updated
automatically every 60 days.

**Comment by thibaultmol** [comment]
I feel like that's a bit high for something like the NSI, no?
7 days I would understand (would still be a bit long).
But I can just imagine people making changes to NSI to then reflect in
changes on suggestions on osmose, and then being confused why it takes so
long to update.

Cheers,
