### ISSUE TITLE
National bank of canada errors shows up in Germany

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-backend#953]
Hi,

Someone on the osm Discord server pointed out an error that osmose generated (already marked as false positive)n
where a 'brand in name' error appeared on this node https://www.openstreetmap.org/node/289980683 
for the National bank of canada, yet the geojson file that's used for it's region on the Name Suggestion index seems correct: https://ideditor.github.io/location-conflation/?locationSet=%7B%22include%22%3A%5B%22quebec.geojson%22%5D%7D&referrer=nsi

page in NSI: https://nsi.guide/index.html?k=amenity&v=bank#Banque%20Nationale

Does the osmose analyze not work with .geojson files yet? or is there some other problem happening?

Cheers,

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/4af11a1846c96a0ddd2e5fad28f6858c1bed3a0c/plugins/TagFix_Brand.py

cc @nlehuby 

We need to implement polygon support or exclude rules with polygon. Better if we can use country / area code than polygon.

**Comment by frodrigo** [comment]
https://github.com/osmlab/name-suggestion-index/blob/main/CONTRIBUTING.md#locationset

Only code in  ISO 3166-1 of size 2 can match Osmose code implementation. Nevertheless it could a satisfiant partial implementation.

**Comment by frodrigo** [comment]
@thibaultmol not sure what is the issue here. I see the code already check for the country and seem correct setting on NSI side also
https://nsi.guide/index.html?k=amenity&v=bank#nationalbank-d90ecd
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Brand.py#L60

**Comment by frodrigo** [comment]
Finally found two issues in the code #988.

**Comment by frodrigo** [comment]
Should be ok, but reopen if not.
