### ISSUE TITLE
update omose plugin for josm france specific rules 

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#954]
Hi,
josm'france specific rules had been modified but 
this rule is still present :
https://github.com/osm-fr/osmose-backend/blob/748bd809d5b9c919d558ac1562c08db44a562ee2/plugins/Josm_FranceSpecificRules.py#L200

**Comment by frodrigo** [comment]
Assert have to be fixed first
>       self.check_err(n.node(data, {u'highway': u'motorway_junction', u'name': u'Trifouilly-lès-Oies'}), expected={'class': 9019003, 'subclass': 1394767972})

```css
node[highway=motorway_junction][name][inside("FR")] {
    throwWarning: "Unusually named motorway_junction; use of 'name=*' for the exit destination?";
    fixRemove: "name";
    suggestAlternative: "'destination=*' tag on the exiting 'highway=*_link'";
    assertMatch: "node highway=motorway_junction name=Trifouilly-lès-Oies";
}
```

**Comment by frodrigo** [comment]
> Assert have to be fixed first

Fixed

**Comment by frodrigo** [comment]
Update in progress
