### ISSUE TITLE
"Highway above ground and no bridge" should offer an alternative fix

### ISSUE THREAD

**Issue by savissimo** [osm-fr/osmose-backend#957]
Taking [this marker](https://osmose.openstreetmap.fr/en/error/14643bed-4279-bea4-6e46-5a650a075ee9) as an example, the fix of the "No bridge" error is not always to add bridge=yes: in cases like this one, you should actually remove the layer=* tag. 

Can an alternate fix be provided?

**Comment by frodrigo** [comment]
The marker is gone, so I cannot see your case.

Alternative fix can be provided.

**Comment by savissimo** [comment]
Sorry about the marker: I set it as fixed, I didn't know it would be deleted. The marker referred to this way: https://www.openstreetmap.org/way/191257755#map=19/45.29699/8.36525

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Layer.py#L60-L64

It more subtile. It depends of the number of the nodes of the way.
