### ISSUE TITLE
osmose_config corrections

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#96]
+ pour "wallise et futuna" et polynesie :
les ".pbf" sont dans "extracts/ocenia"
les ".poly" sont dans "polygons/south-america/"

donc il faut spécifier la bonne url 
ligne 283 et 285
http://download.openstreetmap.fr/polygons/south-america/...

+ pour l'italie

ligne 687 
"gfoss_geodata/osm/output_osm_regioni/"
il faut enlever le "/" a la fin (il est ajouté ligne 213 dans la class defaut_coutnry)

+ pour l'italie
pour toutes les regions l'url du poly est invalide 
elles sont sur https://github.com/lucadelu/ital.img/tree/master/poly

**Comment by jocelynj** [comment]
Pour wallis et futuna et polynesie, les extracts sont à la fois dans oceania et south-america en fait - j'ai du déplacer en faisant un lien symbolique il y a quelque temps. Je corrige de suite, et pour l'italie aussi.

Pour info, l'url du .poly n'est pas utilisé directement par osmose. À moins que tu n'ais vu un effet de bord ?

**Comment by didier2020** [comment]
je voulais juste recuperer tous les poly pour voir précisement 
dans josm les zones non couvertes par osmose.
