### ISSUE TITLE
Underground pipeline

### ISSUE THREAD

**Issue by hungerburg** [osm-fr/osmose-backend#961]
An underground waterway=pressurised does not require a tunnel, at least if it is usage=penstock and man_made=pipeline, below minor issue seems to me a false positive

https://osmose.openstreetmap.fr/en/error/f55ce74a-ce5c-67c9-430f-1dabcd537c71

It is rare, just for completeness

P.

**Comment by frodrigo** [comment]
item | 4110
-- | --
class | 41107
