### ISSUE TITLE
Mapillary - traffic signs: animal crossing expects ways

### ISSUE THREAD

**Issue by fansanelli** [osm-fr/osmose-backend#963]
Hello,

I think there is a problem in the Mapillary analyzer in subject.

Please consider this example:

http://osmose.openstreetmap.fr/it/error/3ed68179-2775-d426-1c4f-09ae6d2a29a8

I created the node on the way:

https://www.openstreetmap.org/node/7685525782

But it is not detected, I think due to this row:

https://github.com/osm-fr/osmose-backend/blob/e5884a15012d3e1a0ec480f19b7128a8a4ece1a1/merge_data/mapillary-traffic-signs.mapping.json#L932

I am following this proposal to add them:

https://wiki.openstreetmap.org/wiki/Proposed_features/animal_crossing

Idk if someone else does something different....

Many thanks
Cheers
Francesco

**Comment by frodrigo** [comment]
This check is about the effect of traffic sign on the ways, not traffic sign them self.
