### ISSUE TITLE
Zone:maxspeed warning on bicycle road

### ISSUE THREAD

**Issue by limes11** [osm-fr/osmose-backend#964]
Dear all,

Osmose sends out a Level 1 issue "Probably missing tag zone:maxspeed=XX:30, according to the neighborhood" on a road with keys (among others) , hw=residential, bicycle_road=yes, maxspeed=30, source:maxspeed=DE:bicycle_road. For example, here https://www.openstreetmap.org/way/174638684

I like how Osmose finds missing zone:maxspeed tags on ways which carry only a maxspeed tag based on the neighbourhood. But bicycle roads are typically found in areas with zone:maxspeed restrictions. It really should not flag this up. 

Best, Limes

**Comment by frodrigo** [comment]
I'm not familiar with `bicycle_road=yes`, never see one.
You want to exclude this kind of highway from surrounding maxspeed zone? When other vehicle than bicycle are allowed, the maxspeed zone does not apply?

**Comment by limes11** [comment]
I can only speak for the situation in Germany, which is where these tags are predominantly used. There are some in other European countries, but even the English wiki only describes the German case.

"You want to exclude this kind of highway from surrounding maxspeed zone?"

Exactly. It is an additional tag to ways with (almost always) hw=residential/service. These roads are usually surrounded by lots of other roads which carry a zone:maxspeed restriction, but such restrictions do not apply on ways with bicycle_road=yes. There, by law, the maxspeed is 30 for all vehicles (that are allowed), which is usually explicitly tagged on these ways. To indicate the maxspeed source, German mappers should (and most often do) add source:maxspeed=DE:bicycle_road.

My suggestion on ways with bicycle_road=yes:

- If there are no tags such as zone:maxspeed, source:maxspeed or maxspeed:type but the neighborhood suggests such a tag, then it should be flagged up.

- If there is such a tag (most likely source:maxspeed=DE:bicycle_road), then Osmose should not flag up a missing zone:maxspeed value. Hardcoding the "source:maxspeed=DE:bicycle_road" case will probably solve almost all of these issues.

Best, Limes

**Comment by frodrigo** [comment]
Since for now it is a German tag, I prefer make it a specific rule for Germany based on `bicycle_road=yes` tag.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.739861&lon=7.093139&item=2xxx&level=1%2C2%2C3&tags=&fixable=
http://osmose.openstreetmap.fr/en/error/077ad581-cb3f-b7f3-5065-1b568ca00dd6
http://osmose.openstreetmap.fr/en/error/df8db054-9df8-0be0-3155-34b269b20dc8
