### ISSUE TITLE
Possible missing direction tag on stop or a give way

### ISSUE THREAD

**Issue by carlosarc87** [osm-fr/osmose-backend#965]
Item: 2090
Class: 4

It should not be shown as an error when _traffic_sign:forward=* / traffic_sign:backward=*_ exists.

Wiki: https://wiki.openstreetmap.org/wiki/Key:traffic_sign#As_part_of_a_way

Examples:
http://osmose.openstreetmap.fr/en/error/c44ca7f3-da61-8b7e-1768-1ac9d104c941
http://osmose.openstreetmap.fr/en/errors/?country=spain_andalucia&item=2090&level=1%2C2%2C3

Regards

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/es/errors/?country=spain*&item=2090&class=4
http://osmose.openstreetmap.fr/es/errors/graph.png?country=spain*&item=2090&class=4
