### ISSUE TITLE
Similar values for source:geometry:ref= should be ignored in Belgium_Flanders

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-backend#966]
Hi,

There seem to be a lot of issues in 'Similar Values' in Belgium (flanders specifically) which should be showing up.
`source:geometry:ref=` is the tag used for matching buildings to the official Flanders building register which sometimes means multiple values. And these do look similar, but shouldn't raise an issue in Osmose

http://osmose.openstreetmap.fr/en/errors/?source=3727&item=3060&limit=5000&class=30601

Examples:
```
source:geometry:ref = Gbg/5876221;Gbg/5876266;Gbg/5876267;Gbg/5876253

source:geometry:ref=Gbg/359443;Gba/552391;Gba/552393
```

Cheers,
Thibault

**Comment by thibaultmol** [comment]
Also, `source:geometry:date` comes up very often in this issue.

For context, both are these related to the importing system of Flanders AIV GRB buiding's database https://wiki.openstreetmap.org/wiki/AIV_GRB_building_import/Import_plan

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?country=belgium*&item=3060&class=30601
http://osmose.openstreetmap.fr/fr/errors/graph.png?country=belgium*&item=3060&class=30601
