### ISSUE TITLE
4130 duplicated wikipedia - issues keep reappearing

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#967]
These issues reappear all the time. I close them and after few days they appear again. Sometimes there are situations when one Wikipedia article describes multiple objects, it's not 1-1 relation, so it's correct to mark them as false alarms.

**Comment by frodrigo** [comment]
See also #884

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=4130&class=1
Switch it concerns multiple objects, it may be switch from one object to an other one.

**Comment by frodrigo** [comment]
Fasle positives may reaper this days. But now I hope they could be marked as false positive for good.
