### ISSUE TITLE
Similar values for addr:flats should be ignored

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-backend#968]
Hi,

Seems like a lot of `addr:flats` tags are being listed under this issue as well, which is to be expected but shouldn't be happening.
Ex:
1-2;101-102;201-202;301-302
1;6;101-102;201-202;301;401-402

(Housenumber tag also has this issue show a lot. Yet this often happens:
ex:
12A-12D;12F-12K
112-164;166-174
)

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?country=belgium*&item=3060&class=30601
http://osmose.openstreetmap.fr/fr/errors/graph.png?country=belgium*&item=3060&class=30601
