### ISSUE TITLE
In France  traffic_sign = city_limit

### ISSUE THREAD

**Issue by operon** [osm-fr/osmose-backend#97]
In France, the cities are limited by signs EB10 and EB20.
These signs must be installed:
- On the main roads (primary, secondary, tertiary)
- At limits or sides of a constructed area (landuse = residential)
  Osmose could detect the landuse = residential where there are admin_centre and test that next (100m) contour landuse = residential and / or next (20m) of the main roads there is a traffic_sign = city_limit

**Comment by frodrigo** [comment]
Do you already found issues with this traffic sign ? This is lot of computation to check that, I'm not sure if really useful.

**Comment by operon** [comment]
The official definition of the urban area is important, it defined:
- Municipal police authority area
- Parking rule
- maximum speed
- Display advertising commecial
- ...

**Comment by frodrigo** [comment]
> On the main roads (primary, secondary, tertiary)

I think in practice the sign can be on any highway level.

> At limits or sides of a constructed area

This one can be done, if you think this is still usefull.

I'm still uncertain about utility.

http://overpass-turbo.eu/s/in1
