### ISSUE TITLE
`strassen-nrw:abs` still keeps appearing as a bad tag

### ISSUE THREAD

**Issue by Identitaet** [osm-fr/osmose-backend#970]
Bad tag
item | 3050
class | 3050
[Here](https://osmose.openstreetmap.fr/de/map/#item=xxxx&zoom=18&lat=51.38639&lon=7.082909&level=1%2C2%2C3&tags=&fixable=)

The weird thing is that this tag should already be on the whitelist since about 2 years in #175 
but it still keeps appearing

**Comment by frodrigo** [comment]
https://github.com/frodrigo/osmose-backend/blob/master/plugins/TagFix_BadKey.py#L61

**Comment by frodrigo** [comment]
Duplicate #791
