### ISSUE TITLE
Monument historique sans attribut “ref:mhs” ou incorrect

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#973]
item |class
-- | --
7080             monument | 2

Error seen here:
https://osmose.openstreetmap.fr/fr/error/3eac78c7-73cd-ec25-89f1-574c2cfd8c34

The ref exists and is correct. Is it a false positive or is something wrong?

**Comment by frodrigo** [comment]
heritage:operator | mhs |  
-- | -- | --
mhs:inscription_date | 2017-04-15 |  
ref:mhs | PA29000083 | http://www.culture.gouv.fr/public/mistral/mersri_fr?ACTION=CHERCHER&FIELD_1=REF&VALUE_1=PA29000083

**Comment by frodrigo** [comment]
There is no location for PA29000083 in the opendatafile.
Just mark it as false positive.
