### ISSUE TITLE
false positives: "Object tagged twice as way and relation"

### ISSUE THREAD

**Issue by camelCaseSucks** [osm-fr/osmose-backend#974]
At high schools in the US, it's very common to have a running track (multipolygon relation) with a football or soccer field (way) inside of it. These are being reported as "an object" tagged twice, when it is meant to be two separate objects. This could be avoided if Osmose ignored leisure=pitch objects with different sport=* tags.

https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.561647&lon=-122.671337&item=4080
https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.540249&lon=-122.579176&item=4080

**Comment by frodrigo** [comment]
item | 4080
-- | --
class | 2

**Comment by Olyon** [comment]
The running track should be tagged with leisure=track instead of leisure=pitch (https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dtrack) and there would be no more errors with 2 different tags, a leisure=track and a leisure=pitch.

**Comment by frodrigo** [comment]
@c

**Comment by frodrigo** [comment]
@camelCaseSucks Reopen if required.
