### ISSUE TITLE
How to transfer suggested tags on another entity

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osmose-backend#976]
Hello,

Osmose suggests to add different tags on a wrong amenity.
The right target is 200 meters in the west. I would like to be able to copy-paste the seven suggested tags on the right amenity without modifying the wrong one. Is there a workaround to easily do that ?

https://osmose.openstreetmap.fr/fr/map/#zoom=17&lat=47.764855&lon=-2.131992&item=8341

Thanks.

**Comment by frodrigo** [comment]
Yes, just copy-paste! Copy from osmose popup and paste them using eg. JOSM.

**Comment by zorglubu** [comment]
I had tried, without success. But, yes, it works ! It's too easy.
Thanks. Désolé pour le dérangement.  ;-)
