### ISSUE TITLE
Errors that are irrelevant because of 3d building?

### ISSUE THREAD

**Issue by thibaultmol** [osm-fr/osmose-backend#977]
Hi,

Detailed 3d buildings like this:
https://www.reddit.com/r/openstreetmap/comments/iwlezz/i_3d_mapped_the_trilogy_of_athens/
![image](https://user-images.githubusercontent.com/1010226/93764576-a7eb1100-fc13-11ea-90b1-112b945710d3.png)
https://demo.f4map.com/#lat=37.9808081&lon=23.7337054&zoom=18&camera.phi=4.872

Seem to cause a lot of errors in Osmose that don't really seem justified in this situation: 
http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=37.980703&lon=23.733708&item=xxxx&level=1%2C2%2C3&tags=&fixable=

![image](https://user-images.githubusercontent.com/1010226/93764654-c4874900-fc13-11ea-9b68-4d9a9a0ef1a2.png)

Mainly errors like this:
```
Invalid polygon
Self-intersection[23.7341334 37.9799547]
```

**Comment by frodrigo** [comment]
Why do you think this issues are invalid? There is bad geom in these buildings.

**Comment by thibaultmol** [comment]
Because of course these polygons will overlap, it's a 3d building. There's no way to 3d map a building like this without having some polygons overlap

**Comment by frodrigo** [comment]
Eg Self-intersection it is by polygon, not by building.

**Comment by thibaultmol** [comment]
Oh, is it because of this:
![image](https://user-images.githubusercontent.com/1010226/93770353-5dba5d80-fc1c-11ea-8d7c-e02ea1365831.png)
on way 848666393 for example
?

Hadn't noticed those corners yet
