### ISSUE TITLE
1080 Orphan nodes cluster

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#979]
For issues 1080 Orphan nodes cluster there isn't any link to an OSM feature (node, way, relation), like in other issues, so it's difficult to find the feature to fix.

**Comment by frodrigo** [comment]
We cannot point all nodes (lot of objects).
May be have a better title/doc?

**Comment by maro-21** [comment]
Is there always a group of nodes? When I checked a random place, there was only one.
If you don't want to have a separate issue for a every single node, we can either:
- link to one of the nodes and write how many are there around this one,
- list all of the nodes if there are less than 10.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_orphan_nodes_cluster.py

Maybe at least 3 (but probably more to have limit area), and we does not have the number.
