### ISSUE TITLE
False positive: "almost junction" reported on path ending on public_transport=platform

### ISSUE THREAD

**Issue by smootheFiets** [osm-fr/osmose-backend#980]
http://osmose.openstreetmap.fr/en/error/fc06de4d-b010-a9bc-66d0-20fab9dd988e

This is a path (520637868) ending on a bus stop (public_transport=platform).  This particular bus stop is a way, bus stops can also be nodes.

Osmose detects, correctly, that the path stops near the neighboring secondary (6486586) and throws issue "almost junction".

I don't think this should be flagged, though: pedestrians will only walk to the bus stop, not on the road (which would be illegal in this case).  The last few cm, between platform and boarding the bus, are not mapped explicitly in OSM.  I expect that the situation will be the same for other public-transport platforms, e.g., train platforms.  Discontinuities are _expected_ here, no issue should be raised. Public-transport platforms, while not part of the way network, are acceptable endpoints for pedestrian-accessible ways.

So, I propose that an if statement (or analog) is introduced in the code, along the lines of 
"is the node at the end of the highway tagged as public_transport=platform or is it part of a way tagged as public_transport=platform?  If the highway is accessible to pedestrians, no almost-junction issue for this end of the highway"

PS: I see in the source code lines containing bus_stop and subway_entrace.   I don't speak SQL, but maybe this issue has been raised before for highway=bus_stop?  In that case, the fix may be as easy as adding public_transport=platform on the same footing?!?

PPS: this is my first Osmose issue. Sorry in advance if I didn't get the 'contributing guidelines' correctly.  Doing my best.

**Comment by frodrigo** [comment]
source | 27942
-- | --
item | 1270
class | 1

highway | path |  
-- | -- | --
smoothness | intermediate |  
surface | paving_stones

**Comment by frodrigo** [comment]
Ignore when connected to public_transport=platform.

**Comment by frodrigo** [comment]
Done, but only for node.
Please mark it on ways as false positive.
