### ISSUE TITLE
3080 swimming pool

### ISSUE THREAD

**Issue by debyos** [osm-fr/osmose-backend#985]
Hi,

it seems that the descriptions to [item 3080 swimming pool](https://wiki.openstreetmap.org/wiki/Osmose/issues) are somewhat outdated. They encourage to use amenity=swimming_pool and landuse=pond, now considered deprecated by the OSM wiki.
Please, try to correct it.
Thanks

debyos

**Comment by frodrigo** [comment]
Note the documentation of Osmose is no more on the wiki. It is now on the source code.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_natural_swimming-pool.py#L85-L93

Please suggest a new doc content.

**Comment by debyos** [comment]
Dear Frédéric,

thank you for your quick answer. I suggest following:

Change the tag `natural=water` in `leisure=swimming_pool`. If it is private then tag it also with `access=private`. If it is actually not a swimming pool then you can use e.g. `natural=water` + `water=pond`/`water=basin`.

Kind regards,

Gábor
