### ISSUE TITLE
Internal server error on fix-edit save

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-backend#99]
The current version deployed on http://osmose.openstreetmap.fr/ does not allow me to save the changes made with the integrated fixed-edit editor, I have always a 500 error in Firefox 43.0.4 MacOSX. I can provide a log if needed.

**Comment by bagage** [comment]
This is related to #88: there is only an issue with my account which contains a space in it. Possible regressions from #88's fix?

**Comment by frodrigo** [comment]
Can you provide a log if you have one ? (btw, this is a frontend issiue)

**Comment by bagage** [comment]
Is Firefox HAR (HTTP ARchive format) enough? Here is [one](http://pastebin.com/XRZPEN9S).

**Comment by frodrigo** [comment]
Fixed
