### ISSUE TITLE
False Positive: Conditional intervals does not fit into opening hours

### ISSUE THREAD

**Issue by ivanrome** [osm-fr/osmose-backend#991]
Hello
It's seems it's a false positive with the rule "Conditional intervals does not fit into opening hours"

[Here is an example](https://www.openstreetmap.org/relation/7842094)

We can see these values: 
```
interval:conditional= 7 @ (Sa-Su 06:00-00:00); 15 @ (Mo-Su 00:00-01:30)
opening_hours=Mo-Su 06:00-01:30
```
It seems OK coditional times are in the interval of the opening_hours.
Could you fix this?
Regards

**Comment by frodrigo** [comment]
Could you give an Osmose link, please.

**Comment by ivanrome** [comment]
http://osmose.openstreetmap.fr/en/errors/?zoom=17&item=3250&level=1%2C2%2C3&tags=&fixable=&limit=500&bbox=-3.7471854686737065%2C40.39843521596058%2C-3.7384951114654545%2C40.402066953950595

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/error/338dd98a-185a-8f64-182f-7da2ec21b5c5


item | 3250
-- | --
class | 32502


https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_IntervalConditional.py

cc @PanierAvide

**Comment by PanierAvide** [comment]
Which version of transporthours python library is deployed in production ? Is it the latest 0.0.4 ? Because I can't reproduce the issue locally with latest version.

**Comment by frodrigo** [comment]
Probably the 0.0.2

cc @jocelynj or @Marc-marc-marc

**Comment by jocelynj** [comment]
Yes, it is 0.0.2, installed from ansible. I will take a look at updating it.

**Comment by ivanrome** [comment]
Hello, some information. I've updated the value of interval:conditional for the relationship from  about the [relationship](https://www.openstreetmap.org/relation/7842094)

Before:
interval:conditional= 7 @ (Sa-Su 06:00-**00:00**); 15 @ (Mo-Su **00:00**-01:30)

After
interval:conditional: 7 @ (Sa-Su 06:00-**24:00**); 15 @ (Mo-Su **00:00**-01:30)

The errror is gone. Maybe it's not accurate to mark 24:00 for midnight only in certain cases.

**Comment by frodrigo** [comment]
Update to 0.0.4 done.
