### ISSUE TITLE
False positive: Mauvais suffixe de clé Concerns tag: `ref:clochers.org=92048g`

### ISSUE THREAD

**Issue by williamdes** [osm-fr/osmose-backend#993]
http://osmose.openstreetmap.fr/fr/error/41cb7031-95b2-4ff7-e9f6-50bf30446c2d

https://wiki.openstreetmap.org/wiki/User:FrViPofm/Place_of_worship

**Comment by frodrigo** [comment]
Yes '.' is not allowed here.

**Comment by williamdes** [comment]
But, this is a valid and used key .. :thinking:

**Comment by williamdes** [comment]
See https://taginfo.openstreetmap.org/keys/?key=ref%3Aclochers.org#overview

**Comment by williamdes** [comment]
@frodrigo I think you closed this issue too quickly ?

**Comment by frodrigo** [comment]
It is not an Osmose issue, it is a data issue. See #948.
