### ISSUE TITLE
amenity={{1.value}}

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#994]
After today's changes, some issues titles look like this:

9001001: `parking without amenity={{1.value}}`
9001002: `tracktype=grade2 together with surface={{1.value}}`
9001002: `highway=living_street together with maxspeed={{1.value}}`

Yesterday it was ok.

**Comment by frodrigo** [comment]
I did not found such issue. Please include more detail, sample issue and links.

In more general way, thank to take time me make issues on githib, but please, include more details, such as an osmose link to an issue.

**Comment by maro-21** [comment]
http://osmose.openstreetmap.fr/pl/errors/?item=9001

**Comment by maro-21** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=9001

**Comment by frodrigo** [comment]
Please exact issue, not all have the issue you ask for
http://osmose.openstreetmap.fr/en/map/#item=9001&zoom=12&lat=51.2766&lon=17.6007&level=1%2C2%2C3&tags=&fixable=

**Comment by frodrigo** [comment]
Please, reopen if problem is still here.

**Comment by maro-21** [comment]
![osmose](https://user-images.githubusercontent.com/57260466/97634580-3e41fc00-1a36-11eb-876b-5916500cb1d2.png)

**Comment by frodrigo** [comment]
Please a link. I need item, class and in this case subclass id.

**Comment by maro-21** [comment]
Everything is my first message...
http://osmose.openstreetmap.fr/pl/error/17bab5a0-9fc3-c83d-2734-62d54c49884e
http://osmose.openstreetmap.fr/pl/error/006ce2f3-533a-9e7a-bc11-b8c4db8572d6
http://osmose.openstreetmap.fr/pl/error/affb9877-4d43-e7fc-40da-1e8b8843f8c4

**Comment by frodrigo** [comment]
Thank you. But now I have object id and can extract subclass id.

**Comment by frodrigo** [comment]
So, this issue append when the tag value is a regex, and the message use "{1.tag}". While it works for non regex value.
```css
*[parking][amenity!~/^(parking|parking_space|parking_entrance|motorcycle_parking)$/]                                                                                                                  
```
```python
err.append({'class': 9001001, 'subclass': 641101944, 'text': mapcss.tr('{0} without {1}', mapcss._tag_uncapture(capture_tags, '{0.key}'), mapcss._tag_uncapture(capture_tags, '{1.tag}'))})                                    

```
