### ISSUE TITLE
9001001: sport without physical feature

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#995]
Can we add `amenity=bar` to the list?
https://github.com/osm-fr/osmose-backend/blob/f78dac6f2fd6196b18172e017f7621705396fc0b/plugins/Josm_combinations.py#L738

Because tagging
`amenity=bar + sport=table_soccer` is correct.
http://osmose.openstreetmap.fr/en/error/1b2c75b3-b69c-3202-4130-4796c0d4ace4

Another thing: tagging `highway=pedestrian + area=yes + sport` should be acceptable too. This is a large square where people are skating, cycling so it is a physical object.
http://osmose.openstreetmap.fr/en/error/f4f57927-6a5c-5384-7f1c-997ff5ffe517

**Comment by frodrigo** [comment]
cc @Klumbumbus

**Comment by Klumbumbus** [comment]
Fixed in JOSM in https://josm.openstreetmap.de/changeset/17091.
