### ISSUE TITLE
Analyser_osmosis configurable by XML file

### ISSUE THREAD

**Issue by marcu** [osm-fr/osmose-backend#996]
I need to be able to create / configure a set of analyzers via forms. The idea is to be able to correct / adapt a query if needed.

My proposal would be that the tool would generate for each analyzer an xml like this 

``` xml
<requests>
    <category>1203</category>
    <description>blop blop blop</descriptopn>
    <request>
        <name>emprise_gare</name>
        <obj>relations</obj>
        <geom>polygone</geom>
        <rule>
            <and>
                <has_tag>public_transport</has_tag>
                <key_value>public_transport=stop_area</key_value>
                <has_tag>network</has_tag>
                <or>
                    <key_value>network=Transilien</key_value>
                    <key_value>network=SNCF</key_value>
                </or>
            </and>
        </rule>
    </request>
    <request>
        <name>emprise_gare_buffer_150</name>
        <obj>emprise_gare</obj>
        <geom>polygone</geom>
        <rule>
            <buffer>150</buffer>
        </rule>
    </request>
    <request>
        <name>end</name>
        <obj>nodes</obj>
        <rule>
            <and>
                <or>
                    <key_value>highway=bus_stop</key_value>
                    <key_value>highway=platform</rukey_valuele>
                </or>
                <has_not_tag>name</has_not_tag>
                <contained>emprise_gare_buffer_150</contained>
            </and>
        </rule>
    </request>
</requests>
```

This xml file would be deposited in the `/opt/osmose-backend/work/xml-analysers/` folder (dedicated to these analysers).

A analyzer named `analyser_osmosis_xml.py` would read each xml file and execute the sql query(s) configured by the file.

For the xml example the sql / python part would be : 

``` python
sql['emprise_gare'] =  """
CREATE TEMP TABLE IF NOT EXISTS emprise_gare AS
SELECT
    relations.id AS id,
    ST_Buffer(ST_Polygonize(ways.linestring), 0) AS geom
FROM
    relations
    JOIN relation_members ON
        relation_members.relation_id = relations.id AND
        relation_members.member_type = 'W'
    JOIN ways ON
        ways.id = relation_members.member_id AND
        ST_NPoints(ways.linestring) > 1
WHERE
    ( relations.tags?'public_transport' AND
      relations.tags->'public_transport' = 'stop_area' AND
      relations.tags?'network' AND
      ( relations.tags->'network' = 'Transilien' OR relations.tags->'network' = 'SNCF' )
);"""

sql['emprise_gare_buffer_150'] = """
CREATE TEMP TABLE IF NOT EXISTS emprise_gare_buffer_150 AS
SELECT
    emprise_gare.id AS id,
    ST_Buffer(emprise_gare.geom, 150) AS geom
FROM
    emprise_gare
"""

sql['end'] = """
SELECT
    nodes.id AS id,
    nodes.geom AS geom
    FROM
      nodes, 
      emprise_gare_buffer_150
    WHERE
    ( ( nodes.tags->'highway'='bus_stop' OR 
        nodes.tags->'highway'='platform' )  AND
         not nodes.tags?'name'  AND
         ST_Contains(emprise_gare_buffer_150.geom, nodes.geom)
   ) )
"""
```
and the analysis part (inside `analyser_osmosis_common`)

``` python
    def __init__(self, config, logger = None):
        self.class[1203] = self.def_class( .... )

        # + pour autres fichiers xml


    def analyser_osmosis_common(self):

         self.run(sql["emprise_gare"])
         self.run(sql["sql_emprise_gare_buffer_150"])
         self.run(sql["end"], callback) # call back défini en fonction de l'obj (nodes, relations ou ways)

         # + sql pour autres fichiers xml
```

**Comment by frodrigo** [comment]
Query like this can be done using MapCSS and spatial operator.

I would prefer implement the missing part of the MapCSS generator rather than implementing a new generator and file format. All part of the JOSM validator in MapCSS using spatial operators would benefit from this implementation.

Nevertheless implement of the missing part of MapCSS could me more complex than write a new generator, as it could be more generic.

@PanierAvide already proposed an other way to generate analyser but dedicated to merge of Opendata. This kind of analyzer could not be done using MapCSS.

**Comment by marcu** [comment]
Hello,

Here is the first version of the analyser : https://github.com/marcu/osmose-backend/commit/79363390cd90999733ed02c8bc504d0ef62f0719

The commit contains two files : 
- analysers/analyser_osmosis_xml.py : the code of the xml analyser
-  analysers/xml-analysers/example.xml : an example of an xml file that describe an analyser, each xml file in its containing folder will be considarated as an xml configuration of an analyser. for the moment it is possible to use buffers in the requests.

**Comment by frodrigo** [comment]
Look at merge json config file, it may inspire you.

**Comment by marcu** [comment]
Can you be more specific ? Which file ? Which method ?

**Comment by frodrigo** [comment]
Eg, one of the most complete
https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json
