### ISSUE TITLE
3092: some invalid phone numbers aren't marked

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#997]
#3092 phone numer

For Poland there should be +48 prefix + 9 digits. I found some invalid phone numbers which weren't found by Osmose:
071-373-00-00
071 345 52 16
+48 79 -000 333
(071) 322-15-48
0 71 326 64 55
3442082
71 324 17 16;601 667 208

**Comment by frodrigo** [comment]
Please can you add an osmose link

https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L1318-L1319

Can you try to make a pull request for add a test for Poland and the end :
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Phone.py#L320

**Comment by frodrigo** [comment]
Please reopen if you have more details.

**Comment by maro-21** [comment]
* I'm not able to reopen issues.
* I added as many details as I could - I listed 7 different phone numbers which weren't detected by Osmose.
* I can't give you any Osmose link becasue there isn't any. As I wrote, these numbers WERE NOT marked by Osmose.

**Comment by frodrigo** [comment]
Please, give a link like this one
http://osmose.openstreetmap.fr/en/map/#zoom=11&lat=54.4546&lon=18.7667&item=3092&level=1%2C2&tags=&fixable=

**Comment by frodrigo** [comment]
Please some osm id object eg.

**Comment by maro-21** [comment]
There aren't because I fixed them. First I fixed all Osmose issues with phone numbers and then I found all the phones with overpass.

**Comment by frodrigo** [comment]
When there is no data, it is harder to find bug. So, I will not until new
bad data will be available.
