### ISSUE TITLE
Question about 3030 tagwatch cleaner

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#998]
Issue: 3030, class: 737787355

Could you explain this issue?
`tag value: shop=hunting => shop=outdoor;hunting (rule ks_vs)`
http://osmose.openstreetmap.fr/en/error/273c31b1-17c1-1d0f-cf03-a3394b8a14bd
Why does it suggest changing shop=hunting to shop=outdoor;hunting (which is invalid)
and what does "ks_vs" mean?

**Comment by frodrigo** [comment]
As explained in the doc, this rule come from this wiki page, and can be edited
https://wiki.openstreetmap.org/wiki/User:FrViPofm/TagwatchCleaner

This rules can be show as early version of MapCSS contrib files. And probably should be curated and migrated to MapCSS.

**Comment by maro-21** [comment]
So to fix it on Osmose, I should fix it on the Wiki?

And what does "ks_vs" mean?

**Comment by frodrigo** [comment]
Yes, fix it on the wiki.

ks_vs, not sure, maybe "key versus"
